-- ============================================================
-- Soru Partisi 14 — 500 soru
--   tarih 100 · cografya 200 · edebiyat 200
--
-- Kalite: tek ve tartışmasız doğru cevap; zamanla değişen bilgi yok;
-- mevcut havuza (parti 13 dahil) karşı tekrar taraması yapıldı.
-- Migration sonunda YALNIZ bu partinin şıkları karıştırılır.
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- ===================== TARİH (100) =====================
('Sümerlerde yazının kullanıldığı malzeme neydi?', '["Kil tablet","Papirüs","Parşömen","Kâğıt"]'::jsonb, 0, 'tarih'),
('Mısır''da papirüs neyden yapılırdı?', '["Hayvan derisinden","Bitki sapından","Kilden","Taştan"]'::jsonb, 1, 'tarih'),
('Parşömen hangi malzemeden üretilirdi?', '["Kil","Bitki lifi","Hayvan derisi","Cam"]'::jsonb, 2, 'tarih'),
('Bergama Krallığı hangi buluşla anılır?', '["Pusula","Cam üfleme","Barut","Parşömen"]'::jsonb, 3, 'tarih'),
('Fenikelilerin en önemli katkısı nedir?', '["Alfabe","Tekerlek","Para","Takvim"]'::jsonb, 0, 'tarih'),
('İlk güneş takvimini yapan uygarlık hangisidir?', '["Sümer","Mısır","Hitit","Roma"]'::jsonb, 1, 'tarih'),
('Asurlular hangi alanda öne çıkmıştır?', '["Cam sanatı","Denizcilik","Ticaret kolonileri","Matbaa"]'::jsonb, 2, 'tarih'),
('Anadolu''ya yazıyı getiren topluluk hangisidir?', '["Yunanlar","Persler","Romalılar","Asurlular"]'::jsonb, 3, 'tarih'),
('Persler''in ünlü yol ağı hangisidir?', '["Kral Yolu","İpek Yolu","Baharat Yolu","Kehribar Yolu"]'::jsonb, 0, 'tarih'),
('Antik Yunan''da tarihin babası sayılan kişi kimdir?', '["Homeros","Herodot","Sokrates","Thales"]'::jsonb, 1, 'tarih'),
('Tıbbın babası sayılan antik hekim kimdir?', '["Aristoteles","Galen","Hipokrat","Pisagor"]'::jsonb, 2, 'tarih'),
('Antik Yunan''da geometrinin gelişimine katkı yapan kişi kimdir?', '["Perikles","Herodot","Sofokles","Öklid"]'::jsonb, 3, 'tarih'),
('Arşimet hangi şehirde yaşamıştır?', '["Sirakuza","Atina","Roma","İskenderiye"]'::jsonb, 0, 'tarih'),
('Roma''da imparatorluk öncesi yönetim biçimi neydi?', '["Monarşi","Cumhuriyet","Teokrasi","Feodalite"]'::jsonb, 1, 'tarih'),
('Roma''nın efsanevi kurucuları kimlerdir?', '["Aeneas ve Dido","Kastor ve Polluks","Romulus ve Remus","Numa ve Tullus"]'::jsonb, 2, 'tarih'),
('Sezar''ın öldürülmesi hangi yılda gerçekleşmiştir?', '["MÖ 27","MÖ 100","MS 14","MÖ 44"]'::jsonb, 3, 'tarih'),
('Roma İmparatorluğu''nda Hristiyanlığı serbest bırakan ferman hangisidir?', '["Milano Fermanı","Nantes Fermanı","Tanzimat","Magna Carta"]'::jsonb, 0, 'tarih'),
('Kavimler Göçü hangi yüzyılda başlamıştır?', '["1. yüzyıl","4. yüzyıl","8. yüzyıl","12. yüzyıl"]'::jsonb, 1, 'tarih'),
('Orta Çağ''da manastırların işlevlerinden biri neydi?', '["Vergi toplamak","Ordu kurmak","El yazması çoğaltmak","Liman işletmek"]'::jsonb, 2, 'tarih'),
('Haçlı Seferleri kaç yüzyıl sürmüştür (yaklaşık)?', '["On yüzyıl","Bir yıl","Beş yüzyıl","İki yüzyıl"]'::jsonb, 3, 'tarih'),
('Endülüs''ün bilime katkısı hangi yolla Avrupa''ya geçti?', '["Çeviri hareketleri","Savaşlar","Denizcilik yalnızca","Ticaret yasağı"]'::jsonb, 0, 'tarih'),
('Beytü''l Hikme hangi şehirde kurulmuştur?', '["Kahire","Bağdat","Şam","Kurtuba"]'::jsonb, 1, 'tarih'),
('Gutenberg''in matbaası neyi hızlandırdı?', '["Tarımı","Savaşları","Bilginin yayılmasını","Madenciliği"]'::jsonb, 2, 'tarih'),
('Reform hareketini başlatan kişi kimdir?', '["Zwingli","Jean Calvin","Erasmus","Martin Luther"]'::jsonb, 3, 'tarih'),
('Reform sonucunda ortaya çıkan mezheplerden biri hangisidir?', '["Protestanlık","Katoliklik","Ortodoksluk","Kıptilik"]'::jsonb, 0, 'tarih'),
('Rönesans''ın öncü şehirlerinden biri hangisidir?', '["Londra","Floransa","Moskova","Lizbon"]'::jsonb, 1, 'tarih'),
('Coğrafi Keşiflerde Portekiz''in öncüsü kim sayılır?', '["Magellan","Kolomb","Denizci Henri","Cortes"]'::jsonb, 2, 'tarih'),
('Amerika kıtasına adını veren kişi kimdir?', '["Cabot","Kristof Kolomb","Macellan","Amerigo Vespucci"]'::jsonb, 3, 'tarih'),
('Aztek İmparatorluğu''nu yıkan İspanyol komutan kimdir?', '["Hernan Cortes","Francisco Pizarro","Vasco da Gama","Balboa"]'::jsonb, 0, 'tarih'),
('İnka İmparatorluğu''nu yıkan İspanyol komutan kimdir?', '["Hernan Cortes","Francisco Pizarro","Magellan","Cook"]'::jsonb, 1, 'tarih'),
('Otuz Yıl Savaşları hangi yüzyılda yaşanmıştır?', '["19. yüzyıl","15. yüzyıl","17. yüzyıl","13. yüzyıl"]'::jsonb, 2, 'tarih'),
('Aydınlanma düşünürlerinden Montesquieu neyi savunmuştur?', '["Kölelik","Mutlak monarşi","Teokrasi","Kuvvetler ayrılığı"]'::jsonb, 3, 'tarih'),
('Rousseau''nun ünlü eseri hangisidir?', '["Toplum Sözleşmesi","Devlet","Prens","Ütopya"]'::jsonb, 0, 'tarih'),
('Amerikan Bağımsızlık Bildirgesi hangi yıl yayımlanmıştır?', '["1789","1776","1804","1812"]'::jsonb, 1, 'tarih'),
('Fransız İhtilali''nin sloganında yer almayan kavram hangisidir?', '["Eşitlik","Özgürlük","Zenginlik","Kardeşlik"]'::jsonb, 2, 'tarih'),
('Sanayi Devrimi''nde buhar makinesini geliştiren kişi kimdir?', '["Rudolf Diesel","George Stephenson","Henry Ford","James Watt"]'::jsonb, 3, 'tarih'),
('İlk buharlı gemi hangi alanda devrim yaptı?', '["Deniz taşımacılığı","Tarım","Madencilik","Dokuma"]'::jsonb, 0, 'tarih'),
('Sömürgecilikte "hammadde kaynağı" arayışı hangi devrimle güçlendi?', '["Fransız İhtilali","Sanayi Devrimi","Rönesans","Reform"]'::jsonb, 1, 'tarih'),
('İtalyan birliğini sağlayan isimlerden biri kimdir?', '["Metternich","Bismarck","Garibaldi","Cavour''un rakibi yok"]'::jsonb, 2, 'tarih'),
('Alman birliğini sağlayan devlet adamı kimdir?', '["Metternich","Garibaldi","Napolyon III","Bismarck"]'::jsonb, 3, 'tarih'),
('Birinci Dünya Savaşı''nda İtilaf Devletleri''nden biri hangisidir?', '["Fransa","Almanya","Avusturya-Macaristan","Bulgaristan"]'::jsonb, 0, 'tarih'),
('Wilson İlkeleri hangi savaşın sonunda açıklanmıştır?', '["İkinci Dünya Savaşı","Birinci Dünya Savaşı","Kore Savaşı","Balkan Savaşları"]'::jsonb, 1, 'tarih'),
('Rusya''da 1917 Devrimi sonrası kurulan devletin adı nedir?', '["Rusya Krallığı","Rus İmparatorluğu","Sovyetler Birliği","Doğu Birliği"]'::jsonb, 2, 'tarih'),
('1929 Büyük Buhran hangi ülkede başlamıştır?', '["Fransa","İngiltere","Almanya","ABD"]'::jsonb, 3, 'tarih'),
('İkinci Dünya Savaşı''nda Mihver Devletleri''nden biri hangisidir?', '["İtalya","İngiltere","Fransa","SSCB"]'::jsonb, 0, 'tarih'),
('Birleşmiş Milletler Güvenlik Konseyi''nin daimî üye sayısı kaçtır?', '["10","5","15","3"]'::jsonb, 1, 'tarih'),
('Soğuk Savaş''ın sona ermesinin simgesi sayılan olay nedir?', '["Vietnam Savaşı","Kore Savaşı","Berlin Duvarı''nın yıkılması","Süveyş Krizi"]'::jsonb, 2, 'tarih'),
('Osmanlı''da ilk kez Batı tarzı elçilikler hangi dönemde açıldı?', '["Yavuz","Fatih","Kanuni","III. Selim"]'::jsonb, 3, 'tarih'),
('Osmanlı''da Lale Devri hangi antlaşmayla başlar?', '["Pasarofça","Karlofça","Zitvatorok","Küçük Kaynarca"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ilk kâğıt fabrikası hangi dönemde kuruldu?', '["Tanzimat","Lale Devri","Meşrutiyet","Kuruluş"]'::jsonb, 1, 'tarih'),
('Patrona Halil İsyanı hangi dönemi sona erdirdi?', '["Islahat","Tanzimat","Lale Devri","Meşrutiyet"]'::jsonb, 2, 'tarih'),
('Osmanlı''da "Vaka-i Hayriye" neyi ifade eder?', '["Islahat","Tanzimat''ın ilanı","Meşrutiyet","Yeniçeri Ocağı''nın kaldırılması"]'::jsonb, 3, 'tarih'),
('II. Mahmut döneminde kurulan ordunun adı nedir?', '["Asakir-i Mansure","Nizam-ı Cedid","Sekban-ı Cedid","Eşkinci"]'::jsonb, 0, 'tarih'),
('Tanzimat Fermanı''nı ilan eden padişah kimdir?', '["II. Mahmut","Abdülmecit","Abdülaziz","II. Abdülhamit"]'::jsonb, 1, 'tarih'),
('Kanun-i Esasi hangi padişah döneminde ilan edilmiştir?', '["Abdülaziz","Abdülmecit","II. Abdülhamit","V. Murat"]'::jsonb, 2, 'tarih'),
('Osmanlı''da Meclis-i Mebusan neyi temsil ediyordu?', '["Ulemayı","Padişahı","Orduyu","Halkın seçtiği meclisi"]'::jsonb, 3, 'tarih'),
('İttihat ve Terakki hangi dönemde etkili olmuştur?', '["II. Meşrutiyet","Tanzimat","Kuruluş","Lale Devri"]'::jsonb, 0, 'tarih'),
('Trablusgarp Savaşı hangi antlaşmayla sona ermiştir?', '["Berlin","Uşi","Bükreş","Atina"]'::jsonb, 1, 'tarih'),
('Balkan Savaşları sonucunda kaybedilen önemli şehir hangisidir?', '["Konya","Bursa","Selanik","Ankara"]'::jsonb, 2, 'tarih'),
('Edirne''nin geri alınması hangi savaşta gerçekleşti?', '["Çanakkale","I. Balkan Savaşı","Trablusgarp","II. Balkan Savaşı"]'::jsonb, 3, 'tarih'),
('Milli Mücadele''de Batı Cephesi komutanı kimdir?', '["İsmet Paşa","Kazım Karabekir","Fevzi Çakmak","Refet Bele"]'::jsonb, 0, 'tarih'),
('Doğu Cephesi''nde Ermenistan''la imzalanan antlaşma hangisidir?', '["Moskova","Gümrü","Kars","Ankara"]'::jsonb, 1, 'tarih'),
('Güney Cephesi''nde mücadele hangi devlete karşıydı?', '["Rusya","Yunanistan","Fransa","İtalya"]'::jsonb, 2, 'tarih'),
('TBMM''ye karşı çıkan ayaklanmaların bastırılması için kurulan mahkemeler hangisidir?', '["Meclis-i Ayan","Divan-ı Harp","Şura-yı Devlet","İstiklal Mahkemeleri"]'::jsonb, 3, 'tarih'),
('Teşkilat-ı Esasiye Kanunu hangi yıl kabul edilmiştir?', '["1921","1923","1924","1925"]'::jsonb, 0, 'tarih'),
('Cumhuriyet döneminde açılan ilk üniversite reformu hangi yıldadır?', '["1923","1933","1945","1950"]'::jsonb, 1, 'tarih'),
('Türkiye''de soyadı almadan önce kişiler nasıl anılırdı?', '["Meslekle yalnızca","Numarayla","Lakap ve baba adıyla","Şehirle"]'::jsonb, 2, 'tarih'),
('Atatürk''ün "Hayatta en hakiki mürşit ilimdir" sözü neyi vurgular?', '["Tarımı","Ticareti","Askerliği","Bilimin önceliğini"]'::jsonb, 3, 'tarih'),
('Türkiye''nin ilk nüfus sayımı hangi yıl yapılmıştır?', '["1927","1923","1935","1940"]'::jsonb, 0, 'tarih'),
('Türkiye''de ilk kadın pilot kimdir?', '["Halide Edip","Sabiha Gökçen","Afet İnan","Nezihe Muhiddin"]'::jsonb, 1, 'tarih'),
('Türkiye''de Latin harflerine geçişte kurulan okullara ne denirdi?', '["Enderun","Darülfünun","Millet Mektepleri","Medrese"]'::jsonb, 2, 'tarih'),
('Osmanlı''da yükseköğretim kurumu Darülfünun neye dönüştü?', '["ODTÜ","Ankara Üniversitesi","Boğaziçi","İstanbul Üniversitesi"]'::jsonb, 3, 'tarih'),
('Türkiye''de Medeni Kanun''un getirdiği önemli değişikliklerden biri nedir?', '["Tek eşlilik","Vergi artışı","Askerlik süresi","Toprak dağıtımı"]'::jsonb, 0, 'tarih'),
('Türkiye''de hafta tatili hangi güne alınmıştır (1935)?', '["Cuma","Pazar","Cumartesi","Perşembe"]'::jsonb, 1, 'tarih'),
('Türkiye''de ilk demir-çelik fabrikası nerede kurulmuştur?', '["Ereğli","Zonguldak","Karabük","İskenderun"]'::jsonb, 2, 'tarih'),
('Etibank ve Sümerbank hangi dönemde kurulmuştur?', '["1980 sonrası","Tanzimat","Meşrutiyet","Devletçilik dönemi"]'::jsonb, 3, 'tarih'),
('İkinci Dünya Savaşı''nda Türkiye''nin genel tutumu neydi?', '["Uzun süre tarafsızlık","Mihver''e katılım","İtilaf''a erken katılım","Savaş ilanı 1939"]'::jsonb, 0, 'tarih'),
('Türkiye''de çok partili hayata kalıcı geçiş hangi yıldadır?', '["1923","1946","1935","1960"]'::jsonb, 1, 'tarih'),
('Antik dönemde Efes''teki ünlü tapınak kime adanmıştı?', '["Apollon","Athena","Artemis","Zeus"]'::jsonb, 2, 'tarih'),
('Halikarnas Mozolesi hangi antik kentte bulunuyordu?', '["Bergama","Efes","Milet","Halikarnas"]'::jsonb, 3, 'tarih'),
('Antik dünyanın yedi harikasından İskenderiye Feneri ne işe yarardı?', '["Gemilere yol göstermek","Tapınak","Kütüphane","Saray"]'::jsonb, 0, 'tarih'),
('Truva''nın bulunduğu bölge bugün hangi ülkededir?', '["Yunanistan","Türkiye","İtalya","Bulgaristan"]'::jsonb, 1, 'tarih'),
('Bizans''ta Nika İsyanı hangi imparator döneminde olmuştur?', '["Herakleios","Konstantin","Justinianus","Basileios"]'::jsonb, 2, 'tarih'),
('Ayasofya''yı yaptıran Bizans imparatoru kimdir?', '["Herakleios","Konstantin","Teodosius","Justinianus"]'::jsonb, 3, 'tarih'),
('Haçlıların 1204''te yağmaladığı şehir hangisidir?', '["Konstantinopolis","Kudüs","Antakya","İskenderiye"]'::jsonb, 0, 'tarih'),
('Anadolu Selçuklularında ticaret yollarının güvenliği nasıl sağlanırdı?', '["Sur yapımı","Kervansaray ve sigorta sistemi","Deniz filosu","Vergi affı"]'::jsonb, 1, 'tarih'),
('Selçuklu mimarisinde taç kapı ne demektir?', '["Minare","Kubbe","Anıtsal giriş","Avlu"]'::jsonb, 2, 'tarih'),
('Osmanlı''da "millet sistemi" neyi düzenlerdi?', '["Ticaret vergisini","Ordu düzenini","Toprak dağıtımını","Dinî toplulukların iç işleyişini"]'::jsonb, 3, 'tarih'),
('Osmanlı''da narh ne demektir?', '["Fiyat sınırı","Vergi","Ceza","Ruhsat"]'::jsonb, 0, 'tarih'),
('Osmanlı''da vakıfların finansmanı neye dayanırdı?', '["Devlet bütçesi yalnızca","Bağışlanan gelir kaynakları","Dış borç","Ticaret vergisi"]'::jsonb, 1, 'tarih'),
('Osmanlı''da menzil teşkilatı ne işe yarardı?', '["Ordu eğitimi","Vergi toplama","Haberleşme ve ulaşım","Cami yapımı"]'::jsonb, 2, 'tarih'),
('Osmanlı''da tersane nerede kurulmuştur (başlıca)?', '["Yalova","Kadıköy","Üsküdar","Haliç"]'::jsonb, 3, 'tarih'),
('Piri Reis''in dünya haritasında hangi kıta yer alır?', '["Amerika kıyıları","Antarktika yalnızca","Avustralya","Grönland yalnızca"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ilk özel Türkçe gazete hangisidir?', '["Takvim-i Vekayi","Tercüman-ı Ahval","Ceride-i Havadis","İkdam"]'::jsonb, 1, 'tarih'),
('Osmanlı''da posta teşkilatı hangi dönemde modernleşti?', '["Lale Devri","Kuruluş","Tanzimat","Fetret"]'::jsonb, 2, 'tarih'),
('Türk tarihinde "Kut" anlayışı neyi ifade eder?', '["Askerlik görevi","Vergi hakkı","Toprak mülkiyeti","Yönetme yetkisinin tanrısal kaynağı"]'::jsonb, 3, 'tarih'),
('İlk Türk devletlerinde ikili teşkilat ne demektir?', '["Doğu-batı olarak yönetim","İki dinli yapı","İki başkent","İki ordu"]'::jsonb, 0, 'tarih'),
('Uygurların yerleşik hayata geçmesinin sonucu nedir?', '["Göçün artması","Şehir ve tapınak yapımı","Ordunun dağılması","Ticaretin bitmesi"]'::jsonb, 1, 'tarih'),
('Karahanlılar hangi dili resmî dil olarak kullanmıştır?', '["Farsça","Arapça","Türkçe","Soğdca"]'::jsonb, 2, 'tarih'),
('Gaznelilerin Hindistan seferlerinin sonucu nedir?', '["Anadolu''nun fethi","Çin''in fethi","Mısır''ın alınması","İslamiyetin yayılması"]'::jsonb, 3, 'tarih'),

-- ===================== COĞRAFYA (200) =====================
('Dünya''nın en büyük yarımadası hangisidir?', '["Arabistan","Anadolu","İber","İskandinav"]'::jsonb, 0, 'cografya'),
('Kızıldeniz hangi iki kıta arasındadır?', '["Avrupa ve Asya","Afrika ve Asya","Asya ve Avustralya","Afrika ve Avrupa"]'::jsonb, 1, 'cografya'),
('Karadeniz''i Marmara''ya bağlayan boğaz hangisidir?', '["Kerç","Çanakkale Boğazı","İstanbul Boğazı","Cebelitarık"]'::jsonb, 2, 'cografya'),
('Marmara Denizi''ndeki en büyük ada hangisidir?', '["Heybeliada","Büyükada","Avşa","Marmara Adası"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en büyük ovalarından Konya Ovası hangi bölgededir?', '["İç Anadolu","Akdeniz","Ege","Marmara"]'::jsonb, 0, 'cografya'),
('Türkiye''de en fazla buğday üretilen bölge hangisidir?', '["Karadeniz","İç Anadolu","Doğu Anadolu","Marmara"]'::jsonb, 1, 'cografya'),
('Bafra ve Çarşamba ovaları hangi nehirlerin deltalarıdır?', '["Sakarya ve Meriç","Fırat ve Dicle","Kızılırmak ve Yeşilırmak","Ceyhan ve Seyhan"]'::jsonb, 2, 'cografya'),
('Türkiye''de en fazla fındık üretilen bölge hangisidir?', '["Marmara","Ege","Akdeniz","Karadeniz"]'::jsonb, 3, 'cografya'),
('Türkiye''de çay tarımının yapıldığı iklim özelliği nedir?', '["Bol yağış ve ılıman sıcaklık","Kuraklık","Aşırı soğuk","Çöl iklimi"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en uzun kıyı şeridine sahip olduğu deniz hangisidir?', '["Karadeniz","Akdeniz","Ege","Marmara"]'::jsonb, 1, 'cografya'),
('Ege kıyılarında kıyı uzunluğunun fazla olmasının sebebi nedir?', '["Yüksek dağlar","Düz kıyı","Girintili çıkıntılı yapı","Delta ovaları"]'::jsonb, 2, 'cografya'),
('Türkiye''nin en büyük akarsu havzası hangisidir?', '["Susurluk","Sakarya","Kızılırmak","Fırat-Dicle"]'::jsonb, 3, 'cografya'),
('Van Gölü''nün suyunun özelliği nedir?', '["Sodalı ve tuzlu","Tatlı","Asidik","Şekerli"]'::jsonb, 0, 'cografya'),
('Tuz Gölü''nün ekonomik önemi nedir?', '["Balıkçılık","Tuz üretimi","Ulaşım","Enerji"]'::jsonb, 1, 'cografya'),
('Türkiye''de sıcak su kaynaklarının bol olmasının nedeni nedir?', '["Yüksek dağlar","Bol yağış","Volkanik ve fay yapısı","Deniz etkisi"]'::jsonb, 2, 'cografya'),
('Jeotermal enerjinin Türkiye''de en yoğun olduğu bölge hangisidir?', '["Doğu Anadolu","Karadeniz","Marmara","Ege"]'::jsonb, 3, 'cografya'),
('Türkiye''nin deprem riskinin yüksek olmasının sebebi nedir?', '["Aktif fay kuşağında olması","Yüksek dağlar","Bol yağış","Volkan yokluğu"]'::jsonb, 0, 'cografya'),
('Erozyonun en önemli sonucu nedir?', '["Yağışın artması","Verimli toprağın kaybı","Nüfusun artması","Ormanın büyümesi"]'::jsonb, 1, 'cografya'),
('Erozyonu önlemenin en etkili yolu nedir?', '["Gübreleme","Sulama","Ağaçlandırma","Sürüm"]'::jsonb, 2, 'cografya'),
('Teraslama hangi amaçla yapılır?', '["Gübre vermek","Sulama yapmak","Yol açmak","Eğimli arazide erozyonu azaltmak"]'::jsonb, 3, 'cografya'),
('Türkiye''de orman varlığının en az olduğu bölge hangisidir?', '["Güneydoğu Anadolu","Karadeniz","Akdeniz","Marmara"]'::jsonb, 0, 'cografya'),
('Maki bitki örtüsü hangi iklimin göstergesidir?', '["Karasal","Akdeniz","Okyanusal","Tundra"]'::jsonb, 1, 'cografya'),
('Bozkır (step) hangi iklimde görülür?', '["Ekvatoral","Akdeniz","Karasal","Muson"]'::jsonb, 2, 'cografya'),
('Türkiye''de kar yağışının en fazla olduğu bölge hangisidir?', '["Güneydoğu Anadolu","Akdeniz","Ege","Doğu Anadolu"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en yüksek ortalama yükseltiye sahip bölgesi hangisidir?', '["Doğu Anadolu","Marmara","Ege","Karadeniz"]'::jsonb, 0, 'cografya'),
('Yükselti arttıkça basınç nasıl değişir?', '["Artar","Azalır","Değişmez","İkiye katlanır"]'::jsonb, 1, 'cografya'),
('Kuzey yarım kürede en uzun gündüz hangi tarihte yaşanır?', '["21 Mart","21 Aralık","21 Haziran","23 Eylül"]'::jsonb, 2, 'cografya'),
('Kuzey yarım kürede en uzun gece hangi tarihte yaşanır?', '["23 Eylül","21 Haziran","21 Mart","21 Aralık"]'::jsonb, 3, 'cografya'),
('21 Mart ve 23 Eylül tarihlerinde ne olur?', '["Gece gündüz eşitlenir","Gündüz en uzundur","Gece en uzundur","Mevsim değişmez"]'::jsonb, 0, 'cografya'),
('Yengeç Dönencesi kaç derecededir?', '["23,5 güney","23,5 kuzey","66,5 kuzey","0"]'::jsonb, 1, 'cografya'),
('Oğlak Dönencesi hangi yarım küredir?', '["İkisi de","Kuzey","Güney","Hiçbiri"]'::jsonb, 2, 'cografya'),
('Kutup dairelerinin enlem değeri kaçtır?', '["90","23,5","45","66,5"]'::jsonb, 3, 'cografya'),
('Bir yerin yerel saatini belirleyen unsur nedir?', '["Boylam","Enlem","Yükselti","Nüfus"]'::jsonb, 0, 'cografya'),
('Bir yerin iklimini belirleyen en temel unsur nedir?', '["Boylam","Enlem","Nüfus","Dil"]'::jsonb, 1, 'cografya'),
('Sıcak çöllerin oluşumunda etkili olan basınç kuşağı hangisidir?', '["Termik alçak","Alçak basınç","Dinamik yüksek basınç","Kutup yüksek"]'::jsonb, 2, 'cografya'),
('Muson iklimini oluşturan temel etken nedir?', '["Akıntılar","Yükselti","Enlem yalnızca","Kara-deniz ısınma farkı"]'::jsonb, 3, 'cografya'),
('Ekvatoral iklimde yağış rejimi nasıldır?', '["Yıl boyu bol","Yalnız yazın","Yalnız kışın","Hiç yok"]'::jsonb, 0, 'cografya'),
('Akdeniz ikliminde yağış hangi mevsimde yoğunlaşır?', '["Yaz","Kış","İlkbahar yalnızca","Sonbahar yalnızca"]'::jsonb, 1, 'cografya'),
('Okyanusal iklimin belirgin özelliği nedir?', '["Aşırı soğuk","Kurak yaz","Yıl boyu düzenli yağış","Çöl koşulları"]'::jsonb, 2, 'cografya'),
('Sıcak su akıntılarının kıyılara etkisi nedir?', '["Rüzgârı durdurur","Sıcaklığı düşürür","Yağışı keser","Sıcaklığı artırır"]'::jsonb, 3, 'cografya'),
('Gulf Stream hangi okyanustadır?', '["Atlas Okyanusu","Büyük Okyanus","Hint Okyanusu","Arktik"]'::jsonb, 0, 'cografya'),
('Dünya''nın en derin gölü hangisidir?', '["Victoria","Baykal","Superior","Tanganyika"]'::jsonb, 1, 'cografya'),
('Amazon Nehri hangi okyanusa dökülür?', '["Hint","Büyük","Atlas","Arktik"]'::jsonb, 2, 'cografya'),
('Ganj Nehri hangi ülkeden geçer?', '["Mısır","Çin","İran","Hindistan"]'::jsonb, 3, 'cografya'),
('Yangtze Nehri hangi ülkededir?', '["Çin","Hindistan","Rusya","Vietnam"]'::jsonb, 0, 'cografya'),
('Mississippi Nehri hangi ülkededir?', '["Kanada","ABD","Meksika","Brezilya"]'::jsonb, 1, 'cografya'),
('Niagara Şelalesi hangi iki ülke sınırındadır?', '["Kanada ve Grönland","ABD ve Meksika","ABD ve Kanada","Brezilya ve Arjantin"]'::jsonb, 2, 'cografya'),
('Iguazu Şelaleleri hangi iki ülke sınırındadır?', '["Bolivya ve Paraguay","Şili ve Peru","Kolombiya ve Ekvador","Brezilya ve Arjantin"]'::jsonb, 3, 'cografya'),
('Himalayalar hangi iki levhanın çarpışmasıyla oluşmuştur?', '["Hint ve Avrasya","Afrika ve Avrupa","Pasifik ve Amerika","Antarktika ve Avustralya"]'::jsonb, 0, 'cografya'),
('Pasifik Ateş Çemberi neyi ifade eder?', '["Sıcak akıntı","Deprem ve volkan kuşağı","Rüzgâr kuşağı","Yağış kuşağı"]'::jsonb, 1, 'cografya'),
('Bir volkanın patlamasıyla oluşan çukura ne denir?', '["Moren","Kaldera yalnızca","Krater","Delta"]'::jsonb, 2, 'cografya'),
('Buzulların aşındırmasıyla oluşan U şekilli vadiye ne denir?', '["Boğaz","Akarsu vadisi","Kanyon","Buzul vadisi"]'::jsonb, 3, 'cografya'),
('Akarsuların oluşturduğu derin ve dar vadiye ne denir?', '["Kanyon","Delta","Kumul","Moren"]'::jsonb, 0, 'cografya'),
('Rüzgârın taşıdığı ince toz birikimine ne denir?', '["Moren","Lös","Traverten","Delta"]'::jsonb, 1, 'cografya'),
('Peribacalarının oluşumunda hangi kayaç etkilidir?', '["Mermer","Granit","Volkanik tüf","Bazalt"]'::jsonb, 2, 'cografya'),
('Sarkıt ve dikitlerin oluştuğu kayaç türü hangisidir?', '["Şist","Granit","Bazalt","Kalker"]'::jsonb, 3, 'cografya'),
('Obruk nedir?', '["Karstik çukur","Volkan ağzı","Buzul gölü","Delta"]'::jsonb, 0, 'cografya'),
('Falezlerin oluşumunda hangi etken rol oynar?', '["Rüzgâr yalnızca","Dalga aşındırması","Buzul","Deprem"]'::jsonb, 1, 'cografya'),
('Kıyı oku ve lagün hangi süreçle oluşur?', '["Buzullaşma","Volkanizma","Dalga ve akıntı birikmesi","Deprem"]'::jsonb, 2, 'cografya'),
('Haliç (estuar) nedir?', '["Körfez","Delta","Lagün","Gelgitin etkili olduğu nehir ağzı"]'::jsonb, 3, 'cografya'),
('Delta oluşumu için gerekli olmayan koşul hangisidir?', '["Güçlü gelgit","Bol alüvyon","Sığ deniz","Yavaş akıntı"]'::jsonb, 0, 'cografya'),
('Dünyada en fazla nüfusa sahip kıta hangisidir?', '["Afrika","Asya","Avrupa","Amerika"]'::jsonb, 1, 'cografya'),
('Nüfus yoğunluğunun en az olduğu kıta hangisidir?', '["Avrupa","Asya","Antarktika","Afrika"]'::jsonb, 2, 'cografya'),
('Bir ülkede doğurganlık hızının düşmesi neye yol açar?', '["Yağışın artmasına","Nüfusun gençleşmesine","Göçün durmasına","Nüfusun yaşlanmasına"]'::jsonb, 3, 'cografya'),
('İç göçün en yaygın nedeni nedir?', '["Ekonomik nedenler","İklim","Dil","Din"]'::jsonb, 0, 'cografya'),
('Beyin göçü ne demektir?', '["Mevsimlik göç","Nitelikli iş gücünün göçü","Zorunlu göç","Kırdan kıra göç"]'::jsonb, 1, 'cografya'),
('Mevsimlik göçün tipik örneği nedir?', '["Eğitim","Emeklilik","Tarım işçiliği","Savaş"]'::jsonb, 2, 'cografya'),
('Şehirlerde gecekondulaşmanın temel nedeni nedir?', '["Bol konut","Yüksek gelir","Az nüfus","Plansız hızlı göç"]'::jsonb, 3, 'cografya'),
('Bir ülkede tarımın milli gelirdeki payının azalması neyi gösterir?', '["Sanayileşmeyi","Kuraklığı","Nüfus azalmasını","Göçün bitmesini"]'::jsonb, 0, 'cografya'),
('Birincil ekonomik faaliyet hangisidir?', '["Sanayi","Tarım","Ticaret","Bankacılık"]'::jsonb, 1, 'cografya'),
('İkincil ekonomik faaliyet hangisidir?', '["Turizm","Tarım","Sanayi","Eğitim"]'::jsonb, 2, 'cografya'),
('Üçüncül ekonomik faaliyet hangisidir?', '["Balıkçılık","Tarım","Madencilik","Hizmet"]'::jsonb, 3, 'cografya'),
('Bir sanayi tesisinin kurulacağı yer seçilirken en önemli etken nedir?', '["Hammadde ve ulaşım","Manzara","İklim yalnızca","Dil"]'::jsonb, 0, 'cografya'),
('Türkiye''de sanayinin en yoğun olduğu şehir hangisidir?', '["Van","İstanbul","Ardahan","Sinop"]'::jsonb, 1, 'cografya'),
('Türkiye''de linyit yataklarının en yoğun olduğu bölgelerden biri neresidir?', '["Marmara adaları","Karadeniz kıyısı","Ege","Trakya kıyısı"]'::jsonb, 2, 'cografya'),
('Taş kömürünün Türkiye''deki başlıca çıkarıldığı il hangisidir?', '["Antalya","Kayseri","Malatya","Zonguldak"]'::jsonb, 3, 'cografya'),
('Türkiye''de krom madeninin önemi nedir?', '["Dünya üretiminde söz sahibi olması","Hiç bulunmaması","Yalnız ithal edilmesi","Yalnız işlenmesi"]'::jsonb, 0, 'cografya'),
('Bakır madeninin en yaygın kullanım alanı nedir?', '["Cam üretimi","Elektrik iletimi","Kâğıt üretimi","Gıda"]'::jsonb, 1, 'cografya'),
('Hidroelektrik santralin kurulması için gereken koşul nedir?', '["Güneş","Rüzgâr","Su ve eğim","Kömür"]'::jsonb, 2, 'cografya'),
('Rüzgâr santralleri için en uygun alanlar nerelerdir?', '["Mağaralar","Ormanlar","Vadi tabanları","Sürekli rüzgâr alan kıyı ve tepeler"]'::jsonb, 3, 'cografya'),
('Güneş enerjisi potansiyeli Türkiye''de en yüksek bölge hangisidir?', '["Güneydoğu Anadolu","Karadeniz","Marmara","Kuzeydoğu"]'::jsonb, 0, 'cografya'),
('Turizmde "kültür turizmi" neye dayanır?', '["Plajlar","Tarihî ve kültürel değerler","Kayak","Sağlık"]'::jsonb, 1, 'cografya'),
('Termal turizm neye dayanır?', '["Deniz","Kar","Sıcak su kaynakları","Orman"]'::jsonb, 2, 'cografya'),
('Bir ülkenin dış ticaret açığı ne demektir?', '["Nüfus artışı","İhracatın fazla olması","Vergi artışı","İthalatın ihracattan fazla olması"]'::jsonb, 3, 'cografya'),
('Transit ticaret nedir?', '["Bir ülkeden geçerek yapılan ticaret","İç ticaret","Kaçakçılık","Takas"]'::jsonb, 0, 'cografya'),
('Boğazların Türkiye için önemi öncelikle nedir?', '["İklimsel","Jeopolitik ve ticari","Tarımsal","Madensel"]'::jsonb, 1, 'cografya'),
('Süveyş Kanalı''nın kapanması neyi etkiler?', '["Demiryollarını","Hava trafiğini","Deniz ticaret yollarını","Tarımı"]'::jsonb, 2, 'cografya'),
('Haritalarda büyük ölçek ne anlama gelir?', '["Daha küçük kâğıt","Daha az ayrıntı","Daha geniş alan","Daha ayrıntılı gösterim"]'::jsonb, 3, 'cografya'),
('Küçük ölçekli haritalar neyi gösterir?', '["Geniş alanı az ayrıntıyla","Dar alanı çok ayrıntıyla","Yalnız şehirleri","Yalnız binaları"]'::jsonb, 0, 'cografya'),
('İzohips çizgileri sıklaştığında arazi nasıldır?', '["Düzdür","Eğim artmıştır","Çukurdur","Denizdir"]'::jsonb, 1, 'cografya'),
('Topografya haritası neyi gösterir?', '["İklimi","Nüfusu","Yeryüzü şekillerini","Ekonomiyi"]'::jsonb, 2, 'cografya'),
('Uydu görüntüleri hangi alanda kullanılmaz?', '["Şehir planlamada","Tarımda","Afet yönetiminde","Şiir yazımında"]'::jsonb, 3, 'cografya'),
('Coğrafi bilgi sistemleri ne işe yarar?', '["Mekânsal veriyi analiz etmek","Ses kaydetmek","Yemek pişirmek","Müzik yapmak"]'::jsonb, 0, 'cografya'),
('Dünya haritasında Grönland''ın gerçekte olduğundan büyük görünmesinin nedeni nedir?', '["Buzullar","Projeksiyon bozulması","Nüfus","Ölçek hatası yok"]'::jsonb, 1, 'cografya'),
('Yeryüzünde kara ve deniz oranı yaklaşık nedir?', '["%71 kara","%50-50","%29 kara, %71 deniz","%10 deniz"]'::jsonb, 2, 'cografya'),
('Dünyanın en büyük okyanusunun adı nedir?', '["Arktik","Atlas","Hint","Pasifik (Büyük)"]'::jsonb, 3, 'cografya'),
('Kıtaların hareketini açıklayan kurama ne denir?', '["Levha tektoniği","Erozyon kuramı","İklim kuramı","Deniz kuramı"]'::jsonb, 0, 'cografya'),
('Pangea nedir?', '["Bir okyanus","Eski tek kıta","Bir dağ","Bir göl"]'::jsonb, 1, 'cografya'),
('Okyanus ortası sırtlar nasıl oluşur?', '["Erozyonla","Levhaların çarpışmasıyla","Levhaların uzaklaşmasıyla","Buzullarla"]'::jsonb, 2, 'cografya'),
('Derin okyanus çukurları nasıl oluşur?', '["Yağışla","Levha uzaklaşmasıyla","Rüzgârla","Levha dalmasıyla"]'::jsonb, 3, 'cografya'),
('Sıcaklık farkının en fazla olduğu iklim tipi hangisidir?', '["Karasal","Okyanusal","Akdeniz","Ekvatoral"]'::jsonb, 0, 'cografya'),
('Nem oranının en yüksek olduğu iklim hangisidir?', '["Çöl","Ekvatoral","Karasal","Tundra"]'::jsonb, 1, 'cografya'),
('Kar örtüsünün yıl boyu bulunduğu sınıra ne denir?', '["Tarım sınırı","Orman sınırı","Kalıcı kar sınırı","Yerleşim sınırı"]'::jsonb, 2, 'cografya'),
('Orman üst sınırını belirleyen temel etken nedir?', '["Rüzgâr yönü","Nüfus","Toprak rengi","Sıcaklık"]'::jsonb, 3, 'cografya'),
('Dağların yağış alan yamacına ne denir?', '["Rüzgâra bakan yamaç","Rüzgâr altı yamaç","Kuzey yamaç hep","Güney yamaç hep"]'::jsonb, 0, 'cografya'),
('Föhn rüzgârının özelliği nedir?', '["Soğuk ve nemli","Sıcak ve kuru olması","Yağışlı","Karlı"]'::jsonb, 1, 'cografya'),
('Türkiye''de yaz kuraklığının en belirgin olduğu bölge hangisidir?', '["Marmara","Karadeniz","Akdeniz","Doğu Anadolu"]'::jsonb, 2, 'cografya'),
('Türkiye''de don olayının en uzun sürdüğü bölge hangisidir?', '["Marmara","Akdeniz","Ege","Doğu Anadolu"]'::jsonb, 3, 'cografya'),
('Karadeniz kıyılarında yağışın yıl boyu olmasının nedeni nedir?', '["Nemli hava kütleleri ve dağ engeli","Çöl etkisi","Buzul etkisi","Volkanlar"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en az yağış alan bölgesi hangisidir?', '["Karadeniz","Güneydoğu Anadolu","Marmara","Ege"]'::jsonb, 1, 'cografya'),
('Türkiye''de sel riskinin artmasının insan kaynaklı nedeni nedir?', '["Baraj yapımı","Ağaçlandırma","Dere yataklarının yapılaşması","Teraslama"]'::jsonb, 2, 'cografya'),
('Türkiye''de heyelanın en sık görüldüğü bölge hangisidir?', '["Marmara","İç Anadolu","Güneydoğu","Karadeniz"]'::jsonb, 3, 'cografya'),
('Çığ riskini artıran temel etken nedir?', '["Eğim ve kar birikimi","Yağmur","Sıcaklık artışı yalnızca","Rüzgâr yokluğu"]'::jsonb, 0, 'cografya'),
('Kuraklığın tarıma etkisi nedir?', '["Verim artar","Verim düşer","Toprak zenginleşir","Yağış artar"]'::jsonb, 1, 'cografya'),
('Çölleşmeyi önlemek için ne yapılır?', '["Ormansızlaştırma","Aşırı otlatma","Ağaçlandırma ve su yönetimi","Sulama yasağı"]'::jsonb, 2, 'cografya'),
('Sürdürülebilir kalkınma ne demektir?', '["Doğayı yok sayma","Hızlı tüketim","Sınırsız üretim","Gelecek kuşakları gözeten kalkınma"]'::jsonb, 3, 'cografya'),
('Milli parkların temel amacı nedir?', '["Doğal ve kültürel değerleri korumak","Sanayi kurmak","Konut yapmak","Maden çıkarmak"]'::jsonb, 0, 'cografya'),
('Ramsar Sözleşmesi neyi korur?', '["Ormanları","Sulak alanları","Çölleri","Dağları"]'::jsonb, 1, 'cografya'),
('Sulak alanların ekolojik önemi nedir?', '["Yol güzergâhı","Maden kaynağı","Kuş ve canlı yaşam alanı","Konut alanı"]'::jsonb, 2, 'cografya'),
('Ekolojik ayak izi neyi ölçer?', '["Nüfusu","Yürüme mesafesini","Ayakkabı numarasını","Doğal kaynak tüketimini"]'::jsonb, 3, 'cografya'),
('Yenilenebilir enerjinin çevresel avantajı nedir?', '["Daha az sera gazı","Daha çok atık","Daha çok kirlilik","Daha çok kömür"]'::jsonb, 0, 'cografya'),
('Bir bölgenin turizm potansiyelini artıran etken hangisidir?', '["Nüfus azlığı","Ulaşım ve konaklama imkânı","Yağış azlığı","Dil çeşitliliği"]'::jsonb, 1, 'cografya'),
('Kıtaların en küçüğü hangisidir?', '["Antarktika","Avrupa","Avustralya","Güney Amerika"]'::jsonb, 2, 'cografya'),
('Avrupa''nın en uzun nehri hangisidir?', '["Elbe","Tuna","Ren","Volga"]'::jsonb, 3, 'cografya'),
('Asya''nın en uzun nehri hangisidir?', '["Yangtze","Ganj","İndus","Amur"]'::jsonb, 0, 'cografya'),
('Güney Amerika''nın en uzun sıradağları hangisidir?', '["Kayalıklar","Andlar","Alpler","Atlas"]'::jsonb, 1, 'cografya'),
('Kuzey Amerika''daki büyük sıradağ sistemi hangisidir?', '["Alpler","Andlar","Kayalık Dağlar","Ural"]'::jsonb, 2, 'cografya'),
('Avustralya''nın iç kesimlerinin genel özelliği nedir?', '["Bataklık","Yağışlı orman","Buzul","Kurak ve çöl"]'::jsonb, 3, 'cografya'),
('Antarktika''nın yüzeyini kaplayan şey nedir?', '["Buz tabakası","Çöl kumu","Orman","Bozkır"]'::jsonb, 0, 'cografya'),
('Kutuplarda güneşin batmadığı döneme ne denir?', '["Kutup gecesi","Beyaz geceler","Ekinoks","Gündönümü"]'::jsonb, 1, 'cografya'),
('Kutup ışıklarının bilimsel adı nedir?', '["Serap","Fata Morgana","Aurora","Halo"]'::jsonb, 2, 'cografya'),
('Serap olayı hangi koşulda görülür?', '["Gece","Karda","Yağmurda","Sıcak havada ışığın kırılmasıyla"]'::jsonb, 3, 'cografya'),
('Sisin oluşması için ne gerekir?', '["Nemli hava ve soğuma","Kuru hava","Yüksek rüzgâr","Yüksek sıcaklık"]'::jsonb, 0, 'cografya'),
('Dolunun tarıma zararı nedir?', '["Toprağı zenginleştirir","Ürünü fiziksel olarak zedeler","Verimi artırır","Sulama sağlar"]'::jsonb, 1, 'cografya'),
('Hortum (tornado) hangi koşulda oluşur?', '["Karlı havada","Açık havada","Güçlü fırtına bulutlarında","Sisli havada"]'::jsonb, 2, 'cografya'),
('Tropikal siklonlar hangi kuşakta oluşur?', '["Dağlar","Kutuplar","Çöller","Tropikal denizler"]'::jsonb, 3, 'cografya'),
('El Nino olayı neyi etkiler?', '["Küresel iklim düzenini","Yalnız Türkiye''yi","Yalnız kutupları","Hiçbir şeyi"]'::jsonb, 0, 'cografya'),
('Bir bölgede uzun yıllar ortalama hava koşullarına ne denir?', '["Hava durumu","İklim","Mevsim","Rüzgâr"]'::jsonb, 1, 'cografya'),
('İklimi inceleyen bilim dalı hangisidir?', '["Sismoloji","Meteoroloji","Klimatoloji","Vulkanoloji"]'::jsonb, 2, 'cografya'),
('Yer altı ve yer üstü sularını inceleyen dal hangisidir?', '["Ekoloji","Sismoloji","Pedoloji","Hidroloji"]'::jsonb, 3, 'cografya'),
('Toprağı inceleyen bilim dalı hangisidir?', '["Pedoloji","Hidroloji","Sismoloji","Meteoroloji"]'::jsonb, 0, 'cografya'),

-- ===================== EDEBİYAT (200) =====================
('Bir metinde olayın anlatıldığı bakış açısına ne denir?', '["Tema","Anlatıcı bakış açısı","Konu","Üslup"]'::jsonb, 1, 'edebiyat'),
('Romanda "kahraman anlatıcı" hangi kişi ağzından anlatır?', '["Üçüncü kişi","İkinci kişi","Birinci kişi","Anlatıcısız"]'::jsonb, 2, 'edebiyat'),
('Hikâye ile romanı ayıran temel özellik nedir?', '["Basım yeri","Dil","Yazar","Uzunluk ve olay sayısı"]'::jsonb, 3, 'edebiyat'),
('Bir eserde çatışma neyi sağlar?', '["Olay örgüsünü ilerletmeyi","Betimlemeyi","Kafiyeyi","Ölçüyü"]'::jsonb, 0, 'edebiyat'),
('Betimleme neyi anlatır?', '["Olayı sıralamayı","Görüntüyü sözle canlandırmayı","Tartışmayı","Kanıtlamayı"]'::jsonb, 1, 'edebiyat'),
('Öyküleyici anlatımda ne öne çıkar?', '["Tanım","Sayısal veri","Olay akışı","Formül"]'::jsonb, 2, 'edebiyat'),
('Bir yazıda "giriş, gelişme, sonuç" neyi ifade eder?', '["Redif","Kafiye","Ölçü","Plan"]'::jsonb, 3, 'edebiyat'),
('Şiirde "imge" ne demektir?', '["Zihinde canlanan görüntü","Ölçü","Kafiye","Dize sayısı"]'::jsonb, 0, 'edebiyat'),
('Şiirde ahenk hangi öğelerle sağlanır?', '["Sayfa sayısı","Ölçü, kafiye ve redif","Yazı tipi","Kapak"]'::jsonb, 1, 'edebiyat'),
('Serbest nazımda hangi kural aranmaz?', '["İmge","Anlam","Ölçü ve kafiye zorunluluğu","Duygu"]'::jsonb, 2, 'edebiyat'),
('Türk halk edebiyatında âşıkların kullandığı çalgı hangisidir?', '["Ud","Piyano","Keman","Saz"]'::jsonb, 3, 'edebiyat'),
('Halk hikâyeleri hangi yolla aktarılır?', '["Sözlü gelenek","Yalnız yazılı","Gazete","Radyo yalnızca"]'::jsonb, 0, 'edebiyat'),
('Destanların ortak özelliği nedir?', '["Bilimsel kanıt","Olağanüstü olaylar ve kahramanlık","İstatistik","Deney"]'::jsonb, 1, 'edebiyat'),
('Oğuz Kağan Destanı hangi kültüre aittir?', '["Yunan","Fars","Türk","Roma"]'::jsonb, 2, 'edebiyat'),
('Manas Destanı hangi Türk topluluğuna aittir?', '["Tatar","Kazak","Özbek","Kırgız"]'::jsonb, 3, 'edebiyat'),
('İlyada destanı hangi savaşı anlatır?', '["Truva Savaşı","Pers Savaşı","Pön Savaşı","Haçlı Seferi"]'::jsonb, 0, 'edebiyat'),
('Gılgamış Destanı hangi uygarlığa aittir?', '["Mısır","Sümer","Yunan","Hint"]'::jsonb, 1, 'edebiyat'),
('Masalın belirgin özelliği nedir?', '["Belge","Kesin tarih","Belirsiz zaman ve yer","İstatistik"]'::jsonb, 2, 'edebiyat'),
('Fabl türünde kahramanlar genellikle kimlerdir?', '["Bilim insanları","Krallar","Askerler","Hayvanlar"]'::jsonb, 3, 'edebiyat'),
('Fabl türünün amacı nedir?', '["Ders vermek","Haber vermek","Ölçmek","Satmak"]'::jsonb, 0, 'edebiyat'),
('İlk çeviri roman hangi eserdir?', '["Robinson","Telemak","Sefiller","Monte Kristo"]'::jsonb, 1, 'edebiyat'),
('Türk edebiyatında ilk tiyatro eseri hangisidir?', '["Zavallı Çocuk","Vatan yahut Silistre","Şair Evlenmesi","Akif Bey"]'::jsonb, 2, 'edebiyat'),
('"Şair Evlenmesi" kimin eseridir?', '["Ahmet Mithat","Namık Kemal","Ziya Paşa","Şinasi"]'::jsonb, 3, 'edebiyat'),
('"Vatan yahut Silistre" kimin eseridir?', '["Namık Kemal","Şinasi","Ziya Paşa","Recaizade"]'::jsonb, 0, 'edebiyat'),
('"Araba Sevdası" romanının yazarı kimdir?', '["Namık Kemal","Recaizade Mahmut Ekrem","Şinasi","Ahmet Mithat"]'::jsonb, 1, 'edebiyat'),
('Ahmet Mithat Efendi hangi yönüyle bilinir?', '["Şiir yazması yalnızca","Ağır dil kullanması","Halk için yazması","Tiyatro yazmaması"]'::jsonb, 2, 'edebiyat'),
('Servet-i Fünun döneminin dil anlayışı nasıldır?', '["Yabancısız","Sade","Argo","Ağır ve sanatlı"]'::jsonb, 3, 'edebiyat'),
('"Eylül" romanı kimin eseridir?', '["Mehmet Rauf","Halit Ziya","Yakup Kadri","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('Tevfik Fikret hangi türde ünlüdür?', '["Roman","Şiir","Tiyatro","Deneme"]'::jsonb, 1, 'edebiyat'),
('"Rübab-ı Şikeste" kimin şiir kitabıdır?', '["Yahya Kemal","Ahmet Haşim","Tevfik Fikret","Nazım Hikmet"]'::jsonb, 2, 'edebiyat'),
('Milli Edebiyat akımının yayın organı hangisidir?', '["Varlık","Servet-i Fünun","Dergâh","Genç Kalemler"]'::jsonb, 3, 'edebiyat'),
('"Yeni Lisan" makalesi hangi akımın başlangıcı sayılır?', '["Milli Edebiyat","Servet-i Fünun","Fecr-i Ati","Garip"]'::jsonb, 0, 'edebiyat'),
('Ömer Seyfettin''in hikâyelerinde öne çıkan tema nedir?', '["Bilim kurgu","Milli duygular","Polisiye","Fantastik"]'::jsonb, 1, 'edebiyat'),
('"Kaşağı" hikâyesi kime aittir?', '["Refik Halid","Sait Faik","Ömer Seyfettin","Sabahattin Ali"]'::jsonb, 2, 'edebiyat'),
('Halide Edip Adıvar''ın Kurtuluş Savaşı''nı anlatan romanı hangisidir?', '["Vurun Kahpeye''nin yazarı değil","Sinekli Bakkal","Handan","Ateşten Gömlek"]'::jsonb, 3, 'edebiyat'),
('"Vurun Kahpeye" romanının yazarı kimdir?', '["Halide Edip Adıvar","Yakup Kadri","Reşat Nuri","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('Yakup Kadri''nin Kurtuluş Savaşı sonrası köyü anlattığı roman hangisidir?', '["Kiralık Konak","Yaban","Nur Baba","Ankara"]'::jsonb, 1, 'edebiyat'),
('"Kiralık Konak" hangi konuyu işler?', '["Deniz","Savaş","Kuşak çatışması","Uzay"]'::jsonb, 2, 'edebiyat'),
('Reşat Nuri Güntekin''in Anadolu''yu anlattığı roman hangisidir?', '["Fatih-Harbiye","Yaban","Huzur","Çalıkuşu"]'::jsonb, 3, 'edebiyat'),
('Peyami Safa''nın Doğu-Batı çatışmasını işlediği roman hangisidir?', '["Fatih-Harbiye","Çalıkuşu","Yaban","İnce Memed"]'::jsonb, 0, 'edebiyat'),
('Sabahattin Ali''nin ünlü romanı hangisidir?', '["Huzur","Kürk Mantolu Madonna","Tutunamayanlar","Yaban"]'::jsonb, 1, 'edebiyat'),
('"Semaver" adlı öykü kitabı kime aittir?', '["Refik Halid","Ömer Seyfettin","Sait Faik","Memduh Şevket"]'::jsonb, 2, 'edebiyat'),
('"Aylak Adam" romanının yazarı kimdir?', '["Bilge Karasu","Oğuz Atay","Adalet Ağaoğlu","Yusuf Atılgan"]'::jsonb, 3, 'edebiyat'),
('Yaşar Kemal''in Çukurova''yı anlattığı romanlar hangi konuyu işler?', '["Toprak ve insan","Uzay","Denizaltı","Sanayi"]'::jsonb, 0, 'edebiyat'),
('Orhan Kemal''in romanlarında ağırlıklı mekân neresidir?', '["Saray","Kent ve fabrika çevresi","Uzay","Manastır"]'::jsonb, 1, 'edebiyat'),
('Nazım Hikmet''in şiirinde öne çıkan biçim özelliği nedir?', '["Hece yalnızca","Aruz","Serbest ölçü","Kafiyesizlik yasağı"]'::jsonb, 2, 'edebiyat'),
('Garip akımının şiire getirdiği yenilik nedir?', '["Uzun destanlar","Ağır dil","Aruz ölçüsü","Sade dil ve gündelik konular"]'::jsonb, 3, 'edebiyat'),
('Garip akımının üç şairi kimlerdir?', '["Orhan Veli, Melih Cevdet, Oktay Rifat","Nazım, Necip Fazıl, Cahit","Yahya Kemal, Haşim, Fikret","Attila İlhan ve ikilisi"]'::jsonb, 0, 'edebiyat'),
('İkinci Yeni şiirinin özelliği nedir?', '["Açık ve sade anlatım","Kapalı ve imgeli anlatım","Destansı","Belgesel"]'::jsonb, 1, 'edebiyat'),
('"Karacaoğlan" hangi türde eser vermiştir?', '["Kaside","Gazel","Koşma ve semai","Mesnevi"]'::jsonb, 2, 'edebiyat'),
('Pir Sultan Abdal hangi edebiyat geleneğindendir?', '["Garip","Divan","Servet-i Fünun","Halk-tasavvuf"]'::jsonb, 3, 'edebiyat'),
('Aşık Veysel''in şiirlerinde öne çıkan tema nedir?', '["Doğa ve insan sevgisi","Savaş","Ticaret","Bilim"]'::jsonb, 0, 'edebiyat'),
('Divan edebiyatında "divan" ne demektir?', '["Meclis yalnızca","Şairin şiirlerini topladığı kitap","Roman","Sözlük"]'::jsonb, 1, 'edebiyat'),
('Fuzuli hangi eseriyle tanınır?', '["Mesnevi","Hüsn ü Aşk","Leyla ile Mecnun","Divanü Lügat"]'::jsonb, 2, 'edebiyat'),
('"Hüsn ü Aşk" kimin eseridir?', '["Nedim","Fuzuli","Baki","Şeyh Galip"]'::jsonb, 3, 'edebiyat'),
('Baki hangi dönemin şairidir?', '["Klasik dönem divan","Tanzimat","Cumhuriyet","Halk"]'::jsonb, 0, 'edebiyat'),
('Nedim hangi dönemle özdeşleşmiştir?', '["Kuruluş","Lale Devri","Tanzimat","Meşrutiyet"]'::jsonb, 1, 'edebiyat'),
('Divan şiirinde "mahlas" ne demektir?', '["Ölçü","Şiir türü","Şairin takma adı","Kafiye"]'::jsonb, 2, 'edebiyat'),
('Divan edebiyatında kullanılan ölçünün adı nedir?', '["Karışık","Hece","Serbest","Aruz"]'::jsonb, 3, 'edebiyat'),
('Aruz ölçüsü neye dayanır?', '["Hecelerin uzunluk-kısalığına","Hece sayısına","Kelime sayısına","Dize sayısına"]'::jsonb, 0, 'edebiyat'),
('Hece ölçüsünde durak neyi ifade eder?', '["Kafiye","Dizedeki bölünme yeri","Redif","Mahlas"]'::jsonb, 1, 'edebiyat'),
('Dörtlüklerle yazılan ve ezgiyle söylenen halk şiiri hangisidir?', '["Kaside","Gazel","Türkü","Rubai"]'::jsonb, 2, 'edebiyat'),
('Bir olayı ya da durumu abartılı anlatan söz sanatı hangisidir?', '["Cinas","Teşbih","Tevriye","Mübalağa"]'::jsonb, 3, 'edebiyat'),
('Bir sözcüğün iki anlama gelecek şekilde kullanılmasına ne denir?', '["Tevriye","Teşbih","Tezat","Tekrir"]'::jsonb, 0, 'edebiyat'),
('Aynı sözcüğün tekrarlanmasıyla yapılan sanata ne denir?', '["Cinas","Tekrir","Tevriye","Kinaye"]'::jsonb, 1, 'edebiyat'),
('Benzetmede kendisine benzetilen öğeye ne denir?', '["Yön","Benzeyen","Benzetilen","Edat"]'::jsonb, 2, 'edebiyat'),
('İstiare (eğretileme) hangi sanatla yakından ilgilidir?', '["Ölçü","Tezat","Tekrir","Benzetme"]'::jsonb, 3, 'edebiyat'),
('Ad aktarması (mecaz-ı mürsel) neye dayanır?', '["Parça-bütün ilişkisi","Benzerlik","Karşıtlık","Tekrar"]'::jsonb, 0, 'edebiyat'),
('"Sobayı yaktık" cümlesinde hangi sanat vardır?', '["Benzetme","Ad aktarması","Abartma","Kişileştirme"]'::jsonb, 1, 'edebiyat'),
('"Cesur Yeni Dünya" kimin eseridir?', '["Kurt Vonnegut","George Orwell","Aldous Huxley","Philip Dick"]'::jsonb, 2, 'edebiyat'),
('"Hayvan Çiftliği" hangi türde bir eserdir?', '["Tiyatro","Belgesel","Şiir","Alegorik roman"]'::jsonb, 3, 'edebiyat'),
('"Karamazov Kardeşler" kimin eseridir?', '["Dostoyevski","Tolstoy","Gogol","Puşkin"]'::jsonb, 0, 'edebiyat'),
('Çehov hangi türde ustadır?', '["Destan","Öykü ve tiyatro","Fabl","Deneme"]'::jsonb, 1, 'edebiyat'),
('"Vişne Bahçesi" kimin oyunudur?', '["Strindberg","Ibsen","Çehov","Shaw"]'::jsonb, 2, 'edebiyat'),
('Molière hangi türde eser vermiştir?', '["Roman","Trajedi yalnızca","Destan","Komedi"]'::jsonb, 3, 'edebiyat'),
('"Cimri" oyununun yazarı kimdir?', '["Molière","Shakespeare","Ibsen","Çehov"]'::jsonb, 0, 'edebiyat'),
('Shakespeare''in trajedilerinden biri hangisidir?', '["Cimri","Macbeth","Vişne Bahçesi","Bir Bebek Evi"]'::jsonb, 1, 'edebiyat'),
('"Romeo ve Juliet" hangi türdedir?', '["Fabl","Komedi","Trajedi","Deneme"]'::jsonb, 2, 'edebiyat'),
('"Yüzyıllık Yalnızlık" kimin eseridir?', '["Mario Vargas Llosa","Pablo Neruda","Jorge Luis Borges","Gabriel Garcia Marquez"]'::jsonb, 3, 'edebiyat'),
('Büyülü gerçekçilik akımı en çok hangi bölgeyle anılır?', '["Latin Amerika","Kuzey Avrupa","Doğu Asya","Kuzey Afrika"]'::jsonb, 0, 'edebiyat'),
('"Küçük Kadınlar" romanının yazarı kimdir?', '["Jane Austen","Louisa May Alcott","Bronte kardeşler","George Eliot"]'::jsonb, 1, 'edebiyat'),
('"Gurur ve Önyargı" kimin eseridir?', '["Emily Bronte","Charlotte Bronte","Jane Austen","Mary Shelley"]'::jsonb, 2, 'edebiyat'),
('Edgar Allan Poe hangi türün öncülerindendir?', '["Destan","Bilim kurgu yalnızca","Fabl","Polisiye ve korku"]'::jsonb, 3, 'edebiyat'),
('Agatha Christie hangi türde ünlüdür?', '["Polisiye","Bilim kurgu","Destan","Fabl"]'::jsonb, 0, 'edebiyat'),
('"Yüzüklerin Efendisi" kimin eseridir?', '["C.S. Lewis","J.R.R. Tolkien","George Martin","Terry Pratchett"]'::jsonb, 1, 'edebiyat'),
('"Narnia Günlükleri" kimin eseridir?', '["Roald Dahl","J.R.R. Tolkien","C.S. Lewis","Philip Pullman"]'::jsonb, 2, 'edebiyat'),
('Bir eserin başka dile aktarılmasına ne denir?', '["Eleştiri","Uyarlama","Özet","Çeviri"]'::jsonb, 3, 'edebiyat'),
('Bir eserin sinemaya aktarılmasına ne denir?', '["Uyarlama","Çeviri","Özet","Dizin"]'::jsonb, 0, 'edebiyat'),
('Edebî eleştirinin amacı nedir?', '["Eseri satmak","Eseri değerlendirmek","Yazarı övmek yalnızca","Basmak"]'::jsonb, 1, 'edebiyat'),
('Bir kitabın önsözünü kim yazar?', '["Dağıtımcı","Matbaacı","Yazar veya bir uzman","Okur"]'::jsonb, 2, 'edebiyat'),
('Dipnot ne için kullanılır?', '["Fiyat yazmak","Başlık atmak","Kapak yapmak","Açıklama ve kaynak vermek"]'::jsonb, 3, 'edebiyat'),
('Bir metinde intihal ne demektir?', '["Başkasının eserini sahiplenme","Alıntı yapma","Çeviri","Özet"]'::jsonb, 0, 'edebiyat'),
('Antoloji nedir?', '["Tek yazarın romanı","Seçme eserler derlemesi","Sözlük","Ansiklopedi"]'::jsonb, 1, 'edebiyat'),
('Bir yazarın tüm eserlerine ne denir?', '["Dizin","Antoloji","Külliyat","Fasikül"]'::jsonb, 2, 'edebiyat'),
('Edebiyatta "klasik" ne anlama gelir?', '["Kısa eser","Yeni çıkan eser","Ucuz eser","Kalıcı değer taşıyan eser"]'::jsonb, 3, 'edebiyat'),

-- ===== EK BLOK =====
('Yer kabuğunun en dış katmanına ne ad verilir?', '["Litosfer","Astenosfer","Manto","Çekirdek"]'::jsonb, 0, 'cografya'),
('Yer''in en içteki katmanı hangisidir?', '["Manto","Çekirdek","Kabuk","Litosfer"]'::jsonb, 1, 'cografya'),
('Magmanın yeryüzüne çıkmasına ne denir?', '["Tektonizma","Erozyon","Volkanizma","Depozisyon"]'::jsonb, 2, 'cografya'),
('Yer kabuğunun kırılmadan bükülmesine ne denir?', '["Birikme","Kırılma","Aşınma","Kıvrılma"]'::jsonb, 3, 'cografya'),
('Kırılma sonucu yükselen bloğa ne ad verilir?', '["Horst","Graben","Delta","Moren"]'::jsonb, 0, 'cografya'),
('Kırılma sonucu çöken alana ne ad verilir?', '["Horst","Graben","Kıvrım","Sırt"]'::jsonb, 1, 'cografya'),
('Kayaçların yerinde ufalanmasına ne denir?', '["Birikme","Taşınma","Ayrışma","Erime"]'::jsonb, 2, 'cografya'),
('Magmanın yer altında soğumasıyla oluşan kayaçlara ne denir?', '["Başkalaşım","Dış püskürük","Tortul","İç püskürük"]'::jsonb, 3, 'cografya'),
('Kireç taşının başkalaşımıyla hangi kayaç oluşur?', '["Mermer","Granit","Bazalt","Kum taşı"]'::jsonb, 0, 'cografya'),
('Kömür hangi kayaç grubuna girer?', '["Püskürük","Tortul","Başkalaşım","Volkanik"]'::jsonb, 1, 'cografya'),
('Petrolün oluştuğu kayaç türü hangisidir?', '["Bazalt","Granit","Tortul","Mermer"]'::jsonb, 2, 'cografya'),
('Yeraltı suyunun kendiliğinden yüzeye çıktığı yere ne denir?', '["Kuyu","Baraj","Kanal","Kaynak"]'::jsonb, 3, 'cografya'),
('Akarsuyun taşıdığı malzemeye ne denir?', '["Alüvyon","Moren","Lös","Lav"]'::jsonb, 0, 'cografya'),
('Akarsuyun denize döküldüğü yerde biriktirmesiyle oluşan şekil nedir?', '["Kanyon","Delta ovası","Peribacası","Falez"]'::jsonb, 1, 'cografya'),
('Akarsuyun aşındırma gücü en fazla nerede olur?', '["Denizde","Ağız kısmında","Eğimin fazla olduğu yerde","Gölde"]'::jsonb, 2, 'cografya'),
('Akarsuların rejimi düzensizse bunun nedeni nedir?', '["Toprağın rengi","Eğimin azlığı","Denizin yakınlığı","Yağışın düzensizliği"]'::jsonb, 3, 'cografya'),
('Buzulların taşıyıp biriktirdiği malzemeye ne denir?', '["Moren","Alüvyon","Lös","Traverten"]'::jsonb, 0, 'cografya'),
('Sirk gölleri hangi etkenle oluşur?', '["Rüzgâr","Buzul","Volkan","Akarsu"]'::jsonb, 1, 'cografya'),
('Krater göllerinin oluşum kaynağı nedir?', '["Rüzgâr","Buzul","Volkanizma","Karstlaşma"]'::jsonb, 2, 'cografya'),
('Set gölleri nasıl oluşur?', '["Deprem çukuruyla","Volkan patlamasıyla","Buzul erimesiyle","Bir çukurun önünün kapanmasıyla"]'::jsonb, 3, 'cografya'),
('Karstik göller hangi kayaçta oluşur?', '["Kalker","Granit","Bazalt","Şist"]'::jsonb, 0, 'cografya'),
('Traverten oluşumunda etkili madde nedir?', '["Tuz","Kireç","Demir","Kükürt"]'::jsonb, 1, 'cografya'),
('Rüzgârın aşındırmasıyla oluşan mantar biçimli kayaya ne denir?', '["Falez","Peribacası","Mantarkaya","Kumul"]'::jsonb, 2, 'cografya'),
('Kumulların oluşumunda hangi etken rol oynar?', '["Dalga","Buzul","Akarsu","Rüzgâr"]'::jsonb, 3, 'cografya'),
('Dalga aşındırmasıyla oluşan düzlüğe ne denir?', '["Aşınım düzlüğü","Delta","Moren","Kumul"]'::jsonb, 0, 'cografya'),
('Tsunaminin en yaygın nedeni nedir?', '["Rüzgâr","Deniz altı depremi","Gelgit","Yağmur"]'::jsonb, 1, 'cografya'),
('Bir bölgede nüfus piramidinin tabanının geniş olması neyi gösterir?', '["Göçü","Yaşlı nüfusu","Genç nüfusun fazlalığını","Ölüm oranını"]'::jsonb, 2, 'cografya'),
('Aritmetik nüfus yoğunluğu nasıl hesaplanır?', '["Yüz ölçümü / nüfus","Nüfus / tarım alanı","Nüfus / gelir","Nüfus / yüz ölçümü"]'::jsonb, 3, 'cografya'),
('Tarımsal nüfus yoğunluğu neyi dikkate alır?', '["Tarım alanını","Toplam alanı","Kent alanını","Orman alanını"]'::jsonb, 0, 'cografya'),
('Kentleşme oranının artması neyi gösterir?', '["Kır nüfusunun artışını","Kent nüfusunun payının artışını","Doğum oranını","Ölüm oranını"]'::jsonb, 1, 'cografya'),
('Bir ülkede ortalama yaşam süresinin uzaması neye bağlıdır?', '["Yüzölçümüne","İklime yalnızca","Sağlık ve yaşam koşullarına","Dil sayısına"]'::jsonb, 2, 'cografya'),
('Metropol kent ne demektir?', '["Sanayi bölgesi","Küçük kasaba","Köy","Çok büyük ve etki alanı geniş kent"]'::jsonb, 3, 'cografya'),
('Kırsal yerleşmelerin en küçük birimi hangisidir?', '["Mezra","Köy","İlçe","Şehir"]'::jsonb, 0, 'cografya'),
('Yayla yerleşmelerinin kullanım amacı nedir?', '["Kış barınması","Yaz otlatması","Sanayi","Turizm yalnızca"]'::jsonb, 1, 'cografya'),
('Toplu yerleşmenin görüldüğü koşul nedir?', '["Dağınık arazi","Bol yağış","Su kaynağının sınırlı olması","Yoğun orman"]'::jsonb, 2, 'cografya'),
('Dağınık yerleşmenin görüldüğü koşul nedir?', '["Buzul","Su kıtlığı","Çöl","Su ve arazinin bol olması"]'::jsonb, 3, 'cografya'),
('Türkiye''de en fazla zeytin üretilen bölge hangisidir?', '["Ege","Doğu Anadolu","Karadeniz iç kesim","Güneydoğu"]'::jsonb, 0, 'cografya'),
('Türkiye''de muz üretiminin yapıldığı bölge hangisidir?', '["Karadeniz","Akdeniz","İç Anadolu","Doğu Anadolu"]'::jsonb, 1, 'cografya'),
('Türkiye''de tütün üretiminin öne çıktığı bölgelerden biri hangisidir?', '["Marmara iç kesim","Doğu Anadolu","Ege","Karadeniz yaylaları"]'::jsonb, 2, 'cografya'),
('Türkiye''de şeker pancarı hangi sanayi koluyla ilişkilidir?', '["Kâğıt","Tekstil","Demir-çelik","Şeker fabrikaları"]'::jsonb, 3, 'cografya'),
('Türkiye''de büyükbaş hayvancılığın yaygın olduğu bölge hangisidir?', '["Doğu Anadolu","Güneydoğu Anadolu","Akdeniz kıyısı","Ege kıyısı"]'::jsonb, 0, 'cografya'),
('Türkiye''de arıcılığın yaygın olmasının nedeni nedir?', '["Kuraklık","Bitki çeşitliliği","Yükseklik azlığı","Sanayi"]'::jsonb, 1, 'cografya'),
('Türkiye''de balıkçılığın en yoğun olduğu deniz hangisidir?', '["Ege","Akdeniz","Karadeniz","Marmara"]'::jsonb, 2, 'cografya'),
('Seracılığın yaygın olduğu Türkiye bölgesi hangisidir?', '["Karadeniz yaylaları","Doğu Anadolu","İç Anadolu","Akdeniz"]'::jsonb, 3, 'cografya'),
('Nadas uygulamasının amacı nedir?', '["Toprakta nem biriktirmek","Verimi düşürmek","Erozyonu artırmak","Tuzlanma"]'::jsonb, 0, 'cografya'),
('Türkiye''de nadasın azalmasının nedeni nedir?', '["Yağışın azalması","Sulama imkânlarının artması","Nüfusun azalması","Toprağın bozulması"]'::jsonb, 1, 'cografya'),
('Dünya''nın Güneş etrafındaki dolanımı ne kadar sürer?', '["Bir gün","Bir ay","Bir yıl","Bir hafta"]'::jsonb, 2, 'cografya'),
('Mevsimlerin oluşmasının temel nedeni nedir?', '["Rüzgârlar","Günlük hareket","Ay''ın hareketi","Eksen eğikliği ve yıllık hareket"]'::jsonb, 3, 'cografya'),
('Gece ile gündüzün oluşmasının nedeni nedir?', '["Günlük hareket","Yıllık hareket","Eksen eğikliği","Ay tutulması"]'::jsonb, 0, 'cografya'),
('Başlangıç meridyeni nereden geçer?', '["Paris","Greenwich","Roma","New York"]'::jsonb, 1, 'cografya'),
('Türkiye hangi yarım kürelerde yer alır?', '["Kuzey ve batı","Güney ve batı","Kuzey ve doğu","Güney ve doğu"]'::jsonb, 2, 'cografya'),
('Uluslararası tarih değiştirme çizgisi yaklaşık hangi boylamdadır?', '["45","0","90","180"]'::jsonb, 3, 'cografya'),
('Bir ülkenin doğusu ile batısı arasında saat farkı olması neye bağlıdır?', '["Boylam farkına","Enlem farkına","Yükseltiye","Nüfusa"]'::jsonb, 0, 'cografya'),
('Kuzey yarım kürede rüzgârların sapma yönü nedir?', '["Sola","Sağa","Sapma yok","Yukarı"]'::jsonb, 1, 'cografya'),
('Yüksek basınç alanlarında genel hava durumu nasıldır?', '["Fırtınalı","Yağışlı","Açık ve durgun","Sisli hep"]'::jsonb, 2, 'cografya'),
('Bağıl nem nedir?', '["Basınç","Toplam su miktarı","Yağış miktarı","Havanın taşıyabileceği neme oranı"]'::jsonb, 3, 'cografya'),
('Yağışın oluşabilmesi için gereken temel koşul nedir?', '["Yoğuşma","Isınma","Basınç artışı","Kuruma"]'::jsonb, 0, 'cografya'),
('Yamaç yağışları nasıl oluşur?', '["Havanın alçalmasıyla","Havanın dağ yamacında yükselmesiyle","Deniz akıntısıyla","Depremle"]'::jsonb, 1, 'cografya'),
('Cephe yağışları nasıl oluşur?', '["Yükseltiyle","Isınmayla yalnızca","Farklı hava kütlelerinin karşılaşmasıyla","Basınçla"]'::jsonb, 2, 'cografya'),

('Bir romanda "olay örgüsü" ne demektir?', '["Yazarın hayatı","Kişi listesi","Mekân tarifi","Olayların düzenlenişi"]'::jsonb, 3, 'edebiyat'),
('Bir edebî eserde tema neyi ifade eder?', '["Eserin ana düşüncesi","Sayfa sayısı","Yazım tarihi","Basımevi"]'::jsonb, 0, 'edebiyat'),
('Romanın olay dışı bölümlerinde kullanılan anlatım tekniği hangisidir?', '["Diyalog yalnızca","İç konuşma","Dipnot","Dizin"]'::jsonb, 1, 'edebiyat'),
('Geriye dönüş tekniği neyi sağlar?', '["Betimlemeyi","Geleceği anlatmayı","Geçmiş olayları aktarmayı","Ölçüyü"]'::jsonb, 2, 'edebiyat'),
('Bilinç akışı tekniği neyi yansıtır?', '["Zamanı","Diyalogları","Mekânı","Kesintisiz düşünce akışını"]'::jsonb, 3, 'edebiyat'),
('Denemenin en belirgin özelliği nedir?', '["Kişisel düşüncenin serbestçe anlatımı","Kanıt zorunluluğu","Kurgusal olay","Ölçü"]'::jsonb, 0, 'edebiyat'),
('Deneme türünün kurucusu sayılan yazar kimdir?', '["Voltaire","Montaigne","Descartes","Bacon''ın öğrencisi"]'::jsonb, 1, 'edebiyat'),
('Makale hangi amaçla yazılır?', '["Olay anlatmak","Duygu aktarmak","Bir düşünceyi kanıtlamak","Şiir yazmak"]'::jsonb, 2, 'edebiyat'),
('Fıkra (köşe yazısı) türünün özelliği nedir?', '["Kurgusal olması","Kanıt zorunluluğu","Uzun olması","Güncel konuyu kısa ele alması"]'::jsonb, 3, 'edebiyat'),
('Söyleşi (sohbet) türünün üslubu nasıldır?', '["Karşısındakiyle konuşur gibi","Resmî","Bilimsel","Şiirsel zorunlu"]'::jsonb, 0, 'edebiyat'),
('Anı türünün temel kaynağı nedir?', '["Hayal","Yaşanmış olaylar","İstatistik","Deney"]'::jsonb, 1, 'edebiyat'),
('Günlük türünün ayırt edici özelliği nedir?', '["Ölçülü olması","Kurgusal olması","Tarih atılarak yazılması","Uzun olması"]'::jsonb, 2, 'edebiyat'),
('Biyografi neyi anlatır?', '["Bir kavramı","Bir olayı","Bir yeri","Bir kişinin yaşamını"]'::jsonb, 3, 'edebiyat'),
('Otobiyografi kimin kaleminden çıkar?', '["Kişinin kendisinden","Bir tarihçiden","Bir eleştirmenden","Bir gazeteciden"]'::jsonb, 0, 'edebiyat'),
('Gezi yazısının konusu nedir?', '["Hayaller","Gezilip görülen yerler","Bilimsel deney","Rüyalar"]'::jsonb, 1, 'edebiyat'),
('Röportajın gazete haberinden farkı nedir?', '["Resimsiz olması","Kısa olması","Araştırma ve yorum içermesi","Kurgusal olması"]'::jsonb, 2, 'edebiyat'),
('Eleştiri türünün ölçütü ne olmalıdır?', '["Satış","Kişisel düşmanlık","Reklam","Nesnel değerlendirme"]'::jsonb, 3, 'edebiyat'),
('Mektup türünün edebiyattaki yeri nedir?', '["Edebî mektuplar tür sayılır","Edebî değeri yoktur","Yalnız resmîdir","Şiirdir"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında "Cumhuriyet Dönemi" ne zaman başlar?', '["1839","1923 sonrası","1876","1960"]'::jsonb, 1, 'edebiyat'),
('Beş Hececiler hangi ölçüyü benimsemiştir?', '["Serbest","Aruz","Hece","Karışık"]'::jsonb, 2, 'edebiyat'),
('Yedi Meşaleciler hangi dönemde ortaya çıkmıştır?', '["Divan","Tanzimat","Servet-i Fünun","Cumhuriyet"]'::jsonb, 3, 'edebiyat'),
('Necip Fazıl Kısakürek hangi türde tanınır?', '["Şiir ve tiyatro","Roman yalnızca","Fabl","Anı yalnızca"]'::jsonb, 0, 'edebiyat'),
('"Kaldırımlar" şiiri kime aittir?', '["Cahit Sıtkı","Necip Fazıl Kısakürek","Ahmet Muhip","Orhan Veli"]'::jsonb, 1, 'edebiyat'),
('Ahmet Haşim şiirinde neyi öne çıkarır?', '["Belgesellik","Nesnel anlatım","Musiki ve imge","Öğreticilik"]'::jsonb, 2, 'edebiyat'),
('Yahya Kemal Beyatlı şiirinde hangi biçimi kullanmıştır?', '["Ölçüsüz","Yalnız serbest","Yalnız hece","Aruz ağırlıklı"]'::jsonb, 3, 'edebiyat'),
('Faruk Nafiz Çamlıbel''in Anadolu''yu anlatan ünlü şiiri hangisidir?', '["Han Duvarları","Kaldırımlar","Otuz Beş Yaş","Sessiz Gemi"]'::jsonb, 0, 'edebiyat'),
('"Sessiz Gemi" şiiri kime aittir?', '["Ahmet Haşim","Yahya Kemal Beyatlı","Tevfik Fikret","Cenap Şahabettin"]'::jsonb, 1, 'edebiyat'),
('Behçet Necatigil hangi türde ürün vermiştir?', '["Fabl","Roman","Şiir","Destan"]'::jsonb, 2, 'edebiyat'),
('Attila İlhan''ın edebiyatta öne çıkan yönü nedir?', '["Yalnız çeviri","Yalnız fabl","Yalnız anı","Şiir ve roman"]'::jsonb, 3, 'edebiyat'),
('Cemal Süreya hangi şiir akımıyla anılır?', '["İkinci Yeni","Garip","Beş Hececiler","Fecr-i Ati"]'::jsonb, 0, 'edebiyat'),
('Turgut Uyar hangi akımın şairlerindendir?', '["Garip","İkinci Yeni","Milli Edebiyat","Servet-i Fünun"]'::jsonb, 1, 'edebiyat'),
('Edip Cansever hangi dönemin şairidir?', '["Divan","Tanzimat","Cumhuriyet sonrası modern şiir","Halk"]'::jsonb, 2, 'edebiyat'),
('Orhan Veli''nin "Anlatamıyorum" şiiri hangi anlayışa örnektir?', '["Destan","Ağır Osmanlıca","Aruz","Sade ve gündelik dil"]'::jsonb, 3, 'edebiyat'),
('Melih Cevdet Anday hangi akımın kurucularındandır?', '["Garip","İkinci Yeni","Beş Hececiler","Fecr-i Ati"]'::jsonb, 0, 'edebiyat'),
('Kafiyeden sonra gelen aynı görevdeki eklere ne denir?', '["Durak","Redif","Mahlas","Vezin"]'::jsonb, 1, 'edebiyat'),
('Tek ses benzerliğine dayanan kafiye türü hangisidir?', '["Zengin kafiye","Tam kafiye","Yarım kafiye","Cinaslı kafiye"]'::jsonb, 2, 'edebiyat'),
('İki ses benzerliğine dayanan kafiye türü hangisidir?', '["Redif","Yarım kafiye","Zengin kafiye","Tam kafiye"]'::jsonb, 3, 'edebiyat'),
('Üç ve daha fazla ses benzerliği olan kafiye hangisidir?', '["Zengin kafiye","Yarım kafiye","Tam kafiye","Cinas"]'::jsonb, 0, 'edebiyat'),
('Dört dizeden oluşan nazım birimine ne denir?', '["Beyit","Dörtlük","Bent","Mısra"]'::jsonb, 1, 'edebiyat'),
('İki dizeden oluşan nazım birimine ne denir?', '["Bent","Dörtlük","Beyit","Kıta"]'::jsonb, 2, 'edebiyat'),
('Divan şiirinde en yaygın nazım şekli hangisidir?', '["Mani","Koşma","Türkü","Gazel"]'::jsonb, 3, 'edebiyat'),
('Gazelin konusu genellikle nedir?', '["Aşk ve güzellik","Savaş","Bilim","Tarım"]'::jsonb, 0, 'edebiyat'),
('Kaside hangi amaçla yazılır?', '["Yergi yalnızca","Övgü","Ağıt","Masal"]'::jsonb, 1, 'edebiyat'),
('Mesnevi nazım şeklinin özelliği nedir?', '["Dörtlük","Tek kafiye","Her beytin kendi içinde kafiyeli olması","Ölçüsüzlük"]'::jsonb, 2, 'edebiyat'),
('Rubai kaç dizeden oluşur?', '["8","2","5","4"]'::jsonb, 3, 'edebiyat'),
('Halk şiirinde ölen kişinin ardından söylenen türe ne denir?', '["Ağıt","Koşma","Semai","Destan"]'::jsonb, 0, 'edebiyat'),
('Mani kaç dizeden oluşur?', '["2","4","6","8"]'::jsonb, 1, 'edebiyat'),
('Koşmanın ölçüsü nedir?', '["Serbest","Aruz","11''li hece","7''li hece"]'::jsonb, 2, 'edebiyat'),
('Semai halk şiirinde hangi ölçüyle söylenir?', '["Serbest","11''li hece","Aruz","8''li hece"]'::jsonb, 3, 'edebiyat'),
('Taşlama türünde ne yapılır?', '["Eleştiri ve yergi","Övgü","Ağıt","Öğüt yalnızca"]'::jsonb, 0, 'edebiyat'),
('Nefes hangi geleneğin nazım türüdür?', '["Divan","Alevi-Bektaşi","Servet-i Fünun","Garip"]'::jsonb, 1, 'edebiyat'),
('İlahi türünün konusu nedir?', '["Aşk yalnızca","Savaş","Dinî-tasavvufi duygular","Doğa yalnızca"]'::jsonb, 2, 'edebiyat'),
('Yunus Emre''nin şiirlerinin dil özelliği nedir?', '["Karışık aruz","Ağır Arapça","Farsça","Sade Türkçe"]'::jsonb, 3, 'edebiyat'),
('Hacı Bektaş Veli hangi eseriyle bilinir?', '["Makalat","Divan","Mesnevi","Şehname"]'::jsonb, 0, 'edebiyat'),
('Mevlana''nın Farsça yazdığı ünlü eseri hangisidir?', '["Divanü Lügat","Mesnevi","Kutadgu Bilig","Şehname"]'::jsonb, 1, 'edebiyat'),
('"Kutadgu Bilig" hangi konuyu işler?', '["Savaş","Aşk","Devlet yönetimi ve erdem","Ticaret"]'::jsonb, 2, 'edebiyat'),
('"Divanü Lügati''t-Türk" nasıl bir eserdir?', '["Şiir kitabı","Roman","Destan","Sözlük"]'::jsonb, 3, 'edebiyat'),
('"Atabetü''l Hakayık" hangi konuda yazılmıştır?', '["Ahlak ve öğüt","Tarih","Coğrafya","Tıp"]'::jsonb, 0, 'edebiyat'),
('Ali Şir Nevai hangi dilin edebî gücünü savunmuştur?', '["Arapça","Türkçe","Farsça","Moğolca"]'::jsonb, 1, 'edebiyat'),
('Karagöz ve Hacivat hangi geleneksel türdendir?', '["Bale","Opera","Gölge oyunu","Roman"]'::jsonb, 2, 'edebiyat'),
('Ortaoyunu''nun sahnelendiği yer nasıldır?', '["Radyo","Kapalı sahne zorunlu","Sinema","Açık alan"]'::jsonb, 3, 'edebiyat'),
('Meddah ne yapar?', '["Tek başına hikâye anlatır","Koro yönetir","Dans eder","Resim yapar"]'::jsonb, 0, 'edebiyat'),
('Tiyatroda "trajedi"nin konusu nedir?', '["Günlük komik olaylar","Soylu kişilerin acıklı sonu","Fabl","Belgesel"]'::jsonb, 1, 'edebiyat'),
('Tiyatroda "komedi" neyi amaçlar?', '["Bilgi vermek yalnızca","Ağlatmak","Güldürerek düşündürmek","Ölçü öğretmek"]'::jsonb, 2, 'edebiyat'),
('Dram türünün özelliği nedir?', '["Ölçülü olması","Yalnız acıklı","Yalnız gülünç","Acıklı ve gülünç yanları birlikte vermesi"]'::jsonb, 3, 'edebiyat'),
('Tiyatroda "perde" ne anlama gelir?', '["Oyunun büyük bölümü","Kostüm","Sahne ışığı","Seyirci"]'::jsonb, 0, 'edebiyat'),
('Tiyatro metninde replik nedir?', '["Sahne tarifi","Oyuncunun söyleyeceği söz","Başlık","Dipnot"]'::jsonb, 1, 'edebiyat'),
('Klasisizm akımının temel aldığı kaynak nedir?', '["Doğu masalları","Orta Çağ","Antik Yunan ve Latin","Halk şiiri"]'::jsonb, 2, 'edebiyat'),
('Romantizm akımının öne çıkardığı unsur nedir?', '["İstatistik","Akıl ve kural","Deney","Duygu ve hayal"]'::jsonb, 3, 'edebiyat'),
('Realizm akımının temel ilkesi nedir?', '["Gerçeği olduğu gibi yansıtmak","Hayali anlatmak","Abartmak","Öğüt vermek"]'::jsonb, 0, 'edebiyat'),
('Natüralizm hangi bilimden etkilenmiştir?', '["Matematik","Doğa bilimleri","Hukuk","Tarih"]'::jsonb, 1, 'edebiyat'),
('Parnasizm hangi türde etkili olmuştur?', '["Tiyatro","Roman","Şiir","Deneme"]'::jsonb, 2, 'edebiyat'),
('Sembolizm neyi öne çıkarır?', '["Kanıt","Kesin gözlem","Belge","Sezgi ve musiki"]'::jsonb, 3, 'edebiyat'),
('Sürrealizm neyden beslenir?', '["Bilinçaltı ve rüya","Deney","İstatistik","Tarih belgesi"]'::jsonb, 0, 'edebiyat'),
('Egzistansiyalizm edebiyata hangi kavramı taşımıştır?', '["Toplumsal sınıf","Bireyin varoluşu","Doğa yasası","Kader"]'::jsonb, 1, 'edebiyat'),
('"Madame Bovary" kimin eseridir?', '["Stendhal","Victor Hugo","Gustave Flaubert","Zola"]'::jsonb, 2, 'edebiyat'),
('Balzac''ın roman dizisinin adı nedir?', '["Rougon-Macquart","İlahi Komedya","Kayıp Zaman","İnsanlık Komedyası"]'::jsonb, 3, 'edebiyat'),
('"Robinson Crusoe" kimin eseridir?', '["Daniel Defoe","Jonathan Swift","Henry Fielding","Samuel Richardson"]'::jsonb, 0, 'edebiyat'),
('"Güliver''in Gezileri" kimin eseridir?', '["Daniel Defoe","Jonathan Swift","Charles Dickens","Walter Scott"]'::jsonb, 1, 'edebiyat'),
('Charles Dickens''ın romanlarında öne çıkan tema nedir?', '["Deniz savaşları","Uzay","Sanayi dönemi yoksulluğu","Fabl"]'::jsonb, 2, 'edebiyat'),
('"Oliver Twist" kimin eseridir?', '["Wilkie Collins","Thomas Hardy","Bronte kardeşler","Charles Dickens"]'::jsonb, 3, 'edebiyat'),
('"Suç ve Ceza" romanının başkahramanı kimdir?', '["Raskolnikov","Aleksey","Pierre","Levin"]'::jsonb, 0, 'edebiyat'),
('"Savaş ve Barış" hangi ülkenin edebiyatına aittir?', '["Fransız","Rus","İngiliz","Alman"]'::jsonb, 1, 'edebiyat'),
('"Ölü Canlar" kimin eseridir?', '["Çehov","Turgenyev","Nikolay Gogol","Puşkin"]'::jsonb, 2, 'edebiyat'),
('Puşkin hangi edebiyatın kurucu isimlerindendir?', '["Macar","Polonya","Çek","Rus"]'::jsonb, 3, 'edebiyat'),
('"Sanat Sanat İçindir" görüşü hangi anlayışı savunur?', '["Sanatın kendi başına amaç olduğunu","Sanatın topluma hizmetini","Sanatın ticaretini","Sanatın yasaklanmasını"]'::jsonb, 0, 'edebiyat'),
('"Toplum İçin Sanat" anlayışını benimseyen Tanzimat sanatçısı kimdir?', '["Recaizade Ekrem","Namık Kemal","Abdülhak Hamit","Cenap Şahabettin"]'::jsonb, 1, 'edebiyat'),
('Tanzimat edebiyatının birinci döneminde amaç neydi?', '["Aruzu bırakmamak","Sanatı gizlemek","Halkı bilinçlendirmek","Yalnız eğlendirmek"]'::jsonb, 2, 'edebiyat'),
('Ziya Paşa''nın ünlü eseri hangisidir?', '["Araba Sevdası","Şair Evlenmesi","İntibah","Terkib-i Bent"]'::jsonb, 3, 'edebiyat'),
('Şinasi''nin Türk edebiyatına kazandırdığı tür hangisidir?', '["Makale","Roman","Destan","Mesnevi"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında ilk resmî gazete hangisidir?', '["Tercüman-ı Ahval","Takvim-i Vekayi","Tasvir-i Efkâr","Servet-i Fünun"]'::jsonb, 1, 'edebiyat'),
('Fecr-i Ati topluluğu hangi anlayışı benimsemiştir?', '["Belgesel anlatım","Toplum için sanat","Sanat şahsi ve muhteremdir","Halk dili"]'::jsonb, 2, 'edebiyat'),
('Bir eserde "mekân" neyi ifade eder?', '["Tema","Olayın zamanı","Kişiler","Olayın geçtiği yer"]'::jsonb, 3, 'edebiyat'),
('Roman kişilerinden olayı sürükleyene ne denir?', '["Başkişi","Figüran","Anlatıcı","Yazar"]'::jsonb, 0, 'edebiyat'),
('Bir eserde karşıt karakter için kullanılan terim nedir?', '["Yardımcı kişi","Karşı güç","Anlatıcı","Okur"]'::jsonb, 1, 'edebiyat'),
('Bir metnin dil ve anlatım özelliklerine ne denir?', '["Konu","Tema","Üslup","Olay"]'::jsonb, 2, 'edebiyat'),
('Edebî metinlerde çağrışım gücü yüksek dile ne denir?', '["Resmî dil","Terimsel dil","Bilimsel dil","Yan anlamlı dil"]'::jsonb, 3, 'edebiyat'),
('Öğretici metinlerde kullanılan dil nasıldır?', '["Açık ve kesin","Kapalı","İmgeli","Ölçülü"]'::jsonb, 0, 'edebiyat'),
('Bir eserin ilk basımına ne denir?', '["Tıpkıbasım","İlk baskı","Çeviri","Uyarlama"]'::jsonb, 1, 'edebiyat'),
('Orhan Pamuk''un İstanbul''u anlattığı kitabı hangisidir?', '["Benim Adım Kırmızı","Kar","İstanbul: Hatıralar ve Şehir","Sessiz Ev"]'::jsonb, 2, 'edebiyat'),
('"Benim Adım Kırmızı" romanı hangi sanat dalını konu alır?', '["Sinema","Heykel","Bale","Minyatür"]'::jsonb, 3, 'edebiyat'),
('Latife Tekin''in anlatımında öne çıkan özellik nedir?', '["Masalsı gerçekçilik","Belgesellik","Bilimsellik","Ölçülü şiir"]'::jsonb, 0, 'edebiyat'),
('Adalet Ağaoğlu hangi türde eser vermiştir?', '["Yalnız şiir","Roman ve oyun","Yalnız fabl","Yalnız çeviri"]'::jsonb, 1, 'edebiyat'),
('Bilge Karasu''nun anlatımının özelliği nedir?', '["Basit dil","Gazete dili","Deneysel ve yoğun dil","Ölçülü şiir"]'::jsonb, 2, 'edebiyat'),
('Ahmet Ümit hangi türde tanınır?', '["Aruz şiiri","Fabl","Destan","Polisiye roman"]'::jsonb, 3, 'edebiyat')

on conflict (soru) do nothing;

-- ===================== KARIŞTIRMA =====================
-- Doğru cevap hep aynı şıkta olmasın: SADECE bu partide eklenen soruların
-- şıkları karıştırılır. `created_at >= transaction_timestamp()` koşulu
-- ZORUNLUDUR; onsuz tüm havuzun şıkları karışır ve o an oynanan maçlarda
-- şık indeksleri kayar.
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
