-- Soru havuzu genişletme: sanat +33, tarih +26, teknoloji +26, edebiyat +28, bilim +28
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Tiyatroda ''trajedi'' türünün temel özelliği nedir?', '["Acıklı sonla biten ciddi olay","Güldürücü olması","Müzikli olması","Kısa olması"]'::jsonb, 0, 'sanat'),
('Dram türü neyi birleştirir?', '["Yalnız acıklıyı","Acıklı ve gülünç yanları","Yalnız gülünçü","Müzik ve dansı"]'::jsonb, 1, 'sanat'),
('Antik Yunan tiyatrosunda koro ne yapardı?', '["Dans ederdi yalnızca","Bilet satardı","Olayı yorumlayıp aktarırdı","Dekor kurardı"]'::jsonb, 2, 'sanat'),
('Tiyatroda ''üç birlik kuralı'' neyi kapsar?', '["Oyuncu, dekor, ışık","Ses, ışık, kostüm","Perde, sahne, koro","Yer, zaman ve olay birliği"]'::jsonb, 3, 'sanat'),
('Ortaoyunu hangi geleneksel Türk tiyatro biçimidir?', '["Açık alanda doğaçlama oyun","Gölge oyunu","Kukla","Opera"]'::jsonb, 0, 'sanat'),
('Meddah geleneğinde anlatıcı kaç kişidir?', '["İki kişi","Tek kişi","Bir topluluk","Koro"]'::jsonb, 1, 'sanat'),
('Modern tiyatroda ''epik tiyatro'' kavramı kime aittir?', '["Stanislavski","Ibsen","Bertolt Brecht","Beckett"]'::jsonb, 2, 'sanat'),
('Stanislavski yöntemi neyi öğretir?', '["Sahne tasarımını","Işık düzenini","Bilet satışını","Oyuncunun rolü içselleştirmesini"]'::jsonb, 3, 'sanat'),
('Absürt tiyatronun temsilcilerinden biri kimdir?', '["Samuel Beckett","Shakespeare","Molière","Çehov"]'::jsonb, 0, 'sanat'),
('Fotoğrafın icadında öne çıkan isimlerden biri kimdir?', '["Thomas Edison","Louis Daguerre","Nikola Tesla","Alexander Bell"]'::jsonb, 1, 'sanat'),
('Fotoğrafçılıkta ''poz süresi'' neyi belirler?', '["Renk sayısını","Çözünürlüğü","Sensöre ulaşan ışık süresini","Odak uzaklığını"]'::jsonb, 2, 'sanat'),
('Fotoğrafta ''kompozisyon'' neyi ifade eder?', '["Baskı kâğıdı","Işık kaynağı türü","Poz süresi","Kadraj içi düzenleme"]'::jsonb, 3, 'sanat'),
('Üçte bir kuralı fotoğrafta neyi önerir?', '["Ana öğeyi çizgi kesişimine yerleştirmeyi","Ortaya koymayı hep","Kenara itmeyi","Yakın çekmeyi"]'::jsonb, 0, 'sanat'),
('Siyah beyaz fotoğrafta vurgulanan öğe nedir?', '["Renk uyumu","Işık, gölge ve doku","Renk sıcaklığı","Doygunluk"]'::jsonb, 1, 'sanat'),
('Belgesel fotoğrafın amacı nedir?', '["Ürün tanıtmak","Soyut biçim üretmek","Gerçeği tanıklıkla aktarmak","Moda göstermek"]'::jsonb, 2, 'sanat'),
('Grafik tasarımda ''tipografi'' neyi konu alır?', '["Fotoğraf seçimini","Renk basımını","Kâğıt kalınlığını","Yazı karakteri ve düzenini"]'::jsonb, 3, 'sanat'),
('Logonun tasarımdaki işlevi nedir?', '["Marka kimliğini simgelemek","Ürün açıklaması","Fiyat bilgisi","Kullanım kılavuzu"]'::jsonb, 0, 'sanat'),
('Işıkta renklerin ana üçlüsü hangisidir?', '["Sarı, mavi, kırmızı","Kırmızı, yeşil, mavi","Camgöbeği, macenta, sarı","Siyah, beyaz, gri"]'::jsonb, 1, 'sanat'),
('Baskıda kullanılan renk sistemi hangisidir?', '["RGB","HSL","CMYK","LAB dışı hiçbiri"]'::jsonb, 2, 'sanat'),
('Doygunluk (satürasyon) neyi ifade eder?', '["Rengin açıklığını","Rengin sıcaklığını","Rengin adını","Rengin canlılık derecesini"]'::jsonb, 3, 'sanat'),
('Sanat eserinde ''denge'' ilkesi neyi sağlar?', '["Görsel ağırlığın dağılımını","Renk sayısını","Boyutu","Malzemeyi"]'::jsonb, 0, 'sanat'),
('Kompozisyonda ''ritim'' neyle oluşur?', '["Tek öğeyle","Öğelerin yinelenmesiyle","Renksizlikle","Boşlukla yalnızca"]'::jsonb, 1, 'sanat'),
('Sanatta ''vurgu'' (odak) neyi sağlar?', '["Rengi soldurmayı","Boyutu büyütmeyi","Bakışı belirli noktaya çekmeyi","Dokuyu silmeyi"]'::jsonb, 2, 'sanat'),
('Altın oran sanatta neyi ifade eder?', '["Altın kullanımı","Sarı renk","Simetri zorunluluğu","Uyumlu kabul edilen oran ilişkisi"]'::jsonb, 3, 'sanat'),
('Simetri ile asimetri arasındaki fark nedir?', '["Asimetride eşitliğin bozulması","Simetride renk olmaması","Asimetride boşluk olmaması","İkisinin aynı olması"]'::jsonb, 0, 'sanat'),
('Negatif alan (boşluk) tasarımda ne sağlar?', '["Renk artışını","Ana öğenin okunurluğunu","Doku artışını","Ağırlık artışını"]'::jsonb, 1, 'sanat'),
('Müzede ''koleksiyon'' ne demektir?', '["Serginin adı","Bilet türü","Kurumun sahip olduğu eser bütünü","Katalog"]'::jsonb, 2, 'sanat'),
('Sanat eserinin ''provenans''ı neyi belgeler?', '["Eserin fiyatını","Eserin boyutunu","Eserin rengini","Eserin sahiplik geçmişini"]'::jsonb, 3, 'sanat'),
('Sanat eserinde sahtecilik neyle tespit edilir?', '["Malzeme ve teknik analizle","Fiyatına bakarak","Boyutuna bakarak","Adına bakarak"]'::jsonb, 0, 'sanat'),
('Louvre Müzesi hangi ülkededir?', '["İtalya","Fransa","İspanya","İngiltere"]'::jsonb, 1, 'sanat'),
('Ermitaj Müzesi hangi şehirdedir?', '["Moskova","Kiev","Saint Petersburg","Varşova"]'::jsonb, 2, 'sanat'),
('İstanbul Arkeoloji Müzeleri''nde sergilenen İskender Lahdi nereden çıkarılmıştır?', '["Efes","Bergama","Truva","Sayda (Sidon)"]'::jsonb, 3, 'sanat'),
('Anadolu Medeniyetleri Müzesi hangi şehirdedir?', '["Ankara","İzmir","Konya","Antalya"]'::jsonb, 0, 'sanat'),
('Osmanlı''da divan-ı hümayun neyi ifade eder?', '["Devlet işlerinin görüşüldüğü kurul","Askerî birlik","Vergi dairesi","Mahkeme binası"]'::jsonb, 0, 'tarih'),
('Osmanlı''da şeyhülislamın görevi neydi?', '["Orduyu yönetmek","Dinî hukuki görüş vermek","Vergi toplamak","Kale yapmak"]'::jsonb, 1, 'tarih'),
('Osmanlı''da kapitülasyonlar neydi?', '["Askerî antlaşmalar","Toprak bağışları","Yabancılara tanınan ticari ayrıcalıklar","Vergi türleri"]'::jsonb, 2, 'tarih'),
('Osmanlı''da Lale Devri hangi alanla anılır?', '["Askerî fetihler","İç savaş","Ekonomik çöküş","Kültür ve imar etkinlikleri"]'::jsonb, 3, 'tarih'),
('Yeniçeri Ocağı''nı kaldıran padişah kimdir?', '["II. Mahmud","III. Selim","Abdülmecid","II. Abdülhamid"]'::jsonb, 0, 'tarih'),
('Islahat Fermanı hangi yıl ilan edilmiştir?', '["1839","1856","1876","1908"]'::jsonb, 1, 'tarih'),
('Kanun-i Esasi neyi ifade eder?', '["Bir vergi kanunu","Bir ferman","Osmanlı''nın ilk anayasası","Bir antlaşma"]'::jsonb, 2, 'tarih'),
('Balkan Savaşları sonucunda Osmanlı ne kaybetmiştir?', '["Anadolu''yu","Kuzey Afrika''yı","Kırım''ı","Balkanlardaki toprakların çoğunu"]'::jsonb, 3, 'tarih'),
('Sevr Antlaşması neyi öngörüyordu?', '["Osmanlı topraklarının paylaşılmasını","Bağımsızlığın tanınmasını","Ateşkesi","Ticaret serbestisini"]'::jsonb, 0, 'tarih'),
('Erzurum Kongresi''nin niteliği nedir?', '["Yalnız yerel karar alması","Bölgesel toplanıp ulusal karar alması","Uluslararası olması","Askerî tören olması"]'::jsonb, 1, 'tarih'),
('Sivas Kongresi''nin en önemli kararı nedir?', '["Saltanatın kaldırılması","Cumhuriyetin ilanı","Ulusal derneklerin birleştirilmesi","Harf değişimi"]'::jsonb, 2, 'tarih'),
('Misak-ı Milli neyi belirlemiştir?', '["Vergi oranlarını","Eğitim programını","Para birimini","Ulusal sınırların esaslarını"]'::jsonb, 3, 'tarih'),
('İnönü Savaşları hangi cephede yapılmıştır?', '["Batı Cephesi","Doğu Cephesi","Güney Cephesi","Kafkas Cephesi"]'::jsonb, 0, 'tarih'),
('Kars Antlaşması hangi ülkelerle imzalanmıştır?', '["Yunanistan''la","Kafkas cumhuriyetleriyle","İtalya''yla","İngiltere''yle"]'::jsonb, 1, 'tarih'),
('Mudanya Ateşkesi neyi sağlamıştır?', '["Cumhuriyetin ilanını","Saltanatın kalkmasını","Silahlı çatışmanın sona ermesini","Anayasanın kabulünü"]'::jsonb, 2, 'tarih'),
('Ankara hangi yıl başkent olmuştur?', '["1920","1922","1924","1923"]'::jsonb, 3, 'tarih'),
('Ölçü birimlerinde metrik sisteme geçiş hangi yıl olmuştur?', '["1931","1923","1926","1938"]'::jsonb, 0, 'tarih'),
('Türkiye Birleşmiş Milletler''e hangi yıl üye olmuştur?', '["1923","1945","1939","1952"]'::jsonb, 1, 'tarih'),
('Çok partili hayata geçiş Türkiye''de hangi dönemde hızlanmıştır?', '["1923 sonrası","1930''lar","1946 sonrası","1960''lar"]'::jsonb, 2, 'tarih'),
('Sanayi Devrimi''nin toplumsal sonucu nedir?', '["Feodalitenin güçlenmesi","Kentlerin küçülmesi","Tarımın büyümesi","İşçi sınıfının doğuşu"]'::jsonb, 3, 'tarih'),
('Sömürgeciliğin temel amacı neydi?', '["Hammadde ve pazar elde etmek","Kültür alışverişi","Eğitim yaymak","Bilim üretmek"]'::jsonb, 0, 'tarih'),
('Berlin Konferansı hangi konuda toplanmıştır?', '["Asya''nın birleşmesi","Afrika''nın paylaşımı","Amerika''nın keşfi","Avrupa barışı"]'::jsonb, 1, 'tarih'),
('Berlin Duvarı hangi iki bölgeyi ayırıyordu?', '["Kuzey ve Güney Almanya","Polonya ve Almanya","Doğu ve Batı Berlin","Avusturya ve Almanya"]'::jsonb, 2, 'tarih'),
('Apartheid rejimi hangi ülkede uygulanmıştır?', '["Nijerya","Kenya","Mısır","Güney Afrika"]'::jsonb, 3, 'tarih'),
('Nelson Mandela hangi mücadeleyle anılır?', '["Irk ayrımcılığına karşı mücadele","Sömürgeciliği savunma","Ekonomik reform","Askerî darbe"]'::jsonb, 0, 'tarih'),
('Avrupa Birliği''nin temeli hangi topluluğa dayanır?', '["NATO","Avrupa Kömür ve Çelik Topluluğu","Varşova Paktı","Birleşmiş Milletler"]'::jsonb, 1, 'tarih'),
('Bilgisayarın ''girdi birimi''ne örnek hangisidir?', '["Klavye","Yazıcı","Monitör","Hoparlör"]'::jsonb, 0, 'teknoloji'),
('Bilgisayarın ''çıktı birimi''ne örnek hangisidir?', '["Fare","Yazıcı","Tarayıcı","Mikrofon"]'::jsonb, 1, 'teknoloji'),
('Dokunmatik ekran hangi birim sayılır?', '["Yalnız girdi","Yalnız çıktı","Hem girdi hem çıktı","Depolama"]'::jsonb, 2, 'teknoloji'),
('USB bağlantısının avantajı nedir?', '["Yalnız yazıcıya uyması","Kablosuz olması","Elektrik vermemesi","Çoklu cihaz için ortak standart"]'::jsonb, 3, 'teknoloji'),
('Modem ile router arasındaki fark nedir?', '["Modemin internet sinyalini dönüştürmesi","Router''ın kablo olması","Modemin yazıcı olması","İkisinin aynı olması"]'::jsonb, 0, 'teknoloji'),
('Gecikme (latency) neyi ölçer?', '["Veri miktarını","Verinin gidiş-dönüş süresini","Kablo kalınlığını","Cihaz sayısını"]'::jsonb, 1, 'teknoloji'),
('Sıkıştırılmış dosya biçimlerinden biri hangisidir?', '["TXT","BMP","ZIP","WAV"]'::jsonb, 2, 'teknoloji'),
('Ses dosyası biçimlerinden kayıplı olan hangisidir?', '["WAV","FLAC","AIFF","MP3"]'::jsonb, 3, 'teknoloji'),
('Video kodeği ne yapar?', '["Videoyu kodlar ve çözer","Videoyu kaydeder yalnızca","Ekranı açar","Ses üretir"]'::jsonb, 0, 'teknoloji'),
('Akış (streaming) teknolojisinde ''tampon'' ne sağlar?', '["Kalite artışı","Önden veri tutup kesintiyi önlemeyi","Dosya küçültme","Ses eşitleme"]'::jsonb, 1, 'teknoloji'),
('Bit hızı (bitrate) neyi etkiler?', '["Ekran boyutunu","Kablo uzunluğunu","Ses veya videonun kalitesini ve boyutunu","Cihaz sayısını"]'::jsonb, 2, 'teknoloji'),
('E-posta protokollerinden gönderme için kullanılan hangisidir?', '["POP3","IMAP","FTP","SMTP"]'::jsonb, 3, 'teknoloji'),
('IMAP protokolünün POP3''e üstünlüğü nedir?', '["İletileri sunucuda senkron tutması","Daha hızlı olması","Şifrelemesi","Ek dosya desteği"]'::jsonb, 0, 'teknoloji'),
('FTP protokolü ne için kullanılır?', '["E-posta gönderme","Dosya aktarımı","Sayfa gösterme","Ses akışı"]'::jsonb, 1, 'teknoloji'),
('SSH protokolü ne sağlar?', '["Dosya sıkıştırma","Sayfa tasarımı","Şifreli uzak erişim","Ses aktarımı"]'::jsonb, 2, 'teknoloji'),
('Terminal (komut satırı) ne sağlar?', '["Grafik tasarım","Video kurgu","Ses kaydı","Metin komutlarıyla sistem yönetimi"]'::jsonb, 3, 'teknoloji'),
('Betik (script) dili ne için kullanılır?', '["Görevleri otomatikleştirmek","Donanım üretmek","Kablo döşemek","Ekran yapmak"]'::jsonb, 0, 'teknoloji'),
('Değişken programlamada neyi ifade eder?', '["Bir komut","Veriyi saklayan adlandırılmış alan","Bir dosya","Bir cihaz"]'::jsonb, 1, 'teknoloji'),
('Koşul ifadesi ne sağlar?', '["Sonsuz tekrarı","Veri silmeyi","Duruma göre farklı yol izlemeyi","Hız artışını"]'::jsonb, 2, 'teknoloji'),
('Fonksiyon (işlev) ne sağlar?', '["Kodun silinmesi","Ekran açılması","Ağ kurulması","Kodun yeniden kullanılabilmesi"]'::jsonb, 3, 'teknoloji'),
('Dizi (array) ile liste arasındaki ortak yan nedir?', '["Sıralı veri saklamaları","Tek değer tutmaları","Görüntü olmaları","Ağ kurmaları"]'::jsonb, 0, 'teknoloji'),
('Sözlük (dictionary) veri yapısı neye dayanır?', '["Sıralı indekse","Anahtar-değer eşlemesine","Ağaç yapısına","Bağlı listeye"]'::jsonb, 1, 'teknoloji'),
('Bağlı liste (linked list) neyi kolaylaştırır?', '["Rastgele erişimi","Sıralamayı","Ekleme ve silme işlemlerini","Şifrelemeyi"]'::jsonb, 2, 'teknoloji'),
('Ağaç veri yapısında ''kök'' nedir?', '["En alttaki düğüm","Orta düğüm","Boş düğüm","En üstteki düğüm"]'::jsonb, 3, 'teknoloji'),
('Graf veri yapısı neyi modeller?', '["Düğümler arası ilişkileri","Sıralı listeyi","Tek değeri","Metni"]'::jsonb, 0, 'teknoloji'),
('Big-O gösterimi neyi anlatır?', '["Kod satır sayısını","Algoritmanın büyüme davranışını","Dosya boyutunu","Ekran çözünürlüğünü"]'::jsonb, 1, 'teknoloji'),
('Şiirde ''imge'' ne anlama gelir?', '["Zihinde canlanan özgün tasarım","Ölçü türü","Kafiye şeması","Nazım biçimi"]'::jsonb, 0, 'edebiyat'),
('Serbest nazımın özelliği nedir?', '["Aruz kullanması","Ölçü ve kafiye zorunluluğu olmaması","Hece kullanması","Beyit zorunluluğu"]'::jsonb, 1, 'edebiyat'),
('Dize (mısra) nedir?', '["İki satırlık birim","Dörtlük","Şiirin bir satırı","Bölüm"]'::jsonb, 2, 'edebiyat'),
('Dörtlük kaç dizeden oluşur?', '["İki","Üç","Altı","Dört"]'::jsonb, 3, 'edebiyat'),
('Sone nazım biçimi kaç dizeden oluşur?', '["On dört","Dört","Sekiz","Yirmi"]'::jsonb, 0, 'edebiyat'),
('Terza rima hangi edebiyattan gelir?', '["İngiliz","İtalyan","Alman","Rus"]'::jsonb, 1, 'edebiyat'),
('Haiku nazım biçimi hangi ülkeye aittir?', '["Çin","Kore","Japonya","Vietnam"]'::jsonb, 2, 'edebiyat'),
('Epik şiirin konusu nedir?', '["Aşk ve doğa","Ölüm acısı","Öğüt","Kahramanlık ve savaş"]'::jsonb, 3, 'edebiyat'),
('Lirik şiirin özelliği nedir?', '["Duyguları yoğun anlatması","Olay anlatması","Öğretmesi","Eleştirmesi"]'::jsonb, 0, 'edebiyat'),
('Didaktik şiirin amacı nedir?', '["Duygu aktarmak","Öğretmek ve bilgi vermek","Olay anlatmak","Güldürmek"]'::jsonb, 1, 'edebiyat'),
('Pastoral şiirin konusu nedir?', '["Kent yaşamı","Savaş","Kır ve çoban yaşamı","Bilim"]'::jsonb, 2, 'edebiyat'),
('Satirik şiirin amacı nedir?', '["Övmek","Ağlatmak","Öğretmek","Eleştirmek ve iğnelemek"]'::jsonb, 3, 'edebiyat'),
('Ağıt (mersiye) hangi duyguyu işler?', '["Ölüm acısını","Sevinci","Öfkeyi","Merakı"]'::jsonb, 0, 'edebiyat'),
('Tiyatro metninde ''monolog'' nedir?', '["İki kişinin konuşması","Tek kişinin konuşması","Koro bölümü","Sessiz sahne"]'::jsonb, 1, 'edebiyat'),
('Diyalog neyi ifade eder?', '["Tek kişilik konuşmayı","Anlatıcı sesini","Karşılıklı konuşmayı","Sahne yönergesini"]'::jsonb, 2, 'edebiyat'),
('Romanda ''bakış açısı'' neyi belirler?', '["Sayfa sayısını","Bölüm başlığını","Yayınevini","Olayın kimin gözünden anlatıldığını"]'::jsonb, 3, 'edebiyat'),
('Birinci tekil kişi anlatımı hangi zamiri kullanır?', '["Ben","O","Sen","Biz"]'::jsonb, 0, 'edebiyat'),
('İlahi (tanrısal) bakış açısı neyi sağlar?', '["Sınırlı bilgi","Her şeyi bilen anlatıcı","Yalnız diyalog","Yalnız betimleme"]'::jsonb, 1, 'edebiyat'),
('Romanda ''olay örgüsü'' neyi ifade eder?', '["Karakter sayısını","Sayfa düzenini","Olayların düzenlenişini","Yayın tarihini"]'::jsonb, 2, 'edebiyat'),
('Anlatımda ''geriye dönüş'' tekniği nedir?', '["Geleceğe atlamak","Olayı özetlemek","Betimleme yapmak","Geçmişteki olaya dönmek"]'::jsonb, 3, 'edebiyat'),
('İç monolog tekniği neyi aktarır?', '["Karakterin düşünce akışını","Dış görünüşü","Mekân betimini","Diyalogu"]'::jsonb, 0, 'edebiyat'),
('Bilinç akışı tekniğinin özelliği nedir?', '["Kronolojik sıra","Düşüncelerin kesintisiz akışı","Nesnel anlatım","Diyalog ağırlığı"]'::jsonb, 1, 'edebiyat'),
('Edebiyatta ''karakter'' ile ''tip'' arasındaki fark nedir?', '["Karakterin basit olması","Tipin karmaşık olması","Tipin tek özelliği temsil etmesi","İkisinin aynı olması"]'::jsonb, 2, 'edebiyat'),
('Postmodern edebiyatın özelliklerinden biri nedir?', '["Kesin gerçekçilik","Tek anlatıcı zorunluluğu","Kronolojik zorunluluk","Metinlerarasılık ve oyunsuluk"]'::jsonb, 3, 'edebiyat'),
('Metinlerarasılık ne demektir?', '["Metnin başka metinlere göndermesi","Metnin çevrilmesi","Metnin özetlenmesi","Metnin basılması"]'::jsonb, 0, 'edebiyat'),
('Büyülü gerçekçilikte ne yapılır?', '["Yalnız gerçek anlatılır","Olağanüstü, gerçekle iç içe verilir","Yalnız masal anlatılır","Bilim kurgu yazılır"]'::jsonb, 1, 'edebiyat'),
('Distopya neyi anlatır?', '["İdeal toplumu","Gerçek tarihi","Kötüye giden kurgusal düzeni","Doğa betimini"]'::jsonb, 2, 'edebiyat'),
('Ütopya neyi anlatır?', '["Karanlık geleceği","Gerçek olayı","Gezi izlenimini","İdeal kurgusal düzeni"]'::jsonb, 3, 'edebiyat'),
('Suyun kaldırma kuvvetini açıklayan ilke kime aittir?', '["Arşimet","Newton","Pascal","Bernoulli"]'::jsonb, 0, 'bilim'),
('Pascal ilkesi neyi açıklar?', '["Kaldırma kuvvetini","Basıncın sıvıda her yöne iletilmesini","Sürtünmeyi","Yerçekimini"]'::jsonb, 1, 'bilim'),
('Bernoulli ilkesi neyi ilişkilendirir?', '["Kütle ile hacmi","Isı ile ışığı","Akışkan hızı ile basıncı","Kuvvet ile zamanı"]'::jsonb, 2, 'bilim'),
('Uçağın kalkışında kanat profilinin rolü nedir?', '["Ağırlık artırmak","Sürtünme artırmak","Isı üretmek","Basınç farkıyla kaldırma kuvveti üretmek"]'::jsonb, 3, 'bilim'),
('Sürtünme kuvvetinin yönü nasıldır?', '["Harekete zıt","Hareketle aynı","Yukarı doğru","Rastgele"]'::jsonb, 0, 'bilim'),
('Basınç nasıl tanımlanır?', '["Birim zamanda iş","Birim alana düşen kuvvet","Birim kütlede enerji","Birim hacimde kütle"]'::jsonb, 1, 'bilim'),
('Yoğunluk nasıl hesaplanır?', '["Hacmin kütleye bölümü","Kuvvetin alana bölümü","Kütlenin hacme bölümü","İşin zamana bölümü"]'::jsonb, 2, 'bilim'),
('Buz suda batmaz, çünkü yoğunluğu nasıldır?', '["Sudan büyüktür","Suya eşittir","Sıfırdır","Sudan küçüktür"]'::jsonb, 3, 'bilim'),
('Hâl değişiminde sıcaklık nasıl davranır?', '["Sabit kalır","Sürekli artar","Sürekli azalır","Sıfırlanır"]'::jsonb, 0, 'bilim'),
('Buharlaşma ile kaynama arasındaki fark nedir?', '["Buharlaşmanın hızlı olması","Kaynamanın belirli sıcaklıkta olması","İkisinin aynı olması","Kaynamanın yüzeyde olması"]'::jsonb, 1, 'bilim'),
('Süblimleşme neyi ifade eder?', '["Sıvıdan gaza","Gazdan sıvıya","Katıdan doğrudan gaza geçişi","Katıdan sıvıya"]'::jsonb, 2, 'bilim'),
('Isıyı en hızlı ileten madde grubu hangisidir?', '["Plastikler","Ahşaplar","Gazlar","Metaller"]'::jsonb, 3, 'bilim'),
('Konveksiyon (taşınım) hangi ortamlarda görülür?', '["Sıvı ve gazlarda","Yalnız katılarda","Boşlukta","Yalnız metalde"]'::jsonb, 0, 'bilim'),
('Işıma (radyasyon) ile ısı aktarımı nerede gerçekleşir?', '["Yalnız katıda","Boşlukta bile","Yalnız sıvıda","Yalnız gazda"]'::jsonb, 1, 'bilim'),
('Termosun yalıtım ilkesi nedir?', '["Yalnız iletimi artırmak","Isı üretmek","Üç ısı aktarım yolunu da azaltmak","Soğutmak"]'::jsonb, 2, 'bilim'),
('Yerçekimi ivmesi Dünya''da yaklaşık kaçtır?', '["1 m/s²","100 m/s²","3 m/s²","10 m/s²"]'::jsonb, 3, 'bilim'),
('Ay''da yerçekimi Dünya''dakine göre nasıldır?', '["Yaklaşık altıda biri","İki katı","Aynı","Sıfır"]'::jsonb, 0, 'bilim'),
('Uzayda ağırlıksızlık hissinin nedeni nedir?', '["Yerçekiminin olmaması","Sürekli serbest düşüş hâli","Havanın olmaması","Sıcaklığın düşüklüğü"]'::jsonb, 1, 'bilim'),
('Yapay uydunun yörüngede kalmasını sağlayan nedir?', '["Motorun sürekli çalışması","Havanın kaldırması","Hız ile çekimin dengesi","Manyetik alan"]'::jsonb, 2, 'bilim'),
('Elektromanyetik tayfta gözle görülen bölge hangisidir?', '["X ışını","Radyo dalgası","Gama ışını","Görünür ışık"]'::jsonb, 3, 'bilim'),
('Morötesi (UV) ışınlar hangi zarara yol açabilir?', '["Cilt hasarı","İşitme kaybı","Kemik erimesi","Diş çürüğü"]'::jsonb, 0, 'bilim'),
('Kızılötesi ışınım neyi algılamada kullanılır?', '["Ses","Isı","Basınç","Nem"]'::jsonb, 1, 'bilim'),
('Röntgende X ışınları neden kullanılır?', '["Renkli olmaları","Isı üretmeleri","Dokulardan farklı geçmeleri","Ses yaymaları"]'::jsonb, 2, 'bilim'),
('Yarı ömür kavramı neyi ifade eder?', '["Tam bozunma süresi","Isınma süresi","Erime süresi","Radyoaktif maddenin yarıya inme süresi"]'::jsonb, 3, 'bilim'),
('Karbon-14 yöntemi neyi tarihlendirir?', '["Organik kalıntıları","Kayaçları","Metalleri","Camları"]'::jsonb, 0, 'bilim'),
('Nükleer füzyon nerede doğal olarak gerçekleşir?', '["Yer kabuğunda","Yıldızlarda","Okyanuslarda","Atmosferde"]'::jsonb, 1, 'bilim'),
('Ozon molekülü kaç oksijen atomundan oluşur?', '["İki","Dört","Üç","Bir"]'::jsonb, 2, 'bilim'),
('Sera gazlarından biri hangisidir?', '["Azot gazı","Argon","Neon","Metan"]'::jsonb, 3, 'bilim')
on conflict (soru) do nothing;
