-- Soru havuzu genişletme: bilim +30, tarih +28, edebiyat +29, genel_kultur +26, sanat +19
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Hayvanlar âleminde omurgalıların ortak özelliği nedir?', '["Sırtta omurga bulunması","Kanat taşıması","Yumurtlaması","Soğukkanlı olması"]'::jsonb, 0, 'bilim'),
('Memelilerin ayırt edici özelliği nedir?', '["Yumurtlaması","Yavrusunu sütle beslemesi","Solungaçla solunumu","Tüylü olması zorunlu"]'::jsonb, 1, 'bilim'),
('Kuşların uçmasını kolaylaştıran iskelet özelliği nedir?', '["Kemiklerin ağır olması","Omurgasız olmaları","Kemiklerin içinin boşluklu olması","Kaslarının az olması"]'::jsonb, 2, 'bilim'),
('Sürüngenlerin vücut ısısı nasıl düzenlenir?', '["İç ısı üretimiyle","Terlemeyle","Titremeyle","Dış ortama bağlı olarak"]'::jsonb, 3, 'bilim'),
('Amfibilerin yaşam döngüsündeki özellik nedir?', '["Suda ve karada yaşayabilmeleri","Yalnız suda yaşamaları","Yalnız karada yaşamaları","Uçabilmeleri"]'::jsonb, 0, 'bilim'),
('Balıkların solunum organı nedir?', '["Akciğer","Solungaç","Trake","Deri yalnızca"]'::jsonb, 1, 'bilim'),
('Böceklerin vücut bölümleri hangileridir?', '["Baş ve gövde","Yalnız gövde","Baş, göğüs, karın","Dört bölüm"]'::jsonb, 2, 'bilim'),
('Örümceklerin böceklerden farkı nedir?', '["Altı bacaklı olmaları","Kanatlı olmaları","Antenli olmaları","Sekiz bacaklı olmaları"]'::jsonb, 3, 'bilim'),
('Eklem bacaklıların ortak yapısı nedir?', '["Dış iskelet","İç iskelet","Omurga","Kabuk yokluğu"]'::jsonb, 0, 'bilim'),
('Yumuşakçalara örnek hangisidir?', '["Karınca","Salyangoz","Kurbağa","Yılan"]'::jsonb, 1, 'bilim'),
('Bakterilerin hücre yapısı nasıldır?', '["Ökaryot","Çok hücreli","Prokaryot","Çekirdekli"]'::jsonb, 2, 'bilim'),
('Mantarların beslenme biçimi nedir?', '["Fotosentezle","Avlanarak","Kemosentezle","Dıştan sindirimle çürükçül"]'::jsonb, 3, 'bilim'),
('Alglerin ortak özelliği nedir?', '["Fotosentez yapabilmeleri","Hayvansal olmaları","Çekirdeksiz olmaları","Kök taşımaları"]'::jsonb, 0, 'bilim'),
('Ekosistemde ''popülasyon'' ne demektir?', '["Farklı türlerin toplamı","Aynı türün bir alandaki bireyleri","Cansız çevre","Besin zinciri"]'::jsonb, 1, 'bilim'),
('Komünite (topluluk) kavramı neyi kapsar?', '["Tek türü","Cansız çevreyi","Bir alandaki tüm popülasyonları","İklim verisini"]'::jsonb, 2, 'bilim'),
('Habitat ne anlama gelir?', '["Bir canlının görevi","Besin zinciri","İklim kuşağı","Bir canlının yaşadığı yer"]'::jsonb, 3, 'bilim'),
('Ekolojik niş kavramı neyi ifade eder?', '["Türün ekosistemdeki rolünü","Yaşadığı yeri yalnızca","Sayısını","Boyutunu"]'::jsonb, 0, 'bilim'),
('Simbiyoz ilişkiye örnek hangisidir?', '["Avlanma","Liken (mantar-alg)","Rekabet","Göç"]'::jsonb, 1, 'bilim'),
('Parazitlik ilişkisinde ne olur?', '["İkisi de yararlanır","İkisi de zarar görür","Biri yararlanır, diğeri zarar görür","Etkileşim olmaz"]'::jsonb, 2, 'bilim'),
('Mutualizm ilişkisinde ne olur?', '["Biri zarar görür","İkisi zarar görür","Etki olmaz","İki taraf da yararlanır"]'::jsonb, 3, 'bilim'),
('Besin piramidinde yukarı çıkıldıkça enerji nasıl değişir?', '["Azalır","Artar","Sabit kalır","İkiye katlanır"]'::jsonb, 0, 'bilim'),
('Karbon döngüsünde fotosentezin rolü nedir?', '["Karbonu serbest bırakmak","Karbondioksiti organik maddeye bağlamak","Azot bağlamak","Su üretmek"]'::jsonb, 1, 'bilim'),
('Azot döngüsünde bakterilerin rolü nedir?', '["Azotu yok etmek","Karbon üretmek","Azotu bitkiye yarayışlı hâle getirmek","Su bağlamak"]'::jsonb, 2, 'bilim'),
('Biyoçeşitliliğin azalmasının başlıca nedeni nedir?', '["Nüfus azalması","İklim soğuması","Ormanların artması","Habitat kaybı"]'::jsonb, 3, 'bilim'),
('Nesli tükenmekte olan tür ne demektir?', '["Yok olma riski yüksek tür","Yeni keşfedilen tür","Yaygın tür","Evcil tür"]'::jsonb, 0, 'bilim'),
('Gen havuzu kavramı neyi ifade eder?', '["Tek bireyin genlerini","Bir popülasyondaki tüm genleri","Bir hücreyi","Bir kromozomu"]'::jsonb, 1, 'bilim'),
('Doğal seçilim neye dayanır?', '["Rastgele üremeye","Boyut büyüklüğüne","Uyum sağlayanın daha çok üremesine","Yaşa"]'::jsonb, 2, 'bilim'),
('Adaptasyon (uyum) ne demektir?', '["Ortamı değiştirmek","Göç etmek","Uyumak","Ortama uygun özellik kazanmak"]'::jsonb, 3, 'bilim'),
('Mutasyonun evrimdeki rolü nedir?', '["Çeşitliliğe kaynak sağlamak","Çeşitliliği azaltmak","Üremeyi durdurmak","Beslenmeyi sağlamak"]'::jsonb, 0, 'bilim'),
('Yapay seçilim nedir?', '["Doğanın seçmesi","İstenen özelliğin seçilerek üretilmesi","Rastgele üreme","Göç"]'::jsonb, 1, 'bilim'),
('Yazının bulunduğu ilk uygarlık hangisidir?', '["Sümerler","Mısırlılar","Hititler","Persler"]'::jsonb, 0, 'tarih'),
('İlk takvimi geliştirdiği kabul edilen uygarlık hangisidir?', '["Frigler","Mısırlılar","Lidyalılar","İyonlar"]'::jsonb, 1, 'tarih'),
('Tarihte ilk kütüphanelerden biri hangi uygarlığa aittir?', '["Fenikeliler","Urartular","Asurlular","Frigler"]'::jsonb, 2, 'tarih'),
('Urartular hangi alanda ileriydi?', '["Deniz ticareti","Piramit yapımı","Takvim","Su kanalları ve madencilik"]'::jsonb, 3, 'tarih'),
('İyon şehir devletlerinden biri hangisidir?', '["Milet","Sard","Gordion","Hattuşa"]'::jsonb, 0, 'tarih'),
('Thales ve Anaksimandros hangi bölgeden çıkmıştır?', '["Frigya","İyonya","Lidya","Kapadokya"]'::jsonb, 1, 'tarih'),
('Büyük İskender hangi krallığın hükümdarıydı?', '["Sparta","Atina","Makedonya","Trakya"]'::jsonb, 2, 'tarih'),
('Bergama Krallığı hangi buluşuyla anılır?', '["Papirüs","Cam","Matbaa","Parşömen"]'::jsonb, 3, 'tarih'),
('Roma''da gladyatör dövüşleri nerede yapılırdı?', '["Amfitiyatroda","Agorada","Tapınakta","Hamamda"]'::jsonb, 0, 'tarih'),
('Roma''nın su getirme yapıları hangileridir?', '["Zigguratlar","Su kemerleri","Kurganlar","Tümülüsler"]'::jsonb, 1, 'tarih'),
('Bizans''ta Ayasofya hangi imparator döneminde yapılmıştır?', '["Konstantin","Theodosius","Justinianus","Herakleios"]'::jsonb, 2, 'tarih'),
('Haçlı Seferleri''nin Bizans üzerindeki etkisi ne olmuştur?', '["Güçlenmesi","Genişlemesi","Etkilenmemesi","Zayıflayıp toprak kaybetmesi"]'::jsonb, 3, 'tarih'),
('Emeviler döneminde başkent neresiydi?', '["Şam","Bağdat","Kahire","Medine"]'::jsonb, 0, 'tarih'),
('Abbasiler döneminde başkent neresiydi?', '["Şam","Bağdat","Kahire","Kurtuba"]'::jsonb, 1, 'tarih'),
('Endülüs''te bilim ve sanatın merkezi olan kent hangisidir?', '["Bağdat","Şam","Kurtuba","Kahire"]'::jsonb, 2, 'tarih'),
('Nizamiye Medreseleri hangi vezirin girişimiyle kurulmuştur?', '["Şemsettin","Ahmet Yesevi","Karatay","Nizamülmülk"]'::jsonb, 3, 'tarih'),
('Moğol istilası hangi devletin yıkılışını hızlandırmıştır?', '["Abbasiler","Emeviler","Osmanlılar","Memlükler"]'::jsonb, 0, 'tarih'),
('Timur hangi savaşta Osmanlı''yı yenmiştir?', '["Kosova Savaşı","Ankara Savaşı","Niğbolu","Varna"]'::jsonb, 1, 'tarih'),
('Fatih Sultan Mehmed''in bilim insanlarını topladığı kurum hangisidir?', '["Enderun dışı hiçbiri","Darülfünun","Sahn-ı Seman Medreseleri","Mekteb-i Sultani"]'::jsonb, 2, 'tarih'),
('Osmanlı''da Enderun Mektebi kimleri yetiştirirdi?', '["Yalnız askerleri","Yalnız tüccarları","Yalnız din adamlarını","Saray ve devlet görevlilerini"]'::jsonb, 3, 'tarih'),
('Osmanlı''da esnaf örgütlenmesi hangi adla anılır?', '["Lonca","Divan","Tımar","Vakıf"]'::jsonb, 0, 'tarih'),
('Vakıf kurumunun temel işlevi neydi?', '["Vergi toplamak","Hayır hizmetlerini sürdürmek","Ordu kurmak","Ticaret yapmak"]'::jsonb, 1, 'tarih'),
('Osmanlı''da ''imaret'' ne işlevi görürdü?', '["Okul olmak","Hastane olmak","Aşevi olarak yemek dağıtmak","Kervansaray olmak"]'::jsonb, 2, 'tarih'),
('Osmanlı''da ''darüşşifa'' ne demektir?', '["Okul","Kütüphane","Han","Hastane"]'::jsonb, 3, 'tarih'),
('Osmanlı''da para birimi olarak kullanılan sikke hangisidir?', '["Akçe","Dinar yalnızca","Drahmi","Dukat"]'::jsonb, 0, 'tarih'),
('Osmanlı''da tahrir defterleri neyi kaydederdi?', '["Savaş planlarını","Nüfus ve vergi kaynaklarını","Mahkeme kararlarını","Ticaret rotalarını"]'::jsonb, 1, 'tarih'),
('Şer''iyye sicilleri hangi kayıtları içerir?', '["Askerî planları","Vergi oranlarını yalnızca","Mahkeme kararlarını","Harita çizimlerini"]'::jsonb, 2, 'tarih'),
('Osmanlı arşivlerinin tarih araştırmalarındaki değeri nedir?', '["İkincil yorum sunması","Kurgu içermesi","Sadece harita içermesi","Birincil kaynak sunması"]'::jsonb, 3, 'tarih'),
('Türkçenin yapı bakımından hangi dil grubunda yer aldığı kabul edilir?', '["Eklemeli diller","Çekimli diller","Yalınlayan diller","Karma diller"]'::jsonb, 0, 'edebiyat'),
('Türkçede sözcük türetmenin temel yolu nedir?', '["Ön ek getirmek","Yapım eki getirmek","Harf değiştirmek","Vurgu değiştirmek"]'::jsonb, 1, 'edebiyat'),
('Büyük ünlü uyumu neye dayanır?', '["Düz-yuvarlak uyumuna","Ünsüz benzeşmesine","Kalın-ince ünlü uyumuna","Vurguya"]'::jsonb, 2, 'edebiyat'),
('Küçük ünlü uyumu neyi düzenler?', '["Kalınlık-incelik uyumunu","Ünsüz yumuşamasını","Ses düşmesini","Düzlük-yuvarlaklık uyumunu"]'::jsonb, 3, 'edebiyat'),
('Ünsüz yumuşaması hangi durumda görülür?', '["Sert ünsüzün ünlüyle yumuşaması","Ünlü düşmesinde","Ünlü türemesinde","Vurgu kaymasında"]'::jsonb, 0, 'edebiyat'),
('Kaynaştırma harfleri hangileridir?', '["k, t, p, ç","y, ş, s, n","a, e, ı, i","l, m, n, r"]'::jsonb, 1, 'edebiyat'),
('Türkçede vurgu genellikle nerededir?', '["İlk hecede","Orta hecede","Son hecede","Vurgu yoktur"]'::jsonb, 2, 'edebiyat'),
('İsim tamlamasında ''belirtili'' olanın özelliği nedir?', '["Hiçbirinin ek almaması","Yalnız birinin ek alması","Sıfat kullanılması","Her iki öğenin de ek alması"]'::jsonb, 3, 'edebiyat'),
('Sıfat tamlamasında tamlayan ne görevindedir?', '["Niteleyici","Belirtici ad","Yüklem","Zarf"]'::jsonb, 0, 'edebiyat'),
('Cümlenin temel öğesi hangisidir?', '["Nesne","Yüklem","Zarf tümleci","Dolaylı tümleç"]'::jsonb, 1, 'edebiyat'),
('Özne ile yüklem uyumu neyi gerektirir?', '["Aynı kökten olmayı","Aynı hecede olmayı","Kişi ve sayı bakımından uyuşmayı","Aynı harfle başlamayı"]'::jsonb, 2, 'edebiyat'),
('Devrik cümlenin özelliği nedir?', '["Yüklemin sonda olması","Öznesiz olması","Nesnesiz olması","Yüklemin sonda olmaması"]'::jsonb, 3, 'edebiyat'),
('Eksiltili cümle nedir?', '["Yüklemi söylenmemiş cümle","Öznesi olmayan cümle","Uzun cümle","Soru cümlesi"]'::jsonb, 0, 'edebiyat'),
('Edat (ilgeç) cümlede ne yapar?', '["Eylem bildirir","Sözcükler arası ilişki kurar","Ad olur","Sıfat olur"]'::jsonb, 1, 'edebiyat'),
('Bağlaç ne işe yarar?', '["Eylem bildirmek","Nesne olmak","Sözcük ya da cümleleri bağlamak","Özne olmak"]'::jsonb, 2, 'edebiyat'),
('Ünlem sözcükleri neyi bildirir?', '["Eylemi","Nesneyi","Zamanı","Duygu ve seslenmeyi"]'::jsonb, 3, 'edebiyat'),
('Zamir (adıl) ne yapar?', '["Adın yerini tutar","Eylemi niteler","Adı niteler","Cümleyi bağlar"]'::jsonb, 0, 'edebiyat'),
('Zarf (belirteç) neyi niteler?', '["Yalnız adı","Eylemi veya sıfatı","Yalnız zamiri","Yalnız edatı"]'::jsonb, 1, 'edebiyat'),
('Yazım kurallarında ''de'' ayrı yazıldığında hangi görevdedir?', '["Yapım eki","Çekim eki","Bulunma durumu eki değil, bağlaç","Kök"]'::jsonb, 2, 'edebiyat'),
('Noktalama işaretlerinden ''noktalı virgül'' ne yapar?', '["Cümleyi bitirir","Soru sorar","Alıntı yapar","Yakın anlamlı cümleleri ayırır"]'::jsonb, 3, 'edebiyat'),
('Tırnak işaretinin işlevi nedir?', '["Alıntıyı belirtmek","Cümleyi bitirmek","Ara söz koymak","Soru sormak"]'::jsonb, 0, 'edebiyat'),
('Parantez (ayraç) ne için kullanılır?', '["Alıntı yapmak","Açıklama eklemek","Cümleyi bitirmek","Soru sormak"]'::jsonb, 1, 'edebiyat'),
('Kesme işaretinin temel işlevi nedir?', '["Cümleyi bitirmek","Soru sormak","Özel adlara gelen ekleri ayırmak","Vurgu yapmak"]'::jsonb, 2, 'edebiyat'),
('Bir metinde ''paragraf'' neye göre ayrılır?', '["Sayfa sayısına","Sözcük sayısına","Harf sayısına","Düşünce bütünlüğüne"]'::jsonb, 3, 'edebiyat'),
('Metinde ''ana düşünce'' ne demektir?', '["Yazarın vermek istediği temel ileti","Yardımcı örnek","Başlık","Kaynakça"]'::jsonb, 0, 'edebiyat'),
('Yardımcı düşüncelerin işlevi nedir?', '["Ana düşünceyi çürütmek","Ana düşünceyi desteklemek","Başlık olmak","Sonuç olmak"]'::jsonb, 1, 'edebiyat'),
('Anlatım bozukluğunun yaygın nedeni nedir?', '["Kısa cümle kurmak","Noktalama kullanmak","Gereksiz sözcük kullanımı","Paragraf açmak"]'::jsonb, 2, 'edebiyat'),
('Metinde ''tutarlılık'' neyi ifade eder?', '["Uzunluğu","Sözcük sayısını","Yazı tipini","Düşüncelerin çelişmemesini"]'::jsonb, 3, 'edebiyat'),
('Özet çıkarmanın amacı nedir?', '["Metnin özünü kısaca vermek","Metni uzatmak","Metni eleştirmek","Metni çevirmek"]'::jsonb, 0, 'edebiyat'),
('İlk yardımda ''ABC'' sıralaması neyi ifade eder?', '["Hava yolu, solunum, dolaşım","Ateş, basınç, ciğer","Ağrı, baş, ciğer","Alt, bel, cilt"]'::jsonb, 0, 'genel_kultur'),
('İlk yardımın temel amacı nedir?', '["Kesin tedavi uygulamak","Yardım gelene dek durumu korumak","İlaç yazmak","Ameliyat yapmak"]'::jsonb, 1, 'genel_kultur'),
('Heimlich manevrası hangi durumda uygulanır?', '["Kanamada","Yanıkta","Boğulma (yabancı cisim) durumunda","Kırıkta"]'::jsonb, 2, 'genel_kultur'),
('Yanıkta ilk yapılması gereken nedir?', '["Diş macunu sürmek","Buz basmak","Sıkı sarmak","Bölgeyi soğuk suyla soğutmak"]'::jsonb, 3, 'genel_kultur'),
('Burun kanamasında doğru davranış nedir?', '["Öne eğilip burun kanadını sıkmak","Başı geriye atmak","Sırtüstü yatmak","Su içmek"]'::jsonb, 0, 'genel_kultur'),
('Kırık şüphesinde ne yapılmalıdır?', '["Yerine oturtmaya çalışmak","Bölgeyi hareketsiz tutmak","Masaj yapmak","Sıcak uygulamak"]'::jsonb, 1, 'genel_kultur'),
('Acil çağrı numarasının bilinmesinin önemi nedir?', '["Sigorta yapmak","Tedavi uygulamak","Hızlı yardım çağırabilmek","Rapor almak"]'::jsonb, 2, 'genel_kultur'),
('Deprem sırasında güvenli davranış nedir?', '["Koşarak dışarı çıkmak","Asansöre binmek","Pencereye yaklaşmak","Çök-kapan-tutun"]'::jsonb, 3, 'genel_kultur'),
('Yangında dumandan korunmak için ne yapılır?', '["Eğilerek ilerlemek","Ayakta koşmak","Derin nefes almak","Pencereyi açmak"]'::jsonb, 0, 'genel_kultur'),
('Trafikte emniyet kemerinin işlevi nedir?', '["Hızı artırmak","Çarpmada savrulmayı önlemek","Yakıt tasarrufu","Konfor sağlamak"]'::jsonb, 1, 'genel_kultur'),
('Çocuk oto koltuğunun gerekliliği neye dayanır?', '["Rahatlık","Görüş açısı","Çocuğun bedenine uygun koruma","Estetik"]'::jsonb, 2, 'genel_kultur'),
('Kask kullanımının temel yararı nedir?', '["Görüşü artırmak","Hızı artırmak","Sesi engellemek","Kafa travması riskini azaltmak"]'::jsonb, 3, 'genel_kultur'),
('Trafikte ''ölü nokta'' ne demektir?', '["Aynalardan görülemeyen alan","Duraklama yeri","Kavşak ortası","Yaya geçidi"]'::jsonb, 0, 'genel_kultur'),
('Beslenmede ''dengeli beslenme'' ne demektir?', '["Tek besin yemek","Besin gruplarından yeterince almak","Aç kalmak","Yalnız protein almak"]'::jsonb, 1, 'genel_kultur'),
('Lif (posa) tüketiminin yararı nedir?', '["Kalori yükseltmesi","Su tutması","Sindirimi düzenlemesi","Kemik yapması"]'::jsonb, 2, 'genel_kultur'),
('Aşırı tuz tüketiminin riski nedir?', '["Diş çürüğü","Görme kaybı","İşitme kaybı","Yüksek tansiyon"]'::jsonb, 3, 'genel_kultur'),
('Düzenli fiziksel aktivitenin yararlarından biri nedir?', '["Kalp sağlığını desteklemesi","Uykusuzluk yapması","Bağışıklığı düşürmesi","İştahı yok etmesi"]'::jsonb, 0, 'genel_kultur'),
('Uyku düzeninin sağlığa etkisi nedir?', '["Etkisi olmaması","Bağışıklık ve odaklanmayı desteklemesi","Yalnız kilo etkisi","Yalnız görme etkisi"]'::jsonb, 1, 'genel_kultur'),
('El yıkamanın hastalıklara etkisi nedir?', '["Bulaşı artırması","Etkisiz olması","Bulaş riskini azaltması","Bağışıklığı düşürmesi"]'::jsonb, 2, 'genel_kultur'),
('Aşı takviminin amacı nedir?', '["Tedavi etmek","Ateş düşürmek","Ağrı kesmek","Hastalıklara karşı zamanında bağışıklık"]'::jsonb, 3, 'genel_kultur'),
('Son kullanma tarihi geçmiş gıdanın riski nedir?', '["Gıda kaynaklı hastalık","Besin değerinin artması","Tadının düzelmesi","Risk olmaması"]'::jsonb, 0, 'genel_kultur'),
('Soğuk zincir kavramı neyi ifade eder?', '["Dondurulmuş üretimi","Ürünün üretimden tüketime soğuk kalması","Buzdolabı markasını","Sıcak taşımayı"]'::jsonb, 1, 'genel_kultur'),
('Etiket okumanın tüketiciye yararı nedir?', '["Fiyatı düşürmek","Kargo hızlandırmak","İçerik ve besin değerini öğrenmek","Marka değiştirmek"]'::jsonb, 2, 'genel_kultur'),
('Gıda israfını azaltmanın yollarından biri nedir?', '["Fazla satın almak","Etiketi okumamak","Stok yapmak","Planlı alışveriş yapmak"]'::jsonb, 3, 'genel_kultur'),
('Enerji tasarrufu için evde yapılabilecek uygulamalardan biri nedir?', '["Yalıtım yaptırmak","Pencereleri açık bırakmak","Cihazları açık tutmak","Ampulleri artırmak"]'::jsonb, 0, 'genel_kultur'),
('Atık pillerin ayrı toplanmasının nedeni nedir?', '["Yer kazanmak","Ağır metal kirliliğini önlemek","Geri dönüşümsüz olması","Ucuz olması"]'::jsonb, 1, 'genel_kultur'),
('Bir yapıda ''kubbe'' hangi yükü taşır?', '["Üst örtü yükünü","Zemin yükünü","Kapı yükünü","Pencere yükünü"]'::jsonb, 0, 'sanat'),
('Kemerin mimarideki işlevi nedir?', '["Süsleme yalnızca","Açıklığı geçip yükü aktarmak","Isı yalıtımı","Su geçirmezlik"]'::jsonb, 1, 'sanat'),
('Sütun başlığına ne ad verilir?', '["Kaide","Gövde","Başlık (kaide değil)","Alınlık"]'::jsonb, 2, 'sanat'),
('Dor, İyon ve Korint neyi tanımlar?', '["Kubbe türlerini","Kemer türlerini","Çatı türlerini","Antik sütun düzenlerini"]'::jsonb, 3, 'sanat'),
('İyon düzeninin ayırt edici öğesi nedir?', '["Kıvrımlı (volütlü) başlık","Sade yastık başlık","Yaprak bezemeli başlık","Başlıksız gövde"]'::jsonb, 0, 'sanat'),
('Korint düzeninin başlığı neyle bezenir?', '["Volüt","Akantus yaprağı","Düz yastık","Geometri"]'::jsonb, 1, 'sanat'),
('Antik tapınakta ''alınlık'' nerede bulunur?', '["Zeminde","Sütun ortasında","Çatının üçgen kısmında","İç mekânda"]'::jsonb, 2, 'sanat'),
('Roma mimarisinin en önemli yapı malzemesi buluşu nedir?', '["Cam","Çelik","Alçı","Beton (harç)"]'::jsonb, 3, 'sanat'),
('Gotik katedrallerde vitray neyi amaçlar?', '["Renkli ışıkla manevi atmosfer","Isı yalıtımı","Ses yalıtımı","Yapı taşıyıcılığı"]'::jsonb, 0, 'sanat'),
('Rönesans mimarisinde hangi biçim yeniden benimsenmiştir?', '["Sivri kemer","Antik oran ve simetri","Uçan payanda","Kaotik plan"]'::jsonb, 1, 'sanat'),
('Osmanlı camisinde ''mihrap'' neyi gösterir?', '["Giriş kapısını","Minare yerini","Kıble yönünü","Avlu sınırını"]'::jsonb, 2, 'sanat'),
('Şadırvanın işlevi nedir?', '["Süsleme yalnızca","Isıtma","Aydınlatma","Abdest almak için su sağlamak"]'::jsonb, 3, 'sanat'),
('Türk-İslam mimarisinde ''medrese'' ne işlev görür?', '["Eğitim yapısı","Hastane","Aşevi","Han"]'::jsonb, 0, 'sanat'),
('Han ile kervansaray arasındaki fark nedir?', '["Hanın yol üzerinde olması","Kervansarayın yol üzerinde olması","İkisinin aynı olması","Hanın kırsal olması"]'::jsonb, 1, 'sanat'),
('Türk hamamının bölümlerinden biri hangisidir?', '["Mihrap","Minber","Sıcaklık","Şerefe"]'::jsonb, 2, 'sanat'),
('Minarede müezzinin çıktığı bölüm hangisidir?', '["Külah","Kaide","Petek","Şerefe"]'::jsonb, 3, 'sanat'),
('Selçuklu yapılarında kullanılan süsleme öğesi nedir?', '["Geometrik geçmeler","Barok kıvrımlar","Gotik gül pencere","Rokoko bezeme"]'::jsonb, 0, 'sanat'),
('Türk mimarisinde ''taşıyıcı ayak'' ne işlev görür?', '["Süsleme","Kubbe yükünü zemine aktarmak","Aydınlatma","Havalandırma"]'::jsonb, 1, 'sanat'),
('Kubbeden duvara geçişte kullanılan öğe hangisidir?', '["Alınlık","Sütun","Pandantif","Kemer ayağı"]'::jsonb, 2, 'sanat')
on conflict (soru) do nothing;
