-- Soru havuzu genişletme: teknoloji +59, sanat +61, spor +45
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('İşletim sisteminde ''çekirdek'' (kernel) neyi yönetir?', '["Donanım ve kaynak erişimini","Kullanıcı arayüzünü","Web sitelerini","Yazıcı kâğıdını"]'::jsonb, 0, 'teknoloji'),
('RAM belleğin en belirgin özelliği nedir?', '["Kalıcı olması","Elektrik kesilince silinmesi","Yalnız okunabilir olması","Çok yavaş olması"]'::jsonb, 1, 'teknoloji'),
('ROM belleğin özelliği nedir?', '["Sürekli silinmesi","Sonsuz kapasiteli olması","Kalıcı ve genelde salt okunur olması","Ağ üzerinden çalışması"]'::jsonb, 2, 'teknoloji'),
('Önbellek (cache) belleğin amacı nedir?', '["Kalıcı depolama","Veri şifreleme","Ağ yönlendirme","Sık kullanılan veriye hızlı erişim"]'::jsonb, 3, 'teknoloji'),
('İşlemcide ''çekirdek sayısı'' neyi etkiler?', '["Aynı anda yapılabilen iş sayısını","Ekran çözünürlüğünü","Disk kapasitesini","Ağ hızını"]'::jsonb, 0, 'teknoloji'),
('GPU öncelikli olarak hangi işi yapar?', '["Dosya saklama","Grafik ve paralel hesaplama","Ağ yönlendirme","Ses kaydı"]'::jsonb, 1, 'teknoloji'),
('İkilik (binary) sayı sisteminde kaç rakam kullanılır?', '["Sekiz","On","İki","On altı"]'::jsonb, 2, 'teknoloji'),
('Bir bayt kaç bitten oluşur?', '["Dört","On altı","Otuz iki","Sekiz"]'::jsonb, 3, 'teknoloji'),
('Onaltılık (hexadecimal) sistemde hangi harfler kullanılır?', '["A''dan F''ye","A''dan Z''ye","X, Y, Z","Hiçbiri"]'::jsonb, 0, 'teknoloji'),
('Unicode''un ASCII''ye üstünlüğü nedir?', '["Daha hızlı olması","Tüm dünya dillerini kapsaması","Daha az yer tutması","Yalnız İngilizceyi desteklemesi"]'::jsonb, 1, 'teknoloji'),
('IP adresinin işlevi nedir?', '["Dosya sıkıştırmak","Şifre üretmek","Cihazı ağda adreslemek","Ekran açmak"]'::jsonb, 2, 'teknoloji'),
('DNS sisteminin görevi nedir?', '["Dosya saklamak","Virüs taramak","Sayfa tasarlamak","Alan adını IP adresine çevirmek"]'::jsonb, 3, 'teknoloji'),
('HTTP ile HTTPS arasındaki fark nedir?', '["HTTPS''in şifreli olması","HTTP''nin daha güvenli olması","HTTPS''in daha yavaş olması","İkisinin aynı olması"]'::jsonb, 0, 'teknoloji'),
('TCP protokolünün temel özelliği nedir?', '["Veriyi kaybetmesi","Veriyi güvenilir ve sıralı iletmesi","Şifrelemesi","Sıkıştırması"]'::jsonb, 1, 'teknoloji'),
('Yönlendirici (router) ne yapar?', '["Veri saklar","Ekran görüntüsü alır","Ağlar arasında veri paketi yönlendirir","Yazıcıyı sürer"]'::jsonb, 2, 'teknoloji'),
('Güvenlik duvarı (firewall) ne sağlar?', '["Dosya sıkıştırmayı","Ekran parlaklığını","Ses artışını","İstenmeyen ağ trafiğini engellemeyi"]'::jsonb, 3, 'teknoloji'),
('VPN kullanımının temel amacı nedir?', '["Bağlantıyı şifreli tünelden geçirmek","İnterneti hızlandırmak","Bellek artırmak","Disk temizlemek"]'::jsonb, 0, 'teknoloji'),
('Proxy sunucusunun işlevi nedir?', '["Dosya silmek","İstekleri aracı olarak iletmek","Kod derlemek","Sayfa tasarlamak"]'::jsonb, 1, 'teknoloji'),
('Simetrik şifrelemede kaç anahtar kullanılır?', '["İki anahtar","Üç anahtar","Tek anahtar","Anahtar yok"]'::jsonb, 2, 'teknoloji'),
('Asimetrik şifrelemede hangi anahtar çifti kullanılır?', '["İki gizli anahtar","İki açık anahtar","Tek anahtar","Açık ve gizli anahtar"]'::jsonb, 3, 'teknoloji'),
('Karma (hash) fonksiyonunun özelliği nedir?', '["Tek yönlü ve sabit uzunlukta çıktı","Geri çevrilebilir olması","Değişken uzunlukta olması","Şifre çözmesi"]'::jsonb, 0, 'teknoloji'),
('İki aşamalı doğrulama neyi artırır?', '["İnternet hızını","Hesap güvenliğini","Disk alanını","Ekran çözünürlüğünü"]'::jsonb, 1, 'teknoloji'),
('Truva atı (trojan) yazılımın özelliği nedir?', '["Kendini kopyalaması","Donanım olması","Zararsız görünüp zarar vermesi","Güncelleme olması"]'::jsonb, 2, 'teknoloji'),
('Solucan (worm) virüsten nasıl ayrılır?', '["Dosyaya bulaşmasıyla","Zarar vermemesiyle","Donanım olmasıyla","Kendi başına yayılabilmesiyle"]'::jsonb, 3, 'teknoloji'),
('Yedekleme stratejisinde ''3-2-1 kuralı'' neyi önerir?', '["Üç kopya, iki ortam, bir uzak yer","Tek kopya","Yalnız bulut","Haftalık silme"]'::jsonb, 0, 'teknoloji'),
('Veritabanında ''birincil anahtar'' ne sağlar?', '["Verinin şifrelenmesini","Kaydın benzersiz tanımlanmasını","Tablonun silinmesini","Yedek alınmasını"]'::jsonb, 1, 'teknoloji'),
('SQL dili ne için kullanılır?', '["Web tasarlamak","Görüntü işlemek","İlişkisel veritabanı sorgulamak","Ağ kurmak"]'::jsonb, 2, 'teknoloji'),
('NoSQL veritabanlarının ayırt edici özelliği nedir?', '["Yalnız tablo kullanması","SQL zorunluluğu","Tek kullanıcılı olması","Esnek şema yapısı"]'::jsonb, 3, 'teknoloji'),
('İndeks (index) veritabanında ne sağlar?', '["Arama hızını artırmayı","Veri şifrelemeyi","Yedek almayı","Kullanıcı eklemeyi"]'::jsonb, 0, 'teknoloji'),
('Normalizasyonun amacı nedir?', '["Veriyi çoğaltmak","Veri tekrarını azaltmak","Sorguyu yavaşlatmak","Tabloyu silmek"]'::jsonb, 1, 'teknoloji'),
('İşlem (transaction) bütünlüğünde ''atomiklik'' ne demektir?', '["Kısmi uygulanma","Sonsuz tekrar","Ya hepsi ya hiçbiri","Rastgele sıra"]'::jsonb, 2, 'teknoloji'),
('Git''te ''commit'' işlemi ne yapar?', '["Dosya siler","Sunucu başlatır","Test çalıştırır","Değişiklikleri kayda geçirir"]'::jsonb, 3, 'teknoloji'),
('Git''te ''branch'' ne işe yarar?', '["Paralel geliştirme dalı açmak","Kod silmek","Dosya sıkıştırmak","Sunucu kurmak"]'::jsonb, 0, 'teknoloji'),
('REST mimarisinin temel ilkesi nedir?', '["Sürekli bağlantı","Durumsuz istemci-sunucu iletişimi","Tek yönlü akış","Şifresiz iletim"]'::jsonb, 1, 'teknoloji'),
('JSON biçimi ne için kullanılır?', '["Görüntü sıkıştırma","Ses kodlama","Veri alışverişi","Video akışı"]'::jsonb, 2, 'teknoloji'),
('Yorumlayıcı (interpreter) derleyiciden nasıl ayrılır?', '["Daha hızlı olması","Makine kodu üretmesi","Donanım olması","Kodu çalışma anında yürütmesi"]'::jsonb, 3, 'teknoloji'),
('Sanal makine (VM) neyi sağlar?', '["Tek donanımda çok sistem çalıştırmayı","Donanım hızlandırma","Veri şifreleme","Ağ kablosu"]'::jsonb, 0, 'teknoloji'),
('Konteyner teknolojisi sanal makineden nasıl ayrılır?', '["Daha ağır olması","İşletim sistemi çekirdeğini paylaşması","Donanım gerektirmesi","Ağ kurmaması"]'::jsonb, 1, 'teknoloji'),
('Bulut bilişimde IaaS ne sunar?', '["Hazır uygulama","Geliştirme platformu","Altyapı hizmeti","Veri kablosu"]'::jsonb, 2, 'teknoloji'),
('SaaS modeli neyi ifade eder?', '["Hizmet olarak donanım","Hizmet olarak ağ","Hizmet olarak depolama","Hizmet olarak yazılım"]'::jsonb, 3, 'teknoloji'),
('Derin öğrenme hangi yapıyı kullanır?', '["Çok katmanlı yapay sinir ağı","Karar ağacı","Veritabanı tablosu","Ağ yönlendirici"]'::jsonb, 0, 'teknoloji'),
('Denetimli öğrenmede model neyle eğitilir?', '["Etiketsiz veriyle","Etiketli veriyle","Ödül sinyaliyle","Rastgele veriyle"]'::jsonb, 1, 'teknoloji'),
('Pekiştirmeli öğrenmede model neyle yönlendirilir?', '["Etiketli veriyle","Elle kuralla","Ödül ve ceza sinyaliyle","Sabit tabloyla"]'::jsonb, 2, 'teknoloji'),
('Doğal dil işleme hangi alanla ilgilenir?', '["Görüntü sıkıştırma","Ağ yönlendirme","Donanım tasarımı","İnsan dilinin bilgisayarla işlenmesi"]'::jsonb, 3, 'teknoloji'),
('Blok zincir teknolojisinin temel özelliği nedir?', '["Dağıtık ve değiştirilemez kayıt","Merkezî sunucu","Tek kullanıcı","Şifresiz veri"]'::jsonb, 0, 'teknoloji'),
('Nesnelerin İnterneti (IoT) neyi ifade eder?', '["Yalnız bilgisayar ağı","Cihazların ağa bağlanıp veri paylaşması","Sosyal medya","Bulut depolama"]'::jsonb, 1, 'teknoloji'),
('5G teknolojisinin öne çıkan özelliği nedir?', '["Kablo gerektirmesi","Kısa pil ömrü","Düşük gecikme ve yüksek hız","Yalnız ses taşıması"]'::jsonb, 2, 'teknoloji'),
('Kablosuz ağda SSID neyi belirtir?', '["Şifreyi","IP adresini","Kanal sayısını","Ağın adını"]'::jsonb, 3, 'teknoloji'),
('Bluetooth teknolojisi hangi mesafede çalışır?', '["Kısa mesafede","Kıtalar arası","Uydu üzerinden","Yalnız kabloyla"]'::jsonb, 0, 'teknoloji'),
('NFC teknolojisi hangi kullanım için yaygındır?', '["Uydu iletişimi","Temassız ödeme","Video akışı","Uzun mesafe ağ"]'::jsonb, 1, 'teknoloji'),
('QR kodun barkoddan farkı nedir?', '["Tek boyutlu olması","Renkli olması zorunluluğu","İki boyutlu olup daha çok veri taşıması","Okunamaması"]'::jsonb, 2, 'teknoloji'),
('Piksel yoğunluğu (DPI) neyi ölçer?', '["Ekran boyutunu","Renk sayısını","Parlaklığı","Birim uzunluktaki nokta sayısını"]'::jsonb, 3, 'teknoloji'),
('Kayıpsız sıkıştırmanın özelliği nedir?', '["Verinin tam geri elde edilebilmesi","Verinin bozulması","Dosyanın büyümesi","Şifrelenmesi"]'::jsonb, 0, 'teknoloji'),
('JPEG biçimi hangi sıkıştırmayı kullanır?', '["Kayıpsız","Kayıplı","Şifreli","Sıkıştırmasız"]'::jsonb, 1, 'teknoloji'),
('PNG biçiminin JPEG''e üstünlüğü nedir?', '["Daha küçük dosya","Daha çok renk","Saydamlık ve kayıpsız sıkıştırma","Video desteği"]'::jsonb, 2, 'teknoloji'),
('Vektörel grafiğin avantajı nedir?', '["Küçük dosya olması hep","Fotoğraf için ideal olması","Renksiz olması","Büyütünce bozulmaması"]'::jsonb, 3, 'teknoloji'),
('Çözünürlük 1920x1080 hangi adla anılır?', '["Full HD","4K","HD Ready","8K"]'::jsonb, 0, 'teknoloji'),
('Yenileme hızı (Hz) neyi belirtir?', '["Renk derinliğini","Ekranın saniyedeki tazelenme sayısını","Çözünürlüğü","Parlaklığı"]'::jsonb, 1, 'teknoloji'),
('OLED ekranın LCD''ye üstünlüğü nedir?', '["Daha ucuz olması","Daha dayanıklı olması","Gerçek siyah ve yüksek kontrast","Işık gerektirmesi"]'::jsonb, 2, 'teknoloji'),
('Rönesans resminde perspektif neyi sağlamıştır?', '["Derinlik yanılsaması","Renk zenginliği","Düz yüzey etkisi","Soyutlama"]'::jsonb, 0, 'sanat'),
('Sfumato tekniği hangi etkiyi yaratır?', '["Keskin çizgiler","Yumuşak geçişli sisli görünüm","Parlak renkler","Geometrik biçim"]'::jsonb, 1, 'sanat'),
('Chiaroscuro tekniği neye dayanır?', '["Renk körlüğüne","Düz boyamaya","Güçlü ışık-gölge karşıtlığına","Nokta tekniğine"]'::jsonb, 2, 'sanat'),
('Caravaggio hangi teknikle özdeşleşmiştir?', '["Puantilizm","Kolaj","Frottage","Chiaroscuro"]'::jsonb, 3, 'sanat'),
('Fresk tekniği nereye uygulanır?', '["Islak sıva üzerine","Tuval üzerine","Cam üzerine","Metal üzerine"]'::jsonb, 0, 'sanat'),
('Tempera boyada bağlayıcı olarak ne kullanılır?', '["Keten yağı","Yumurta","Su","Reçine"]'::jsonb, 1, 'sanat'),
('Yağlı boyanın Rönesans''ta yaygınlaşmasının nedeni nedir?', '["Ucuz olması","Kokusuz olması","Yavaş kuruyup detay imkânı vermesi","Hızlı kuruması"]'::jsonb, 2, 'sanat'),
('Suluboyanın belirgin özelliği nedir?', '["Kalın doku vermesi","Işıksız olması","Kâğıda uygun olmaması","Saydam katmanlar oluşturması"]'::jsonb, 3, 'sanat'),
('Akrilik boyanın yağlı boyaya göre farkı nedir?', '["Hızlı kuruması","Yavaş kuruması","Su geçirmemesi","Kokusuz olmaması"]'::jsonb, 0, 'sanat'),
('Gravür sanatında görüntü nasıl elde edilir?', '["Fırçayla boyanarak","Oyulmuş kalıptan baskı alınarak","Kalemle çizilerek","Yakılarak"]'::jsonb, 1, 'sanat'),
('Litografi baskı tekniği neye dayanır?', '["Metal oymaya","Ahşap kesmeye","Yağ ve suyun birbirini itmesine","İpek eleğe"]'::jsonb, 2, 'sanat'),
('Serigrafi tekniğinde ne kullanılır?', '["Taş yüzey","Bakır levha","Ahşap blok","İpek elek ve şablon"]'::jsonb, 3, 'sanat'),
('Kolaj tekniği neye dayanır?', '["Farklı malzemelerin yapıştırılmasına","Boya karışımına","Taş yontmaya","Metal dökmeye"]'::jsonb, 0, 'sanat'),
('Heykelde ''yontma'' yöntemi nasıl çalışır?', '["Malzeme ekleyerek","Malzemeden eksilterek","Döküm yaparak","Kaynak yaparak"]'::jsonb, 1, 'sanat'),
('Bronz heykelde kullanılan döküm yöntemi hangisidir?', '["Taş yontma","Ahşap oyma","Kayıp mum yöntemi","Kil pişirme"]'::jsonb, 2, 'sanat'),
('Rölyef nedir?', '["Serbest duran heykel","Duvar resmi","Cam işleme","Yüzeyden kabartma heykel"]'::jsonb, 3, 'sanat'),
('Mozaik sanatında hangi malzeme kullanılır?', '["Küçük renkli taş ve cam parçaları","Yağlı boya","İpek iplik","Alçı kalıp"]'::jsonb, 0, 'sanat'),
('Vitray sanatı hangi malzemeye dayanır?', '["Mermer","Renkli cam","Ahşap","Kumaş"]'::jsonb, 1, 'sanat'),
('Osmanlı minyatüründe perspektif neden kullanılmaz?', '["Boyanın yetersizliği","Kâğıdın küçüklüğü","Anlatım geleneğinin farklı olması","Yasak olması"]'::jsonb, 2, 'sanat'),
('Levni hangi sanat dalında tanınır?', '["Hat","Ebru","Çini","Minyatür"]'::jsonb, 3, 'sanat'),
('Hat sanatında sülüs ve nesih neyi ifade eder?', '["Yazı çeşitlerini","Kâğıt türlerini","Mürekkep renklerini","Kalem markalarını"]'::jsonb, 0, 'sanat'),
('Tezhip sanatı neyi süsler?', '["Duvar yüzeylerini","El yazması sayfa kenarlarını","Halı desenlerini","Cam eşyayı"]'::jsonb, 1, 'sanat'),
('Çini sanatında ağırlıklı olarak hangi renk kullanılır?', '["Kahverengi","Siyah","Mavi tonları","Mor"]'::jsonb, 2, 'sanat'),
('İznik çinilerinin ünlendiği dönem hangisidir?', '["Roma dönemi","Bizans dönemi","Cumhuriyet dönemi","Klasik Osmanlı dönemi"]'::jsonb, 3, 'sanat'),
('Barok üslubun temel özelliği nedir?', '["Hareketli ve gösterişli anlatım","Sade ve simetrik düzen","Geometrik soyutlama","Tek renk kullanımı"]'::jsonb, 0, 'sanat'),
('Rokoko üslubu neyle tanınır?', '["Ağır ve anıtsal biçim","İnce, süslü ve zarif bezeme","Endüstriyel malzeme","Soyut lekeler"]'::jsonb, 1, 'sanat'),
('Neoklasik sanat hangi dönemden esinlenmiştir?', '["Orta Çağ","Barok","Antik Yunan ve Roma","Gotik"]'::jsonb, 2, 'sanat'),
('Romantizm sanatında öne çıkan nedir?', '["Matematiksel düzen","Endüstri övgüsü","Belgesel gerçeklik","Duygu ve doğanın gücü"]'::jsonb, 3, 'sanat'),
('Gerçekçilik (realizm) akımı neyi konu alır?', '["Gündelik yaşamı olduğu gibi","Mitolojik sahneleri","Soyut biçimleri","Dinî konuları"]'::jsonb, 0, 'sanat'),
('Empresyonizmde ressamlar neyi yakalamaya çalışmıştır?', '["Kesin çizgileri","Işığın anlık etkisini","Dinî öyküleri","Geometrik düzeni"]'::jsonb, 1, 'sanat'),
('Puantilizm tekniği neye dayanır?', '["Geniş fırça darbelerine","Tek renk kullanımına","Renk noktalarının yan yana konmasına","Kolaja"]'::jsonb, 2, 'sanat'),
('Post-empresyonizmin öncülerinden biri kimdir?', '["Claude Monet","Edouard Manet","Camille Pissarro","Paul Cezanne"]'::jsonb, 3, 'sanat'),
('Fovizm akımının ayırt edici özelliği nedir?', '["Çarpıcı ve doğal olmayan renkler","Gri tonlar","Fotoğrafik gerçeklik","Geometrik düzen"]'::jsonb, 0, 'sanat'),
('Kübizm akımının kurucularından biri kimdir?', '["Salvador Dali","Georges Braque","Wassily Kandinsky","Edvard Munch"]'::jsonb, 1, 'sanat'),
('Dadaizm akımı neye tepki olarak doğmuştur?', '["Empresyonizme","Fotoğrafa","Savaşa ve geleneksel değerlere","Mimarlığa"]'::jsonb, 2, 'sanat'),
('Sürrealizm neyi konu alır?', '["Belgesel gerçeği","Endüstriyel üretimi","Geometrik düzeni","Bilinçdışı ve rüya imgelerini"]'::jsonb, 3, 'sanat'),
('Salvador Dali hangi akımın temsilcisidir?', '["Sürrealizm","Kübizm","Fütürizm","Empresyonizm"]'::jsonb, 0, 'sanat'),
('Soyut sanatın temel özelliği nedir?', '["Fotoğrafik olması","Tanınabilir nesne göstermemesi","Yalnız portre olması","Manzara olması"]'::jsonb, 1, 'sanat'),
('Wassily Kandinsky hangi alanda öncüdür?', '["Fotogerçekçilik","Barok heykel","Soyut resim","Gotik mimari"]'::jsonb, 2, 'sanat'),
('De Stijl akımı hangi biçimlerle çalışır?', '["Eğrisel süslemeler","Doğal manzaralar","Portreler","Yatay-dikey çizgiler ve ana renkler"]'::jsonb, 3, 'sanat'),
('Piet Mondrian hangi akımla anılır?', '["De Stijl","Fovizm","Barok","Rokoko"]'::jsonb, 0, 'sanat'),
('Soyut dışavurumculuğun merkezi hangi şehir olmuştur?', '["Paris","New York","Berlin","Roma"]'::jsonb, 1, 'sanat'),
('Pop art akımı neyden beslenmiştir?', '["Antik mitolojiden","Dinî öykülerden","Popüler kültür ve reklamdan","Kırsal yaşamdan"]'::jsonb, 2, 'sanat'),
('Andy Warhol hangi akımın temsilcisidir?', '["Kübizm","Dadaizm","Barok","Pop art"]'::jsonb, 3, 'sanat'),
('Performans sanatının malzemesi nedir?', '["Sanatçının bedeni ve eylemi","Tuval","Mermer","Bronz"]'::jsonb, 0, 'sanat'),
('Enstalasyon (yerleştirme) sanatı neyi kullanır?', '["Yalnız tuvali","Mekânın bütününü","Yalnız kâğıdı","Yalnız sesi"]'::jsonb, 1, 'sanat'),
('Video art hangi araçla üretilir?', '["Yağlı boya","Mermer","Hareketli görüntü","Alçı"]'::jsonb, 2, 'sanat'),
('Sokak sanatının yaygın biçimi hangisidir?', '["Fresk","Vitray","Tezhip","Grafiti"]'::jsonb, 3, 'sanat'),
('Gotik mimarinin ayırt edici öğesi nedir?', '["Sivri kemer ve uçan payanda","Yuvarlak kemer","Düz çatı","Kubbe zorunluluğu"]'::jsonb, 0, 'sanat'),
('Roman (Romanesk) mimarinin özelliği nedir?', '["İnce duvar ve sivri kemer","Kalın duvar ve yuvarlak kemer","Cam cephe","Çelik iskelet"]'::jsonb, 1, 'sanat'),
('Bizans mimarisinin simge yapısı hangisidir?', '["Notre Dame","Parthenon","Ayasofya","Taç Mahal"]'::jsonb, 2, 'sanat'),
('Selçuklu mimarisinde taçkapı neyi ifade eder?', '["Kubbe kasnağı","İç avlu","Minare şerefesi","Anıtsal giriş kapısı"]'::jsonb, 3, 'sanat'),
('Osmanlı camilerinde ''merkezî kubbe'' düzeni neyi amaçlar?', '["Geniş ve bölünmemiş iç mekân","Yüksek minare","Dar koridor","Çok katlı yapı"]'::jsonb, 0, 'sanat'),
('Modern mimaride ''form işlevi izler'' ilkesi kime aittir?', '["Le Corbusier","Louis Sullivan","Frank Gehry","Antoni Gaudi"]'::jsonb, 1, 'sanat'),
('Le Corbusier hangi alanda tanınır?', '["Heykel","Resim dışı hiçbiri","Modern mimarlık","Müzik"]'::jsonb, 2, 'sanat'),
('Antoni Gaudi''nin tamamlanmamış ünlü yapısı hangisidir?', '["Notre Dame","Ayasofya","Kolezyum","Sagrada Familia"]'::jsonb, 3, 'sanat'),
('Frank Lloyd Wright''ın doğayla bütünleşen ünlü evi hangisidir?', '["Şelale Evi","Villa Savoye","Cam Ev","Farnsworth Evi"]'::jsonb, 0, 'sanat'),
('Müzelerde ''restorasyon'' ne demektir?', '["Eseri yeniden yapmak","Eseri özgün hâline yaklaştırarak onarmak","Eseri satmak","Eseri kopyalamak"]'::jsonb, 1, 'sanat'),
('Konservasyon (koruma) çalışmasının amacı nedir?', '["Eseri değiştirmek","Eseri boyamak","Eserin bozulmasını yavaşlatmak","Eseri taşımak"]'::jsonb, 2, 'sanat'),
('Bienal ne anlama gelir?', '["Yılda iki kez sergi","Sürekli sergi","Tek günlük sergi","İki yılda bir düzenlenen sergi"]'::jsonb, 3, 'sanat'),
('Küratörün sergideki görevi nedir?', '["Sergiyi kavramsal olarak kurgulamak","Bilet satmak","Eser üretmek","Duvar boyamak"]'::jsonb, 0, 'sanat'),
('Olimpiyat sloganı neyi ifade eder?', '["Daha hızlı, daha yüksek, daha güçlü","Barış, dostluk, sevgi","Bir arada, ileri, güçlü","Güç, hız, zafer"]'::jsonb, 0, 'spor'),
('Maratonun uzunluğu yaklaşık ne kadardır?', '["21 kilometre","42 kilometre","10 kilometre","50 kilometre"]'::jsonb, 1, 'spor'),
('Yarı maraton kaç kilometredir?', '["42 kilometre","15 kilometre","21 kilometre","30 kilometre"]'::jsonb, 2, 'spor'),
('Heptatlon hangi kategoride yapılır?', '["Erkekler","Karma","Gençler","Kadınlar"]'::jsonb, 3, 'spor'),
('Atletizmde ''sırıkla yüksek atlama'' hangi araçla yapılır?', '["Esnek sırık","Trambolin","Halat","Yay"]'::jsonb, 0, 'spor'),
('Gülle atmada kullanılan araç nedir?', '["Disk","Metal küre","Cirit","Çekiç"]'::jsonb, 1, 'spor'),
('Yüzmede ''kelebek'' hangi stilin adıdır?', '["Bir atlama biçimi","Bir başlangıç şekli","Bir yüzme stili","Bir dönüş tekniği"]'::jsonb, 2, 'spor'),
('Sırtüstü yüzme stilinde start nasıl alınır?', '["Blok üstünden","Trambolinden","Kenardan koşarak","Suyun içinden"]'::jsonb, 3, 'spor'),
('Artistik jimnastikte erkeklerde bulunan alet hangisidir?', '["Halka","Denge aleti","Kurdele","Çember"]'::jsonb, 0, 'spor'),
('Ritmik jimnastikte kullanılan araçlardan biri hangisidir?', '["Paralel bar","Kurdele","Halka","Atlama beygiri"]'::jsonb, 1, 'spor'),
('Basketbolda şut saati kaç saniyedir?', '["30 saniye","45 saniye","24 saniye","12 saniye"]'::jsonb, 2, 'spor'),
('Voleybolda bir takım toptaki en fazla kaç dokunuş hakkına sahiptir?', '["İki","Dört","Beş","Üç"]'::jsonb, 3, 'spor'),
('Hentbolde kaleye atış yapılan alan nasıl sınırlanır?', '["Kale sahası çizgisiyle","Orta çizgiyle","Kenar çizgisiyle","Ceza noktasıyla"]'::jsonb, 0, 'spor'),
('Futbolda VAR sistemi ne için kullanılır?', '["Süre tutmak","Video ile karar incelemesi","Bilet satmak","Saha ölçmek"]'::jsonb, 1, 'spor'),
('Tenis maçında ''deuce'' hangi skorda söylenir?', '["30-30","15-15","40-40","0-0"]'::jsonb, 2, 'spor'),
('Tenis turnuvalarında ''Grand Slam'' kaç turnuvadan oluşur?', '["Üç","Beş","Altı","Dört"]'::jsonb, 3, 'spor'),
('Golfte ''birdie'' ne anlama gelir?', '["Par''ın bir altında bitirmek","Par''ın bir üstünde bitirmek","Delikte bir vuruş","Oyunu bırakmak"]'::jsonb, 0, 'spor'),
('Judo sporunun kökeni hangi ülkedir?', '["Kore","Japonya","Çin","Tayland"]'::jsonb, 1, 'spor'),
('Tekvando hangi ülkenin geleneksel sporudur?', '["Japonya","Çin","Güney Kore","Vietnam"]'::jsonb, 2, 'spor'),
('Karate sporunda ''kata'' ne anlama gelir?', '["Serbest dövüş","Hakem kararı","Kuşak töreni","Belirlenmiş hareket dizisi"]'::jsonb, 3, 'spor'),
('Eskrim sporunda kullanılan silahlardan biri hangisidir?', '["Flöre","Sopa","Mızrak","Balta"]'::jsonb, 0, 'spor'),
('Giro d''Italia hangi ülkenin bisiklet turudur?', '["Fransa","İtalya","İspanya","Portekiz"]'::jsonb, 1, 'spor'),
('Formula 1''de ''pole pozisyonu'' nasıl kazanılır?', '["Yarışı kazanarak","Kura ile","Sıralama turlarında en iyi dereceyle","Puan sırasına göre"]'::jsonb, 2, 'spor'),
('Ralli yarışlarında kopilotun görevi nedir?', '["Aracı sürmek","Lastik değiştirmek","Zaman tutmak","Yol notlarını okumak"]'::jsonb, 3, 'spor'),
('Buz hokeyinde oyun alanına ne ad verilir?', '["Ring (rink)","Kort","Pist","Saha çemberi"]'::jsonb, 0, 'spor'),
('Biatlon hangi iki dalın birleşimidir?', '["Yüzme ve koşu","Kayaklı koşu ve atıcılık","Bisiklet ve koşu","Kayak ve atlama"]'::jsonb, 1, 'spor'),
('Triatlon hangi üç dalı içerir?', '["Koşu, atlama, atma","Yüzme, kürek, koşu","Yüzme, bisiklet, koşu","Bisiklet, boks, koşu"]'::jsonb, 2, 'spor'),
('Kürek sporunda ''tek çifte'' ne demektir?', '["İki sporcunun tek kürekle","Dört kişilik tekne","Sekiz kişilik tekne","Tek sporcunun iki kürekle yarışması"]'::jsonb, 3, 'spor'),
('Yelken yarışlarında rüzgâr yönüne karşı ilerlemeye ne denir?', '["Orsa","Pupa","Apaz","Demir"]'::jsonb, 0, 'spor'),
('Güreşte ''tuş'' ne anlama gelir?', '["Puan almak","Rakibin sırtını yere getirmek","Uyarı almak","Süre bitmek"]'::jsonb, 1, 'spor'),
('Yağlı güreşin yapıldığı geleneksel etkinlik hangisidir?', '["Nevruz","Hıdırellez","Kırkpınar","Ahilik Haftası"]'::jsonb, 2, 'spor'),
('Cirit oyunu geleneksel olarak ne üzerinde oynanır?', '["Yaya olarak","Buzda","Suda","At sırtında"]'::jsonb, 3, 'spor'),
('Türkiye''nin geleneksel sporlarından biri olan mangala nedir?', '["Strateji taşı oyunu","Bir güreş türü","Bir at yarışı","Bir okçuluk dalı"]'::jsonb, 0, 'spor'),
('Satrançta ''pat'' durumu ne anlama gelir?', '["Yenilgi","Beraberlik","Galibiyet","Hükmen mağlubiyet"]'::jsonb, 1, 'spor'),
('FIFA hangi sporun uluslararası federasyonudur?', '["Basketbol","Voleybol","Futbol","Atletizm"]'::jsonb, 2, 'spor'),
('FIBA hangi sporun federasyonudur?', '["Futbol","Hentbol","Voleybol","Basketbol"]'::jsonb, 3, 'spor'),
('UEFA hangi kıtanın futbol konfederasyonudur?', '["Avrupa","Asya","Afrika","Güney Amerika"]'::jsonb, 0, 'spor'),
('IAAF/World Athletics hangi sporu yönetir?', '["Yüzme","Atletizm","Bisiklet","Kayak"]'::jsonb, 1, 'spor'),
('WADA kuruluşunun görevi nedir?', '["Hakem atamak","Bilet satmak","Dopingle mücadele","Saha yapmak"]'::jsonb, 2, 'spor'),
('CAS (Spor Tahkim Mahkemesi) hangi konuda karar verir?', '["Bilet fiyatları","Saha bakımı","Forma tasarımı","Sporla ilgili hukuki uyuşmazlıklar"]'::jsonb, 3, 'spor'),
('Sporcu ''transfer bedeli'' neyi ifade eder?', '["Kulüpler arası geçiş için ödenen ücret","Sporcunun maaşı","Bilet geliri","Sponsor ücreti"]'::jsonb, 0, 'spor'),
('Fair play ödülü neye verilir?', '["En çok gol atana","Sportmenlik davranışına","En hızlı koşana","En çok maç yapana"]'::jsonb, 1, 'spor'),
('Sporda ''antrenman periyotlaması'' neyi amaçlar?', '["Sakatlığı artırmayı","Süreyi kısaltmayı","Performansı planlı zirveye taşımayı","Beslenmeyi bozmayı"]'::jsonb, 2, 'spor'),
('Sporda ''VO2 maks'' neyi ölçer?', '["Kas gücünü","Esnekliği","Denge yeteneğini","Maksimum oksijen kullanım kapasitesini"]'::jsonb, 3, 'spor'),
('Isınmanın temel amacı nedir?', '["Sakatlanma riskini azaltmak","Yorgunluk yaratmak","Kas kaybı sağlamak","Süreyi doldurmak"]'::jsonb, 0, 'spor')
on conflict (soru) do nothing;
