-- Soru havuzu genişletme: sinema +22, teknoloji +26, muzik +24, spor +24, sanat +18
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Bilim kurgu sinemasının temel konusu nedir?', '["Bilim ve teknolojinin kurgusal sonuçları","Tarihsel olaylar","Aşk ilişkileri","Spor yarışları"]'::jsonb, 0, 'sinema'),
('Korku sinemasında ''gerilim yaratma'' hangi araçla güçlendirilir?', '["Uzun jenerik","Ses ve ışık kullanımı","Geniş kadro","Renkli afiş"]'::jsonb, 1, 'sinema'),
('Gişe filmi (blockbuster) kavramı neyi anlatır?', '["Düşük bütçeli deneysel film","Kısa film","Yüksek bütçeli, geniş kitlelik film","Belgesel"]'::jsonb, 2, 'sinema'),
('Sinemada ''tür karması'' ne demektir?', '["Tek türde kalmak","Belgesel çekmek","Kısa film yapmak","Birden çok türün birleştirilmesi"]'::jsonb, 3, 'sinema'),
('Gerilim (thriller) filmlerinde izleyicide amaçlanan duygu nedir?', '["Sürekli merak ve tedirginlik","Kahkaha","Uyku","Hüzün"]'::jsonb, 0, 'sinema'),
('Kara film (film noir) anlatısında tipik karakter kimdir?', '["Süper kahraman","Ahlaki olarak gri dedektif","Çocuk kahraman","Uzaylı"]'::jsonb, 1, 'sinema'),
('Savaş filmlerinde ''anti-militarist'' bakış neyi vurgular?', '["Zaferi","Kahramanlığı","Savaşın yıkıcılığını","Silah teknolojisini"]'::jsonb, 2, 'sinema'),
('Biyografi filmi neyi konu alır?', '["Kurgusal kahramanı","Hayvanları","Doğa olaylarını","Gerçek bir kişinin yaşamını"]'::jsonb, 3, 'sinema'),
('Yol filmi (road movie) anlatısı neye dayanır?', '["Yolculuk boyunca dönüşüme","Tek mekânda kalmaya","Savaş sahnelerine","Dans gösterisine"]'::jsonb, 0, 'sinema'),
('Sinemada ''kara mizah'' neyi birleştirir?', '["Aksiyon ve romantizmi","Karanlık konuyu gülünç anlatımla","Belgesel ve animasyonu","Müzikal ve korkuyu"]'::jsonb, 1, 'sinema'),
('Bir filmin ''atmosferi'' neyle kurulur?', '["Yalnız senaryoyla","Yalnız oyuncuyla","Görüntü, ses ve mekân bütünlüğüyle","Yalnız afişle"]'::jsonb, 2, 'sinema'),
('Sinema salonunda ''perde oranı'' neyi belirtir?', '["Ses düzeyini","Koltuk sayısını","Bilet fiyatını","Görüntünün en-boy ilişkisini"]'::jsonb, 3, 'sinema'),
('Bir filmde ''süre'' anlatıya nasıl etki eder?', '["Ritmi ve gerilimi belirler","Rengi değiştirir","Sesi artırır","Afişi belirler"]'::jsonb, 0, 'sinema'),
('Bir film festivalinde ''jüri özel ödülü'' neyi belirtir?', '["İzleyici oylamasını","Jürinin öne çıkardığı yapımı","Gişe rekorunu","En uzun filmi"]'::jsonb, 1, 'sinema'),
('İzleyici ödülü nasıl belirlenir?', '["Jüri kararıyla","Gişe geliriyle","Seyirci oylarıyla","Basın oyuyla"]'::jsonb, 2, 'sinema'),
('Sinemada ''kadın yönetmen'' görünürlüğü hangi eğilimle artmıştır?', '["Bütçe kısıtlarıyla","Salon azalmasıyla","Bilet zammıyla","Festival ve kota politikalarıyla"]'::jsonb, 3, 'sinema'),
('Bağımsız yapımlarda dağıtımın zorluğu nedir?', '["Salon ve tanıtım bütçesi yetersizliği","Senaryo bulamamak","Oyuncu bulamamak","Kamera bulamamak"]'::jsonb, 0, 'sinema'),
('Film eleştirisinin işlevi nedir?', '["Bilet satmak","Yapıtı çözümleyip değerlendirmek","Fragman yapmak","Afiş basmak"]'::jsonb, 1, 'sinema'),
('Sinemada ''seyirci kimliği'' neyi etkiler?', '["Kurgu süresini","Kamera açısını","Filmin alımlanmasını","Işık düzenini"]'::jsonb, 2, 'sinema'),
('Bir filmin ''yeniden değerlendirilmesi'' ne demektir?', '["Yeniden çekilmesi","Kurgulanması","Seslendirilmesi","Zamanla değerinin yeniden tartışılması"]'::jsonb, 3, 'sinema'),
('Sinema tarihi yazımında ''akım'' kavramı neyi ifade eder?', '["Ortak estetik anlayışı paylaşan yapımlar","Aynı yıl çıkan filmler","Aynı ülkedeki filmler","Aynı süre filmler"]'::jsonb, 0, 'sinema'),
('Sinemada ''ulusal sinema'' kavramı neye vurgu yapar?', '["Yalnız dile","Ülkeye özgü anlatı ve üretim koşullarına","Yalnız bütçeye","Yalnız salon sayısına"]'::jsonb, 1, 'sinema'),
('Bilgisayar ağlarında ''topoloji'' neyi ifade eder?', '["Cihazların bağlanma düzenini","Kablo rengini","Veri türünü","Şifre uzunluğunu"]'::jsonb, 0, 'teknoloji'),
('Yıldız topolojisinde merkez ne bulunur?', '["Halka kablo","Anahtar veya dağıtıcı","Sonlandırıcı","Yedek disk"]'::jsonb, 1, 'teknoloji'),
('LAN ile WAN arasındaki fark nedir?', '["Kablo türü","Şifreleme","Kapsadıkları coğrafi alan","Cihaz markası"]'::jsonb, 2, 'teknoloji'),
('DHCP protokolü ne yapar?', '["Şifre üretir","Dosya taşır","Sayfa gösterir","Cihazlara otomatik IP dağıtır"]'::jsonb, 3, 'teknoloji'),
('NAT teknolojisi ne sağlar?', '["Birden çok cihazın tek IP ile çıkışını","Şifreleme","Sıkıştırma","Yedekleme"]'::jsonb, 0, 'teknoloji'),
('80 numaralı port hangi servisle ilişkilidir?', '["FTP","HTTP","SSH","SMTP"]'::jsonb, 1, 'teknoloji'),
('Ağ izleme araçlarının amacı nedir?', '["Kod yazmak","Sayfa tasarlamak","Trafiği ve arızayı görebilmek","Yazıcı sürmek"]'::jsonb, 2, 'teknoloji'),
('Sunucu ''kesinti süresi'' (downtime) neyi ifade eder?', '["Bakım maliyetini","Kullanıcı sayısını","Veri boyutunu","Hizmet veremediği süreyi"]'::jsonb, 3, 'teknoloji'),
('Yedeklilik (redundancy) neyi sağlar?', '["Arıza durumunda hizmetin sürmesini","Hızın artmasını","Maliyetin düşmesini","Verinin silinmesini"]'::jsonb, 0, 'teknoloji'),
('Felaket kurtarma planı neyi kapsar?', '["Yeni ürün geliştirmeyi","Büyük kesintide sistemi geri getirmeyi","Pazarlama planını","İşe alımı"]'::jsonb, 1, 'teknoloji'),
('Veri bütünlüğü kavramı neyi güvence altına alır?', '["Verinin hızlı olmasını","Verinin büyümesini","Verinin doğru ve tutarlı kalmasını","Verinin silinmesini"]'::jsonb, 2, 'teknoloji'),
('Şifreleme anahtarının uzunluğu neyi etkiler?', '["Dosya boyutunu yalnızca","Ekran çözünürlüğünü","Ağ hızını","Kırılma zorluğunu"]'::jsonb, 3, 'teknoloji'),
('Yazılım lisansı neyi belirler?', '["Kullanım koşullarını","Kurulum süresini","Dosya boyutunu","Ekran rengini"]'::jsonb, 0, 'teknoloji'),
('GPL gibi lisanslar hangi ilkeyi taşır?', '["Kaynağın gizlenmesini","Türev çalışmaların da açık kalmasını","Ücretsizlik yasağını","Ticari kullanım yasağını"]'::jsonb, 1, 'teknoloji'),
('Yazılımda ''sürüm numarası'' ne bildirir?', '["Fiyatı","Dosya boyutunu","Değişikliklerin düzeyini","Kullanıcı sayısını"]'::jsonb, 2, 'teknoloji'),
('Beta sürüm ne anlama gelir?', '["Son kararlı sürüm","Kaldırılmış sürüm","Ticari sürüm","Yaygın teste açılmış öncül sürüm"]'::jsonb, 3, 'teknoloji'),
('Geriye dönük uyumluluk neyi sağlar?', '["Eski sürümlerle çalışabilmeyi","Yeni donanım gerektirmeyi","Veriyi silmeyi","Hızı artırmayı"]'::jsonb, 0, 'teknoloji'),
('Kullanıcı deneyimi (UX) tasarımı neyi hedefler?', '["Kodun kısalmasını","Kullanımın kolay ve doyurucu olmasını","Sunucu hızını","Dosya boyutunu"]'::jsonb, 1, 'teknoloji'),
('Erişilebilirlik (accessibility) tasarımda neyi amaçlar?', '["Yalnız uzmanların kullanmasını","Hızı artırmayı","Herkesin kullanabilmesini","Maliyeti düşürmeyi"]'::jsonb, 2, 'teknoloji'),
('Ekran okuyucu yazılımı kimin için geliştirilmiştir?', '["Çocuklar","Yöneticiler","Geliştiriciler","Görme engelli kullanıcılar"]'::jsonb, 3, 'teknoloji'),
('Karanlık mod (dark mode) hangi durumda avantaj sağlar?', '["Düşük ışıkta göz yorgunluğunu azaltmada","Yüksek ışıkta okumada","Baskıda","Ses kalitesinde"]'::jsonb, 0, 'teknoloji'),
('Uygulama mağazasının işlevi nedir?', '["Donanım satışı","Yazılım dağıtımı ve güncellemesi","İnternet sağlama","Veri saklama"]'::jsonb, 1, 'teknoloji'),
('Mobil uygulamada ''yerel'' ile ''web'' fark nedir?', '["Web''in kurulması","İkisinin aynı olması","Yerelin cihaza kurulması","Yerelin tarayıcıda çalışması"]'::jsonb, 2, 'teknoloji'),
('Çevrim dışı çalışma özelliği ne sağlar?', '["Daha hızlı ağ","Daha çok veri","Otomatik güncelleme","İnternetsiz de kullanılabilmeyi"]'::jsonb, 3, 'teknoloji'),
('Anlık bildirim (push) ne sağlar?', '["Uygulama kapalıyken haber vermeyi","Veri sıkıştırmayı","Şifre üretmeyi","Ekran açmayı"]'::jsonb, 0, 'teknoloji'),
('Uygulama izinlerinin sınırlanması neyi korur?', '["Pil ömrünü yalnızca","Kullanıcı gizliliğini","Ekran parlaklığını","Ağ hızını"]'::jsonb, 1, 'teknoloji'),
('Rock müzikte ''riff'' ne anlama gelir?', '["Yinelenen kısa ezgi kalıbı","Şarkı sözü","Davul solosu","Konser adı"]'::jsonb, 0, 'muzik'),
('Elektro gitarda ''distortion'' efekti ne yapar?', '["Sesi yumuşatır","Sesi bozarak sert bir tını verir","Tempoyu artırır","Notayı değiştirir"]'::jsonb, 1, 'muzik'),
('Bas gitarın topluluktaki rolü nedir?', '["Ana ezgiyi taşımak","Vurmalı görevi","Ritim ve armoni temelini kurmak","Solo zorunluluğu"]'::jsonb, 2, 'muzik'),
('Davul setinde ''hi-hat'' nedir?', '["Büyük davul","Trampet","Tom","Ayakla açılıp kapanan zil çifti"]'::jsonb, 3, 'muzik'),
('Metronom kullanımının çalışmadaki yararı nedir?', '["Tempo istikrarı kazandırması","Ses gürlüğü","Nota okuma","Akort tutma"]'::jsonb, 0, 'muzik'),
('Akustik gitar ile klasik gitar arasındaki fark nedir?', '["Perde sayısı","Tel malzemesi ve tını","Renk","Boyut zorunluluğu"]'::jsonb, 1, 'muzik'),
('Kapo (capo) gitarda ne sağlar?', '["Teli gevşetmeyi","Sesi kısmayı","Tonu yükseltmeyi","Perde eklemeyi"]'::jsonb, 2, 'muzik'),
('Piyanoda pedalın işlevi nedir?', '["Tonu değiştirmek","Tempo tutmak","Nota yazmak","Sesi uzatmak veya kısmak"]'::jsonb, 3, 'muzik'),
('Bir albümde ''single'' ne anlama gelir?', '["Tanıtım için öne çıkarılan tek parça","Albümün tamamı","Konser kaydı","Kapak tasarımı"]'::jsonb, 0, 'muzik'),
('Canlı albüm neyi içerir?', '["Stüdyo kaydını","Konser kaydını","Demo kaydını","Prova kaydını"]'::jsonb, 1, 'muzik'),
('Cover (yeniden yorum) ne demektir?', '["Yeni eser bestelemek","Söz yazmak","Başkasının eserini yeniden seslendirmek","Klip çekmek"]'::jsonb, 2, 'muzik'),
('Remix çalışması neyi yapar?', '["Yeni söz yazmak","Konser vermek","Nota basmak","Var olan parçayı yeniden düzenlemek"]'::jsonb, 3, 'muzik'),
('Sampling tekniği nedir?', '["Var olan kayıttan parça alıp kullanmak","Canlı çalmak","Nota yazmak","Akort etmek"]'::jsonb, 0, 'muzik'),
('DJ''in setteki temel işi nedir?', '["Beste yapmak","Parçaları akıcı biçimde birleştirmek","Nota yazmak","Sahne kurmak"]'::jsonb, 1, 'muzik'),
('Elektronik dansta ''BPM'' neyi ölçer?', '["Ses şiddetini","Frekansı","Dakikadaki vuruş sayısını","Süreyi"]'::jsonb, 2, 'muzik'),
('Ses kartının stüdyodaki işlevi nedir?', '["Nota yazmak","Işık vermek","Kayıt silmek","Analog sesi sayısala çevirmek"]'::jsonb, 3, 'muzik'),
('Kondenser mikrofonun avantajı nedir?', '["Ayrıntıyı hassas yakalaması","Dayanıklılığı","Ucuzluğu","Enerjisiz çalışması"]'::jsonb, 0, 'muzik'),
('Pop filtresi kayıtta ne engeller?', '["Yankıyı","Patlayıcı ünsüz seslerini","Uğultuyu","Tempoyu"]'::jsonb, 1, 'muzik'),
('Reverb efekti neyi taklit eder?', '["Gecikmeyi","Bozulmayı","Mekân yankısını","Sıkıştırmayı"]'::jsonb, 2, 'muzik'),
('Kompresör efekti ne yapar?', '["Tempoyu değiştirir","Tonu değiştirir","Yankı ekler","Ses düzeyi farklarını dengeler"]'::jsonb, 3, 'muzik'),
('Ekolayzır (EQ) ne sağlar?', '["Frekans dengesini ayarlamayı","Tempo ayarını","Nota düzeltmeyi","Kayıt silmeyi"]'::jsonb, 0, 'muzik'),
('Müzik yayıncılığında ''katalog'' ne anlama gelir?', '["Albüm kapağı","Sahip olunan eser haklarının bütünü","Konser takvimi","Bilet listesi"]'::jsonb, 1, 'muzik'),
('Konservatuvarın işlevi nedir?', '["Müze işletmek","Plak basmak","Müzik ve sahne sanatları eğitimi","Konser satmak"]'::jsonb, 2, 'muzik'),
('Orkestra provasında ''genel prova'' ne demektir?', '["İlk okuma","Bölüm provası","Solist provası","Konser koşullarında son prova"]'::jsonb, 3, 'muzik'),
('Esneklik antrenmanının yararı nedir?', '["Hareket açıklığını artırmak","Kas kütlesini artırmak","Dayanıklılığı azaltmak","Hızı düşürmek"]'::jsonb, 0, 'spor'),
('Kuvvet antrenmanında ''set'' ne demektir?', '["Tek tekrar","Bir tekrar grubunun tamamı","Dinlenme süresi","Antrenman günü"]'::jsonb, 1, 'spor'),
('Sporcu beslenmesinde karbonhidratın rolü nedir?', '["Kas yıkımı","Su tutma","Temel enerji kaynağı olmak","Vitamin sağlama"]'::jsonb, 2, 'spor'),
('Proteinin sporcu beslenmesindeki rolü nedir?', '["Hızlı enerji","Su dengesi","Isı üretimi","Kas onarımı ve yapımı"]'::jsonb, 3, 'spor'),
('Yarışma öncesi hidrasyonun önemi nedir?', '["Performans düşüşünü önlemek","Kilo artırmak","Uyku sağlamak","Kas yıkmak"]'::jsonb, 0, 'spor'),
('Sporda ''toparlanma'' (recovery) neyi kapsar?', '["Ek antrenman","Dinlenme, beslenme ve uyku","Yarışma","Seyahat"]'::jsonb, 1, 'spor'),
('Aktif dinlenme ne demektir?', '["Tam hareketsizlik","Ağır antrenman","Hafif hareketle toparlanma","Uyku"]'::jsonb, 2, 'spor'),
('Sporda ''aşırı antrenman sendromu'' neye yol açar?', '["Hızlı gelişim","Kas artışı","Sakatlık azalması","Performans düşüşü ve yorgunluk"]'::jsonb, 3, 'spor'),
('Isınmanın ardından yapılan dinamik germe neyi hedefler?', '["Hareket açıklığını artırmayı","Kas yıkmayı","Nabzı düşürmeyi","Uykuyu getirmeyi"]'::jsonb, 0, 'spor'),
('Soğuma (cool down) evresinin amacı nedir?', '["Performansı artırmak","Nabzı ve vücudu kademeli dinlendirmek","Ağırlık kaldırmak","Hız denemesi yapmak"]'::jsonb, 1, 'spor'),
('Kramp genellikle neyle ilişkilendirilir?', '["Fazla uykuyla","Soğuk havayla yalnızca","Sıvı ve mineral kaybıyla","Yüksek rakımla"]'::jsonb, 2, 'spor'),
('Buz uygulaması akut sakatlıkta neyi hedefler?', '["Kas kütlesini artırmayı","Esnekliği artırmayı","Isınmayı","Şişlik ve ağrıyı azaltmayı"]'::jsonb, 3, 'spor'),
('Fizyoterapinin sporda rolü nedir?', '["Sakatlık sonrası işlevi geri kazandırmak","Taktik geliştirmek","Beslenme planı yapmak","Antrenman yönetmek"]'::jsonb, 0, 'spor'),
('Sporda ''zihinsel hazırlık'' neyi içerir?', '["Kas geliştirme","Odaklanma ve baskıyla başa çıkma","Esneklik çalışması","Kilo verme"]'::jsonb, 1, 'spor'),
('Takım sporlarında ''taktik'' neyi ifade eder?', '["Uzun dönem hedef","Beslenme düzeni","Maç içi uygulanan oyun planı","Antrenman süresi"]'::jsonb, 2, 'spor'),
('Sporda ''strateji'' ile ''taktik'' farkı nedir?', '["Taktiğin uzun vadeli olması","İkisinin aynı olması","Stratejinin maç içi olması","Stratejinin uzun vadeli olması"]'::jsonb, 3, 'spor'),
('Bir sporcunun ''form durumu'' neyi ifade eder?', '["Güncel performans düzeyini","Yaşını","Boyunu","Takımını"]'::jsonb, 0, 'spor'),
('Amatör ile profesyonel sporcu farkı nedir?', '["Antrenman yapıp yapmaması","Sporun geçim kaynağı olup olmaması","Lisans sahibi olması","Yaş sınırı"]'::jsonb, 1, 'spor'),
('Sporda ''lisans'' neyi belgeler?', '["Sağlık durumunu yalnızca","Kulüp gelirini","Sporcunun resmî yarışma hakkını","Antrenör düzeyini"]'::jsonb, 2, 'spor'),
('Antrenör lisansı neyi gösterir?', '["Sporcu geçmişini","Kulüp sayısını","Maaş düzeyini","Eğitim ve yetkinlik düzeyini"]'::jsonb, 3, 'spor'),
('Spor hekimliğinin görev alanı nedir?', '["Sporcu sağlığı ve sakatlık yönetimi","Bilet satışı","Saha bakımı","Malzeme üretimi"]'::jsonb, 0, 'spor'),
('Dopingin sporcuya en büyük zararı nedir?', '["Süreli ceza yalnızca","Sağlığın kalıcı zarar görmesi","Maddi kayıp","Takım değişikliği"]'::jsonb, 1, 'spor'),
('Doping testi ne zaman yapılabilir?', '["Yalnız yarışma günü","Yalnız sezon sonu","Yarışma içinde ve dışında","Yalnız transferde"]'::jsonb, 2, 'spor'),
('Sporda ''engelli erişimi'' tesislerde neyi gerektirir?', '["Yalnız otopark","Yalnız bilet indirimi","Yalnız tabela","Rampa ve uygun donanımı"]'::jsonb, 3, 'spor'),
('Haute couture ne anlama gelir?', '["Kişiye özel üst düzey terzilik","Seri üretim","İkinci el giyim","Spor giyim"]'::jsonb, 0, 'sanat'),
('Endüstriyel tasarımın amacı nedir?', '["Tek eser üretmek","Seri üretilebilir işlevsel ürün","Duvar resmi yapmak","Heykel dökmek"]'::jsonb, 1, 'sanat'),
('Ergonomi tasarımda neyi gözetir?', '["Rengi","Fiyatı","İnsan vücuduna uygunluğu","Ağırlığı yalnızca"]'::jsonb, 2, 'sanat'),
('Peyzaj mimarlığı neyi tasarlar?', '["Bina cephesini","Mobilyayı","Afişi","Açık alan ve yeşil düzenlemeleri"]'::jsonb, 3, 'sanat'),
('Kent mobilyası kavramı neyi kapsar?', '["Bank, aydınlatma gibi kamusal öğeleri","Ev eşyasını","Ofis dolabını","Otel yatağını"]'::jsonb, 0, 'sanat'),
('Restorasyonda ''özgünlük ilkesi'' neyi savunur?', '["Modern malzeme kullanımını","Özgün malzeme ve tekniğe sadakati","Tamamen yenilemeyi","Yıkıp yapmayı"]'::jsonb, 1, 'sanat'),
('Anıt eser kavramı neyi ifade eder?', '["Yeni bina","Geçici yapı","Korunması gereken tarihî yapı","Depo"]'::jsonb, 2, 'sanat'),
('Sit alanı ilan edilmesi neyi sağlar?', '["Yapılaşmanın serbest kalmasını","Vergi artışını","Nüfus artışını","Bölgenin koruma altına alınmasını"]'::jsonb, 3, 'sanat'),
('Seramik ile porselen arasındaki fark nedir?', '["Porselenin daha ince ve saydam olması","Seramiğin saydam olması","İkisinin aynı olması","Porselenin pişmemesi"]'::jsonb, 0, 'sanat'),
('Cam üflemede ustanın kullandığı temel araç nedir?', '["Fırça","Üfleme borusu","Keski","Mengene"]'::jsonb, 1, 'sanat'),
('Ahşap oymacılığında kullanılan araç hangisidir?', '["Fırça","Mala","Keski","Şablon"]'::jsonb, 2, 'sanat'),
('Kilim dokumada motiflerin işlevi nedir?', '["Yalnız süsleme","Ağırlık artırma","Renk azaltma","Anlam ve kültürel simge taşımak"]'::jsonb, 3, 'sanat'),
('Bakır işlemede ''kalaylama'' neden yapılır?', '["Sağlık için yüzeyi kaplamak","Ağırlık vermek","Renk vermek yalnızca","Sertleştirmek"]'::jsonb, 0, 'sanat'),
('Telkâri sanatı hangi malzemeyle yapılır?', '["Ahşap","İnce gümüş tel","Cam","Deri"]'::jsonb, 1, 'sanat'),
('Kündekari tekniği hangi malzemede uygulanır?', '["Metal","Cam","Ahşap","Taş"]'::jsonb, 2, 'sanat'),
('Kalemişi süsleme nerede uygulanır?', '["Kâğıt kenarında","Cam üstünde","Halı üzerinde","Duvar ve tavan yüzeylerinde"]'::jsonb, 3, 'sanat'),
('Mukarnas mimaride nerede kullanılır?', '["Taçkapı ve kubbe geçişlerinde","Zeminde","Çatı örtüsünde","Pencere camında"]'::jsonb, 0, 'sanat'),
('Sanat eğitiminde ''desen'' çalışmasının amacı nedir?', '["Renk karıştırmak","Gözlem ve çizim becerisini geliştirmek","Heykel dökmek","Baskı almak"]'::jsonb, 1, 'sanat')
on conflict (soru) do nothing;
