-- ============================================================
-- Soru Partisi 16 — 500 soru
--   sinema 100 · teknoloji 200 · muzik 200
--
-- Kalite: tek ve tartışmasız doğru cevap; güncel sürüm/fiyat/şirket
-- durumu gibi zamanla değişen bilgi YOK; mevcut havuza karşı tekrar
-- taraması yapıldı. Sonunda yalnız bu partinin şıkları karışır.
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- ===================== SİNEMA (100) =====================
('Sinemada "senaryo" hangi aşamada hazırlanır?', '["Çekimden önce","Çekimden sonra","Vizyonda","Festivalde"]'::jsonb, 0, 'sinema'),
('Bir filmde "karakter yayı" ne demektir?', '["Kamera hareketi","Karakterin film boyunca değişimi","Ses efekti","Sahne süresi"]'::jsonb, 1, 'sinema'),
('Senaryoda "üç perde yapısı" neyi ifade eder?', '["Üç mekân","Üç oyuncu","Kuruluş, çatışma, çözüm","Üç kamera"]'::jsonb, 2, 'sinema'),
('Sinemada "doruk nokta" (klimaks) nedir?', '["Fragman","Açılış sahnesi","Jenerik","Gerilimin en yüksek anı"]'::jsonb, 3, 'sinema'),
('Filmde "çatışma" neden gereklidir?', '["Hikâyeyi ilerletmek için","Süreyi uzatmak için","Ses için","Işık için"]'::jsonb, 0, 'sinema'),
('Sinemada "antagonist" kimdir?', '["Yönetmen","Baş karakterin karşısındaki güç","Yapımcı","Kurgucu"]'::jsonb, 1, 'sinema'),
('"Protagonist" ne anlama gelir?', '["Anlatıcı","Kötü karakter","Hikâyenin baş karakteri","Figüran"]'::jsonb, 2, 'sinema'),
('Sinemada "McGuffin" ne demektir?', '["Işık tekniği","Kamera türü","Ses efekti","Olay örgüsünü tetikleyen nesne"]'::jsonb, 3, 'sinema'),
('Sinemada "deus ex machina" ne anlama gelir?', '["Beklenmedik dış müdahaleyle çözüm","Yavaş çekim","Ters kurgu","Ses geçişi"]'::jsonb, 0, 'sinema'),
('Filmde "açılış sahnesi" neyi belirler?', '["Bilet fiyatını","İzleyicinin ilk izlenimini","Ödülü","Süreyi"]'::jsonb, 1, 'sinema'),
('Sinemada "paralel kurgu" nedir?', '["Yavaş çekim","Tek olay","İki olayın dönüşümlü gösterimi","Ters oynatma"]'::jsonb, 2, 'sinema'),
('"Jump cut" ne anlama gelir?', '["Donma","Yumuşak geçiş","Kararma","Aynı çekimde ani zaman atlaması"]'::jsonb, 3, 'sinema'),
('Sinemada "match cut" nedir?', '["Benzer biçimlerle kurulan geçiş","Rastgele kesme","Kararma","Zoom"]'::jsonb, 0, 'sinema'),
('"Montaj sekansı" ne işe yarar?', '["Diyalog kurmak","Uzun süreci kısaca özetlemek","Ses ölçmek","Kadraj almak"]'::jsonb, 1, 'sinema'),
('Sinemada "kesintisiz uzun çekim" neyi vurgular?', '["Kurgu bolluğunu","Hızı","Gerçek zaman duygusunu","Renk çeşitliliğini"]'::jsonb, 2, 'sinema'),
('Filmde "diegetik ses" ne demektir?', '["Efekt yok","Dışarıdan eklenen müzik","Altyazı","Sahnenin içinden gelen ses"]'::jsonb, 3, 'sinema'),
('"Non-diegetik" müzik nedir?', '["Sahne dünyasında olmayan fon müziği","Radyodan çıkan ses","Oyuncunun şarkısı","Ortam gürültüsü"]'::jsonb, 0, 'sinema'),
('Sinemada "leitmotif" ne anlama gelir?', '["Kamera açısı","Tekrarlanan müzikal tema","Renk paleti","Kurgu hatası"]'::jsonb, 1, 'sinema'),
('Bir filmde "atmosfer" neyle kurulur?', '["Yalnız afiş","Yalnız diyalog","Işık, ses ve mekân birlikte","Yalnız süre"]'::jsonb, 2, 'sinema'),
('Filmde "ton" ne ifade eder?', '["Bilet türü","Ses seviyesi","Görüntü parlaklığı","Anlatının duygusal rengi"]'::jsonb, 3, 'sinema'),
('Sinemada "gerçek zamanlı anlatı" ne demektir?', '["Film süresi olay süresine eşittir","Geriye dönüş","Hızlandırma","Rüya sahnesi"]'::jsonb, 0, 'sinema'),
('"Bağımsız sinema"nın avantajı olarak görülen şey nedir?', '["Yüksek bütçe","Yaratıcı özgürlük","Geniş dağıtım","Ünlü kadro"]'::jsonb, 1, 'sinema'),
('Sinemada "auteur" kuramı neyi savunur?', '["Oyuncu merkezliliği","Yapımcının üstünlüğünü","Yönetmenin filmin asıl yazarı olduğunu","Kurgucunun üstünlüğü"]'::jsonb, 2, 'sinema'),
('"Sinematografi" terimi neyi kapsar?', '["Dağıtım","Senaryo yazımı","Ses miksajı","Görüntünün kamerayla oluşturulması"]'::jsonb, 3, 'sinema'),
('Objektifin "geniş açı" olması ne sağlar?', '["Daha geniş alanı kadraja almak","Uzağı yakınlaştırmak","Ses artışı","Renk doygunluğu"]'::jsonb, 0, 'sinema'),
('"Telefoto" objektif ne yapar?', '["Alanı genişletir","Uzaktaki nesneyi büyütür","Işığı keser","Ses kaydeder"]'::jsonb, 1, 'sinema'),
('Sinemada "kare hızı" (fps) neyi gösterir?', '["Ses kanalını","Renk sayısını","Saniyedeki kare sayısını","Süreyi"]'::jsonb, 2, 'sinema'),
('Yüksek kare hızıyla çekip normal hızda oynatmak ne sağlar?', '["Ses artışı","Hızlandırma","Renk değişimi","Yavaş çekim etkisi"]'::jsonb, 3, 'sinema'),
('Sinemada "en boy oranı" ne belirler?', '["Görüntü çerçevesinin biçimini","Ses formatını","Süreyi","Bilet fiyatını"]'::jsonb, 0, 'sinema'),
('"Letterbox" ne demektir?', '["Yan bantlar","Geniş görüntünün üst-alt siyah bantla gösterimi","Renk filtresi","Ses formatı"]'::jsonb, 1, 'sinema'),
('Sinemada "3 nokta aydınlatma" hangi ışıkları içerir?', '["İki flaş","Yalnız ana ışık","Ana, dolgu ve arka ışık","Doğal ışık"]'::jsonb, 2, 'sinema'),
('"Ana ışık" (key light) ne yapar?', '["Renk verir","Gölgeyi yumuşatır","Arkayı ayırır","Temel aydınlatmayı sağlar"]'::jsonb, 3, 'sinema'),
('"Dolgu ışığı" ne işe yarar?', '["Gölgeleri yumuşatmak","Gölgeyi artırmak","Odak vermek","Ses eklemek"]'::jsonb, 0, 'sinema'),
('Arka ışık (back light) ne sağlar?', '["Yüzü aydınlatmak","Konuyu fondan ayırmak","Gölge oluşturmak yalnızca","Renk düşürmek"]'::jsonb, 1, 'sinema'),
('Sinemada "low key" aydınlatma neyi yaratır?', '["Belgesel etkisi","Parlak neşeli hava","Karanlık ve gizemli atmosfer","Renk patlaması"]'::jsonb, 2, 'sinema'),
('"High key" aydınlatma nasıl bir etki verir?', '["Bulanık","Karanlık","Gölgeli","Aydınlık ve az gölgeli"]'::jsonb, 3, 'sinema'),
('Sinemada "kostüm" karaktere ne katar?', '["Görsel kimlik","Ses","Süre","Bütçe"]'::jsonb, 0, 'sinema'),
('"Sanat yönetmeni" ne yapar?', '["Kamera kullanır","Görsel tasarım ve dekoru yönetir","Kurgu yapar","Bilet satar"]'::jsonb, 1, 'sinema'),
('Sinemada "set" ne demektir?', '["Salon","Kurgu odası","Çekimin yapıldığı düzenlenmiş mekân","Afiş"]'::jsonb, 2, 'sinema'),
('"Lokasyon çekimi" ne anlama gelir?', '["Animasyon","Stüdyoda çekim","Yeşil perde","Gerçek mekânda çekim"]'::jsonb, 3, 'sinema'),
('Sinemada "klaket" ne işe yarar?', '["Görüntü ve sesi senkronlamak","Işık ölçmek","Renk vermek","Süre uzatmak"]'::jsonb, 0, 'sinema'),
('"Çekim planı" (shot list) ne içerir?', '["Bilet listesini","Çekilecek planların listesini","Oyuncu maaşını","Afiş tasarımını"]'::jsonb, 1, 'sinema'),
('Sinemada "prova" neden yapılır?', '["Kurgu yapmak","Bilet satmak","Sahneyi çekim öncesi denemek","Ses miksajı"]'::jsonb, 2, 'sinema'),
('"Reji" ne anlama gelir?', '["Dağıtım","Kurgu","Yapım bütçesi","Yönetmenlik işi"]'::jsonb, 3, 'sinema'),
('Bir filmin "ikinci ekibi" ne çeker?', '["Ana kadro gerektirmeyen planları","Başrol sahnelerini","Jeneriği","Fragmanı"]'::jsonb, 0, 'sinema'),
('Sinemada "yeşil ışık almak" ne demektir?', '["Çekimin iptali","Yapımın onaylanması","Vizyona girmesi","Ödül alması"]'::jsonb, 1, 'sinema'),
('Sinemada "bütçe" neyi belirler?', '["Ödülü","Filmin süresini","Yapımın olanaklarını","Türünü"]'::jsonb, 2, 'sinema'),
('Filmlerin yaş sınırlandırması neden yapılır?', '["Ses ayarı","Bilet artırmak","Süreyi kısaltmak","İçeriğin uygunluğunu belirtmek"]'::jsonb, 3, 'sinema'),
('Sinemada "dağıtımcı" ne yapar?', '["Filmi salonlara ulaştırır","Filmi çeker","Kurgular","Yazar"]'::jsonb, 0, 'sinema'),
('"Gala" gösterimi nedir?', '["Son gösterim","Filmin özel ilk gösterimi","Festival ödülü","Fragman"]'::jsonb, 1, 'sinema'),
('Sinemada "eleştirmen" ne yapar?', '["Bilet satar","Filmi çeker","Filmi değerlendirir","Işık tutar"]'::jsonb, 2, 'sinema'),
('Sessiz filmlerde müzik nasıl sağlanırdı?', '["Radyodan","Kayıttan","Dublajla","Salonda canlı çalınarak"]'::jsonb, 3, 'sinema'),
('Renkli sinemaya geçiş neyi değiştirmiştir?', '["Görsel anlatım olanaklarını","Süreyi","Bilet sistemini","Kurgu kurallarını"]'::jsonb, 0, 'sinema'),
('Geniş perde formatları hangi amaçla geliştirilmiştir?', '["Sesi artırmak","Sinemayı televizyondan ayırmak","Süre kısaltmak","Maliyet düşürmek"]'::jsonb, 1, 'sinema'),
('3D sinemada derinlik etkisi nasıl sağlanır?', '["Hızlı kurgu","Yüksek ses","İki farklı görüntünün ayrı gözlere ulaşmasıyla","Parlak renk"]'::jsonb, 2, 'sinema'),
('Dijital sinemaya geçişin en belirgin sonucu nedir?', '["Ses kaybı","Renk kaybı","Süre artışı","Film şeridinin yerini dosyaların alması"]'::jsonb, 3, 'sinema'),
('Sinemada "arşiv görüntüsü" ne demektir?', '["Daha önce çekilmiş kayıtlar","Yeni çekim","Animasyon","Fragman"]'::jsonb, 0, 'sinema'),
('Belgeselde "gözlemci yaklaşım" ne yapar?', '["Sahneler kurar","Müdahalesiz kaydeder","Oyuncu kullanır","Efekt ekler"]'::jsonb, 1, 'sinema'),
('"Docudrama" ne anlama gelir?', '["Animasyon","Tam kurgu","Gerçek olayların canlandırmalı anlatımı","Reklam"]'::jsonb, 2, 'sinema'),
('Sinemada "mockumentary" nedir?', '["Reklam","Gerçek belgesel","Haber","Belgesel biçiminde kurmaca"]'::jsonb, 3, 'sinema'),
('Kısa filmlerin festivallerdeki yeri nedir?', '["Ayrı kategori olarak yarışır","Yarışmaz","Yalnız açılışta","Yalnız kapanışta"]'::jsonb, 0, 'sinema'),
('Sinemada "omnibus film" ne demektir?', '["Tek uzun plan","Birden çok kısa bölümden oluşan film","Belgesel","Fragman"]'::jsonb, 1, 'sinema'),
('"Antoloji film" ne anlama gelir?', '["Devam filmi","Tek öykü","Farklı öykülerden oluşan film","Ön hikâye"]'::jsonb, 2, 'sinema'),
('Sinemada "spin-off" nedir?', '["Fragman","Yeniden çevrim","Ön hikâye","Yan karakter üzerinden türeyen yapım"]'::jsonb, 3, 'sinema'),
('"Reboot" ne demektir?', '["Seriyi baştan başlatmak","Devam ettirmek","Kısaltmak","Belgeselleştirmek"]'::jsonb, 0, 'sinema'),
('Sinemada "franchise" ne anlama gelir?', '["Tek film","Birden çok filme yayılan seri","Festival","Salon"]'::jsonb, 1, 'sinema'),
('Bir filmin "yönetmen kurgusu" versiyonu nedir?', '["Fragman","Stüdyo sürümü","Yönetmenin tercih ettiği sürüm","Kısa versiyon zorunlu"]'::jsonb, 2, 'sinema'),
('Sinemada "kamera arkası" görüntüleri ne gösterir?', '["Afişi","Filmin kendisini","Fragmanı","Yapım sürecini"]'::jsonb, 3, 'sinema'),
('Filmde "sansür" ne anlama gelir?', '["İçeriğin sınırlandırılması","Kurgu tekniği","Ses ayarı","Renk düzeltme"]'::jsonb, 0, 'sinema'),
('Sinema salonunda perdenin işlevi nedir?', '["Ses üretimi","Görüntünün yansıtılması","Işık kaynağı","Havalandırma"]'::jsonb, 1, 'sinema'),
('Projeksiyon cihazı ne yapar?', '["Bilet basar","Ses kaydeder","Görüntüyü perdeye yansıtır","Kurgu yapar"]'::jsonb, 2, 'sinema'),
('Sinemada "surround ses" ne sağlar?', '["Altyazı","Tek kanal ses","Sessizlik","Çevresel ses deneyimi"]'::jsonb, 3, 'sinema'),
('Filmde "ses tasarımı" neyi kapsar?', '["Tüm işitsel öğelerin kurgulanması","Yalnız müziği","Yalnız diyaloğu","Yalnız efekti"]'::jsonb, 0, 'sinema'),
('Sinemada "adaptasyon hakkı" ne demektir?', '["Bilet hakkı","Bir eseri filme çekme izni","Dağıtım payı","Ödül"]'::jsonb, 1, 'sinema'),
('Filmde "telif" neyi korur?', '["Salon düzenini","Bilet fiyatını","Eser sahibinin haklarını","Süreyi"]'::jsonb, 2, 'sinema'),
('Sinemada "ortak yapım" ne anlama gelir?', '["Belgesel","Tek yapımcı","Amatör çekim","Birden çok ülke veya şirketin ortak üretimi"]'::jsonb, 3, 'sinema'),
('Bir filmin "uluslararası versiyonu" neden hazırlanır?', '["Farklı ülkelerde gösterim için","Süreyi uzatmak için","Ödül için","Bilet için"]'::jsonb, 0, 'sinema'),
('Sinemada "film şeridi" hangi malzemeden yapılırdı?', '["Kâğıt","Selüloit esaslı film","Cam","Metal"]'::jsonb, 1, 'sinema'),
('Sinemada "negatif" nedir?', '["Fragman","Gösterim kopyası","Çekimde pozlanan asıl film","Afiş"]'::jsonb, 2, 'sinema'),
('"Kopya" (print) ne anlama gelir?', '["Storyboard","Negatif","Senaryo","Gösterim için çoğaltılan film"]'::jsonb, 3, 'sinema'),
('Sinemada "restorasyon" neyi amaçlar?', '["Eski filmleri yenilemek","Yeni film çekmek","Kurgulamak","Dağıtmak"]'::jsonb, 0, 'sinema'),
('"Sinematek" ne işlev görür?', '["Bilet ofisi","Film arşivi ve gösterim merkezi","Set","Stüdyo"]'::jsonb, 1, 'sinema'),
('Sinemada "kadraj dışı" (off-screen) ne demektir?', '["Yakın plan","Kadraj merkezi","Görüntü dışında kalan alan","Genel plan"]'::jsonb, 2, 'sinema'),
('Filmde "point of view" çekimi neyi gösterir?', '["Jeneriği","Kuş bakışını","Genel planı","Karakterin gözünden görüneni"]'::jsonb, 3, 'sinema'),
('Sinemada "dolly zoom" etkisi neyi yaratır?', '["Mekân algısında tedirgin edici değişim","Renk artışı","Ses yankısı","Yavaşlama"]'::jsonb, 0, 'sinema'),
('"Handheld" çekimin etkisi nedir?', '["Tam sabitlik","Devingen ve gerçekçi his","Yavaşlama","Renk kaybı"]'::jsonb, 1, 'sinema'),
('Sinemada "kurgu ritmi" neyi etkiler?', '["Bütçeyi","Renk paletini","Filmin temposunu","Afişi"]'::jsonb, 2, 'sinema'),
('Aksiyon filmlerinde kurgu genellikle nasıldır?', '["Tek plan","Uzun ve durağan","Sessiz","Hızlı ve kısa planlı"]'::jsonb, 3, 'sinema'),
('Sinemada "sessizlik" nasıl kullanılır?', '["Gerilim ve vurgu aracı olarak","Hata olarak","Süre doldurmak için","Ses hatası olarak"]'::jsonb, 0, 'sinema'),
('Filmde "ön izleme gösterimi" ne için yapılır?', '["Ödül almak","Seyirci tepkisini ölçmek","Bilet satmak","Kurgu bitirmek"]'::jsonb, 1, 'sinema'),
('Sinemada "kapanış planı" ne yapar?', '["Fragman olur","Filmi açar","Filmi görsel olarak sonlandırır","Jenerik olur"]'::jsonb, 2, 'sinema'),
('Bir filmde "tema" ne demektir?', '["Süre","Kamera açısı","Ses formatı","Filmin işlediği temel düşünce"]'::jsonb, 3, 'sinema'),
('Sinemada "sembol" kullanımı neyi sağlar?', '["Anlamı dolaylı aktarmak","Sesi artırmak","Süreyi kısaltmak","Bilet satmak"]'::jsonb, 0, 'sinema'),
('Filmde "ironi" nasıl ortaya çıkar?', '["Yüksek sesle","Beklenen ile olan arasındaki karşıtlıkla","Hızlı kurguyla","Renkle"]'::jsonb, 1, 'sinema'),
('Sinemada "gerilim" nasıl artırılır?', '["Renk azaltarak","Ses kısarak yalnızca","Bilgi ve zamanlamayı yöneterek","Süre uzatarak"]'::jsonb, 2, 'sinema'),
('Filmde "sürpriz" ile "gerilim" farkı nedir?', '["Gerilim sessizdir","Fark yoktur","Sürpriz uzundur","Gerilimde izleyici önceden bilgilidir"]'::jsonb, 3, 'sinema'),
('Sinemada "karakter tanıtımı" genellikle nerede yapılır?', '["Filmin ilk bölümünde","Finalde","Jenerikte","Fragmanda"]'::jsonb, 0, 'sinema'),
('Bir filmde "alt metin" ne demektir?', '["Altyazı","Söylenmeyen ama sezilen anlam","Dipnot","Jenerik yazısı"]'::jsonb, 1, 'sinema'),
('Sinemada "gerçekçilik" anlayışı neyi hedefler?', '["Animasyon","Fantastik dünya","Yaşamı olduğu gibi yansıtmak","Reklam"]'::jsonb, 2, 'sinema'),
('Sinemada "tür karışımı" ne demektir?', '["Kısa film","Tek tür","Belgesel","Birden çok türün bir arada kullanımı"]'::jsonb, 3, 'sinema'),

-- ===================== TEKNOLOJİ (200) =====================
('Bilgisayarda CPU''nun açılımı nedir?', '["Merkezî işlem birimi","Bellek birimi","Görüntü birimi","Depolama birimi"]'::jsonb, 0, 'teknoloji'),
('RAM ne tür bir bellektir?', '["Kalıcı depolama","Geçici (uçucu) bellek","Optik disk","Yedekleme kartı"]'::jsonb, 1, 'teknoloji'),
('Bilgisayar kapatıldığında RAM''deki veriye ne olur?', '["Diske yazılır","Kalıcı olur","Silinir","Şifrelenir"]'::jsonb, 2, 'teknoloji'),
('SSD''nin HDD''ye göre avantajı nedir?', '["Daha yavaş","Daha çok gürültü","Daha çok hareketli parça","Daha hızlı erişim"]'::jsonb, 3, 'teknoloji'),
('GPU öncelikle hangi işlerde kullanılır?', '["Grafik ve paralel hesaplama","Yalnız depolama","Yalnız ağ","Yalnız ses"]'::jsonb, 0, 'teknoloji'),
('Anakartın işlevi nedir?', '["Veri depolamak","Bileşenleri birbirine bağlamak","Görüntü üretmek","Ses çalmak"]'::jsonb, 1, 'teknoloji'),
('BIOS/UEFI ne zaman çalışır?', '["Uyku sırasında","Kapatılırken","Bilgisayar açılırken","Yalnız güncellemede"]'::jsonb, 2, 'teknoloji'),
('İşletim sisteminin temel görevi nedir?', '["Yalnız yazıcı","Yalnız oyun çalıştırmak","Yalnız internet","Donanım ve yazılım arasında yönetim"]'::jsonb, 3, 'teknoloji'),
('Linux nasıl bir yazılımdır?', '["Açık kaynak işletim sistemi çekirdeği","Kapalı kaynak oyun","Donanım","Veri tabanı"]'::jsonb, 0, 'teknoloji'),
('Açık kaynak yazılımın özelliği nedir?', '["Ücretsiz olmak zorunda olması","Kaynak kodunun erişilebilir olması","Kapalı olması","Yalnız sunucuda çalışması"]'::jsonb, 1, 'teknoloji'),
('Bir bit kaç değer alabilir?', '["8","4","2","10"]'::jsonb, 2, 'teknoloji'),
('Bir bayt kaç bittir?', '["2","4","16","8"]'::jsonb, 3, 'teknoloji'),
('Onaltılık (hexadecimal) sistemde taban kaçtır?', '["16","8","10","2"]'::jsonb, 0, 'teknoloji'),
('ASCII neyi kodlar?', '["Renkleri","Karakterleri","Sesleri","Görüntüleri"]'::jsonb, 1, 'teknoloji'),
('Unicode neyi çözmeyi amaçlar?', '["Görüntü sıkıştırma","Ses sıkıştırma","Tüm dillerin karakterlerini tek standartta toplamak","Ağ hızı"]'::jsonb, 2, 'teknoloji'),
('UTF-8 nedir?', '["Bir ağ protokolü","Bir programlama dili","Bir işletim sistemi","Bir karakter kodlama biçimi"]'::jsonb, 3, 'teknoloji'),
('İnternette IP adresi ne işe yarar?', '["Cihazı ağda adreslemek","Şifre üretmek","Dosya sıkıştırmak","Ses iletmek"]'::jsonb, 0, 'teknoloji'),
('DNS ne yapar?', '["Dosya şifreler","Alan adını IP adresine çevirir","Veri sıkıştırır","Ses üretir"]'::jsonb, 1, 'teknoloji'),
('HTTP protokolü ne için kullanılır?', '["Ses kaydı","Dosya şifreleme","Web sayfalarının iletimi","Yazıcı sürücüsü"]'::jsonb, 2, 'teknoloji'),
('HTTPS''in HTTP''den farkı nedir?', '["Yalnız resim iletmesi","Daha yavaş olması yalnızca","Farkı yok","Şifreli iletişim"]'::jsonb, 3, 'teknoloji'),
('SSL/TLS ne sağlar?', '["Güvenli veri iletimi","Veri sıkıştırma","Ekran çözünürlüğü","Ses kalitesi"]'::jsonb, 0, 'teknoloji'),
('VPN''in temel işlevi nedir?', '["Ekranı büyütmek","Şifreli bir ağ tüneli kurmak","Dosya silmek","Yazı yazmak"]'::jsonb, 1, 'teknoloji'),
('Güvenlik duvarı (firewall) ne yapar?', '["Ekran açar","Veri sıkıştırır","Ağ trafiğini filtreler","Yazıcı sürer"]'::jsonb, 2, 'teknoloji'),
('İki faktörlü doğrulama neyi artırır?', '["Ekran parlaklığını","İnternet hızını","Depolama alanını","Hesap güvenliğini"]'::jsonb, 3, 'teknoloji'),
('Güçlü parolanın özelliği nedir?', '["Uzun ve tahmin edilemez olması","Kısa olması","Ad-soyad içermesi","Doğum tarihi olması"]'::jsonb, 0, 'teknoloji'),
('Kimlik avı (phishing) nedir?', '["Veri yedekleme","Sahte mesajla bilgi çalma girişimi","Yazılım güncelleme","Ağ hızlandırma"]'::jsonb, 1, 'teknoloji'),
('Antivirüs yazılımının işlevi nedir?', '["Ses düzenleme","Dosya oluşturma","Zararlı yazılımları tespit ve engelleme","Ağ kurma"]'::jsonb, 2, 'teknoloji'),
('Yazılım yamalarının başlıca faydası nedir?', '["Reklam artışı","Renk değişimi","Simge değişimi","Güvenlik açıklarının kapatılması"]'::jsonb, 3, 'teknoloji'),
('Veri merkezleri ne yapar?', '["Sunucuları barındırır ve işletir","Kâğıt üretir","Elektrik üretir yalnızca","Yazılım satar"]'::jsonb, 0, 'teknoloji'),
('Sunucu (server) ne demektir?', '["Yalnız yazıcı","Hizmet sunan bilgisayar","Yalnız monitör","Yalnız klavye"]'::jsonb, 1, 'teknoloji'),
('İstemci-sunucu mimarisinde istemci ne yapar?', '["Veri saklar yalnızca","Hizmet sunar","Hizmet talep eder","Ağ kurar"]'::jsonb, 2, 'teknoloji'),
('API ne işe yarar?', '["Ses üretir","Ekran boyutunu ayarlar","Dosya siler","Yazılımların birbiriyle konuşmasını sağlar"]'::jsonb, 3, 'teknoloji'),
('Veri tabanı ne için kullanılır?', '["Veriyi düzenli saklamak ve sorgulamak","Görüntü üretmek","Ses çalmak","Yazdırmak"]'::jsonb, 0, 'teknoloji'),
('İlişkisel veri tabanında veriler nasıl tutulur?', '["Yalnız dosyada","Tablolar halinde","Yalnız resimde","Yalnız metinde"]'::jsonb, 1, 'teknoloji'),
('Birincil anahtar (primary key) ne sağlar?', '["Şifrelemeyi","Sıralamayı","Kaydın benzersiz kimliğini","Yedeklemeyi"]'::jsonb, 2, 'teknoloji'),
('İndeks veri tabanında neyi hızlandırır?', '["Yedeklemeyi","Yazmayı her zaman","Silmeyi","Sorgulamayı"]'::jsonb, 3, 'teknoloji'),
('NoSQL veri tabanları hangi durumda tercih edilir?', '["Esnek şema ve ölçeklenebilirlik gerektiğinde","Yalnız küçük veride","Yalnız metin dosyasında","Yalnız yazıcıda"]'::jsonb, 0, 'teknoloji'),
('HTML ne işe yarar?', '["Sunucu yönetir","Web sayfasının yapısını tanımlar","Veri şifreler","Ses üretir"]'::jsonb, 1, 'teknoloji'),
('CSS''in görevi nedir?', '["Ağ kurmak","Veri saklamak","Sayfanın görünümünü biçimlendirmek","Dosya sıkıştırmak"]'::jsonb, 2, 'teknoloji'),
('JavaScript ağırlıklı olarak nerede çalışır?', '["Yalnız kamerada","Yalnız yazıcıda","Yalnız modemde","Tarayıcıda"]'::jsonb, 3, 'teknoloji'),
('Python hangi tür bir dildir?', '["Yorumlanan yüksek seviyeli dil","Makine dili","Donanım tanımlama dili","İşaretleme dili"]'::jsonb, 0, 'teknoloji'),
('Derleyici (compiler) ne yapar?', '["Kodu siler","Kaynak kodu makine koduna çevirir","Kodu şifreler","Kodu yazdırır"]'::jsonb, 1, 'teknoloji'),
('Yorumlayıcı (interpreter) ne yapar?', '["Kodu siler","Tümünü derler","Kodu satır satır çalıştırır","Kodu paketler"]'::jsonb, 2, 'teknoloji'),
('Algoritma nedir?', '["Bir ekran","Bir donanım","Bir kablo","Bir sorunu çözen adım dizisi"]'::jsonb, 3, 'teknoloji'),
('Değişken ne işe yarar?', '["Veriyi bellekte adlandırarak tutmak","Ekran açmak","Ses vermek","Yazdırmak"]'::jsonb, 0, 'teknoloji'),
('Döngü yapısı ne sağlar?', '["Programın kapanmasını","Kod bloğunun tekrarlanmasını","Ekran temizliğini","Ses artışını"]'::jsonb, 1, 'teknoloji'),
('Koşul ifadesi ne yapar?', '["Kodu siler","Her zaman aynı işi yapar","Duruma göre farklı kod çalıştırır","Kodu derler"]'::jsonb, 2, 'teknoloji'),
('Fonksiyon kullanmanın faydası nedir?', '["Hızı düşürmek","Kodu uzatmak","Hata artırmak","Kodu yeniden kullanılabilir yapmak"]'::jsonb, 3, 'teknoloji'),
('Hata ayıklama (debugging) ne demektir?', '["Hataları bulup düzeltmek","Yeni özellik yazmak","Kodu silmek","Kodu şifrelemek"]'::jsonb, 0, 'teknoloji'),
('Sürüm kontrol sistemi ne sağlar?', '["Ekran kaydı","Kod değişikliklerinin izlenmesi","Ses kaydı","Yazıcı yönetimi"]'::jsonb, 1, 'teknoloji'),
('Git ne tür bir araçtır?', '["Veri tabanı","Metin editörü","Dağıtık sürüm kontrol sistemi","İşletim sistemi"]'::jsonb, 2, 'teknoloji'),
('"Commit" ne anlama gelir?', '["Ağ kurmak","Dosya silmek","Programı kapatmak","Değişikliği kayıt altına almak"]'::jsonb, 3, 'teknoloji'),
('Yazılımda "branch" ne işe yarar?', '["Paralel geliştirme dalı açmak","Kod silmek","Test kapatmak","Sunucu kurmak"]'::jsonb, 0, 'teknoloji'),
('Birim testi (unit test) neyi test eder?', '["Tüm sistemi","Küçük kod parçalarının doğruluğunu","Donanımı","Ağı"]'::jsonb, 1, 'teknoloji'),
('Yazılımda "refactoring" ne demektir?', '["Hata eklemek","Yeni özellik eklemek","Davranışı değiştirmeden kodu iyileştirmek","Kodu silmek"]'::jsonb, 2, 'teknoloji'),
('Açık kaynak lisansı neyi belirler?', '["Kodun boyutunu","Kodun hızını","Kodun rengini","Kodun kullanım koşullarını"]'::jsonb, 3, 'teknoloji'),
('Denetimli öğrenmede ne kullanılır?', '["Etiketli veri","Etiketsiz veri","Yalnız ses","Yalnız görüntü"]'::jsonb, 0, 'teknoloji'),
('Denetimsiz öğrenmede amaç nedir?', '["Etiket tahmini","Veride yapı ve kümeler bulmak","Donanım testi","Ağ kurulumu"]'::jsonb, 1, 'teknoloji'),
('Yapay sinir ağı neyden esinlenmiştir?', '["Kemikten","Kas dokusundan","Beyindeki nöron yapısından","Damardan"]'::jsonb, 2, 'teknoloji'),
('Derin öğrenmede "katman" ne ifade eder?', '["Ağ kablosunu","Ekran çözünürlüğünü","Disk bölümünü","Ağın işlem basamağını"]'::jsonb, 3, 'teknoloji'),
('Aşırı öğrenme (overfitting) nedir?', '["Modelin eğitim verisine fazla uyması","Verinin azlığı","Donanım hatası","Ağ gecikmesi"]'::jsonb, 0, 'teknoloji'),
('Eğitim ve test verisini ayırmanın amacı nedir?', '["Veriyi silmek","Modelin genelleme başarısını ölçmek","Hızı artırmak","Diski boşaltmak"]'::jsonb, 1, 'teknoloji'),
('Doğal dil işleme neyle ilgilenir?', '["Ağ yönlendirme","Görüntü sıkıştırma","Metin ve konuşmanın işlenmesi","Disk biçimlendirme"]'::jsonb, 2, 'teknoloji'),
('Bilgisayarlı görü neyi hedefler?', '["Ağ kurmak","Ses üretmek","Metin yazmak","Görüntüden anlam çıkarmak"]'::jsonb, 3, 'teknoloji'),
('Robotikte "sensör" ne yapar?', '["Çevreden veri toplar","Hareket üretir","Enerji üretir","Kod yazar"]'::jsonb, 0, 'teknoloji'),
('Robotikte "aktüatör" ne yapar?', '["Veri toplar","Hareketi üretir","Kod derler","Ağ kurar"]'::jsonb, 1, 'teknoloji'),
('Nesnelerin İnterneti (IoT) nedir?', '["Yalnız bilgisayarlar","Yalnız telefonlar","Cihazların ağa bağlanıp veri paylaşması","Yalnız yazıcılar"]'::jsonb, 2, 'teknoloji'),
('Akıllı ev sistemlerinde amaç nedir?', '["Ses kesmek","Elektrik üretmek","Su üretmek","Cihazları uzaktan yönetmek"]'::jsonb, 3, 'teknoloji'),
('Giyilebilir teknolojiye örnek nedir?', '["Akıllı saat","Masaüstü bilgisayar","Yazıcı","Sunucu"]'::jsonb, 0, 'teknoloji'),
('GPS ne işe yarar?', '["Ses kaydetmek","Konum belirlemek","Görüntü sıkıştırmak","Metin yazmak"]'::jsonb, 1, 'teknoloji'),
('GPS konumu nasıl hesaplanır?', '["Mikrofonla","Kamerayla","Uydulardan gelen sinyallerin zamanıyla","Isı sensörüyle"]'::jsonb, 2, 'teknoloji'),
('Bluetooth hangi mesafe için tasarlanmıştır?', '["Denizaltı kablosu","Kıtalararası","Uydu bağlantısı","Kısa mesafe"]'::jsonb, 3, 'teknoloji'),
('Wi-Fi hangi tür bağlantı sağlar?', '["Kablosuz yerel ağ","Kablolu ağ","Uydu telefonu","Fiber kablo"]'::jsonb, 0, 'teknoloji'),
('NFC teknolojisi ne için kullanılır?', '["Uzun mesafe iletişim","Çok kısa mesafeli veri aktarımı","Uydu bağlantısı","Radyo yayını"]'::jsonb, 1, 'teknoloji'),
('QR kod ne yapar?', '["Görüntü çeker","Ses kaydeder","Bilgiyi iki boyutlu desen olarak taşır","Ağ kurar"]'::jsonb, 2, 'teknoloji'),
('RFID etiketleri ne için kullanılır?', '["Veri şifrelemek","Görüntü işlemek","Ses üretmek","Nesneleri radyo dalgasıyla tanımlamak"]'::jsonb, 3, 'teknoloji'),
('Fiber optik kablo veriyi neyle taşır?', '["Işıkla","Elektrik akımıyla","Sesle","Isıyla"]'::jsonb, 0, 'teknoloji'),
('Fiber optiğin avantajı nedir?', '["Ucuz olması yalnızca","Yüksek hız ve düşük kayıp","Ağır olması","Kısa mesafe"]'::jsonb, 1, 'teknoloji'),
('Modem ne yapar?', '["Ses üretir","Görüntü işler","Sinyalleri dönüştürerek internet bağlantısı sağlar","Yazı yazar"]'::jsonb, 2, 'teknoloji'),
('Router (yönlendirici) ne işe yarar?', '["Ses çalmak","Görüntü büyütmek","Dosya silmek","Ağ trafiğini yönlendirmek"]'::jsonb, 3, 'teknoloji'),
('Bant genişliği neyi ifade eder?', '["Birim zamanda taşınabilen veri miktarını","Kablo uzunluğunu","Ekran boyutunu","Disk boyutunu"]'::jsonb, 0, 'teknoloji'),
('Gecikme (latency) nedir?', '["Veri miktarı","Verinin ulaşma süresi","Ekran parlaklığı","Disk hızı"]'::jsonb, 1, 'teknoloji'),
('Veri sıkıştırmanın amacı nedir?', '["Hızı düşürmek","Kaliteyi artırmak zorunlu","Daha az yer kaplaması","Renk eklemek"]'::jsonb, 2, 'teknoloji'),
('Kayıpsız sıkıştırma ne sağlar?', '["Ses kaybını","Verinin bozulmasını","Renk kaybını","Verinin tam geri elde edilmesini"]'::jsonb, 3, 'teknoloji'),
('JPEG hangi tür sıkıştırma kullanır?', '["Kayıplı","Kayıpsız","Sıkıştırmasız","Şifreli"]'::jsonb, 0, 'teknoloji'),
('PNG formatının özelliği nedir?', '["Yalnız video","Kayıpsız ve saydamlık desteği","Yalnız ses","Yalnız metin"]'::jsonb, 1, 'teknoloji'),
('MP3 hangi veriyi sıkıştırır?', '["Metin","Görüntü","Ses","Program"]'::jsonb, 2, 'teknoloji'),
('PDF formatının amacı nedir?', '["Kod derlemek","Video oynatmak","Ağ kurmak","Belgeyi biçimi bozulmadan taşımak"]'::jsonb, 3, 'teknoloji'),
('Piksel nedir?', '["Görüntünün en küçük birimi","Ses birimi","Ağ birimi","Bellek birimi"]'::jsonb, 0, 'teknoloji'),
('Çözünürlük neyi ifade eder?', '["Ses seviyesini","Görüntüdeki piksel sayısını","Disk hızını","Ağ gecikmesini"]'::jsonb, 1, 'teknoloji'),
('Vektörel görüntünün avantajı nedir?', '["Renk sınırı","Küçük dosya olması zorunlu","Büyütünce bozulmaması","Yalnız siyah-beyaz"]'::jsonb, 2, 'teknoloji'),
('RGB renk modeli neyi temel alır?', '["Ses","Boyaların karışımı","Isı","Kırmızı, yeşil, mavi ışık"]'::jsonb, 3, 'teknoloji'),
('CMYK renk modeli nerede kullanılır?', '["Baskıda","Ekranda","Ses kaydında","Ağ trafiğinde"]'::jsonb, 0, 'teknoloji'),
('3D yazıcı nasıl üretim yapar?', '["Malzeme keserek","Katman katman ekleyerek","Dökerek yalnızca","Presleyerek"]'::jsonb, 1, 'teknoloji'),
('CNC tezgâhı ne yapar?', '["Boyama","Elle kesme","Bilgisayar denetiminde işleme","Kaynak yalnızca"]'::jsonb, 2, 'teknoloji'),
('Sanal gerçeklik (VR) ne sunar?', '["Yalnız metin","Gerçek dünyaya bilgi ekleme","Yalnız ses","Tümüyle dijital ortam deneyimi"]'::jsonb, 3, 'teknoloji'),
('Blokzincir teknolojisinin temel özelliği nedir?', '["Dağıtık ve değiştirilmesi zor kayıt","Merkezî tek kopya","Yalnız yerel dosya","Yalnız yazıcı"]'::jsonb, 0, 'teknoloji'),
('Kriptografide "şifreleme" ne yapar?', '["Veriyi siler","Veriyi okunamaz hale getirir","Veriyi büyütür","Veriyi renklendirir"]'::jsonb, 1, 'teknoloji'),
('Simetrik şifrelemede anahtar durumu nedir?', '["Anahtar yok","Farklı anahtarlar","Aynı anahtar şifreler ve çözer","İki taraf da açık"]'::jsonb, 2, 'teknoloji'),
('Asimetrik şifrelemede kaç anahtar vardır?', '["Anahtar yok","Bir","Üç","İki (açık ve gizli)"]'::jsonb, 3, 'teknoloji'),
('Özet (hash) fonksiyonunun özelliği nedir?', '["Girdiden sabit uzunlukta çıktı üretmesi","Geri çevrilebilir olması","Rastgele değişmesi","Şifre çözmesi"]'::jsonb, 0, 'teknoloji'),
('Dijital imza ne sağlar?', '["Renk düzeltme","Kimlik doğrulama ve bütünlük","Ses kaydı","Ağ hızı"]'::jsonb, 1, 'teknoloji'),
('Sanallaştırma ne demektir?', '["Kabloyu uzatmak","Donanımı çoğaltmak","Bir donanımda birden çok sanal makine çalıştırmak","Ekranı bölmek"]'::jsonb, 2, 'teknoloji'),
('Konteyner teknolojisi ne sağlar?', '["Ekran açmak","Donanım üretmek","Kablo çekmek","Uygulamayı bağımlılıklarıyla paketlemek"]'::jsonb, 3, 'teknoloji'),
('Bulut bilişimde "ölçeklenebilirlik" ne demektir?', '["Kaynakların ihtiyaca göre artırılabilmesi","Sabit kapasite","Donanım azlığı","Ağ kesintisi"]'::jsonb, 0, 'teknoloji'),
('Yük dengeleyici (load balancer) ne yapar?', '["Veriyi siler","Trafiği sunucular arasında dağıtır","Kod derler","Ekran açar"]'::jsonb, 1, 'teknoloji'),
('Önbellek (cache) ne sağlar?', '["Şifreleme","Kalıcı depolama","Sık kullanılan veriye hızlı erişim","Yedekleme"]'::jsonb, 2, 'teknoloji'),
('Çerez (cookie) ne işe yarar?', '["Ağ kurmak","Virüs yaymak","Dosya silmek","Tarayıcıda küçük veri saklamak"]'::jsonb, 3, 'teknoloji'),
('Arama motorlarının temel işlevi nedir?', '["İçerikleri dizinleyip bulmak","Video düzenlemek","Ses çalmak","Kod derlemek"]'::jsonb, 0, 'teknoloji'),
('Web tarayıcısının görevi nedir?', '["Ağ kablosu üretmek","Web içeriğini görüntülemek","Disk biçimlendirmek","Yazıcı sürmek"]'::jsonb, 1, 'teknoloji'),
('E-posta protokollerinden SMTP ne yapar?', '["Dosya sıkıştırır","E-posta okur yalnızca","E-posta gönderimini sağlar","Ses iletir"]'::jsonb, 2, 'teknoloji'),
('Spam e-posta ne demektir?', '["Sistem günlüğü","Şifreli ileti","Resmî yazışma","İstenmeyen toplu ileti"]'::jsonb, 3, 'teknoloji'),
('Dijital ayak izi nedir?', '["İnternette bıraktığımız veri izleri","Ekran görüntüsü","Klavye tuşu","Disk bölümü"]'::jsonb, 0, 'teknoloji'),
('Kişisel verilerin korunmasının amacı nedir?', '["Reklam artırmak","Bireyin mahremiyetini güvence altına almak","Hız artırmak","Depolama azaltmak"]'::jsonb, 1, 'teknoloji'),
('Açık veri ne anlama gelir?', '["Silinmiş veri","Şifreli veri","Herkesin erişip kullanabileceği veri","Bozuk veri"]'::jsonb, 2, 'teknoloji'),
('Büyük veri (big data) neyi ifade eder?', '["Yalnız metin","Küçük tablolar","Tek dosya","Çok büyük ve karmaşık veri kümeleri"]'::jsonb, 3, 'teknoloji'),
('Veri madenciliği ne yapar?', '["Büyük veriden anlamlı örüntüler çıkarır","Veriyi siler","Veriyi şifreler","Veriyi yazdırır"]'::jsonb, 0, 'teknoloji'),
('Veri görselleştirmenin amacı nedir?', '["Veriyi gizlemek","Veriyi anlaşılır biçimde sunmak","Veriyi silmek","Veriyi sıkıştırmak"]'::jsonb, 1, 'teknoloji'),
('Elektrik devresinde direncin birimi nedir?', '["Amper","Volt","Ohm","Watt"]'::jsonb, 2, 'teknoloji'),
('Transistörün temel işlevi nedir?', '["Ses üretmek","Işık üretmek","Isı üretmek","Sinyali anahtarlamak ve yükseltmek"]'::jsonb, 3, 'teknoloji'),
('Entegre devre (çip) nedir?', '["Tek gövdede toplanmış devre elemanları","Tek kablo","Tek ekran","Tek pil"]'::jsonb, 0, 'teknoloji'),
('Yarı iletken malzemeye örnek nedir?', '["Bakır","Silisyum","Altın","Ahşap"]'::jsonb, 1, 'teknoloji'),
('Mikrodenetleyici ne işe yarar?', '["Kablo çekmek","Ekran üretmek","Küçük gömülü sistemleri yönetmek","Yazıcı basmak"]'::jsonb, 2, 'teknoloji'),
('Arduino ne tür bir platformdur?', '["Tarayıcı","İşletim sistemi","Veri tabanı","Açık kaynak mikrodenetleyici kartı"]'::jsonb, 3, 'teknoloji'),
('Raspberry Pi nedir?', '["Küçük tek kart bilgisayar","Yazıcı","Modem","Monitör"]'::jsonb, 0, 'teknoloji'),
('Lityum-iyon pillerin yaygın kullanım nedeni nedir?', '["Düşük kapasite","Yüksek enerji yoğunluğu","Ağırlık","Ucuz üretim yalnızca"]'::jsonb, 1, 'teknoloji'),
('Hızlı şarj teknolojisi neyi artırır?', '["Ekran boyutunu","Pil ömrünü kesin olarak","Şarj gücünü ve hızını","Ses seviyesini"]'::jsonb, 2, 'teknoloji'),
('Elektrikli araçların çevresel avantajı nedir?', '["Daha çok yağ","Daha çok yakıt","Daha çok gürültü","Egzoz salımı olmaması"]'::jsonb, 3, 'teknoloji'),
('Otonom araçlarda kullanılan sensörlerden biri nedir?', '["LIDAR","Klavye","Fare","Yazıcı"]'::jsonb, 0, 'teknoloji'),
('Drone (İHA) ne demektir?', '["Denizaltı","İnsansız hava aracı","Uydu","Tren"]'::jsonb, 1, 'teknoloji'),
('Uydu haberleşmesinin avantajı nedir?', '["Kablo gerektirmesi","Sıfır gecikme","Geniş alanda kapsama","Yalnız şehir içi"]'::jsonb, 2, 'teknoloji'),
('Yapay uydu yörüngede nasıl kalır?', '["Kabloyla","Motorla sürekli","Balonla","Hız ve yer çekimi dengesiyle"]'::jsonb, 3, 'teknoloji'),
('Radar hangi ilkeye dayanır?', '["Radyo dalgalarının yansıması","Işık kırılması","Ses emilimi","Isı yayılımı"]'::jsonb, 0, 'teknoloji'),
('Sonar hangi ortamda kullanılır?', '["Uzayda","Su altında","Vakumda","Çölde yalnızca"]'::jsonb, 1, 'teknoloji'),
('Lazerin özelliği nedir?', '["Isı yokluğu","Dağınık ışık","Tek dalga boylu ve yönlü ışık","Renksizlik"]'::jsonb, 2, 'teknoloji'),
('Barkod okuyucular hangi teknolojiyi kullanır?', '["Ses dalgası","Manyetik alan","Radyoaktivite","Optik okuma"]'::jsonb, 3, 'teknoloji'),
('Dokunmatik ekranların yaygın türü hangisidir?', '["Kapasitif","Manyetik","Optik disk","Termal kâğıt"]'::jsonb, 0, 'teknoloji'),
('OLED ekranın LCD''den farkı nedir?', '["Arka aydınlatma zorunlu","Pikseller kendi ışığını üretir","Renksiz olması","Kalın olması"]'::jsonb, 1, 'teknoloji'),
('Ekranlarda "yenileme hızı" neyi gösterir?', '["Piksel boyutunu","Renk sayısını","Saniyedeki görüntü tazeleme sayısını","Parlaklığı"]'::jsonb, 2, 'teknoloji'),
('Klavyelerde "QWERTY" nedir?', '["Ekran çözünürlüğü","Marka","Bağlantı türü","Tuş düzeni"]'::jsonb, 3, 'teknoloji'),
('USB bağlantısının işlevi nedir?', '["Veri ve güç aktarımı","Yalnız ses","Yalnız görüntü","Yalnız ağ"]'::jsonb, 0, 'teknoloji'),
('Ethernet kablosu ne için kullanılır?', '["Ses kaydı","Kablolu ağ bağlantısı","Görüntü büyütme","Şarj etme"]'::jsonb, 1, 'teknoloji'),
('Yazıcılarda lazer teknolojisinin avantajı nedir?', '["Sessizlik zorunlu","Renk zenginliği zorunlu","Hızlı ve net metin baskısı","Ucuzluk zorunlu"]'::jsonb, 2, 'teknoloji'),
('Tarayıcı (scanner) ne yapar?', '["Belgeyi şifreler","Belgeyi basar","Belgeyi siler","Belgeyi dijital görüntüye çevirir"]'::jsonb, 3, 'teknoloji'),
('OCR teknolojisi ne sağlar?', '["Görüntüdeki yazıyı metne çevirmek","Sesi metne çevirmek","Metni sese çevirmek","Video kesmek"]'::jsonb, 0, 'teknoloji'),
('Konuşma tanıma sistemleri ne yapar?', '["Metni resme çevirir","Sesi metne dönüştürür","Videoyu keser","Ağ kurar"]'::jsonb, 1, 'teknoloji'),
('Biyometrik doğrulamaya örnek nedir?', '["PIN","Parola","Parmak izi","Kart numarası"]'::jsonb, 2, 'teknoloji'),
('Yüz tanıma sistemlerinde temel risk nedir?', '["Ses kaybı","Hız düşüklüğü zorunlu","Renk kaybı","Mahremiyet sorunları"]'::jsonb, 3, 'teknoloji'),
('Siber güvenlikte "sızma testi" nedir?', '["İzinli olarak açıkların denenmesi","İzinsiz saldırı","Veri silme","Yedekleme"]'::jsonb, 0, 'teknoloji'),
('Zararlı yazılım türlerinden "truva atı" ne yapar?', '["Yalnız kopyalanır","Zararsız görünüp zarar verir","Yalnız reklam gösterir","Yalnız yavaşlatır"]'::jsonb, 1, 'teknoloji'),
('Solucan (worm) türü zararlının özelliği nedir?', '["Zararsız olması","Elle kurulması","Kendi kendine yayılması","Yalnız yazıcıyı etkilemesi"]'::jsonb, 2, 'teknoloji'),
('Casus yazılım (spyware) ne yapar?', '["Pil şarj eder","Dosya sıkıştırır","Ağ hızlandırır","Kullanıcı bilgisini gizlice toplar"]'::jsonb, 3, 'teknoloji'),
('Yazılım güvenliğinde "en az yetki" ilkesi nedir?', '["Gerekli olan en düşük yetkiyi vermek","Herkese tam yetki","Yetki vermemek","Rastgele yetki"]'::jsonb, 0, 'teknoloji'),
('İki bilgisayarın veri alışverişi için ortak kurallar bütününe ne denir?', '["Sürücü","Protokol","Uygulama","Çekirdek"]'::jsonb, 1, 'teknoloji'),
('TCP protokolünün özelliği nedir?', '["Şifreleme","Sırasız iletim","Güvenilir ve sıralı iletim","Sıkıştırma"]'::jsonb, 2, 'teknoloji'),
('UDP protokolü hangi durumda tercih edilir?', '["Şifrelemede","Bankacılık kaydında","Dosya bütünlüğünde","Hızın önem taşıdığı yayınlarda"]'::jsonb, 3, 'teknoloji'),
('Port numarası ne işe yarar?', '["Aynı cihazdaki servisleri ayırmak","Cihazı adreslemek","Veri şifrelemek","Kablo seçmek"]'::jsonb, 0, 'teknoloji'),
('MAC adresi neyi tanımlar?', '["Kullanıcıyı","Ağ donanımını","Dosyayı","Uygulamayı"]'::jsonb, 1, 'teknoloji'),
('IPv6''nın IPv4''e göre avantajı nedir?', '["Daha az güvenlik","Daha kısa adres","Çok daha fazla adres alanı","Daha az cihaz"]'::jsonb, 2, 'teknoloji'),
('Alan adı uzantısı ".org" genelde neyi çağrıştırır?', '["Askerî","Ticaret","Devlet","Kâr amacı gütmeyen kuruluş"]'::jsonb, 3, 'teknoloji'),
('Web sitesinde "responsive tasarım" ne demektir?', '["Ekran boyutuna uyum sağlaması","Sabit genişlik","Yalnız masaüstü","Yalnız mobil"]'::jsonb, 0, 'teknoloji'),
('Erişilebilirlik (accessibility) neyi hedefler?', '["Yalnız uzmanları","Herkesin kullanabilmesini","Hız artışını","Renk azaltmayı"]'::jsonb, 1, 'teknoloji'),
('Kullanıcı deneyimi (UX) neyle ilgilenir?', '["Yalnız kodla","Yalnız renklerle","Kullanımın kolaylığı ve akışı","Yalnız donanımla"]'::jsonb, 2, 'teknoloji'),
('Kullanıcı arayüzü (UI) neyi kapsar?', '["Disk bölümünü","Sunucu yapısını","Ağ topolojisini","Görsel ve etkileşim öğelerini"]'::jsonb, 3, 'teknoloji'),
('Mobil uygulamada "push bildirim" nedir?', '["Sunucudan cihaza gönderilen uyarı","Kullanıcı mesajı","Reklam banner","Ekran görüntüsü"]'::jsonb, 0, 'teknoloji'),
('PWA ne anlama gelir?', '["Yalnız mobil oyun","Uygulama gibi çalışan web uygulaması","Yalnız masaüstü program","Bir ağ protokolü"]'::jsonb, 1, 'teknoloji'),
('Çevrimdışı çalışabilen web uygulamaları neyi kullanır?', '["Yalnız veritabanı","Yalnız sunucu","Önbellek ve servis çalışanı","Yalnız e-posta"]'::jsonb, 2, 'teknoloji'),
('Yazılımda "sürüm numarası" ne gösterir?', '["Fiyatı","Kod satır sayısını","Kullanıcı sayısını","Yayınlanan sürümün kimliğini"]'::jsonb, 3, 'teknoloji'),
('Beta sürüm ne demektir?', '["Test aşamasındaki sürüm","Son kararlı sürüm","Silinmiş sürüm","Ücretli sürüm"]'::jsonb, 0, 'teknoloji'),
('Yazılımda "geri uyumluluk" nedir?', '["Yalnız yeniyle çalışma","Eski sürümlerle çalışabilme","Hiç çalışmama","Sadece test"]'::jsonb, 1, 'teknoloji'),
('Dosya uzantısı ne belirtir?', '["Dosyanın sahibini","Dosyanın boyutunu","Dosyanın türünü","Dosyanın tarihini"]'::jsonb, 2, 'teknoloji'),
('Dosya sistemi ne yapar?', '["Ağ kurar","Ekran açar","Ses üretir","Verilerin diskte düzenlenmesini sağlar"]'::jsonb, 3, 'teknoloji'),
('Disk birleştirme (defrag) ne işe yarar?', '["Parçalı dosyaları düzenlemek","Dosya silmek","Şifrelemek","Yedeklemek"]'::jsonb, 0, 'teknoloji'),
('RAID teknolojisi ne sağlar?', '["Ekran çoğaltma","Birden çok diskle performans veya yedeklilik","Ses artırma","Ağ kurma"]'::jsonb, 1, 'teknoloji'),
('Sanal bellek ne işe yarar?', '["Ses artırmak","Ekran büyütmek","Disk alanını bellek gibi kullanmak","Ağ kurmak"]'::jsonb, 2, 'teknoloji'),
('İşletim sisteminde "işlem" (process) nedir?', '["Bir ekran","Bir dosya","Bir kablo","Çalışan bir programın örneği"]'::jsonb, 3, 'teknoloji'),
('Çok çekirdekli işlemcinin avantajı nedir?', '["Aynı anda birden çok iş yürütmek","Daha az bellek","Daha az güç zorunlu","Daha az çekirdek"]'::jsonb, 0, 'teknoloji'),
('Aşırı ısınmaya karşı bilgisayarda ne kullanılır?', '["Ek bellek","Soğutucu ve fan","Ek klavye","Ek ekran"]'::jsonb, 1, 'teknoloji'),
('Kesintisiz güç kaynağı (UPS) ne sağlar?', '["İnternet","Kalıcı elektrik üretimi","Elektrik kesildiğinde geçici besleme","Soğutma"]'::jsonb, 2, 'teknoloji'),
('Elektronik atıkların (e-atık) sorunu nedir?', '["Ucuz olması","Hafif olması","Renksiz olması","Zararlı madde içermesi"]'::jsonb, 3, 'teknoloji'),
('Enerji verimliliği yüksek cihazların faydası nedir?', '["Daha az enerji tüketimi","Daha çok ısı","Daha kısa ömür","Daha çok gürültü"]'::jsonb, 0, 'teknoloji'),
('Dijital okuryazarlık ne demektir?', '["Yalnız yazı yazma","Dijital araçları bilinçli kullanabilme","Yalnız oyun oynama","Yalnız kod yazma"]'::jsonb, 1, 'teknoloji'),
('İnternette bilgi doğrulamanın en sağlıklı yolu nedir?', '["Başlığı okumak","Tek paylaşıma güvenmek","Birden çok güvenilir kaynağa bakmak","Yorumlara bakmak"]'::jsonb, 2, 'teknoloji'),
('Telifsiz (açık lisanslı) görsel ne demektir?', '["Bozuk görsel","Yasak görsel","Şifreli görsel","Belirli koşullarla serbest kullanılabilen görsel"]'::jsonb, 3, 'teknoloji'),
('Yazılımda "dokümantasyon" neden önemlidir?', '["Kullanım ve bakımı kolaylaştırır","Kodu hızlandırır","Dosyayı küçültür","Ağı kurar"]'::jsonb, 0, 'teknoloji'),

-- ===================== MÜZİK (200) =====================
('Müzikte "nota" ne ifade eder?', '["Ritim aleti","Sesin yazıya dökülmüş hali","Şarkı sözü","Sahne"]'::jsonb, 1, 'muzik'),
('Batı müziğinde temel nota sayısı kaçtır?', '["9","5","7","12"]'::jsonb, 2, 'muzik'),
('Do-re-mi dizisinde "mi"den sonra hangi nota gelir?', '["Si","Sol","La","Fa"]'::jsonb, 3, 'muzik'),
('Sol anahtarı hangi çizgi üzerinde başlar?', '["İkinci çizgi","Birinci çizgi","Üçüncü çizgi","Dördüncü çizgi"]'::jsonb, 0, 'muzik'),
('Fa anahtarı genellikle hangi seslerde kullanılır?', '["İnce sesler","Kalın sesler","Yalnız vurmalılarda","Yalnız seste"]'::jsonb, 1, 'muzik'),
('Porte kaç çizgiden oluşur?', '["6","4","5","3"]'::jsonb, 2, 'muzik'),
('Müzikte "ölçü" ne belirler?', '["Sahne düzenini","Şarkının sözünü","Enstrüman sayısını","Vuruşların gruplanmasını"]'::jsonb, 3, 'muzik'),
('4/4''lük ölçüde bir ölçüde kaç vuruş vardır?', '["4","2","3","6"]'::jsonb, 0, 'muzik'),
('3/4''lük ölçü hangi dansla özdeşleşmiştir?', '["Tango","Vals","Marş","Polka"]'::jsonb, 1, 'muzik'),
('Müzikte "tempo" neyi gösterir?', '["Rengi","Yüksekliği","Hızı","Süreyi yalnızca"]'::jsonb, 2, 'muzik'),
('"Allegro" terimi neyi ifade eder?', '["Gürültülü","Yavaş tempo","Sessiz","Hızlı tempo"]'::jsonb, 3, 'muzik'),
('"Adagio" ne anlama gelir?', '["Yavaş tempo","Çok hızlı","Kesik kesik","Gürültülü"]'::jsonb, 0, 'muzik'),
('"Forte" işareti neyi belirtir?', '["Alçak ses","Yüksek ses","Hızlı","Yavaş"]'::jsonb, 1, 'muzik'),
('"Piano" nüans işareti ne demektir?', '["Hızlı","Yüksek ses","Hafif ses","Yavaş"]'::jsonb, 2, 'muzik'),
('"Crescendo" ne anlama gelir?', '["Sabit","Giderek azalan","Aniden duran","Giderek yükselen ses"]'::jsonb, 3, 'muzik'),
('"Diminuendo" ne demektir?', '["Giderek azalan ses","Giderek artan","Ani duruş","Sabit hız"]'::jsonb, 0, 'muzik'),
('"Legato" nasıl çalınır?', '["Kesik kesik","Bağlı ve akıcı","Sessiz","Çok hızlı"]'::jsonb, 1, 'muzik'),
('"Staccato" nasıl çalınır?', '["Yavaş","Bağlı","Kesik kesik","Yüksek"]'::jsonb, 2, 'muzik'),
('Müzikte "armoni" nedir?', '["Söz yazımı","Tek ses","Ritim kalıbı","Seslerin birlikte uyumlu kullanımı"]'::jsonb, 3, 'muzik'),
('"Melodi" ne demektir?', '["Ardışık seslerden oluşan ezgi","Aynı anda çalınan sesler","Vuruş düzeni","Ses şiddeti"]'::jsonb, 0, 'muzik'),
('"Ritim" neyi ifade eder?', '["Ses yüksekliği","Seslerin süre ve vuruş düzeni","Ses rengi","Melodi"]'::jsonb, 1, 'muzik'),
('"Tını" (ses rengi) neyi ayırt ettirir?', '["Tempoyu","Ses yüksekliğini","Farklı çalgıların aynı notasını","Ölçüyü"]'::jsonb, 2, 'muzik'),
('Akort ne demektir?', '["Sahne düzeni","Şarkı sözü","Nota yazımı","Çalgının doğru sese ayarlanması"]'::jsonb, 3, 'muzik'),
('Diyapazon ne için kullanılır?', '["Referans ses vermek","Ritim tutmak","Ses yükseltmek","Nota yazmak"]'::jsonb, 0, 'muzik'),
('Bir oktav kaç sesi kapsar?', '["Üç nota","Aynı notanın bir üst tekrarına kadar","İki nota","On nota"]'::jsonb, 1, 'muzik'),
('Majör diziler genelde nasıl bir duygu verir?', '["Gerilimli","Hüzünlü","Parlak ve neşeli","Nötr"]'::jsonb, 2, 'muzik'),
('Minör diziler genelde nasıl bir duygu verir?', '["Komik","Neşeli","Marş gibi","Hüzünlü"]'::jsonb, 3, 'muzik'),
('Akor nedir?', '["Aynı anda duyulan üç veya daha çok ses","Tek ses","Vuruş","Nüans"]'::jsonb, 0, 'muzik'),
('Üçlü akor kaç sesten oluşur?', '["2","3","4","5"]'::jsonb, 1, 'muzik'),
('Müzikte "es" işareti neyi gösterir?', '["Tempoyu","Ses yüksekliğini","Sessizlik süresini","Tınıyı"]'::jsonb, 2, 'muzik'),
('Bemol işareti sesi ne yapar?', '["Uzatır","Yarım ses inceltir","Susturur","Yarım ses kalınlaştırır"]'::jsonb, 3, 'muzik'),
('Diyez işareti sesi ne yapar?', '["Yarım ses inceltir","Yarım ses kalınlaştırır","Susturur","Kısaltır"]'::jsonb, 0, 'muzik'),
('Bekar (naturel) işareti ne yapar?', '["Sesi uzatır","Diyez ve bemolü iptal eder","Sesi keser","Tempoyu artırır"]'::jsonb, 1, 'muzik'),
('Yaylı çalgılardan biri hangisidir?', '["Trompet","Flüt","Keman","Davul"]'::jsonb, 2, 'muzik'),
('Kemanın telleri kaç tanedir?', '["3","6","5","4"]'::jsonb, 3, 'muzik'),
('Viyola kemana göre nasıldır?', '["Daha büyük ve kalın sesli","Daha küçük","Aynı boyutta","Telsiz"]'::jsonb, 0, 'muzik'),
('Viyolonsel nasıl çalınır?', '["Omuzda","Oturarak, yere dayanarak","Ayakta boyunda","Yatarak"]'::jsonb, 1, 'muzik'),
('Kontrbas hangi ses bölgesindedir?', '["Orta","En ince","En kalın","Değişken değil"]'::jsonb, 2, 'muzik'),
('Arp hangi çalgı ailesindendir?', '["Klavyeli","Nefesli","Vurmalı","Telli"]'::jsonb, 3, 'muzik'),
('Gitar hangi yolla ses üretir?', '["Tellerin titreşimiyle","Hava üflemeyle","Vurmayla yalnızca","Elektrikle yalnızca"]'::jsonb, 0, 'muzik'),
('Klasik gitarın telleri genelde neyden yapılır?', '["Çelik zorunlu","Naylon","İpek zorunlu","Bakır zorunlu"]'::jsonb, 1, 'muzik'),
('Elektro gitarda sesi algılayan parça nedir?', '["Perde","Klavye","Manyetik (pickup)","Askı"]'::jsonb, 2, 'muzik'),
('Bas gitarın işlevi nedir?', '["Nefesli görev","Solo melodi zorunlu","Vurmalı görev","Kalın ses ve ritim temeli"]'::jsonb, 3, 'muzik'),
('Piyano hangi çalgı ailesine girer?', '["Klavyeli-telli vurmalı","Nefesli","Yaylı","Elektronik"]'::jsonb, 0, 'muzik'),
('Piyanoda ses nasıl üretilir?', '["Yay sürtmesiyle","Çekiçlerin tellere vurmasıyla","Üfleyerek","Tel çekerek"]'::jsonb, 1, 'muzik'),
('Piyanoda pedal ne sağlar?', '["Nota yazımı","Tempo","Sesin uzaması ve tını değişimi","Akort"]'::jsonb, 2, 'muzik'),
('Org ve piyanonun temel farkı nedir?', '["Boyut","Tuş sayısı zorunlu","Renk","Ses üretim biçimi"]'::jsonb, 3, 'muzik'),
('Akordeon nasıl çalışır?', '["Körükle hava basarak","Yay sürterek","Tel çekerek","Vurarak"]'::jsonb, 0, 'muzik'),
('Flüt hangi çalgı ailesindendir?', '["Yaylı","Nefesli","Vurmalı","Klavyeli"]'::jsonb, 1, 'muzik'),
('Klarnet hangi malzemeden yapılır (klasik olarak)?', '["Taş","Cam","Ahşap","Kâğıt"]'::jsonb, 2, 'muzik'),
('Obua hangi tür nefesli çalgıdır?', '["Bakır üflemeli","Tek kamışlı","Kamışsız","Çift kamışlı"]'::jsonb, 3, 'muzik'),
('Fagot hangi ses bölgesindedir?', '["Kalın","İnce","Çok ince","Yok"]'::jsonb, 0, 'muzik'),
('Trompet hangi ailedendir?', '["Tahta nefesli","Bakır nefesli","Yaylı","Vurmalı"]'::jsonb, 1, 'muzik'),
('Trombonda ses yüksekliği neyle değişir?', '["Yayla","Perdeyle","Sürgüyle","Telle"]'::jsonb, 2, 'muzik'),
('Korno hangi ailedendir?', '["Klavyeli","Yaylı","Vurmalı","Bakır nefesli"]'::jsonb, 3, 'muzik'),
('Tuba hangi ses bölgesindedir?', '["En kalın bakır nefesli","En ince","Orta","Yok"]'::jsonb, 0, 'muzik'),
('Saksafon hangi ailededir?', '["Bakır nefesli kamışsız","Tahta nefesli (kamışlı)","Yaylı","Vurmalı"]'::jsonb, 1, 'muzik'),
('Davul hangi çalgı ailesindendir?', '["Nefesli","Yaylı","Vurmalı","Klavyeli"]'::jsonb, 2, 'muzik'),
('Timpani neyle akort edilir?', '["Telle","Yayla","Üfleyerek","Pedal veya vidalarla"]'::jsonb, 3, 'muzik'),
('Ksilofon nasıl çalınır?', '["Çubuklara tokmakla vurarak","Üfleyerek","Yay sürterek","Tel çekerek"]'::jsonb, 0, 'muzik'),
('Zil (cymbal) hangi ailededir?', '["Yaylı","Vurmalı","Nefesli","Telli"]'::jsonb, 1, 'muzik'),
('Bateri hangi çalgıların bir araya gelmesidir?', '["Nefeslilerin","Yaylıların","Davul ve zillerin","Klavyelilerin"]'::jsonb, 2, 'muzik'),
('Senfoni orkestrasında en kalabalık grup hangisidir?', '["Klavyeliler","Vurmalılar","Bakır nefesliler","Yaylılar"]'::jsonb, 3, 'muzik'),
('Oda müziği ne demektir?', '["Küçük topluluk için yazılmış müzik","Büyük orkestra","Opera","Bale"]'::jsonb, 0, 'muzik'),
('Yaylı dörtlü hangi çalgılardan oluşur?', '["Dört keman","İki keman, viyola, viyolonsel","Dört viyola","Keman ve piyano"]'::jsonb, 1, 'muzik'),
('Solo ne anlama gelir?', '["Düet","Koro","Tek kişinin icrası","Orkestra"]'::jsonb, 2, 'muzik'),
('Düet kaç kişilik icradır?', '["1","3","4","2"]'::jsonb, 3, 'muzik'),
('Soprano hangi ses bölgesidir?', '["En ince kadın sesi","En kalın erkek sesi","Orta erkek sesi","Kalın kadın sesi"]'::jsonb, 0, 'muzik'),
('Alto ses bölgesi nasıldır?', '["En ince kadın sesi","Kalın kadın sesi","Kalın erkek sesi","İnce erkek sesi"]'::jsonb, 1, 'muzik'),
('Tenor hangi ses bölgesidir?', '["İnce kadın sesi","Kalın erkek sesi","İnce erkek sesi","Kalın kadın sesi"]'::jsonb, 2, 'muzik'),
('Bas ses bölgesi nasıldır?', '["İnce erkek sesi","En ince kadın sesi","Orta kadın sesi","En kalın erkek sesi"]'::jsonb, 3, 'muzik'),
('Operada solo şarkıya ne denir?', '["Arya","Uvertür","Final","Koro"]'::jsonb, 0, 'muzik'),
('Uvertür ne zaman çalınır?', '["Ortasında","Eserin başında","Sonunda","Aralarda"]'::jsonb, 1, 'muzik'),
('Operet ile opera farkı nedir?', '["Operet daha uzundur","Fark yoktur","Operette konuşmalı bölümler ve hafif konu","Opera dansızdır"]'::jsonb, 2, 'muzik'),
('Müzikalin özelliği nedir?', '["Yalnız oyun","Yalnız şarkı","Yalnız dans","Şarkı, dans ve oyunun birleşimi"]'::jsonb, 3, 'muzik'),
('Bale müziği ne için bestelenir?', '["Dans gösterisi için","Koro için","Radyo için","Marş için"]'::jsonb, 0, 'muzik'),
('Senfoni ne demektir?', '["Tek çalgı eseri","Orkestra için çok bölümlü eser","Şarkı","Dans"]'::jsonb, 1, 'muzik'),
('Sonat genellikle hangi topluluk içindir?', '["Koro","Büyük orkestra","Bir veya iki çalgı","Bando"]'::jsonb, 2, 'muzik'),
('Fügün temel özelliği nedir?', '["Sözlü olması","Tek sesli olması","Ritimsiz olması","Bir temanın seslerde taklitle işlenmesi"]'::jsonb, 3, 'muzik'),
('Barok dönem bestecilerinden biri kimdir?', '["Johann Sebastian Bach","Beethoven","Chopin","Debussy"]'::jsonb, 0, 'muzik'),
('Vivaldi''nin ünlü eseri hangisidir?', '["Kuğu Gölü","Dört Mevsim","Fındıkkıran","Bolero"]'::jsonb, 1, 'muzik'),
('Klasik dönem bestecilerinden biri kimdir?', '["Wagner","Bach","Mozart","Stravinski"]'::jsonb, 2, 'muzik'),
('Beethoven''ın 9. Senfonisi''nde yer alan ünlü bölüm hangisidir?', '["Requiem","Ay Işığı","Dört Mevsim","Neşeye Övgü"]'::jsonb, 3, 'muzik'),
('Beethoven hayatının ilerleyen döneminde hangi güçlüğü yaşamıştır?', '["İşitme kaybı","Görme kaybı","Konuşma kaybı","Hareket kaybı"]'::jsonb, 0, 'muzik'),
('Romantik dönem bestecilerinden biri kimdir?', '["Bach","Chopin","Vivaldi","Handel"]'::jsonb, 1, 'muzik'),
('Chopin ağırlıklı olarak hangi çalgı için bestelemiştir?', '["Flüt","Keman","Piyano","Trompet"]'::jsonb, 2, 'muzik'),
('Çaykovski''nin bale eserlerinden biri hangisidir?', '["Bolero","Carmen","Aida","Kuğu Gölü"]'::jsonb, 3, 'muzik'),
('"Bolero" eserinin bestecisi kimdir?', '["Maurice Ravel","Claude Debussy","Erik Satie","Gabriel Faure"]'::jsonb, 0, 'muzik'),
('Debussy hangi müzik akımıyla anılır?', '["Barok","Empresyonizm","Klasik","Rönesans"]'::jsonb, 1, 'muzik'),
('Wagner hangi türde eser vermiştir?', '["Marş yalnızca","Bale yalnızca","Opera","Caz"]'::jsonb, 2, 'muzik'),
('Verdi hangi ülkenin bestecisidir?', '["Rusya","Almanya","Fransa","İtalya"]'::jsonb, 3, 'muzik'),
('Stravinski''nin ünlü bale müziği hangisidir?', '["Bahar Ayini","Kuğu Gölü","Fındıkkıran","Giselle"]'::jsonb, 0, 'muzik'),
('Cazın en belirgin özelliği nedir?', '["Katı nota bağlılığı","Doğaçlama","Sözsüzlük zorunlu","Tek çalgı"]'::jsonb, 1, 'muzik'),
('Blues müziğinin kökeni nereye dayanır?', '["Uzak Doğu","İskandinav halk müziği","Afrikalı Amerikalıların müzik geleneği","Alp bölgesi"]'::jsonb, 2, 'muzik'),
('Samba hangi ülkenin müziğidir?', '["Şili","Küba","Portekiz","Brezilya"]'::jsonb, 3, 'muzik'),
('Flamenko hangi ülkeyle anılır?', '["İspanya","İtalya","Yunanistan","Fas"]'::jsonb, 0, 'muzik'),
('Hip hop kültüründe müzikle birlikte anılan öğe nedir?', '["Bale","Rap ve DJ''lik","Opera","Marş"]'::jsonb, 1, 'muzik'),
('Elektronik müzikte "synthesizer" ne yapar?', '["Sesi keser","Sesi kaydeder yalnızca","Sesi elektronik olarak üretir","Notayı yazar"]'::jsonb, 2, 'muzik'),
('Sampler cihazı ne işe yarar?', '["Ölçü tutmak","Nota yazmak","Akort etmek","Kaydedilmiş sesleri çalmak ve işlemek"]'::jsonb, 3, 'muzik'),
('MIDI nedir?', '["Çalgı ve cihazlar arası veri iletişim standardı","Ses dosyası formatı","Hoparlör türü","Mikrofon türü"]'::jsonb, 0, 'muzik'),
('Stüdyoda "mixing" ne yapar?', '["Şarkı yazar","Kanalları dengeleyip birleştirir","Nota basar","Sahne kurar"]'::jsonb, 1, 'muzik'),
('"Mastering" hangi aşamadır?', '["Prova","İlk kayıt","Son ses düzenleme aşaması","Konser"]'::jsonb, 2, 'muzik'),
('Mikrofonun görevi nedir?', '["Akort etmek","Sesi büyütmek yalnızca","Nota yazmak","Sesi elektrik sinyaline çevirmek"]'::jsonb, 3, 'muzik'),
('Hoparlör ne yapar?', '["Elektrik sinyalini sese çevirir","Sesi kaydeder","Nota yazar","Ölçü tutar"]'::jsonb, 0, 'muzik'),
('Ses yalıtımı stüdyoda neden önemlidir?', '["Isıtmak","İstenmeyen sesleri engellemek","Aydınlatmak","Süslemek"]'::jsonb, 1, 'muzik'),
('Türk müziğinde ritim kalıplarına ne denir?', '["Perde","Makam","Usul","Taksim"]'::jsonb, 2, 'muzik'),
('"Taksim" ne demektir?', '["Koro bölümü","Sözlü eser","Ritim kalıbı","Doğaçlama çalgı icrası"]'::jsonb, 3, 'muzik'),
('Türk müziğinde "koma" nedir?', '["Sesler arası küçük aralık","Ölçü","Usul","Form"]'::jsonb, 0, 'muzik'),
('Ud hangi çalgı ailesindendir?', '["Nefesli","Telli (mızraplı)","Vurmalı","Yaylı"]'::jsonb, 1, 'muzik'),
('Bağlama nasıl çalınır?', '["Üfleyerek","Yayla","Tezene veya parmakla","Tokmakla"]'::jsonb, 2, 'muzik'),
('Kanun çalgısı nasıl seslendirilir?', '["Tokmakla","Yayla","Üfleyerek","Parmaklara takılan mızraplarla"]'::jsonb, 3, 'muzik'),
('Ney hangi çalgı ailesindendir?', '["Nefesli","Telli","Vurmalı","Klavyeli"]'::jsonb, 0, 'muzik'),
('Kemençe nasıl çalınır?', '["Mızrapla","Yay ile","Üfleyerek","Vurarak"]'::jsonb, 1, 'muzik'),
('Kaval hangi ailedendir?', '["Telli","Yaylı","Nefesli","Vurmalı"]'::jsonb, 2, 'muzik'),
('Darbuka hangi ailedendir?', '["Yaylı","Telli","Nefesli","Vurmalı"]'::jsonb, 3, 'muzik'),
('Def çalgısı nasıl çalınır?', '["Elle vurarak","Yayla","Üfleyerek","Tezeneyle"]'::jsonb, 0, 'muzik'),
('Tulum hangi bölgede yaygındır?', '["Ege","Doğu Karadeniz","Akdeniz","İç Anadolu"]'::jsonb, 1, 'muzik'),
('Sipsi hangi bölgede yaygın bir çalgıdır?', '["Trakya","Doğu Karadeniz","Batı Akdeniz","Doğu Anadolu"]'::jsonb, 2, 'muzik'),
('"Kırık hava" ne demektir?', '["Marş","Serbest ritimli","Sözsüz eser","Ölçülü ritimli halk ezgisi"]'::jsonb, 3, 'muzik'),
('Türkü sözlerini derleyen kişiye ne denir?', '["Derlemeci","Besteci","Şef","Solist"]'::jsonb, 0, 'muzik'),
('Âşık müziğinde ana çalgı hangisidir?', '["Ud","Saz (bağlama)","Kanun","Ney"]'::jsonb, 1, 'muzik'),
('Mehter müziği hangi topluluğa aittir?', '["Kilise korosu","Saray orkestrası","Osmanlı askerî bandosu","Halk korosu"]'::jsonb, 2, 'muzik'),
('Mehterde kullanılan çalgılardan biri hangisidir?', '["Klavsen","Piyano","Arp","Kös"]'::jsonb, 3, 'muzik'),
('Türk Sanat Müziği''nde "fasıl" nedir?', '["Belirli sırayla icra edilen eserler bütünü","Tek eser","Doğaçlama","Ritim kalıbı"]'::jsonb, 0, 'muzik'),
('Dede Efendi hangi müzik geleneğinin bestecisidir?', '["Batı klasik müziği","Türk müziği","Caz","Rock"]'::jsonb, 1, 'muzik'),
('Türkiye''de çok sesli müziğin öncü bestecilerinden biri kimdir?', '["Dede Efendi","Itri","Ahmet Adnan Saygun","Hacı Arif Bey"]'::jsonb, 2, 'muzik'),
('"Türk Beşleri" hangi alanda anılır?', '["Caz grubu","Halk ozanları","Opera sanatçıları","Çoksesli Türk müziği bestecileri"]'::jsonb, 3, 'muzik'),
('Bir şarkıda "nakarat" nedir?', '["Tekrarlanan bölüm","Giriş","Final","Ara müzik"]'::jsonb, 0, 'muzik'),
('Şarkıda "köprü" (bridge) ne işe yarar?', '["Şarkıyı bitirmek","Bölümler arasında değişiklik sağlamak","Nakaratı tekrarlamak","Girişi uzatmak"]'::jsonb, 1, 'muzik'),
('Şarkı sözü yazarına ne denir?', '["Aranjör","Besteci","Söz yazarı","Şef"]'::jsonb, 2, 'muzik'),
('Aranjörün görevi nedir?', '["Bilet satmak","Söz yazmak","Sahne kurmak","Eseri düzenlemek"]'::jsonb, 3, 'muzik'),
('Bestecinin görevi nedir?', '["Müziği yaratmak","Sahneyi kurmak","Işık vermek","Bilet satmak"]'::jsonb, 0, 'muzik'),
('Bir albümde "single" ne demektir?', '["Tüm albüm","Tek olarak yayımlanan parça","Konser kaydı","Klip"]'::jsonb, 1, 'muzik'),
('Müzikte "cover" ne anlama gelir?', '["Klip çekmek","Yeni beste","Başka sanatçının eserini yeniden yorumlamak","Konser vermek"]'::jsonb, 2, 'muzik'),
('"Remix" ne demektir?', '["Akort","Yeni söz yazma","Canlı kayıt","Var olan parçanın yeniden düzenlenmesi"]'::jsonb, 3, 'muzik'),
('Canlı performansta "sound check" nedir?', '["Konser öncesi ses denemesi","Bilet kontrolü","Işık provası yalnızca","Sahne temizliği"]'::jsonb, 0, 'muzik'),
('Konserde "encore" ne anlama gelir?', '["Ara","Seyirci isteğiyle ek performans","Kapanış anonsu","Bilet iadesi"]'::jsonb, 1, 'muzik'),
('Nota yazımında "anahtar" ne belirler?', '["Nüansı","Tempoyu","Notaların ses yüksekliğini","Süreyi"]'::jsonb, 2, 'muzik'),
('Müzikte "transpoze" ne demektir?', '["Çalgıyı değiştirmek","Tempoyu değiştirmek","Sözü değiştirmek","Eseri başka tona aktarmak"]'::jsonb, 3, 'muzik'),
('"Tonalite" ne ifade eder?', '["Eserin ton merkezini","Ses şiddetini","Süreyi","Ritmi"]'::jsonb, 0, 'muzik'),
('Atonal müzik neyi terk eder?', '["Ritmi","Belirli bir ton merkezini","Melodiyi","Çalgıyı"]'::jsonb, 1, 'muzik'),
('Polifoni ne demektir?', '["Ritim kalıbı","Tek ses","Birden çok bağımsız ezginin birlikteliği","Sözsüzlük"]'::jsonb, 2, 'muzik'),
('Monofoni ne anlama gelir?', '["Nüans","Çok sesli doku","Ritim","Tek ezgi çizgisi"]'::jsonb, 3, 'muzik'),
('Homofoni nasıl bir dokudur?', '["Bir ezgi ve ona eşlik eden akorlar","Bağımsız çok ezgi","Tek ses","Ritimsiz"]'::jsonb, 0, 'muzik'),
('Kanon formu neye dayanır?', '["Ritim değişimine","Aynı ezginin gecikmeli tekrarına","Sözsüzlüğe","Doğaçlamaya"]'::jsonb, 1, 'muzik'),
('Rondo formunun özelliği nedir?', '["Tema yokluğu","Tek bölüm","Ana temanın tekrar tekrar dönmesi","Serbest ritim"]'::jsonb, 2, 'muzik'),
('Varyasyon formunda ne yapılır?', '["Söz eklenir","Tema hiç duyulmaz","Ritim sabit kalır","Tema çeşitlenerek işlenir"]'::jsonb, 3, 'muzik'),
('Müzikte "motif" nedir?', '["En küçük anlamlı ezgi birimi","Tüm eser","Bir ölçü sessizlik","Nüans"]'::jsonb, 0, 'muzik'),
('Müzikte "cümle" (fraz) ne demektir?', '["Tek nota","Anlamlı ezgi bölümü","Es","Anahtar"]'::jsonb, 1, 'muzik'),
('Müzik terapisi neyi amaçlar?', '["Albüm satmak","Konser vermek","Müzikle iyileşmeye destek olmak","Nota öğretmek"]'::jsonb, 2, 'muzik'),
('Erken yaşta müzik eğitiminin faydalarından biri nedir?', '["Kas kütlesi","Boy uzaması","Görme keskinliği","İşitsel ve bilişsel gelişime katkı"]'::jsonb, 3, 'muzik'),
('Solfej ne demektir?', '["Notaları okuyarak seslendirme","Çalgı akordu","Ritim yazımı","Beste yapma"]'::jsonb, 0, 'muzik'),
('Dikte çalışması müzikte neyi geliştirir?', '["Parmak gücünü","İşitme ve nota yazma becerisini","Nefesi","Duruşu"]'::jsonb, 1, 'muzik'),
('Mutlak kulak ne demektir?', '["Hızlı çalma","Yüksek sesle söyleme","Bir sesi referanssız tanıyabilme","Nota yazma"]'::jsonb, 2, 'muzik'),
('Koroda "a capella" ne anlama gelir?', '["Kayıtla","Orkestrayla","Solo","Çalgısız söyleme"]'::jsonb, 3, 'muzik'),
('Vokalde "vibrato" nedir?', '["Sesin hafif dalgalanması","Sesin kesilmesi","Sesin susması","Sesin hızlanması"]'::jsonb, 0, 'muzik'),
('Şan eğitiminde diyafram neden önemlidir?', '["Ses rengini değiştirir yalnızca","Nefes desteği sağlar","Nota okur","Tempo tutar"]'::jsonb, 1, 'muzik'),
('Sesin sağlıklı kullanımı için ne önerilir?', '["Uykusuzluk","Bağırarak çalışma","Isınma ve yeterli su","Soğuk hava"]'::jsonb, 2, 'muzik'),
('Müzikte "prova" ne demektir?', '["Albüm","Konser","Kayıt","Performans öncesi çalışma"]'::jsonb, 3, 'muzik'),
('Orkestrada konzertmeister kimdir?', '["Birinci kemanların başı","Şef","Solist zorunlu","Vurmalı sorumlusu"]'::jsonb, 0, 'muzik'),
('Bir eserde "partisyon" nedir?', '["Tek çalgı notası","Tüm partilerin bir arada yazıldığı nota","Şarkı sözü","Afiş"]'::jsonb, 1, 'muzik'),
('Çalgı "parti"si ne demektir?', '["Sahne düzeni","Tüm eser","Bir çalgının çalacağı bölüm","Konser programı"]'::jsonb, 2, 'muzik'),
('Müzikte "tutti" ne anlama gelir?', '["Yavaşlama","Solo","Sessizlik","Tüm topluluğun birlikte çalması"]'::jsonb, 3, 'muzik'),
('"Da capo" işareti ne der?', '["Baştan tekrar et","Sonda bitir","Yavaşla","Hızlan"]'::jsonb, 0, 'muzik'),
('"Fine" işareti neyi belirtir?', '["Başlangıcı","Bitiş yerini","Tekrarı","Nüansı"]'::jsonb, 1, 'muzik'),
('Tekrar işaretleri ne sağlar?', '["Tempo artışını","Bölümün atlanmasını","Bölümün yeniden çalınmasını","Ses azalmasını"]'::jsonb, 2, 'muzik'),
('"Fermata" işareti ne yapar?', '["Nüansı düşürür","Sesi keser","Tempoyu artırır","Sesi belirsiz süre uzatır"]'::jsonb, 3, 'muzik'),
('Müzikte "senkop" nedir?', '["Vurgunun beklenmedik yere kayması","Tempo artışı","Ses azalması","Sessizlik"]'::jsonb, 0, 'muzik'),
('"Arpej" ne demektir?', '["Akorun aynı anda çalınması","Akor seslerinin sırayla çalınması","Sessizlik","Tempo"]'::jsonb, 1, 'muzik'),
('"Glissando" ne anlama gelir?', '["Sessizlik","Kesik çalma","Sesler arası kaydırarak geçiş","Tekrar"]'::jsonb, 2, 'muzik'),
('"Tremolo" nedir?', '["Sesin susması","Sesin kesilmesi","Sesin uzaması","Sesin hızlı tekrarı"]'::jsonb, 3, 'muzik'),
('"Pizzicato" nasıl uygulanır?', '["Teli parmakla çekerek","Yayla sürterek","Üfleyerek","Vurarak"]'::jsonb, 0, 'muzik'),
('Yaylı çalgılarda yay neyle sürtünme sağlar?', '["Yağ","Reçine","Su","Toz şeker"]'::jsonb, 1, 'muzik'),
('Nefesli çalgılarda "kamış" ne işe yarar?', '["Sesi kesmek","Havayı ısıtmak","Titreşerek ses üretmek","Akort etmek"]'::jsonb, 2, 'muzik'),
('Bir çalgının "perde"si ne işe yarar?', '["Akort yapmak","Ses yükseltmek","Ritim tutmak","Farklı sesleri belirlemek"]'::jsonb, 3, 'muzik'),
('Müzikte "ses yüksekliği" neye bağlıdır?', '["Titreşim frekansına","Ses şiddetine","Tınıya","Süreye"]'::jsonb, 0, 'muzik'),
('Müzikte "ses şiddeti" neyi belirler?', '["Sesin inceliğini","Sesin gürlüğünü","Sesin rengini","Sesin süresini"]'::jsonb, 1, 'muzik'),
('Konser salonlarında akustik neden önemlidir?', '["Aydınlatma için","Isıtma için","Sesin dengeli yayılması için","Bilet için"]'::jsonb, 2, 'muzik'),
('Yankı (eko) neden oluşur?', '["Isıyla","Sesin emilmesiyle","Işıkla","Sesin yüzeylerden yansımasıyla"]'::jsonb, 3, 'muzik'),

-- ===== EK BLOK =====
('Bilgisayarda "önyükleme" (boot) ne demektir?', '["Sistemin başlatılma süreci","Kapatma","Uyku modu","Biçimlendirme"]'::jsonb, 0, 'teknoloji'),
('Sürücü (driver) yazılımı ne yapar?', '["Dosya siler","Donanımın işletim sistemiyle çalışmasını sağlar","Ağ kurar","Video kurgular"]'::jsonb, 1, 'teknoloji'),
('Klavye kısayolu kullanmanın faydası nedir?', '["Ekran büyütmek","Bellek artırmak","İşlemleri hızlandırmak","Disk temizlemek"]'::jsonb, 2, 'teknoloji'),
('Bir dosyanın "salt okunur" olması ne demektir?', '["Şifreli olması","Silinemez olması zorunlu","Gizli olması","Değiştirilemez olması"]'::jsonb, 3, 'teknoloji'),
('"Bulut yedekleme" hangi riski azaltır?', '["Yerel cihaz arızasında veri kaybını","İnternet kesintisini","Elektrik kesintisini","Ekran kırılmasını"]'::jsonb, 0, 'teknoloji'),
('Bir web adresindeki "https" ne gösterir?', '["Sitenin hızlı olduğunu","Bağlantının şifreli olduğunu","Sitenin ücretsiz olduğunu","Sitenin yeni olduğunu"]'::jsonb, 1, 'teknoloji'),
('Tarayıcıda "gizli sekme" ne yapar?', '["IP''yi gizler","Tamamen anonim yapar","Geçmişi yerel olarak tutmaz","Virüsü engeller"]'::jsonb, 2, 'teknoloji'),
('Bir uygulamanın "izinleri" neyi belirler?', '["Rengini","Fiyatını","Boyutunu","Hangi verilere erişebileceğini"]'::jsonb, 3, 'teknoloji'),
('Mobil cihazlarda "uçak modu" ne yapar?', '["Kablosuz bağlantıları kapatır","Pili şarj eder","Ekranı kapatır","Sesi artırır"]'::jsonb, 0, 'teknoloji'),
('"Sıcak nokta" (hotspot) özelliği ne sağlar?', '["Isıtmayı","Cihazın internetini paylaşmayı","Şarj etmeyi","Yedeklemeyi"]'::jsonb, 1, 'teknoloji'),
('Bilgisayarda "görev yöneticisi" ne gösterir?', '["Ağ şifresini","Dosya listesini","Çalışan işlemleri ve kaynak kullanımını","Ekran çözünürlüğünü"]'::jsonb, 2, 'teknoloji'),
('Bir programın "kaynak tüketimi" neyi ifade eder?', '["Rengini","Fiyatını","Boyutunu yalnızca","İşlemci ve bellek kullanımını"]'::jsonb, 3, 'teknoloji'),
('Yazılımda "açık" (bug) ne demektir?', '["İstenmeyen davranışa yol açan hata","Yeni özellik","Belge","Test"]'::jsonb, 0, 'teknoloji'),
('"Yama" (patch) ne işe yarar?', '["Yeni ürün satmak","Bilinen hataları gidermek","Diski silmek","Ağ kurmak"]'::jsonb, 1, 'teknoloji'),
('Yazılımda "bağımlılık" ne demektir?', '["Dosya boyutu","Kod satırı sayısı","Kullanılan dış kütüphaneler","Kullanıcı sayısı"]'::jsonb, 2, 'teknoloji'),

('Müzikte "prelüd" ne anlama gelir?', '["Tekrar","Final","Ara verme","Giriş niteliğinde parça"]'::jsonb, 3, 'muzik'),
('"Etüt" müzikte ne amaçla yazılır?', '["Teknik çalışma için","Konser finali için","Dans için","Marş için"]'::jsonb, 0, 'muzik'),
('"Nocturne" (noktürn) ne çağrıştırır?', '["Marş","Gece esintili lirik parça","Dans havası","Askerî müzik"]'::jsonb, 1, 'muzik'),
('"Serenat" geleneksel olarak ne zaman söylenirdi?', '["Öğlen","Sabah","Akşam ve gece","Şafakta"]'::jsonb, 2, 'muzik'),
('"Requiem" hangi amaçla bestelenir?', '["Dans için","Düğün için","Zafer için","Anma ve ağıt için"]'::jsonb, 3, 'muzik'),
('Marş müziğinin belirgin özelliği nedir?', '["Düzenli ve yürüyüşe uygun ritim","Serbest ritim","Çok yavaş tempo","Sözsüzlük"]'::jsonb, 0, 'muzik'),
('Ninni müziğinin özelliği nedir?', '["Hızlı ve gürültülü","Yumuşak ve sakinleştirici","Marş temposunda","Sert vurgulu"]'::jsonb, 1, 'muzik'),
('"Kantat" hangi türdendir?', '["Yalnız dans","Yalnız çalgısal","Sesli ve çalgılı bölümlü eser","Yalnız solo"]'::jsonb, 2, 'muzik'),
('"Oratoryo" ne demektir?', '["Marş","Bale","Operet","Sahnesiz büyük vokal-orkestra eseri"]'::jsonb, 3, 'muzik'),
('"Lied" ne anlama gelir?', '["Piyano eşlikli sanat şarkısı","Orkestra eseri","Bale müziği","Askerî marş"]'::jsonb, 0, 'muzik'),
('Rönesans müziğinde çok seslilik nasıl gelişmiştir?', '["Tek sesle","Bağımsız ezgilerin birlikte kullanımıyla","Ritimsizlikle","Elektronikle"]'::jsonb, 1, 'muzik'),
('Gregoryen ilahilerin özelliği nedir?', '["Elektronik","Çok sesli","Tek sesli dinî ezgi","Danslı"]'::jsonb, 2, 'muzik'),
('Barok dönemde yaygın klavyeli çalgı hangisidir?', '["Akordeon","Elektro org","Sentezleyici","Klavsen"]'::jsonb, 3, 'muzik'),
('Klavsende ses nasıl üretilir?', '["Teller çekilerek (mızraplanarak)","Çekiçle vurularak","Yayla","Üflenerek"]'::jsonb, 0, 'muzik'),
('Handel hangi dönemin bestecisidir?', '["Romantik","Barok","Çağdaş","Rönesans"]'::jsonb, 1, 'muzik'),
('Haydn hangi türün gelişiminde önemlidir?', '["Rock","Caz","Senfoni","Reggae"]'::jsonb, 2, 'muzik'),
('Schubert hangi türde çok sayıda eser vermiştir?', '["Caz","Bale","Marş","Lied (sanat şarkısı)"]'::jsonb, 3, 'muzik'),
('Brahms hangi dönemin bestecisidir?', '["Romantik","Barok","Rönesans","Çağdaş elektronik"]'::jsonb, 0, 'muzik'),
('Liszt hangi çalgının ustası olarak bilinir?', '["Keman","Piyano","Flüt","Trompet"]'::jsonb, 1, 'muzik'),
('Paganini hangi çalgıyla anılır?', '["Arp","Piyano","Keman","Klarnet"]'::jsonb, 2, 'muzik'),
('Rimski-Korsakov hangi ülkenin bestecisidir?', '["İspanya","İtalya","Fransa","Rusya"]'::jsonb, 3, 'muzik')

on conflict (soru) do nothing;

-- ===================== KARIŞTIRMA =====================
-- Doğru cevap hep aynı şıkta olmasın: SADECE bu partide eklenen soruların
-- şıkları karıştırılır. `created_at >= transaction_timestamp()` koşulu
-- ZORUNLUDUR; onsuz tüm havuzun şıkları karışır ve o an oynanan maçlarda
-- şık indeksleri kayar.
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
