-- Soru havuzu genişletme — Parti 2: Bilim
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Suyun kimyasal formülü nedir?', '["H2O","CO2","O2","H2O2"]'::jsonb, 0, 'bilim'),
('Işık hızı yaklaşık saniyede kaç kilometredir?', '["300.000 km","150.000 km","1.000.000 km","30.000 km"]'::jsonb, 0, 'bilim'),
('Güneş sistemindeki en büyük gezegen hangisidir?', '["Jüpiter","Satürn","Neptün","Dünya"]'::jsonb, 0, 'bilim'),
('Güneş''e en yakın gezegen hangisidir?', '["Merkür","Venüs","Dünya","Mars"]'::jsonb, 0, 'bilim'),
('Kızıl Gezegen olarak bilinen gezegen hangisidir?', '["Mars","Venüs","Jüpiter","Merkür"]'::jsonb, 0, 'bilim'),
('Halkalarıyla ünlü gezegen hangisidir?', '["Satürn","Jüpiter","Uranüs","Neptün"]'::jsonb, 0, 'bilim'),
('Dünya''nın uydusu hangisidir?', '["Ay","Titan","Europa","Fobos"]'::jsonb, 0, 'bilim'),
('Dünya Güneş''in etrafındaki turunu yaklaşık kaç günde tamamlar?', '["365 gün","360 gün","350 gün","400 gün"]'::jsonb, 0, 'bilim'),
('İnsan vücudundaki en büyük organ hangisidir?', '["Deri","Karaciğer","Akciğer","Beyin"]'::jsonb, 0, 'bilim'),
('İnsan vücudundaki en büyük iç organ hangisidir?', '["Karaciğer","Kalp","Akciğer","Mide"]'::jsonb, 0, 'bilim'),
('Yetişkin bir insanda kaç kemik bulunur?', '["206","208","212","186"]'::jsonb, 0, 'bilim'),
('Kanı vücuda pompalayan organ hangisidir?', '["Kalp","Akciğer","Karaciğer","Böbrek"]'::jsonb, 0, 'bilim'),
('İnsanda kanı temizleyen organ hangisidir?', '["Böbrek","Mide","Kalp","Dalak"]'::jsonb, 0, 'bilim'),
('Vücudumuzda oksijeni taşıyan kan hücresi hangisidir?', '["Alyuvar","Akyuvar","Trombosit","Plazma"]'::jsonb, 0, 'bilim'),
('İnsanın kalıtım materyali hangisidir?', '["DNA","RNA","Protein","Enzim"]'::jsonb, 0, 'bilim'),
('Fotosentez yapan canlılar hangi gazı üretir?', '["Oksijen","Karbondioksit","Azot","Hidrojen"]'::jsonb, 0, 'bilim'),
('Bitkiler fotosentez için hangi gazı kullanır?', '["Karbondioksit","Oksijen","Azot","Helyum"]'::jsonb, 0, 'bilim'),
('Atmosferde en çok bulunan gaz hangisidir?', '["Azot","Oksijen","Karbondioksit","Argon"]'::jsonb, 0, 'bilim'),
('Yerçekimi kanununu formüle eden bilim insanı kimdir?', '["Newton","Einstein","Galileo","Kepler"]'::jsonb, 0, 'bilim'),
('Görelilik kuramını geliştiren bilim insanı kimdir?', '["Einstein","Newton","Bohr","Planck"]'::jsonb, 0, 'bilim'),
('E=mc² formülü kime aittir?', '["Einstein","Newton","Tesla","Edison"]'::jsonb, 0, 'bilim'),
('Evrim kuramıyla tanınan bilim insanı kimdir?', '["Darwin","Mendel","Lamarck","Pasteur"]'::jsonb, 0, 'bilim'),
('Radyoaktiviteyi keşfederek iki Nobel kazanan kadın bilim insanı kimdir?', '["Marie Curie","Rosalind Franklin","Ada Lovelace","Lise Meitner"]'::jsonb, 0, 'bilim'),
('Telefonun mucidi olarak bilinen kişi kimdir?', '["Graham Bell","Edison","Tesla","Marconi"]'::jsonb, 0, 'bilim'),
('Ampulü ticarileştiren mucit kimdir?', '["Edison","Tesla","Bell","Faraday"]'::jsonb, 0, 'bilim'),
('Alternatif akımla çalışmalarıyla ünlü mucit kimdir?', '["Tesla","Edison","Volta","Ampere"]'::jsonb, 0, 'bilim'),
('Penisilini keşfeden bilim insanı kimdir?', '["Fleming","Pasteur","Koch","Jenner"]'::jsonb, 0, 'bilim'),
('Kuduz aşısını geliştiren bilim insanı kimdir?', '["Pasteur","Fleming","Koch","Salk"]'::jsonb, 0, 'bilim'),
('Periyodik tabloyu düzenleyen kimyager kimdir?', '["Mendeleyev","Lavoisier","Dalton","Bohr"]'::jsonb, 0, 'bilim'),
('Altının kimyasal sembolü nedir?', '["Au","Ag","Al","Fe"]'::jsonb, 0, 'bilim'),
('Gümüşün kimyasal sembolü nedir?', '["Ag","Au","Gu","Si"]'::jsonb, 0, 'bilim'),
('Demirin kimyasal sembolü nedir?', '["Fe","De","Ir","Dm"]'::jsonb, 0, 'bilim'),
('Oksijenin kimyasal sembolü nedir?', '["O","Ox","O2","Os"]'::jsonb, 0, 'bilim'),
('Sofra tuzunun kimyasal formülü nedir?', '["NaCl","KCl","CaCl2","NaOH"]'::jsonb, 0, 'bilim'),
('Periyodik tablodaki ilk element hangisidir?', '["Hidrojen","Helyum","Oksijen","Lityum"]'::jsonb, 0, 'bilim'),
('Su kaç derecede kaynar (deniz seviyesinde)?', '["100°C","90°C","110°C","120°C"]'::jsonb, 0, 'bilim'),
('Su kaç derecede donar?', '["0°C","-10°C","5°C","-5°C"]'::jsonb, 0, 'bilim'),
('Sesin boşlukta yayılamamasının sebebi nedir?', '["Madde olmaması","Sıcaklık düşüklüğü","Basınç yüksekliği","Işık olmaması"]'::jsonb, 0, 'bilim'),
('Gökkuşağında kaç renk olduğu kabul edilir?', '["7","6","8","5"]'::jsonb, 0, 'bilim'),
('Depremleri inceleyen bilim dalı hangisidir?', '["Sismoloji","Jeoloji","Meteoroloji","Astronomi"]'::jsonb, 0, 'bilim'),
('Deprem büyüklüğünü ölçen alet hangisidir?', '["Sismograf","Barometre","Termometre","Higrometre"]'::jsonb, 0, 'bilim'),
('Hava basıncını ölçen alet hangisidir?', '["Barometre","Termometre","Sismograf","Anemometre"]'::jsonb, 0, 'bilim'),
('Rüzgar hızını ölçen alet hangisidir?', '["Anemometre","Barometre","Higrometre","Altimetre"]'::jsonb, 0, 'bilim'),
('Canlıları inceleyen bilim dalı hangisidir?', '["Biyoloji","Kimya","Fizik","Jeoloji"]'::jsonb, 0, 'bilim'),
('Hücreyi ilk kez gözlemleyip adlandıran bilim insanı kimdir?', '["Robert Hooke","Darwin","Pasteur","Mendel"]'::jsonb, 0, 'bilim'),
('Bezelye deneyleriyle kalıtımın temellerini atan bilim insanı kimdir?', '["Mendel","Darwin","Watson","Crick"]'::jsonb, 0, 'bilim'),
('İnsan vücudunda kaç çift kromozom bulunur?', '["23","46","22","24"]'::jsonb, 0, 'bilim'),
('Dünyanın merkezindeki katman hangisidir?', '["Çekirdek","Manto","Kabuk","Litosfer"]'::jsonb, 0, 'bilim'),
('Dünya''nın katmanlarından en dışta olanı hangisidir?', '["Yer kabuğu","Manto","Dış çekirdek","İç çekirdek"]'::jsonb, 0, 'bilim'),
('Volkanlardan çıkan erimiş kayaca ne ad verilir?', '["Lav","Magma","Tüf","Bazalt"]'::jsonb, 0, 'bilim'),
('Yer altındaki erimiş kayaca ne ad verilir?', '["Magma","Lav","Mineral","Tortul"]'::jsonb, 0, 'bilim'),
('En sert doğal mineral hangisidir?', '["Elmas","Kuvars","Topaz","Korindon"]'::jsonb, 0, 'bilim'),
('Elmas hangi elementten oluşur?', '["Karbon","Silisyum","Kalsiyum","Bor"]'::jsonb, 0, 'bilim'),
('Dinozorların yok olduğu dönem hangisidir?', '["Kretase sonu","Jura sonu","Trias başı","Permiyen"]'::jsonb, 0, 'bilim'),
('Ay''ın Dünya çevresindeki turu yaklaşık kaç gün sürer?', '["27 gün","15 gün","45 gün","60 gün"]'::jsonb, 0, 'bilim'),
('Güneş tutulması ne zaman gerçekleşir?', '["Ay, Dünya ile Güneş arasına girince","Dünya, Ay ile Güneş arasına girince","Güneş, Ay''ın arkasına geçince","Ay kendi gölgesine girince"]'::jsonb, 0, 'bilim'),
('Bir yıldızın çekim kuvvetinden ışığın bile kaçamadığı gök cismi nedir?', '["Kara delik","Nötron yıldızı","Süpernova","Kuasar"]'::jsonb, 0, 'bilim'),
('Samanyolu nedir?', '["Galaksimiz","Takımyıldız","Gezegen","Bulutsu"]'::jsonb, 0, 'bilim'),
('Güneş hangi gaz ağırlıklıdır?', '["Hidrojen","Oksijen","Azot","Karbondioksit"]'::jsonb, 0, 'bilim'),
('Kutup Yıldızı hangi yönü gösterir?', '["Kuzey","Güney","Doğu","Batı"]'::jsonb, 0, 'bilim'),
('Bilgisayarın beyni olarak adlandırılan birim hangisidir?', '["İşlemci (CPU)","RAM","Ekran kartı","Anakart"]'::jsonb, 0, 'bilim'),
('WWW kısaltmasının açılımı nedir?', '["World Wide Web","World Web Wide","Wide World Web","Web World Wide"]'::jsonb, 0, 'bilim'),
('İnterneti icat ettiği kabul edilen "WWW''nin babası" kimdir?', '["Tim Berners-Lee","Bill Gates","Steve Jobs","Alan Turing"]'::jsonb, 0, 'bilim'),
('Modern bilgisayar biliminin babası sayılan İngiliz matematikçi kimdir?', '["Alan Turing","Charles Babbage","John von Neumann","Ada Lovelace"]'::jsonb, 0, 'bilim'),
('Tarihin ilk bilgisayar programcısı kabul edilen kişi kimdir?', '["Ada Lovelace","Grace Hopper","Alan Turing","Charles Babbage"]'::jsonb, 0, 'bilim'),
('İlk iPhone hangi yılda tanıtılmıştır?', '["2007","2005","2010","2003"]'::jsonb, 0, 'bilim'),
('Microsoft''un kurucusu kimdir?', '["Bill Gates","Steve Jobs","Mark Zuckerberg","Elon Musk"]'::jsonb, 0, 'bilim'),
('Apple''ın kurucularından en tanınanı kimdir?', '["Steve Jobs","Bill Gates","Jeff Bezos","Larry Page"]'::jsonb, 0, 'bilim'),
('İnsan beyninin büyük bölümünü oluşturan kısım hangisidir?', '["Beyin yarım küreleri","Beyincik","Omurilik soğanı","Hipotalamus"]'::jsonb, 0, 'bilim'),
('Dengeyi sağlayan beyin bölümü hangisidir?', '["Beyincik","Beyin","Omurilik","Hipofiz"]'::jsonb, 0, 'bilim'),
('İnsanda kaç duyu organı vardır?', '["5","4","6","7"]'::jsonb, 0, 'bilim'),
('Gözün renkli kısmına ne ad verilir?', '["İris","Retina","Kornea","Pupilla"]'::jsonb, 0, 'bilim'),
('Sesi algılayan duyu organı hangisidir?', '["Kulak","Göz","Burun","Dil"]'::jsonb, 0, 'bilim'),
('Vücudun en küçük kemiği nerededir?', '["Kulak","El","Ayak","Burun"]'::jsonb, 0, 'bilim'),
('Vücudun en uzun kemiği hangisidir?', '["Uyluk kemiği (femur)","Kaval kemiği","Pazu kemiği","Kürek kemiği"]'::jsonb, 0, 'bilim'),
('Hangi vitamin güneş ışığıyla sentezlenir?', '["D vitamini","C vitamini","A vitamini","B12 vitamini"]'::jsonb, 0, 'bilim'),
('C vitamini en çok hangisinde bulunur?', '["Turunçgiller","Et","Süt","Ekmek"]'::jsonb, 0, 'bilim'),
('Kanın pıhtılaşmasını sağlayan kan hücresi hangisidir?', '["Trombosit","Alyuvar","Akyuvar","Plazma"]'::jsonb, 0, 'bilim'),
('Vücudu hastalıklara karşı koruyan kan hücresi hangisidir?', '["Akyuvar","Alyuvar","Trombosit","Hemoglobin"]'::jsonb, 0, 'bilim'),
('İnsülin hormonu hangi organda üretilir?', '["Pankreas","Karaciğer","Böbrek","Mide"]'::jsonb, 0, 'bilim'),
('Şeker hastalığının tıptaki adı nedir?', '["Diyabet","Anemi","Astım","Migren"]'::jsonb, 0, 'bilim'),
('Dünyada en yaygın kan grubu hangisidir?', '["0 Rh+","A Rh+","B Rh+","AB Rh+"]'::jsonb, 0, 'bilim'),
('Bal yapan böcek hangisidir?', '["Arı","Karınca","Kelebek","Sinek"]'::jsonb, 0, 'bilim'),
('Dünyanın en hızlı kara hayvanı hangisidir?', '["Çita","Aslan","Antilop","At"]'::jsonb, 0, 'bilim'),
('Dünyanın en büyük hayvanı hangisidir?', '["Mavi balina","Fil","Köpekbalığı","Zürafa"]'::jsonb, 0, 'bilim'),
('Dünyanın en uzun boylu hayvanı hangisidir?', '["Zürafa","Fil","Deve","Ayı"]'::jsonb, 0, 'bilim'),
('Kuşların vücudunu kaplayan yapı nedir?', '["Tüy","Pul","Kıl","Deri"]'::jsonb, 0, 'bilim'),
('Penguenler doğal olarak hangi yarım kürede yaşar?', '["Güney","Kuzey","Her ikisi","Sadece Ekvator"]'::jsonb, 0, 'bilim'),
('Kutup ayıları doğal olarak nerede yaşar?', '["Kuzey Kutbu","Güney Kutbu","Her iki kutup","Grönland dışında her yer"]'::jsonb, 0, 'bilim'),
('Yarasalar yönlerini nasıl bulur?', '["Ses dalgalarıyla (ekolokasyon)","Görerek","Koklayarak","Isıyla"]'::jsonb, 0, 'bilim'),
('Bukalemunlar neyle ünlüdür?', '["Renk değiştirmek","Hızlı koşmak","Uçmak","Zehir püskürtmek"]'::jsonb, 0, 'bilim'),
('Ahtapotun kaç kolu vardır?', '["8","6","10","12"]'::jsonb, 0, 'bilim'),
('Örümceklerin kaç bacağı vardır?', '["8","6","10","4"]'::jsonb, 0, 'bilim'),
('Böceklerin kaç bacağı vardır?', '["6","8","4","10"]'::jsonb, 0, 'bilim'),
('Kelebeğin yaşam döngüsünde tırtıldan sonraki evre hangisidir?', '["Pupa (krizalit)","Yumurta","Ergin","Larva"]'::jsonb, 0, 'bilim'),
('Fotosentez bitkinin hangi organelinde gerçekleşir?', '["Kloroplast","Mitokondri","Ribozom","Çekirdek"]'::jsonb, 0, 'bilim'),
('Hücrenin enerji santrali olarak bilinen organel hangisidir?', '["Mitokondri","Kloroplast","Lizozom","Golgi"]'::jsonb, 0, 'bilim'),
('Dünyadaki oksijenin önemli bölümünü üreten canlılar hangileridir?', '["Deniz yosunları ve fitoplanktonlar","Ormanlardaki kuşlar","Mantarlar","Bakteriler"]'::jsonb, 0, 'bilim'),
('Ekosistemde üretici olan canlılar hangileridir?', '["Bitkiler","Otçullar","Etçiller","Mantarlar"]'::jsonb, 0, 'bilim'),
('Asit yağmurlarına neden olan başlıca gaz hangisidir?', '["Kükürt dioksit","Oksijen","Azot","Helyum"]'::jsonb, 0, 'bilim'),
('Sera etkisine en çok katkıda bulunan gaz hangisidir?', '["Karbondioksit","Oksijen","Azot","Argon"]'::jsonb, 0, 'bilim'),
('Ozon tabakası bizi neyden korur?', '["Zararlı güneş ışınlarından","Meteorlardan","Soğuktan","Rüzgardan"]'::jsonb, 0, 'bilim'),
('Geri dönüşüm sembolü hangi şekildedir?', '["Üçgen oluşturan oklar","Daire içinde yaprak","Kare içinde yıldız","Çift yönlü ok"]'::jsonb, 0, 'bilim'),
('Hangisi yenilenebilir enerji kaynağıdır?', '["Rüzgar","Kömür","Petrol","Doğalgaz"]'::jsonb, 0, 'bilim'),
('Elektrik akım birimi nedir?', '["Amper","Volt","Watt","Ohm"]'::jsonb, 0, 'bilim'),
('Elektrik gerilim birimi nedir?', '["Volt","Amper","Watt","Joule"]'::jsonb, 0, 'bilim'),
('Güç birimi nedir?', '["Watt","Volt","Newton","Pascal"]'::jsonb, 0, 'bilim'),
('Kuvvet birimi nedir?', '["Newton","Watt","Joule","Pascal"]'::jsonb, 0, 'bilim'),
('Frekans birimi nedir?', '["Hertz","Desibel","Watt","Ohm"]'::jsonb, 0, 'bilim'),
('Ses şiddeti hangi birimle ölçülür?', '["Desibel","Hertz","Newton","Lümen"]'::jsonb, 0, 'bilim'),
('Bir atomun çekirdeğinde hangi parçacıklar bulunur?', '["Proton ve nötron","Proton ve elektron","Elektron ve nötron","Sadece proton"]'::jsonb, 0, 'bilim'),
('Atomun çevresinde dolanan negatif yüklü parçacık hangisidir?', '["Elektron","Proton","Nötron","Foton"]'::jsonb, 0, 'bilim'),
('Mıknatısın çekmediği metal hangisidir?', '["Alüminyum","Demir","Nikel","Kobalt"]'::jsonb, 0, 'bilim'),
('Simyacıların altın yapmaya çalıştığı uğraş hangi bilimin atasıdır?', '["Kimya","Fizik","Biyoloji","Astronomi"]'::jsonb, 0, 'bilim'),
('Teleskopu gökyüzü gözlemlerinde ilk sistematik kullanan bilim insanı kimdir?', '["Galileo","Newton","Kepler","Kopernik"]'::jsonb, 0, 'bilim'),
('Dünya''nın Güneş çevresinde döndüğünü savunan modeli yeniden gündeme getiren kişi kimdir?', '["Kopernik","Batlamyus","Aristo","Sokrat"]'::jsonb, 0, 'bilim'),
('İlk yapay uydu hangisidir?', '["Sputnik 1","Apollo 11","Explorer 1","Voyager 1"]'::jsonb, 0, 'bilim'),
('Mars''ta görev yapan NASA keşif araçlarından biri hangisidir?', '["Curiosity","Hubble","Cassini","Voyager"]'::jsonb, 0, 'bilim'),
('Hubble nedir?', '["Uzay teleskobu","Roket","Uydu telefonu","Mars aracı"]'::jsonb, 0, 'bilim'),
('Ses hızını aşan uçakların çıkardığı patlamaya ne denir?', '["Sonik patlama","Türbülans","Rezonans","Yankı"]'::jsonb, 0, 'bilim'),
('Hangisi memeli bir deniz canlısıdır?', '["Yunus","Köpekbalığı","Ahtapot","Denizanası"]'::jsonb, 0, 'bilim'),
('Balinalar nasıl solunum yapar?', '["Akciğerle","Solungaçla","Deriyle","Yüzgeçle"]'::jsonb, 0, 'bilim'),
('Yılanlar nasıl beslenir?', '["Avını bütün yutar","Çiğneyerek","Emerek","Yalayarak"]'::jsonb, 0, 'bilim'),
('Hangisi sürüngendir?', '["Timsah","Kurbağa","Semender","Yunus"]'::jsonb, 0, 'bilim'),
('Kurbağa hangi canlı sınıfındandır?', '["İki yaşamlılar (amfibi)","Sürüngenler","Memeliler","Balıklar"]'::jsonb, 0, 'bilim'),
('Işık bir prizmadan geçince ne olur?', '["Renklerine ayrılır","Yok olur","Hızlanır","Isınır"]'::jsonb, 0, 'bilim'),
('Gök gürültüsünü şimşekten sonra duymamızın sebebi nedir?', '["Ses ışıktan yavaştır","Işık sesten yavaştır","Kulağımız geç algılar","Bulutlar sesi tutar"]'::jsonb, 0, 'bilim'),
('Demirin paslanmasına neden olan şey nedir?', '["Oksijen ve nem","Sadece sıcaklık","Işık","Tuz"]'::jsonb, 0, 'bilim'),
('Hangisi fiziksel değişimdir?', '["Buzun erimesi","Kağıdın yanması","Sütün ekşimesi","Demirin paslanması"]'::jsonb, 0, 'bilim'),
('Maddenin en küçük yapı taşı olarak bilinen birim nedir?', '["Atom","Molekül","Hücre","Element"]'::jsonb, 0, 'bilim'),
('Maddenin üç temel hali hangileridir?', '["Katı, sıvı, gaz","Sıcak, soğuk, ılık","Sert, yumuşak, esnek","Ağır, hafif, orta"]'::jsonb, 0, 'bilim'),
('Hangi gezegen Güneş Sistemi''nden gezegen statüsü çıkarılmıştır?', '["Plüton","Neptün","Merkür","Uranüs"]'::jsonb, 0, 'bilim'),
('Bir gün kaç saattir?', '["24","12","36","48"]'::jsonb, 0, 'bilim'),
('Artık yıl kaç günden oluşur?', '["366","365","364","367"]'::jsonb, 0, 'bilim'),
('Vücut ısısını ölçen alet hangisidir?', '["Termometre","Barometre","Tansiyon aleti","Higrometre"]'::jsonb, 0, 'bilim'),
('Röntgen ışınlarını keşfeden bilim insanı kimdir?', '["Wilhelm Röntgen","Marie Curie","Becquerel","Rutherford"]'::jsonb, 0, 'bilim'),
('Kalp atışlarını kaydeden cihaz hangisidir?', '["EKG","MR","Röntgen","Ultrason"]'::jsonb, 0, 'bilim')
on conflict (soru) do nothing;
