-- Soru havuzu genişletme: edebiyat +63, tarih +34, bilim +58
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Öykü ile roman arasındaki temel fark nedir?', '["Öykünün daha dar kapsamlı olması","Öykünün şiirsel olması","Romanın kısa olması","İkisinin aynı olması"]'::jsonb, 0, 'edebiyat'),
('Deneme türünün özelliği nedir?', '["Bilimsel kanıt zorunluluğu","Kişisel görüşü serbestçe anlatması","Kurgusal olay örgüsü","Sahnelenmesi"]'::jsonb, 1, 'edebiyat'),
('Makale türünün temel amacı nedir?', '["Duygu aktarmak","Öykü anlatmak","Bir savı kanıtlarla savunmak","Sahne kurmak"]'::jsonb, 2, 'edebiyat'),
('Anı (hatıra) türü neye dayanır?', '["Hayal ürünü olaylara","Bilimsel deneye","Sahne oyununa","Yazarın yaşadıklarına"]'::jsonb, 3, 'edebiyat'),
('Röportaj türünün ayırt edici yanı nedir?', '["Yerinde araştırma ve görüşmeye dayanması","Tamamen kurgu olması","Ölçülü yazılması","Sahnelenmesi"]'::jsonb, 0, 'edebiyat'),
('Eleştiri türünün amacı nedir?', '["Eseri kopyalamak","Eseri değerlendirip yorumlamak","Eseri satmak","Eseri gizlemek"]'::jsonb, 1, 'edebiyat'),
('Destan türünün özelliği nedir?', '["Gündelik yaşamı anlatması","Kısa olması","Olağanüstü kahramanları anlatması","Düzyazı olması zorunluluğu"]'::jsonb, 2, 'edebiyat'),
('Türk destanlarından Ergenekon hangi boya aittir?', '["Uygurlar","Hunlar","Kırgızlar","Göktürkler"]'::jsonb, 3, 'edebiyat'),
('Türeyiş ve Göç destanları hangi boya aittir?', '["Uygurlar","Göktürkler","Hunlar","Kıpçaklar"]'::jsonb, 0, 'edebiyat'),
('Alp Er Tunga Destanı hangi topluluğa aittir?', '["Uygurlar","Sakalar (İskitler)","Oğuzlar","Avarlar"]'::jsonb, 1, 'edebiyat'),
('Efsane ile masal arasındaki fark nedir?', '["Masalın gerçek olması","Efsanenin kısa olması","Efsanenin gerçek bir yere bağlanması","İkisinin aynı olması"]'::jsonb, 2, 'edebiyat'),
('Atasözünün özelliği nedir?', '["Uzun ve serbest olması","Yazarı belli olması","Ölçülü olması","Kalıplaşmış ve öğüt verici olması"]'::jsonb, 3, 'edebiyat'),
('Deyimin atasözünden farkı nedir?', '["Öğüt vermeyip durum anlatması","Öğüt vermesi","Uzun olması","Ölçülü olması"]'::jsonb, 0, 'edebiyat'),
('Bilmece türünün amacı nedir?', '["Öğüt vermek","Zekâyı sınayan bir cevap aratmak","Olay anlatmak","Şiir okumak"]'::jsonb, 1, 'edebiyat'),
('Mani nazım biriminin özelliği nedir?', '["On dört dizeli","Serbest ölçülü","Dört dizeli ve yedili hece ölçüsü","Beyitli"]'::jsonb, 2, 'edebiyat'),
('Koşma nazım biçiminde ölçü nedir?', '["Yedili hece","Aruz","Serbest","On birli hece"]'::jsonb, 3, 'edebiyat'),
('Semai nazım biçiminde hece ölçüsü kaçtır?', '["Sekizli","On birli","On dörtlü","Yedili"]'::jsonb, 0, 'edebiyat'),
('Destan (halk edebiyatı nazım biçimi) hangi ölçüyle yazılır?', '["Aruz ölçüsü","Hece ölçüsü","Serbest ölçü","Ölçüsüz"]'::jsonb, 1, 'edebiyat'),
('Kasidenin temel amacı nedir?', '["Aşkı anlatmak","Ölümü anlatmak","Birini övmek","Öğüt vermek"]'::jsonb, 2, 'edebiyat'),
('Divan edebiyatında ölçü olarak ne kullanılır?', '["Hece","Serbest","Ölçü kullanılmaz","Aruz"]'::jsonb, 3, 'edebiyat'),
('Hece ölçüsü neye dayanır?', '["Dizedeki hece sayısına","Hecelerin uzunluğuna","Kafiyeye","Redife"]'::jsonb, 0, 'edebiyat'),
('Redif nedir?', '["Dize sonundaki ses benzerliği","Kafiyeden sonra tekrarlanan ek","Ölçü türü","Nazım biçimi"]'::jsonb, 1, 'edebiyat'),
('Kafiye nedir?', '["Tekrarlanan kelime","Hece sayısı","Dize sonundaki ses benzerliği","Ölçü adı"]'::jsonb, 2, 'edebiyat'),
('Teşbih (benzetme) sanatı neye dayanır?', '["Abartıya","Karşıtlığa","Ses tekrarına","İki şeyin ortak yönle eşlenmesine"]'::jsonb, 3, 'edebiyat'),
('İstiare (eğretileme) sanatı neyi yapar?', '["Benzetmenin bir öğesini söylemez","Abartır","Ses tekrarlar","Karşıtlık kurar"]'::jsonb, 0, 'edebiyat'),
('Mübalağa sanatı neyi ifade eder?', '["Küçültme","Abartma","Karşılaştırma","Kişileştirme"]'::jsonb, 1, 'edebiyat'),
('Teşhis sanatı neyi yapar?', '["Abartır","Karşıtlık kurar","İnsan dışı varlığa insan özelliği verir","Ses yineler"]'::jsonb, 2, 'edebiyat'),
('Tezat sanatı neye dayanır?', '["Benzetmeye","Abartıya","Yinelemeye","Karşıt kavramların bir arada kullanımına"]'::jsonb, 3, 'edebiyat'),
('Aliterasyon nedir?', '["Ünsüz seslerin yinelenmesi","Ünlü seslerin yinelenmesi","Hece sayımı","Kafiye türü"]'::jsonb, 0, 'edebiyat'),
('Asonans nedir?', '["Ünsüz yinelenmesi","Ünlü seslerin yinelenmesi","Redif","Ölçü"]'::jsonb, 1, 'edebiyat'),
('Tevriye sanatı neye dayanır?', '["Abartıya","Karşıtlığa","Bir sözün iki anlamının kullanılmasına","Kişileştirmeye"]'::jsonb, 2, 'edebiyat'),
('Tanzimat edebiyatının temel amacı neydi?', '["Divan geleneğini sürdürmek","Halk şiirini yaymak","Din dışı şiiri yasaklamak","Batı edebiyatını tanıtıp toplumu eğitmek"]'::jsonb, 3, 'edebiyat'),
('İlk Türkçe tiyatro eseri olarak anılan yapıt hangisidir?', '["Şair Evlenmesi","Vatan yahut Silistre","İntibah","Araba Sevdası"]'::jsonb, 0, 'edebiyat'),
('Şair Evlenmesi''nin yazarı kimdir?', '["Namık Kemal","Şinasi","Ziya Paşa","Ahmet Mithat"]'::jsonb, 1, 'edebiyat'),
('İntibah romanının yazarı kimdir?', '["Şinasi","Recaizade Ekrem","Namık Kemal","Samipaşazade Sezai"]'::jsonb, 2, 'edebiyat'),
('Servet-i Fünun döneminin öne çıkan romancısı kimdir?', '["Namık Kemal","Ahmet Mithat","Ömer Seyfettin","Halit Ziya Uşaklıgil"]'::jsonb, 3, 'edebiyat'),
('Ömer Seyfettin hangi türde tanınır?', '["Öykü","Roman","Şiir","Tiyatro"]'::jsonb, 0, 'edebiyat'),
('Yakup Kadri Karaosmanoğlu''nun köy konulu romanı hangisidir?', '["Kiralık Konak","Yaban","Ankara","Nur Baba"]'::jsonb, 1, 'edebiyat'),
('Peyami Safa''nın ünlü psikolojik romanı hangisidir?', '["Yaban","Çalıkuşu","Dokuzuncu Hariciye Koğuşu","Sinekli Bakkal"]'::jsonb, 2, 'edebiyat'),
('Orhan Kemal''in romanlarının başlıca konusu nedir?', '["Saray hayatı","Bilim kurgu","Fantastik dünya","Emekçilerin yaşamı"]'::jsonb, 3, 'edebiyat'),
('Kemal Tahir''in tarihsel romanlarından biri hangisidir?', '["Devlet Ana","Aşk-ı Memnu","Huzur","Tutunamayanlar"]'::jsonb, 0, 'edebiyat'),
('Fakir Baykurt hangi konuyu işlemiştir?', '["Aristokrat yaşam","Köy gerçekliği","Uzay macerası","Polisiye"]'::jsonb, 1, 'edebiyat'),
('Yusuf Atılgan''ın ünlü romanı hangisidir?', '["Yaban","Huzur","Anayurt Oteli","Devlet Ana"]'::jsonb, 2, 'edebiyat'),
('Latife Tekin hangi anlatım biçimiyle tanınır?', '["Belgesel roman","Polisiye","Bilim kurgu","Büyülü gerçekçilik"]'::jsonb, 3, 'edebiyat'),
('Nâzım Hikmet şiirde hangi ölçüyü kullanmıştır?', '["Serbest ölçü","Aruz","Hece","Sadece on birli hece"]'::jsonb, 0, 'edebiyat'),
('Yahya Kemal Beyatlı hangi ölçüyü ustaca kullanmıştır?', '["Hece","Aruz","Serbest","Ölçüsüz"]'::jsonb, 1, 'edebiyat'),
('Ahmet Haşim hangi şiir anlayışını savunmuştur?', '["Toplumcu şiir","Öğretici şiir","Saf (öz) şiir","Destansı şiir"]'::jsonb, 2, 'edebiyat'),
('Cahit Sıtkı Tarancı''nın yaş temalı ünlü şiiri hangisidir?', '["Sessiz Gemi","Han Duvarları","Kaldırımlar","Otuz Beş Yaş"]'::jsonb, 3, 'edebiyat'),
('Kaldırımlar şiiri hangi şaire aittir?', '["Necip Fazıl Kısakürek","Cahit Sıtkı","Orhan Veli","Attila İlhan"]'::jsonb, 0, 'edebiyat'),
('Çehov hangi türde ustalığıyla tanınır?', '["Destan","Öykü ve tiyatro","Epik şiir","Deneme"]'::jsonb, 1, 'edebiyat'),
('İnsanlık Komedyası dizisinin yazarı kimdir?', '["Hugo","Zola","Balzac","Stendhal"]'::jsonb, 2, 'edebiyat'),
('Germinal romanının yazarı kimdir?', '["Flaubert","Balzac","Proust","Emile Zola"]'::jsonb, 3, 'edebiyat'),
('Kayıp Zamanın İzinde eserinin yazarı kimdir?', '["Marcel Proust","Camus","Sartre","Gide"]'::jsonb, 0, 'edebiyat'),
('Ulysses romanının yazarı kimdir?', '["Virginia Woolf","James Joyce","T.S. Eliot","D.H. Lawrence"]'::jsonb, 1, 'edebiyat'),
('Mrs Dalloway romanının yazarı kimdir?', '["Joyce","Austen","Virginia Woolf","Bronte"]'::jsonb, 2, 'edebiyat'),
('Oliver Twist ve İki Şehrin Hikayesi kimin eserleridir?', '["Thomas Hardy","Walter Scott","Anthony Trollope","Charles Dickens"]'::jsonb, 3, 'edebiyat'),
('Edgar Allan Poe hangi türün öncüsü sayılır?', '["Polisiye ve korku öyküsü","Bilim kurgu romanı","Tarihsel roman","Pastoral şiir"]'::jsonb, 0, 'edebiyat'),
('Çavdar Tarlasında Çocuklar kimin eseridir?', '["Kerouac","J.D. Salinger","Vonnegut","Updike"]'::jsonb, 1, 'edebiyat'),
('Zaman Makinesi romanının yazarı kimdir?', '["Jules Verne","Asimov","H.G. Wells","Clarke"]'::jsonb, 2, 'edebiyat'),
('Gulliver''in Gezileri kimin eseridir?', '["Defoe","Fielding","Sterne","Jonathan Swift"]'::jsonb, 3, 'edebiyat'),
('Büyülü Dağ romanının yazarı kimdir?', '["Thomas Mann","Hermann Hesse","Kafka","Böll"]'::jsonb, 0, 'edebiyat'),
('Bozkırkurdu romanının yazarı kimdir?', '["Thomas Mann","Hermann Hesse","Kafka","Zweig"]'::jsonb, 1, 'edebiyat'),
('Satranç adlı novellanın yazarı kimdir?', '["Kafka","Musil","Stefan Zweig","Broch"]'::jsonb, 2, 'edebiyat'),
('Neolitik Devrim neyi ifade eder?', '["Tarıma ve yerleşik yaşama geçiş","Yazının bulunuşu","Ateşin bulunuşu","Demir kullanımı"]'::jsonb, 0, 'tarih'),
('Tarih öncesi ile tarihi devirleri ayıran olay nedir?', '["Ateşin bulunması","Yazının icadı","Tekerleğin icadı","Tarımın başlaması"]'::jsonb, 1, 'tarih'),
('Çatalhöyük hangi döneme ait bir yerleşimdir?', '["Paleolitik","Tunç Çağı","Neolitik","Demir Çağı"]'::jsonb, 2, 'tarih'),
('Sümerlerde şehir devletlerinin merkezinde yer alan yapı nedir?', '["Piramit","Amfitiyatro","Akropol","Ziggurat"]'::jsonb, 3, 'tarih'),
('Mısır''da firavunlar için yapılan anıt mezarlar hangileridir?', '["Piramitler","Zigguratlar","Kurganlar","Tümülüsler"]'::jsonb, 0, 'tarih'),
('Mumyalama geleneği hangi uygarlıkla özdeşleşmiştir?', '["Sümer","Mısır","Hitit","Fenike"]'::jsonb, 1, 'tarih'),
('Hititlerin başkenti neresiydi?', '["Ninova","Babil","Hattuşa","Sard"]'::jsonb, 2, 'tarih'),
('Friglerin başkenti neresiydi?', '["Sard","Tuşpa","Ninova","Gordion"]'::jsonb, 3, 'tarih'),
('Lidyalıların başkenti neresiydi?', '["Sard","Gordion","Efes","Milet"]'::jsonb, 0, 'tarih'),
('İyonyalılar hangi alanda öne çıkmıştır?', '["Piramit yapımı","Bilim ve felsefe","Mumyalama","Kanun yapımı"]'::jsonb, 1, 'tarih'),
('Perslerin kurduğu yol ağı hangisidir?', '["İpek Yolu","Baharat Yolu","Kral Yolu","Kürk Yolu"]'::jsonb, 2, 'tarih'),
('Atina''da demokrasi hangi kurumda uygulanıyordu?', '["Senato","Konsül","Divan","Halk meclisi"]'::jsonb, 3, 'tarih'),
('Sparta hangi özelliğiyle bilinir?', '["Askerî yaşam düzeni","Ticaret merkezi olması","Felsefe okulu","Deniz gücü olmaması"]'::jsonb, 0, 'tarih'),
('İskender''in kurduğu imparatorluk hangi kültürü doğurmuştur?', '["Roma kültürü","Helenistik kültür","Bizans kültürü","Pers kültürü"]'::jsonb, 1, 'tarih'),
('Roma''da cumhuriyet döneminde yönetimde kimler etkiliydi?', '["Firavunlar","Halifeler","Senato ve konsüller","Şahlar"]'::jsonb, 2, 'tarih'),
('Roma İmparatorluğu''nda ''Pax Romana'' ne anlama gelir?', '["Roma iç savaşı","Roma yasası","Roma ordusu","Roma barış dönemi"]'::jsonb, 3, 'tarih'),
('Kavimler Göçü''nün en önemli sonucu nedir?', '["Roma''nın ikiye ayrılması","Yazının bulunması","Rönesans","Sanayi Devrimi"]'::jsonb, 0, 'tarih'),
('Feodalite (derebeylik) düzeninin temeli nedir?', '["Para ekonomisi","Toprak karşılığı hizmet ilişkisi","Sanayi üretimi","Deniz ticareti"]'::jsonb, 1, 'tarih'),
('Magna Carta hangi hakkı sınırlamıştır?', '["Kilisenin yetkilerini","Halkın haklarını","Kralın yetkilerini","Tüccarların hakkını"]'::jsonb, 2, 'tarih'),
('Reform hareketinin sonucu ne olmuştur?', '["Katolikliğin bitişi","İslam''ın yayılışı","Ortodoksluğun kuruluşu","Protestanlığın doğuşu"]'::jsonb, 3, 'tarih'),
('Coğrafi Keşifleri hızlandıran teknik gelişme nedir?', '["Pusula ve gemicilik bilgisi","Matbaa","Barut","Buhar makinesi"]'::jsonb, 0, 'tarih'),
('Aydınlanma Çağı''nın temel dayanağı nedir?', '["Gelenek","Akıl ve bilim","Otorite","Mistisizm"]'::jsonb, 1, 'tarih'),
('Amerikan Bağımsızlık Bildirgesi hangi yıl kabul edilmiştir?', '["1789","1799","1776","1804"]'::jsonb, 2, 'tarih'),
('Napolyon''un son yenilgisi hangi savaştadır?', '["Austerlitz","Trafalgar","Leipzig","Waterloo"]'::jsonb, 3, 'tarih'),
('Viyana Kongresi''nin amacı neydi?', '["Napolyon sonrası Avrupa düzenini kurmak","Sanayi Devrimi''ni başlatmak","Sömürgeleri paylaşmak","Reform yapmak"]'::jsonb, 0, 'tarih'),
('Sanayi Devrimi''nin temel enerji kaynağı neydi?', '["Petrol","Kömür ve buhar","Elektrik","Rüzgâr"]'::jsonb, 1, 'tarih'),
('Çanakkale Savaşları''nın sonucu ne olmuştur?', '["İstanbul''un işgali","Osmanlı''nın teslimi","İtilaf kuvvetlerinin geçememesi","Savaşın bitmesi"]'::jsonb, 2, 'tarih'),
('Mondros Ateşkes Antlaşması ne anlama geliyordu?', '["Savaşın kazanılması","Cumhuriyetin ilanı","Saltanatın kaldırılması","Osmanlı''nın savaştan çekilmesi"]'::jsonb, 3, 'tarih'),
('Türk kadınlarına milletvekili seçme ve seçilme hakkı hangi yıl verilmiştir?', '["1934","1923","1930","1926"]'::jsonb, 0, 'tarih'),
('Tevhid-i Tedrisat Kanunu neyi sağlamıştır?', '["Harf değişimini","Eğitimin birleştirilmesini","Kadın haklarını","Takvim değişimini"]'::jsonb, 1, 'tarih'),
('Pearl Harbor saldırısı hangi ülkeyi savaşa sokmuştur?', '["İngiltere","Sovyetler Birliği","ABD","Fransa"]'::jsonb, 2, 'tarih'),
('Marshall Planı neyi amaçlamıştır?', '["Askerî işgali","Sömürge kurmayı","Ticaret yasağını","Avrupa''nın ekonomik onarımını"]'::jsonb, 3, 'tarih'),
('NATO hangi yıl kurulmuştur?', '["1949","1945","1955","1961"]'::jsonb, 0, 'tarih'),
('Küba Füze Krizi hangi yıl yaşanmıştır?', '["1949","1962","1956","1968"]'::jsonb, 1, 'tarih'),
('Bir atomun kimliğini belirleyen tanecik hangisidir?', '["Proton","Nötron","Elektron","Foton"]'::jsonb, 0, 'bilim'),
('İzotop atomlar hangi bakımdan farklıdır?', '["Proton sayısı","Nötron sayısı","Elektron yükü","Element adı"]'::jsonb, 1, 'bilim'),
('Periyodik tabloda aynı grupta bulunan elementlerin ortak yanı nedir?', '["Atom kütlesi","Kaynama noktası","Değerlik elektron sayısı","Renk"]'::jsonb, 2, 'bilim'),
('Soy gazların tepkimeye girmemesinin nedeni nedir?', '["Ağır olmaları","Renksiz olmaları","Nadir olmaları","Kararlı elektron dizilimi"]'::jsonb, 3, 'bilim'),
('İyonik bağ nasıl oluşur?', '["Elektron alışverişiyle","Elektron ortaklığıyla","Proton geçişiyle","Nötron paylaşımıyla"]'::jsonb, 0, 'bilim'),
('Kovalent bağ nasıl oluşur?', '["Elektron aktarımıyla","Elektronların ortaklaşa kullanılmasıyla","Proton geçişiyle","Isı alışverişiyle"]'::jsonb, 1, 'bilim'),
('Suyun yüksek kaynama noktasının nedeni nedir?', '["İyonik bağlar","Metalik bağlar","Hidrojen bağları","Düşük yoğunluk"]'::jsonb, 2, 'bilim'),
('Asitlerin sulu çözeltide verdiği iyon hangisidir?', '["Hidroksit iyonu","Sodyum iyonu","Klor iyonu","Hidrojen iyonu"]'::jsonb, 3, 'bilim'),
('pH değeri 7 olan çözelti nasıl tanımlanır?', '["Nötr","Kuvvetli asit","Kuvvetli baz","Doymuş"]'::jsonb, 0, 'bilim'),
('Endotermik tepkimenin özelliği nedir?', '["Isı vermesi","Isı soğurması","Işık üretmesi","Kütle kaybı"]'::jsonb, 1, 'bilim'),
('Newton''un birinci hareket yasası neyi anlatır?', '["Kuvvet-ivme ilişkisini","Etki-tepkiyi","Eylemsizlik ilkesini","Kütle çekimini"]'::jsonb, 2, 'bilim'),
('Newton''un üçüncü yasası neyi ifade eder?', '["Eylemsizliği","Enerji korunumunu","Momentumun sıfırlanmasını","Her etkiye eşit ve zıt tepki"]'::jsonb, 3, 'bilim'),
('İvme neyi ifade eder?', '["Hızın zamana göre değişimini","Yolun zamana oranını","Kuvvetin kütleye oranı değil","Enerjinin değişimini"]'::jsonb, 0, 'bilim'),
('Kinetik enerji neye bağlıdır?', '["Yalnız yüksekliğe","Kütle ve hıza","Yalnız sıcaklığa","Yalnız hacme"]'::jsonb, 1, 'bilim'),
('Potansiyel enerji hangi durumda artar?', '["Hız arttıkça","Sıcaklık düştükçe","Yükseklik arttıkça","Kütle azaldıkça"]'::jsonb, 2, 'bilim'),
('Mutlak sıfır sıcaklığı Kelvin ölçeğinde kaçtır?', '["273","100","373","0"]'::jsonb, 3, 'bilim'),
('Işığın kırılması hangi durumda gerçekleşir?', '["Ortam değiştirirken","Aynı ortamda giderken","Boşlukta giderken","Yansırken"]'::jsonb, 0, 'bilim'),
('Gökyüzünün mavi görünmesinin nedeni nedir?', '["Denizin yansıması","Işığın saçılması","Ozon rengi","Bulut yoğunluğu"]'::jsonb, 1, 'bilim'),
('Prizma beyaz ışığa ne yapar?', '["Yok eder","Isıtır","Renklerine ayırır","Hızlandırır"]'::jsonb, 2, 'bilim'),
('Sesin boşlukta yayılmamasının nedeni nedir?', '["Çok hızlı olması","Enerjisiz olması","Elektromanyetik olması","Ortam taneciği gerektirmesi"]'::jsonb, 3, 'bilim'),
('Sesin en hızlı yayıldığı ortam hangisidir?', '["Katı","Sıvı","Gaz","Boşluk"]'::jsonb, 0, 'bilim'),
('Doppler etkisi neyi açıklar?', '["Sesin sönmesini","Hareketle frekansın değişmesini","Işığın kırılmasını","Yankının oluşumunu"]'::jsonb, 1, 'bilim'),
('Ohm yasası hangi büyüklükleri ilişkilendirir?', '["Kütle, hız ve enerji","Basınç, hacim ve sıcaklık","Gerilim, akım ve direnç","Kuvvet, alan ve zaman"]'::jsonb, 2, 'bilim'),
('Seri bağlı devrede akım nasıldır?', '["Her elemanda farklıdır","Sıfırdır","İkiye katlanır","Her elemanda aynıdır"]'::jsonb, 3, 'bilim'),
('Paralel bağlı devrede gerilim nasıldır?', '["Her kolda aynıdır","Her kolda farklıdır","Sıfırdır","Toplanır"]'::jsonb, 0, 'bilim'),
('Manyetik alan hangi durumda oluşur?', '["Durgun yükte","Hareketli yük (akım) varlığında","Yalnız mıknatısta","Yalnız boşlukta"]'::jsonb, 1, 'bilim'),
('Transformatörün işlevi nedir?', '["Akımı üretmek","Direnç eklemek","Gerilim düzeyini değiştirmek","Frekansı sıfırlamak"]'::jsonb, 2, 'bilim'),
('Hücre teorisine göre canlıların temel birimi nedir?', '["Doku","Organ","Molekül","Hücre"]'::jsonb, 3, 'bilim'),
('Prokaryot hücrenin ökaryottan farkı nedir?', '["Zarla çevrili çekirdeğinin olmaması","Ribozomu olmaması","DNA''sı olmaması","Zarı olmaması"]'::jsonb, 0, 'bilim'),
('Mitokondrinin hücredeki görevi nedir?', '["Protein sentezi","Enerji üretimi","Atık depolama","Bölünme"]'::jsonb, 1, 'bilim'),
('Fotosentezde hangi gaz kullanılır?', '["Oksijen","Azot","Karbondioksit","Hidrojen"]'::jsonb, 2, 'bilim'),
('Fotosentezin ürünlerinden biri hangisidir?', '["Karbondioksit","Azot","Metan","Oksijen"]'::jsonb, 3, 'bilim'),
('Mitoz bölünmenin sonucu nedir?', '["Aynı kromozom sayılı iki hücre","Yarı kromozomlu dört hücre","Tek hücre","Kromozomsuz hücre"]'::jsonb, 0, 'bilim'),
('DNA''da adenin hangi baz ile eşleşir?', '["Guanin","Timin","Sitozin","Urasil"]'::jsonb, 1, 'bilim'),
('RNA''da timin yerine hangi baz bulunur?', '["Adenin","Guanin","Urasil","Sitozin"]'::jsonb, 2, 'bilim'),
('Genin tanımı nedir?', '["Bir protein türü","Bir hücre organeli","Bir hormon","Kalıtsal bilgi taşıyan DNA parçası"]'::jsonb, 3, 'bilim'),
('Mendel''in çalıştığı bitki hangisidir?', '["Bezelye","Fasulye","Mısır","Buğday"]'::jsonb, 0, 'bilim'),
('Baskın (dominant) gen ne anlama gelir?', '["Etkisini hiç göstermeyen gen","Etkisini her durumda gösteren gen","Bozuk gen","Yedek gen"]'::jsonb, 1, 'bilim'),
('İnsanda kromozom sayısı kaçtır?', '["23","48","46","44"]'::jsonb, 2, 'bilim'),
('Alyuvarların temel görevi nedir?', '["Mikrop öldürmek","Pıhtılaşma sağlamak","Hormon üretmek","Oksijen taşımak"]'::jsonb, 3, 'bilim'),
('Akyuvarların temel görevi nedir?', '["Bağışıklık savunması","Oksijen taşımak","Yağ sindirmek","Kemik yapmak"]'::jsonb, 0, 'bilim'),
('Trombositlerin görevi nedir?', '["Oksijen taşımak","Kanın pıhtılaşması","Hormon salgılamak","Sindirim"]'::jsonb, 1, 'bilim'),
('Böbreğin temel görevi nedir?', '["Oksijen almak","Yiyecek öğütmek","Kanı süzüp atık uzaklaştırmak","Hormon depolamak"]'::jsonb, 2, 'bilim'),
('İnsanda gaz alışverişi hangi yapıda gerçekleşir?', '["Bronşlarda","Gırtlakta","Yemek borusunda","Alveollerde"]'::jsonb, 3, 'bilim'),
('Enzimlerin temel özelliği nedir?', '["Tepkimeleri hızlandırması","Tepkimeyi durdurması","Enerji üretmesi","Hücre bölmesi"]'::jsonb, 0, 'bilim'),
('Hormonların vücuttaki taşıyıcısı nedir?', '["Sinir","Kan","Lenf yalnızca","Hava"]'::jsonb, 1, 'bilim'),
('İnsülin hormonu neyi düzenler?', '["Kan basıncını","Vücut ısısını","Kan şekerini","Kalp atışını"]'::jsonb, 2, 'bilim'),
('Bağışıklık sisteminde antikor ne yapar?', '["Enerji üretir","Sindirim yapar","Kemik yapar","Yabancı maddeyi tanıyıp etkisizleştirir"]'::jsonb, 3, 'bilim'),
('Aşının çalışma ilkesi nedir?', '["Bağışıklık belleği oluşturmak","Mikrobu doğrudan öldürmek","Ateşi düşürmek","Ağrı kesmek"]'::jsonb, 0, 'bilim'),
('Virüslerin canlı sayılmama gerekçelerinden biri nedir?', '["DNA taşımaması","Konak dışında çoğalamaması","Protein içermemesi","Zar taşımaması"]'::jsonb, 1, 'bilim'),
('Ekosistemde üreticiler kimlerdir?', '["Etçiller","Ayrıştırıcılar","Fotosentez yapan canlılar","Otçullar"]'::jsonb, 2, 'bilim'),
('Besin zincirinde ayrıştırıcıların rolü nedir?', '["Enerji üretmek","Avlanmak","Fotosentez yapmak","Organik maddeyi doğaya döndürmek"]'::jsonb, 3, 'bilim'),
('Bir ekosistemde enerji akışının yönü nasıldır?', '["Tek yönlü","Çift yönlü","Dairesel","Rastgele"]'::jsonb, 0, 'bilim'),
('Halkalarıyla tanınan gezegen hangisidir?', '["Jüpiter","Satürn","Uranüs","Mars"]'::jsonb, 1, 'bilim'),
('Kızıl gezegen olarak anılan gezegen hangisidir?', '["Venüs","Merkür","Mars","Jüpiter"]'::jsonb, 2, 'bilim'),
('Kara deliğin en belirgin özelliği nedir?', '["Işık yayması","Soğuk olması","Küçük kütleli olması","Işığın bile kaçamayacağı çekim"]'::jsonb, 3, 'bilim'),
('Büyük Patlama kuramı neyi açıklar?', '["Evrenin genişleyerek oluşumunu","Güneş''in sönmesini","Ay''ın oluşumunu","Depremleri"]'::jsonb, 0, 'bilim'),
('Samanyolu ne tür bir gök cismidir?', '["Yıldız","Sarmal galaksi","Gezegen","Kuyruklu yıldız"]'::jsonb, 1, 'bilim')
on conflict (soru) do nothing;
