-- Soru havuzu genişletme — Parti 3: Edebiyat + Sanat
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('İstiklal Marşı''nın şairi kimdir?', '["Mehmet Akif Ersoy","Yahya Kemal","Namık Kemal","Ziya Gökalp"]'::jsonb, 0, 'edebiyat'),
('İstiklal Marşı hangi yılda kabul edilmiştir?', '["1921","1923","1920","1924"]'::jsonb, 0, 'edebiyat'),
('"Safahat" adlı eser kime aittir?', '["Mehmet Akif Ersoy","Tevfik Fikret","Yahya Kemal","Ahmet Haşim"]'::jsonb, 0, 'edebiyat'),
('Nutuk adlı eser kime aittir?', '["Mustafa Kemal Atatürk","İsmet İnönü","Kazım Karabekir","Fevzi Çakmak"]'::jsonb, 0, 'edebiyat'),
('"İnce Memed" romanının yazarı kimdir?', '["Yaşar Kemal","Orhan Kemal","Kemal Tahir","Fakir Baykurt"]'::jsonb, 0, 'edebiyat'),
('Nobel Edebiyat Ödülü kazanan ilk Türk yazar kimdir?', '["Orhan Pamuk","Yaşar Kemal","Nazım Hikmet","Aziz Nesin"]'::jsonb, 0, 'edebiyat'),
('"Benim Adım Kırmızı" romanının yazarı kimdir?', '["Orhan Pamuk","Elif Şafak","Ahmet Ümit","Oğuz Atay"]'::jsonb, 0, 'edebiyat'),
('"Tutunamayanlar" romanının yazarı kimdir?', '["Oğuz Atay","Yusuf Atılgan","Sait Faik","Sabahattin Ali"]'::jsonb, 0, 'edebiyat'),
('"Kürk Mantolu Madonna" kimin eseridir?', '["Sabahattin Ali","Sait Faik","Orhan Kemal","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('"Çalıkuşu" romanının yazarı kimdir?', '["Reşat Nuri Güntekin","Halide Edib","Yakup Kadri","Hüseyin Rahmi"]'::jsonb, 0, 'edebiyat'),
('"Sinekli Bakkal" romanının yazarı kimdir?', '["Halide Edib Adıvar","Reşat Nuri","Yakup Kadri","Halid Ziya"]'::jsonb, 0, 'edebiyat'),
('"Yaban" romanının yazarı kimdir?', '["Yakup Kadri Karaosmanoğlu","Reşat Nuri","Halide Edib","Refik Halid"]'::jsonb, 0, 'edebiyat'),
('"Aşk-ı Memnu" romanının yazarı kimdir?', '["Halid Ziya Uşaklıgil","Mehmet Rauf","Hüseyin Cahit","Recaizade Ekrem"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatının ilk yerli romanı kabul edilen eser hangisidir?', '["Taaşşuk-ı Talat ve Fitnat","İntibah","Araba Sevdası","Felatun Bey ile Rakım Efendi"]'::jsonb, 0, 'edebiyat'),
('"Memleketimden İnsan Manzaraları" kimin eseridir?', '["Nazım Hikmet","Orhan Veli","Cahit Sıtkı","Attila İlhan"]'::jsonb, 0, 'edebiyat'),
('Garip akımının öncüsü olan şair kimdir?', '["Orhan Veli Kanık","Nazım Hikmet","Cemal Süreya","Cahit Külebi"]'::jsonb, 0, 'edebiyat'),
('"İstanbul''u dinliyorum gözlerim kapalı" dizesi kime aittir?', '["Orhan Veli Kanık","Yahya Kemal","Nazım Hikmet","Necip Fazıl"]'::jsonb, 0, 'edebiyat'),
('"Otuz Beş Yaş" şiirinin şairi kimdir?', '["Cahit Sıtkı Tarancı","Orhan Veli","Ahmet Muhip","Ziya Osman"]'::jsonb, 0, 'edebiyat'),
('"Kaldırımlar" şiirinin şairi kimdir?', '["Necip Fazıl Kısakürek","Nazım Hikmet","Yahya Kemal","Faruk Nafiz"]'::jsonb, 0, 'edebiyat'),
('"Han Duvarları" şiirinin şairi kimdir?', '["Faruk Nafiz Çamlıbel","Necip Fazıl","Yahya Kemal","Orhan Seyfi"]'::jsonb, 0, 'edebiyat'),
('Divan edebiyatının ünlü "Su Kasidesi" kime aittir?', '["Fuzuli","Baki","Nedim","Nefi"]'::jsonb, 0, 'edebiyat'),
('Leyla ile Mecnun mesnevisinin en ünlü Türkçe yazarı kimdir?', '["Fuzuli","Baki","Şeyh Galip","Nabi"]'::jsonb, 0, 'edebiyat'),
('"Mesnevi" adlı eser kime aittir?', '["Mevlana","Yunus Emre","Hacı Bektaş","Ahmet Yesevi"]'::jsonb, 0, 'edebiyat'),
('"Gel, gel, ne olursan ol yine gel" çağrısı kime atfedilir?', '["Mevlana","Yunus Emre","Hacı Bektaş Veli","Pir Sultan"]'::jsonb, 0, 'edebiyat'),
('"Sevelim, sevilelim" felsefesiyle tanınan halk ozanı kimdir?', '["Yunus Emre","Karacaoğlan","Pir Sultan Abdal","Aşık Veysel"]'::jsonb, 0, 'edebiyat'),
('"Uzun ince bir yoldayım" türküsünün sahibi kimdir?', '["Aşık Veysel","Neşet Ertaş","Karacaoğlan","Dadaloğlu"]'::jsonb, 0, 'edebiyat'),
('Dede Korkut Hikayeleri hangi Türk boyunun destanlarını anlatır?', '["Oğuzlar","Kıpçaklar","Uygurlar","Karluklar"]'::jsonb, 0, 'edebiyat'),
('Divanü Lugati''t-Türk''ün yazarı kimdir?', '["Kaşgarlı Mahmut","Yusuf Has Hacib","Ali Şir Nevai","Ahmet Yesevi"]'::jsonb, 0, 'edebiyat'),
('Kutadgu Bilig''in yazarı kimdir?', '["Yusuf Has Hacib","Kaşgarlı Mahmut","Edip Ahmet","Ahmet Yesevi"]'::jsonb, 0, 'edebiyat'),
('Nasreddin Hoca fıkralarında hangi hayvana ters biner?', '["Eşek","At","Deve","Katır"]'::jsonb, 0, 'edebiyat'),
('Keloğlan masallarında Keloğlan genellikle kiminle yaşar?', '["Annesiyle","Babasıyla","Dedesiyle","Kardeşiyle"]'::jsonb, 0, 'edebiyat'),
('"Romeo ve Juliet" kimin eseridir?', '["Shakespeare","Goethe","Moliere","Dante"]'::jsonb, 0, 'edebiyat'),
('"Hamlet" kimin eseridir?', '["Shakespeare","Çehov","İbsen","Sofokles"]'::jsonb, 0, 'edebiyat'),
('"Suç ve Ceza" romanının yazarı kimdir?', '["Dostoyevski","Tolstoy","Çehov","Gogol"]'::jsonb, 0, 'edebiyat'),
('"Savaş ve Barış" romanının yazarı kimdir?', '["Tolstoy","Dostoyevski","Turgenyev","Puşkin"]'::jsonb, 0, 'edebiyat'),
('"Sefiller" romanının yazarı kimdir?', '["Victor Hugo","Balzac","Zola","Flaubert"]'::jsonb, 0, 'edebiyat'),
('"Don Kişot" romanının yazarı kimdir?', '["Cervantes","Lorca","Marquez","Borges"]'::jsonb, 0, 'edebiyat'),
('"Yüzyıllık Yalnızlık" romanının yazarı kimdir?', '["Gabriel Garcia Marquez","Borges","Llosa","Neruda"]'::jsonb, 0, 'edebiyat'),
('"Küçük Prens" kitabının yazarı kimdir?', '["Saint-Exupery","Jules Verne","Andersen","Grimm Kardeşler"]'::jsonb, 0, 'edebiyat'),
('"Denizler Altında Yirmi Bin Fersah" kimin eseridir?', '["Jules Verne","H.G. Wells","Daniel Defoe","Stevenson"]'::jsonb, 0, 'edebiyat'),
('"Robinson Crusoe" romanının yazarı kimdir?', '["Daniel Defoe","Jonathan Swift","Stevenson","Dickens"]'::jsonb, 0, 'edebiyat'),
('"Oliver Twist" romanının yazarı kimdir?', '["Charles Dickens","Mark Twain","Jane Austen","Bronte"]'::jsonb, 0, 'edebiyat'),
('"Tom Sawyer''ın Maceraları" kimin eseridir?', '["Mark Twain","Dickens","Jack London","Hemingway"]'::jsonb, 0, 'edebiyat'),
('"İhtiyar Adam ve Deniz" kimin eseridir?', '["Hemingway","Steinbeck","Faulkner","Fitzgerald"]'::jsonb, 0, 'edebiyat'),
('"1984" romanının yazarı kimdir?', '["George Orwell","Aldous Huxley","Ray Bradbury","Kafka"]'::jsonb, 0, 'edebiyat'),
('"Hayvan Çiftliği" romanının yazarı kimdir?', '["George Orwell","Huxley","Kafka","Camus"]'::jsonb, 0, 'edebiyat'),
('"Dönüşüm" adlı eserinde böceğe dönüşen karakteri anlatan yazar kimdir?', '["Franz Kafka","Albert Camus","Sartre","Hesse"]'::jsonb, 0, 'edebiyat'),
('"İlahi Komedya" kimin eseridir?', '["Dante","Petrarca","Boccaccio","Machiavelli"]'::jsonb, 0, 'edebiyat'),
('"Faust" kimin eseridir?', '["Goethe","Schiller","Nietzsche","Kant"]'::jsonb, 0, 'edebiyat'),
('İlyada ve Odysseia destanlarının yazarı kabul edilen kişi kimdir?', '["Homeros","Hesiodos","Sofokles","Euripides"]'::jsonb, 0, 'edebiyat'),
('Sherlock Holmes karakterini yaratan yazar kimdir?', '["Arthur Conan Doyle","Agatha Christie","Edgar Allan Poe","Raymond Chandler"]'::jsonb, 0, 'edebiyat'),
('Hercule Poirot karakterini yaratan yazar kimdir?', '["Agatha Christie","Conan Doyle","Simenon","Dan Brown"]'::jsonb, 0, 'edebiyat'),
('Harry Potter serisinin yazarı kimdir?', '["J.K. Rowling","Tolkien","C.S. Lewis","Stephenie Meyer"]'::jsonb, 0, 'edebiyat'),
('"Yüzüklerin Efendisi" serisinin yazarı kimdir?', '["Tolkien","Rowling","Martin","Lewis"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında "Beş Hececiler" hangi ölçüyle yazmıştır?', '["Hece ölçüsü","Aruz ölçüsü","Serbest ölçü","Pentametre"]'::jsonb, 0, 'edebiyat'),
('Bir şiirde dize sonlarındaki ses benzerliğine ne denir?', '["Kafiye (uyak)","Redif","Aliterasyon","Nakarat"]'::jsonb, 0, 'edebiyat'),
('Olayları oluş sırasıyla anlatan, kişi-yer-zaman içeren yazı türü hangisidir?', '["Hikaye","Deneme","Makale","Fıkra"]'::jsonb, 0, 'edebiyat'),
('Bir kişinin hayatını kendi kaleminden anlatan tür hangisidir?', '["Otobiyografi","Biyografi","Anı","Günlük"]'::jsonb, 0, 'edebiyat'),
('Sahnede oynanmak için yazılan edebi tür hangisidir?', '["Tiyatro","Roman","Deneme","Destan"]'::jsonb, 0, 'edebiyat'),
('Güldürürken düşündüren tiyatro türü hangisidir?', '["Komedi","Trajedi","Dram","Opera"]'::jsonb, 0, 'edebiyat'),
('Karagöz ve Hacivat hangi geleneksel sanattır?', '["Gölge oyunu","Orta oyunu","Meddahlık","Kukla"]'::jsonb, 0, 'edebiyat'),
('Tek kişilik geleneksel Türk seyirlik anlatı sanatı hangisidir?', '["Meddahlık","Karagöz","Orta oyunu","Köy tiyatrosu"]'::jsonb, 0, 'edebiyat'),
('Mona Lisa tablosunun ressamı kimdir?', '["Leonardo da Vinci","Michelangelo","Rafael","Botticelli"]'::jsonb, 0, 'sanat'),
('Mona Lisa hangi müzede sergilenmektedir?', '["Louvre","British Museum","Prado","Uffizi"]'::jsonb, 0, 'sanat'),
('"Yıldızlı Gece" tablosunun ressamı kimdir?', '["Van Gogh","Monet","Cezanne","Gauguin"]'::jsonb, 0, 'sanat'),
('Kulağını kestiği bilinen ünlü ressam kimdir?', '["Van Gogh","Picasso","Dali","Munch"]'::jsonb, 0, 'sanat'),
('"Guernica" tablosunun ressamı kimdir?', '["Picasso","Dali","Miro","Goya"]'::jsonb, 0, 'sanat'),
('Kübizmin kurucularından sayılan ressam kimdir?', '["Picasso","Van Gogh","Monet","Kandinsky"]'::jsonb, 0, 'sanat'),
('"Çığlık" tablosunun ressamı kimdir?', '["Edvard Munch","Van Gogh","Klimt","Schiele"]'::jsonb, 0, 'sanat'),
('Eriyen saatleriyle ünlü sürrealist ressam kimdir?', '["Salvador Dali","Picasso","Magritte","Miro"]'::jsonb, 0, 'sanat'),
('Sistine Şapeli''nin tavanını boyayan sanatçı kimdir?', '["Michelangelo","Leonardo","Rafael","Donatello"]'::jsonb, 0, 'sanat'),
('Davut (David) heykelinin yontucusu kimdir?', '["Michelangelo","Bernini","Donatello","Rodin"]'::jsonb, 0, 'sanat'),
('"Düşünen Adam" heykelinin sanatçısı kimdir?', '["Rodin","Michelangelo","Bernini","Brancusi"]'::jsonb, 0, 'sanat'),
('"Son Akşam Yemeği" freskinin sanatçısı kimdir?', '["Leonardo da Vinci","Michelangelo","Giotto","Rafael"]'::jsonb, 0, 'sanat'),
('İzlenimcilik (empresyonizm) akımına adını veren "İzlenim: Gündoğumu" tablosu kimindir?', '["Claude Monet","Manet","Renoir","Degas"]'::jsonb, 0, 'sanat'),
('"Nilüferler" serisiyle ünlü ressam kimdir?', '["Monet","Van Gogh","Cezanne","Renoir"]'::jsonb, 0, 'sanat'),
('"Öpücük" tablosuyla ünlü Avusturyalı ressam kimdir?', '["Gustav Klimt","Egon Schiele","Kokoschka","Munch"]'::jsonb, 0, 'sanat'),
('Türkiye''nin en tanınmış ressamlarından "Kaplumbağa Terbiyecisi"nin sahibi kimdir?', '["Osman Hamdi Bey","İbrahim Çallı","Fikret Mualla","Bedri Rahmi"]'::jsonb, 0, 'sanat'),
('Osman Hamdi Bey''in kurduğu müze hangisidir?', '["İstanbul Arkeoloji Müzesi","Topkapı Sarayı","Ayasofya","Dolmabahçe"]'::jsonb, 0, 'sanat'),
('Dokuzuncu Senfoni kimin eseridir?', '["Beethoven","Mozart","Bach","Brahms"]'::jsonb, 0, 'sanat'),
('"Türk Marşı" (Rondo alla Turca) hangi bestecinin eseridir?', '["Mozart","Beethoven","Chopin","Liszt"]'::jsonb, 0, 'sanat'),
('Sağırlığına rağmen bestelerine devam eden besteci kimdir?', '["Beethoven","Bach","Handel","Haydn"]'::jsonb, 0, 'sanat'),
('"Dört Mevsim" konçertolarının bestecisi kimdir?', '["Vivaldi","Bach","Handel","Telemann"]'::jsonb, 0, 'sanat'),
('"Kuğu Gölü" balesinin bestecisi kimdir?', '["Çaykovski","Stravinsky","Prokofiev","Rahmaninov"]'::jsonb, 0, 'sanat'),
('Piyanonun şairi olarak anılan Polonyalı besteci kimdir?', '["Chopin","Liszt","Schumann","Schubert"]'::jsonb, 0, 'sanat'),
('Klasik Batı müziğinde dört telli yaylı çalgı hangisidir?', '["Keman","Gitar","Arp","Ud"]'::jsonb, 0, 'sanat'),
('Senfoni orkestrasını yöneten kişiye ne denir?', '["Şef","Solist","Bestekar","Virtüöz"]'::jsonb, 0, 'sanat'),
('Türk sanat müziğinde kullanılan mızraplı, armudi gövdeli çalgı hangisidir?', '["Ud","Kanun","Ney","Tambur"]'::jsonb, 0, 'sanat'),
('Üflemeli Türk müziği çalgısı hangisidir?', '["Ney","Kanun","Ud","Bağlama"]'::jsonb, 0, 'sanat'),
('Halk müziğimizin temel çalgısı hangisidir?', '["Bağlama","Ud","Kanun","Kemençe"]'::jsonb, 0, 'sanat'),
('Karadeniz yöresiyle özdeşleşen çalgı hangisidir?', '["Kemençe","Bağlama","Zurna","Mey"]'::jsonb, 0, 'sanat'),
('Mehter takımı hangi orduya aittir?', '["Osmanlı","Selçuklu","Roma","Bizans"]'::jsonb, 0, 'sanat'),
('Opera sanatı hangi ülkede doğmuştur?', '["İtalya","Fransa","Almanya","Avusturya"]'::jsonb, 0, 'sanat'),
('Bale sanatı hangi ülkede saray dansı olarak doğmuştur?', '["İtalya","Rusya","Fransa","İngiltere"]'::jsonb, 0, 'sanat'),
('"Sefiller" ve "Notre Dame''ın Kamburu" müzikallerinin geçtiği şehir hangisidir?', '["Paris","Londra","Roma","Viyana"]'::jsonb, 0, 'sanat'),
('Ebru sanatı neyin üzerine yapılır?', '["Su","Kağıt","Cam","Kumaş"]'::jsonb, 0, 'sanat'),
('Hat sanatı neyin sanatıdır?', '["Güzel yazı","Resim","Heykel","Çini"]'::jsonb, 0, 'sanat'),
('İznik neyiyle ünlüdür?', '["Çinileri","Halıları","Kilimler","Gümüş işleme"]'::jsonb, 0, 'sanat'),
('Geleneksel Türk el sanatlarından "telkari" hangi madenle yapılır?', '["Gümüş","Bakır","Demir","Kalay"]'::jsonb, 0, 'sanat'),
('Oscar ödüllerini veren akademi hangi ülkededir?', '["ABD","İngiltere","Fransa","İtalya"]'::jsonb, 0, 'sanat'),
('Cannes Film Festivali hangi ülkede düzenlenir?', '["Fransa","İtalya","ABD","İspanya"]'::jsonb, 0, 'sanat'),
('Altın Portakal Film Festivali hangi şehirde düzenlenir?', '["Antalya","İstanbul","Adana","İzmir"]'::jsonb, 0, 'sanat'),
('"Titanic" ve "Avatar" filmlerinin yönetmeni kimdir?', '["James Cameron","Spielberg","Nolan","Scorsese"]'::jsonb, 0, 'sanat'),
('"Yüzüklerin Efendisi" film üçlemesinin yönetmeni kimdir?', '["Peter Jackson","James Cameron","Ridley Scott","George Lucas"]'::jsonb, 0, 'sanat'),
('Charlie Chaplin hangi dönem sinemasının efsanesidir?', '["Sessiz sinema","Renkli sinema","Korku sineması","Belgesel"]'::jsonb, 0, 'sanat'),
('Türk sinemasının "Sultan"ı olarak anılan oyuncu kimdir?', '["Türkan Şoray","Fatma Girik","Hülya Koçyiğit","Filiz Akın"]'::jsonb, 0, 'sanat'),
('Yeşilçam döneminin ünlü "Turist Ömer" karakterini canlandıran oyuncu kimdir?', '["Sadri Alışık","Kemal Sunal","Ayhan Işık","Öztürk Serengil"]'::jsonb, 0, 'sanat'),
('"Hababam Sınıfı" filmlerinde İnek Şaban karakterini kim canlandırmıştır?', '["Kemal Sunal","Şener Şen","Halit Akçatepe","Tarık Akan"]'::jsonb, 0, 'sanat'),
('Tiyatroda perde arasındaki bölümlere ne ad verilir?', '["Perde","Sahne","Tablo","Epizot"]'::jsonb, 0, 'sanat'),
('Origami hangi ülkenin geleneksel kağıt katlama sanatıdır?', '["Japonya","Çin","Kore","Tayland"]'::jsonb, 0, 'sanat'),
('Flamenko dansı hangi ülkeyle özdeşleşmiştir?', '["İspanya","İtalya","Portekiz","Meksika"]'::jsonb, 0, 'sanat'),
('Tango hangi ülkede doğmuştur?', '["Arjantin","İspanya","Brezilya","Küba"]'::jsonb, 0, 'sanat'),
('Halay hangi kültürün geleneksel dansıdır?', '["Anadolu","Balkan","Kafkas","Orta Asya"]'::jsonb, 0, 'sanat'),
('Horon hangi bölgemizin halk dansıdır?', '["Karadeniz","Ege","Trakya","Akdeniz"]'::jsonb, 0, 'sanat'),
('Zeybek hangi bölgemizin halk dansıdır?', '["Ege","Karadeniz","Doğu Anadolu","İç Anadolu"]'::jsonb, 0, 'sanat'),
('Mevlevilikteki dönerek yapılan ritüel ne olarak bilinir?', '["Sema","Semah","Zikir","Halay"]'::jsonb, 0, 'sanat')
on conflict (soru) do nothing;
