-- Soru havuzu genişletme: cografya +124
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Nevşehir''in Ürgüp ilçesi hangi turizm türüyle öne çıkar?', '["Kültür turizmi","Kış turizmi","Termal turizm","Kongre turizmi"]'::jsonb, 0, 'cografya'),
('Assos antik kenti hangi ilimizdedir?', '["Balıkesir","Çanakkale","İzmir","Edirne"]'::jsonb, 1, 'cografya'),
('Bergama antik kenti hangi ilimizdedir?', '["Manisa","Aydın","İzmir","Balıkesir"]'::jsonb, 2, 'cografya'),
('Afrodisias antik kenti hangi ilimizdedir?', '["Denizli","Muğla","İzmir","Aydın"]'::jsonb, 3, 'cografya'),
('Perge antik kenti hangi ilimizdedir?', '["Antalya","Mersin","Muğla","Isparta"]'::jsonb, 0, 'cografya'),
('Zeugma antik kenti hangi ilimizdedir?', '["Şanlıurfa","Gaziantep","Kilis","Adıyaman"]'::jsonb, 1, 'cografya'),
('Mardin''in Midyat ilçesi hangi el sanatıyla ünlüdür?', '["Halı dokuma","Çini","Telkâri gümüş işçiliği","Bakırcılık"]'::jsonb, 2, 'cografya'),
('Sivas''ın Zara ilçesi hangi nehrin doğduğu bölgededir?', '["Fırat","Sakarya","Dicle","Kızılırmak"]'::jsonb, 3, 'cografya'),
('Erzincan Ovası''nın oluşumunda hangi etken rol oynamıştır?', '["Fay çöküntüsü","Buzul","Volkan","Rüzgâr"]'::jsonb, 0, 'cografya'),
('Bursa''nın İnegöl ilçesi hangi sanayi dalıyla anılır?', '["Tekstil","Mobilya","Otomotiv","Cam"]'::jsonb, 1, 'cografya'),
('Denizli hangi tekstil ürünüyle öne çıkar?', '["Deri ceket","Ayakkabı","Havlu ve bornoz","Halı"]'::jsonb, 2, 'cografya'),
('Gaziantep hangi gıda ürünüyle coğrafi işaret almıştır?', '["Lokum","Pastırma","Helva","Baklava"]'::jsonb, 3, 'cografya'),
('Kayseri hangi et ürünüyle bilinir?', '["Pastırma","Kokoreç","Sucuk dışı hiçbiri","Balık"]'::jsonb, 0, 'cografya'),
('Afyonkarahisar hangi süt ürünüyle anılır?', '["Tulum peyniri","Kaymak","Yoğurt","Ayran"]'::jsonb, 1, 'cografya'),
('Erzincan hangi peynir türüyle bilinir?', '["Kaşar","Lor","Tulum peyniri","Çökelek"]'::jsonb, 2, 'cografya'),
('Rize''nin başlıca tarım ürünü hangisidir?', '["Buğday","Pamuk","Zeytin","Çay"]'::jsonb, 3, 'cografya'),
('Giresun hangi tarım ürünüyle özdeşleşmiştir?', '["Fındık","Çay","Üzüm","İncir"]'::jsonb, 0, 'cografya'),
('Nizip hangi tarım ürünüyle bilinir?', '["Çay","Zeytin","Fındık","Muz"]'::jsonb, 1, 'cografya'),
('Amasya hangi meyvesiyle ünlüdür?', '["Muz","Portakal","Elma","Ananas"]'::jsonb, 2, 'cografya'),
('Mersin''in Anamur ilçesi hangi meyveyle ünlüdür?', '["Kayısı","Elma","Kiraz","Muz"]'::jsonb, 3, 'cografya'),
('Isparta hangi tarım ürünüyle özdeşleşmiştir?', '["Gül","Pamuk","Çay","Fındık"]'::jsonb, 0, 'cografya'),
('Türkiye''de haşhaş ekimi hangi bölgede yoğundur?', '["Doğu Karadeniz","İç Batı Anadolu","Trakya","Güneydoğu Anadolu"]'::jsonb, 1, 'cografya'),
('Tütün üretiminde öne çıkan ilimiz hangisidir?', '["Rize","Bolu","Adıyaman","Sinop"]'::jsonb, 2, 'cografya'),
('Şeker pancarı üretiminde öne çıkan bölgemiz hangisidir?', '["Akdeniz","Doğu Karadeniz","Güneydoğu Anadolu","İç Anadolu"]'::jsonb, 3, 'cografya'),
('Ayçiçeği üretiminde öne çıkan bölgemiz hangisidir?', '["Trakya","Doğu Anadolu","Doğu Karadeniz","Akdeniz"]'::jsonb, 0, 'cografya'),
('Soya ve yer fıstığı hangi bölgemizde daha çok yetiştirilir?', '["Doğu Anadolu","Akdeniz","Karadeniz","İç Anadolu"]'::jsonb, 1, 'cografya'),
('Nohut üretiminde öne çıkan bölgemiz hangisidir?', '["Doğu Karadeniz","Trakya","İç Anadolu","Doğu Anadolu"]'::jsonb, 2, 'cografya'),
('Kivi üretimi Türkiye''de hangi kıyıda yapılır?', '["İç Anadolu","Güneydoğu Anadolu","Doğu Anadolu","Karadeniz"]'::jsonb, 3, 'cografya'),
('Avokado üretimi Türkiye''de hangi kıyıda başlamıştır?', '["Akdeniz","Karadeniz","Marmara","Doğu Anadolu"]'::jsonb, 0, 'cografya'),
('Türkiye''de çeltik tarımının su ihtiyacı neden yüksektir?', '["Kuraklığa dayanması","Sürekli su altında yetişmesi","Serada yetişmesi","Kısa sürede olgunlaşması"]'::jsonb, 1, 'cografya'),
('Türkiye''de ilk kurulan şeker fabrikalarından biri hangi ildedir?', '["Rize","Trabzon","Uşak","Muğla"]'::jsonb, 2, 'cografya'),
('Türkiye''de en fazla sera alanı hangi ilde bulunur?', '["Ankara","Erzurum","Sivas","Antalya"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en büyük hayvan pazarlarından biri hangi ildedir?', '["Kars","Yalova","Bartın","Kilis"]'::jsonb, 0, 'cografya'),
('Van kedisinin ayırt edici özelliği nedir?', '["Kuyruksuz olması","İki farklı renkte göz","Tüysüz olması","Kısa bacaklı olması"]'::jsonb, 1, 'cografya'),
('Kangal köpeği hangi ilimizle özdeşleşmiştir?', '["Konya","Erzurum","Sivas","Van"]'::jsonb, 2, 'cografya'),
('Ankara keçisinin ürünü nedir?', '["Yün","İpek","Deri","Tiftik"]'::jsonb, 3, 'cografya'),
('Türkiye''de arı ürünlerinden çam balı hangi bölgede üretilir?', '["Ege ve Akdeniz","Doğu Anadolu","Trakya","Güneydoğu Anadolu"]'::jsonb, 0, 'cografya'),
('Anzer balı hangi ilimizde üretilir?', '["Ordu","Rize","Muğla","Kars"]'::jsonb, 1, 'cografya'),
('Kültür balıkçılığında en çok yetiştirilen tür hangisidir?', '["Hamsi","Palamut","Levrek ve çipura","Uskumru"]'::jsonb, 2, 'cografya'),
('Türkiye''de alabalık yetiştiriciliği hangi ortamda yapılır?', '["Tuzlu deniz","Acı su gölü","Termal su","Tatlı su"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en büyük termik santrallerinden Afşin-Elbistan hangi yakıtı kullanır?', '["Linyit","Doğal gaz","Fuel oil","Odun"]'::jsonb, 0, 'cografya'),
('Soma hangi ilimizin ilçesidir?', '["İzmir","Manisa","Balıkesir","Kütahya"]'::jsonb, 1, 'cografya'),
('Türkiye''de doğal gaz depolama tesisi bulunan Tuz Gölü hangi yöntemi kullanır?', '["Yüzey tankı","Deniz altı boru","Yer altı tuz kubbesi","Buz depolama"]'::jsonb, 2, 'cografya'),
('Rüzgâr santrallerinin verimli olması için gereken temel koşul nedir?', '["Yüksek sıcaklık","Bol yağış","Düz arazi","Sürekli ve düzenli rüzgâr"]'::jsonb, 3, 'cografya'),
('Güneş panellerinin verimini en çok ne etkiler?', '["Işınım süresi ve açısı","Rüzgâr hızı","Nem oranı","Toprak türü"]'::jsonb, 0, 'cografya'),
('Biyokütle enerjisi neyden elde edilir?', '["Kömürden","Organik atıklardan","Uranyumdan","Rüzgârdan"]'::jsonb, 1, 'cografya'),
('Dalga enerjisi hangi doğal kaynağa dayanır?', '["Yeraltı ısısına","Güneşe doğrudan","Deniz hareketine","Rüzgâra doğrudan"]'::jsonb, 2, 'cografya'),
('Enerji verimliliği kavramı neyi hedefler?', '["Daha çok enerji üretmeyi","Fiyatı artırmayı","Tüketimi artırmayı","Aynı işi daha az enerjiyle yapmayı"]'::jsonb, 3, 'cografya'),
('Bir ülkenin enerjide dışa bağımlılığı neyi gösterir?', '["İthal kaynak oranının yüksekliğini","Üretim fazlasını","İhracat gücünü","Rezerv zenginliğini"]'::jsonb, 0, 'cografya'),
('Bir bölgede sanayi kirliliğinin en yaygın göstergesi nedir?', '["Nüfus artışı","Hava ve su kirliliği","Yol yapımı","Ağaçlandırma"]'::jsonb, 1, 'cografya'),
('Arıtma tesislerinin işlevi nedir?', '["İçme suyu üretmek yalnızca","Hava filtrelemek","Atık suyu temizlemek","Toprak sürmek"]'::jsonb, 2, 'cografya'),
('Katı atık düzenli depolama alanının amacı nedir?', '["Atığı yakmak","Atığı denize dökmek","Atığı gömmemek","Çevreye sızıntıyı engellemek"]'::jsonb, 3, 'cografya'),
('Kompostlaştırma hangi atık türüne uygulanır?', '["Organik atıklara","Metal atıklara","Cam atıklara","Pil atıklarına"]'::jsonb, 0, 'cografya'),
('Sıfır atık yaklaşımının temel ilkesi nedir?', '["Atığı yakmak","Atığı kaynağında azaltmak","Atığı gömmek","Atığı ihraç etmek"]'::jsonb, 1, 'cografya'),
('İklim kuşaklarının oluşmasının temel nedeni nedir?', '["Yer şekilleri","Bitki örtüsü","Güneş ışınlarının geliş açısı","Nüfus dağılışı"]'::jsonb, 2, 'cografya'),
('Tropikal kuşak hangi enlemler arasındadır?', '["Kutup daireleri arası","45-60 enlemleri","Yalnız ekvator","Dönenceler arası"]'::jsonb, 3, 'cografya'),
('Orta kuşak hangi enlemler arasında yer alır?', '["Dönence ile kutup dairesi arası","Ekvator ile dönence arası","Kutup dairesi ile kutup arası","Yalnız 45. paralel"]'::jsonb, 0, 'cografya'),
('Kutup kuşağında yıllık sıcaklık nasıldır?', '["Sürekli yüksek","Sürekli düşük","Çok değişken","Ilıman"]'::jsonb, 1, 'cografya'),
('Yükselti kuşaklanması dağlarda neyi taklit eder?', '["Boylam farkını","Gelgit döngüsünü","Enlem kuşaklarını","Mevsim geçişini"]'::jsonb, 2, 'cografya'),
('Bir yerin denizden yüksekliğine ne ad verilir?', '["Enlem","Boylam","Eğim","Rakım"]'::jsonb, 3, 'cografya'),
('Rölyef (yer şekli) terimi neyi ifade eder?', '["Yüzeyin engebe durumunu","İklim tipini","Toprak rengini","Nüfus sayısını"]'::jsonb, 0, 'cografya'),
('Plato nedir?', '["Alçak ova","Akarsularla yarılmış yüksek düzlük","Dağ zirvesi","Kıyı bataklığı"]'::jsonb, 1, 'cografya'),
('Türkiye''de Cihanbeyli Platosu hangi bölgededir?', '["Ege","Marmara","İç Anadolu","Akdeniz"]'::jsonb, 2, 'cografya'),
('Haymana Platosu hangi ilimizin çevresindedir?', '["Konya","Kayseri","Eskişehir","Ankara"]'::jsonb, 3, 'cografya'),
('Erzurum-Kars Platosu''nun yüksekliği neyi etkiler?', '["Kışların sert geçmesini","Yağışın artmasını","Denizelliği","Bitki çeşitliliğini"]'::jsonb, 0, 'cografya'),
('Taşeli Platosu hangi bölgemizde yer alır?', '["Karadeniz","Akdeniz","Marmara","Doğu Anadolu"]'::jsonb, 1, 'cografya'),
('Obruk Platosu hangi jeolojik özelliğiyle bilinir?', '["Volkanik koniler","Buzul vadileri","Karstik çukurlar","Kum tepeleri"]'::jsonb, 2, 'cografya'),
('Bir dağın zirvesi ile eteği arasındaki fark neyi belirtir?', '["Mutlak yüksekliği","Enlemi","Eğimi","Bağıl (göreceli) yüksekliği"]'::jsonb, 3, 'cografya'),
('Mutlak yükseklik neye göre ölçülür?', '["Deniz seviyesine göre","Dağ eteğine göre","Ekvatora göre","Kutba göre"]'::jsonb, 0, 'cografya'),
('Dağ oluşumuna (orojenez) örnek hangi süreçtir?', '["Akarsu aşındırması","Levhaların çarpışması","Buzul erimesi","Rüzgâr birikimi"]'::jsonb, 1, 'cografya'),
('Epirojenez neyi ifade eder?', '["Dağ oluşumu","Volkan patlaması","Kıtaların alçalıp yükselmesi","Deprem"]'::jsonb, 2, 'cografya'),
('Kıvrım dağlarının oluşumunda hangi kuvvet etkilidir?', '["Dikey gerilme","Buzul basıncı","Rüzgâr aşındırması","Yanal sıkışma"]'::jsonb, 3, 'cografya'),
('Antiklinal ve senklinal terimleri neyi anlatır?', '["Kıvrımın tepe ve çukurunu","Fayın iki yanını","Volkan konisini","Delta kollarını"]'::jsonb, 0, 'cografya'),
('Horst ve graben hangi süreçle oluşur?', '["Kıvrılma","Kırılma (faylanma)","Buzullaşma","Karstlaşma"]'::jsonb, 1, 'cografya'),
('Türkiye''de graben ovalarına örnek hangisidir?', '["Konya Ovası","Erzurum Ovası","Gediz Ovası","Bafra Ovası"]'::jsonb, 2, 'cografya'),
('Kırık (fay) hatlarının depremle ilişkisi nedir?', '["Faylar depremi engeller","İlgisizdirler","Faylar yalnız volkan yapar","Depremler genelde faylarda olur"]'::jsonb, 3, 'cografya'),
('Diri fay ne demektir?', '["Yakın jeolojik dönemde hareket etmiş fay","Hiç hareket etmemiş fay","Volkanik boru","Buzul çatlağı"]'::jsonb, 0, 'cografya'),
('Depremin büyüklüğü hangi ölçekle ifade edilir?', '["Mercalli ölçeği","Moment büyüklük ölçeği","Beaufort ölçeği","Richter dışı hiçbiri"]'::jsonb, 1, 'cografya'),
('Depremde en çok hasarın nedeni nedir?', '["Yağmurun şiddeti","Rüzgârın hızı","Yapıların dayanıksız olması","Sıcaklık artışı"]'::jsonb, 2, 'cografya'),
('Zemin sıvılaşması hangi zeminlerde görülür?', '["Kayalık zeminlerde","Donmuş zeminlerde","Kuru killi zeminlerde","Suya doygun kum zeminlerde"]'::jsonb, 3, 'cografya'),
('Deprem sonrası artçı sarsıntılar neyi gösterir?', '["Fayın enerji boşaltmayı sürdürdüğünü","Yeni bir fay oluştuğunu","Depremin bittiğini","Volkanın patlayacağını"]'::jsonb, 0, 'cografya'),
('Türkiye''de yapı denetiminin amacı nedir?', '["Kira artışı","Depreme dayanıklı yapılaşma","Nüfus planlaması","Arsa satışı"]'::jsonb, 1, 'cografya'),
('Volkanik püskürmede çıkan kül bulutu havacılığı nasıl etkiler?', '["Hızlandırır","Etkilemez","Uçuşları durdurabilir","Yakıt tasarrufu sağlar"]'::jsonb, 2, 'cografya'),
('Gayzer nedir?', '["Sürekli soğuk pınar","Volkan konisi","Buzul çatlağı","Aralıklı sıcak su fışkırması"]'::jsonb, 3, 'cografya'),
('Gayzerleriyle tanınan ülke hangisidir?', '["İzlanda","Mısır","Hindistan","Portekiz"]'::jsonb, 0, 'cografya'),
('Yeraltı suyunun beslenmesi öncelikle neyle olur?', '["Deniz suyuyla","Yağış sızmasıyla","Rüzgârla","Buharlaşmayla"]'::jsonb, 1, 'cografya'),
('Geçirimsiz tabakanın yeraltı suyundaki rolü nedir?', '["Suyu buharlaştırmak","Suyu tuzlandırmak","Suyun birikmesini sağlamak","Suyu ısıtmak"]'::jsonb, 2, 'cografya'),
('Tatlı su kaynaklarının dünyadaki en büyük deposu nedir?', '["Göller","Akarsular","Atmosfer","Buzullar"]'::jsonb, 3, 'cografya'),
('Su döngüsünde buharlaşmanın kaynağı temel olarak nedir?', '["Güneş enerjisi","Rüzgâr","Yerçekimi","Yeraltı ısısı"]'::jsonb, 0, 'cografya'),
('Terleme (transpirasyon) hangi canlılarla ilgilidir?', '["Balıklarla","Bitkilerle","Kuşlarla","Böceklerle"]'::jsonb, 1, 'cografya'),
('Havzalar arası su transferi hangi amaçla yapılır?', '["Enerji üretmek yalnızca","Balık taşımak","Su açığını kapatmak","Turizm için"]'::jsonb, 2, 'cografya'),
('Kuraklık ile çölleşme arasındaki fark nedir?', '["Kuraklığın kalıcı olması","İkisinin aynı olması","Çölleşmenin geçici olması","Çölleşmenin kalıcı bozulma olması"]'::jsonb, 3, 'cografya'),
('Su stresi kavramı neyi ifade eder?', '["Kişi başına düşen suyun azlığını","Yağışın fazlalığını","Baraj sayısını","Nehir uzunluğunu"]'::jsonb, 0, 'cografya'),
('Türkiye su kaynakları bakımından nasıl tanımlanır?', '["Su zengini ülke","Su azlığı yaşayan ülke","Su fazlası olan ülke","Susuz ülke"]'::jsonb, 1, 'cografya'),
('Sulama suyunda tuzluluk artarsa ne olur?', '["Verim artar","Toprak zenginleşir","Bitki gelişimi engellenir","Su tasarrufu olur"]'::jsonb, 2, 'cografya'),
('Bir gölün kapalı havzada olması ne anlama gelir?', '["Suyunun tatlı olması","Derin olması","Buz tutması","Suyunun denize ulaşmaması"]'::jsonb, 3, 'cografya'),
('Kapalı havza göllerinin suyu genellikle nasıldır?', '["Tuzlu veya acı","Her zaman tatlı","Donmuş","Renksiz"]'::jsonb, 0, 'cografya'),
('Türkiye''de en büyük kapalı havza hangisidir?', '["Fırat Havzası","Konya Kapalı Havzası","Sakarya Havzası","Meriç Havzası"]'::jsonb, 1, 'cografya'),
('Akarsu havzası kavramı neyi kapsar?', '["Yalnız yatağını","Yalnız ağzını","Bir akarsuyu besleyen tüm alanı","Yalnız kaynağını"]'::jsonb, 2, 'cografya'),
('Bir akarsuyun kaynak bölgesinde aşındırma nasıldır?', '["Yana doğru güçlüdür","Hiç yoktur","Birikimden azdır","Derine doğru güçlüdür"]'::jsonb, 3, 'cografya'),
('Akarsuyun ağız kısmında hangi süreç baskındır?', '["Birikim","Derine aşındırma","Buzul aşındırma","Rüzgâr taşıma"]'::jsonb, 0, 'cografya'),
('Peneplen (yontukdüz) nedir?', '["Yeni oluşan dağ","Aşınarak düzleşmiş eski arazi","Volkanik plato","Buzul vadisi"]'::jsonb, 1, 'cografya'),
('Kanyon vadi hangi koşulda oluşur?', '["Deltada birikimle","Buzul erimesiyle","Kalker arazide derine aşındırmayla","Rüzgâr taşımasıyla"]'::jsonb, 2, 'cografya'),
('Tektonik göl nasıl oluşur?', '["Volkan kraterinin dolmasıyla","Buzul çukurunun dolmasıyla","Kıyı setinin kapatmasıyla","Çöküntü alanının suyla dolmasıyla"]'::jsonb, 3, 'cografya'),
('Set gölü nasıl oluşur?', '["Vadinin bir engelle kapanmasıyla","Fay çöküntüsüyle","Krater oluşumuyla","Karst erimesiyle"]'::jsonb, 0, 'cografya'),
('Türkiye''de heyelan set gölüne örnek hangisidir?', '["Van Gölü","Tortum Gölü","Tuz Gölü","Manyas Gölü"]'::jsonb, 1, 'cografya'),
('Tortum Şelalesi hangi ilimizdedir?', '["Erzincan","Artvin","Erzurum","Bayburt"]'::jsonb, 2, 'cografya'),
('Kurşunlu Şelalesi hangi ilimizdedir?', '["Denizli","Muğla","Aydın","Antalya"]'::jsonb, 3, 'cografya'),
('Muradiye Şelalesi hangi ilimizdedir?', '["Van","Bitlis","Muş","Hakkari"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en çok ada barındıran denizi hangisidir?', '["Karadeniz","Ege","Akdeniz","Marmara"]'::jsonb, 1, 'cografya'),
('İmroz Adası''nın Türkçe adı nedir?', '["Bozcaada","Avşa","Gökçeada","Marmara Adası"]'::jsonb, 2, 'cografya'),
('Kıbrıs Akdeniz''in kaçıncı büyük adasıdır?', '["Birinci","Beşinci","Yedinci","Üçüncü"]'::jsonb, 3, 'cografya'),
('Akdeniz''in en büyük adası hangisidir?', '["Sicilya","Sardunya","Kıbrıs","Girit"]'::jsonb, 0, 'cografya'),
('Ege Denizi''ndeki adaların çokluğu neyle açıklanır?', '["Volkanik püskürmelerle","Kıyı dağlarının sular altında kalmasıyla","Buzul çekilmesiyle","Mercan oluşumuyla"]'::jsonb, 1, 'cografya'),
('Santorini Adası hangi jeolojik olayla şekillenmiştir?', '["Buzul aşındırması","Deprem çöküntüsü","Büyük volkanik patlama","Mercan birikimi"]'::jsonb, 2, 'cografya'),
('Bir kıyının turizme uygunluğunu belirleyen temel etken nedir?', '["Nüfus yoğunluğu","Maden varlığı","Sanayi tesisi","İklim ve kıyı yapısı"]'::jsonb, 3, 'cografya'),
('Türkiye''de mavi bayrak uygulaması neyi belgeler?', '["Plaj ve deniz temizliğini","Otel yıldızını","Ulaşım kalitesini","Nüfus sayısını"]'::jsonb, 0, 'cografya'),
('Kruvaziyer turizmi hangi ulaşımla ilişkilidir?', '["Demiryolu","Deniz yolu","Hava yolu","Karayolu"]'::jsonb, 1, 'cografya'),
('İnanç turizmi hangi kaynağa dayanır?', '["Kayak pistlerine","Termal sulara","Dinî mekânlara","Fuarlara"]'::jsonb, 2, 'cografya'),
('Kongre turizminin gerektirdiği temel altyapı nedir?', '["Kayak pisti","Plaj","Mağara","Büyük toplantı salonları ve konaklama"]'::jsonb, 3, 'cografya'),
('Sağlık turizmi neyi kapsar?', '["Tedavi amaçlı seyahatleri","Kış sporlarını","Fuar gezilerini","Doğa yürüyüşünü"]'::jsonb, 0, 'cografya'),
('Turizmin bir bölgeye olumsuz etkisi ne olabilir?', '["İstihdam artışı","Doğal alanların tahribi","Döviz girdisi","Altyapı gelişimi"]'::jsonb, 1, 'cografya'),
('Turizmde mevsimlik yoğunlaşmanın sonucu nedir?', '["Gelirin sabitlenmesi","Nüfusun azalması","İstihdamın süreksiz olması","Altyapının bozulmaması"]'::jsonb, 2, 'cografya'),
('Bir ülkenin turizm gelirinin artması dış ticarette neye katkı yapar?', '["İthalata","Vergi indirimine","Gümrük artışına","Döviz gelirine"]'::jsonb, 3, 'cografya')
on conflict (soru) do nothing;
