-- Soru havuzu genişletme: cografya +49
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Küba''nın başkenti hangisidir?', '["Havana","Santiago","Kingston","Santo Domingo"]'::jsonb, 0, 'cografya'),
('Jamaika''nın başkenti hangisidir?', '["Havana","Kingston","Nassau","Port-au-Prince"]'::jsonb, 1, 'cografya'),
('Panama''nın başkenti hangisidir?', '["San Jose","Managua","Panama City","Tegucigalpa"]'::jsonb, 2, 'cografya'),
('Kosta Rika''nın başkenti hangisidir?', '["Managua","Panama City","San Salvador","San Jose"]'::jsonb, 3, 'cografya'),
('Guatemala hangi kıtada yer alır?', '["Kuzey Amerika","Güney Amerika","Afrika","Asya"]'::jsonb, 0, 'cografya'),
('Venezuela hangi denize kıyıdır?', '["Akdeniz","Karayip Denizi","Baltık Denizi","Kızıldeniz"]'::jsonb, 1, 'cografya'),
('Paraguay''ın coğrafi özelliği nedir?', '["Ada ülkesi olması","Uzun kıyısı olması","Denize kıyısı olmaması","Kutupta olması"]'::jsonb, 2, 'cografya'),
('Ekvador ülkesinin adı neyle ilişkilidir?', '["Dağ adıyla","Nehir adıyla","Kaşif adıyla","Ekvator çizgisiyle"]'::jsonb, 3, 'cografya'),
('Surinam ve Guyana hangi kıtadadır?', '["Güney Amerika","Afrika","Asya","Okyanusya"]'::jsonb, 0, 'cografya'),
('Senegal''in başkenti hangisidir?', '["Bamako","Dakar","Konakri","Abidjan"]'::jsonb, 1, 'cografya'),
('Gana''nın başkenti hangisidir?', '["Lagos","Abidjan","Akra","Lome"]'::jsonb, 2, 'cografya'),
('Uganda''nın başkenti hangisidir?', '["Nairobi","Kigali","Dodoma","Kampala"]'::jsonb, 3, 'cografya'),
('Ruanda''nın başkenti hangisidir?', '["Kigali","Kampala","Bujumbura","Nairobi"]'::jsonb, 0, 'cografya'),
('Zambiya ve Zimbabve arasındaki doğal sınır nedir?', '["Nil","Zambezi Nehri","Kongo","Nijer"]'::jsonb, 1, 'cografya'),
('Botsvana''nın büyük bölümünü kaplayan doğal ortam nedir?', '["Yağmur ormanı","Buzul","Kalahari","Tundra"]'::jsonb, 2, 'cografya'),
('Sudan ve Güney Sudan''ı ayıran temel etken ne olmuştur?', '["Deniz","Dağ sırası","Buzul","Siyasi ayrılık"]'::jsonb, 3, 'cografya'),
('Libya''nın yüzölçümünün büyük bölümü hangi ortamdır?', '["Çöl","Orman","Bataklık","Buzul"]'::jsonb, 0, 'cografya'),
('Moritanya hangi çölün etkisindedir?', '["Gobi","Sahra","Kalahari","Atacama"]'::jsonb, 1, 'cografya'),
('Somali''nin kıyısı hangi denize açılır?', '["Atlas Okyanusu","Akdeniz","Hint Okyanusu","Baltık"]'::jsonb, 2, 'cografya'),
('Yemen hangi boğaza kıyıdır?', '["Hürmüz","Malakka","Cebelitarık","Bab-ül Mendeb"]'::jsonb, 3, 'cografya'),
('Bahreyn coğrafi olarak nasıl bir ülkedir?', '["Ada ülkesi","Karayla çevrili","Yarımada","Kıta ülkesi"]'::jsonb, 0, 'cografya'),
('Kuveyt hangi körfeze kıyıdır?', '["Aden Körfezi","Basra Körfezi","Umman Körfezi dışı hiçbiri","Akabe Körfezi"]'::jsonb, 1, 'cografya'),
('Ürdün''ün denize açılan tek limanı nerededir?', '["Amman","İrbid","Akabe","Zerka"]'::jsonb, 2, 'cografya'),
('Lübnan''ın coğrafi özelliği nedir?', '["Çöl ülkesi","Ada ülkesi","Karayla çevrili","Dağlık ve Akdeniz kıyılı olması"]'::jsonb, 3, 'cografya'),
('Kıbrıs''ın en yüksek dağı hangisidir?', '["Trodos","Beşparmak","Toros","Olimpos dışı hiçbiri"]'::jsonb, 0, 'cografya'),
('Malta hangi denizde yer alır?', '["Ege","Akdeniz","Karadeniz","Baltık"]'::jsonb, 1, 'cografya'),
('Andorra hangi iki ülke arasındadır?', '["İtalya ve İsviçre","Almanya ve Avusturya","İspanya ve Fransa","Portekiz ve İspanya"]'::jsonb, 2, 'cografya'),
('San Marino hangi ülkenin içinde yer alır?', '["İspanya","Fransa","İsviçre","İtalya"]'::jsonb, 3, 'cografya'),
('Lihtenştayn hangi iki ülke arasındadır?', '["İsviçre ve Avusturya","Almanya ve Fransa","İtalya ve Slovenya","Çekya ve Polonya"]'::jsonb, 0, 'cografya'),
('Lüksemburg''un coğrafi özelliği nedir?', '["Ada ülkesi olması","Denize kıyısı olmaması","Uzun kıyısı olması","Çöl olması"]'::jsonb, 1, 'cografya'),
('Kuzey Denizi ile Baltık''ı bağlayan kanal hangi ülkededir?', '["Danimarka","Polonya","Almanya","Hollanda"]'::jsonb, 2, 'cografya'),
('İsveç ile Danimarka''yı bağlayan yapı nedir?', '["Manş Tüneli","Bosphorus Köprüsü","Golden Gate","Öresund Köprüsü"]'::jsonb, 3, 'cografya'),
('Manş Tüneli hangi iki ülkeyi bağlar?', '["İngiltere ve Fransa","İrlanda ve İngiltere","Danimarka ve İsveç","İtalya ve Fransa"]'::jsonb, 0, 'cografya'),
('İskoçya''nın en büyük kenti hangisidir?', '["Edinburgh","Glasgow","Aberdeen","Dundee"]'::jsonb, 1, 'cografya'),
('Galler''in başkenti hangisidir?', '["Swansea","Newport","Cardiff","Bangor"]'::jsonb, 2, 'cografya'),
('Kuzey İrlanda''nın merkezi hangisidir?', '["Dublin","Cork","Derry","Belfast"]'::jsonb, 3, 'cografya'),
('Sicilya ile İtalya anakarası arasındaki boğaz hangisidir?', '["Messina","Otranto","Gibraltar","Bonifacio"]'::jsonb, 0, 'cografya'),
('Korsika ile Sardunya arasındaki boğaz hangisidir?', '["Messina","Bonifacio","Otranto","Dardanel"]'::jsonb, 1, 'cografya'),
('Adriyatik''i İyon Denizi''ne bağlayan boğaz hangisidir?', '["Messina","Cebelitarık","Otranto","Bonifacio"]'::jsonb, 2, 'cografya'),
('Sri Lanka ile Hindistan arasındaki dar deniz alanı nasıl anılır?', '["Malakka","Sunda","Torres","Palk Boğazı"]'::jsonb, 3, 'cografya'),
('Java ile Sumatra arasındaki boğaz hangisidir?', '["Sunda","Malakka","Torres","Bering"]'::jsonb, 0, 'cografya'),
('Avustralya ile Yeni Gine arasındaki boğaz hangisidir?', '["Bass","Torres","Cook","Sunda"]'::jsonb, 1, 'cografya'),
('Avustralya ile Tazmanya arasındaki boğaz hangisidir?', '["Torres","Cook","Bass","Palk"]'::jsonb, 2, 'cografya'),
('Yeni Zelanda''nın iki adası arasındaki boğaz hangisidir?', '["Bass","Torres","Sunda","Cook"]'::jsonb, 3, 'cografya'),
('Güney Amerika''nın güney ucundaki boğaz hangisidir?', '["Macellan Boğazı","Drake dışı hiçbiri","Bering","Torres"]'::jsonb, 0, 'cografya'),
('Kuzey Amerika ile Güney Amerika''yı ayıran kanal hangisidir?', '["Süveyş","Panama Kanalı","Kiel","Korint"]'::jsonb, 1, 'cografya'),
('Korint Kanalı hangi ülkededir?', '["İtalya","Mısır","Yunanistan","Türkiye"]'::jsonb, 2, 'cografya'),
('Kiel Kanalı hangi ülkededir?', '["Hollanda","Danimarka","Polonya","Almanya"]'::jsonb, 3, 'cografya'),
('Volga-Don Kanalı hangi iki suyu bağlar?', '["Hazar ve Karadeniz havzalarını","Baltık ve Kuzey Denizi","Akdeniz ve Kızıldeniz","Ege ve Marmara"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
