-- Soru havuzu genişletme: cografya +60
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Dünyada en çok konuşulan dil ailelerinden biri hangisidir?', '["Hint-Avrupa","Ural-Altay dışı hiçbiri","Bantu","Eskimo-Aleut"]'::jsonb, 0, 'cografya'),
('Türkçe hangi dil ailesinde sınıflandırılır?', '["Hint-Avrupa","Ural-Altay","Sami","Bantu"]'::jsonb, 1, 'cografya'),
('Arapça ve İbranice hangi dil grubundandır?', '["Hint-Avrupa","Ural-Altay","Sami dilleri","Bantu"]'::jsonb, 2, 'cografya'),
('İspanyolcanın Latin Amerika''da yaygın olmasının nedeni nedir?', '["İklim","Göç yolları","Ticaret yolları","Sömürge geçmişi"]'::jsonb, 3, 'cografya'),
('Brezilya''da Portekizce konuşulmasının nedeni nedir?', '["Portekiz sömürge geçmişi","İspanyol sömürgesi","Fransız etkisi","Yerli dil"]'::jsonb, 0, 'cografya'),
('Fransızcanın Batı Afrika''da yaygın olmasının nedeni nedir?', '["İklim benzerliği","Fransız sömürge dönemi","Ticaret yolları","Göç"]'::jsonb, 1, 'cografya'),
('İngilizcenin dünya çapında yaygınlaşmasının başlıca nedeni nedir?', '["Kolay öğrenilmesi","Alfabesi","Sömürgecilik ve ekonomik etki","Nüfusu"]'::jsonb, 2, 'cografya'),
('Bir bölgede iki dilin birlikte kullanılmasına ne denir?', '["Lehçe","Ağız","Argo","İki dillilik"]'::jsonb, 3, 'cografya'),
('Lehçe ile ağız arasındaki fark nedir?', '["Lehçenin daha büyük ayrışma göstermesi","Ağzın yazılı olması","İkisinin aynı olması","Lehçenin yazısız olması"]'::jsonb, 0, 'cografya'),
('Dünya dillerinin kaybolmasının başlıca nedeni nedir?', '["İklim değişikliği","Baskın dile geçiş ve kuşak kopukluğu","Deprem","Ulaşım"]'::jsonb, 1, 'cografya'),
('Dünyada nüfusça en yaygın dinlerden biri hangisidir?', '["Şintoizm","Sihizm","Hristiyanlık","Caynizm"]'::jsonb, 2, 'cografya'),
('Hinduizm ağırlıklı olarak hangi ülkede yaygındır?', '["Japonya","Endonezya","Mısır","Hindistan"]'::jsonb, 3, 'cografya'),
('Budizm hangi bölgede yaygındır?', '["Doğu ve Güneydoğu Asya","Kuzey Afrika","Güney Amerika","Kuzey Avrupa"]'::jsonb, 0, 'cografya'),
('Şintoizm hangi ülkeyle özdeşleşmiştir?', '["Kore","Japonya","Çin","Vietnam"]'::jsonb, 1, 'cografya'),
('Kudüs hangi dinler için kutsal sayılır?', '["Yalnız bir din","Yalnız iki din","Üç semavi din için","Hiçbiri"]'::jsonb, 2, 'cografya'),
('Hac ibadeti hangi şehre yapılır?', '["Medine","Kudüs","Şam","Mekke"]'::jsonb, 3, 'cografya'),
('Vatikan hangi dinin merkezidir?', '["Katoliklik","Ortodoksluk","Protestanlık","Anglikanlık"]'::jsonb, 0, 'cografya'),
('Kültür bölgesi kavramı neyi ifade eder?', '["Aynı iklimli alanı","Ortak kültürel özellik gösteren alanı","Aynı toprak türünü","Aynı yüksekliği"]'::jsonb, 1, 'cografya'),
('Kültürel yayılma (difüzyon) ne demektir?', '["Kültürün yok olması","Nüfusun artması","Kültür öğelerinin başka alanlara geçmesi","İklimin değişmesi"]'::jsonb, 2, 'cografya'),
('Kültürel asimilasyon neyi anlatır?', '["Kültürlerin ayrışması","Göçün durması","Dilin korunması","Bir grubun baskın kültüre karışması"]'::jsonb, 3, 'cografya'),
('Çok kültürlülük kavramı neyi savunur?', '["Farklı kültürlerin bir arada yaşamasını","Tek kültür dayatmasını","Göçün yasaklanmasını","Dil birliğini"]'::jsonb, 0, 'cografya'),
('Kültürel miras kavramı neyi kapsar?', '["Yalnız binaları","Somut ve somut olmayan değerleri","Yalnız müzeleri","Yalnız kitapları"]'::jsonb, 1, 'cografya'),
('Somut olmayan kültürel mirasa örnek nedir?', '["Cami binası","Antik kent","Gelenek, el sanatı ve müzik","Kale"]'::jsonb, 2, 'cografya'),
('Göç kuramlarında ''itici faktör'' neyi anlatır?', '["Hedefteki cazibeyi","Yol mesafesini","Ulaşım maliyetini","Kaynak bölgedeki olumsuz koşulları"]'::jsonb, 3, 'cografya'),
('Göçte ''çekici faktör'' nedir?', '["Hedef bölgedeki olanaklar","Kaynaktaki işsizlik","Savaş","Kuraklık"]'::jsonb, 0, 'cografya'),
('Zincirleme göç ne demektir?', '["Toplu sürgün","Önce gidenlerin yakınlarını çekmesi","Mevsimlik dönüş","Rastgele göç"]'::jsonb, 1, 'cografya'),
('Kentten kıra göç (karşı göç) neden yaşanır?', '["İş bulma zorunluluğu","Eğitim zorunluluğu","Yaşam kalitesi ve maliyet arayışı","Sanayi çekimi"]'::jsonb, 2, 'cografya'),
('Göçün kaynak bölgeye etkisi ne olabilir?', '["Nüfusun artması","İş gücünün artması","Kentleşmenin artması","Genç nüfusun azalması"]'::jsonb, 3, 'cografya'),
('İnsani Gelişme Endeksi hangi bileşenleri içerir?', '["Sağlık, eğitim ve gelir","Nüfus, alan, iklim","Ordu, sanayi, tarım","Turizm, ticaret, maden"]'::jsonb, 0, 'cografya'),
('Kişi başına gelirin yanıltıcı olabilmesinin nedeni nedir?', '["Nüfusu göstermemesi","Gelir dağılımını göstermemesi","Alanı göstermemesi","İklimi göstermemesi"]'::jsonb, 1, 'cografya'),
('Gini katsayısı neyi ölçer?', '["Nüfus yoğunluğunu","Enflasyonu","Gelir dağılımındaki eşitsizliği","İhracatı"]'::jsonb, 2, 'cografya'),
('Okuryazarlık oranı hangi göstergeye girer?', '["Sağlık göstergesine","Gelir göstergesine","Ulaşım göstergesine","Eğitim düzeyi göstergesine"]'::jsonb, 3, 'cografya'),
('Bebek ölüm hızı hangi alanı yansıtır?', '["Sağlık ve refah düzeyini","Eğitim düzeyini yalnızca","İhracatı","Ulaşımı"]'::jsonb, 0, 'cografya'),
('Gelişmiş ülkelerde tarımın milli gelirdeki payı nasıldır?', '["Çok yüksektir","Düşüktür","Yarıdan fazladır","Tamamıdır"]'::jsonb, 1, 'cografya'),
('Az gelişmiş ülkelerde ihracatın yapısı genelde nasıldır?', '["Yüksek teknoloji ağırlıklı","Hizmet ağırlıklı","Ham madde ağırlıklı","Yazılım ağırlıklı"]'::jsonb, 2, 'cografya'),
('Sanayileşmekte olan ülkelerin ortak özelliği nedir?', '["Nüfusun azalması","Tarımın büyümesi","Kentlerin küçülmesi","Kentleşme ve göçün hızlanması"]'::jsonb, 3, 'cografya'),
('Bir ülkenin dışa bağımlılığını azaltmanın yolu nedir?', '["Üretim çeşitliliği ve teknoloji","İthalat artışı","İhracat yasağı","Nüfus artışı"]'::jsonb, 0, 'cografya'),
('Bölgesel kalkınma ajanslarının amacı nedir?', '["Vergi toplamak","Bölgeler arası farkı azaltmak","Nüfus saymak","Yol yapmak"]'::jsonb, 1, 'cografya'),
('Teşvik bölgesi uygulaması neyi hedefler?', '["Gelişmiş bölgeyi büyütmek","Vergi artırmak","Geri kalmış bölgelere yatırım çekmek","Göçü artırmak"]'::jsonb, 2, 'cografya'),
('Siyasi coğrafyada ''devletin unsurları'' nelerdir?', '["Ordu, bayrak, marş","Kent, köy, kasaba","Dil, din, tarih","Ülke, halk ve egemenlik"]'::jsonb, 3, 'cografya'),
('Üniter devlet yapısının özelliği nedir?', '["Tek merkezden yönetim","Eyaletlere bölünme","Çok başkentlilik","Konfederasyon"]'::jsonb, 0, 'cografya'),
('Federal devlet yapısının özelliği nedir?', '["Tek merkezli olması","Eyaletlerin kendi yetkilerinin olması","Yönetimsiz olması","Sınırsız olması"]'::jsonb, 1, 'cografya'),
('Konfederasyon ne anlama gelir?', '["Tek devlet","Sömürge","Bağımsız devletlerin gevşek birliği","İl yönetimi"]'::jsonb, 2, 'cografya'),
('Uluslararası örgütlere üyeliğin ülkeye katkısı nedir?', '["Egemenlik kaybı zorunlu","Nüfus artışı","Toprak artışı","İşbirliği ve temsil gücü"]'::jsonb, 3, 'cografya'),
('Sınır aşan sular sorununun temel nedeni nedir?', '["Nehirlerin birden çok ülkeden geçmesi","Denizlerin paylaşımı","Buzul erimesi","Yağış azlığı"]'::jsonb, 0, 'cografya'),
('Ortak havza yönetiminde temel ilke nedir?', '["Tek taraflı kullanım","Hakkaniyetli ve akılcı kullanım","Kullanmama","Satış"]'::jsonb, 1, 'cografya'),
('Deniz yetki alanlarının belirlenmesinde esas alınan ölçüt nedir?', '["Nüfus","Ordu gücü","Kıyı uzunluğu ve coğrafi konum","Ekonomi"]'::jsonb, 2, 'cografya'),
('Kıta sahanlığı anlaşmazlıklarının temel konusu nedir?', '["Balık türleri","Ada isimleri","Liman adları","Deniz altı kaynak hakları"]'::jsonb, 3, 'cografya'),
('Kutup bölgelerinde egemenlik tartışmasının nedeni nedir?', '["Kaynak ve rota potansiyeli","Turizm","Tarım","Sanayi"]'::jsonb, 0, 'cografya'),
('Uzay hukuku hangi ilkeyi benimser?', '["Uzayın paylaşılması","Uzayın tüm insanlığın ortak alanı olması","Uzayın satılması","Uzayın kapatılması"]'::jsonb, 1, 'cografya'),
('Dünya tarım bölgelerinde ''buğday kuşağı'' nerede uzanır?', '["Ekvator çevresinde","Kutuplarda","Orta kuşak düzlüklerinde","Çöllerde"]'::jsonb, 2, 'cografya'),
('Pamuk üretiminin dünyada yoğunlaştığı ülkelerden biri hangisidir?', '["Norveç","İzlanda","Finlandiya","Hindistan"]'::jsonb, 3, 'cografya'),
('Dünyada çelik üretiminde öne çıkan ülke hangisidir?', '["Çin","Portekiz","İrlanda","Yeni Zelanda"]'::jsonb, 0, 'cografya'),
('Otomotiv sanayisinde öne çıkan ülkelerden biri hangisidir?', '["Nepal","Almanya","Bolivya","Moğolistan"]'::jsonb, 1, 'cografya'),
('Elektronik üretiminde öne çıkan bölge hangisidir?', '["Orta Afrika","Amazon","Doğu ve Güneydoğu Asya","Sibirya"]'::jsonb, 2, 'cografya'),
('Yazılım ve bilişim hizmetlerinde öne çıkan ülke hangisidir?', '["Nijer","Çad","Papua Yeni Gine","Hindistan"]'::jsonb, 3, 'cografya'),
('Turizm gelirlerinde öne çıkan ülkelerden biri hangisidir?', '["Fransa","Moğolistan","Çad","Bhutan"]'::jsonb, 0, 'cografya'),
('Dünya ticaretinde konteyner limanlarının önemi nedir?', '["Balıkçılık","Yük akışının merkezi olması","Turizm","Tarım"]'::jsonb, 1, 'cografya'),
('Küresel tedarik zinciri kavramı neyi anlatır?', '["Tek ülkede üretimi","Yerel ticareti","Üretimin ülkelere yayılmış olmasını","El üretimini"]'::jsonb, 2, 'cografya'),
('Tedarik zinciri kesintilerinin ekonomik sonucu nedir?', '["Fiyat düşüşü","Üretim artışı","Talep artışı","Üretim gecikmesi ve fiyat artışı"]'::jsonb, 3, 'cografya')
on conflict (soru) do nothing;
