-- Soru havuzu genişletme: cografya +73
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Akdeniz havzasında yazın etkili olan basınç sistemi hangisidir?', '["Yüksek basınç","Alçak basınç","Cephe sistemi","Muson"]'::jsonb, 0, 'cografya'),
('Kışın Akdeniz''e yağış getiren sistem hangisidir?', '["Yüksek basınç","Gezici alçak basınçlar","Alizeler","Muson"]'::jsonb, 1, 'cografya'),
('Batı rüzgârları hangi kuşakta etkilidir?', '["Ekvatoral kuşak","Kutup kuşağı","Orta kuşak","Tropikal kuşak"]'::jsonb, 2, 'cografya'),
('Kutup rüzgârlarının özelliği nedir?', '["Sıcak ve nemli","Ilıman","Yağışlı","Soğuk ve kuru olması"]'::jsonb, 3, 'cografya'),
('Ekvator çevresinde alçak basıncın nedeni nedir?', '["Havanın ısınıp yükselmesi","Havanın soğuyup alçalması","Rüzgârın durması","Yağışın azlığı"]'::jsonb, 0, 'cografya'),
('Dönenceler çevresinde çöllerin yoğunlaşmasının nedeni nedir?', '["Yükselen hava","Alçalıcı hava ve yüksek basınç","Bol yağış","Soğuk akıntı yokluğu"]'::jsonb, 1, 'cografya'),
('Soğuk su akıntılarının kıyıda yarattığı etki nedir?', '["Bol yağış","Sıcaklık artışı","Kuraklık ve sis","Kar yağışı"]'::jsonb, 2, 'cografya'),
('Namib ve Atacama çöllerinin kıyıda olmasının nedeni nedir?', '["Sıcak akıntı etkisi","Yükseklik","Buzul","Soğuk akıntı etkisi"]'::jsonb, 3, 'cografya'),
('Muson ikliminde kışın rüzgâr yönü nasıldır?', '["Karadan denize","Denizden karaya","Kuzeyden güneye sabit","Değişmez"]'::jsonb, 0, 'cografya'),
('Savan ikliminde yağış nasıl dağılır?', '["Kışın yoğun","Yazın yoğun, kışın kurak","Yıl boyu eşit","Hiç yağmaz"]'::jsonb, 1, 'cografya'),
('Step ikliminde bitki örtüsü neden ağaçsızdır?', '["Sıcaklığın düşüklüğü","Toprağın tuzluluğu","Yağışın yetersizliği","Rüzgârın şiddeti"]'::jsonb, 2, 'cografya'),
('Tundra topraklarının tarıma elverişsiz olmasının nedeni nedir?', '["Aşırı verimli olması","Tuzlu olması","Kumlu olması","Donmuş ve verimsiz olması"]'::jsonb, 3, 'cografya'),
('Tayga ormanlarının en geniş olduğu ülke hangisidir?', '["Rusya","Brezilya","Hindistan","Avustralya"]'::jsonb, 0, 'cografya'),
('Kutup çölü kavramı neyi ifade eder?', '["Sıcak kum çölü","Yağışı çok az olan soğuk bölge","Yağışlı bölge","Ormanlık alan"]'::jsonb, 1, 'cografya'),
('Buzulların bulunduğu yükseklik sınırına ne ad verilir?', '["Orman sınırı","Tarım sınırı","Daimî kar sınırı","Yerleşim sınırı"]'::jsonb, 2, 'cografya'),
('Daimî kar sınırı Ekvator''dan kutuplara gidildikçe nasıl değişir?', '["Yükselir","Değişmez","Kaybolur","Alçalır"]'::jsonb, 3, 'cografya'),
('Sirk ve buzul vadisi hangi etkenin ürünüdür?', '["Buzul","Akarsu","Rüzgâr","Dalga"]'::jsonb, 0, 'cografya'),
('Drumlin ve moren hangi süreçle oluşur?', '["Akarsu birikimiyle","Buzul birikimiyle","Rüzgâr birikimiyle","Volkanik püskürmeyle"]'::jsonb, 1, 'cografya'),
('Buzul gölüne örnek Türkiye''den hangisi verilebilir?', '["Tuz Gölü","Manyas Gölü","Cilo Dağları''ndaki göller","Sapanca Gölü"]'::jsonb, 2, 'cografya'),
('Rüzgâr aşındırmasıyla oluşan mantar kaya nerede görülür?', '["Yağmur ormanlarında","Buzul alanlarında","Bataklıklarda","Kurak bölgelerde"]'::jsonb, 3, 'cografya'),
('Lös toprakları nasıl oluşur?', '["Rüzgârın taşıdığı tozun birikmesiyle","Akarsu alüvyonuyla","Buzul öğütmesiyle","Volkan külüyle"]'::jsonb, 0, 'cografya'),
('Çöllerde ''vadi'' benzeri kuru yatağa ne ad verilir?', '["Delta","Kuru dere yatağı","Lagün","Fiyort"]'::jsonb, 1, 'cografya'),
('Kum fırtınasının tarıma etkisi nedir?', '["Toprağı sulaması","Verimi artırması","Ekinleri örtüp zarar vermesi","Zararsız olması"]'::jsonb, 2, 'cografya'),
('Yağmur gölgesi etkisi nasıl oluşur?', '["Denize yakınlıkla","Buzul erimesiyle","Ovada birikmeyle","Rüzgâraltı yamacın kuru kalmasıyla"]'::jsonb, 3, 'cografya'),
('Denizcilikte ''rota'' ne anlama gelir?', '["İzlenecek yol doğrultusu","Gemi hızı","Yük miktarı","Liman adı"]'::jsonb, 0, 'cografya'),
('Pusulanın gösterdiği kuzey hangi kuzeydir?', '["Coğrafi kuzey","Manyetik kuzey","Grid kuzey","Yıldız kuzeyi"]'::jsonb, 1, 'cografya'),
('Manyetik kuzey ile coğrafi kuzey arasındaki açıya ne denir?', '["Eğim","Azimut","Sapma (deklinasyon)","Meridyen"]'::jsonb, 2, 'cografya'),
('Deniz mili yaklaşık kaç metredir?', '["1000","1609","2000","1852"]'::jsonb, 3, 'cografya'),
('Denizcilikte hız birimi hangisidir?', '["Knot","Beaufort","Mach","Newton"]'::jsonb, 0, 'cografya'),
('Gemi taşımacılığında ''draft'' neyi belirtir?', '["Uzunluğunu","Geminin su çekimini","Genişliğini","Hızını"]'::jsonb, 1, 'cografya'),
('Deniz feneri ve şamandıraların ortak işlevi nedir?', '["Yük taşımak","Balık avlamak","Seyir yardımcısı olmak","Hava ölçmek"]'::jsonb, 2, 'cografya'),
('Deniz seviyesindeki değişimleri ölçen alete ne ad verilir?', '["Barometre","Anemometre","Higrometre","Mareograf"]'::jsonb, 3, 'cografya'),
('Okyanuslarda tuzluluğun en yüksek olduğu bölgeler nerelerdir?', '["Buharlaşmanın fazla olduğu alanlar","Kutuplar","Nehir ağızları","Yağışlı ekvator"]'::jsonb, 0, 'cografya'),
('Nehir ağızlarında tuzluluğun düşmesinin nedeni nedir?', '["Buharlaşma","Tatlı su karışması","Rüzgâr","Gelgit"]'::jsonb, 1, 'cografya'),
('Akdeniz''in tuzluluğunun okyanustan yüksek olmasının nedeni nedir?', '["Nehirlerin çokluğu","Derinliğin azlığı","Buharlaşmanın fazlalığı","Soğukluğu"]'::jsonb, 2, 'cografya'),
('Deniz suyu sıcaklığının derinlikle değişimi nasıldır?', '["Derinlikte artar","Değişmez","Rastgeledir","Derinlikte azalır"]'::jsonb, 3, 'cografya'),
('Okyanus akıntılarını oluşturan başlıca etken nedir?', '["Rüzgârlar ve yoğunluk farkı","Gelgit yalnızca","Depremler","Volkanlar"]'::jsonb, 0, 'cografya'),
('Termohalin dolaşımı neye bağlıdır?', '["Rüzgâra yalnızca","Sıcaklık ve tuzluluk farkına","Aya","Güneş tutulmasına"]'::jsonb, 1, 'cografya'),
('Kutup buzullarının erimesinin okyanus dolaşımına etkisi ne olabilir?', '["Hızlandırması kesin","Etkisiz kalması","Dolaşımı zayıflatması","Tuzluluğu artırması"]'::jsonb, 2, 'cografya'),
('Deniz buzu ile kara buzulu arasındaki fark nedir?', '["Deniz buzunun yükseltmesi","İkisinin aynı olması","Kara buzulunun etkisiz olması","Yalnız kara buzulunun düzeyi yükseltmesi"]'::jsonb, 3, 'cografya'),
('Antarktika''daki buz kalkanının küresel önemi nedir?', '["Deniz seviyesi için su deposu olması","Petrol kaynağı","Tarım alanı","Turizm merkezi"]'::jsonb, 0, 'cografya'),
('Kuzey Kutbu ile Güney Kutbu arasındaki temel coğrafi fark nedir?', '["İkisinin de kıta olması","Kuzeyin okyanus, güneyin kıta olması","İkisinin de okyanus olması","Kuzeyin kıta olması"]'::jsonb, 1, 'cografya'),
('Bir bölgenin ''kıtasal iklime'' sahip olması ne demektir?', '["Denize yakın","Yıl boyu yağışlı","Denizden uzak, sıcaklık farkı yüksek","Sıcaklık farkı düşük"]'::jsonb, 2, 'cografya'),
('Sibirya''da kışların çok sert geçmesinin nedeni nedir?', '["Deniz etkisi","Alçak enlem","Sıcak akıntı","Denizden uzaklık ve yüksek enlem"]'::jsonb, 3, 'cografya'),
('İzlanda''nın enlemine göre ılıman olmasının nedeni nedir?', '["Sıcak akıntı etkisi","Volkanik ısı","Alçak enlem","Yükselti"]'::jsonb, 0, 'cografya'),
('Batı Avrupa''nın kışları neden aynı enlemdeki Kanada''dan ılıktır?', '["Daha güneyde olması","Sıcak okyanus akıntısı","Yükseltisi","Nüfus yoğunluğu"]'::jsonb, 1, 'cografya'),
('Bir ülkenin enerji kaynağı çeşitliliği neden önemlidir?', '["Fiyatı sabitlemesi","Tüketimi artırması","Arz güvenliğini artırması","İthalatı zorunlu kılması"]'::jsonb, 2, 'cografya'),
('Petrol rezervlerinin en yoğun olduğu bölge hangisidir?', '["Kuzey Avrupa","Orta Afrika","Okyanusya","Orta Doğu"]'::jsonb, 3, 'cografya'),
('Doğal gaz rezervi bakımından öne çıkan ülkelerden biri hangisidir?', '["Rusya","Portekiz","İrlanda","Yeni Zelanda"]'::jsonb, 0, 'cografya'),
('Uranyum madeninin başlıca kullanım alanı nedir?', '["Cam üretimi","Nükleer enerji","Gübre","Tekstil"]'::jsonb, 1, 'cografya'),
('Nadir toprak elementlerinin önemi nedir?', '["Gıda üretiminde","İnşaatta","İleri teknoloji ürünlerinde kullanılması","Tekstilde"]'::jsonb, 2, 'cografya'),
('Lityumun teknolojideki önemi nedir?', '["Cam üretiminde","Gübre üretiminde","Kâğıt üretiminde","Pil üretiminde kullanılması"]'::jsonb, 3, 'cografya'),
('Kaynak çeşitliliği olmayan ülkelerin ekonomik riski nedir?', '["Tek ürüne bağımlılık","Yüksek çeşitlilik","Düşük ihracat","Fazla üretim"]'::jsonb, 0, 'cografya'),
('OPEC örgütü hangi alanda etkilidir?', '["Tarım ürünleri","Petrol üretim ve fiyat politikası","Tekstil","Turizm"]'::jsonb, 1, 'cografya'),
('Enerji koridoru olmak bir ülkeye ne kazandırır?', '["Rezerv artışı","Nüfus artışı","Transit gelir ve stratejik önem","Toprak genişlemesi"]'::jsonb, 2, 'cografya'),
('Tarihte ''Bereketli Hilal'' neden önemlidir?', '["İlk sanayi bölgesi","İlk maden bölgesi","İlk liman bölgesi","Tarımın ilk başladığı bölge olması"]'::jsonb, 3, 'cografya'),
('İlk kentlerin nehir kıyısında kurulmasının nedeni nedir?', '["Su ve verimli toprak","Savunma kolaylığı yalnızca","Maden varlığı","Serin iklim"]'::jsonb, 0, 'cografya'),
('Mısır uygarlığının Nil''e bağımlılığı neyi gösterir?', '["Nüfusun etkisini","Coğrafyanın uygarlığa etkisini","Dilin etkisini","Dinin etkisini"]'::jsonb, 1, 'cografya'),
('İpek Yolu''nun canlanmasında hangi coğrafi öğe belirleyiciydi?', '["Okyanus akıntıları","Buzul yolları","Geçit ve vaha zincirleri","Delta ovaları"]'::jsonb, 2, 'cografya'),
('Kavimler Göçü''nün coğrafi tetikleyicisi ne olmuştur?', '["Deniz yükselmesi","Volkan patlaması","Buzul çağı başlangıcı","İklim ve otlak baskısı"]'::jsonb, 3, 'cografya'),
('Coğrafi Keşifler''de Atlantik rüzgârlarının rolü nedir?', '["Gemilere yön ve itki sağlaması","Yolu kapatması","Fırtına yaratması yalnızca","Etkisiz olması"]'::jsonb, 0, 'cografya'),
('Sömürgeciliğin coğrafi kaynağı ne olmuştur?', '["Nüfus fazlalığı","Hammadde bölgelerine erişim isteği","İklim değişimi","Buzul erimesi"]'::jsonb, 1, 'cografya'),
('Sanayi Devrimi''nin İngiltere''de başlamasında hangi coğrafi etken rol oynamıştır?', '["Çöl iklimi","Yüksek dağlar","Kömür ve demir yataklarının varlığı","Buzul örtüsü"]'::jsonb, 2, 'cografya'),
('Demiryolunun yayılması yerleşmeleri nasıl etkilemiştir?', '["Kentleri küçültmüştür","Etkilememiştir","Kırsalı büyütmüştür","Hat boyunca kentleri büyütmüştür"]'::jsonb, 3, 'cografya'),
('Süveyş ve Panama kanallarının ortak sonucu nedir?', '["Deniz ticaretini kısaltması","Ticareti azaltması","Tarımı geliştirmesi","Nüfusu azaltması"]'::jsonb, 0, 'cografya'),
('Küreselleşmenin coğrafi sonucu nedir?', '["Ulaşımın azalması","Mekânsal etkileşimin artması","İletişimin azalması","Ticaretin bitmesi"]'::jsonb, 1, 'cografya'),
('Bir ülkenin lojistik merkez olması neye bağlıdır?', '["Nüfus fazlalığına","Yüzölçümüne","Konum, altyapı ve ulaşım ağına","İklimine"]'::jsonb, 2, 'cografya'),
('Serbest ticaret bölgelerinin coğrafi konum tercihi neye dayanır?', '["Dağlık alana","Çöle","Buzula","Liman ve sınır yakınlığına"]'::jsonb, 3, 'cografya'),
('Deprem sonrası geçici barınma alanlarının seçiminde ölçüt nedir?', '["Güvenli zemin ve ulaşılabilirlik","Manzara","Yükseklik","Nüfus yoğunluğu"]'::jsonb, 0, 'cografya'),
('Afet lojistiğinde en kritik unsur nedir?', '["Depo büyüklüğü","Hızlı ve doğru dağıtım","Araç rengi","Personel sayısı"]'::jsonb, 1, 'cografya'),
('Coğrafi bilgi sistemlerinin afet yönetimindeki rolü nedir?', '["Yardım dağıtımı yalnızca","Bina yapımı","Risk haritalama ve planlama","Vergi toplama"]'::jsonb, 2, 'cografya'),
('Kentsel risk azaltma planlarının temel amacı nedir?', '["Nüfusu artırmak","Yapılaşmayı artırmak","Vergi toplamak","Can ve mal kaybını en aza indirmek"]'::jsonb, 3, 'cografya'),
('Bir yerleşimin ''dirençliliği'' (resilience) neyi ifade eder?', '["Afet sonrası toparlanma kapasitesini","Nüfus büyüklüğünü","Yüzölçümünü","Gelir düzeyini"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
