-- Soru havuzu genişletme: cografya +74
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Ardahan hangi bölgemizde yer alır?', '["Doğu Anadolu","Karadeniz","İç Anadolu","Marmara"]'::jsonb, 0, 'cografya'),
('Bayburt hangi bölgemizde yer alır?', '["Doğu Anadolu","Karadeniz","İç Anadolu","Ege"]'::jsonb, 1, 'cografya'),
('Gümüşhane hangi bölgemizde yer alır?', '["Doğu Anadolu","İç Anadolu","Karadeniz","Marmara"]'::jsonb, 2, 'cografya'),
('Çankırı hangi bölgemizde yer alır?', '["Karadeniz","Marmara","Ege","İç Anadolu"]'::jsonb, 3, 'cografya'),
('Kırıkkale hangi bölgemizde yer alır?', '["İç Anadolu","Karadeniz","Akdeniz","Doğu Anadolu"]'::jsonb, 0, 'cografya'),
('Kırşehir hangi bölgemizde yer alır?', '["Akdeniz","İç Anadolu","Ege","Karadeniz"]'::jsonb, 1, 'cografya'),
('Uşak hangi bölgemizde yer alır?', '["İç Anadolu","Akdeniz","Ege","Marmara"]'::jsonb, 2, 'cografya'),
('Kütahya hangi bölgemizde yer alır?', '["İç Anadolu","Marmara","Karadeniz","Ege"]'::jsonb, 3, 'cografya'),
('Bilecik hangi iki bölgenin geçişinde yer alır?', '["Marmara ve İç Anadolu","Ege ve Akdeniz","Karadeniz ve Doğu Anadolu","Akdeniz ve Güneydoğu"]'::jsonb, 0, 'cografya'),
('Yalova hangi denize kıyıdır?', '["Karadeniz","Marmara","Ege","Akdeniz"]'::jsonb, 1, 'cografya'),
('Kilis hangi ülkeyle sınır komşusudur?', '["Irak","İran","Suriye","Gürcistan"]'::jsonb, 2, 'cografya'),
('Şırnak hangi ülkelerle sınırdaştır?', '["İran ve Ermenistan","Gürcistan ve Azerbaycan","Bulgaristan ve Yunanistan","Irak ve Suriye"]'::jsonb, 3, 'cografya'),
('Hakkari hangi ülkelerle sınırdaştır?', '["İran ve Irak","Gürcistan ve Ermenistan","Suriye ve Ürdün","Azerbaycan ve İran"]'::jsonb, 0, 'cografya'),
('Ağrı hangi ülkeyle sınır komşusudur?', '["Irak","İran","Gürcistan","Bulgaristan"]'::jsonb, 1, 'cografya'),
('Artvin hangi ülkeyle sınır komşusudur?', '["Ermenistan","Azerbaycan","Gürcistan","İran"]'::jsonb, 2, 'cografya'),
('Edirne hangi ülkelerle sınır komşusudur?', '["Romanya ve Sırbistan","Makedonya ve Arnavutluk","Moldova ve Ukrayna","Yunanistan ve Bulgaristan"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en düşük rakımlı il merkezlerinden biri hangisidir?', '["İzmir","Erzurum","Van","Kars"]'::jsonb, 0, 'cografya'),
('Türkiye''de en fazla ilçesi olan illerden biri hangisidir?', '["Bayburt","İstanbul","Kilis","Yalova"]'::jsonb, 1, 'cografya'),
('Bolu Dağı geçidi hangi iki bölgeyi bağlar?', '["Ege ve Akdeniz","İç Anadolu ve Doğu Anadolu","Marmara ve Karadeniz","Marmara ve Ege"]'::jsonb, 2, 'cografya'),
('Belen Geçidi hangi ilimizdedir?', '["Mersin","Adana","Osmaniye","Hatay"]'::jsonb, 3, 'cografya'),
('Gülek Boğazı hangi dağ sisteminde yer alır?', '["Toroslar","Kaçkarlar","Ilgaz","Uludağ"]'::jsonb, 0, 'cografya'),
('Zigana Geçidi hangi dağ sırasında yer alır?', '["Toroslar","Doğu Karadeniz Dağları","Menteşe Dağları","Köroğlu Dağları"]'::jsonb, 1, 'cografya'),
('Kop Geçidi hangi illeri bağlar?', '["Trabzon ve Rize","Van ve Bitlis","Erzurum ve Bayburt","Sivas ve Tokat"]'::jsonb, 2, 'cografya'),
('Anadolu''nun kuzeyindeki dağ sırasına ne ad verilir?', '["Toroslar","Menteşe Dağları","Nur Dağları","Kuzey Anadolu Dağları"]'::jsonb, 3, 'cografya'),
('Nur (Amanos) Dağları hangi ilimizde yer alır?', '["Hatay","Antalya","Muğla","Mersin"]'::jsonb, 0, 'cografya'),
('Menteşe Dağları hangi bölgemizdedir?', '["Karadeniz","Ege","İç Anadolu","Doğu Anadolu"]'::jsonb, 1, 'cografya'),
('Köroğlu Dağları hangi bölgemizde uzanır?', '["Doğu Karadeniz","Ege","Batı Karadeniz","Akdeniz"]'::jsonb, 2, 'cografya'),
('Bolkar Dağları hangi dağ sisteminin parçasıdır?', '["Kaçkarlar","Uludağ","Ilgaz","Toroslar"]'::jsonb, 3, 'cografya'),
('Aladağlar hangi illerin sınırında yükselir?', '["Niğde, Kayseri ve Adana","Rize, Trabzon, Artvin","Edirne, Kırklareli","İzmir, Manisa"]'::jsonb, 0, 'cografya'),
('Munzur Dağları hangi ilimizdedir?', '["Bingöl","Tunceli","Elazığ","Erzincan"]'::jsonb, 1, 'cografya'),
('Bingöl Dağları hangi bölgemizdedir?', '["Karadeniz","İç Anadolu","Doğu Anadolu","Marmara"]'::jsonb, 2, 'cografya'),
('Hasan Dağı hangi ilimizdedir?', '["Nevşehir","Niğde","Konya","Aksaray"]'::jsonb, 3, 'cografya'),
('Melendiz Dağı hangi bölgede yer alır?', '["İç Anadolu","Doğu Anadolu","Akdeniz","Ege"]'::jsonb, 0, 'cografya'),
('Karacadağ hangi ilimizin çevresindedir?', '["Mardin","Diyarbakır","Şanlıurfa","Batman"]'::jsonb, 1, 'cografya'),
('Tendürek Dağı hangi ilimizdedir?', '["Van","Iğdır","Ağrı","Kars"]'::jsonb, 2, 'cografya'),
('Sultan Dağları hangi bölgemizde uzanır?', '["Karadeniz","Marmara","Güneydoğu Anadolu","İç Anadolu ve Ege geçişi"]'::jsonb, 3, 'cografya'),
('Spil Dağı hangi ilimizdedir?', '["Manisa","İzmir","Aydın","Denizli"]'::jsonb, 0, 'cografya'),
('Boz Dağlar hangi bölgemizdedir?', '["Karadeniz","Ege","İç Anadolu","Akdeniz"]'::jsonb, 1, 'cografya'),
('Ganos Dağı hangi bölgemizdedir?', '["Ege","Akdeniz","Trakya","Doğu Anadolu"]'::jsonb, 2, 'cografya'),
('Istranca (Yıldız) Dağları hangi bölgemizdedir?', '["Ege","İç Anadolu","Karadeniz doğusu","Trakya"]'::jsonb, 3, 'cografya'),
('Türkiye''de tektonik göllerin yoğun olduğu yöre hangisidir?', '["Göller Yöresi","Ergene Havzası","Çukurova","Bafra Ovası"]'::jsonb, 0, 'cografya'),
('Burdur Gölü''nün tuzluluğunun yüksek olmasının nedeni nedir?', '["Deniz suyu karışması","Kapalı havzada olması","Buzul beslemesi","Volkanik su"]'::jsonb, 1, 'cografya'),
('Marmara Gölü hangi ilimizdedir?', '["Balıkesir","İzmir","Manisa","Bursa"]'::jsonb, 2, 'cografya'),
('Ulubat Gölü hangi ilimizdedir?', '["Balıkesir","Kocaeli","Yalova","Bursa"]'::jsonb, 3, 'cografya'),
('İznik Gölü hangi ilimizdedir?', '["Bursa","Sakarya","Kocaeli","Bilecik"]'::jsonb, 0, 'cografya'),
('Terkos Gölü hangi kentin su kaynaklarındandır?', '["Ankara","İstanbul","İzmir","Bursa"]'::jsonb, 1, 'cografya'),
('Ankara''nın içme suyu sağlayan barajlarından biri hangisidir?', '["Keban Barajı","Atatürk Barajı","Çubuk Barajı","Seyhan Barajı"]'::jsonb, 2, 'cografya'),
('Türkiye''de sazan ve inci kefali gibi türlerin bulunduğu göl hangisidir?', '["Tuz Gölü","Acıgöl","Burdur Gölü","Van Gölü"]'::jsonb, 3, 'cografya'),
('Van Gölü''nde yaşayan inci kefalinin özelliği nedir?', '["Sodalı suya uyum sağlaması","Tuzlu denizde yaşaması","Buzda yaşaması","Karada yaşaması"]'::jsonb, 0, 'cografya'),
('Türkiye''de flamingoların uğrak alanı olan göl hangisidir?', '["Uzungöl","Tuz Gölü","Abant Gölü","Çıldır Gölü"]'::jsonb, 1, 'cografya'),
('Kuş gözlemciliği için önemli olan Gediz Deltası hangi ildedir?', '["Manisa","Aydın","İzmir","Balıkesir"]'::jsonb, 2, 'cografya'),
('Göksu Deltası hangi ilimizdedir?', '["Antalya","Adana","Hatay","Mersin"]'::jsonb, 3, 'cografya'),
('Kızılırmak Deltası''nda korunan başlıca değer nedir?', '["Sulak alan ve kuş varlığı","Maden yatağı","Orman ürünü","Termal su"]'::jsonb, 0, 'cografya'),
('Meriç Deltası hangi iki ülke arasında paylaşılır?', '["Türkiye ve Bulgaristan","Türkiye ve Yunanistan","Yunanistan ve Bulgaristan","Türkiye ve Romanya"]'::jsonb, 1, 'cografya'),
('Dünyada en çok kahve tüketen bölgelerden biri hangisidir?', '["Sahra","Amazon","İskandinavya","Sibirya"]'::jsonb, 2, 'cografya'),
('Pirinç tüketiminin en yüksek olduğu kıta hangisidir?', '["Avrupa","Afrika","Okyanusya","Asya"]'::jsonb, 3, 'cografya'),
('Muz üretiminde öne çıkan bölgelerden biri hangisidir?', '["Orta Amerika","Sibirya","İskandinavya","Kanada"]'::jsonb, 0, 'cografya'),
('Hindistan cevizi hangi iklim kuşağında yetişir?', '["Kutup","Tropikal","Tundra","Karasal"]'::jsonb, 1, 'cografya'),
('Hurma ağacı hangi ortamda yetişir?', '["Tundrada","Yağmur ormanında","Sıcak ve kurak vahalarda","Buzul kenarında"]'::jsonb, 2, 'cografya'),
('Kauçuk ağacı hangi bölgede yetiştirilir?', '["Kuzey Avrupa","Orta Asya bozkırı","Kutup","Tropikal Güneydoğu Asya"]'::jsonb, 3, 'cografya'),
('Şeker kamışı hangi iklimde yetişir?', '["Tropikal ve subtropikal","Kutup","Tundra","Sert karasal"]'::jsonb, 0, 'cografya'),
('Şeker pancarı hangi iklimde yetişir?', '["Tropikal","Ilıman karasal","Ekvatoral","Kutup"]'::jsonb, 1, 'cografya'),
('Dünya''nın ekseninin eğik olması ne yaratır?', '["Gece gündüzü","Gelgiti","Mevsimleri","Rüzgârları"]'::jsonb, 2, 'cografya'),
('Dünya''nın günlük hareketinin sonucu nedir?', '["Mevsimlerin oluşması","Gelgitin oluşması","Rüzgârın oluşması","Gece ve gündüzün oluşması"]'::jsonb, 3, 'cografya'),
('Dünya''nın yıllık hareketinin süresi yaklaşık ne kadardır?', '["365 gün","30 gün","24 saat","100 gün"]'::jsonb, 0, 'cografya'),
('Artık yıl uygulaması neden gereklidir?', '["Ayın hareketi","Yıl süresinin tam gün olmaması","Eksen eğikliği","Gelgit"]'::jsonb, 1, 'cografya'),
('Ay''ın evrelerinin nedeni nedir?', '["Dünya''nın dönmesi","Güneş''in dönmesi","Ay''ın Dünya çevresinde dolanması","Gelgit"]'::jsonb, 2, 'cografya'),
('Gelgit genliğinin en yüksek olduğu durum hangisidir?', '["Dik açıdayken","Ay tutulmasında","Kış aylarında","Güneş ve Ay aynı doğrultudayken"]'::jsonb, 3, 'cografya'),
('Gelgitten enerji üretimi hangi kıyılarda uygundur?', '["Genliği yüksek kıyılarda","Kapalı denizlerde","Göllerde","Nehirlerde"]'::jsonb, 0, 'cografya'),
('Türkiye''de gelgit enerjisinin uygun olmamasının nedeni nedir?', '["Kıyının kısalığı","Gelgit genliğinin çok düşük olması","Suyun soğukluğu","Rüzgârın azlığı"]'::jsonb, 1, 'cografya'),
('Güneş ışınlarının dik geldiği yerlerde sıcaklık neden yüksektir?', '["Atmosferin kalın olması","Yükseltinin fazlalığı","Enerjinin dar alana düşmesi","Nemin azlığı"]'::jsonb, 2, 'cografya'),
('Aynı anda iki farklı yarım kürede farklı mevsim yaşanmasının nedeni nedir?', '["Günlük hareket","Ay''ın çekimi","Atmosfer basıncı","Eksen eğikliği ve yıllık hareket"]'::jsonb, 3, 'cografya'),
('Gündönümü (solstis) tarihlerinde ne olur?', '["Gündüz veya gece en uzun olur","Gece gündüz eşitlenir","Mevsim bitmez","Ay tutulur"]'::jsonb, 0, 'cografya'),
('Kutup gündüzü ne demektir?', '["Güneşin hiç doğmaması","Güneşin uzun süre batmaması","Ayın görünmemesi","Sisin sürmesi"]'::jsonb, 1, 'cografya')
on conflict (soru) do nothing;
