-- Başlangıç soru havuzu (Claude API devreye girene kadar oyun oynanabilir olsun)
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Türkiye''nin başkenti hangi şehirdir?', '["İstanbul","Ankara","İzmir","Bursa"]', 1, 'cografya'),
('İstiklal Marşı''nın yazarı kimdir?', '["Mehmet Akif Ersoy","Yahya Kemal Beyatlı","Ziya Gökalp","Namık Kemal"]', 0, 'edebiyat'),
('Dünyanın en büyük okyanusu hangisidir?', '["Atlas Okyanusu","Hint Okyanusu","Pasifik Okyanusu","Arktik Okyanusu"]', 2, 'cografya'),
('Su molekülünün kimyasal formülü nedir?', '["CO2","H2O","O2","NaCl"]', 1, 'bilim'),
('Osmanlı Devleti''nin kurucusu kimdir?', '["Orhan Bey","Ertuğrul Gazi","Osman Bey","Fatih Sultan Mehmet"]', 2, 'tarih'),
('Mona Lisa tablosunun ressamı kimdir?', '["Michelangelo","Leonardo da Vinci","Rafael","Rembrandt"]', 1, 'sanat'),
('Türkiye''nin en uzun nehri hangisidir?', '["Fırat","Sakarya","Yeşilırmak","Kızılırmak"]', 3, 'cografya'),
('Güneş Sistemi''ndeki en büyük gezegen hangisidir?', '["Satürn","Jüpiter","Neptün","Mars"]', 1, 'bilim'),
('İstanbul''u fetheden Osmanlı padişahı kimdir?', '["Yavuz Sultan Selim","Kanuni Sultan Süleyman","Fatih Sultan Mehmet","II. Murad"]', 2, 'tarih'),
('Nobel Edebiyat Ödülü kazanan Türk yazar kimdir?', '["Yaşar Kemal","Orhan Pamuk","Aziz Nesin","Oğuz Atay"]', 1, 'edebiyat'),
('2023 itibarıyla dünyanın en kalabalık ülkesi hangisidir?', '["Çin","ABD","Hindistan","Endonezya"]', 2, 'cografya'),
('Telefonun mucidi olarak bilinen kişi kimdir?', '["Thomas Edison","Alexander Graham Bell","Nikola Tesla","Guglielmo Marconi"]', 1, 'bilim'),
('Türkiye Cumhuriyeti hangi yıl ilan edildi?', '["1920","1921","1922","1923"]', 3, 'tarih'),
('En küçük asal sayı hangisidir?', '["0","1","2","3"]', 2, 'bilim'),
('"Suç ve Ceza" romanının yazarı kimdir?', '["Tolstoy","Dostoyevski","Çehov","Gogol"]', 1, 'edebiyat'),
('Dünyanın en yüksek dağı hangisidir?', '["K2","Kangchenjunga","Everest","Ağrı Dağı"]', 2, 'cografya'),
('Işığın boşluktaki hızı yaklaşık kaç km/saniyedir?', '["150.000","300.000","450.000","600.000"]', 1, 'bilim'),
('Türkiye''nin en büyük gölü hangisidir?', '["Tuz Gölü","Beyşehir Gölü","Van Gölü","Eğirdir Gölü"]', 2, 'cografya'),
('Penisilini keşfeden bilim insanı kimdir?', '["Louis Pasteur","Alexander Fleming","Marie Curie","Robert Koch"]', 1, 'bilim'),
('2002 FIFA Dünya Kupası''nı hangi ülke kazandı?', '["Almanya","Fransa","Brezilya","İtalya"]', 2, 'spor'),
('Standart bir piyanoda kaç tuş vardır?', '["66","76","88","98"]', 2, 'sanat'),
('Türkiye''de kaç il vardır?', '["79","80","81","82"]', 2, 'genel'),
('Batı''da "Muhteşem" lakabıyla anılan Osmanlı padişahı kimdir?', '["Fatih Sultan Mehmet","Kanuni Sultan Süleyman","Yavuz Sultan Selim","IV. Murad"]', 1, 'tarih'),
('DNA''nın açılımında hangi asit yer alır?', '["Ribonükleik asit","Deoksiribonükleik asit","Amino asit","Folik asit"]', 1, 'bilim'),
('Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?', '["Kanada","Çin","ABD","Rusya"]', 3, 'cografya'),
('"1984" romanının yazarı kimdir?', '["Aldous Huxley","George Orwell","Ray Bradbury","Franz Kafka"]', 1, 'edebiyat'),
('İnsan vücudundaki en büyük organ hangisidir?', '["Karaciğer","Akciğer","Deri","Beyin"]', 2, 'bilim'),
('Basketbolda bir takım sahada aynı anda kaç oyuncuyla oynar?', '["4","5","6","7"]', 1, 'spor'),
('Çanakkale Deniz Zaferi hangi yıl kazanılmıştır?', '["1914","1915","1916","1918"]', 1, 'tarih'),
('Mars gezegeninin yaygın takma adı nedir?', '["Mavi Gezegen","Kızıl Gezegen","Gaz Devi","Buz Gezegeni"]', 1, 'bilim'),
('Ay''a ayak basan ilk insan kimdir?', '["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","Michael Collins"]', 2, 'tarih'),
('"Ayçiçekleri" tablosunun ressamı kimdir?', '["Claude Monet","Vincent van Gogh","Pablo Picasso","Salvador Dali"]', 1, 'sanat'),
('Yaz Olimpiyat Oyunları kaç yılda bir düzenlenir?', '["2","3","4","5"]', 2, 'spor'),
('Türkiye''nin en kalabalık şehri hangisidir?', '["Ankara","İzmir","İstanbul","Antalya"]', 2, 'cografya'),
('Hücrenin enerji üretim merkezi olarak bilinen organel hangisidir?', '["Ribozom","Mitokondri","Çekirdek","Golgi cisimciği"]', 1, 'bilim'),
('Sherlock Holmes karakterinin yaratıcısı kimdir?', '["Agatha Christie","Arthur Conan Doyle","Edgar Allan Poe","Jules Verne"]', 1, 'edebiyat'),
('UEFA Şampiyonlar Ligi''ni en çok kazanan kulüp hangisidir?', '["Barcelona","Bayern Münih","Milan","Real Madrid"]', 3, 'spor'),
('Mustafa Kemal Atatürk hangi yıl doğmuştur?', '["1879","1880","1881","1883"]', 2, 'tarih'),
('Periyodik tabloda "Au" simgesi hangi elementi gösterir?', '["Gümüş","Altın","Alüminyum","Bakır"]', 1, 'bilim'),
('Genel kabule göre dünyanın en uzun nehri hangisidir?', '["Amazon","Nil","Mississippi","Yangtze"]', 1, 'cografya')
on conflict (soru) do nothing;
