-- Soru havuzu genişletme: cografya +61
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Toprak profilinde ''A horizonu'' neyi ifade eder?', '["Organik maddece zengin üst katman","Ana kaya","Kireç birikim katı","Taban suyu"]'::jsonb, 0, 'cografya'),
('Toprakta ''kil'' oranının yüksek olmasının etkisi nedir?', '["Su geçirgenliğinin artması","Su tutma kapasitesinin artması","Havalanmanın artması","Verimin sıfırlanması"]'::jsonb, 1, 'cografya'),
('Kumlu toprağın belirgin özelliği nedir?', '["Suyu tutması","Ağır olması","Suyu hızlı geçirmesi","Havasız olması"]'::jsonb, 2, 'cografya'),
('Tınlı toprak neden tarımda tercih edilir?', '["Tamamen kumlu olması","Tamamen killi olması","Taşlı olması","Su tutma ve havalanma dengesi"]'::jsonb, 3, 'cografya'),
('Toprakta pH değerinin bitkiye etkisi nedir?', '["Besin alımını belirlemesi","Rengi belirlemesi","Sıcaklığı belirlemesi","Ağırlığı belirlemesi"]'::jsonb, 0, 'cografya'),
('Asitli toprakların iyileştirilmesinde ne kullanılır?', '["Tuz","Kireç","Kum","Çakıl"]'::jsonb, 1, 'cografya'),
('Toprak tuzluluğunun başlıca nedeni nedir?', '["Aşırı gübreleme yalnızca","Ağaçlandırma","Aşırı sulama ve yetersiz drenaj","Nadas"]'::jsonb, 2, 'cografya'),
('Drenaj sisteminin tarımsal işlevi nedir?', '["Su tutmak","Gübre vermek","Tohum ekmek","Fazla suyu uzaklaştırmak"]'::jsonb, 3, 'cografya'),
('Toprak sıkışmasının bitkiye etkisi nedir?', '["Kök gelişimini engellemesi","Kökü güçlendirmesi","Suyu artırması","Havayı artırması"]'::jsonb, 0, 'cografya'),
('Örtü bitkisi ekiminin toprağa yararı nedir?', '["Toprağı kurutması","Erozyonu azaltıp organik madde katması","Tuzu artırması","Verimi düşürmesi"]'::jsonb, 1, 'cografya'),
('Doğrudan ekim (sürümsüz tarım) neyi hedefler?', '["Verimi düşürmeyi","Sürümü artırmayı","Toprak yapısını korumayı","Suyu tüketmeyi"]'::jsonb, 2, 'cografya'),
('Biyocoğrafyada ''tür yayılışı'' neye bağlıdır?', '["Yalnız nüfusa","Yalnız yükseltiye","Yalnız enleme","İklim, toprak ve engellere"]'::jsonb, 3, 'cografya'),
('Coğrafi izolasyonun türleşmedeki rolü nedir?', '["Popülasyonları ayırıp farklılaştırması","Türleri birleştirmesi","Göçü artırması","Üremeyi durdurması"]'::jsonb, 0, 'cografya'),
('Ada biyocoğrafyasında tür sayısını etkileyen etken nedir?', '["Adanın rengi","Adanın büyüklüğü ve anakaraya uzaklığı","Adanın adı","Adanın yaşı yalnızca"]'::jsonb, 1, 'cografya'),
('Relikt tür ne demektir?', '["Yeni gelen tür","Evcil tür","Geçmiş iklimden kalan tür","İstilacı tür"]'::jsonb, 2, 'cografya'),
('Türkiye''de sığla ağacının önemi nedir?', '["Her yerde bulunması","İstilacı olması","Evcil olması","Dar alanda yaşayan endemik olması"]'::jsonb, 3, 'cografya'),
('Kazdağı göknarı hangi ilimizde yayılış gösterir?', '["Balıkesir","Rize","Antalya","Kars"]'::jsonb, 0, 'cografya'),
('Türkiye''de step alanlarının ağaçlandırılmasında hangi tür tercih edilir?', '["Nem seven türler","Kurağa dayanıklı türler","Tropikal türler","Su bitkileri"]'::jsonb, 1, 'cografya'),
('Hidrolojik döngüde ''sızma'' ne anlama gelir?', '["Suyun buharlaşması","Suyun akması","Suyun toprağa geçmesi","Suyun donması"]'::jsonb, 2, 'cografya'),
('Yüzeysel akış ne zaman artar?', '["Toprak kuruysa","Yağış azsa","Bitki örtüsü fazlaysa","Toprak doygunsa veya geçirimsizse"]'::jsonb, 3, 'cografya'),
('Havza yönetimi neyi hedefler?', '["Su kaynaklarını bütüncül planlamayı","Tek nehri korumayı","Barajı yıkmayı","Tarımı durdurmayı"]'::jsonb, 0, 'cografya'),
('Su kalitesi izlemede hangi parametre temeldir?', '["Renk yalnızca","Çözünmüş oksijen","Ses","Ağırlık"]'::jsonb, 1, 'cografya'),
('Bir akarsuda çözünmüş oksijenin düşmesi neyi gösterir?', '["Suyun temizlendiğini","Debinin arttığını","Kirlilik yükünün arttığını","Sıcaklığın düştüğünü"]'::jsonb, 2, 'cografya'),
('Biyolojik oksijen ihtiyacı (BOİ) neyi ölçer?', '["Tuzluluğu","Sertliği","Rengi","Organik kirlilik düzeyini"]'::jsonb, 3, 'cografya'),
('Su kaynaklarında ''debi ölçümü'' neden yapılır?', '["Kullanılabilir su miktarını belirlemek","Balık saymak","Derinlik ölçmek","Renk ölçmek"]'::jsonb, 0, 'cografya'),
('Kar erimesinin akarsu rejimine etkisi nedir?', '["Yazın debiyi yükseltmesi","İlkbaharda debiyi yükseltmesi","Kışın yükseltmesi","Etkisiz olması"]'::jsonb, 1, 'cografya'),
('Karla beslenen akarsuların Türkiye''deki bölgesi hangisidir?', '["Ege kıyısı","Güney Marmara","Doğu Anadolu","Trakya"]'::jsonb, 2, 'cografya'),
('Yağmurla beslenen akarsuların rejimi nasıldır?', '["Yıl boyu sabit","Yalnız yazın yüksek","Hiç değişmez","Yağış dönemine bağlı düzensiz"]'::jsonb, 3, 'cografya'),
('Kaynak sularıyla beslenen akarsuların özelliği nedir?', '["Rejimlerinin düzenli olması","Rejimlerinin düzensizliği","Kurumaları","Tuzlu olmaları"]'::jsonb, 0, 'cografya'),
('Uygulama imar planı neyi ayrıntılandırır?', '["Ülke politikasını","Parsel ve yapılaşma koşullarını","Bölge iklimini","Nüfus sayımını"]'::jsonb, 1, 'cografya'),
('Kentte ''yoğunluk'' kararının etkisi nedir?', '["Bina rengini","İklimi","Altyapı ve trafik yükünü belirlemesi","Toprak türünü"]'::jsonb, 2, 'cografya'),
('Kentsel donatı alanı neyi kapsar?', '["Sanayi parsellerini","Otoyolu","Maden sahasını","Okul, park, sağlık gibi kamusal alanları"]'::jsonb, 3, 'cografya'),
('Kent içinde sanayinin dışarı taşınmasının nedeni nedir?', '["Kirlilik ve trafik yükünü azaltmak","Maliyet artışı","İşçi azlığı","Enerji fazlası"]'::jsonb, 0, 'cografya'),
('Kentsel dönüşümde ''yerinde dönüşüm'' ne demektir?', '["Halkın taşınması","Halkın aynı bölgede kalması","Alanın boşaltılması","Yeşil alan yapılması"]'::jsonb, 1, 'cografya'),
('Kentlerde otopark planlamasının amacı nedir?', '["Trafiği artırmak","Yol daraltmak","Yol üstü park yükünü azaltmak","Bina yükseltmek"]'::jsonb, 2, 'cografya'),
('Kavşak düzenlemelerinde dönel kavşağın avantajı nedir?', '["Duraklamayı artırması","Hızı artırması","Yaya geçişini kaldırması","Akışın sürekliliğini sağlaması"]'::jsonb, 3, 'cografya'),
('Karayolunda ''viraj yarıçapı'' neyi etkiler?', '["Güvenli geçiş hızını","Yol rengini","Yol uzunluğunu","Yol genişliğini yalnızca"]'::jsonb, 0, 'cografya'),
('Karayolunda ''eğim'' sınırlarının olmasının nedeni nedir?', '["Estetik","Araç güvenliği ve tırmanma kapasitesi","Maliyet yalnızca","Manzara"]'::jsonb, 1, 'cografya'),
('Tünel yapımının coğrafi gerekçesi nedir?', '["Nüfusu artırmak","Yolu uzatmak","Dağlık engeli aşmak","Manzara sunmak"]'::jsonb, 2, 'cografya'),
('Viyadük hangi durumda tercih edilir?', '["Düz ovada","Çölde","Deniz üstünde yalnızca","Vadi ve derin çöküntüleri geçmede"]'::jsonb, 3, 'cografya'),
('Demiryolu güzergâhında eğimin düşük tutulmasının nedeni nedir?', '["Tekerlek-ray sürtünmesinin azlığı","Estetik kaygı","Hız sınırı","Maliyet düşüklüğü"]'::jsonb, 0, 'cografya'),
('Havalimanı yer seçiminde temel ölçüt nedir?', '["Manzara","Düz arazi ve rüzgâr yönü","Nüfus yoğunluğu","Maden varlığı"]'::jsonb, 1, 'cografya'),
('Liman yer seçiminde aranan özellik nedir?', '["Sığ kıyı","Dalgalı açık deniz","Doğal korunaklı ve derin koy","Bataklık"]'::jsonb, 2, 'cografya'),
('Boru hattı güzergâhında hangi risk gözetilir?', '["Nüfus yoğunluğu yalnızca","Manzara","İklim güzelliği","Fay hatları ve heyelan alanları"]'::jsonb, 3, 'cografya'),
('Enerji nakil hatlarının güzergâh seçiminde ölçüt nedir?', '["Kısa mesafe ve erişilebilirlik","Manzara","Nüfus","Toprak rengi"]'::jsonb, 0, 'cografya'),
('Baraj yeri seçiminde aranan jeolojik özellik nedir?', '["Killi gevşek zemin","Sağlam ve geçirimsiz zemin","Fay üstü","Karstik zemin"]'::jsonb, 1, 'cografya'),
('Karstik alanlarda baraj yapımının riski nedir?', '["Suyun donması","Suyun tuzlanması","Suyun yer altına kaçması","Suyun ısınması"]'::jsonb, 2, 'cografya'),
('Hidroelektrik santralde ''düşü yüksekliği'' neyi etkiler?', '["Su rengini","Su sıcaklığını","Balık sayısını","Üretilebilecek enerji miktarını"]'::jsonb, 3, 'cografya'),
('Nehir tipi hidroelektrik santralin özelliği nedir?', '["Büyük depolama yapmaması","Büyük göl oluşturması","Rüzgârla çalışması","Güneşle çalışması"]'::jsonb, 0, 'cografya'),
('Rüzgâr türbini yerleşiminde ''iz etkisi'' ne demektir?', '["Gölge oluşturması","Öndeki türbinin arkadakini etkilemesi","Ses yapması","Kuş göçü"]'::jsonb, 1, 'cografya'),
('Güneş santrallerinde panel eğiminin belirlenmesinde ölçüt nedir?', '["Rüzgâr hızı","Nem","Enlem ve ışınım açısı","Toprak türü"]'::jsonb, 2, 'cografya'),
('Jeotermal sahada reenjeksiyon neden yapılır?', '["Isıyı artırmak","Su satmak","Kirletmek","Rezervuar basıncını korumak"]'::jsonb, 3, 'cografya'),
('Sera gazı salımı en yüksek sektörlerden biri hangisidir?', '["Enerji üretimi","Kütüphanecilik","Turizm rehberliği","Grafik tasarım"]'::jsonb, 0, 'cografya'),
('Ulaşımda emisyonu azaltmanın etkili yolu nedir?', '["Araç sayısını artırmak","Toplu ve raylı sisteme geçiş","Yol genişletmek","Hız artırmak"]'::jsonb, 1, 'cografya'),
('Tarımda sera gazı salımının başlıca kaynağı nedir?', '["Sulama","Hasat","Hayvancılık ve gübre kullanımı","Depolama"]'::jsonb, 2, 'cografya'),
('Atık yönetiminde hiyerarşinin ilk basamağı nedir?', '["Geri dönüşüm","Yakma","Depolama","Önleme ve azaltma"]'::jsonb, 3, 'cografya'),
('Kompost tesisinin çıktısı nedir?', '["Toprak iyileştirici organik gübre","Metal hurda","Cam kırığı","Plastik granül"]'::jsonb, 0, 'cografya'),
('Atıktan enerji tesislerinin amacı nedir?', '["Atığı depolamak","Atığı enerjiye dönüştürmek","Atığı gömmek","Atığı ihraç etmek"]'::jsonb, 1, 'cografya'),
('Mikroplastik kirliliğinin ana kaynaklarından biri nedir?', '["Kum","Kaya","Parçalanan plastik atıklar","Odun"]'::jsonb, 2, 'cografya'),
('Deniz çöplerinin ekosisteme etkisi nedir?', '["Besin sağlaması","Suyu temizlemesi","Oksijen üretmesi","Canlıların yutması ve dolanması"]'::jsonb, 3, 'cografya'),
('Sahil temizliği çalışmalarının çevresel değeri nedir?', '["Atığın denize karışmasını önlemek","Turizmi kısıtlamak","Balığı azaltmak","Kumu almak"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
