-- Soru havuzu genişletme: cografya +134
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Erciyes Dağı hangi ilimizin sınırlarındadır?', '["Kayseri","Niğde","Nevşehir","Sivas"]'::jsonb, 0, 'cografya'),
('Süphan Dağı hangi gölün kuzeyinde yükselir?', '["Tuz Gölü","Van Gölü","Beyşehir Gölü","İznik Gölü"]'::jsonb, 1, 'cografya'),
('Kaçkar Dağları hangi bölgemizde yer alır?', '["Batı Karadeniz","Doğu Anadolu","Doğu Karadeniz","İç Anadolu"]'::jsonb, 2, 'cografya'),
('Uludağ hangi ilimizin sınırları içindedir?', '["Balıkesir","Kütahya","Bilecik","Bursa"]'::jsonb, 3, 'cografya'),
('Nemrut Krater Gölü hangi ilimizdedir?', '["Bitlis","Adıyaman","Van","Muş"]'::jsonb, 0, 'cografya'),
('Toros Dağları hangi kıyımız boyunca uzanır?', '["Ege","Akdeniz","Karadeniz","Marmara"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en uzun akarsuyu hangisidir?', '["Sakarya","Fırat","Kızılırmak","Yeşilırmak"]'::jsonb, 2, 'cografya'),
('Seyhan ve Ceyhan nehirleri hangi ovayı sular?', '["Konya Ovası","Bafra Ovası","Amik Ovası","Çukurova"]'::jsonb, 3, 'cografya'),
('Meriç Nehri hangi bölgemizde akar?', '["Trakya","Ege","İç Anadolu","Karadeniz"]'::jsonb, 0, 'cografya'),
('Tuz Gölü hangi bölgemizde yer alır?', '["Doğu Anadolu","İç Anadolu","Akdeniz","Ege"]'::jsonb, 1, 'cografya'),
('Beyşehir Gölü hangi ilimizin sınırlarındadır?', '["Isparta","Antalya","Konya","Burdur"]'::jsonb, 2, 'cografya'),
('Bafa Gölü nasıl oluşmuş bir göldür?', '["Krater gölü","Buzul gölü","Karstik göl","Kıyı seti gölü"]'::jsonb, 3, 'cografya'),
('Salda Gölü hangi ilimizde bulunur?', '["Burdur","Isparta","Denizli","Antalya"]'::jsonb, 0, 'cografya'),
('GAP projesi hangi iki nehir havzasını kapsar?', '["Kızılırmak ve Yeşilırmak","Fırat ve Dicle","Sakarya ve Susurluk","Seyhan ve Ceyhan"]'::jsonb, 1, 'cografya'),
('Konya Ovası hangi tarım ürününde öne çıkar?', '["Çay","Fındık","Tahıl","Muz"]'::jsonb, 2, 'cografya'),
('Çay tarımı Türkiye''de ağırlıklı olarak nerede yapılır?', '["Ege","Akdeniz","Marmara","Doğu Karadeniz"]'::jsonb, 3, 'cografya'),
('Fındık üretimi Türkiye''de hangi bölgede yoğunlaşır?', '["Karadeniz","Ege","İç Anadolu","Güneydoğu"]'::jsonb, 0, 'cografya'),
('Muz tarımı Türkiye''de hangi kıyıda yapılır?', '["Karadeniz","Akdeniz","Marmara","Ege"]'::jsonb, 1, 'cografya'),
('Zeytin üretimi Türkiye''de hangi bölgede yoğundur?', '["Doğu Anadolu","İç Anadolu","Ege","Karadeniz"]'::jsonb, 2, 'cografya'),
('Antep fıstığı üretimi hangi bölgemizde öne çıkar?', '["Marmara","Karadeniz","Ege","Güneydoğu Anadolu"]'::jsonb, 3, 'cografya'),
('Türkiye''de pamuk tarımı en çok hangi ovada yapılır?', '["Çukurova","Bafra Ovası","Erzurum Ovası","Muş Ovası"]'::jsonb, 0, 'cografya'),
('Karadeniz ikliminin belirgin özelliği nedir?', '["Yazın kurak olması","Her mevsim yağışlı olması","Kışın kar yağmaması","Yıl boyu sıcak olması"]'::jsonb, 1, 'cografya'),
('Akdeniz ikliminde yazlar nasıl geçer?', '["Serin ve yağışlı","Soğuk ve karlı","Sıcak ve kurak","Ilık ve nemli"]'::jsonb, 2, 'cografya'),
('Karasal iklimin en belirgin özelliği nedir?', '["Yıl boyu yağış","Kışların ılık geçmesi","Nem oranının yüksekliği","Gece gündüz sıcaklık farkının fazlalığı"]'::jsonb, 3, 'cografya'),
('Bozkır (step) bitki örtüsü hangi bölgede yaygındır?', '["İç Anadolu","Doğu Karadeniz","Batı Ege","Marmara kıyıları"]'::jsonb, 0, 'cografya'),
('Türkiye''de sıcaklık genel olarak hangi yöne gidildikçe azalır?', '["Güney ve batıya","Kuzey ve doğuya","Yalnız batıya","Yalnız güneye"]'::jsonb, 1, 'cografya'),
('Boğazlar (İstanbul ve Çanakkale) hangi iki denizi bağlar?', '["Ege ve Akdeniz","Karadeniz ve Hazar","Karadeniz ve Ege","Akdeniz ve Kızıldeniz"]'::jsonb, 2, 'cografya'),
('Çanakkale Boğazı hangi iki denizi birleştirir?', '["Karadeniz ve Marmara","Ege ve Akdeniz","Marmara ve Akdeniz","Marmara ve Ege"]'::jsonb, 3, 'cografya'),
('Bozcaada hangi ilimize bağlıdır?', '["Çanakkale","Balıkesir","İzmir","Edirne"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en batı ucu hangi burundur?', '["İnceburun","Baba Burnu","Dalko Burnu","Anamur Burnu"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en kuzey noktası hangi ilimizdedir?', '["Samsun","Kastamonu","Sinop","Zonguldak"]'::jsonb, 2, 'cografya'),
('Türkiye''nin en güney noktası hangi ilimizdedir?', '["Mersin","Antalya","Adana","Hatay"]'::jsonb, 3, 'cografya'),
('Kapadokya bölgesi ağırlıklı olarak hangi ilimizdedir?', '["Nevşehir","Kayseri","Aksaray","Niğde"]'::jsonb, 0, 'cografya'),
('Karstik şekiller hangi kayaç türünde oluşur?', '["Granit","Kireçtaşı","Bazalt","Kumtaşı"]'::jsonb, 1, 'cografya'),
('Mağarada yukarıdan aşağı doğru uzayan oluşuma ne denir?', '["Dikit","Sütun","Sarkıt","Traverten"]'::jsonb, 2, 'cografya'),
('Delta ovası nasıl oluşur?', '["Buzul aşındırır","Rüzgâr biriktirir","Volkan püskürür","Akarsu alüvyonu denizde biriktirir"]'::jsonb, 3, 'cografya'),
('Türkiye''de delta oluşumuna örnek olan ova hangisidir?', '["Çukurova","Konya Ovası","Erzurum Ovası","Muş Ovası"]'::jsonb, 0, 'cografya'),
('Falez (yalıyar) hangi etkiyle oluşur?', '["Buzul hareketiyle","Deniz dalgalarının aşındırmasıyla","Rüzgâr birikimiyle","Akarsu birikimiyle"]'::jsonb, 1, 'cografya'),
('Moren birikintileri hangi etkenin ürünüdür?', '["Akarsu","Rüzgâr","Buzul","Dalga"]'::jsonb, 2, 'cografya'),
('Barkan (hilal kumulu) hangi etkenin ürünüdür?', '["Buzul","Akarsu","Deniz","Rüzgâr"]'::jsonb, 3, 'cografya'),
('Menderes (kıvrım) oluşumu akarsuyun hangi özelliğini gösterir?', '["Eğimin azaldığını","Debisinin sıfırlandığını","Kaynağına yaklaştığını","Donmuş olduğunu"]'::jsonb, 0, 'cografya'),
('Akarsuyun birim zamanda taşıdığı su miktarına ne denir?', '["Rejim","Debi","Havza","Profil"]'::jsonb, 1, 'cografya'),
('Akarsu rejimi neyi ifade eder?', '["Suyun sıcaklığını","Yatağın genişliğini","Debinin yıl içindeki değişimini","Kaynağın yüksekliğini"]'::jsonb, 2, 'cografya'),
('İki akarsu havzasını birbirinden ayıran sınıra ne denir?', '["Taban seviyesi","Menderes","Delta","Su bölümü çizgisi"]'::jsonb, 3, 'cografya'),
('Akarsuyun aşındırabileceği en alt seviyeye ne denir?', '["Taban seviyesi","Kaynak seviyesi","Su bölümü","Debi eşiği"]'::jsonb, 0, 'cografya'),
('Heyelanın en önemli tetikleyicisi nedir?', '["Kuraklık","Aşırı yağış ve eğim","Rüzgâr","Yüksek sıcaklık"]'::jsonb, 1, 'cografya'),
('Türkiye''de heyelan en çok hangi bölgede görülür?', '["İç Anadolu","Güneydoğu Anadolu","Karadeniz","Marmara"]'::jsonb, 2, 'cografya'),
('Deprem şiddetini ölçen ölçeğe ne ad verilir?', '["Beaufort ölçeği","Mohs ölçeği","Celsius ölçeği","Mercalli ölçeği"]'::jsonb, 3, 'cografya'),
('Deprem dalgalarının kaynaklandığı yer altı noktasına ne denir?', '["İç merkez (hiposantr)","Dış merkez","Fay düzlemi","Kırık hattı"]'::jsonb, 0, 'cografya'),
('Kuzey Anadolu Fay Hattı hangi yönde uzanır?', '["Kuzey-güney","Doğu-batı","Kuzeydoğu-güneybatı","Dairesel"]'::jsonb, 1, 'cografya'),
('Türkiye''nin deprem riski en düşük bölgesi hangisidir?', '["Marmara","Ege","Güneydoğu Anadolu''nun güneyi","Doğu Anadolu"]'::jsonb, 2, 'cografya'),
('Volkanik dağların tepesindeki çukurluğa ne denir?', '["Kaldera","Obruk","Doğal köprü","Krater"]'::jsonb, 3, 'cografya'),
('Bir volkan konisinin çökmesiyle oluşan geniş çukura ne denir?', '["Kaldera","Krater","Lagün","Delta"]'::jsonb, 0, 'cografya'),
('Türkiye''de sönmüş volkanlara örnek hangi dağdır?', '["Uludağ","Ağrı Dağı","Kaçkar","Ilgaz"]'::jsonb, 1, 'cografya'),
('Jeotermal kaynaklar hangi jeolojik özellikle ilişkilidir?', '["Buzullaşma","Delta oluşumu","Volkanizma ve fay hatları","Kumul hareketi"]'::jsonb, 2, 'cografya'),
('Traverten oluşumu hangi suyla ilgilidir?', '["Tuzlu deniz suyu","Buzul suyu","Yağmur suyu","Kireç yüklü sıcak su"]'::jsonb, 3, 'cografya'),
('Türkiye''de bor madeni rezervi bakımından öne çıkan il hangisidir?', '["Balıkesir","Trabzon","Sivas","Erzurum"]'::jsonb, 0, 'cografya'),
('Zonguldak hangi maden kaynağıyla anılır?', '["Bakır","Taş kömürü","Krom","Bor"]'::jsonb, 1, 'cografya'),
('Türkiye''de linyit çıkarımıyla anılan il hangisidir?', '["Rize","Ordu","Kütahya","Edirne"]'::jsonb, 2, 'cografya'),
('Ergani hangi madenle anılır?', '["Kömür","Demir","Altın","Bakır"]'::jsonb, 3, 'cografya'),
('Divriği hangi madenin çıkarıldığı yerdir?', '["Demir","Bor","Krom","Kurşun"]'::jsonb, 0, 'cografya'),
('Bir bölgeden dışarıya sürekli göç verilmesi neye yol açar?', '["Nüfusun artmasına","Nüfusun azalmasına","Doğum oranının artmasına","Yüzölçümünün büyümesine"]'::jsonb, 1, 'cografya'),
('Mevsimlik tarım göçü hangi tür göze örnektir?', '["Kalıcı göç","Zorunlu göç","Geçici göç","Beyin göçü"]'::jsonb, 2, 'cografya'),
('Kentleşmenin en önemli nedeni nedir?', '["Kırsalda nüfus artışı","İklim değişimi","Yol yapımı","İş olanaklarının kentte toplanması"]'::jsonb, 3, 'cografya'),
('Dağlık alanlarda nüfusun seyrek olmasının temel nedeni nedir?', '["Tarım ve ulaşım güçlüğü","Su kaynağının olmaması","Yağışın fazlalığı","Toprağın tuzlu olması"]'::jsonb, 0, 'cografya'),
('Yayla yerleşmesi hangi ekonomik faaliyete bağlıdır?', '["Madencilik","Hayvancılık","Balıkçılık","Sanayi"]'::jsonb, 1, 'cografya'),
('Dağınık yerleşme hangi koşulda görülür?', '["Kurak düzlüklerde","Çöllerde","Su ve arazinin bol olduğu engebede","Kutuplarda"]'::jsonb, 2, 'cografya'),
('Harita ölçeği büyüdükçe ayrıntı nasıl değişir?', '["Azalır","Değişmez","Sıfırlanır","Artar"]'::jsonb, 3, 'cografya'),
('1/1.000.000 ölçekli harita hangi tür haritadır?', '["Küçük ölçekli","Büyük ölçekli","Kadastro haritası","Plan"]'::jsonb, 0, 'cografya'),
('İzohips (eş yükselti) eğrileri neyi gösterir?', '["Aynı sıcaklıktaki noktaları","Aynı yükseklikteki noktaları","Aynı yağış alan yerleri","Aynı nüfuslu alanları"]'::jsonb, 1, 'cografya'),
('İzohips eğrilerinin sıklaşması neyi gösterir?', '["Yükseltinin azaldığını","Yağışın arttığını","Eğimin arttığını","Nüfusun arttığını"]'::jsonb, 2, 'cografya'),
('İzoterm eğrileri neyi gösterir?', '["Eşit yükseklikleri","Eşit yağışı","Eşit basıncı","Eşit sıcaklıktaki yerleri"]'::jsonb, 3, 'cografya'),
('İzobar eğrileri neyi gösterir?', '["Eşit basınçtaki yerleri","Eşit sıcaklığı","Eşit nemi","Eşit yüksekliği"]'::jsonb, 0, 'cografya'),
('Paralellerin en uzunu hangisidir?', '["Yengeç Dönencesi","Ekvator","Oğlak Dönencesi","Kutup dairesi"]'::jsonb, 1, 'cografya'),
('Meridyenler arasındaki yerel saat farkı kaç dakikadır?', '["1 dakika","15 dakika","4 dakika","60 dakika"]'::jsonb, 2, 'cografya'),
('Başlangıç meridyeni hangi gözlemevinden geçer?', '["Paris","Roma","Kahire","Greenwich"]'::jsonb, 3, 'cografya'),
('Ekvator''un uzunluğu yaklaşık ne kadardır?', '["40 bin kilometre","10 bin kilometre","100 bin kilometre","4 bin kilometre"]'::jsonb, 0, 'cografya'),
('Yengeç Dönencesi kaçıncı paralelde yer alır?', '["0°","23° 27'' kuzey","45° kuzey","66° 33'' kuzey"]'::jsonb, 1, 'cografya'),
('21 Haziran''da Kuzey Yarım Küre''de hangi mevsim başlar?', '["Kış","İlkbahar","Yaz","Sonbahar"]'::jsonb, 2, 'cografya'),
('Dünya''nın Güneş''e en yakın olduğu konuma ne denir?', '["Günöte (afel)","Ekinoks","Solstis","Günberi (perihel)"]'::jsonb, 3, 'cografya'),
('Yerel saat farkının nedeni nedir?', '["Dünya''nın kendi ekseni etrafında dönmesi","Eksen eğikliği","Yıllık hareket","Ay tutulması"]'::jsonb, 0, 'cografya'),
('Uluslararası tarih değiştirme çizgisi hangi meridyene yakındır?', '["0. meridyen","180. meridyen","90. meridyen","45. meridyen"]'::jsonb, 1, 'cografya'),
('Alizeler hangi kuşakta esen sürekli rüzgârlardır?', '["Kutup kuşağı","Orta kuşak","Tropikal kuşak","Ekvator üstü kuşak"]'::jsonb, 2, 'cografya'),
('Muson iklimi en belirgin olarak hangi kıtada görülür?', '["Avrupa","Kuzey Amerika","Antarktika","Asya"]'::jsonb, 3, 'cografya'),
('Muson yağmurları hangi mevsimde yoğunlaşır?', '["Yaz","Kış","İlkbahar","Sonbahar"]'::jsonb, 0, 'cografya'),
('Ekvatoral iklimin bitki örtüsü nedir?', '["Bozkır","Yağmur ormanı","Tundra","Maki"]'::jsonb, 1, 'cografya'),
('Tundra bitki örtüsü hangi kuşakta görülür?', '["Tropikal","Ekvatoral","Kutup altı","Akdeniz"]'::jsonb, 2, 'cografya'),
('Savan bitki örtüsü hangi iklimde görülür?', '["Tundra iklimi","Okyanusal iklim","Karasal iklim","Tropikal (savan) iklim"]'::jsonb, 3, 'cografya'),
('Taygalar hangi ağaç türünden oluşur?', '["İğne yapraklı","Geniş yapraklı","Kaktüs","Palmiye"]'::jsonb, 0, 'cografya'),
('Sahra Çölü''nün güneyindeki geçiş kuşağına ne ad verilir?', '["Pampa","Sahel","Step","Tayga"]'::jsonb, 1, 'cografya'),
('Atacama Çölü hangi kıtadadır?', '["Afrika","Asya","Güney Amerika","Avustralya"]'::jsonb, 2, 'cografya'),
('Gobi Çölü hangi iki ülke arasında uzanır?', '["İran ve Irak","Hindistan ve Pakistan","Rusya ve Kazakistan","Çin ve Moğolistan"]'::jsonb, 3, 'cografya'),
('Himalaya Dağları hangi iki levhanın çarpışmasıyla oluşmuştur?', '["Hint ve Avrasya","Afrika ve Avrupa","Pasifik ve Kuzey Amerika","Nazca ve Güney Amerika"]'::jsonb, 0, 'cografya'),
('Alpler hangi kıtada yer alır?', '["Asya","Avrupa","Afrika","Güney Amerika"]'::jsonb, 1, 'cografya'),
('Kilimanjaro Dağı hangi ülkededir?', '["Kenya","Etiyopya","Tanzanya","Uganda"]'::jsonb, 2, 'cografya'),
('Victoria Gölü hangi kıtadadır?', '["Asya","Güney Amerika","Avustralya","Afrika"]'::jsonb, 3, 'cografya'),
('Marianas Çukuru hangi okyanustadır?', '["Pasifik","Atlas","Hint","Arktik"]'::jsonb, 0, 'cografya'),
('Cebelitarık Boğazı hangi iki su kütlesini bağlar?', '["Kızıldeniz ve Hint Okyanusu","Akdeniz ve Atlas Okyanusu","Karadeniz ve Marmara","Baltık ve Kuzey Denizi"]'::jsonb, 1, 'cografya'),
('Hürmüz Boğazı hangi körfezin çıkışındadır?', '["Aden Körfezi","Meksika Körfezi","Basra Körfezi","Biscay Körfezi"]'::jsonb, 2, 'cografya'),
('Malakka Boğazı hangi iki ülke arasındadır?', '["Japonya ve Kore","Hindistan ve Sri Lanka","Çin ve Vietnam","Malezya ve Endonezya"]'::jsonb, 3, 'cografya'),
('Bering Boğazı hangi iki kıtayı ayırır?', '["Asya ve Kuzey Amerika","Avrupa ve Asya","Afrika ve Avrupa","Avustralya ve Asya"]'::jsonb, 0, 'cografya'),
('Madagaskar hangi okyanustadır?', '["Pasifik","Hint Okyanusu","Atlas","Arktik"]'::jsonb, 1, 'cografya'),
('İzlanda''nın jeolojik olarak öne çıkan özelliği nedir?', '["Çöl iklimi","Buzulsuzluk","Volkanik ve jeotermal etkinlik","Deprem olmaması"]'::jsonb, 2, 'cografya'),
('Antarktika kıtasının en belirgin özelliği nedir?', '["Tropikal olması","Yoğun nüfuslu olması","Çöl bitkileriyle kaplı olması","Buz örtüsüyle kaplı olması"]'::jsonb, 3, 'cografya'),
('Yüzölçümü en küçük kıta hangisidir?', '["Avustralya","Avrupa","Antarktika","Güney Amerika"]'::jsonb, 0, 'cografya'),
('Süveyş Kanalı hangi ülkenin topraklarındadır?', '["Suudi Arabistan","Mısır","İsrail","Ürdün"]'::jsonb, 1, 'cografya'),
('Kazakistan''ın başkenti hangisidir?', '["Almatı","Taşkent","Astana","Bişkek"]'::jsonb, 2, 'cografya'),
('Fas''ın başkenti hangisidir?', '["Kazablanka","Marakeş","Fes","Rabat"]'::jsonb, 3, 'cografya'),
('Nijerya''nın başkenti hangisidir?', '["Abuja","Lagos","Kano","Ibadan"]'::jsonb, 0, 'cografya'),
('Güney Afrika Cumhuriyeti''nin yasama başkenti hangisidir?', '["Johannesburg","Cape Town","Durban","Port Elizabeth"]'::jsonb, 1, 'cografya'),
('Vietnam''ın başkenti hangisidir?', '["Ho Chi Minh","Da Nang","Hanoi","Hue"]'::jsonb, 2, 'cografya'),
('Myanmar''ın başkenti hangisidir?', '["Yangon","Mandalay","Bago","Nay Pyi Taw"]'::jsonb, 3, 'cografya'),
('Bolivya''nın yönetim merkezi hangisidir?', '["La Paz","Sucre","Santa Cruz","Cochabamba"]'::jsonb, 0, 'cografya'),
('Vatikan hangi şehrin içindedir?', '["Milano","Roma","Floransa","Napoli"]'::jsonb, 1, 'cografya'),
('Yüzölçümü en küçük ülke hangisidir?', '["Monako","San Marino","Vatikan","Malta"]'::jsonb, 2, 'cografya'),
('Kıtalar arasında yer alan tek ülke olarak anılan Türkiye hangi iki kıtadadır?', '["Avrupa ve Afrika","Asya ve Afrika","Avrupa ve Amerika","Asya ve Avrupa"]'::jsonb, 3, 'cografya'),
('Skandinavya Yarımadası''nda hangi ülkeler yer alır?', '["Norveç ve İsveç","Danimarka ve Hollanda","Finlandiya ve Estonya","İzlanda ve İrlanda"]'::jsonb, 0, 'cografya'),
('İber Yarımadası''nda hangi iki ülke bulunur?', '["İtalya ve Yunanistan","İspanya ve Portekiz","Fransa ve Belçika","Hırvatistan ve Slovenya"]'::jsonb, 1, 'cografya'),
('Balkan Yarımadası hangi kıtada yer alır?', '["Asya","Afrika","Avrupa","Amerika"]'::jsonb, 2, 'cografya'),
('Arap Yarımadası''nın en büyük ülkesi hangisidir?', '["Yemen","Umman","Katar","Suudi Arabistan"]'::jsonb, 3, 'cografya'),
('Denize kıyısı olmayan ülkelere ne ad verilir?', '["Karayla çevrili ülke","Ada ülkesi","Yarımada ülkesi","Takımada ülkesi"]'::jsonb, 0, 'cografya'),
('Endonezya coğrafi olarak nasıl bir ülkedir?', '["Karayla çevrili ülke","Takımada ülkesi","Yarımada ülkesi","Kıta ülkesi"]'::jsonb, 1, 'cografya'),
('Panama Kanalı''nın ekonomik önemi nedir?', '["Tatlı su sağlaması","Elektrik üretmesi","Deniz yolunu kısaltması","Sulama yapması"]'::jsonb, 2, 'cografya'),
('Victoria Şelalesi hangi nehir üzerindedir?', '["Nil","Kongo","Nijer","Zambezi"]'::jsonb, 3, 'cografya'),
('El Nino olayı hangi okyanusta gözlenir?', '["Pasifik","Atlas","Hint","Arktik"]'::jsonb, 0, 'cografya'),
('Gulf Stream (Golf Akıntısı) hangi etkiyi yaratır?', '["Sahra''yı soğutur","Batı Avrupa''yı ılıtır","Asya''ya yağmur getirir","Kutupları ısıtmaz"]'::jsonb, 1, 'cografya'),
('Sıcak su akıntılarının kıyı iklimine etkisi nedir?', '["Kuraklık yaratır","Sıcaklığı düşürür","Sıcaklığı ve yağışı artırır","Etkisi yoktur"]'::jsonb, 2, 'cografya'),
('Gelgit olayının temel nedeni nedir?', '["Rüzgârlar","Deprem","Volkanizma","Ay ve Güneş''in çekim etkisi"]'::jsonb, 3, 'cografya'),
('Sera etkisinin artması hangi sonuca yol açar?', '["Küresel ısınma","Buzul çağı","Yağışın durması","Eksen kayması"]'::jsonb, 0, 'cografya'),
('Ozon tabakasının işlevi nedir?', '["Yağmur oluşturmak","Zararlı morötesi ışınları süzmek","Rüzgâr yaratmak","Isı üretmek"]'::jsonb, 1, 'cografya'),
('Atmosferin hava olaylarının gerçekleştiği katmanı hangisidir?', '["Stratosfer","Mezosfer","Troposfer","Termosfer"]'::jsonb, 2, 'cografya'),
('Yükseklik arttıkça atmosfer basıncı nasıl değişir?', '["Artar","Değişmez","Önce artar sonra azalır","Azalır"]'::jsonb, 3, 'cografya'),
('Bağıl nem yüzde yüze ulaştığında ne olur?', '["Yoğuşma başlar","Buharlaşma hızlanır","Basınç düşer","Rüzgâr durur"]'::jsonb, 0, 'cografya'),
('Yamaç (orografik) yağışı nasıl oluşur?', '["Cepheler karşılaşınca","Nemli hava dağ yamacında yükselince","Hava aşırı ısınınca","Basınç yükselince"]'::jsonb, 1, 'cografya')
on conflict (soru) do nothing;
