-- Soru havuzu genişletme — Parti 8: Spor + Sanat + Edebiyat
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Futbolda penaltı noktası kaleye kaç metre uzaklıktadır?', '["11","9","12","10"]'::jsonb, 0, 'spor'),
('Futbolda köşe vuruşu hangi durumda verilir?', '["Top savunmadan auta çıkınca","Faul olunca","Ofsayt olunca","Elle oynanınca"]'::jsonb, 0, 'spor'),
('Futbolda kırmızı kart ne anlama gelir?', '["Oyundan ihraç","Uyarı","Penaltı","Değişiklik"]'::jsonb, 0, 'spor'),
('Bir futbolcu aynı maçta iki sarı kart görürse ne olur?', '["Kırmızı kartla atılır","Penaltı verilir","Ceza sahası dışına çıkar","Bir maç ceza alır"]'::jsonb, 0, 'spor'),
('Futbolda hat-trick ne demektir?', '["Bir maçta 3 gol atmak","3 asist yapmak","3 maç üst üste gol","3 kurtarış"]'::jsonb, 0, 'spor'),
('Türkiye''nin üç büyük kulübü hangi şehirdendir?', '["İstanbul","Ankara","İzmir","Bursa"]'::jsonb, 0, 'spor'),
('Trabzonspor''un renkleri nedir?', '["Bordo-mavi","Sarı-kırmızı","Siyah-beyaz","Sarı-lacivert"]'::jsonb, 0, 'spor'),
('Galatasaray''ın renkleri nedir?', '["Sarı-kırmızı","Sarı-lacivert","Bordo-mavi","Kırmızı-beyaz"]'::jsonb, 0, 'spor'),
('Fenerbahçe''nin renkleri nedir?', '["Sarı-lacivert","Sarı-kırmızı","Mavi-beyaz","Yeşil-sarı"]'::jsonb, 0, 'spor'),
('Beşiktaş''ın renkleri nedir?', '["Siyah-beyaz","Kırmızı-beyaz","Mavi-siyah","Yeşil-beyaz"]'::jsonb, 0, 'spor'),
('Süper Lig''de bir sezonda her takım kaç maç oynar (18 takımlı ligde)?', '["34","38","30","36"]'::jsonb, 0, 'spor'),
('Galibiyette takıma kaç puan verilir?', '["3","2","1","5"]'::jsonb, 0, 'spor'),
('Şampiyonlar Ligi müziği hangi bestecinin eserinden uyarlanmıştır?', '["Handel","Mozart","Bach","Wagner"]'::jsonb, 0, 'spor'),
('Ballon d''Or (Altın Top) ödülü kime verilir?', '["Yılın en iyi futbolcusuna","En golcü oyuncuya","En iyi kaleciye","En iyi teknik direktöre"]'::jsonb, 0, 'spor'),
('Arda Güler hangi pozisyonda oynar?', '["Orta saha/forvet arkası","Kaleci","Stoper","Sol bek"]'::jsonb, 0, 'spor'),
('NBA''de bir maç kaç periyottan oluşur?', '["4","2","3","6"]'::jsonb, 0, 'spor'),
('Basketbolda üç sayılık atış nereden atılır?', '["Üç sayı çizgisi gerisinden","Pota altından","Serbest atış çizgisinden","Orta sahadan"]'::jsonb, 0, 'spor'),
('Basketbolda smaç ne demektir?', '["Topu potaya yukarıdan basmak","Uzaktan atış","Top çalmak","Blok yapmak"]'::jsonb, 0, 'spor'),
('12 Dev Adam hangi spor dalımızın milli takımıdır?', '["Basketbol","Voleybol","Futbol","Hentbol"]'::jsonb, 0, 'spor'),
('NBA''de oynayan ilk Türk basketbolcu kimdir?', '["Mirsad Türkcan","Hedo Türkoğlu","Mehmet Okur","Ersan İlyasova"]'::jsonb, 0, 'spor'),
('Voleybolda file üzerinde topu yere indirme vuruşuna ne denir?', '["Smaç","Manşet","Blok","Plase"]'::jsonb, 0, 'spor'),
('Voleybolda maç kaç set üzerinden oynanır?', '["5 set (3 kazanan)","3 set","7 set","4 set"]'::jsonb, 0, 'spor'),
('Teniste "ace" ne demektir?', '["Karşılanamayan servis","Çift hata","File topu","Uzun ralli"]'::jsonb, 0, 'spor'),
('Roland Garros hangi zeminde oynanır?', '["Toprak","Çim","Sert kort","Halı"]'::jsonb, 0, 'spor'),
('Wimbledon hangi zeminde oynanır?', '["Çim","Toprak","Sert kort","Parke"]'::jsonb, 0, 'spor'),
('Masa tenisinde servis kaç sayıda bir el değiştirir?', '["2","5","3","1"]'::jsonb, 0, 'spor'),
('Badmintonda topa ne ad verilir?', '["Tüytop","Raket topu","Servis topu","Mini top"]'::jsonb, 0, 'spor'),
('Yüzme havuzunun olimpik uzunluğu kaç metredir?', '["50","25","100","75"]'::jsonb, 0, 'spor'),
('Atletizmde en kısa koşu mesafesi hangisidir?', '["100 m","200 m","60 m salon","400 m"]'::jsonb, 0, 'spor'),
('Dekatlon kaç branştan oluşur?', '["10","7","5","12"]'::jsonb, 0, 'spor'),
('Heptatlon kaç branştan oluşur?', '["7","10","5","8"]'::jsonb, 0, 'spor'),
('Yüksek atlamada hangi teknik yaygın kullanılır?', '["Fosbury Flop","Makas","Dalış","Burgu"]'::jsonb, 0, 'spor'),
('Sırıkla atlamada sporcular yaklaşık kaç metreyi aşabilir?', '["6","3","10","8"]'::jsonb, 0, 'spor'),
('Cirit atma hangi spor dalına girer?', '["Atletizm","Güreş","Binicilik","Okçuluk"]'::jsonb, 0, 'spor'),
('Halterde iki temel hareket hangileridir?', '["Koparma ve silkme","İtme ve çekme","Kaldırma ve indirme","Pres ve squat"]'::jsonb, 0, 'spor'),
('Boksta ringin köşe sayısı kaçtır?', '["4","3","6","8"]'::jsonb, 0, 'spor'),
('Boks maçında raundlar arası dinlenme süresi kaç dakikadır?', '["1","2","3","5"]'::jsonb, 0, 'spor'),
('Karatede siyah kuşak neyi simgeler?', '["Ustalık","Başlangıç","Orta seviye","Hakemlik"]'::jsonb, 0, 'spor'),
('Olimpiyatlarda altın madalya kazanan ilk Türk kadın sporcu Nurcan Taylan hangi branştadır?', '["Halter","Güreş","Tekvando","Atletizm"]'::jsonb, 0, 'spor'),
('Survivor yarışması hangi tür yarışmadır?', '["Doğada mücadele","Bilgi yarışması","Müzik yarışması","Yemek yarışması"]'::jsonb, 0, 'genel'),
('Satrançta "rok" hamlesi hangi taşlarla yapılır?', '["Şah ve kale","Şah ve vezir","Kale ve fil","Vezir ve at"]'::jsonb, 0, 'spor'),
('Satrançta piyon son sıraya ulaşınca ne olur?', '["Terfi eder","Oyundan çıkar","Geri döner","Şah olur"]'::jsonb, 0, 'spor'),
('Satrançta at nasıl hareket eder?', '["L şeklinde","Çapraz","Düz","Tek kare her yöne"]'::jsonb, 0, 'spor'),
('Go oyunu hangi ülkede doğmuştur?', '["Çin","Japonya","Kore","Hindistan"]'::jsonb, 0, 'genel'),
('Tavla kaç pul ile oynanır (her oyuncu)?', '["15","12","16","10"]'::jsonb, 0, 'genel'),
('Picasso hangi ülkede doğmuştur?', '["İspanya","Fransa","İtalya","Portekiz"]'::jsonb, 0, 'sanat'),
('Van Gogh hangi ülkede doğmuştur?', '["Hollanda","Belçika","Fransa","Almanya"]'::jsonb, 0, 'sanat'),
('Frida Kahlo hangi ülkenin ressamıdır?', '["Meksika","İspanya","Arjantin","Küba"]'::jsonb, 0, 'sanat'),
('Andy Warhol hangi sanat akımının öncüsüdür?', '["Pop art","Kübizm","Sürrealizm","Empresyonizm"]'::jsonb, 0, 'sanat'),
('Banksy hangi sanat türüyle tanınır?', '["Sokak sanatı","Heykel","Yağlı boya","Seramik"]'::jsonb, 0, 'sanat'),
('"İnci Küpeli Kız" tablosunun ressamı kimdir?', '["Vermeer","Rembrandt","Rubens","Van Eyck"]'::jsonb, 0, 'sanat'),
('"Gece Devriyesi" tablosunun ressamı kimdir?', '["Rembrandt","Vermeer","Hals","Bosch"]'::jsonb, 0, 'sanat'),
('"Venüs''ün Doğuşu" tablosunun ressamı kimdir?', '["Botticelli","Rafael","Titian","Caravaggio"]'::jsonb, 0, 'sanat'),
('"Amerikan Gotiği" tablosu hangi ülkenin ikonik eseridir?', '["ABD","İngiltere","Almanya","Kanada"]'::jsonb, 0, 'sanat'),
('Heykel "Pieta" kimin eseridir?', '["Michelangelo","Bernini","Donatello","Canova"]'::jsonb, 0, 'sanat'),
('Louvre Müzesi''nin camdan piramidi hangi mimara aittir?', '["I.M. Pei","Frank Gehry","Zaha Hadid","Le Corbusier"]'::jsonb, 0, 'sanat'),
('Guggenheim Bilbao Müzesi''nin mimarı kimdir?', '["Frank Gehry","Zaha Hadid","Norman Foster","Renzo Piano"]'::jsonb, 0, 'sanat'),
('Zaha Hadid hangi alanda dünyaca ünlüdür?', '["Mimarlık","Resim","Heykel","Moda"]'::jsonb, 0, 'sanat'),
('Türkiye''nin ünlü kadın opera sanatçısı kimdir?', '["Leyla Gencer","Sezen Aksu","Ajda Pekkan","İdil Biret"]'::jsonb, 0, 'sanat'),
('İdil Biret hangi enstrümanın virtüözüdür?', '["Piyano","Keman","Çello","Flüt"]'::jsonb, 0, 'sanat'),
('Fazıl Say hangi enstrümanı çalar?', '["Piyano","Keman","Gitar","Ney"]'::jsonb, 0, 'sanat'),
('Barış Manço hangi müzik türünün öncülerindendir?', '["Anadolu rock","Arabesk","Pop","Caz"]'::jsonb, 0, 'sanat'),
('"Minik Serçe" lakaplı sanatçımız kimdir?', '["Sezen Aksu","Ajda Pekkan","Nilüfer","Emel Sayın"]'::jsonb, 0, 'sanat'),
('"Süperstar" lakaplı sanatçımız kimdir?', '["Ajda Pekkan","Sezen Aksu","Hülya Avşar","Gülben Ergen"]'::jsonb, 0, 'sanat'),
('Zeki Müren hangi müzik türünün ustasıydı?', '["Türk sanat müziği","Halk müziği","Rock","Caz"]'::jsonb, 0, 'sanat'),
('Aşık Veysel hangi enstrümanıyla özdeşleşmiştir?', '["Bağlama","Ud","Kaval","Zurna"]'::jsonb, 0, 'sanat'),
('Caz müziği hangi ülkede doğmuştur?', '["ABD","Fransa","Küba","Brezilya"]'::jsonb, 0, 'sanat'),
('Reggae müziği hangi ülkeyle özdeşleşmiştir?', '["Jamaika","Küba","Brezilya","Nijerya"]'::jsonb, 0, 'sanat'),
('Bob Marley hangi müzik türünün efsanesidir?', '["Reggae","Rock","Caz","Blues"]'::jsonb, 0, 'sanat'),
('The Beatles hangi şehirden çıkmıştır?', '["Liverpool","Londra","Manchester","Birmingham"]'::jsonb, 0, 'sanat'),
('"Kralın" lakabıyla anılan rock''n roll yıldızı kimdir?', '["Elvis Presley","Chuck Berry","Little Richard","Buddy Holly"]'::jsonb, 0, 'sanat'),
('Michael Jackson''ın lakabı nedir?', '["Pop''un Kralı","Rock''ın Kralı","Soul''un Babası","Dansın Efendisi"]'::jsonb, 0, 'sanat'),
('Queen grubunun solisti kimdir?', '["Freddie Mercury","David Bowie","Mick Jagger","Elton John"]'::jsonb, 0, 'sanat'),
('"Bohemian Rhapsody" hangi grubun şarkısıdır?', '["Queen","The Beatles","Pink Floyd","Led Zeppelin"]'::jsonb, 0, 'sanat'),
('Opera "Carmen"in bestecisi kimdir?', '["Bizet","Verdi","Puccini","Rossini"]'::jsonb, 0, 'sanat'),
('"La Traviata" operasının bestecisi kimdir?', '["Verdi","Puccini","Bizet","Wagner"]'::jsonb, 0, 'sanat'),
('"Fındıkkıran" balesinin bestecisi kimdir?', '["Çaykovski","Stravinsky","Prokofiev","Minkus"]'::jsonb, 0, 'sanat'),
('Senfonide genellikle kaç bölüm bulunur?', '["4","3","5","2"]'::jsonb, 0, 'sanat'),
('Bir oktavda kaç nota vardır?', '["7","8","12","5"]'::jsonb, 0, 'sanat'),
('Nota dizisinin ilk notası hangisidir?', '["Do","La","Sol","Mi"]'::jsonb, 0, 'sanat'),
('Hangi enstrüman vurmalı çalgıdır?', '["Davul","Keman","Flüt","Gitar"]'::jsonb, 0, 'sanat'),
('Hangi enstrüman nefesli çalgıdır?', '["Flüt","Keman","Piyano","Arp"]'::jsonb, 0, 'sanat'),
('Orkestrada en kalın sesli yaylı çalgı hangisidir?', '["Kontrbas","Çello","Viyola","Keman"]'::jsonb, 0, 'sanat'),
('"Nobel Edebiyat Ödülü" alan ilk kadın yazar kimdir?', '["Selma Lagerlöf","Pearl Buck","Toni Morrison","Doris Lessing"]'::jsonb, 0, 'edebiyat'),
('"Gurur ve Önyargı" romanının yazarı kimdir?', '["Jane Austen","Charlotte Bronte","Emily Bronte","Virginia Woolf"]'::jsonb, 0, 'edebiyat'),
('"Uğultulu Tepeler" romanının yazarı kimdir?', '["Emily Bronte","Charlotte Bronte","Jane Austen","George Eliot"]'::jsonb, 0, 'edebiyat'),
('"Jane Eyre" romanının yazarı kimdir?', '["Charlotte Bronte","Emily Bronte","Jane Austen","Mary Shelley"]'::jsonb, 0, 'edebiyat'),
('"Frankenstein" romanının yazarı kimdir?', '["Mary Shelley","Bram Stoker","Edgar Allan Poe","H.G. Wells"]'::jsonb, 0, 'edebiyat'),
('"Drakula" romanının yazarı kimdir?', '["Bram Stoker","Mary Shelley","Poe","Lovecraft"]'::jsonb, 0, 'edebiyat'),
('"Kuzgun" şiirinin şairi kimdir?', '["Edgar Allan Poe","Walt Whitman","Emily Dickinson","Robert Frost"]'::jsonb, 0, 'edebiyat'),
('"Martin Eden" romanının yazarı kimdir?', '["Jack London","Hemingway","Steinbeck","Mark Twain"]'::jsonb, 0, 'edebiyat'),
('"Beyaz Diş" ve "Vahşetin Çağrısı" kimin eserleridir?', '["Jack London","Hemingway","Melville","Defoe"]'::jsonb, 0, 'edebiyat'),
('"Moby Dick" romanının yazarı kimdir?', '["Herman Melville","Jack London","Verne","Stevenson"]'::jsonb, 0, 'edebiyat'),
('"Define Adası" romanının yazarı kimdir?', '["Stevenson","Defoe","Verne","Dumas"]'::jsonb, 0, 'edebiyat'),
('"Üç Silahşörler" romanının yazarı kimdir?', '["Alexandre Dumas","Victor Hugo","Balzac","Flaubert"]'::jsonb, 0, 'edebiyat'),
('"Monte Kristo Kontu" romanının yazarı kimdir?', '["Alexandre Dumas","Victor Hugo","Stendhal","Zola"]'::jsonb, 0, 'edebiyat'),
('"Madame Bovary" romanının yazarı kimdir?', '["Flaubert","Balzac","Zola","Maupassant"]'::jsonb, 0, 'edebiyat'),
('"Goriot Baba" romanının yazarı kimdir?', '["Balzac","Flaubert","Hugo","Stendhal"]'::jsonb, 0, 'edebiyat'),
('"Anna Karenina" romanının yazarı kimdir?', '["Tolstoy","Dostoyevski","Çehov","Turgenyev"]'::jsonb, 0, 'edebiyat'),
('"Karamazov Kardeşler" romanının yazarı kimdir?', '["Dostoyevski","Tolstoy","Gogol","Gorki"]'::jsonb, 0, 'edebiyat'),
('"Babalar ve Oğullar" romanının yazarı kimdir?', '["Turgenyev","Tolstoy","Çehov","Puşkin"]'::jsonb, 0, 'edebiyat'),
('"Ölü Canlar" romanının yazarı kimdir?', '["Gogol","Dostoyevski","Çehov","Bulgakov"]'::jsonb, 0, 'edebiyat'),
('"Vişne Bahçesi" oyununun yazarı kimdir?', '["Çehov","İbsen","Strindberg","Gorki"]'::jsonb, 0, 'edebiyat'),
('"Nora - Bir Bebek Evi" oyununun yazarı kimdir?', '["İbsen","Çehov","Shaw","Beckett"]'::jsonb, 0, 'edebiyat'),
('"Godot''yu Beklerken" oyununun yazarı kimdir?', '["Samuel Beckett","Ionesco","Sartre","Camus"]'::jsonb, 0, 'edebiyat'),
('"Yabancı" romanının yazarı kimdir?', '["Albert Camus","Sartre","Kafka","Gide"]'::jsonb, 0, 'edebiyat'),
('"Bulantı" romanının yazarı kimdir?', '["Sartre","Camus","Kafka","Beckett"]'::jsonb, 0, 'edebiyat'),
('"Şeker Portakalı" romanının yazarı kimdir?', '["Jose Mauro de Vasconcelos","Marquez","Coelho","Borges"]'::jsonb, 0, 'edebiyat'),
('"Simyacı" romanının yazarı kimdir?', '["Paulo Coelho","Marquez","Vasconcelos","Allende"]'::jsonb, 0, 'edebiyat'),
('"Fareler ve İnsanlar" romanının yazarı kimdir?', '["John Steinbeck","Hemingway","Faulkner","Fitzgerald"]'::jsonb, 0, 'edebiyat'),
('"Gazap Üzümleri" romanının yazarı kimdir?', '["John Steinbeck","Hemingway","Dos Passos","Caldwell"]'::jsonb, 0, 'edebiyat'),
('"Muhteşem Gatsby" romanının yazarı kimdir?', '["F. Scott Fitzgerald","Hemingway","Faulkner","Salinger"]'::jsonb, 0, 'edebiyat'),
('"Çavdar Tarlasında Çocuklar" romanının yazarı kimdir?', '["J.D. Salinger","Fitzgerald","Kerouac","Updike"]'::jsonb, 0, 'edebiyat'),
('"Bülbülü Öldürmek" romanının yazarı kimdir?', '["Harper Lee","Toni Morrison","Capote","Faulkner"]'::jsonb, 0, 'edebiyat'),
('"Cesur Yeni Dünya" romanının yazarı kimdir?', '["Aldous Huxley","Orwell","Bradbury","Zamyatin"]'::jsonb, 0, 'edebiyat'),
('"Fahrenheit 451" romanının yazarı kimdir?', '["Ray Bradbury","Orwell","Huxley","Asimov"]'::jsonb, 0, 'edebiyat'),
('Bilim kurgu yazarı Isaac Asimov en çok neyle tanınır?', '["Robot öyküleri","Korku","Polisiye","Fantastik"]'::jsonb, 0, 'edebiyat'),
('"Dune" romanının yazarı kimdir?', '["Frank Herbert","Asimov","Clarke","Heinlein"]'::jsonb, 0, 'edebiyat'),
('"2001: Bir Uzay Macerası"nın yazarı kimdir?', '["Arthur C. Clarke","Asimov","Bradbury","Lem"]'::jsonb, 0, 'edebiyat'),
('Agatha Christie''nin ünlü kadın dedektifi kimdir?', '["Miss Marple","Bayan Hudson","Bayan Watson","Nancy Drew"]'::jsonb, 0, 'edebiyat'),
('"Doğu Ekspresinde Cinayet" kimin eseridir?', '["Agatha Christie","Conan Doyle","Simenon","Highsmith"]'::jsonb, 0, 'edebiyat'),
('"Da Vinci Şifresi" romanının yazarı kimdir?', '["Dan Brown","Umberto Eco","Ken Follett","Grisham"]'::jsonb, 0, 'edebiyat'),
('"Gülün Adı" romanının yazarı kimdir?', '["Umberto Eco","Dan Brown","Calvino","Pirandello"]'::jsonb, 0, 'edebiyat')
on conflict (soru) do nothing;
