-- ============================================================
-- Soru Partisi 13 — 500 soru
--   genel_kultur 200 · bilim 200 · tarih 100
--
-- Kalite: tek ve tartışmasız doğru cevap; zamanla değişen bilgi yok;
-- yoruma açık ifade yok; mevcut havuza (3.193 soru) karşı anahtar kelime ve
-- birebir tekrar taraması yapıldı; şıklar kısa. Migration sonunda YALNIZ bu
-- partinin şıkları karıştırılır.
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- ===================== GENEL KÜLTÜR (200) =====================

-- Mutfak ve yiyecek kültürü
('Mercimek çorbasının ana malzemesi hangi baklagildir?', '["Mercimek","Nohut","Fasulye","Bezelye"]'::jsonb, 0, 'genel_kultur'),
('Tarhana hangi yöntemle saklanır?', '["Dondurularak","Kurutularak","Salamura","Tütsüleyerek"]'::jsonb, 1, 'genel_kultur'),
('Pastırmanın üzerine sürülen baharatlı karışıma ne denir?', '["Pul biber","Sumak","Çemen","Kekik"]'::jsonb, 2, 'genel_kultur'),
('Sucuk hangi tür gıdadır?', '["Sebze turşusu","Süt ürünü","Tahıl ürünü","Fermente et ürünü"]'::jsonb, 3, 'genel_kultur'),
('Turşu hangi işlemle yapılır?', '["Salamura ve fermantasyon","Kurutma","Kavurma","Haşlama"]'::jsonb, 0, 'genel_kultur'),
('Boza hangi tahıldan yapılır?', '["Pirinç","Darı veya bulgur","Mercimek","Nohut"]'::jsonb, 1, 'genel_kultur'),
('Salep hangi bitkiden elde edilir?', '["Kahve çekirdeği","Çay yaprağı","Orkide kökü","Kakao"]'::jsonb, 2, 'genel_kultur'),
('Kaymak hangi besinin üst tabakasından elde edilir?', '["Bal","Yoğurt suyu","Zeytinyağı","Süt"]'::jsonb, 3, 'genel_kultur'),
('Lahmacunun üzerine sıkılan meyve hangisidir?', '["Limon","Portakal","Elma","Nar"]'::jsonb, 0, 'genel_kultur'),
('Menemen hangi öğünle özdeşleşmiştir?', '["Gece yarısı","Kahvaltı","Öğle yemeği ana yemek","Tatlı"]'::jsonb, 1, 'genel_kultur'),
('Künefe hangi peynirle yapılır?', '["Tulum","Kaşar","Tuzsuz taze peynir","Rokfor"]'::jsonb, 2, 'genel_kultur'),
('Hamsi hangi pişirme yöntemiyle sıkça hazırlanır?', '["Şerbetli","Fırında tatlı olarak","Salamura tatlı","Tavada kızartma"]'::jsonb, 3, 'genel_kultur'),
('Mantı geleneksel olarak neyle servis edilir?', '["Yoğurt","Reçel","Bal","Pekmez"]'::jsonb, 0, 'genel_kultur'),
('Zeytinin acılığını gidermek için ne yapılır?', '["Kızartılır","Salamurada bekletilir","Dondurulur","Kurutulur"]'::jsonb, 1, 'genel_kultur'),
('Pekmez hangi meyveden en çok yapılır?', '["Kivi","Muz","Üzüm","Ananas"]'::jsonb, 2, 'genel_kultur'),
('Sushi hangi tahılla hazırlanır?', '["Arpa","Bulgur","Mısır","Pirinç"]'::jsonb, 3, 'genel_kultur'),
('Guacamole hangi meyveden yapılır?', '["Avokado","Domates","Salatalık","Biber"]'::jsonb, 0, 'genel_kultur'),
('Hummus hangi baklagilden yapılır?', '["Mercimek","Nohut","Fasulye","Bakla"]'::jsonb, 1, 'genel_kultur'),
('Ratatuy hangi ülkenin yemeğidir?', '["İspanya","İtalya","Fransa","Yunanistan"]'::jsonb, 2, 'genel_kultur'),
('Kimchi hangi ülkenin geleneksel yiyeceğidir?', '["Vietnam","Japonya","Çin","Kore"]'::jsonb, 3, 'genel_kultur'),

-- Trafik ve güvenlik
('Mavi zeminli yuvarlak trafik levhaları neyi belirtir?', '["Mecburiyet","Tehlike","Yasak","Bilgi tabelası değil"]'::jsonb, 0, 'genel_kultur'),
('Yaya geçidinde önceliği kim taşır?', '["Otomobil","Yaya","Motosiklet","Bisiklet"]'::jsonb, 1, 'genel_kultur'),
('Dörtlü flaşör hangi durumda yakılır?', '["Sola dönüşte","Sağa dönüşte","Arıza veya tehlike","Park ederken hep"]'::jsonb, 2, 'genel_kultur'),
('Kavşakta trafik ışığı yoksa kim geçer?', '["Hızlı araç","Soldan gelen","Büyük araç","Sağdan gelen"]'::jsonb, 3, 'genel_kultur'),
('Emniyet kemeri hangi koltuklarda zorunludur?', '["Tüm koltuklarda","Yalnız ön koltukta","Yalnız sürücüde","Yalnız arkada"]'::jsonb, 0, 'genel_kultur'),
('Çocuk oto koltuğu neye göre seçilir?', '["Renge","Yaş ve kiloya","Markaya","Araç modeline"]'::jsonb, 1, 'genel_kultur'),
('Sis lambası ne zaman kullanılır?', '["Gece hep","Güneşli günde","Görüşün azaldığı havada","Otoparkta"]'::jsonb, 2, 'genel_kultur'),
('Alkollü araç kullanmanın en temel riski nedir?', '["Motor ısınması","Yakıt tüketimi","Lastik aşınması","Tepki süresinin uzaması"]'::jsonb, 3, 'genel_kultur'),
('Hız limiti levhası neyi gösterir?', '["İzin verilen en yüksek hız","Zorunlu hız","En düşük hız","Ortalama hız"]'::jsonb, 0, 'genel_kultur'),

-- Sağlık, ilk yardım, hijyen
('Sağlıklı yetişkin için normal nabız aralığı nedir?', '["20-40","60-100","120-160","150-200"]'::jsonb, 1, 'genel_kultur'),
('El yıkama en az kaç saniye sürmelidir?', '["60","3","20","120"]'::jsonb, 2, 'genel_kultur'),
('Ateş ölçümünde kullanılan birim nedir?', '["Volt","Bar","Newton","Santigrat derece"]'::jsonb, 3, 'genel_kultur'),
('Kırık şüphesinde bölgeye ne uygulanır?', '["Atel ile sabitleme","Masaj","Sıcak kompres","Çekme"]'::jsonb, 0, 'genel_kultur'),
('Kesikte kanamayı azaltmak için uzuv nasıl tutulur?', '["Aşağıda","Kalp seviyesinden yukarıda","Sallanarak","Suda"]'::jsonb, 1, 'genel_kultur'),
('Güneş çarpmasında ilk yapılacak nedir?', '["Koşturmak","Sıcak içecek vermek","Serin yere almak","Üstünü örtmek"]'::jsonb, 2, 'genel_kultur'),
('Böcek sokmasında şişliği azaltmak için ne uygulanır?', '["Sirke ruhu","Sıcak","Tuz","Soğuk"]'::jsonb, 3, 'genel_kultur'),
('Bilinci açık boğulan kişiye ne yapılır?', '["Öksürmesi teşvik edilir","Su içirilir","Sırtı ovulur","Yatırılır"]'::jsonb, 0, 'genel_kultur'),
('Sağlıklı beslenmede tabağın en büyük bölümü ne olmalı?', '["Şeker","Sebze","Yağ","Tuz"]'::jsonb, 1, 'genel_kultur'),
('Vücutta en fazla bulunan madde nedir?', '["Yağ","Protein","Su","Mineral"]'::jsonb, 2, 'genel_kultur'),
('Göz sağlığı için ekran kullanımında önerilen kural nedir?', '["Yakından bakmak","Sürekli bakmak","Karanlıkta bakmak","20-20-20 kuralı"]'::jsonb, 3, 'genel_kultur'),
('Aşıların saklandığı sıcaklık zincirine ne denir?', '["Soğuk zincir","Sıcak zincir","Kuru zincir","Nem zinciri"]'::jsonb, 0, 'genel_kultur'),
('Diş ipi ne işe yarar?', '["Diş beyazlatır","Diş aralarını temizler","Nefes açar","Diş taşı söker"]'::jsonb, 1, 'genel_kultur'),
('Egzersiz öncesi yapılan hazırlığa ne denir?', '["Germe sonrası","Soğuma","Isınma","Dinlenme"]'::jsonb, 2, 'genel_kultur'),
('Yetişkinde günlük önerilen su miktarı yaklaşık kaç litredir?', '["0,5","6","10","2"]'::jsonb, 3, 'genel_kultur'),

-- Ekonomi, banka, hukuk
('Bankada vadeli hesabın vadesiz hesaptan farkı nedir?', '["Belirli süre bekletilir","Kart verilir","Ücretsizdir","Şubesizdir"]'::jsonb, 0, 'genel_kultur'),
('IBAN ne işe yarar?', '["Şifre üretir","Hesabı uluslararası tanımlar","Kart basar","Faiz hesaplar"]'::jsonb, 1, 'genel_kultur'),
('Çek ve senet hangi tür belgelerdir?', '["Tapu belgesi","Kimlik belgesi","Kıymetli evrak","Ruhsat"]'::jsonb, 2, 'genel_kultur'),
('Kefil ne yapar?', '["Vergi toplar","Faiz belirler","Kredi verir","Borcu garanti eder"]'::jsonb, 3, 'genel_kultur'),
('Bütçe açığı ne demektir?', '["Giderin gelirden fazla olması","Gelirin fazla olması","Borcun bitmesi","Vergi indirimi"]'::jsonb, 0, 'genel_kultur'),
('Asgari ücret nedir?', '["Ortalama ücret","Yasal en düşük ücret","En yüksek ücret","Prim"]'::jsonb, 1, 'genel_kultur'),
('KDV hangi tür vergidir?', '["Servet vergisi","Doğrudan vergi","Dolaylı vergi","Gümrük dışı"]'::jsonb, 2, 'genel_kultur'),
('Miras hukuku neyi düzenler?', '["Vergi oranını","Kira sözleşmesini","Trafik cezasını","Ölen kişinin mal paylaşımını"]'::jsonb, 3, 'genel_kultur'),
('Tapu neyi belgeler?', '["Taşınmaz mülkiyetini","Araç sahipliğini","Kimliği","Diploma"]'::jsonb, 0, 'genel_kultur'),
('Noterin temel görevi nedir?', '["Dava açmak","İşlemleri resmen onaylamak","Ceza vermek","Vergi toplamak"]'::jsonb, 1, 'genel_kultur'),
('Sözleşmede "fesih" ne anlama gelir?', '["İmzalama","Uzatma","Sona erdirme","Devretme"]'::jsonb, 2, 'genel_kultur'),
('Bir işçinin yıllık izin hakkı neye bağlıdır?', '["Şehre","Boyuna","Doğum ayına","Çalışma süresine"]'::jsonb, 3, 'genel_kultur'),
('Emeklilik primi hangi kuruma ödenir?', '["Sosyal güvenlik kurumuna","Belediyeye","Valiliğe","Bankaya"]'::jsonb, 0, 'genel_kultur'),
('Enflasyonun alım gücüne etkisi nedir?', '["Artırır","Azaltır","Etkilemez","İkiye katlar"]'::jsonb, 1, 'genel_kultur'),
('Döviz kuru neyi ifade eder?', '["Vergi oranı","Faiz oranı","İki para biriminin değişim oranı","Kâr oranı"]'::jsonb, 2, 'genel_kultur'),

-- Doğa, tarım, hayvan bakımı
('Toprağın işlenmesine ne denir?', '["Depolama","Hasat","Harman","Sürüm"]'::jsonb, 3, 'genel_kultur'),
('Nadas ne demektir?', '["Toprağı dinlendirmek","Ürün toplamak","Tohum ekmek","Sulamak"]'::jsonb, 0, 'genel_kultur'),
('Damla sulama neyi sağlar?', '["Daha çok su kullanımı","Su tasarrufu","Toprak kaybı","Tuzlanma"]'::jsonb, 1, 'genel_kultur'),
('Sera etkisiyle serada ne artar?', '["Kar","Rüzgâr","Sıcaklık","Buz"]'::jsonb, 2, 'genel_kultur'),
('Kompost yapımında hangi atık kullanılır?', '["Plastik","Cam","Metal","Organik atık"]'::jsonb, 3, 'genel_kultur'),
('Bitkilerde kök çürümesinin yaygın nedeni nedir?', '["Aşırı sulama","Az güneş","Rüzgâr","Soğuk hava"]'::jsonb, 0, 'genel_kultur'),
('Saksı bitkisinin toprağı neden değiştirilir?', '["Renk değişsin diye","Besin tükendiği için","Ağırlaşsın diye","Kokusu için"]'::jsonb, 1, 'genel_kultur'),
('Kedilerin tırmalama ihtiyacı nedendir?', '["Uyku","Açlık","Tırnak bakımı ve işaretleme","Susuzluk"]'::jsonb, 2, 'genel_kultur'),
('Köpeklerde aşı takvimi kim tarafından belirlenir?', '["Kasap","Sahibi","Belediye","Veteriner"]'::jsonb, 3, 'genel_kultur'),
('Akvaryum balıkları için suyun neyi önemlidir?', '["Sıcaklık ve temizlik","Rengi","Kokusu","Tuzu her zaman"]'::jsonb, 0, 'genel_kultur'),
('Arıların poleni taşıması neye yol açar?', '["Erozyon","Tozlaşma","Kuraklık","Don"]'::jsonb, 1, 'genel_kultur'),
('Solucanların toprağa faydası nedir?', '["Taşlaştırma","Kurutma","Havalandırma ve gübreleme","Tuzlama"]'::jsonb, 2, 'genel_kultur'),
('Ağaç dikmenin en uygun mevsimi genellikle hangisidir?', '["Fark etmez","Yaz ortası","Kışın en soğuğu","Sonbahar veya ilkbahar"]'::jsonb, 3, 'genel_kultur'),
('Meyve ağaçlarında aşılamanın amacı nedir?', '["İstenen çeşidi çoğaltmak","Ağacı kısaltmak","Yaprağı artırmak","Kökü kesmek"]'::jsonb, 0, 'genel_kultur'),
('Organik tarımda neyin kullanımı sınırlıdır?', '["Su","Sentetik kimyasallar","Güneş","Toprak"]'::jsonb, 1, 'genel_kultur'),

-- Ev, tamir, teknoloji kullanımı
('Sigortanın atmasının yaygın nedeni nedir?', '["Soğuk hava","Az kullanım","Aşırı yüklenme","Nem eksikliği"]'::jsonb, 2, 'genel_kultur'),
('Çamaşır etiketindeki çarpı işaretli simge ne anlatır?', '["Fiyatı","Zorunluluğu","Öneriyi","Yapılmaması gerekeni"]'::jsonb, 3, 'genel_kultur'),
('Beyaz eşyada enerji sınıfı neyi gösterir?', '["Enerji verimliliğini","Ağırlığı","Rengi","Sesini"]'::jsonb, 0, 'genel_kultur'),
('Su kaçağında ilk yapılması gereken nedir?', '["Boyamak","Ana vanayı kapatmak","Beklemek","Isıtmak"]'::jsonb, 1, 'genel_kultur'),
('Priz ve fişte topraklama neyi önler?', '["Isı kaybını","Ses kısılmasını","Elektrik çarpmasını","Işık azalmasını"]'::jsonb, 2, 'genel_kultur'),
('Boya yapmadan önce duvara ne uygulanır?', '["Su","Cila","Yağ","Astar"]'::jsonb, 3, 'genel_kultur'),
('Silikon en çok nerede kullanılır?', '["Su yalıtımında","Elektrik iletiminde","Isıtmada","Aydınlatmada"]'::jsonb, 0, 'genel_kultur'),
('Matkap ucu seçilirken neye bakılır?', '["Renge","Delinecek malzemeye","Markaya","Ağırlığa"]'::jsonb, 1, 'genel_kultur'),
('Buzdolabının arkasındaki ızgara ne işe yarar?', '["Ses keser","Su tutar","Isıyı dışarı atar","Işık verir"]'::jsonb, 2, 'genel_kultur'),
('Klimada filtre temizliği neyi sağlar?', '["Renk","Daha çok gürültü","Daha çok enerji","Verim ve hava kalitesi"]'::jsonb, 3, 'genel_kultur'),

-- Coğrafya ve dünya bilgisi (genel kültür düzeyi)
('Bir ülkenin başkenti hangi özelliğiyle tanımlanır?', '["Yönetim merkezi olması","En kalabalık olması","En eski olması","En büyük olması"]'::jsonb, 0, 'genel_kultur'),
('Yarımküreleri ayıran hayali çizgi hangisidir?', '["Meridyen","Ekvator","Dönence","Kutup dairesi"]'::jsonb, 1, 'genel_kultur'),
('Denizden yüksekliğe göre en yüksek yerleşim türü hangisidir?', '["Kıyı ovası","Delta","Yayla","Lagün"]'::jsonb, 2, 'genel_kultur'),
('Bir ülkenin karasularının ötesindeki alana ne denir?', '["Körfez","Kıta sahanlığı yok","İç su","Açık deniz"]'::jsonb, 3, 'genel_kultur'),
('Nüfus piramidi neyi gösterir?', '["Yaş ve cinsiyet dağılımını","Gelir dağılımını","Eğitim düzeyini","İklimi"]'::jsonb, 0, 'genel_kultur'),
('Kentleşme neyi ifade eder?', '["Köy nüfusunun artmasını","Kent nüfusunun artmasını","Tarımın artmasını","Ormanların artmasını"]'::jsonb, 1, 'genel_kultur'),
('Bir bölgenin ekonomik faaliyeti neye göre şekillenir?', '["Dil sayısı","Bayrak rengi","Doğal koşullar ve kaynaklar","Tarih uzunluğu"]'::jsonb, 2, 'genel_kultur'),
('Turizmin bir bölgeye en görünür etkisi nedir?', '["Deprem","Nüfus azalması","Yağış artışı","İstihdam artışı"]'::jsonb, 3, 'genel_kultur'),
('Barajların temel işlevlerinden biri nedir?', '["Su depolamak","Kum üretmek","Rüzgâr kesmek","Isı üretmek"]'::jsonb, 0, 'genel_kultur'),
('Tarım arazilerinin yerleşime açılmasının sonucu nedir?', '["Verim artar","Tarım alanı azalır","Yağış artar","Toprak zenginleşir"]'::jsonb, 1, 'genel_kultur'),

-- Kültür, sanat, gündelik bilgi
('Bir müzedeki eserlerin yanındaki açıklama kartına ne denir?', '["Broşür","Afiş","Etiket","Katalog kapağı"]'::jsonb, 2, 'genel_kultur'),
('Tiyatroda "prömiyer" ne demektir?', '["Ara","Son gösterim","Prova","İlk gösterim"]'::jsonb, 3, 'genel_kultur'),
('Bir kitabın ilk baskısına ne denir?', '["Birinci basım","Cilt","Fasikül","Nüsha dışı"]'::jsonb, 0, 'genel_kultur'),
('Gazetede köşe yazısını kim yazar?', '["Muhabir","Köşe yazarı","Editör","Dizgici"]'::jsonb, 1, 'genel_kultur'),
('Radyoda canlı yayın ne demektir?', '["Tekrar","Kayıttan çalan","Anında yayınlanan","Reklam"]'::jsonb, 2, 'genel_kultur'),
('Bir belgeselin amacı nedir?', '["Yarışma yapmak","Yalnız eğlendirmek","Ürün satmak","Bilgilendirmek"]'::jsonb, 3, 'genel_kultur'),
('Sosyal medyada "algoritma" ne yapar?', '["İçerik sıralar","İnternet üretir","Cihaz şarj eder","Ekran temizler"]'::jsonb, 0, 'genel_kultur'),
('Bir markanın sloganı ne işe yarar?', '["Fiyat belirler","Akılda kalmayı sağlar","Üretim yapar","Vergi öder"]'::jsonb, 1, 'genel_kultur'),
('Telif hakkı süresi dolan eserler nasıl anılır?', '["Yasak eser","Gizli eser","Kamu malı","Taslak"]'::jsonb, 2, 'genel_kultur'),
('Bir sergide "retrospektif" ne demektir?', '["Atölye","Yeni işler","Satış fuarı","Sanatçının geçmiş işlerine bakış"]'::jsonb, 3, 'genel_kultur'),

-- Ölçüler, semboller, sayılar
('Bir gros kaç adettir?', '["144","100","120","12"]'::jsonb, 0, 'genel_kultur'),
('Bir kilobayt kaç bayttır (yaklaşık)?', '["100","1024","10","1000000"]'::jsonb, 1, 'genel_kultur'),
('Bir mil yaklaşık kaç kilometredir?', '["3","1","1,6","10"]'::jsonb, 2, 'genel_kultur'),
('Bir inç yaklaşık kaç santimetredir?', '["5","1","10","2,54"]'::jsonb, 3, 'genel_kultur'),
('Bir libre (pound) yaklaşık kaç gramdır?', '["454","100","1000","250"]'::jsonb, 0, 'genel_kultur'),
('Bir galon hangi tür ölçüdür?', '["Ağırlık","Hacim","Uzunluk","Sıcaklık"]'::jsonb, 1, 'genel_kultur'),
('Fahrenhayt ölçeğinde suyun donma noktası kaçtır?', '["100","0","32","212"]'::jsonb, 2, 'genel_kultur'),
('Fahrenhayt ölçeğinde suyun kaynama noktası kaçtır?', '["180","100","32","212"]'::jsonb, 3, 'genel_kultur'),
('Bir karat hangi alanda kullanılır?', '["Değerli taş ve altın","Uzunluk","Hız","Basınç"]'::jsonb, 0, 'genel_kultur'),
('24 ayar altın neyi ifade eder?', '["Yarı saf altını","Saf altını","Gümüşü","Bakırı"]'::jsonb, 1, 'genel_kultur'),
('Desibel neyi ölçer?', '["Isıyı","Işık şiddetini","Ses şiddetini","Basıncı"]'::jsonb, 2, 'genel_kultur'),

-- Oyun, hobi, koleksiyon
('Satrançta atın hareketi hangi harfe benzer?', '["Z","T","S","L"]'::jsonb, 3, 'genel_kultur'),
('Dama oyununda taşlar nasıl ilerler?', '["Çapraz","Düz","L şeklinde","Serbest"]'::jsonb, 0, 'genel_kultur'),
('Pul koleksiyonculuğuna ne denir?', '["Nümismatik","Filateli","Bibliyofili","Kartofili"]'::jsonb, 1, 'genel_kultur'),
('Madeni para koleksiyonculuğuna ne denir?', '["Astroloji","Filateli","Nümismatik","Heraldik"]'::jsonb, 2, 'genel_kultur'),
('Origami hangi malzemeyle yapılır?', '["Cam","Kumaş","Metal","Kâğıt"]'::jsonb, 3, 'genel_kultur'),
('Puzzle (yapboz) neyi geliştirir?', '["Görsel algı ve sabır","Kas gücü","Nefes kapasitesi","Duyma"]'::jsonb, 0, 'genel_kultur'),
('Yoga hangi yönüyle bilinir?', '["Ağırlık kaldırma","Esneklik ve nefes","Hız koşusu","Dalış"]'::jsonb, 1, 'genel_kultur'),
('Kamp yaparken ateş söndürülürken ne kullanılır?', '["Yağ","Benzin","Su ve toprak","Kâğıt"]'::jsonb, 2, 'genel_kultur'),

-- Dil, iletişim, yazışma
('Kısaltmalarda nokta hangi durumda kullanılır?', '["Yalnız sayılarda","Hiçbirinde","Hepsinde","Bazı kısaltmalarda"]'::jsonb, 3, 'genel_kultur'),
('Tırnak işareti neyi belirtir?', '["Alıntıyı","Toplamayı","Bölmeyi","Soruyu"]'::jsonb, 0, 'genel_kultur'),
('Üç nokta hangi anlamda kullanılır?', '["Bitişi kesin","Sözün sürdüğünü","Toplamayı","Çarpmayı"]'::jsonb, 1, 'genel_kultur'),
('Parantez ne için kullanılır?', '["Bağırmak","Soru sormak","Açıklama eklemek","Bölmek"]'::jsonb, 2, 'genel_kultur'),
('İki nokta hangi durumda kullanılır?', '["Ünlemde","Cümle sonunda hep","Soruda","Açıklama ve sıralama öncesi"]'::jsonb, 3, 'genel_kultur'),
('"Ki" bağlacı nasıl yazılır?', '["Ayrı","Bitişik","Tireyle","Tırnakla"]'::jsonb, 0, 'genel_kultur'),
('"De/da" bağlacı nasıl yazılır?', '["Bitişik","Ayrı","Tireyle","Büyük harfle"]'::jsonb, 1, 'genel_kultur'),
('Özel isimlere gelen ekler nasıl ayrılır?', '["Noktayla","Virgülle","Kesme işaretiyle","Tireyle"]'::jsonb, 2, 'genel_kultur'),
('Bir metnin kısaltılmış haline ne denir?', '["Kaynak","Dipnot","Başlık","Özet"]'::jsonb, 3, 'genel_kultur'),
('Resmî yazıda hitap nereye yazılır?', '["Metnin başına","Sonuna","Ortasına","Kenara"]'::jsonb, 0, 'genel_kultur'),

-- Genel kültür karışık (kalan)
('Dünyanın en çok kullanılan alfabesi hangisidir?', '["Kiril","Latin","Arap","Yunan"]'::jsonb, 1, 'genel_kultur'),
('Bir yılda kaç çeyrek (üç aylık dönem) vardır?', '["6","2","4","12"]'::jsonb, 2, 'genel_kultur'),
('Pusulanın çalışması neye dayanır?', '["Yağmur","Güneş ışığı","Rüzgâr","Yer manyetik alanı"]'::jsonb, 3, 'genel_kultur'),
('Gökkuşağının oluşması için ne gerekir?', '["Güneş ve su damlacıkları","Kar ve rüzgâr","Sis ve gece","Bulut ve şimşek"]'::jsonb, 0, 'genel_kultur'),
('Bir kişinin parmak izinin özelliği nedir?', '["Değişmesi","Kişiye özgü olması","Aynı olması","Silinmesi"]'::jsonb, 1, 'genel_kultur'),
('Kan bağışının en temel şartı nedir?', '["Uykusuz olmak","Aç olmak","Sağlıklı olmak","Spor yapmış olmak"]'::jsonb, 2, 'genel_kultur'),
('Organ bağışı ne zaman geçerli olur?', '["Emeklilikte","Kendiliğinden","Doğumda","Yasal onayla"]'::jsonb, 3, 'genel_kultur'),
('İtfaiye merdiveni ne için kullanılır?', '["Yüksek kata ulaşmak","Su ısıtmak","Yol kapatmak","Ses vermek"]'::jsonb, 0, 'genel_kultur'),
('Ambulansın üzerindeki yazı neden ters yazılır?', '["Süs için","Aynada düz görünsün diye","Yanlışlıkla","Yasa gereği değil"]'::jsonb, 1, 'genel_kultur'),
('Acil durumda toplanma alanı ne işe yarar?', '["Pazar yeri","Otopark","Güvenli buluşma noktası","Spor sahası"]'::jsonb, 2, 'genel_kultur'),
('Yangın tüpünde "ABC" ne anlama gelir?', '["Basınç","Marka","Ağırlık","Yangın sınıfları"]'::jsonb, 3, 'genel_kultur'),
('Baca temizliği neden yapılır?', '["Yangın ve zehirlenmeyi önlemek","Renk vermek","Ses azaltmak","Isı artırmak"]'::jsonb, 0, 'genel_kultur'),
('Karbonmonoksit neden tehlikelidir?', '["Kırmızı olduğu için","Renksiz ve kokusuz olduğu için","Kokulu olduğu için","Ağır olduğu için"]'::jsonb, 1, 'genel_kultur'),
('Elektrikli cihazları fişten çekmek neyi sağlar?', '["Daha uzun kablo","Daha hızlı çalışma","Enerji tasarrufu ve güvenlik","Daha çok ses"]'::jsonb, 2, 'genel_kultur'),
('Bir binada asansör yangında neden kullanılmaz?', '["Küçük olduğu için","Yavaş olduğu için","Pahalı olduğu için","Arıza ve kapanma riski"]'::jsonb, 3, 'genel_kultur'),
('Deprem sırasında araç kullanan kişi ne yapmalıdır?', '["Güvenli yerde durmak","Hızlanmak","Köprüye girmek","Tünelde durmak"]'::jsonb, 0, 'genel_kultur'),
('Sel sırasında ne yapılmamalıdır?', '["Yüksek yere çıkmak","Su birikintisine girmek","Haber almak","Çanta hazırlamak"]'::jsonb, 1, 'genel_kultur'),
('Çığ riski en çok nerede vardır?', '["Kumsalda","Ovada","Dik karlı yamaçlarda","Ormanda"]'::jsonb, 2, 'genel_kultur'),
('İlk yardımda "ABC" sırası neyi ifade eder?', '["Alerji, beslenme, ciğer","Ağrı, baş, ciğer","Ateş, basınç, cilt","Hava yolu, solunum, dolaşım"]'::jsonb, 3, 'genel_kultur'),
('Bir pilin üzerindeki "+" işareti neyi gösterir?', '["Artı kutbu","Ağırlığı","Boyutu","Markayı"]'::jsonb, 0, 'genel_kultur'),
('Ampulün watt değeri neyi gösterir?', '["Işık rengini","Güç tüketimini","Ömrünü","Boyutunu"]'::jsonb, 1, 'genel_kultur'),
('LED ampulün avuç içi avantajı nedir?', '["Kısa ömrü","Çok ısınması","Az enerji tüketmesi","Ağırlığı"]'::jsonb, 2, 'genel_kultur'),
('Güneş enerjisi hangi tür kaynaktır?', '["Kimyasal atık","Fosil","Nükleer","Yenilenebilir"]'::jsonb, 3, 'genel_kultur'),
('Rüzgâr enerjisinde en önemli koşul nedir?', '["Sürekli rüzgâr","Bol yağmur","Sıcaklık","Kar"]'::jsonb, 0, 'genel_kultur'),
('Su tasarrufu için duşta ne yapılır?', '["Suyu açık bırakmak","Süreyi kısaltmak","Küvet doldurmak","Sıcak tutmak"]'::jsonb, 1, 'genel_kultur'),
('Atık pilller nereye atılır?', '["Lavaboya","Çöpe","Özel kutulara","Bahçeye"]'::jsonb, 2, 'genel_kultur'),
('Kâğıt geri dönüşümü neyi korur?', '["Petrolü yalnızca","Denizleri yalnızca","Madenleri","Ağaçları"]'::jsonb, 3, 'genel_kultur'),
('Cam geri dönüşümünde cam kaç kez dönüştürülebilir?', '["Defalarca","Bir kez","İki kez","Hiç"]'::jsonb, 0, 'genel_kultur'),
('Sıfır atık yaklaşımının amacı nedir?', '["Atığı yakmak","Atığı en aza indirmek","Atığı gömmek","Atığı biriktirmek"]'::jsonb, 1, 'genel_kultur'),
('Kompostun tarımdaki karşılığı nedir?', '["Tohum","Böcek ilacı","Doğal gübre","Sulama"]'::jsonb, 2, 'genel_kultur'),
('Bir ürünün "son tüketim" ile "tavsiye edilen tüketim" tarihi farkı nedir?', '["Biri ağırlık","İkisi aynı","Biri fiyat","Biri güvenlik, diğeri kalite"]'::jsonb, 3, 'genel_kultur'),
('Gıda zehirlenmesini önlemenin temel yolu nedir?', '["Uygun saklama ve pişirme","Çok tuz","Çok şeker","Az su"]'::jsonb, 0, 'genel_kultur'),
('Çiğ ve pişmiş gıdalar neden ayrı tutulur?', '["Yer kazanmak","Çapraz bulaşmayı önlemek","Renk için","Koku için"]'::jsonb, 1, 'genel_kultur'),
('Buzdolabında en soğuk bölüm neresidir?', '["Üst raf","Kapak","Alt raflar","Sebzelik"]'::jsonb, 2, 'genel_kultur'),
('Dondurulmuş gıda nasıl çözdürülmelidir?', '["Radyatörde","Güneşte","Sıcak suda hep","Buzdolabında"]'::jsonb, 3, 'genel_kultur'),
('Yemek pişirirken tencere kapağı kapalıysa ne olur?', '["Daha az enerji harcanır","Daha çok enerji","Tat kaybolur","Süre uzar"]'::jsonb, 0, 'genel_kultur'),
('Zeytinyağının dumanlanma noktası neyi belirler?', '["Rengini","Pişirmeye uygunluğunu","Fiyatını","Şişesini"]'::jsonb, 1, 'genel_kultur'),
('Bal neden bozulmaz?', '["Soğuk olduğu için","Şekersiz olduğu için","Düşük nem ve doğal yapısı","Tuzlu olduğu için"]'::jsonb, 2, 'genel_kultur'),
('Ekmek buzdolabında neden çabuk bayatlar?', '["Isındığı için","Soğuk olduğu için tazelenir","Nemlendiği için","Nişasta yapısı değiştiği için"]'::jsonb, 3, 'genel_kultur'),
('Çayın demlenmesi ne kadar sürer (yaklaşık)?', '["5-10 dakika","1 saniye","1 saat","1 gün"]'::jsonb, 0, 'genel_kultur'),
('Kahve çekirdeği hangi işlemden sonra öğütülür?', '["Dondurma","Kavurma","Haşlama","Kurutma yalnızca"]'::jsonb, 1, 'genel_kultur'),
('Süt neden pastörize edilir?', '["Renklendirmek","Tatlandırmak","Zararlı mikropları azaltmak","Ağırlaştırmak"]'::jsonb, 2, 'genel_kultur'),
('Yumurtanın tazeliği nasıl anlaşılır?', '["Ağırlığından","Sallayarak hep","Renginden","Suya batırılarak"]'::jsonb, 3, 'genel_kultur'),
('Kuru baklagiller pişirmeden önce neden ıslatılır?', '["Pişme süresini kısaltmak","Renk vermek","Tuzlamak","Ağırlaştırmak"]'::jsonb, 0, 'genel_kultur'),
('Makarna suyuna tuz ne zaman atılır?', '["En başta hep","Su kaynayınca","En sonda","Hiç atılmaz"]'::jsonb, 1, 'genel_kultur'),
('Hamurun dinlendirilmesi neyi sağlar?', '["Kurumasını","Sertleşmesini","Kolay şekil almasını","Renk almasını"]'::jsonb, 2, 'genel_kultur'),
('Fırında pişen keklerin ortası neden çöker?', '["Soğuk yumurta","Fazla un","Az şeker","Erken kapak açma ve ısı düşüşü"]'::jsonb, 3, 'genel_kultur'),
('Bir tarifte "kısık ateş" ne demektir?', '["Düşük ısı","En yüksek ısı","Ateşsiz","Fırın"]'::jsonb, 0, 'genel_kultur'),
('Ölçü kaşığı ile çay kaşığı farkı nedir?', '["Renk","Standart hacim","Malzeme","Uzunluk"]'::jsonb, 1, 'genel_kultur'),
('Mutfakta çapraz bulaşmayı önlemek için ne kullanılır?', '["Aynı tabak","Aynı bıçak","Ayrı kesme tahtaları","Aynı bez"]'::jsonb, 2, 'genel_kultur'),
('Bulaşık makinesinde parlatıcı ne işe yarar?', '["Kokulandırır yalnızca","Isıtır","Köpürtür","Leke bırakmadan kurutur"]'::jsonb, 3, 'genel_kultur'),
('Çamaşırda renklileri ayırmanın sebebi nedir?', '["Renk vermesini önlemek","Yer kazanmak","Hızlı yıkamak","Az deterjan"]'::jsonb, 0, 'genel_kultur'),
('Yün kazak nasıl kurutulmalıdır?', '["Askıda","Düz zeminde serilerek","Radyatörde","Güneşte asılı"]'::jsonb, 1, 'genel_kultur'),
('Leke çıkarmada en önemli kural nedir?', '["Ütülemek","Beklemek","Hemen müdahale etmek","Kurutmak"]'::jsonb, 2, 'genel_kultur'),
('Ayakkabı bakımında kalıp ne işe yarar?', '["Isıtır","Rengini değiştirir","Ağırlaştırır","Formunu korur"]'::jsonb, 3, 'genel_kultur'),
('Bitki sulamada sabah saatleri neden tercih edilir?', '["Buharlaşma az olduğu için","Işık çok olduğu için","Rüzgâr için","Soğuk için"]'::jsonb, 0, 'genel_kultur'),
('Evde nem oranı yüksekse ne oluşabilir?', '["Kuraklık","Küf","Statik elektrik","Toz azalması"]'::jsonb, 1, 'genel_kultur'),
('Havalandırma neden önemlidir?', '["Gürültü için","Isı kaybı için","Temiz hava ve nem dengesi","Işık için"]'::jsonb, 2, 'genel_kultur'),
('Uyku düzeni için akşam nelerden kaçınılmalıdır?', '["Yürüyüş","Su içmek","Kitap okumak","Kafein ve parlak ekran"]'::jsonb, 3, 'genel_kultur'),
('Stresi azaltmada etkili basit yöntem nedir?', '["Düzenli nefes ve hareket","Uykusuzluk","Aç kalmak","Hareketsizlik"]'::jsonb, 0, 'genel_kultur'),
('Zaman yönetiminde "acil ve önemli" ayrımı neye yarar?', '["Uyumaya","Önceliklendirmeye","Harcamaya","Gezmeye"]'::jsonb, 1, 'genel_kultur'),
('Bir toplantıda gündem ne işe yarar?', '["Katılımı azaltır","Süreyi uzatır","Konuları sıralar","Karar verir"]'::jsonb, 2, 'genel_kultur'),
('Geri bildirim verirken en etkili yaklaşım nedir?', '["Susmak","Genel konuşmak","Suçlamak","Somut ve yapıcı olmak"]'::jsonb, 3, 'genel_kultur'),
('Bir ekipte rol dağılımı neden yapılır?', '["Sorumluluk netleşsin diye","Kalabalık olsun diye","Süre uzasın diye","Maliyet artsın diye"]'::jsonb, 0, 'genel_kultur'),
('Bir projede "kilometre taşı" ne demektir?', '["Bütçe kalemi","Önemli ara hedef","Toplantı","Rapor türü"]'::jsonb, 1, 'genel_kultur'),
('Risk yönetiminde ilk adım nedir?', '["Ekip kurmak","Bütçe artırmak","Riskleri belirlemek","Rapor yazmak"]'::jsonb, 2, 'genel_kultur'),
('Bir ürünün prototipi ne işe yarar?', '["Vergilendirmeye","Satışa","Reklama","Fikri denemeye"]'::jsonb, 3, 'genel_kultur')

on conflict (soru) do nothing;

-- ===================== BİLİM (200) =====================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- Kimya
('Bir atomda nötronlar nerede bulunur?', '["Çekirdekte","Yörüngede","Dışta","Bağlarda"]'::jsonb, 0, 'bilim'),
('Periyodik tabloda dikey sütunlara ne denir?', '["Periyot","Grup","Blok","Seri"]'::jsonb, 1, 'bilim'),
('Periyodik tabloda yatay sıralara ne denir?', '["Blok","Grup","Periyot","Küme"]'::jsonb, 2, 'bilim'),
('Metallerin ortak özelliği nedir?', '["Uçucu olması","Kırılgan olması","Renksiz olması","Isı ve elektriği iletmesi"]'::jsonb, 3, 'bilim'),
('Ametallerin genel özelliği nedir?', '["Kötü iletken olmaları","İyi iletken olmaları","Parlak olmaları","Dövülebilir olmaları"]'::jsonb, 0, 'bilim'),
('İki atom arasında elektron ortaklaşmasıyla oluşan bağ hangisidir?', '["İyonik","Kovalent","Metalik","Hidrojen"]'::jsonb, 1, 'bilim'),
('Elektron alışverişiyle oluşan bağ hangisidir?', '["Metalik","Kovalent","İyonik","Van der Waals"]'::jsonb, 2, 'bilim'),
('Suyun kaynama noktası yükseklerde neden düşer?', '["Yoğunluk arttığı için","Sıcaklık arttığı için","Nem arttığı için","Basınç azaldığı için"]'::jsonb, 3, 'bilim'),
('Çözeltide çözen madde genellikle hangisidir?', '["Miktarı çok olan","Miktarı az olan","Katı olan","Renkli olan"]'::jsonb, 0, 'bilim'),
('Doymuş çözelti ne demektir?', '["Hiç çözünmemiş","Daha fazla çözünmeyen","Seyreltik","Kaynayan"]'::jsonb, 1, 'bilim'),
('Kimyasal tepkimede katalizör ne yapar?', '["Kütleyi artırır","Ürünü değiştirir","Hızı artırır","Isıyı yok eder"]'::jsonb, 2, 'bilim'),
('Ekzotermik tepkimede ne olur?', '["Renk kaybolur","Isı soğurulur","Kütle artar","Isı açığa çıkar"]'::jsonb, 3, 'bilim'),
('Endotermik tepkimede ne olur?', '["Isı soğurulur","Isı açığa çıkar","Kütle azalır","Basınç sabitlenir"]'::jsonb, 0, 'bilim'),
('Asitlerin pH aralığı nedir?', '["7-14 arası","0-7 arası","Tam 7","14 üstü"]'::jsonb, 1, 'bilim'),
('Bazların pH aralığı nedir?', '["Tam 0","0-7 arası","7-14 arası","Negatif"]'::jsonb, 2, 'bilim'),
('Sirkedeki asidin adı nedir?', '["Karbonik asit","Sülfürik asit","Nitrik asit","Asetik asit"]'::jsonb, 3, 'bilim'),
('Limon ve portakaldaki asit hangisidir?', '["Sitrik asit","Asetik asit","Laktik asit","Formik asit"]'::jsonb, 0, 'bilim'),
('Midede sindirime yardımcı asit hangisidir?', '["Sitrik asit","Hidroklorik asit","Asetik asit","Karbonik asit"]'::jsonb, 1, 'bilim'),
('Sabun hangi tepkimeyle üretilir?', '["Fotosentez","Yanma","Sabunlaşma","Nötrleşme değil"]'::jsonb, 2, 'bilim'),
('Alaşım nedir?', '["Çözelti değil","Saf element","Bileşik","Metal karışımı"]'::jsonb, 3, 'bilim'),
('Bronz hangi metallerin alaşımıdır?', '["Bakır ve kalay","Demir ve karbon","Bakır ve çinko","Altın ve gümüş"]'::jsonb, 0, 'bilim'),
('Pirinç (metal) hangi metallerin alaşımıdır?', '["Bakır ve kalay","Bakır ve çinko","Demir ve nikel","Altın ve bakır"]'::jsonb, 1, 'bilim'),
('Çelik hangi elementlerin bileşiminden oluşur?', '["Alüminyum ve çinko","Bakır ve kalay","Demir ve karbon","Kurşun ve kalay"]'::jsonb, 2, 'bilim'),
('Suyun sertliğine neden olan mineraller hangileridir?', '["Bakır ve kurşun","Sodyum ve klor","Demir ve çinko","Kalsiyum ve magnezyum"]'::jsonb, 3, 'bilim'),
('Kireç taşının kimyasal adı nedir?', '["Kalsiyum karbonat","Sodyum klorür","Potasyum nitrat","Magnezyum oksit"]'::jsonb, 0, 'bilim'),

-- Fizik
('Bir cismin ağırlığı neye bağlıdır?', '["Yalnız hacim","Kütle ve yer çekimi","Yalnız renk","Yalnız sıcaklık"]'::jsonb, 1, 'bilim'),
('Serbest düşen bir cismin ivmesi neye eşittir?', '["Hızına","Sıfıra","Yer çekimi ivmesine","Kütlesine"]'::jsonb, 2, 'bilim'),
('Sürtünmesiz ortamda tüy ve taş nasıl düşer?', '["Hiç düşmez","Taş önce","Tüy önce","Aynı anda"]'::jsonb, 3, 'bilim'),
('Basınç nasıl hesaplanır?', '["Kuvvet bölü alan","Kuvvet çarpı alan","Alan bölü kuvvet","Kütle çarpı hız"]'::jsonb, 0, 'bilim'),
('Sivri uçlu cisimler neden daha kolay batar?', '["Alan büyük","Alan küçük, basınç büyük","Kuvvet küçük","Kütle az"]'::jsonb, 1, 'bilim'),
('Sıvı basıncı neye bağlıdır?', '["Kabın rengi","Kabın şekli","Derinlik ve yoğunluk","Kabın ağırlığı"]'::jsonb, 2, 'bilim'),
('Bir cisim sıvıda yüzüyorsa yoğunluğu nasıldır?', '["Eşittir hep","Sıvıdan büyüktür","Sıfırdır","Sıvıdan küçüktür"]'::jsonb, 3, 'bilim'),
('Isı ile sıcaklık arasındaki fark nedir?', '["Isı enerji, sıcaklık ölçüdür","İkisi aynıdır","Isı ölçüdür","Sıcaklık enerjidir"]'::jsonb, 0, 'bilim'),
('Bir maddenin öz ısısı neyi belirtir?', '["Rengini","Isınma zorluğunu","Kütlesini","Hacmini"]'::jsonb, 1, 'bilim'),
('Suyun öz ısısının yüksek olması neye yol açar?', '["Hızlı donmasına","Hızlı kaynamasına","Geç ısınıp geç soğumasına","Renk değişimine"]'::jsonb, 2, 'bilim'),
('Termometrede cıva yerine hangi sıvı da kullanılır?', '["Sirke","Su","Yağ","Alkol"]'::jsonb, 3, 'bilim'),
('Sesin havadaki hızı yaklaşık kaç m/s''dir?', '["340","3000","30","34000"]'::jsonb, 0, 'bilim'),
('Yankı nasıl oluşur?', '["Sesin kırılmasıyla","Sesin yansımasıyla","Işıkla","Isıyla"]'::jsonb, 1, 'bilim'),
('Sesin yüksekliği (ince-kalın) neye bağlıdır?', '["Hıza","Genliğe","Frekansa","Sıcaklığa"]'::jsonb, 2, 'bilim'),
('Sesin şiddeti neye bağlıdır?', '["Hıza","Frekansa","Renge","Genliğe"]'::jsonb, 3, 'bilim'),
('Işığın bir yıldaki yol aldığı uzaklığa ne denir?', '["Işık yılı","Parsek","Astronomi birimi","Angstrom"]'::jsonb, 0, 'bilim'),
('Beyaz ışık kaç ana renkten oluşur (gökkuşağı)?', '["3","7","5","10"]'::jsonb, 1, 'bilim'),
('Bir cisim kırmızı görünüyorsa ne yapıyordur?', '["Işık üretiyordur","Kırmızıyı yutuyordur","Kırmızıyı yansıtıyordur","Işığı kırıyordur"]'::jsonb, 2, 'bilim'),
('Siyah cisimler ışığa ne yapar?', '["Üretir","Yansıtır","Kırar","Soğurur"]'::jsonb, 3, 'bilim'),
('Düz aynada görüntü nasıldır?', '["Zıt çevrilmiş ve eşit büyüklükte","Ters ve küçük","Ters ve büyük","Renkli"]'::jsonb, 0, 'bilim'),
('İnce kenarlı mercek ışığı ne yapar?', '["Dağıtır","Toplar","Yutar","Yansıtır"]'::jsonb, 1, 'bilim'),
('Kalın kenarlı mercek ışığı ne yapar?', '["Yutar","Toplar","Dağıtır","Renklendirir"]'::jsonb, 2, 'bilim'),
('Miyop göz kusurunda görüntü nerede oluşur?', '["Kornea üstünde","Retinanın arkasında","Retinada","Retinanın önünde"]'::jsonb, 3, 'bilim'),
('Hipermetrop göz kusurunda görüntü nerede oluşur?', '["Retinanın arkasında","Retinanın önünde","Retinada","İris üstünde"]'::jsonb, 0, 'bilim'),
('Elektrik akımının yönü hangi yüklerin hareketiyle tanımlanır?', '["Nötron","Pozitif yük yönü","Foton","Proton hareketi"]'::jsonb, 1, 'bilim'),
('Bir iletkenin direnci neye bağlıdır?', '["Ağırlığına","Rengine","Uzunluk, kesit ve cinsi","Şekline yalnızca"]'::jsonb, 2, 'bilim'),
('Elektromıknatıs nasıl oluşturulur?', '["Boyayarak","Isıtarak","Soğutarak","Bobinden akım geçirerek"]'::jsonb, 3, 'bilim'),
('Jeneratör hangi dönüşümü yapar?', '["Hareketi elektriğe","Elektriği ışığa","Isıyı sese","Sesi ısıya"]'::jsonb, 0, 'bilim'),
('Elektrik motoru hangi dönüşümü yapar?', '["Hareketi elektriğe","Elektriği harekete","Isıyı ışığa","Sesi elektriğe"]'::jsonb, 1, 'bilim'),
('Transformatör ne işe yarar?', '["Direnci yok eder","Akımı üretir","Gerilimi değiştirir","Işık verir"]'::jsonb, 2, 'bilim'),
('Nükleer füzyon nedir?', '["Yanma","Çekirdeğin bölünmesi","Elektron kaybı","Çekirdeklerin birleşmesi"]'::jsonb, 3, 'bilim'),
('Nükleer fisyon nedir?', '["Çekirdeğin bölünmesi","Çekirdeklerin birleşmesi","Elektron kazanımı","Buharlaşma"]'::jsonb, 0, 'bilim'),
('Radyoaktif maddenin yarılanma süresi neyi gösterir?', '["Tamamının bozunmasını","Yarısının bozunma süresini","Erime noktasını","Kaynama noktasını"]'::jsonb, 1, 'bilim'),

-- Biyoloji
('Hücre zarının temel görevi nedir?', '["Protein sentezlemek","Enerji üretmek","Madde geçişini denetlemek","Kalıtım taşımak"]'::jsonb, 2, 'bilim'),
('Ribozomun görevi nedir?', '["Depolama","Enerji üretimi","Sindirim","Protein sentezi"]'::jsonb, 3, 'bilim'),
('Kloroplastın görevi nedir?', '["Fotosentez","Solunum","Sindirim","Boşaltım"]'::jsonb, 0, 'bilim'),
('Lizozomun görevi nedir?', '["Protein sentezi","Hücre içi sindirim","Enerji üretimi","Bölünme"]'::jsonb, 1, 'bilim'),
('Hücre çekirdeğinin görevi nedir?', '["Madde depolamak","Enerji üretmek","Kalıtım bilgisini taşımak","Hareket sağlamak"]'::jsonb, 2, 'bilim'),
('Mitoz bölünme sonucunda ne oluşur?', '["Sekiz hücre","Dört farklı hücre","Bir hücre","İki özdeş hücre"]'::jsonb, 3, 'bilim'),
('Mayoz bölünme hangi hücrelerde görülür?', '["Üreme hücrelerinde","Deri hücrelerinde","Kas hücrelerinde","Sinir hücrelerinde"]'::jsonb, 0, 'bilim'),
('Enzimlerin yapısı nedir?', '["Yağ","Protein","Karbonhidrat","Mineral"]'::jsonb, 1, 'bilim'),
('Enzimler neye duyarlıdır?', '["Ses","Renk","Sıcaklık ve pH","Işık yalnızca"]'::jsonb, 2, 'bilim'),
('Fotosentez hangi organelde gerçekleşir?', '["Koful","Mitokondri","Ribozom","Kloroplast"]'::jsonb, 3, 'bilim'),
('Fotosentez için gerekli olmayan hangisidir?', '["Oksijen","Su","Karbondioksit","Işık"]'::jsonb, 0, 'bilim'),
('Bitkilerde su kaybına ne denir?', '["Fotosentez","Terleme","Solunum","Çimlenme"]'::jsonb, 1, 'bilim'),
('Kalbin kaç odacığı vardır?', '["3","2","4","5"]'::jsonb, 2, 'bilim'),
('Kalpten vücuda kan taşıyan damarlara ne denir?', '["Lenf damarı","Toplardamar","Kılcal damar","Atardamar"]'::jsonb, 3, 'bilim'),
('Vücuttan kalbe kan taşıyan damarlara ne denir?', '["Toplardamar","Atardamar","Kılcal","Aort"]'::jsonb, 0, 'bilim'),
('Küçük kan dolaşımı hangi organlar arasındadır?', '["Kalp ve böbrek","Kalp ve akciğer","Beyin ve kalp","Mide ve kalp"]'::jsonb, 1, 'bilim'),
('Soluk alırken diyafram ne yapar?', '["Hareketsiz kalır","Gevşer ve yükselir","Kasılır ve alçalır","Genişlemez"]'::jsonb, 2, 'bilim'),
('Akciğerlerde gaz alışverişi nerede olur?', '["Gırtlakta","Bronşlarda","Soluk borusunda","Alveollerde"]'::jsonb, 3, 'bilim'),
('İdrarın oluştuğu organ hangisidir?', '["Böbrek","Karaciğer","Mide","Dalak"]'::jsonb, 0, 'bilim'),
('Pankreasın sindirimdeki rolü nedir?', '["Kan üretmek","Enzim salgılamak","Hava taşımak","Kemik yapmak"]'::jsonb, 1, 'bilim'),
('Merkezî sinir sistemi neleri kapsar?', '["Kas ve kemik","Kalp ve damar","Beyin ve omurilik","Deri ve tırnak"]'::jsonb, 2, 'bilim'),
('Refleks hangi yapıyla hızlı gerçekleşir?', '["Böbrek","Ön beyin","Hipofiz","Omurilik"]'::jsonb, 3, 'bilim'),
('İskelet sisteminin görevlerinden biri nedir?', '["Destek ve koruma","Sindirim","Solunum","Boşaltım"]'::jsonb, 0, 'bilim'),
('Kaslar kemiklere neyle bağlanır?', '["Bağ dokusu yok","Kiriş (tendon)","Kıkırdak","Deri"]'::jsonb, 1, 'bilim'),
('İstemsiz çalışan kas türü hangisidir?', '["Çizgili kas","İskelet kası","Düz kas","Kol kası"]'::jsonb, 2, 'bilim'),
('Bağışıklıkta antikorları hangi hücreler üretir?', '["Kas hücreleri","Alyuvarlar","Trombositler","Akyuvarlar"]'::jsonb, 3, 'bilim'),
('Aşının çalışma prensibi nedir?', '["Bağışıklığı önceden uyarmak","Mikropları öldürmek doğrudan","Ateşi düşürmek","Ağrıyı kesmek"]'::jsonb, 0, 'bilim'),
('Kan grubu sisteminde evrensel verici hangisidir?', '["AB Rh pozitif","0 Rh negatif","A Rh pozitif","B Rh negatif"]'::jsonb, 1, 'bilim'),
('Kan grubu sisteminde evrensel alıcı hangisidir?', '["A Rh negatif","0 Rh negatif","AB Rh pozitif","B Rh pozitif"]'::jsonb, 2, 'bilim'),
('DNA''nın yapı birimine ne denir?', '["Yağ asidi","Aminoasit","Glikoz","Nükleotid"]'::jsonb, 3, 'bilim'),
('Proteinlerin yapı birimi nedir?', '["Aminoasit","Nükleotid","Glikoz","Gliserol"]'::jsonb, 0, 'bilim'),
('Karbonhidratların yapı birimi nedir?', '["Aminoasit","Glikoz","Nükleotid","Yağ asidi"]'::jsonb, 1, 'bilim'),
('Kalıtımda baskın gen nasıl gösterilir?', '["Rakamla","Küçük harfle","Büyük harfle","Sembolsüz"]'::jsonb, 2, 'bilim'),
('İnsanda cinsiyeti belirleyen kromozomlar hangileridir?', '["M ve N","A ve B","R ve S","X ve Y"]'::jsonb, 3, 'bilim'),
('Bakteriler hangi yapıya sahip değildir?', '["Çekirdek zarı","Hücre zarı","Ribozom","Sitoplazma"]'::jsonb, 0, 'bilim'),
('Antibiyotikler hangi canlılara etki etmez?', '["Bakterilere","Virüslere","Bazı mantarlara","Parazitlere"]'::jsonb, 1, 'bilim'),
('Mantarların beslenme şekli nedir?', '["Kemosentez","Fotosentez","Dışarıdan hazır besin","Işıkla"]'::jsonb, 2, 'bilim'),
('Ekosistemde ayrıştırıcılara örnek hangisidir?', '["Çam","Aslan","Kartal","Bakteri ve mantar"]'::jsonb, 3, 'bilim'),
('Besin zincirinde her basamakta enerjiye ne olur?', '["Azalır","Artar","Sabit kalır","İkiye katlanır"]'::jsonb, 0, 'bilim'),
('Simbiyoz ilişkide her iki tarafın yarar görmesine ne denir?', '["Parazitlik","Mutualizm","Avcılık","Rekabet"]'::jsonb, 1, 'bilim'),
('Bir türün tamamen yok olmasına ne denir?', '["Adaptasyon","Göç","Nesli tükenme","Mutasyon"]'::jsonb, 2, 'bilim'),
('Adaptasyon ne demektir?', '["Bölünme","Yok olma","Göç etme","Çevreye uyum"]'::jsonb, 3, 'bilim'),
('Mutasyon nedir?', '["Kalıtsal maddede değişim","Beslenme şekli","Göç türü","Solunum çeşidi"]'::jsonb, 0, 'bilim'),

-- Yer bilimleri ve astronomi
('Yer kabuğundaki en yaygın element hangisidir?', '["Demir","Oksijen","Karbon","Altın"]'::jsonb, 1, 'bilim'),
('Fosiller hangi kayaçlarda bulunur?', '["Başkalaşım","Püskürük","Tortul","Volkanik cam"]'::jsonb, 2, 'bilim'),
('Elmasın sertliği Mohs ölçeğinde kaçtır?', '["1","5","7","10"]'::jsonb, 3, 'bilim'),
('Mohs ölçeğinde en yumuşak mineral hangisidir?', '["Talk","Elmas","Kuvars","Korund"]'::jsonb, 0, 'bilim'),
('Depremin oluştuğu yer altı noktasına ne denir?', '["Dış merkez","Odak (iç merkez)","Fay yüzeyi","Kırık ucu"]'::jsonb, 1, 'bilim'),
('Depremin yeryüzündeki izdüşümüne ne denir?', '["Odak","İç merkez","Dış merkez","Kuşak"]'::jsonb, 2, 'bilim'),
('Yer altındaki erimiş kayaca ne denir?', '["Tüf","Lav","Bazalt","Magma"]'::jsonb, 3, 'bilim'),
('Ay''ın kendi ışığı var mıdır?', '["Yoktur, yansıtır","Vardır","Kısmen üretir","Yalnız dolunayda"]'::jsonb, 0, 'bilim'),
('Güneş tutulması nasıl oluşur?', '["Dünya araya girince","Ay, Dünya ile Güneş arasına girince","Güneş sönünce","Bulut kapatınca"]'::jsonb, 1, 'bilim'),
('Gelgit olayının başlıca nedeni nedir?', '["Yağmur","Rüzgâr","Ay''ın çekim kuvveti","Deprem"]'::jsonb, 2, 'bilim'),
('Meteor ile göktaşı arasındaki fark nedir?', '["Göktaşı yanar","İkisi aynıdır","Meteor yere ulaşır","Göktaşı yere ulaşandır"]'::jsonb, 3, 'bilim'),
('Bir yıldızın rengi neyi gösterir?', '["Sıcaklığını","Yaşını yalnızca","Uzaklığını","Kütlesini yalnızca"]'::jsonb, 0, 'bilim'),
('Kara delik nedir?', '["Boş uzay","Çekimi ışığı bile bırakmayan cisim","Soğuk yıldız","Gaz bulutu"]'::jsonb, 1, 'bilim'),
('Nebula nedir?', '["Bir uydu","Bir gezegen","Gaz ve toz bulutu","Bir kuyruklu yıldız"]'::jsonb, 2, 'bilim'),
('Evrenin genişlediği fikri hangi gözleme dayanır?', '["Meteorlar","Ay''ın hareketi","Güneş lekeleri","Galaksilerin uzaklaşması"]'::jsonb, 3, 'bilim'),

-- Matematik ve ölçüm
('Bir sayının karekökü neyi verir?', '["Kendisiyle çarpılınca o sayıyı veren sayıyı","İki katını","Yarısını","Küpünü"]'::jsonb, 0, 'bilim'),
('Pi sayısı hangi orandan gelir?', '["Alan bölü çevre","Çevre bölü çap","Çap bölü yarıçap","Alan bölü çap"]'::jsonb, 1, 'bilim'),
('Bir üçgenin alanı nasıl hesaplanır?', '["Kenarlar toplamı","Taban çarpı yükseklik","Taban çarpı yükseklik bölü 2","Çevre bölü 2"]'::jsonb, 2, 'bilim'),
('Dikdörtgenin alanı nasıl bulunur?', '["Köşegen karesi","Kenarlar toplamı","Çevre bölü 2","Uzun kenar çarpı kısa kenar"]'::jsonb, 3, 'bilim'),
('Karenin çevresi nasıl bulunur?', '["Kenar çarpı 4","Kenar karesi","Kenar çarpı 2","Köşegen çarpı 4"]'::jsonb, 0, 'bilim'),
('Bir açının 180 dereceye tamamlayanına ne denir?', '["Tümler açı","Bütünler açı","Ters açı","Dik açı"]'::jsonb, 1, 'bilim'),
('Bir açının 90 dereceye tamamlayanına ne denir?', '["Komşu açı","Bütünler açı","Tümler açı","Geniş açı"]'::jsonb, 2, 'bilim'),
('Pisagor bağıntısı hangi üçgende geçerlidir?', '["Her üçgen","Eşkenar üçgen","Geniş açılı üçgen","Dik üçgen"]'::jsonb, 3, 'bilim'),
('Bir zar atıldığında 6 gelme olasılığı kaçtır?', '["1/6","1/2","1/3","1/12"]'::jsonb, 0, 'bilim'),
('Bir madenî para atıldığında yazı gelme olasılığı kaçtır?', '["1/4","1/2","1/6","1/3"]'::jsonb, 1, 'bilim'),
('Aritmetik ortalama nasıl bulunur?', '["En büyük eksi en küçük","Adet bölü toplam","Toplam bölü adet","Ortadaki değer"]'::jsonb, 2, 'bilim'),
('En büyük ile en küçük değerin farkına ne denir?', '["Mod","Ortalama","Medyan","Açıklık"]'::jsonb, 3, 'bilim'),
('Bir sayının mutlak değeri ne verir?', '["İşaretsiz büyüklüğünü","Karesini","Tersini","Yarısını"]'::jsonb, 0, 'bilim'),
('Negatif sayı ile negatif sayının çarpımı nasıldır?', '["Negatif","Pozitif","Sıfır","Belirsiz"]'::jsonb, 1, 'bilim'),
('Sıfırın herhangi bir sayıyla çarpımı kaçtır?', '["Sayının kendisi","1","0","Tanımsız"]'::jsonb, 2, 'bilim'),
('Bir sayının sıfırıncı kuvveti kaçtır (sıfır hariç)?', '["Tanımsız","0","Sayının kendisi","1"]'::jsonb, 3, 'bilim'),

-- Bilim tarihi ve yöntem
('Bilimsel yöntemin ilk adımı nedir?', '["Gözlem ve problem belirleme","Sonuç yazma","Yayın yapma","Ödül alma"]'::jsonb, 0, 'bilim'),
('Hipotez nedir?', '["Kesin sonuç","Test edilebilir öngörü","Yasa","Teori"]'::jsonb, 1, 'bilim'),
('Kontrollü deneyde kontrol grubunun amacı nedir?', '["Süreyi kısaltmak","Sonucu değiştirmek","Karşılaştırma sağlamak","Maliyeti azaltmak"]'::jsonb, 2, 'bilim'),
('Bilimsel teori ne demektir?', '["Fikir","Tahmin","Varsayım","Kanıtlarla desteklenmiş açıklama"]'::jsonb, 3, 'bilim'),
('Akran değerlendirmesi (hakem) ne işe yarar?', '["Çalışmayı denetlemek","Hızlandırmak","Ücret belirlemek","Reklam yapmak"]'::jsonb, 0, 'bilim'),
('Aşıyı ilk uygulayan olarak bilinen kişi kimdir?', '["Louis Pasteur","Edward Jenner","Robert Koch","Alexander Fleming"]'::jsonb, 1, 'bilim'),
('Verem basilini bulan bilim insanı kimdir?', '["Edward Jenner","Louis Pasteur","Robert Koch","Joseph Lister"]'::jsonb, 2, 'bilim'),
('Ameliyatlarda antisepsiyi geliştiren kişi kimdir?', '["Charles Darwin","Robert Koch","Gregor Mendel","Joseph Lister"]'::jsonb, 3, 'bilim'),
('Radyoaktiviteyi keşfeden bilim insanı kimdir?', '["Henri Becquerel","Isaac Newton","Michael Faraday","James Watt"]'::jsonb, 0, 'bilim'),
('Kuantum kuramının öncülerinden biri kimdir?', '["Isaac Newton","Max Planck","Galileo","Kepler"]'::jsonb, 1, 'bilim'),
('DNA''nın çift sarmal yapısını açıklayan çalışmada kimler öne çıkar?', '["Curie ve Becquerel","Newton ve Hooke","Watson ve Crick","Darwin ve Wallace"]'::jsonb, 2, 'bilim'),
('Alternatif akım çalışmalarıyla tanınan mucit kimdir?', '["Michael Faraday","Thomas Edison","James Watt","Nikola Tesla"]'::jsonb, 3, 'bilim'),
('Termodinamiğin birinci yasası neyi ifade eder?', '["Enerjinin korunumunu","Entropinin artışını","Mutlak sıfırı","Basınç artışını"]'::jsonb, 0, 'bilim'),
('Entropi kavramı neyi ölçer?', '["Sıcaklığı","Düzensizliği","Basıncı","Kütleyi"]'::jsonb, 1, 'bilim'),
('Kütlenin korunumu yasasını ortaya koyan kimdir?', '["Avogadro","Dalton","Lavoisier","Mendeleyev"]'::jsonb, 2, 'bilim'),
('Bir gazın hacmi basınçla nasıl değişir (sabit sıcaklıkta)?', '["Karesiyle artar","Doğru orantılı","Değişmez","Ters orantılı"]'::jsonb, 3, 'bilim'),
('Bir gazın hacmi sıcaklıkla nasıl değişir (sabit basınçta)?', '["Doğru orantılı","Ters orantılı","Değişmez","Kübik azalır"]'::jsonb, 0, 'bilim')

on conflict (soru) do nothing;

-- ===================== BİLİM (ek) + TARİH =====================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- Bilim (ek 50)
('Bir bileşiği oluşturan elementler hangi yolla ayrılır?', '["Fiziksel yolla","Kimyasal yolla","Süzerek","Eleyerek"]'::jsonb, 1, 'bilim'),
('Homojen olmayan karışıma ne denir?', '["Bileşik","Çözelti","Heterojen karışım","Element"]'::jsonb, 2, 'bilim'),
('Buz, su ve su buharı neyin farklı hâlleridir?', '["Bileşiğin değil","Farklı maddelerin","Karışımın","Aynı maddenin"]'::jsonb, 3, 'bilim'),
('Erime ısısı neyi ifade eder?', '["Katıdan sıvıya geçiş için gereken ısı","Sıcaklık artışı","Kütle kaybı","Hacim artışı"]'::jsonb, 0, 'bilim'),
('Bir maddenin hâl değişimi sırasında sıcaklık ne yapar?', '["Sürekli artar","Sabit kalır","Sürekli azalır","İki katına çıkar"]'::jsonb, 1, 'bilim'),
('Genleşme en çok hangi hâlde görülür?', '["Sıvı","Katı","Gaz","Plazma değil"]'::jsonb, 2, 'bilim'),
('Bimetal şerit neden kullanılır?', '["Basınç ölçmek","Işık üretmek","Ses vermek","Sıcaklık değişimini algılamak"]'::jsonb, 3, 'bilim'),
('Yalıtım malzemesi ne sağlar?', '["Isı geçişini azaltır","Isıyı artırır","Elektrik iletir","Ses üretir"]'::jsonb, 0, 'bilim'),
('Kılcallık olayı hangi kuvvetlerle açıklanır?', '["Yer çekimi yalnızca","Yapışma ve birleşme","Manyetizma","Sürtünme"]'::jsonb, 1, 'bilim'),
('Yüzey gerilimi sayesinde ne gerçekleşir?', '["Donma","Buharlaşma","Su damlasının küresel olması","Erime"]'::jsonb, 2, 'bilim'),
('Deniz suyunun tuzluluğu neye yol açar?', '["Yoğunluk azalmasına","Kaynama noktasının düşmesine","Renk değişimine","Donma noktasının düşmesine"]'::jsonb, 3, 'bilim'),
('Bir bitkinin gövdesindeki halkalar neyi gösterir?', '["Yaşını","Boyunu","Türünü","Sağlığını yalnızca"]'::jsonb, 0, 'bilim'),
('Tohumun çimlenmesi için gerekli olmayan nedir?', '["Su","Işık","Uygun sıcaklık","Oksijen"]'::jsonb, 1, 'bilim'),
('Bitkilerde çiçeğin dişi organına ne denir?', '["Petal","Stamen","Pistil","Sepal"]'::jsonb, 2, 'bilim'),
('Bitkilerde erkek organa ne denir?', '["Kök","Pistil","Yaprak","Stamen"]'::jsonb, 3, 'bilim'),
('Meyve hangi yapıdan gelişir?', '["Yumurtalıktan","Yapraktan","Kökten","Gövdeden"]'::jsonb, 0, 'bilim'),
('Omurgalı hayvan grubu hangisidir?', '["Böcekler","Balıklar","Yumuşakçalar","Solucanlar"]'::jsonb, 1, 'bilim'),
('Omurgasız hayvan grubu hangisidir?', '["Memeliler","Kuşlar","Böcekler","Sürüngenler"]'::jsonb, 2, 'bilim'),
('Soğukkanlı hayvanların vücut sıcaklığı neye bağlıdır?', '["Renklerine","Beslenmeye","Uykuya","Ortam sıcaklığına"]'::jsonb, 3, 'bilim'),
('Başkalaşım geçiren hayvanlara örnek hangisidir?', '["Kurbağa","At","İnek","Kartal"]'::jsonb, 0, 'bilim'),
('İnsanda yağların sindirimi nerede tamamlanır?', '["Mide","İnce bağırsak","Ağız","Kalın bağırsak"]'::jsonb, 1, 'bilim'),
('Karbonhidratların sindirimi nerede başlar?', '["İnce bağırsak","Mide","Ağız","Yemek borusu"]'::jsonb, 2, 'bilim'),
('Proteinlerin sindirimi nerede başlar?', '["Kalın bağırsak","Ağız","İnce bağırsak","Mide"]'::jsonb, 3, 'bilim'),
('Vitaminlerin ortak özelliği nedir?', '["Az miktarda gerekli olmaları","Enerji vermeleri","Yapı taşı olmaları","Su olmaları"]'::jsonb, 0, 'bilim'),
('Yağda çözünen vitaminlerden biri hangisidir?', '["C vitamini","A vitamini","B1","B12"]'::jsonb, 1, 'bilim'),
('Suda çözünen vitaminlerden biri hangisidir?', '["D vitamini","A vitamini","C vitamini","K vitamini"]'::jsonb, 2, 'bilim'),
('Kemiklerde kalsiyum emilimini artıran vitamin hangisidir?', '["E vitamini","C vitamini","B6","D vitamini"]'::jsonb, 3, 'bilim'),
('Kanın pıhtılaşmasında rol oynayan vitamin hangisidir?', '["K vitamini","C vitamini","A vitamini","B2"]'::jsonb, 0, 'bilim'),
('İnsan vücudunda en uzun sinir hangisidir?', '["Optik sinir","Siyatik siniri","İşitme siniri","Koku siniri"]'::jsonb, 1, 'bilim'),
('Gözde renkli kısma ne denir?', '["Retina","Kornea","İris","Pupilla"]'::jsonb, 2, 'bilim'),
('Göz bebeğinin görevi nedir?', '["Odaklamak yalnızca","Renk üretmek","Görüntü oluşturmak","Işık miktarını ayarlamak"]'::jsonb, 3, 'bilim'),
('Deri kaç ana tabakadan oluşur?', '["Üst deri ve alt deri","Tek tabaka","Beş tabaka","On tabaka"]'::jsonb, 0, 'bilim'),
('Ter bezlerinin görevi nedir?', '["Besin üretmek","Vücut sıcaklığını düzenlemek","Hormon taşımak","Kan üretmek"]'::jsonb, 1, 'bilim'),
('Kılcal damarların görevi nedir?', '["Hava taşımak","Kan pompalamak","Madde alışverişi","Kemik yapmak"]'::jsonb, 2, 'bilim'),
('Lenf sisteminin görevlerinden biri nedir?', '["Sindirim","Kan pompalamak","Solunum","Bağışıklık ve sıvı dengesi"]'::jsonb, 3, 'bilim'),
('Hormonlar vücutta nasıl taşınır?', '["Kan yoluyla","Sinirlerle","Hava ile","Kaslarla"]'::jsonb, 0, 'bilim'),
('Tiroit bezinin salgısı neyi etkiler?', '["Görmeyi","Metabolizmayı","Duymayı","Kas gücünü yalnızca"]'::jsonb, 1, 'bilim'),
('Adrenalin hangi durumda salgılanır?', '["Açlık yalnızca","Uyku","Stres ve tehlike","Dinlenme"]'::jsonb, 2, 'bilim'),
('İnsanda embriyonun geliştiği organ hangisidir?', '["Karaciğer","Mide","Böbrek","Rahim"]'::jsonb, 3, 'bilim'),
('Ekosistemde üreticiler hangi canlılardır?', '["Yeşil bitkiler","Etçiller","Otçullar","Mantarlar"]'::jsonb, 0, 'bilim'),
('Karbon döngüsünde bitkiler ne yapar?', '["Karbondioksit üretir yalnızca","Karbondioksiti kullanır","Azot bağlar","Oksijen tüketir yalnızca"]'::jsonb, 1, 'bilim'),
('Su döngüsünde buharlaşma nerede en çoktur?', '["Buzullarda","Çöllerde","Okyanuslarda","Mağaralarda"]'::jsonb, 2, 'bilim'),
('Asit yağmurlarının başlıca nedeni nedir?', '["Su buharı","Oksijen","Azot gazı","Kükürt ve azot oksitleri"]'::jsonb, 3, 'bilim'),
('Küresel ısınmanın ana nedeni olarak gösterilen gaz hangisidir?', '["Karbondioksit","Azot","Helyum","Argon"]'::jsonb, 0, 'bilim'),
('Biyoçeşitliliğin azalması neye yol açar?', '["Verimin artmasına","Ekosistemin zayıflamasına","Yağışın artmasına","Toprağın zenginleşmesine"]'::jsonb, 1, 'bilim'),
('Bir kayacın ufalanarak toprağa dönüşmesine ne denir?', '["Taşınma","Birikme","Ayrışma","Erime"]'::jsonb, 2, 'bilim'),
('Yer altı sularının toplandığı geçirimli katmana ne denir?', '["Moren","Fay","Kraterr","Akifer"]'::jsonb, 3, 'bilim'),
('Bir gölün ötrofikasyonu neyle ilgilidir?', '["Aşırı besin ve yosunlaşma","Tuz azalması","Sıcaklık düşüşü","Derinlik artışı"]'::jsonb, 0, 'bilim'),
('Ozon tabakasını incelten maddelere ne denir?', '["Azot gazları yalnızca","Kloroflorokarbonlar","Su buharı","Oksijen"]'::jsonb, 1, 'bilim'),

-- ===================== TARİH (110) =====================

('Anadolu''da Çatalhöyük hangi döneme aittir?', '["Demir Çağı","Tunç Çağı","Neolitik","Roma"]'::jsonb, 2, 'tarih'),
('Göbeklitepe''nin önemi nedir?', '["İlk liman olması","İlk şehir olması","İlk saray olması","Bilinen en eski tapınak alanlarından olması"]'::jsonb, 3, 'tarih'),
('Hitit Devleti hangi bölgede kurulmuştur?', '["Orta Anadolu","Trakya","Ege kıyıları","Kafkasya"]'::jsonb, 0, 'tarih'),
('Urartuların en bilinen faaliyeti nedir?', '["Deniz ticareti","Su kanalları ve kaleler","Cam üretimi","Matbaa"]'::jsonb, 1, 'tarih'),
('Frigyalıların ünlü kral yolu neyi bağlardı?', '["Hindistan ile Çin''i","Mısır ile Roma''yı","Anadolu ile doğu ticaret yollarını","İspanya ile Fas''ı"]'::jsonb, 2, 'tarih'),
('İyonların bilime katkısı hangi alandadır?', '["Madencilik","Denizcilik yalnızca","Tarım","Felsefe ve doğa bilimleri"]'::jsonb, 3, 'tarih'),
('Antik Yunan''da olimpiyatlar hangi tanrı adına yapılırdı?', '["Zeus","Poseidon","Ares","Hermes"]'::jsonb, 0, 'tarih'),
('Sparta hangi özelliğiyle bilinirdi?', '["Ticaret","Askerî düzen","Felsefe","Denizcilik"]'::jsonb, 1, 'tarih'),
('Atina''da doğan yönetim biçimi hangisidir?', '["Teokrasi","Monarşi","Demokrasi","Feodalite"]'::jsonb, 2, 'tarih'),
('Roma''da halkın seçtiği temsilcilere ne denirdi?', '["Diktatör","Konsül yalnızca","Senatör","Tribün"]'::jsonb, 3, 'tarih'),
('Roma hukukunun modern hukuka etkisi nedir?', '["Temel kavramları sağlaması","Hiç etkisi yok","Yalnız ceza hukuku","Yalnız deniz hukuku"]'::jsonb, 0, 'tarih'),
('Roma''da su kemerleri ne için yapılmıştır?', '["Savunma","Şehre su taşımak","Tapınak","Pazar"]'::jsonb, 1, 'tarih'),
('Pompeii şehrini yok eden olay nedir?', '["Sel","Deprem","Vezüv Yanardağı patlaması","Savaş"]'::jsonb, 2, 'tarih'),
('İskender''in hocası kimdir?', '["Pisagor","Platon","Sokrates","Aristoteles"]'::jsonb, 3, 'tarih'),
('Helenistik dönem neyle başlar?', '["İskender''in fetihleriyle","Roma''nın kuruluşuyla","Mısır''ın yıkılışıyla","Pers''in doğuşuyla"]'::jsonb, 0, 'tarih'),
('İskenderiye Kütüphanesi hangi ülkede kurulmuştur?', '["Yunanistan","Mısır","İtalya","İran"]'::jsonb, 1, 'tarih'),
('Kağıdı icat eden uygarlık hangisidir?', '["Roma","Mısır","Çin","Hint"]'::jsonb, 2, 'tarih'),
('Barutu ilk kullanan uygarlık hangisidir?', '["Pers","Roma","Yunan","Çin"]'::jsonb, 3, 'tarih'),
('Pusulanın yaygınlaşması neyi kolaylaştırdı?', '["Denizciliği","Tarımı","Madenciliği","Dokumacılığı"]'::jsonb, 0, 'tarih'),
('Orta Çağ Avrupa''sındaki toprak düzenine ne denir?', '["Kapitalizm","Feodalite","Sosyalizm","Merkantilizm"]'::jsonb, 1, 'tarih'),
('Veba salgını Avrupa''da hangi yüzyılda büyük yıkım yaptı?', '["18. yüzyıl","10. yüzyıl","14. yüzyıl","20. yüzyıl"]'::jsonb, 2, 'tarih'),
('İstanbul''un fethinde surları aşmak için ne kullanıldı?', '["Kule yok","Mancınık yalnızca","Tünel yalnızca","Büyük toplar"]'::jsonb, 3, 'tarih'),
('Fatih Sultan Mehmet gemileri karadan nereye yürüttü?', '["Haliç''e","Marmara''ya","Karadeniz''e","Ege''ye"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ilk kez hangi padişah "Kayser-i Rum" unvanını kullandı?', '["Yavuz Selim","Fatih Sultan Mehmet","Kanuni","Orhan Bey"]'::jsonb, 1, 'tarih'),
('Yavuz Sultan Selim''in Mısır seferi sonucu ne oldu?', '["Kırım alındı","Balkanlar alındı","Halifelik Osmanlı''ya geçti","Viyana kuşatıldı"]'::jsonb, 2, 'tarih'),
('Kanuni döneminde Avrupa''da hangi ülkeye kapitülasyon verildi?', '["İspanya","İngiltere","Rusya","Fransa"]'::jsonb, 3, 'tarih'),
('Osmanlı''da ilk kez Viyana ne zaman kuşatıldı?', '["Kanuni döneminde","Fatih döneminde","Yavuz döneminde","II. Mahmut döneminde"]'::jsonb, 0, 'tarih'),
('Osmanlı''da duraklama döneminin başlangıcı olarak hangi antlaşma gösterilir?', '["Karlofça","Zitvatorok","Pasarofça","Küçük Kaynarca"]'::jsonb, 1, 'tarih'),
('Küçük Kaynarca Antlaşması hangi devletle imzalanmıştır?', '["Fransa","Avusturya","Rusya","İngiltere"]'::jsonb, 2, 'tarih'),
('Osmanlı''da Nizam-ı Cedid ordusunu kuran padişah kimdir?', '["Abdülaziz","II. Mahmut","Abdülmecit","III. Selim"]'::jsonb, 3, 'tarih'),
('Sened-i İttifak hangi konuda önemlidir?', '["Padişah yetkisinin ilk kez sınırlanması","Ordu kurulması","Vergi artışı","Toprak dağıtımı"]'::jsonb, 0, 'tarih'),
('Islahat Fermanı hangi konuyu düzenlemiştir?', '["Ordu düzeni","Gayrimüslimlerin hakları","Vergi affı","Toprak reformu"]'::jsonb, 1, 'tarih'),
('Osmanlı''da ilk demiryolu hangi amaçla yapıldı?', '["Turizm","Askerî yasak","Ticaret ve ulaşım","Madencilik yalnızca"]'::jsonb, 2, 'tarih'),
('Osmanlı''da Duyun-ı Umumiye ne için kuruldu?', '["Ordu","Eğitim","Sağlık","Dış borçların tahsili"]'::jsonb, 3, 'tarih'),
('Berlin Antlaşması hangi savaşın ardından imzalanmıştır?', '["93 Harbi","Kırım Savaşı","Trablusgarp","Balkan Savaşları"]'::jsonb, 0, 'tarih'),
('Birinci Dünya Savaşı''nda Osmanlı hangi blokta yer aldı?', '["İtilaf","İttifak","Tarafsız","Bağlantısız"]'::jsonb, 1, 'tarih'),
('Çanakkale''de "Conkbayırı" hangi cephede yer alır?', '["Kanal","Kafkas","Gelibolu","Irak"]'::jsonb, 2, 'tarih'),
('Kut''ül Amare zaferi hangi cephede kazanılmıştır?', '["Filistin","Gelibolu","Kafkas","Irak"]'::jsonb, 3, 'tarih'),
('Havza Genelgesi''nin amacı neydi?', '["Milli mücadeleyi örgütlemek","Vergi toplamak","Ordu dağıtmak","Ticaret açmak"]'::jsonb, 0, 'tarih'),
('Sivas Kongresi''nde alınan temel karar nedir?', '["Saltanatın kaldırılması","Milli cemiyetlerin birleştirilmesi","Cumhuriyetin ilanı","Halifeliğin kaldırılması"]'::jsonb, 1, 'tarih'),
('Türkiye Büyük Millet Meclisi''nin ilk açılış yeri neresidir?', '["İzmir","İstanbul","Ankara","Sivas"]'::jsonb, 2, 'tarih'),
('Birinci İnönü Muharebesi''nin siyasi sonucu nedir?', '["Ordunun dağılması","Savaşın bitmesi","Barış antlaşması","TBMM''nin itibarının artması"]'::jsonb, 3, 'tarih'),
('Sakarya Savaşı''nın önemi nedir?', '["Geri çekilmenin sona ermesi","İlk zafer olması","Son savaş olması","Deniz zaferi olması"]'::jsonb, 0, 'tarih'),
('Büyük Taarruz''un sonucu ne oldu?', '["Ankara''nın alınması","İzmir''in kurtarılması","Bursa''nın kaybı","Trakya''nın kaybı"]'::jsonb, 1, 'tarih'),
('Lozan''da çözülemeyen ve sonraya kalan konu hangisidir?', '["Vergi","Ordu düzeni","Hatay ve Musul gibi sorunlar","Eğitim"]'::jsonb, 2, 'tarih'),
('Cumhuriyetin ilanıyla devlet başkanlığı unvanı ne oldu?', '["Vali","Padişah","Sadrazam","Cumhurbaşkanı"]'::jsonb, 3, 'tarih'),
('Türkiye''de çok partili hayata geçiş denemesi ilk hangi partiyle olmuştur?', '["Terakkiperver Cumhuriyet Fırkası","Demokrat Parti","Halk Fırkası","Vatan Partisi"]'::jsonb, 0, 'tarih'),
('Şapka Kanunu hangi alanda yapılan bir düzenlemedir?', '["Eğitim","Kılık kıyafet","Hukuk","Ekonomi"]'::jsonb, 1, 'tarih'),
('Tekke ve zaviyelerin kapatılması hangi amaçla yapıldı?', '["Ordu kurmak","Vergi artırmak","Laik düzeni güçlendirmek","Ticaret açmak"]'::jsonb, 2, 'tarih'),
('Kabotaj Kanunu neyi düzenler?', '["Demir yollarını","Kara yollarını","Hava yollarını","Türk karasularında taşımacılığı"]'::jsonb, 3, 'tarih'),
('Sanayi Devrimi''nin ilk etkilediği sektör hangisidir?', '["Dokuma","Madencilik","Tarım","Bankacılık"]'::jsonb, 0, 'tarih'),
('Sanayi Devrimi''nin toplumsal sonuçlarından biri nedir?', '["Feodalitenin güçlenmesi","İşçi sınıfının doğuşu","Köylerin büyümesi","Ticaretin durması"]'::jsonb, 1, 'tarih'),
('Fransız İhtilali''nin yaydığı temel fikirlerden biri nedir?', '["Teokrasi","Feodalite","Milliyetçilik","Kölelik"]'::jsonb, 2, 'tarih'),
('Napolyon hangi ülkenin imparatoru olmuştur?', '["Avusturya","İspanya","İtalya","Fransa"]'::jsonb, 3, 'tarih'),
('Viyana Kongresi neyi amaçlamıştır?', '["Avrupa düzenini yeniden kurmak","Ticareti yasaklamak","Sömürge kurmak","Ordu dağıtmak"]'::jsonb, 0, 'tarih'),
('ABD''de köleliği kaldıran başkan kimdir?', '["George Washington","Abraham Lincoln","Thomas Jefferson","Franklin Roosevelt"]'::jsonb, 1, 'tarih'),
('Birinci Dünya Savaşı''nı başlatan olay nedir?', '["Berlin Duvarı","Pearl Harbor","Avusturya veliahtının suikastı","Waterloo"]'::jsonb, 2, 'tarih'),
('Normandiya Çıkarması hangi savaşta gerçekleşmiştir?', '["Vietnam Savaşı","Birinci Dünya Savaşı","Kore Savaşı","İkinci Dünya Savaşı"]'::jsonb, 3, 'tarih'),
('Marshall Yardımı neyi amaçlamıştır?', '["Avrupa''nın ekonomik onarımını","Ordu kurmayı","Sömürge açmayı","Vergi toplamayı"]'::jsonb, 0, 'tarih'),
('Varşova Paktı hangi bloğun askerî örgütüydü?', '["Batı Bloku","Doğu Bloku","Tarafsızlar","Bağlantısızlar"]'::jsonb, 1, 'tarih'),
('Berlin Duvarı hangi şehri ikiye bölmüştü?', '["Prag","Viyana","Berlin","Varşova"]'::jsonb, 2, 'tarih'),
('Küba Füze Krizi hangi iki ülke arasındaydı?', '["ABD ve Küba yalnızca","ABD ve Çin","SSCB ve Çin","ABD ve SSCB"]'::jsonb, 3, 'tarih'),
('İnsanlığın Ay''a ilk ayak basışı hangi yıldadır?', '["1969","1957","1975","1981"]'::jsonb, 0, 'tarih'),
('Sömürgeciliğin sona ermesine ne denir?', '["Kolonizasyon","Dekolonizasyon","Restorasyon","Reformasyon"]'::jsonb, 1, 'tarih'),
('Güney Afrika''da ırk ayrımı politikasının adı neydi?', '["Feodalite","Segregasyon yalnızca","Apartheid","Kolonyalizm"]'::jsonb, 2, 'tarih'),
('Hindistan''ın bağımsızlık hareketinin önderi kimdir?', '["Patel","Nehru yalnızca","Bose","Mahatma Gandhi"]'::jsonb, 3, 'tarih'),
('Çin''de imparatorluk dönemini sona erdiren olay nedir?', '["1911 Devrimi","Boxer İsyanı","Afyon Savaşı","Uzun Yürüyüş"]'::jsonb, 0, 'tarih'),
('Japonya''da modernleşmeyi başlatan dönem hangisidir?', '["Edo Dönemi","Meiji Restorasyonu","Heian Dönemi","Nara Dönemi"]'::jsonb, 1, 'tarih'),
('İpek Yolu''nun sona ermesinde etkili olan gelişme nedir?', '["Salgınlar yalnızca","Depremler","Deniz yollarının bulunması","İklim değişimi"]'::jsonb, 2, 'tarih'),
('Coğrafi Keşiflerin en önemli sonuçlarından biri nedir?', '["Nüfusun azalması","Feodalitenin güçlenmesi","Bilimin durması","Yeni ticaret yollarının açılması"]'::jsonb, 3, 'tarih'),
('Rönesans''ın Osmanlı''ya yansımasının sınırlı kalma nedenlerinden biri nedir?', '["Matbaanın geç yaygınlaşması","Nüfus azlığı","Toprak yetersizliği","Deniz eksikliği"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ilk resmî gazete hangisidir?', '["Tercüman-ı Ahval","Takvim-i Vekayi","Ceride-i Havadis","Basiret"]'::jsonb, 1, 'tarih'),
('Osmanlı''da açılan ilk modern tıp okulunun amacı neydi?', '["Denizcilik","Ticaret","Ordu için hekim yetiştirmek","Mimarlık"]'::jsonb, 2, 'tarih'),
('Selçuklularda medreselerin yaygınlaşmasını sağlayan vezir kimdir?', '["Melikşah","Tuğrul Bey","Alparslan","Nizamülmülk"]'::jsonb, 3, 'tarih'),
('Türk-İslam devletlerinde "ikta" ne demektir?', '["Toprak gelirinin tahsisi","Vergi affı","Askerî rütbe","Ticaret izni"]'::jsonb, 0, 'tarih'),
('Anadolu''da Ahilik teşkilatı hangi alanda örgütlenmiştir?', '["Ordu","Esnaf ve zanaat","Denizcilik","Tarım yalnızca"]'::jsonb, 1, 'tarih'),
('Malazgirt''ten sonra Anadolu''da kurulan ilk beyliklerden biri hangisidir?', '["Osmanoğulları","Karamanoğulları","Danişmentliler","Candaroğulları"]'::jsonb, 2, 'tarih'),
('Osmanlı Devleti''nin kuruluş yeri neresidir?', '["Edirne","Konya","Sivas","Söğüt ve Domaniç"]'::jsonb, 3, 'tarih'),
('Osmanlı''da "devşirme" sistemi hangi amaçla uygulanmıştır?', '["Devlet ve ordu kadrosu yetiştirmek","Vergi toplamak","Toprak dağıtmak","Ticaret yapmak"]'::jsonb, 0, 'tarih'),
('Osmanlı''da divanın başkanı kimdi (klasik dönem sonrası)?', '["Şeyhülislam","Sadrazam","Defterdar","Nişancı"]'::jsonb, 1, 'tarih'),
('Osmanlı''da fetva veren makam hangisidir?', '["Kazasker","Sadrazam","Şeyhülislam","Defterdar"]'::jsonb, 2, 'tarih'),
('Osmanlı maliyesinden sorumlu görevli kimdi?', '["Reisülküttap","Nişancı","Kazasker","Defterdar"]'::jsonb, 3, 'tarih'),
('Osmanlı''da tuğrayı çeken görevli kimdi?', '["Nişancı","Defterdar","Kazasker","Sadrazam"]'::jsonb, 0, 'tarih'),
('Osmanlı ordusunda hafif süvari birliklerine ne denirdi?', '["Yeniçeriler","Akıncılar","Cebeciler","Topçular"]'::jsonb, 1, 'tarih'),
('Osmanlı donanmasının başındaki komutana ne denirdi?', '["Beylerbeyi","Sadrazam","Kaptan-ı Derya","Sancakbeyi"]'::jsonb, 2, 'tarih'),
('Osmanlı''da eyaletlerin yöneticisine ne denirdi?', '["Defterdar","Kadı","Müftü","Beylerbeyi"]'::jsonb, 3, 'tarih'),
('Osmanlı''da sancakların yöneticisine ne denirdi?', '["Sancakbeyi","Beylerbeyi","Kadı","Vali"]'::jsonb, 0, 'tarih'),
('Osmanlı mimarisinde Süleymaniye Külliyesi hangi şehirdedir?', '["Edirne","İstanbul","Bursa","Konya"]'::jsonb, 1, 'tarih'),
('Topkapı Sarayı hangi dönemde yönetim merkeziydi?', '["Selçuklu","Bizans","Osmanlı","Roma"]'::jsonb, 2, 'tarih'),
('Dolmabahçe Sarayı hangi yüzyılda yapılmıştır?', '["20. yüzyıl","15. yüzyıl","17. yüzyıl","19. yüzyıl"]'::jsonb, 3, 'tarih'),
('Osmanlı''da lonca sisteminin işlevi neydi?', '["Üretim ve kaliteyi denetlemek","Vergi toplamak","Ordu kurmak","Cami yapmak"]'::jsonb, 0, 'tarih'),
('Anadolu''da Selçuklu döneminden kalma darüşşifa ne işlevi görürdü?', '["Okul","Hastane","Kervansaray","Hamam"]'::jsonb, 1, 'tarih'),
('Türklerin kullandığı ilk alfabelerden biri hangisidir?', '["Kiril","Latin","Göktürk","Arap"]'::jsonb, 2, 'tarih'),
('Uygurların matbaaya benzer tekniği neydi?', '["Mühür yok","Taş baskı yalnızca","Elle yazım","Blok baskı"]'::jsonb, 3, 'tarih'),
('İlk Türk devletlerinde "kurultay" neydi?', '["Devlet meclisi","Ordu birliği","Vergi türü","Din töreni"]'::jsonb, 0, 'tarih'),
('Türklerde "töre" ne anlama gelir?', '["Vergi","Yazısız hukuk kuralları","Ordu","Ticaret"]'::jsonb, 1, 'tarih'),
('Hunların ünlü hükümdarı kimdir?', '["Bilge Kağan","Bumin","Attila","Mete''nin oğlu yok"]'::jsonb, 2, 'tarih'),
('Mete Han hangi devletin hükümdarıdır?', '["Avar","Göktürk","Uygur","Asya Hun"]'::jsonb, 3, 'tarih'),
('Göktürk Devleti''nin kurucusu kimdir?', '["Bumin Kağan","Bilge Kağan","Kültigin","İstemi Yabgu"]'::jsonb, 0, 'tarih'),
('Türk adının geçtiği ilk yazılı Türkçe belgeler hangileridir?', '["Divanü Lügat","Orhun Yazıtları","Kutadgu Bilig","Dede Korkut"]'::jsonb, 1, 'tarih'),
('Talas Savaşı hangi iki güç arasında olmuştur?', '["Roma ve Kartaca","Türkler ve Persler","Araplar ve Çinliler","Moğollar ve Ruslar"]'::jsonb, 2, 'tarih'),
('Timur İmparatorluğu''nun başkenti neresiydi?', '["Kabil","Buhara","Herat","Semerkant"]'::jsonb, 3, 'tarih')

on conflict (soru) do nothing;

-- ===================== KARIŞTIRMA =====================
-- Doğru cevap hep aynı şıkta olmasın: SADECE bu partide eklenen soruların
-- şıkları karıştırılır. `created_at >= transaction_timestamp()` koşulu
-- ZORUNLUDUR; onsuz tüm havuzun şıkları karışır ve o an oynanan maçlarda
-- şık indeksleri kayar.
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
