-- Soru havuzu genişletme: cografya +74
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Konstantinopolis hangi kentin eski adıdır?', '["İstanbul","İzmir","Antalya","Selanik"]'::jsonb, 0, 'cografya'),
('Smyrna hangi kentin antik adıdır?', '["Bursa","İzmir","Antalya","Adana"]'::jsonb, 1, 'cografya'),
('Ankyra hangi kentin antik adıdır?', '["Konya","Kayseri","Ankara","Sivas"]'::jsonb, 2, 'cografya'),
('Ikonion hangi kentin antik adıdır?', '["Ankara","Niğde","Aksaray","Konya"]'::jsonb, 3, 'cografya'),
('Caesarea hangi kentin antik adlarındandır?', '["Kayseri","Kütahya","Manisa","Denizli"]'::jsonb, 0, 'cografya'),
('Prusa hangi kentin antik adıdır?', '["Balıkesir","Bursa","Bilecik","Yalova"]'::jsonb, 1, 'cografya'),
('Nicaea (İznik) hangi ilimizin ilçesidir?', '["Sakarya","Kocaeli","Bursa","Bilecik"]'::jsonb, 2, 'cografya'),
('Antiochia hangi kentin antik adıdır?', '["Adana","Mersin","Osmaniye","Antakya"]'::jsonb, 3, 'cografya'),
('Edessa hangi kentin antik adıdır?', '["Şanlıurfa","Mardin","Diyarbakır","Gaziantep"]'::jsonb, 0, 'cografya'),
('Amida hangi kentin antik adıdır?', '["Batman","Diyarbakır","Siirt","Bitlis"]'::jsonb, 1, 'cografya'),
('Trapezus hangi kentin antik adıdır?', '["Rize","Giresun","Trabzon","Ordu"]'::jsonb, 2, 'cografya'),
('Sinope hangi kentin antik adıdır?', '["Samsun","Bartın","Zonguldak","Sinop"]'::jsonb, 3, 'cografya'),
('Halikarnassos hangi ilçemizin antik adıdır?', '["Bodrum","Marmaris","Datça","Fethiye"]'::jsonb, 0, 'cografya'),
('Telmessos hangi ilçemizin antik adıdır?', '["Kaş","Fethiye","Kalkan","Marmaris"]'::jsonb, 1, 'cografya'),
('Side antik kenti hangi ilimizdedir?', '["Mersin","Muğla","Antalya","Burdur"]'::jsonb, 2, 'cografya'),
('Patara antik kenti hangi ilimizdedir?', '["Muğla","Denizli","Isparta","Antalya"]'::jsonb, 3, 'cografya'),
('Sagalassos antik kenti hangi ilimizdedir?', '["Burdur","Isparta","Antalya","Denizli"]'::jsonb, 0, 'cografya'),
('Laodikeia antik kenti hangi ilimizdedir?', '["Aydın","Denizli","Muğla","Manisa"]'::jsonb, 1, 'cografya'),
('Priene ve Milet antik kentleri hangi ilimizdedir?', '["İzmir","Muğla","Aydın","Denizli"]'::jsonb, 2, 'cografya'),
('Sardes antik kenti hangi ilimizdedir?', '["İzmir","Uşak","Kütahya","Manisa"]'::jsonb, 3, 'cografya'),
('Alacahöyük hangi ilimizde yer alır?', '["Çorum","Yozgat","Amasya","Tokat"]'::jsonb, 0, 'cografya'),
('Arslantepe höyüğü hangi ilimizdedir?', '["Elazığ","Malatya","Adıyaman","Sivas"]'::jsonb, 1, 'cografya'),
('Aizanoi antik kenti hangi ilimizdedir?', '["Uşak","Afyonkarahisar","Kütahya","Eskişehir"]'::jsonb, 2, 'cografya'),
('Ahlat mezar taşları hangi ilimizdedir?', '["Van","Muş","Ağrı","Bitlis"]'::jsonb, 3, 'cografya'),
('Harput kalesi hangi ilimizdedir?', '["Elazığ","Malatya","Tunceli","Bingöl"]'::jsonb, 0, 'cografya'),
('Sümbüllü ve Akdamar adaları hangi gölde yer alır?', '["Beyşehir Gölü","Van Gölü","Eğirdir Gölü","Tuz Gölü"]'::jsonb, 1, 'cografya'),
('Nemrut Kalderası hangi ilimizde yer alır?', '["Adıyaman","Van","Bitlis","Muş"]'::jsonb, 2, 'cografya'),
('Ağrı Dağı''nın yüksekliği yaklaşık ne kadardır?', '["3000 metre","4000 metre","6500 metre","5100 metre"]'::jsonb, 3, 'cografya'),
('Everest''in yüksekliği yaklaşık ne kadardır?', '["8850 metre","6000 metre","7000 metre","10000 metre"]'::jsonb, 0, 'cografya'),
('Kilimanjaro''nun yüksekliği yaklaşık ne kadardır?', '["3000 metre","5900 metre","8000 metre","2000 metre"]'::jsonb, 1, 'cografya'),
('Mont Blanc''ın yüksekliği yaklaşık ne kadardır?', '["2000 metre","6000 metre","4800 metre","8000 metre"]'::jsonb, 2, 'cografya'),
('Nil Nehri''nin uzunluğu yaklaşık ne kadardır?', '["2000 kilometre","4000 kilometre","10000 kilometre","6600 kilometre"]'::jsonb, 3, 'cografya'),
('Amazon Nehri''nin en belirgin özelliği nedir?', '["Debisinin dünyada en yüksek olması","En kısa olması","Tuzlu olması","Donması"]'::jsonb, 0, 'cografya'),
('Kızılırmak''ın uzunluğu yaklaşık ne kadardır?', '["300 kilometre","1350 kilometre","700 kilometre","2500 kilometre"]'::jsonb, 1, 'cografya'),
('Van Gölü''nün yüzölçümü yaklaşık ne kadardır?', '["100 kilometrekare","800 kilometrekare","3700 kilometrekare","20000 kilometrekare"]'::jsonb, 2, 'cografya'),
('Türkiye''nin yüzölçümü yaklaşık ne kadardır?', '["300 bin kilometrekare","1,5 milyon kilometrekare","100 bin kilometrekare","780 bin kilometrekare"]'::jsonb, 3, 'cografya'),
('Türkiye''nin ortalama yükseltisi yaklaşık ne kadardır?', '["1130 metre","300 metre","2500 metre","50 metre"]'::jsonb, 0, 'cografya'),
('Türkiye''nin ortalama yükseltisinin fazla olmasının sonucu nedir?', '["Yağışın artması","Sıcaklığın düşük olması","Nemin artması","Denizelliğin artması"]'::jsonb, 1, 'cografya'),
('Türkiye''nin matematik konumunda enlem aralığı hangisidir?', '["26-45 kuzey","0-30 kuzey","36-42 kuzey","45-60 kuzey"]'::jsonb, 2, 'cografya'),
('Türkiye''nin boylam aralığı hangisidir?', '["36-42 doğu","0-20 doğu","45-60 doğu","26-45 doğu"]'::jsonb, 3, 'cografya'),
('Türkiye''nin doğusu ile batısı arasındaki yerel saat farkı ne kadardır?', '["76 dakika","24 dakika","120 dakika","15 dakika"]'::jsonb, 0, 'cografya'),
('Türkiye''nin kuzeyi ile güneyi arasındaki iklim farkının nedeni nedir?', '["Boylam farkı","Enlem farkı ve dağ sıraları","Yerel saat farkı","Nüfus farkı"]'::jsonb, 1, 'cografya'),
('Yer gözlem uydularının coğrafyaya katkısı nedir?', '["Hava üretmek","Su üretmek","Arazi değişimini izlemek","Enerji üretmek"]'::jsonb, 2, 'cografya'),
('Uydu görüntülerinde ''çözünürlük'' neyi belirler?', '["Renk sayısını","Görüntü boyutunu","Uydu hızını","Ayırt edilebilen en küçük ayrıntıyı"]'::jsonb, 3, 'cografya'),
('Hava fotoğraflarının haritacılıkta kullanımı nasıl adlandırılır?', '["Fotogrametri","Kartografya","Jeodezi","Hidrografi"]'::jsonb, 0, 'cografya'),
('Jeodezi bilimi neyle ilgilenir?', '["Bitki örtüsüyle","Yerin şekli ve ölçümüyle","Nüfusla","İklimle"]'::jsonb, 1, 'cografya'),
('Hidrografi neyi inceler?', '["Hava olaylarını","Kayaçları","Su kütlelerinin ölçüm ve haritalanmasını","Nüfusu"]'::jsonb, 2, 'cografya'),
('Topografya ile jeomorfoloji arasındaki fark nedir?', '["Topografyanın süreç incelemesi","İkisinin aynı olması","Jeomorfolojinin ölçüm yapması","Jeomorfolojinin süreçleri incelemesi"]'::jsonb, 3, 'cografya'),
('Klimatoloji bilimi neyi inceler?', '["İklimi ve uzun dönem değişimini","Günlük havayı","Kayaçları","Nüfusu"]'::jsonb, 0, 'cografya'),
('Meteoroloji ile klimatoloji arasındaki fark nedir?', '["Klimatolojinin günlük olması","Meteorolojinin kısa dönemle ilgilenmesi","İkisinin aynı olması","Meteorolojinin uzun dönem olması"]'::jsonb, 1, 'cografya'),
('Pedoloji bilimi neyi inceler?', '["Suyu","Havayı","Toprağı","Kayaçları"]'::jsonb, 2, 'cografya'),
('Speleoloji bilimi neyi inceler?', '["Buzulları","Çölleri","Deltaları","Mağaraları"]'::jsonb, 3, 'cografya'),
('Vulkanoloji bilimi neyi inceler?', '["Volkanları","Buzulları","Nehirleri","Toprağı"]'::jsonb, 0, 'cografya'),
('Sismoloji bilimi neyi inceler?', '["Volkanları","Depremleri","Buzulları","Rüzgârları"]'::jsonb, 1, 'cografya'),
('Oşinografi bilimi neyi inceler?', '["Dağları","Çölleri","Okyanusları","Ormanları"]'::jsonb, 2, 'cografya'),
('Glasiyoloji bilimi neyi inceler?', '["Mağaraları","Volkanları","Toprağı","Buzulları"]'::jsonb, 3, 'cografya'),
('Demografi bilimi neyi inceler?', '["Nüfus yapısını ve hareketlerini","Toprağı","İklimi","Kayaçları"]'::jsonb, 0, 'cografya'),
('Kartografya bilimi neyle ilgilenir?', '["Nüfus sayımıyla","Harita yapımı ve tasarımıyla","Toprak analiziyle","Deprem ölçümüyle"]'::jsonb, 1, 'cografya'),
('Toponimi neyi inceler?', '["Kayaç adlarını","Bitki adlarını","Yer adlarını","Hayvan adlarını"]'::jsonb, 2, 'cografya'),
('Bir bölgede yer adlarının kökeni neyi gösterebilir?', '["İklim türünü","Toprak yapısını","Yükseltiyi","Geçmiş yerleşim ve kültürleri"]'::jsonb, 3, 'cografya'),
('Uzaktan algılamada ''bant'' kavramı neyi ifade eder?', '["Belirli dalga boyu aralığını","Görüntü boyutunu","Uydu adını","Yörünge yüksekliğini"]'::jsonb, 0, 'cografya'),
('Kızılötesi bantların uzaktan algılamadaki kullanımı nedir?', '["Ses ölçmek","Bitki sağlığını izlemek","Nüfus saymak","Rüzgâr ölçmek"]'::jsonb, 1, 'cografya'),
('Radar uydularının avantajı nedir?', '["Renkli görüntü vermesi","Ucuz olması","Bulutlu havada da görüntü alması","Küçük olması"]'::jsonb, 2, 'cografya'),
('Sayısal yükseklik modeli neyi sunar?', '["Nüfus verisini","İklim verisini","Toprak verisini","Arazinin üç boyutlu yükseklik verisini"]'::jsonb, 3, 'cografya'),
('Coğrafi veride ''katman'' kavramı neyi ifade eder?', '["Aynı tür verinin ayrı düzlemde tutulması","Haritanın kalınlığını","Kâğıt sayısını","Ölçeği"]'::jsonb, 0, 'cografya'),
('Konumsal analiz neyi sağlar?', '["Metin düzenlemeyi","Mekânsal ilişkileri ortaya koymayı","Ses işlemeyi","Renk basmayı"]'::jsonb, 1, 'cografya'),
('Yer seçimi analizinde CBS nasıl kullanılır?', '["Rastgele seçerek","Anket yaparak","Ölçütleri katman katman değerlendirerek","Tahmin ederek"]'::jsonb, 2, 'cografya'),
('Isı haritası (heat map) neyi gösterir?', '["Sıcaklığı yalnızca","Yükseltiyi","Sınırları","Yoğunluk dağılımını"]'::jsonb, 3, 'cografya'),
('Nokta dağılım haritası neyi gösterir?', '["Olayların konumsal dağılımını","Yükseltiyi","Sınırları","Ölçeği"]'::jsonb, 0, 'cografya'),
('Koroplet harita neyi gösterir?', '["Noktaları","Alanlara göre değişen değeri renklerle","Çizgileri","Yükseltiyi"]'::jsonb, 1, 'cografya'),
('Akış haritası neyi gösterir?', '["Yükseltiyi","Toprağı","Hareket ve yönelimleri","İklimi"]'::jsonb, 2, 'cografya'),
('Kartogram nedir?', '["Ölçeksiz kroki","Fiziki harita","Siyasi harita","Alanın veriye göre bozulduğu harita"]'::jsonb, 3, 'cografya'),
('Bir haritada ''genelleştirme'' neden yapılır?', '["Ölçeğe uygun sadeleştirme için","Renk artırmak için","Başlık koymak için","Kâğıt seçmek için"]'::jsonb, 0, 'cografya'),
('Harita okumada ilk bakılması gereken öğe nedir?', '["Kâğıt türü","Başlık, ölçek ve lejant","Basım yeri","Yazı tipi"]'::jsonb, 1, 'cografya')
on conflict (soru) do nothing;
