-- Soru havuzu genişletme: cografya +157
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Türkiye''nin en çok komşusu olan ili hangisidir?', '["Sivas","Konya","Ankara","Kayseri"]'::jsonb, 0, 'cografya'),
('Iğdır ovası hangi özelliğiyle bilinir?', '["Çay tarımı","Mikroklima sayesinde pamuk yetişmesi","Muz üretimi","Fındık bahçeleri"]'::jsonb, 1, 'cografya'),
('Erzurum-Kars platosu hangi hayvancılık türüyle öne çıkar?', '["Deve yetiştiriciliği","Balıkçılık","Büyükbaş hayvancılık","İpekböcekçiliği"]'::jsonb, 2, 'cografya'),
('Türkiye''de kış turizmi merkezi olan Palandöken hangi ildedir?', '["Kars","Ağrı","Bayburt","Erzurum"]'::jsonb, 3, 'cografya'),
('Kartalkaya kayak merkezi hangi ilimizdedir?', '["Bolu","Düzce","Zonguldak","Karabük"]'::jsonb, 0, 'cografya'),
('Uzungöl hangi ilimizde bulunur?', '["Rize","Trabzon","Artvin","Gümüşhane"]'::jsonb, 1, 'cografya'),
('Ölüdeniz hangi ilçemizde yer alır?', '["Marmaris","Bodrum","Fethiye","Kaş"]'::jsonb, 2, 'cografya'),
('Kaputaş Plajı hangi ilimizdedir?', '["Muğla","Mersin","İzmir","Antalya"]'::jsonb, 3, 'cografya'),
('Kuş Cenneti Milli Parkı hangi ilimizdedir?', '["Balıkesir","Bursa","Çanakkale","Manisa"]'::jsonb, 0, 'cografya'),
('Sultan Sazlığı hangi ilimizde bulunur?', '["Niğde","Kayseri","Konya","Aksaray"]'::jsonb, 1, 'cografya'),
('Munzur Vadisi Milli Parkı hangi ilimizdedir?', '["Erzincan","Bingöl","Tunceli","Elazığ"]'::jsonb, 2, 'cografya'),
('Köprülü Kanyon hangi ilimizde yer alır?', '["Mersin","Isparta","Burdur","Antalya"]'::jsonb, 3, 'cografya'),
('Ihlara Vadisi hangi ilimizdedir?', '["Aksaray","Nevşehir","Niğde","Konya"]'::jsonb, 0, 'cografya'),
('Sivas''taki Balıklı Kaplıca hangi özelliğiyle bilinir?', '["Tuz mağarasıyla","Doktor balıklarıyla tedavi","Buz gölüyle","Çamur banyosuyla"]'::jsonb, 1, 'cografya'),
('Manyas Gölü hangi özelliğiyle korunmaktadır?', '["Tuzluluğu","Derinliği","Kuş göç yolu üzerinde olması","Volkanik olması"]'::jsonb, 2, 'cografya'),
('Eğirdir Gölü hangi ilimizdedir?', '["Burdur","Konya","Antalya","Isparta"]'::jsonb, 3, 'cografya'),
('Marmara Denizi''nin en büyük adası hangisidir?', '["Marmara Adası","Avşa","Ekinlik","Büyükada"]'::jsonb, 0, 'cografya'),
('Ege kıyılarının girintili çıkıntılı olmasının nedeni nedir?', '["Dağların kıyıya paralel olması","Dağların denize dik uzanması","Buzul aşındırması","Volkanik patlamalar"]'::jsonb, 1, 'cografya'),
('Karadeniz kıyılarında liman sayısının az olmasının nedeni nedir?', '["Suların sığ olması","Kıyının buzla kaplı olması","Dağların kıyıya paralel uzanması","Gelgitin şiddeti"]'::jsonb, 2, 'cografya'),
('Türkiye''de gelgit olayının etkisinin az olmasının nedeni nedir?', '["Suların soğukluğu","Kıyıların dik olması","Rüzgârların zayıflığı","Denizlerin iç deniz olması"]'::jsonb, 3, 'cografya'),
('Karadeniz''in tuzluluk oranının Akdeniz''den düşük olmasının nedeni nedir?', '["Bol akarsuyla beslenmesi","Daha sıcak olması","Daha derin olması","Daha küçük olması"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en önemli konteyner limanlarından Ambarlı hangi ildedir?', '["Kocaeli","İstanbul","Tekirdağ","Yalova"]'::jsonb, 1, 'cografya'),
('Türkiye''nin doğal gaz ithalatında öne çıkan ulaşım biçimi nedir?', '["Demiryolu","Karayolu","Boru hattı","Hava yolu"]'::jsonb, 2, 'cografya'),
('Bakü-Tiflis-Ceyhan hattı neyi taşır?', '["Doğal gaz","Su","Elektrik","Ham petrol"]'::jsonb, 3, 'cografya'),
('Hidroelektrik santraller enerjiyi neyden üretir?', '["Akan suyun gücünden","Rüzgârdan","Kömürden","Güneşten"]'::jsonb, 0, 'cografya'),
('Rüzgâr enerjisi Türkiye''de en çok hangi bölgede üretilir?', '["Doğu Anadolu","Ege","Güneydoğu Anadolu","Karadeniz"]'::jsonb, 1, 'cografya'),
('Jeotermal enerji üretiminde öne çıkan ilimiz hangisidir?', '["Rize","Kars","Denizli","Edirne"]'::jsonb, 2, 'cografya'),
('Yenilenebilir enerji kaynağı olmayan hangisidir?', '["Rüzgâr","Güneş","Jeotermal","Kömür"]'::jsonb, 3, 'cografya'),
('Fosil yakıtların yakılması hangi gazın artmasına yol açar?', '["Karbondioksit","Oksijen","Helyum","Argon"]'::jsonb, 0, 'cografya'),
('Çölleşmenin başlıca insan kaynaklı nedeni nedir?', '["Baraj yapımı","Aşırı otlatma ve ormansızlaşma","Şehirleşme","Ulaşım"]'::jsonb, 1, 'cografya'),
('Toprağın en verimli üst katmanına ne ad verilir?', '["Ana kaya","Alt toprak","Humus","Kum katmanı"]'::jsonb, 2, 'cografya'),
('Nadas uygulaması hangi amaçla yapılır?', '["Ürünü hızlandırmak","Zararlıyı çoğaltmak","Sulamayı artırmak","Toprağın nem ve verim kazanması"]'::jsonb, 3, 'cografya'),
('Terra rossa toprağı hangi iklim bölgesinde oluşur?', '["Akdeniz","Tundra","Ekvatoral","Çöl"]'::jsonb, 0, 'cografya'),
('Alüvyal toprak nerede birikir?', '["Dağ zirvelerinde","Akarsu taşkın ovalarında","Çöl ortasında","Buzul üstünde"]'::jsonb, 1, 'cografya'),
('Türkiye''de tarımın makineleşmesi hangi sonucu doğurmuştur?', '["Nüfusun azalması","Ekili alanın küçülmesi","Kırdan kente göçün artması","Verimin düşmesi"]'::jsonb, 2, 'cografya'),
('Seracılık Türkiye''de en çok hangi ilde yapılır?', '["Erzurum","Sivas","Ordu","Antalya"]'::jsonb, 3, 'cografya'),
('Türkiye''de en fazla üretilen tahıl hangisidir?', '["Buğday","Pirinç","Yulaf","Çavdar"]'::jsonb, 0, 'cografya'),
('Çeltik (pirinç) tarımı hangi ilimizde yoğundur?', '["Ağrı","Edirne","Erzurum","Kars"]'::jsonb, 1, 'cografya'),
('İncir üretiminde öne çıkan ilimiz hangisidir?', '["Rize","Bolu","Aydın","Kars"]'::jsonb, 2, 'cografya'),
('Kayısı üretiminde öne çıkan ilimiz hangisidir?', '["Trabzon","Muğla","Edirne","Malatya"]'::jsonb, 3, 'cografya'),
('Üzüm üretiminde öne çıkan ilimiz hangisidir?', '["Manisa","Rize","Artvin","Ardahan"]'::jsonb, 0, 'cografya'),
('Türkiye''de arıcılığın en yaygın olduğu il hangisidir?', '["Konya","Ordu","Şanlıurfa","Yozgat"]'::jsonb, 1, 'cografya'),
('Angora (tiftik) keçisi hangi ilimizle özdeşleşmiştir?', '["İzmir","Antalya","Ankara","Samsun"]'::jsonb, 2, 'cografya'),
('Hamsi avcılığı hangi denizimizde yoğundur?', '["Akdeniz","Ege","Marmara","Karadeniz"]'::jsonb, 3, 'cografya'),
('Sünger avcılığı Türkiye''de hangi kıyıda yapılır?', '["Ege ve Akdeniz","Karadeniz","Marmara","Yalnız Karadeniz"]'::jsonb, 0, 'cografya'),
('Türkiye''nin ilk demir çelik fabrikası hangi ilde kurulmuştur?', '["İskenderun","Karabük","Kırıkkale","Ereğli"]'::jsonb, 1, 'cografya'),
('Petrol rafinerisi bulunan Batman hangi bölgemizdedir?', '["Doğu Anadolu","İç Anadolu","Güneydoğu Anadolu","Akdeniz"]'::jsonb, 2, 'cografya'),
('Türkiye''de otomotiv sanayisinin yoğunlaştığı bölge hangisidir?', '["Doğu Anadolu","Karadeniz","Güneydoğu Anadolu","Marmara"]'::jsonb, 3, 'cografya'),
('Türkiye''de sanayinin en gelişmiş olduğu il hangisidir?', '["İstanbul","Van","Muş","Ardahan"]'::jsonb, 0, 'cografya'),
('Organize sanayi bölgelerinin amacı nedir?', '["Tarımı artırmak","Sanayiyi planlı bir alanda toplamak","Turizmi geliştirmek","Ormanı korumak"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en yoğun kullanılan ulaşım türü hangisidir?', '["Demiryolu","Denizyolu","Karayolu","Havayolu"]'::jsonb, 2, 'cografya'),
('Marmaray projesi neyi sağlar?', '["Karayolu köprüsü","Havalimanı bağlantısı","Deniz otobüsü hattı","Boğaz altından raylı geçiş"]'::jsonb, 3, 'cografya'),
('Türkiye''nin turizm gelirlerinde ilk sırada gelen il hangisidir?', '["Antalya","Ardahan","Bayburt","Hakkari"]'::jsonb, 0, 'cografya'),
('Kültür turizmi hangi kaynağa dayanır?', '["Kayak pistleri","Tarihî ve arkeolojik miras","Termal sular","Deniz kumu"]'::jsonb, 1, 'cografya'),
('Termal turizm hangi doğal kaynağa dayanır?', '["Buzullar","Kumullar","Sıcak su kaynakları","Mağaralar"]'::jsonb, 2, 'cografya'),
('Ekoturizm hangi ilkeyi esas alır?', '["Kitlesel tatili","Sanayileşmeyi","Kentleşmeyi","Doğaya zarar vermeden gezmeyi"]'::jsonb, 3, 'cografya'),
('Bir ülkenin dışarıya sattığı mallara ne denir?', '["İhracat","İthalat","Transit ticaret","Gümrük"]'::jsonb, 0, 'cografya'),
('Dış ticaret açığı ne anlama gelir?', '["İhracatın fazla olması","İthalatın ihracattan fazla olması","Ticaretin durması","Vergilerin artması"]'::jsonb, 1, 'cografya'),
('Serbest bölgelerin temel amacı nedir?', '["Tarımı desteklemek","Nüfusu artırmak","Dış ticareti kolaylaştırmak","Ormanı korumak"]'::jsonb, 2, 'cografya'),
('Bir bölgenin ekonomik kalkınmasında en belirleyici doğal etken nedir?', '["Nüfusun genç olması","İklimin sıcak olması","Yüzölçümünün büyüklüğü","Kaynak zenginliği ve ulaşım"]'::jsonb, 3, 'cografya'),
('Kentlerin nüfus çekmesinin başlıca nedeni nedir?', '["İş ve eğitim olanakları","Temiz hava","Ucuz arazi","Sessizlik"]'::jsonb, 0, 'cografya'),
('Bir ülkede nüfus piramidinin geniş tabanlı olması neyi gösterir?', '["Yaşlı nüfusun fazlalığını","Doğum oranının yüksekliğini","Göç almadığını","Ölüm oranının sıfır olduğunu"]'::jsonb, 1, 'cografya'),
('Aktif nüfus hangi yaş grubunu kapsar?', '["Yalnız çocukları","Yalnız yaşlıları","Çalışma çağındakileri","Tüm nüfusu"]'::jsonb, 2, 'cografya'),
('Nüfus artış hızının negatif olması ne demektir?', '["Nüfusun sabit kaldığı","Göç alındığı","Doğumun arttığı","Nüfusun azaldığı"]'::jsonb, 3, 'cografya'),
('Beyin göçü hangi nüfus grubunun göçüdür?', '["Nitelikli iş gücünün","Emeklilerin","Çocukların","Mevsimlik işçilerin"]'::jsonb, 0, 'cografya'),
('Mülteci hareketleri hangi göç türüne girer?', '["Mevsimlik göç","Zorunlu göç","İsteğe bağlı göç","Beyin göçü"]'::jsonb, 1, 'cografya'),
('Rusya''nın Avrupa ile Asya arasındaki doğal sınırı hangisidir?', '["Kafkas Dağları","Karpatlar","Ural Dağları","Altay Dağları"]'::jsonb, 2, 'cografya'),
('Kafkas Dağları hangi iki denizin arasındadır?', '["Baltık ve Kuzey","Ege ve Akdeniz","Kızıldeniz ve Akdeniz","Karadeniz ve Hazar"]'::jsonb, 3, 'cografya'),
('Pireneler hangi iki ülkeyi ayırır?', '["Fransa ve İspanya","İtalya ve Avusturya","Almanya ve Polonya","Norveç ve İsveç"]'::jsonb, 0, 'cografya'),
('Karpat Dağları ağırlıklı olarak hangi ülkededir?', '["Yunanistan","Romanya","Portekiz","Finlandiya"]'::jsonb, 1, 'cografya'),
('Balkanlar''da yer almayan ülke hangisidir?', '["Sırbistan","Bulgaristan","Avusturya","Arnavutluk"]'::jsonb, 2, 'cografya'),
('Baltık ülkeleri hangileridir?', '["Polonya, Çekya, Slovakya","Danimarka, Norveç, İsveç","Belçika, Hollanda, Lüksemburg","Estonya, Letonya, Litvanya"]'::jsonb, 3, 'cografya'),
('Benelüks ülkeleri hangileridir?', '["Belçika, Hollanda, Lüksemburg","Bulgaristan, Sırbistan, Bosna","Estonya, Letonya, Litvanya","İsviçre, Avusturya, Slovenya"]'::jsonb, 0, 'cografya'),
('Sicilya Adası hangi ülkeye aittir?', '["Yunanistan","İtalya","İspanya","Fransa"]'::jsonb, 1, 'cografya'),
('Girit Adası hangi ülkeye aittir?', '["İtalya","Türkiye","Yunanistan","Kıbrıs"]'::jsonb, 2, 'cografya'),
('Korsika Adası hangi ülkeye aittir?', '["İtalya","İspanya","Monako","Fransa"]'::jsonb, 3, 'cografya'),
('Sardunya Adası hangi ülkeye aittir?', '["İtalya","Fransa","İspanya","Tunus"]'::jsonb, 0, 'cografya'),
('Balear Adaları hangi ülkeye aittir?', '["Fransa","İspanya","İtalya","Portekiz"]'::jsonb, 1, 'cografya'),
('Kanarya Adaları hangi ülkeye bağlıdır?', '["Fas","Portekiz","İspanya","Fransa"]'::jsonb, 2, 'cografya'),
('Azor Adaları hangi ülkeye bağlıdır?', '["İspanya","Fas","İngiltere","Portekiz"]'::jsonb, 3, 'cografya'),
('Hawaii hangi ülkenin eyaletidir?', '["ABD","Japonya","Avustralya","Meksika"]'::jsonb, 0, 'cografya'),
('Tazmanya hangi ülkeye aittir?', '["Yeni Zelanda","Avustralya","Endonezya","Papua Yeni Gine"]'::jsonb, 1, 'cografya'),
('Falkland Adaları hangi okyanustadır?', '["Pasifik","Hint","Atlas Okyanusu","Arktik"]'::jsonb, 2, 'cografya'),
('Galapagos Adaları hangi ülkeye aittir?', '["Peru","Şili","Kolombiya","Ekvador"]'::jsonb, 3, 'cografya'),
('Sri Lanka hangi ülkenin güneyinde yer alır?', '["Hindistan","Endonezya","Bangladeş","Myanmar"]'::jsonb, 0, 'cografya'),
('Maldivler hangi okyanustadır?', '["Pasifik","Hint Okyanusu","Atlas","Arktik"]'::jsonb, 1, 'cografya'),
('Küba hangi denizde yer alır?', '["Akdeniz","Baltık Denizi","Karayip Denizi","Mercan Denizi"]'::jsonb, 2, 'cografya'),
('Meksika Körfezi hangi okyanusa açılır?', '["Pasifik","Hint","Arktik","Atlas Okyanusu"]'::jsonb, 3, 'cografya'),
('Aden Körfezi hangi denize açılır?', '["Kızıldeniz","Akdeniz","Karadeniz","Baltık Denizi"]'::jsonb, 0, 'cografya'),
('Basra Körfezi hangi okyanusa bağlanır?', '["Atlas","Hint Okyanusu","Pasifik","Arktik"]'::jsonb, 1, 'cografya'),
('Baltık Denizi hangi kıtanın kuzeyindedir?', '["Asya","Afrika","Avrupa","Kuzey Amerika"]'::jsonb, 2, 'cografya'),
('Adriyatik Denizi hangi iki ülke arasındadır?', '["Yunanistan ve Türkiye","İspanya ve Fransa","Mısır ve Libya","İtalya ve Hırvatistan"]'::jsonb, 3, 'cografya'),
('Kuzey Denizi hangi ülkelerin kıyısındadır?', '["İngiltere ve Norveç","İtalya ve Yunanistan","Türkiye ve Bulgaristan","İspanya ve Fas"]'::jsonb, 0, 'cografya'),
('Kongo Nehri hangi kıtadadır?', '["Asya","Afrika","Güney Amerika","Avustralya"]'::jsonb, 1, 'cografya'),
('Nijer Nehri hangi kıtadadır?', '["Asya","Avrupa","Afrika","Amerika"]'::jsonb, 2, 'cografya'),
('Sarı Irmak (Huang He) hangi ülkededir?', '["Hindistan","Japonya","Kore","Çin"]'::jsonb, 3, 'cografya'),
('Mekong Nehri hangi bölgeden geçer?', '["Güneydoğu Asya","Kuzey Afrika","Orta Avrupa","Kuzey Amerika"]'::jsonb, 0, 'cografya'),
('İndus Nehri ağırlıklı olarak hangi ülkededir?', '["İran","Pakistan","Afganistan","Nepal"]'::jsonb, 1, 'cografya'),
('Colorado Nehri hangi büyük kanyonu oluşturmuştur?', '["Köprülü Kanyon","Ihlara Vadisi","Büyük Kanyon","Fjord"]'::jsonb, 2, 'cografya'),
('Fiyort (fjord) oluşumu hangi etkenin ürünüdür?', '["Rüzgâr birikimi","Volkan patlaması","Deprem","Buzul aşındırması"]'::jsonb, 3, 'cografya'),
('Fiyortlarıyla tanınan ülke hangisidir?', '["Norveç","İtalya","Yunanistan","Portekiz"]'::jsonb, 0, 'cografya'),
('Ria tipi kıyı nasıl oluşur?', '["Buzul vadisinin dolmasıyla","Akarsu vadisinin deniz basmasıyla","Volkan çökmesiyle","Kum birikmesiyle"]'::jsonb, 1, 'cografya'),
('Lagün (kıyı gölü) nasıl oluşur?', '["Volkan kraterinin dolmasıyla","Buzulun erimesiyle","Kıyı kordonunun koyu kapatmasıyla","Fayın çökmesiyle"]'::jsonb, 2, 'cografya'),
('Atol nedir?', '["Volkanik yarımada","Buzul gölü","Kum çölü","Halka biçiminde mercan adası"]'::jsonb, 3, 'cografya'),
('Mercan resiflerinin oluşumu için gereken koşul nedir?', '["Sıcak ve sığ deniz suyu","Soğuk derin su","Tatlı su","Tuzsuz su"]'::jsonb, 0, 'cografya'),
('Levha tektoniği kuramı neyi açıklar?', '["İklim kuşaklarını","Kıtaların hareketini","Nüfus dağılışını","Bitki örtüsünü"]'::jsonb, 1, 'cografya'),
('Pangea neyi ifade eder?', '["Bir okyanus akıntısı","Bir çöl adı","Kıtaların birleşik olduğu eski kara","Bir sıradağ"]'::jsonb, 2, 'cografya'),
('Pasifik Ateş Çemberi neyle tanınır?', '["Kuraklığıyla","Buzullarıyla","Ormanlarıyla","Deprem ve volkan yoğunluğuyla"]'::jsonb, 3, 'cografya'),
('Yeryüzünün en dış katmanı hangisidir?', '["Yer kabuğu","Manto","Dış çekirdek","İç çekirdek"]'::jsonb, 0, 'cografya'),
('Manto katmanının temel özelliği nedir?', '["Tamamen katı olması","Akışkan hareketli olması","Gaz halinde olması","Buzdan oluşması"]'::jsonb, 1, 'cografya'),
('Magmanın yeryüzüne çıkmış hâline ne ad verilir?', '["Manto","Tortul","Lav","Moren"]'::jsonb, 2, 'cografya'),
('Püskürük (magmatik) kayaçlara örnek hangisidir?', '["Kalker","Kumtaşı","Mermer","Bazalt"]'::jsonb, 3, 'cografya'),
('Tortul kayaçlara örnek hangisidir?', '["Kireçtaşı","Granit","Bazalt","Andezit"]'::jsonb, 0, 'cografya'),
('Başkalaşım (metamorfik) kayaca örnek hangisidir?', '["Kumtaşı","Mermer","Bazalt","Kil"]'::jsonb, 1, 'cografya'),
('Fosillere hangi kayaç türünde rastlanır?', '["Püskürük","Başkalaşım","Tortul","Volkanik cam"]'::jsonb, 2, 'cografya'),
('Coğrafi Bilgi Sistemleri (CBS) ne sağlar?', '["Nüfus artışını","İklim değişimini","Toprak verimini","Konumsal verinin analizini"]'::jsonb, 3, 'cografya'),
('GPS sisteminin coğrafyadaki temel işlevi nedir?', '["Konum belirlemek","Yükseklik artırmak","Sıcaklık ölçmek","Yağış tahmini"]'::jsonb, 0, 'cografya'),
('Uzaktan algılama nasıl veri toplar?', '["Arazi ölçümüyle","Uydu ve hava fotoğraflarıyla","Anketle","Sayımla"]'::jsonb, 1, 'cografya'),
('Bir haritada kuzey yönü genellikle nerede gösterilir?', '["Alt tarafta","Sağda","Üst tarafta","Solda"]'::jsonb, 2, 'cografya'),
('Fiziki haritalarda yeşil renk neyi gösterir?', '["Yüksek dağları","Denizleri","Çölleri","Alçak ovaları"]'::jsonb, 3, 'cografya'),
('Fiziki haritalarda kahverengi tonlar neyi gösterir?', '["Yüksek dağlık alanları","Ovaları","Gölleri","Ormanları"]'::jsonb, 0, 'cografya'),
('Bir haritanın ölçeği küçüldükçe kapsanan alan nasıl değişir?', '["Daralır","Genişler","Değişmez","İkiye bölünür"]'::jsonb, 1, 'cografya'),
('Projeksiyon (izdüşüm) yöntemi neden gereklidir?', '["Renk seçmek için","Ölçek büyütmek için","Küresel yüzeyi düzleme aktarmak için","Yön bulmak için"]'::jsonb, 2, 'cografya'),
('Topografya haritaları neyi ayrıntılı gösterir?', '["Nüfus dağılışını","Ürün çeşidini","Siyasi sınırları","Yer şekillerini"]'::jsonb, 3, 'cografya'),
('Kadastro haritalarının konusu nedir?', '["Arazi mülkiyet sınırları","İklim tipleri","Bitki örtüsü","Deniz derinliği"]'::jsonb, 0, 'cografya'),
('Batimetri neyi ölçer?', '["Dağ yüksekliğini","Su altı derinliğini","Hava sıcaklığını","Nüfus yoğunluğunu"]'::jsonb, 1, 'cografya'),
('Bir yerin mutlak konumu neye göre belirlenir?', '["Komşu ülkelere göre","Denize uzaklığa göre","Enlem ve boylama göre","Yükseltiye göre"]'::jsonb, 2, 'cografya'),
('Göreceli (özel) konum neyi ifade eder?', '["Enlem-boylam değerlerini","Yüzölçümünü","Nüfusunu","Çevresine göre konumunu"]'::jsonb, 3, 'cografya'),
('Enlemin en belirgin etkisi nedir?', '["Sıcaklık dağılışı","Yerel saat","Yer şekilleri","Toprak türü"]'::jsonb, 0, 'cografya'),
('Boylamın en belirgin etkisi nedir?', '["Sıcaklık dağılışı","Yerel saat farkı","Bitki örtüsü","Yağış miktarı"]'::jsonb, 1, 'cografya'),
('Türkiye''nin ortak saati hangi meridyene göre ayarlanır?', '["30. doğu meridyeni","0. meridyen","45. doğu meridyeni","60. doğu meridyeni"]'::jsonb, 2, 'cografya'),
('Aynı boylam üzerindeki iki nokta için ortak olan nedir?', '["Sıcaklık","Yükselti","İklim","Yerel saat"]'::jsonb, 3, 'cografya'),
('Aynı enlem üzerindeki noktalarda ortak olan nedir?', '["Güneş ışınlarının geliş açısı","Yerel saat","Yükselti","Nüfus"]'::jsonb, 0, 'cografya'),
('Kutuplara gidildikçe paralel dairelerin boyu nasıl değişir?', '["Uzar","Kısalır","Değişmez","İkiye katlanır"]'::jsonb, 1, 'cografya'),
('Dünya''nın şekli en doğru hangi terimle tanımlanır?', '["Tam küre","Silindir","Geoid","Koni"]'::jsonb, 2, 'cografya'),
('Dünya''nın kutuplardan basık olmasının sonucu nedir?', '["Kutupta gündüz olmaması","Mevsimlerin oluşması","Gelgitin oluşması","Ekvator yarıçapının daha uzun olması"]'::jsonb, 3, 'cografya'),
('Dinamik basınç nasıl oluşur?', '["Hava kütlelerinin yükselip alçalmasıyla","Sıcaklık farkıyla","Nem farkıyla","Yükselti farkıyla"]'::jsonb, 0, 'cografya'),
('Termik alçak basınç nasıl oluşur?', '["Havanın soğuyup alçalmasıyla","Havanın ısınıp yükselmesiyle","Yağış artışıyla","Rüzgârın durmasıyla"]'::jsonb, 1, 'cografya'),
('Rüzgâr hangi yönde eser?', '["Alçak basınçtan yükseğe","Kuzeyden güneye hep","Yüksek basınçtan alçak basınca","Doğudan batıya hep"]'::jsonb, 2, 'cografya'),
('Meltem rüzgârları hangi zaman ölçeğinde yön değiştirir?', '["Yıllık","Mevsimlik","On yıllık","Günlük"]'::jsonb, 3, 'cografya'),
('Fön rüzgârının özelliği nedir?', '["Dağ yamacından sıcak ve kuru inmesi","Soğuk ve nemli olması","Yağış getirmesi","Kutuplardan gelmesi"]'::jsonb, 0, 'cografya'),
('Türkiye''de etkili olan sıcak ve kuru güney rüzgârına ne denir?', '["Poyraz","Lodos","Karayel","Yıldız"]'::jsonb, 1, 'cografya'),
('Poyraz rüzgârı hangi yönden eser?', '["Güneybatı","Güneydoğu","Kuzeydoğu","Kuzeybatı"]'::jsonb, 2, 'cografya'),
('Türkiye''de kışın kar getiren kuzeybatı rüzgârı hangisidir?', '["Lodos","Samyeli","Kıble","Karayel"]'::jsonb, 3, 'cografya'),
('Samyeli rüzgârının özelliği nedir?', '["Sıcak ve kavurucu olması","Soğuk ve karlı olması","Nemli olması","Sürekli esmesi"]'::jsonb, 0, 'cografya'),
('Hava tahmininde kullanılan basınç birimi hangisidir?', '["Nüton","Hektopaskal","Joule","Amper"]'::jsonb, 1, 'cografya'),
('Higrometre neyi ölçer?', '["Basıncı","Rüzgâr hızını","Nemi","Yağış miktarını"]'::jsonb, 2, 'cografya'),
('Anemometre neyi ölçer?', '["Nemi","Sıcaklığı","Yağışı","Rüzgâr hızını"]'::jsonb, 3, 'cografya'),
('Plüviyometre neyi ölçer?', '["Yağış miktarını","Rüzgâr yönünü","Basıncı","Nemi"]'::jsonb, 0, 'cografya'),
('Barometre neyi ölçer?', '["Sıcaklığı","Hava basıncını","Nemi","Yağışı"]'::jsonb, 1, 'cografya'),
('Sis nasıl oluşur?', '["Yüksek bulut oluşumuyla","Kar erimesiyle","Yer yüzeyine yakın yoğuşmayla","Rüzgârın durmasıyla"]'::jsonb, 2, 'cografya'),
('Kırağı hangi koşulda oluşur?', '["Yağmurun donmasıyla","Karın erimesiyle","Sisin dağılmasıyla","Su buharının doğrudan buza dönüşmesiyle"]'::jsonb, 3, 'cografya'),
('Dolu hangi bulut türünde oluşur?', '["Kümülonimbüs","Sirüs","Stratüs","Altokümülüs"]'::jsonb, 0, 'cografya'),
('Sirüs bulutları hangi yükseklikte bulunur?', '["Alçak","Yüksek","Yer seviyesinde","Stratosferde"]'::jsonb, 1, 'cografya'),
('Kasırga (tropikal siklon) hangi koşulda güç kazanır?', '["Karada","Soğuk sularda","Sıcak okyanus suyu üzerinde","Çölde"]'::jsonb, 2, 'cografya'),
('Hortum (tornado) en sık hangi ülkede görülür?', '["Norveç","Mısır","Yeni Zelanda","ABD"]'::jsonb, 3, 'cografya'),
('Kuraklığın tarımsal sonucu nedir?', '["Verimin düşmesi","Ekili alanın artması","Toprağın zenginleşmesi","Sulamanın kolaylaşması"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
