-- Soru havuzu genişletme — Parti 4: Spor + Genel
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Bir futbol takımı sahada kaç oyuncuyla mücadele eder?', '["11","10","12","9"]'::jsonb, 0, 'spor'),
('Futbolda bir maç normal süresi kaç dakikadır?', '["90","80","100","120"]'::jsonb, 0, 'spor'),
('FIFA Dünya Kupası kaç yılda bir düzenlenir?', '["4","2","3","5"]'::jsonb, 0, 'spor'),
('2022 FIFA Dünya Kupası''nı hangi ülke kazanmıştır?', '["Arjantin","Fransa","Brezilya","Almanya"]'::jsonb, 0, 'spor'),
('Dünya Kupası''nı en çok kazanan ülke hangisidir?', '["Brezilya","Almanya","İtalya","Arjantin"]'::jsonb, 0, 'spor'),
('Türkiye 2002 Dünya Kupası''nda kaçıncı olmuştur?', '["3.","2.","4.","Çeyrek final"]'::jsonb, 0, 'spor'),
('UEFA Şampiyonlar Ligi''ni en çok kazanan kulüp hangisidir?', '["Real Madrid","Barcelona","Bayern Münih","Milan"]'::jsonb, 0, 'spor'),
('Lionel Messi kariyerinin büyük bölümünü hangi kulüpte geçirmiştir?', '["Barcelona","Real Madrid","PSG","Inter Miami"]'::jsonb, 0, 'spor'),
('Cristiano Ronaldo hangi ülkenin milli takımında oynar?', '["Portekiz","İspanya","Brezilya","Arjantin"]'::jsonb, 0, 'spor'),
('Pele hangi ülkenin efsane futbolcusudur?', '["Brezilya","Arjantin","Portekiz","İspanya"]'::jsonb, 0, 'spor'),
('Diego Maradona hangi ülkenin efsanesidir?', '["Arjantin","Brezilya","Uruguay","Şili"]'::jsonb, 0, 'spor'),
('Türkiye Süper Ligi''nde en çok şampiyonluğu olan kulüp hangisidir?', '["Galatasaray","Fenerbahçe","Beşiktaş","Trabzonspor"]'::jsonb, 0, 'spor'),
('UEFA Kupası kazanan ilk Türk takımı hangisidir?', '["Galatasaray","Fenerbahçe","Beşiktaş","Trabzonspor"]'::jsonb, 0, 'spor'),
('Galatasaray UEFA Kupası''nı hangi yıl kazanmıştır?', '["2000","1999","2002","1996"]'::jsonb, 0, 'spor'),
('Basketbolda bir takım sahada kaç oyuncuyla oynar?', '["5","6","7","4"]'::jsonb, 0, 'spor'),
('Basketbol potasının yüksekliği kaç metredir?', '["3,05","2,90","3,20","2,75"]'::jsonb, 0, 'spor'),
('NBA hangi ülkenin basketbol ligidir?', '["ABD","İngiltere","İspanya","Kanada"]'::jsonb, 0, 'spor'),
('Michael Jordan kariyerinin efsane yıllarını hangi takımda geçirmiştir?', '["Chicago Bulls","Lakers","Celtics","Knicks"]'::jsonb, 0, 'spor'),
('Voleybolda bir takım sahada kaç oyuncuyla oynar?', '["6","5","7","8"]'::jsonb, 0, 'spor'),
('Voleybolda bir set normalde kaç sayıda biter?', '["25","21","15","30"]'::jsonb, 0, 'spor'),
('Türkiye Kadın Voleybol Milli Takımı''nın lakabı nedir?', '["Filenin Sultanları","Filenin Melekleri","Sultanlar Ligi","Altın Kızlar"]'::jsonb, 0, 'spor'),
('Tenis kortunda dört büyük turnuvaya ne ad verilir?', '["Grand Slam","Masters","Premier","Cup Series"]'::jsonb, 0, 'spor'),
('Wimbledon tenis turnuvası hangi ülkede oynanır?', '["İngiltere","Fransa","ABD","Avustralya"]'::jsonb, 0, 'spor'),
('Teniste sıfır sayı ne olarak adlandırılır?', '["Love","Zero","Nil","Out"]'::jsonb, 0, 'spor'),
('Olimpiyat Oyunları kaç yılda bir yapılır?', '["4","2","3","5"]'::jsonb, 0, 'spor'),
('Modern Olimpiyatlar ilk kez hangi şehirde düzenlenmiştir?', '["Atina","Paris","Londra","Roma"]'::jsonb, 0, 'spor'),
('Olimpiyat bayrağındaki halka sayısı kaçtır?', '["5","4","6","7"]'::jsonb, 0, 'spor'),
('Olimpiyat halkaları neyi temsil eder?', '["Kıtaları","Ülkeleri","Sporları","Denizleri"]'::jsonb, 0, 'spor'),
('Maraton koşusu yaklaşık kaç kilometredir?', '["42","35","50","26"]'::jsonb, 0, 'spor'),
('Maraton adını hangi ülkedeki bir kasabadan alır?', '["Yunanistan","İtalya","Türkiye","Mısır"]'::jsonb, 0, 'spor'),
('100 metre dünya rekorunun sahibi (9.58) kimdir?', '["Usain Bolt","Carl Lewis","Tyson Gay","Asafa Powell"]'::jsonb, 0, 'spor'),
('Usain Bolt hangi ülkenin sporcusudur?', '["Jamaika","ABD","Kenya","Trinidad"]'::jsonb, 0, 'spor'),
('Naim Süleymanoğlu hangi sporun efsanesidir?', '["Halter","Güreş","Boks","Atletizm"]'::jsonb, 0, 'spor'),
('"Cep Herkülü" lakaplı sporcumuz kimdir?', '["Naim Süleymanoğlu","Halil Mutlu","Hamza Yerlikaya","Taha Akgül"]'::jsonb, 0, 'spor'),
('Türkiye''nin ata sporu olarak bilinen spor hangisidir?', '["Güreş","Futbol","Okçuluk","Cirit"]'::jsonb, 0, 'spor'),
('Kırkpınar Yağlı Güreşleri hangi ilimizde yapılır?', '["Edirne","Tekirdağ","Kırklareli","Çanakkale"]'::jsonb, 0, 'spor'),
('Kırkpınar''da başpehlivana verilen ödül kemerin adı nedir?', '["Altın kemer","Gümüş kemer","Kırmızı kuşak","Şampiyonluk kuşağı"]'::jsonb, 0, 'spor'),
('Boksta nakavt anlamına gelen kısaltma nedir?', '["KO","TKO","NK","BO"]'::jsonb, 0, 'spor'),
('Muhammed Ali hangi sporun efsanesidir?', '["Boks","Güreş","Basketbol","Atletizm"]'::jsonb, 0, 'spor'),
('Formula 1''de en çok dünya şampiyonluğu rekoru kaçtır?', '["7","5","8","6"]'::jsonb, 0, 'spor'),
('Formula 1 İstanbul yarışları hangi pistte yapılmıştır?', '["İstanbul Park","Veliefendi","TOSFED","İzmir Park"]'::jsonb, 0, 'spor'),
('Satrançta oyunu kazanmak için rakibin hangi taşı mat edilir?', '["Şah","Vezir","Kale","At"]'::jsonb, 0, 'spor'),
('Satranç tahtasında kaç kare vardır?', '["64","81","100","49"]'::jsonb, 0, 'spor'),
('Satrançta en güçlü taş hangisidir?', '["Vezir","Şah","Kale","Fil"]'::jsonb, 0, 'spor'),
('Yüzmede hangi stil en hızlı kabul edilir?', '["Serbest","Kurbağalama","Sırtüstü","Kelebek"]'::jsonb, 0, 'spor'),
('Sürat pateni hangi zeminde yapılır?', '["Buz","Asfalt","Parke","Çim"]'::jsonb, 0, 'spor'),
('Golfte topun vurulduğu sopalara ne denir?', '["Kulüp (club)","Raket","Sopa","Stick"]'::jsonb, 0, 'spor'),
('Beyzbol hangi ülkenin milli sporu sayılır?', '["ABD","Japonya","Küba","Kanada"]'::jsonb, 0, 'spor'),
('Sumo güreşi hangi ülkenin geleneksel sporudur?', '["Japonya","Çin","Kore","Moğolistan"]'::jsonb, 0, 'spor'),
('Tekvando hangi ülkede doğmuştur?', '["Güney Kore","Japonya","Çin","Tayland"]'::jsonb, 0, 'spor'),
('Judo hangi ülkede doğmuştur?', '["Japonya","Çin","Kore","Brezilya"]'::jsonb, 0, 'spor'),
('Hentbolda bir takım sahada kaç oyuncuyla oynar?', '["7","6","5","8"]'::jsonb, 0, 'spor'),
('Su topu hangi ortamda oynanır?', '["Havuz","Deniz","Göl","Nehir"]'::jsonb, 0, 'spor'),
('Eskrimde kullanılan silahlardan biri hangisidir?', '["Epe","Mızrak","Yay","Topuz"]'::jsonb, 0, 'spor'),
('Okçulukta hedef tahtasının tam ortasına ne denir?', '["On (sarı bölge)","Merkez","Göbek","Hedef"]'::jsonb, 0, 'spor'),
('Bilardoda beyaz topa vurmak için kullanılan sopaya ne denir?', '["Isteka","Çubuk","Baston","Şiş"]'::jsonb, 0, 'spor'),
('Bowlingde tüm lobutları tek atışta devirmeye ne denir?', '["Strike","Spare","Full","Perfect"]'::jsonb, 0, 'spor'),
('Bir hafta kaç gündür?', '["7","6","8","5"]'::jsonb, 0, 'genel'),
('Bir yılda kaç ay vardır?', '["12","10","11","13"]'::jsonb, 0, 'genel'),
('Şubat ayı normal yıllarda kaç gündür?', '["28","29","30","27"]'::jsonb, 0, 'genel'),
('Türk bayrağında hangi semboller bulunur?', '["Ay ve yıldız","Güneş ve yıldız","Ay ve güneş","Sadece yıldız"]'::jsonb, 0, 'genel'),
('Türkiye''nin telefon kodu kaçtır?', '["+90","+91","+49","+44"]'::jsonb, 0, 'genel'),
('Türkiye''nin para birimi nedir?', '["Türk Lirası","Euro","Dolar","Kuruş"]'::jsonb, 0, 'genel'),
('Japonya''nın para birimi nedir?', '["Yen","Yuan","Won","Dolar"]'::jsonb, 0, 'genel'),
('İngiltere''nin para birimi nedir?', '["Sterlin","Euro","Dolar","Frank"]'::jsonb, 0, 'genel'),
('Avrupa Birliği''nin ortak para birimi nedir?', '["Euro","Sterlin","Frank","Mark"]'::jsonb, 0, 'genel'),
('Kırmızı ile sarının karışımından hangi renk oluşur?', '["Turuncu","Yeşil","Mor","Kahverengi"]'::jsonb, 0, 'genel'),
('Mavi ile sarının karışımından hangi renk oluşur?', '["Yeşil","Turuncu","Mor","Gri"]'::jsonb, 0, 'genel'),
('Kırmızı ile mavinin karışımından hangi renk oluşur?', '["Mor","Yeşil","Turuncu","Pembe"]'::jsonb, 0, 'genel'),
('Trafik ışığında kırmızı ne anlama gelir?', '["Dur","Geç","Yavaşla","Bekle"]'::jsonb, 0, 'genel'),
('Türkiye''de acil çağrı merkezi numarası kaçtır?', '["112","155","110","156"]'::jsonb, 0, 'genel'),
('Bir düzine kaç adettir?', '["12","10","6","24"]'::jsonb, 0, 'genel'),
('Yarım düzine kaç adettir?', '["6","12","4","8"]'::jsonb, 0, 'genel'),
('Bir saat kaç dakikadır?', '["60","100","30","90"]'::jsonb, 0, 'genel'),
('Bir dakika kaç saniyedir?', '["60","100","30","120"]'::jsonb, 0, 'genel'),
('Bir kilometre kaç metredir?', '["1000","100","10000","500"]'::jsonb, 0, 'genel'),
('Bir kilogram kaç gramdır?', '["1000","100","500","10000"]'::jsonb, 0, 'genel'),
('Bir litre kaç mililitredir?', '["1000","100","500","250"]'::jsonb, 0, 'genel'),
('Satranç ve dama hangi tür oyunlardandır?', '["Zeka oyunları","Şans oyunları","Kart oyunları","Spor oyunları"]'::jsonb, 0, 'genel'),
('Monopoly hangi tür oyundur?', '["Kutu oyunu","Kart oyunu","Video oyunu","Açık hava oyunu"]'::jsonb, 0, 'genel'),
('Bir tavla zarında en büyük sayı kaçtır?', '["6","9","5","12"]'::jsonb, 0, 'genel'),
('İskambil destesinde kaç kart vardır (jokersiz)?', '["52","54","48","50"]'::jsonb, 0, 'genel'),
('İskambil destesinde kaç farklı sembol (renk) vardır?', '["4","2","3","6"]'::jsonb, 0, 'genel'),
('Piyanoda kaç tuş vardır (standart)?', '["88","61","76","100"]'::jsonb, 0, 'genel'),
('Gitarın standart tel sayısı kaçtır?', '["6","4","5","7"]'::jsonb, 0, 'genel'),
('Kemanın kaç teli vardır?', '["4","6","5","3"]'::jsonb, 0, 'genel'),
('Türk kahvesi neyle birlikte ikram edilir?', '["Su ve lokum","Çay","Süt","Şeker"]'::jsonb, 0, 'genel'),
('Baklavanın temel malzemelerinden biri hangisidir?', '["Yufka","Pirinç","Bulgur","Patates"]'::jsonb, 0, 'genel'),
('İskender kebap hangi şehrimizle özdeşleşmiştir?', '["Bursa","Adana","Konya","Gaziantep"]'::jsonb, 0, 'genel'),
('Adana''nın meşhur yemeği hangisidir?', '["Adana kebap","İskender","Mantı","Çiğ köfte"]'::jsonb, 0, 'genel'),
('Mantı hangi şehrimizle özdeşleşmiştir?', '["Kayseri","Konya","Bursa","Sivas"]'::jsonb, 0, 'genel'),
('Baklavasıyla ünlü şehrimiz hangisidir?', '["Gaziantep","Adana","Hatay","Mersin"]'::jsonb, 0, 'genel'),
('Hamsi hangi bölgemizle özdeşleşmiştir?', '["Karadeniz","Ege","Akdeniz","Marmara"]'::jsonb, 0, 'genel'),
('Sushi hangi ülkenin yemeğidir?', '["Japonya","Çin","Kore","Tayland"]'::jsonb, 0, 'genel'),
('Pizza hangi ülkenin yemeğidir?', '["İtalya","Fransa","İspanya","Yunanistan"]'::jsonb, 0, 'genel'),
('Paella hangi ülkenin yemeğidir?', '["İspanya","İtalya","Portekiz","Meksika"]'::jsonb, 0, 'genel'),
('Croissant hangi ülkeyle özdeşleşmiştir?', '["Fransa","İtalya","Belçika","Avusturya"]'::jsonb, 0, 'genel'),
('Çay en çok hangi ilimizde yetişir?', '["Rize","Trabzon","Ordu","Artvin"]'::jsonb, 0, 'genel'),
('Fındık üretiminde dünya lideri ülke hangisidir?', '["Türkiye","İtalya","ABD","Gürcistan"]'::jsonb, 0, 'genel'),
('Kahvenin anavatanı hangi ülke kabul edilir?', '["Etiyopya","Brezilya","Kolombiya","Yemen"]'::jsonb, 0, 'genel'),
('Bal hangi hayvandan elde edilir?', '["Arı","İpek böceği","İnek","Keçi"]'::jsonb, 0, 'genel'),
('İpek hangi canlıdan elde edilir?', '["İpek böceği","Örümcek","Koyun","Pamuk bitkisi"]'::jsonb, 0, 'genel'),
('Yoğurt hangi kültürün dünyaya kazandırdığı kabul edilen besindir?', '["Türk","Yunan","Bulgar","Hint"]'::jsonb, 0, 'genel'),
('Nasreddin Hoca hangi şehrimizle anılır?', '["Akşehir","Konya","Kayseri","Sivrihisar"]'::jsonb, 0, 'genel'),
('Türkiye''de 23 Nisan hangi bayramdır?', '["Ulusal Egemenlik ve Çocuk Bayramı","Gençlik ve Spor Bayramı","Zafer Bayramı","Cumhuriyet Bayramı"]'::jsonb, 0, 'genel'),
('19 Mayıs hangi bayramdır?', '["Atatürk''ü Anma, Gençlik ve Spor Bayramı","Çocuk Bayramı","Zafer Bayramı","Emek Bayramı"]'::jsonb, 0, 'genel'),
('30 Ağustos hangi bayramdır?', '["Zafer Bayramı","Cumhuriyet Bayramı","Çocuk Bayramı","Gençlik Bayramı"]'::jsonb, 0, 'genel'),
('Anneler Günü hangi ayda kutlanır?', '["Mayıs","Nisan","Haziran","Mart"]'::jsonb, 0, 'genel'),
('Öğretmenler Günü Türkiye''de hangi tarihte kutlanır?', '["24 Kasım","23 Nisan","10 Kasım","5 Ekim"]'::jsonb, 0, 'genel'),
('Dünya Kadınlar Günü hangi tarihtedir?', '["8 Mart","8 Mayıs","1 Mayıs","8 Nisan"]'::jsonb, 0, 'genel'),
('Pusulanın iğnesi hangi yönü gösterir?', '["Kuzey","Güney","Doğu","Batı"]'::jsonb, 0, 'genel'),
('Güneş hangi yönden doğar?', '["Doğu","Batı","Kuzey","Güney"]'::jsonb, 0, 'genel'),
('Türk lirası banknotlarının ön yüzünde kimin portresi vardır?', '["Atatürk","Mimar Sinan","Mevlana","Fatih"]'::jsonb, 0, 'genel'),
('Kuzey Kıbrıs''ta resmi dil nedir?', '["Türkçe","Rumca","İngilizce","Yunanca"]'::jsonb, 0, 'genel'),
('Brezilya''nın resmi dili nedir?', '["Portekizce","İspanyolca","Brezilyaca","İngilizce"]'::jsonb, 0, 'genel'),
('Dünyada en çok konuşulan ana dil hangisidir?', '["Mandarin Çincesi","İngilizce","İspanyolca","Hintçe"]'::jsonb, 0, 'genel'),
('Braille alfabesi kimler için geliştirilmiştir?', '["Görme engelliler","İşitme engelliler","Konuşma engelliler","Okuma güçlüğü çekenler"]'::jsonb, 0, 'genel'),
('İşaret dili hangi engel grubuyla iletişimde kullanılır?', '["İşitme engelliler","Görme engelliler","Yürüme engelliler","Hepsi"]'::jsonb, 0, 'genel'),
('Kızılay''ın uluslararası karşılığı hangi örgüttür?', '["Kızılhaç","UNICEF","WHO","Yeşilay"]'::jsonb, 0, 'genel'),
('Sigara ve alkolle mücadele eden Türk kurumu hangisidir?', '["Yeşilay","Kızılay","AFAD","LÖSEV"]'::jsonb, 0, 'genel')
on conflict (soru) do nothing;
