-- Soru havuzu genişletme: cografya +116
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Türkiye''nin Ege kıyısındaki en büyük limanı hangi ildedir?', '["İzmir","Aydın","Muğla","Manisa"]'::jsonb, 0, 'cografya'),
('İskenderun Limanı hangi ilimizdedir?', '["Mersin","Hatay","Adana","Osmaniye"]'::jsonb, 1, 'cografya'),
('Türkiye''nin Karadeniz''deki büyük limanlarından Samsun hangi ovanın kıyısındadır?', '["Çukurova","Amik","Çarşamba","Gediz"]'::jsonb, 2, 'cografya'),
('Haydarpaşa Limanı hangi şehirdedir?', '["Kocaeli","Bursa","Yalova","İstanbul"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en işlek havalimanı hangi şehirdedir?', '["İstanbul","Ankara","İzmir","Antalya"]'::jsonb, 0, 'cografya'),
('Karayolu ulaşımının Türkiye''de yaygınlaşmasının nedeni nedir?', '["Maliyetinin en düşük olması","Kapıdan kapıya taşıma esnekliği","Hızının en yüksek olması","Yük kapasitesinin en büyüğü olması"]'::jsonb, 1, 'cografya'),
('Demiryolu taşımacılığının en büyük avantajı nedir?', '["En hızlı olması","Her yere ulaşması","Ağır yükü ucuza taşıması","Hava koşullarından etkilenmemesi"]'::jsonb, 2, 'cografya'),
('Denizyolu taşımacılığının temel üstünlüğü nedir?', '["En hızlı olması","Karadan her yere gitmesi","Küçük yükler için uygunluğu","Birim maliyetin en düşük olması"]'::jsonb, 3, 'cografya'),
('Boru hattı taşımacılığı hangi ürünlerde kullanılır?', '["Petrol ve doğal gaz","Tahıl","Otomobil","Tekstil"]'::jsonb, 0, 'cografya'),
('Türkiye''de ilk demiryolu hattı hangi bölgede yapılmıştır?', '["Doğu Anadolu","Ege","Karadeniz","Güneydoğu Anadolu"]'::jsonb, 1, 'cografya'),
('Bir yerleşimin ticaret merkezi olmasında en önemli etken nedir?', '["Yüksek rakım","Ormanlık olması","Ulaşım yollarının kesişmesi","Soğuk iklim"]'::jsonb, 2, 'cografya'),
('Kent hiyerarşisinde metropol ne anlama gelir?', '["Küçük kasaba","Köy yerleşimi","Sanayi sitesi","Geniş etki alanı olan büyük kent"]'::jsonb, 3, 'cografya'),
('Uydu kent kavramı neyi ifade eder?', '["Büyük kentin çevresindeki bağlı yerleşim","Dağ köyü","Kıyı kasabası","Turistik belde"]'::jsonb, 0, 'cografya'),
('Kent planlamasında yeşil kuşak neyi amaçlar?', '["Nüfusu artırmak","Kentin yayılmasını sınırlamak","Sanayi kurmak","Yol açmak"]'::jsonb, 1, 'cografya'),
('Kırsal yerleşmelerde toplu yerleşme hangi koşulda görülür?', '["Suyun bol olduğu yerlerde","Ormanlık alanlarda","Su kaynağının sınırlı olduğu yerlerde","Dağ zirvelerinde"]'::jsonb, 2, 'cografya'),
('Mezra nasıl bir yerleşim birimidir?', '["Büyük ilçe merkezi","Sanayi sitesi","Liman kenti","Köyden ayrılmış küçük tarım yerleşmesi"]'::jsonb, 3, 'cografya'),
('Oba yerleşmesi hangi yaşam biçimiyle ilgilidir?', '["Göçebe hayvancılık","Sanayi işçiliği","Balıkçılık","Madencilik"]'::jsonb, 0, 'cografya'),
('Divan, kom ve dam yerleşmeleri hangi tür yerleşmelerdir?', '["Kalıcı kent yerleşmeleri","Geçici kırsal yerleşmeler","Sanayi yerleşmeleri","Liman yerleşmeleri"]'::jsonb, 1, 'cografya'),
('Türkiye''de kırsal nüfusun azalmasının temel nedeni nedir?', '["Doğum oranının artması","Tarımın gelişmesi","Kente göç","İklimin ısınması"]'::jsonb, 2, 'cografya'),
('Bir ülkede tarımda çalışan nüfus oranının düşmesi neyi gösterir?', '["Tarımın çöktüğünü","Nüfusun azaldığını","Toprağın verimsizleştiğini","Sanayi ve hizmetin geliştiğini"]'::jsonb, 3, 'cografya'),
('Gayrisafi yurt içi hasıla neyi ölçer?', '["Üretilen mal ve hizmetin değerini","Nüfus sayısını","Yüzölçümünü","İhracat miktarını"]'::jsonb, 0, 'cografya'),
('Kişi başına düşen gelirin yüksekliği neyi gösterir?', '["Nüfusun fazlalığını","Refah düzeyinin yüksekliğini","Yüzölçümünün büyüklüğünü","Tarımın gelişmişliğini"]'::jsonb, 1, 'cografya'),
('Gelişmiş ülkelerde nüfus artış hızı genellikle nasıldır?', '["Çok yüksek","Sıfır","Düşük","Sürekli artan"]'::jsonb, 2, 'cografya'),
('Az gelişmiş ülkelerde nüfusun genel özelliği nedir?', '["Yaşlı nüfusun fazlalığı","Nüfusun azalması","Kentleşmenin tamamlanması","Genç nüfus oranının yüksekliği"]'::jsonb, 3, 'cografya'),
('Bir ülkede ortalama yaşam süresinin uzaması neyi gösterir?', '["Sağlık koşullarının iyileştiğini","Doğum oranının arttığını","Göçün arttığını","Tarımın gerilediğini"]'::jsonb, 0, 'cografya'),
('Türkiye''de nüfus sayımlarını hangi kurum yapar?', '["MTA","TÜİK","DSİ","Meteoroloji"]'::jsonb, 1, 'cografya'),
('MTA kurumunun görev alanı nedir?', '["Hava tahmini","Su yapıları","Maden ve yer bilimleri araştırmaları","Orman yönetimi"]'::jsonb, 2, 'cografya'),
('Kandilli Rasathanesi hangi konuda çalışır?', '["Tarım","Turizm","Ulaşım","Deprem ve gözlem"]'::jsonb, 3, 'cografya'),
('Kızılçam ağacı hangi iklim bölgesinde yaygındır?', '["Akdeniz","Tundra","Karasal","Ekvatoral"]'::jsonb, 0, 'cografya'),
('Ladin ve göknar ağaçları hangi bölgemizde yaygındır?', '["Ege","Doğu Karadeniz","Güneydoğu Anadolu","Akdeniz"]'::jsonb, 1, 'cografya'),
('Orman yangınlarının en sık görüldüğü bölgemiz hangisidir?', '["Doğu Anadolu","İç Anadolu","Akdeniz","Karadeniz"]'::jsonb, 2, 'cografya'),
('Ağaç kesim ve dikiminin planlı yapılmasına ne ad verilir?', '["Tarım","Bahçecilik","Peyzaj","Ormancılık"]'::jsonb, 3, 'cografya'),
('Mera hayvancılığının en yaygın olduğu bölgemiz hangisidir?', '["Doğu Anadolu","Marmara","Ege","Karadeniz"]'::jsonb, 0, 'cografya'),
('Ahır (besi) hayvancılığı hangi bölgede daha gelişmiştir?', '["Doğu Anadolu","Marmara","Güneydoğu Anadolu","Karadeniz"]'::jsonb, 1, 'cografya'),
('İpekböcekçiliği Türkiye''de hangi ilimizle özdeşleşmiştir?', '["Rize","Kars","Bursa","Van"]'::jsonb, 2, 'cografya'),
('Kültür balıkçılığının yaygın olduğu bölge hangisidir?', '["İç Anadolu","Güneydoğu Anadolu","Doğu Anadolu","Ege ve Karadeniz kıyıları"]'::jsonb, 3, 'cografya'),
('Türkiye''de tuz üretiminde öne çıkan göl hangisidir?', '["Tuz Gölü","Van Gölü","Beyşehir Gölü","Sapanca Gölü"]'::jsonb, 0, 'cografya'),
('Deniz suyundan tuz elde etme yöntemi nedir?', '["Damıtma","Buharlaştırma","Süzme","Dondurma"]'::jsonb, 1, 'cografya'),
('Mermer üretiminde öne çıkan ilimiz hangisidir?', '["Rize","Ordu","Afyonkarahisar","Artvin"]'::jsonb, 2, 'cografya'),
('Türkiye''nin lületaşı ile bilinen ili hangisidir?', '["Kütahya","Uşak","Bilecik","Eskişehir"]'::jsonb, 3, 'cografya'),
('Çini ve seramik üretimiyle bilinen ilimiz hangisidir?', '["Kütahya","Sivas","Erzincan","Bayburt"]'::jsonb, 0, 'cografya'),
('Halı dokumacılığıyla anılan Hereke hangi ilimizdedir?', '["Sakarya","Kocaeli","Bursa","Yalova"]'::jsonb, 1, 'cografya'),
('Bakır işlemeciliğiyle bilinen ilimiz hangisidir?', '["Rize","Sinop","Gaziantep","Düzce"]'::jsonb, 2, 'cografya'),
('Türkiye''de kükürt ve barit gibi madenlerin çıkarılması hangi sektöre girer?', '["Tarım","Turizm","Ticaret","Madencilik"]'::jsonb, 3, 'cografya'),
('Bir madenin işletilebilir olması için gereken temel koşul nedir?', '["Rezerv ve tenörün yeterli olması","Yakınında şehir olması","Yağış alması","Ormanlık olması"]'::jsonb, 0, 'cografya'),
('Tenör kavramı madencilikte neyi ifade eder?', '["Maden derinliğini","Cevherdeki metal oranını","Rezerv miktarını","Maden fiyatını"]'::jsonb, 1, 'cografya'),
('Açık işletme yöntemi hangi durumda kullanılır?', '["Maden çok derindeyse","Maden denizdeyse","Maden yüzeye yakınsa","Maden sıvıysa"]'::jsonb, 2, 'cografya'),
('Türkiye''de doğal gaz üretiminin ithalatı karşılama durumu nasıldır?', '["Tamamını karşılar","Fazlasını ihraç eder","Hiç üretim yoktur","İhtiyacın küçük kısmını karşılar"]'::jsonb, 3, 'cografya'),
('Nükleer santralin çalışma ilkesi nedir?', '["Çekirdek bölünmesiyle ısı üretmek","Rüzgârı çevirmek","Suyu düşürmek","Kömür yakmak"]'::jsonb, 0, 'cografya'),
('Akkuyu Nükleer Santrali hangi ilimizdedir?', '["Sinop","Mersin","Adana","Antalya"]'::jsonb, 1, 'cografya'),
('Bir bölgede sanayinin kurulmasında en önemli etken nedir?', '["Yağış miktarı","Yükselti","Hammadde, enerji ve ulaşım","Bitki örtüsü"]'::jsonb, 2, 'cografya'),
('Sanayinin hammaddeye yakın kurulması hangi sektörde önemlidir?', '["Yazılım","Bankacılık","Sigortacılık","Çimento ve şeker"]'::jsonb, 3, 'cografya'),
('Şeker fabrikalarının pancar üretim alanına yakın kurulmasının nedeni nedir?', '["Hammaddenin çabuk bozulması","İşçinin ucuzluğu","Enerjinin bolluğu","Vergi avantajı"]'::jsonb, 0, 'cografya'),
('Türkiye''de tekstil sanayisinin gelişmesinde en etkili faktör nedir?', '["Demir cevheri","Pamuk üretimi","Kömür yatakları","Orman varlığı"]'::jsonb, 1, 'cografya'),
('Bir ülkenin sanayi ürünü ihracatının artması neyi gösterir?', '["Tarımın çöktüğünü","Nüfusun azaldığını","Katma değerin yükseldiğini","İthalatın bittiğini"]'::jsonb, 2, 'cografya'),
('Ham madde ihraç edip işlenmiş ürün ithal etmek neye yol açar?', '["Ticaret fazlasına","Enflasyonun bitmesine","Nüfus artışına","Dış ticaret açığına"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en çok ihracat yaptığı bölge hangisidir?', '["Avrupa","Güney Amerika","Okyanusya","Orta Afrika"]'::jsonb, 0, 'cografya'),
('Transit ticaret ne anlama gelir?', '["Sadece ihracat","Bir ülke üzerinden geçen ticaret","Sadece ithalat","İç ticaret"]'::jsonb, 1, 'cografya'),
('Türkiye''nin transit ticarette avantajı nereden gelir?', '["Yüksek dağlarından","Geniş çöllerinden","Asya ile Avrupa arasında olmasından","Buzullarından"]'::jsonb, 2, 'cografya'),
('Bir ülkenin coğrafi konumunun stratejik olması ne demektir?', '["Yüzölçümünün büyüklüğü","Nüfusunun fazlalığı","İkliminin sıcaklığı","Ticaret ve askerî yolların kesişmesi"]'::jsonb, 3, 'cografya'),
('İpek Yolu''nun coğrafi önemi neydi?', '["Doğu-batı ticaretini sağlaması","Kuzey-güney göçünü sağlaması","Deniz seferlerini kısaltması","Maden taşımayı kolaylaştırması"]'::jsonb, 0, 'cografya'),
('Baharat Yolu hangi bölgeleri bağlıyordu?', '["Sibirya ve Çin","Hindistan ve Akdeniz","Amerika ve Avrupa","Afrika ve Avustralya"]'::jsonb, 1, 'cografya'),
('Coğrafi Keşifler''in ticaret yollarına etkisi ne olmuştur?', '["İpek Yolu güçlenmiştir","Kara ticareti artmıştır","Akdeniz''in önemi azalmıştır","Deniz ticareti bitmiştir"]'::jsonb, 2, 'cografya'),
('Ekonomik coğrafyada ''kaynak laneti'' ne anlama gelir?', '["Kaynakların tükenmesi","Kaynağın bulunamaması","Kaynağın pahalılaşması","Kaynak bolluğunun kalkınmayı engellemesi"]'::jsonb, 3, 'cografya'),
('Bir bölgede monokültür tarım neyi ifade eder?', '["Tek ürüne bağımlı tarım","Çok ürünlü tarım","Organik tarım","Seracılık"]'::jsonb, 0, 'cografya'),
('Organik tarımın temel ilkesi nedir?', '["Yüksek verim almak","Kimyasal girdi kullanmamak","Sera kurmak","Makine kullanmak"]'::jsonb, 1, 'cografya'),
('Damla sulama yönteminin avantajı nedir?', '["Verimi düşürmesi","Toprağı tuzlaştırması","Su tasarrufu sağlaması","Maliyetsiz olması"]'::jsonb, 2, 'cografya'),
('Aşırı ve bilinçsiz sulamanın toprağa etkisi nedir?', '["Humus artışı","Verim artışı","Erozyonun bitmesi","Tuzlanma ve çoraklaşma"]'::jsonb, 3, 'cografya'),
('Nöbetleşe (münavebeli) ekim neden yapılır?', '["Toprağın verimini korumak için","Ürünü hızlandırmak için","Zararlıyı çoğaltmak için","Suyu artırmak için"]'::jsonb, 0, 'cografya'),
('Teraslama hangi soruna karşı yapılır?', '["Sel","Erozyon","Deprem","Don"]'::jsonb, 1, 'cografya'),
('Rüzgâr perdesi (ağaç şeridi) hangi amaçla dikilir?', '["Gölge yapmak","Yakacak sağlamak","Rüzgâr erozyonunu azaltmak","Meyve almak"]'::jsonb, 2, 'cografya'),
('Türkiye''de erozyonun en şiddetli olduğu bölge hangisidir?', '["Doğu Karadeniz","Marmara","Ege","İç Anadolu"]'::jsonb, 3, 'cografya'),
('Erozyonu artıran başlıca insan etkinliği nedir?', '["Bitki örtüsünün yok edilmesi","Ağaçlandırma","Teraslama","Nadas"]'::jsonb, 0, 'cografya'),
('Bir havzada baraj yapımının olumsuz etkisi ne olabilir?', '["Enerji üretimi","Yerleşim alanlarının su altında kalması","Sulama olanağı","Taşkın kontrolü"]'::jsonb, 1, 'cografya'),
('Taşkın (sel) riskini azaltmanın en etkili yolu nedir?', '["Dere yatağına yapılaşmak","Toprağı sıkıştırmak","Havzayı ağaçlandırmak","Kanalı daraltmak"]'::jsonb, 2, 'cografya'),
('Dere yataklarına yapılaşmanın sonucu nedir?', '["Erozyonun bitmesi","Verimin artması","Depremin azalması","Sel riskinin artması"]'::jsonb, 3, 'cografya'),
('Yeraltı suyunun aşırı çekilmesi hangi sorunu doğurur?', '["Obruk ve çökme","Yağış artışı","Toprak zenginleşmesi","Deprem"]'::jsonb, 0, 'cografya'),
('Konya Ovası''nda obrukların artmasının nedeni nedir?', '["Deprem sıklığı","Yeraltı suyunun aşırı kullanımı","Yağış fazlalığı","Volkanik etkinlik"]'::jsonb, 1, 'cografya'),
('Artezyen kuyusu nasıl çalışır?', '["Pompa gücüyle","Yağmurla dolarak","Basınçlı yeraltı suyunun yükselmesiyle","Buhar basıncıyla"]'::jsonb, 2, 'cografya'),
('Karstik kaynaklar hangi kayaçta oluşur?', '["Granit","Bazalt","Mermer","Kireçtaşı"]'::jsonb, 3, 'cografya'),
('Fay kaynaklarının en belirgin özelliği nedir?', '["Sıcak ve mineralli olması","Soğuk ve tatlı olması","Tuzlu olması","Mevsimlik olması"]'::jsonb, 0, 'cografya'),
('Türkiye''de kaplıcaların çokluğu neyle açıklanır?', '["Buzul aşındırması","Genç oluşumlu ve faylı yapı","Delta oluşumu","Çöl iklimi"]'::jsonb, 1, 'cografya'),
('Bir bölgenin genç oluşumlu olması ne anlama gelir?', '["Nüfusunun genç olması","Bitkilerinin yeni olması","Jeolojik olarak yeni şekillenmiş olması","Kentlerinin yeni kurulması"]'::jsonb, 2, 'cografya'),
('Türkiye''nin dağlık ve engebeli olmasının ulaşıma etkisi nedir?', '["Yolları kısaltması","Ulaşımı hızlandırması","Etkisi olmaması","Yol maliyetini artırması"]'::jsonb, 3, 'cografya'),
('Dağların denize paralel uzandığı kıyılarda kıyı çizgisi nasıldır?', '["Az girintili çıkıntılı","Çok girintili çıkıntılı","Tamamen düz","Adalarla dolu"]'::jsonb, 0, 'cografya'),
('Boyuna (konkordan) kıyı tipine Türkiye''den örnek hangisidir?', '["Ege kıyıları","Karadeniz kıyıları","Güney Marmara","Batı Akdeniz"]'::jsonb, 1, 'cografya'),
('Enine (diskordan) kıyı tipine Türkiye''den örnek hangisidir?', '["Karadeniz kıyıları","Doğu Akdeniz","Ege kıyıları","Kuzey Marmara"]'::jsonb, 2, 'cografya'),
('Kıta sahanlığı ne demektir?', '["Okyanus ortası sırt","Derin deniz çukuru","Volkanik ada","Kıtanın deniz altındaki sığ uzantısı"]'::jsonb, 3, 'cografya'),
('Kıta sahanlığının ekonomik önemi nedir?', '["Petrol ve balıkçılık kaynakları","Buzul suyu","Rüzgâr enerjisi","Orman varlığı"]'::jsonb, 0, 'cografya'),
('Karasuları kavramı neyi ifade eder?', '["Açık deniz","Kıyıdan itibaren egemenlik alanı","Uluslararası sular","Nehir suları"]'::jsonb, 1, 'cografya'),
('Münhasır ekonomik bölge neyi kapsar?', '["Hava sahasını","Kara sınırını","Deniz kaynaklarını kullanma hakkını","Nehir havzasını"]'::jsonb, 2, 'cografya'),
('Denizlerdeki akıntıların balıkçılığa etkisi nedir?', '["Balıkları uzaklaştırır","Suyu dondurur","Tuzu artırır","Besin taşıyarak balık toplar"]'::jsonb, 3, 'cografya'),
('Soğuk ve sıcak akıntıların karşılaştığı yerlerde ne oluşur?', '["Zengin balık alanları ve sis","Çöl koşulları","Buzul kütlesi","Volkanik ada"]'::jsonb, 0, 'cografya'),
('Kutup buzullarının erimesinin denizcilikteki olası sonucu nedir?', '["Süveyş''in kapanması","Kuzey deniz yollarının açılması","Panama''nın donması","Okyanusların küçülmesi"]'::jsonb, 1, 'cografya'),
('Deniz kirliliğinin en yaygın nedeni nedir?', '["Gelgit","Akıntı","Atık ve petrol deşarjı","Dalga"]'::jsonb, 2, 'cografya'),
('Karadeniz''de derinlerde oksijenin bulunmamasının nedeni nedir?', '["Aşırı balık avı","Buzul erimesi","Yüksek sıcaklık","Tuzluluk farkıyla suyun karışmaması"]'::jsonb, 3, 'cografya'),
('Müsilaj sorununun temel nedeni nedir?', '["Aşırı besin kirliliği ve ısınma","Deprem","Gelgit","Rüzgâr"]'::jsonb, 0, 'cografya'),
('Marmara Denizi''nin ekolojik olarak kırılgan olmasının nedeni nedir?', '["Derinliğinin azlığı","İç deniz olması ve yoğun kirlilik","Tuzsuz olması","Buz tutması"]'::jsonb, 1, 'cografya'),
('Boğazlar''daki alt akıntı hangi yönde ilerler?', '["Karadeniz''den Akdeniz''e","Doğudan batıya","Akdeniz''den Karadeniz''e","Batıdan doğuya"]'::jsonb, 2, 'cografya'),
('Boğazlar''daki üst akıntının yönü nedir?', '["Akdeniz''den Karadeniz''e","Kuzeyden güneye sabit","Değişmez","Karadeniz''den Akdeniz''e"]'::jsonb, 3, 'cografya'),
('Bir ülkenin coğrafi konumu iklimini nasıl etkiler?', '["Enlem ve denizellik yoluyla","Nüfus yoluyla","Yönetim biçimiyle","Para birimiyle"]'::jsonb, 0, 'cografya'),
('Denizellik etkisi kıyılarda neye yol açar?', '["Sıcaklık farkının artmasına","Sıcaklık farkının azalmasına","Yağışın bitmesine","Donmaya"]'::jsonb, 1, 'cografya'),
('Karasallık etkisi iç bölgelerde neye yol açar?', '["Yağışın artmasına","Nemin artmasına","Sıcaklık farkının artmasına","Sıcaklığın sabitleşmesine"]'::jsonb, 2, 'cografya'),
('Yükseltinin sıcaklığa etkisi nasıldır?', '["Yükseldikçe sıcaklık artar","Etkisi yoktur","Sadece kışın etkilidir","Yükseldikçe sıcaklık düşer"]'::jsonb, 3, 'cografya'),
('Bakının (yamaç yönünün) sıcaklığa etkisi nedir?', '["Güneşe bakan yamaç daha sıcaktır","Kuzey yamaç daha sıcaktır","Etkisi yoktur","Yalnız yağışı etkiler"]'::jsonb, 0, 'cografya'),
('Türkiye''de güney yamaçların tarımda erken ürün vermesinin nedeni nedir?', '["Daha fazla yağış alması","Daha fazla güneş alması","Toprağının farklı olması","Rüzgâr almaması"]'::jsonb, 1, 'cografya'),
('Aynı dağda yükseldikçe bitki türlerinin değişmesine ne denir?', '["Yatay kuşaklanma","Enlem etkisi","Dikey kuşaklanma","Bakı etkisi"]'::jsonb, 2, 'cografya'),
('Orman üst sınırının yükseldikçe sona ermesinin nedeni nedir?', '["Toprağın bitmesi","Yağışın artması","Rüzgârın kesilmesi","Sıcaklığın yetersiz kalması"]'::jsonb, 3, 'cografya'),
('Ekvator''dan kutuplara gidildikçe bitki örtüsü nasıl değişir?', '["Ormandan tundraya doğru","Tundradan ormana doğru","Hep aynı kalır","Çölden ormana doğru"]'::jsonb, 0, 'cografya'),
('Bir bölgede tarım ürünü çeşitliliğinin fazla olması neyi gösterir?', '["Nüfus yoğunluğunu","İklim çeşitliliğini","Sanayi gelişimini","Ulaşım kolaylığını"]'::jsonb, 1, 'cografya'),
('Türkiye''de hemen her tarım ürününün yetişebilmesinin nedeni nedir?', '["Toprağın tek tip olması","Yüzölçümünün büyüklüğü","İklim ve yer şekli çeşitliliği","Nüfusun fazlalığı"]'::jsonb, 2, 'cografya'),
('Türkiye''de tarımsal üretimin yıllara göre değişmesinin başlıca nedeni nedir?', '["Nüfus değişimi","Döviz kuru","Ulaşım sorunu","Yağış düzensizliği"]'::jsonb, 3, 'cografya'),
('Sulama olanağının artması tarımda neyi sağlar?', '["Üretimin iklime bağımlılığını azaltır","Ekili alanı küçültür","Verimi düşürür","Ürün çeşidini azaltır"]'::jsonb, 0, 'cografya'),
('Bir tarım ürününün ''ihraç ürünü'' olması ne demektir?', '["Yalnız iç tüketimde kullanılması","Yurt dışına satılması","İthal edilmesi","Üretilmemesi"]'::jsonb, 1, 'cografya'),
('Coğrafi işaret tescili neyi korur?', '["Fabrikanın markasını","Buluş hakkını","Ürünün yöresel kimliğini","Telif hakkını"]'::jsonb, 2, 'cografya'),
('Malatya kayısısı ve Antep baklavası hangi koruma kapsamındadır?', '["Patent","Telif","Marka tescili yok","Coğrafi işaret"]'::jsonb, 3, 'cografya')
on conflict (soru) do nothing;
