-- Genel kültür kalite revizyonu.
-- SORUN: genel_kultur kategorisinde "kültür" sayılamayacak kadar basit sorular
-- vardı (birim/sayma ezberi, hayvan yavruları, gündelik eşya tanımları, plaka
-- kodları, temel geometri). Canlı testte kategori seviyesiz görünüyordu.
-- ÇÖZÜM: bu sorular pasife alınır (SİLİNMEZ; geçmiş maç kayıtları questions
-- satırına bağlıdır) ve yerine tarih, sanat, edebiyat, mitoloji, uluslararası
-- kurumlar, uygarlık mirası, bilim tarihi ve hukuk/ekonomi kavramlarından
-- oluşan 122 orta zorlukta soru eklenir.

-- 1) Aşırı basit 73 soruyu pasife al
update public.questions
   set aktif = false
 where kategori = 'genel_kultur'
   and id in (
     'ef8c53ed-8198-42f3-a4a1-8d76f5135caf',
     'b0ace350-ed5a-4a48-b9d3-fc2cf5ab5716',
     'b6ca087b-983c-40dd-985c-a3ec7fd29c00',
     'ba01eb56-54ea-4514-a945-12b629abe7e5',
     '417f6698-d959-4302-aed9-d2cf05966e7b',
     '5bc854df-8ed7-4048-b979-e7305304e1c4',
     '5b780ada-0273-4d0e-b7c3-b08ad027e70a',
     '801c77f5-6a65-4874-80b9-5f77bda14f72',
     '4bbe07a5-eac7-462a-b755-567874f4994a',
     'fb585d1e-df0c-4e34-9b84-112af3fe73ca',
     '25283020-5777-4abd-9e59-8f23b0997cfe',
     'a135a8a6-35ba-496b-a3a1-8e9229bb67e9',
     '8ca9b613-ba8a-4479-a202-5f865f7b3057',
     '67058e8a-864e-48f4-a2a0-9ec0275730d5',
     'a1196b11-a85d-4c89-b88a-65ce4bf3c491',
     '559d7c5c-6a0a-4dc9-bf37-ae4351637a7f',
     'dce86ca2-41ec-4af5-b352-922e5dd0058c',
     '6ce6868d-23b0-4769-9829-a2c3d592ea18',
     '7e4c07f2-4459-4fd3-b9df-27c363465350',
     '96404e34-f1a5-4383-8f57-1586db1a1170',
     '4a691eec-dca9-4a9e-87a8-d924cf7ef90d',
     'f1e123d2-165d-486a-81b8-ea09376038ea',
     '774d5fe0-7342-4c9b-ba1a-24bdc006ce17',
     '98ba7bf2-d7d2-4a82-975f-552f48dd8ef5',
     'bc5ea7e8-d788-464d-a484-f04e547ca8ac',
     '5fb47cff-0977-47c3-8700-4f98bf7e5f24',
     '85ddc75e-aba8-4061-9107-e033f34cf424',
     '1a987d79-d7a7-42ca-9da8-16f5fb2c521e',
     'c3db1c81-e5b6-4277-9a1d-61150dc23968',
     '3c5d79eb-78d9-4dae-891e-da89cab3ceee',
     'b888ca29-aff2-4217-b8d7-aab31a74865c',
     '87b0e4f6-a3dd-408f-a6ae-a21cb81b61af',
     'a681ebb3-4d61-4e53-a40e-2f35d7a67eba',
     '934497c1-6c51-4ba3-9dcf-8ed4fcd24460',
     'eced759d-a7e4-4b31-a7a7-aeaa99032f77',
     'a637277a-69b1-41c6-8c18-84719548cc05',
     'e47c6c1d-edc6-4fa3-ab4d-c4dbf8447482',
     '247ba7ac-3df0-44d3-8791-25155956fdeb',
     '64400a42-ec99-43e7-a6f3-e68778ecedb9',
     'ea648b8c-4593-4c7f-9aed-3a30d8db9939',
     'f86bf6bf-0f95-4d60-b7d8-c7a8ccfe3d5a',
     'a45ad954-bbe2-4116-b448-b23d05daaef8',
     'aac28d04-3f81-4c97-90bf-c6a308b23041',
     'ba5ddffd-dfd7-4094-a2ea-a568766f6266',
     '247da128-953f-44ca-936b-e297f318db4a',
     'fdce07bf-8dae-4c65-8fd8-9d8f18ab9769',
     '7eb035f6-239e-447f-b897-0467d17a81fd',
     'f1116c11-b3c3-4ed7-ac52-5dadba2d11f8',
     '83035925-d5ff-40f8-89f8-565b2f865eef',
     '0576f28b-5c52-480e-98c0-4bc795ec442d',
     '001cb5b3-5675-4449-a0bc-95678b020d36',
     '2ecaefe2-c1b7-477e-8ca8-78650054de59',
     'e238bd79-be8b-49f5-a8be-dc0f7299a009',
     '65be68a4-83ca-4423-afaa-2c97e39f9079',
     '37913024-331e-46ec-9a9a-fb9679ace2c5',
     'c0924bd4-084e-4a2f-a89e-66d790fa7a40',
     'd943b820-b8c3-48f1-aabb-d9a9df1f9a7a',
     'b97455ff-6e3c-4136-9580-f3c066e98329',
     '46a599d8-f5d0-4c62-8c6b-8142c46ef906',
     'a5078cd5-eed2-4370-aa2c-ba09ec61a3dd',
     '956b0dd9-0c96-4b64-bf42-4cef6db04b10',
     'ed7ea0b4-0aba-424b-9e5b-de505c0fe039',
     '89b33be1-3724-4341-89e1-ca8aeb796b2d',
     'baa14e0e-709e-4f86-9efb-920d127882c6',
     'da1b1452-a6be-4a88-b196-f51a2a5b4335',
     'fcdf0e88-3b11-4908-bfd9-f51f1b1adbc7',
     '40a05ce2-6975-40c8-9d3c-c0f73b76e8a5',
     'c90558a6-1f03-48c2-ac84-ecebe27636e8',
     '19b1de23-b9d1-4fa9-8cce-1f67a5453d1c',
     '6c707f76-f855-4767-a28a-3a3e32b2b10d',
     '48e6e43a-bbb4-4e17-8588-2a34e708d722',
     'c584d054-df00-407c-b59f-191ddff78bf0',
     '5dc33c3b-3c17-4c4b-b33e-391c18bfa58e'
   );

-- 2) Yeni genel kültür soruları (soru kolonu UNIQUE)
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Kavimler Göçü''nü başlatan kavim hangisidir?', '["Hunlar","Gotlar","Vandallar","Vikingler"]'::jsonb, 0, 'genel_kultur'),
('Rönesans hareketi ilk olarak hangi ülkede doğmuştur?', '["Fransa","İtalya","İngiltere","Hollanda"]'::jsonb, 1, 'genel_kultur'),
('Fransız İhtilali''nin üç temel sloganı hangisidir?', '["Barış, ekmek, toprak","Düzen, disiplin, güç","Özgürlük, eşitlik, kardeşlik","Bilim, sanat, ticaret"]'::jsonb, 2, 'genel_kultur'),
('Kanuni Sultan Süleyman''a Avrupa''da verilen unvan nedir?', '["Fatih Süleyman","Yavuz Süleyman","Gazi Süleyman","Muhteşem Süleyman"]'::jsonb, 3, 'genel_kultur'),
('Lozan Antlaşması hangi ülkede imzalanmıştır?', '["İsviçre","Fransa","İtalya","Belçika"]'::jsonb, 0, 'genel_kultur'),
('Dünyanın çevresini dolaşan ilk sefere kim önderlik etmiştir?', '["Kristof Kolomb","Macellan","Vasco da Gama","James Cook"]'::jsonb, 1, 'genel_kultur'),
('Çivi yazısını bulan uygarlık hangisidir?', '["Mısırlılar","Fenikeliler","Sümerler","Lidyalılar"]'::jsonb, 2, 'genel_kultur'),
('Alfabeyi geliştirerek yaygınlaştıran uygarlık hangisidir?', '["Sümerler","Urartular","İskitler","Fenikeliler"]'::jsonb, 3, 'genel_kultur'),
('Parayı ilk kez kullandığı kabul edilen uygarlık hangisidir?', '["Lidyalılar","Frigler","Hititler","Persler"]'::jsonb, 0, 'genel_kultur'),
('Orhun Yazıtları hangi alfabeyle yazılmıştır?', '["Uygur alfabesi","Göktürk alfabesi","Arap alfabesi","Latin alfabesi"]'::jsonb, 1, 'genel_kultur'),
('Osmanlı Devleti''nin ilk resmî gazetesi hangisidir?', '["Tercüman-ı Ahval","Ceride-i Havadis","Takvim-i Vekayi","Tasvir-i Efkâr"]'::jsonb, 2, 'genel_kultur'),
('Harf İnkılabı hangi yıl gerçekleştirilmiştir?', '["1924","1926","1934","1928"]'::jsonb, 3, 'genel_kultur'),
('Mısır hiyerogliflerini çözen bilim insanı kimdir?', '["Champollion","Schliemann","Napolyon","Herodot"]'::jsonb, 0, 'genel_kultur'),
('Roma İmparatorluğu''nu doğu ve batı olarak ayıran imparator kimdir?', '["Konstantin","Theodosius","Sezar","Neron"]'::jsonb, 1, 'genel_kultur'),
('Osmanlı''da devşirme sistemiyle oluşturulan piyade ordusu hangisidir?', '["Sipahiler","Akıncılar","Yeniçeri Ocağı","Levent Ocağı"]'::jsonb, 2, 'genel_kultur'),
('Tarihte ilk yazılı antlaşma olarak kabul edilen belge hangisidir?', '["Magna Carta","Vestfalya Antlaşması","Milano Fermanı","Kadeş Antlaşması"]'::jsonb, 3, 'genel_kultur'),
('Rus Çarlığı''nı imparatorluğa dönüştüren hükümdar kimdir?', '["I. Petro","II. Katerina","IV. İvan","I. Aleksandr"]'::jsonb, 0, 'genel_kultur'),
('Hindistan''ın bağımsızlık hareketine önderlik eden lider kimdir?', '["Nehru","Mahatma Gandhi","Sukarno","Nasır"]'::jsonb, 1, 'genel_kultur'),
('Danişmentliler Anadolu''nun hangi bölgesinde kurulmuştur?', '["Ege","Akdeniz","Orta Karadeniz","Trakya"]'::jsonb, 2, 'genel_kultur'),
('Guernica adlı tablonun ressamı kimdir?', '["Salvador Dali","Henri Matisse","Joan Miro","Pablo Picasso"]'::jsonb, 3, 'genel_kultur'),
('Yıldızlı Gece tablosu hangi ressama aittir?', '["Vincent van Gogh","Claude Monet","Paul Cezanne","Edvard Munch"]'::jsonb, 0, 'genel_kultur'),
('Çığlık adlı tablo hangi sanatçıya aittir?', '["Egon Schiele","Edvard Munch","Gustav Klimt","Vincent van Gogh"]'::jsonb, 1, 'genel_kultur'),
('Selimiye Camii''nin mimarı kimdir?', '["Mimar Kemalettin","Sedefkâr Mehmed Ağa","Mimar Sinan","Mimar Hayreddin"]'::jsonb, 2, 'genel_kultur'),
('Hat sanatı hangi alanda icra edilir?', '["Halı dokuma","Çini yapımı","Taş işleme","Güzel yazı"]'::jsonb, 3, 'genel_kultur'),
('Karagöz ve Hacivat hangi geleneksel sanat türüne aittir?', '["Gölge oyunu","Kukla tiyatrosu","Meddahlık","Ortaoyunu"]'::jsonb, 0, 'genel_kultur'),
('Bir operada tek kişinin söylediği parçaya ne ad verilir?', '["Koro","Arya","Uvertür","Resitatif"]'::jsonb, 1, 'genel_kultur'),
('Beşinci Senfoni hangi bestecinin eseridir?', '["Mozart","Bach","Beethoven","Çaykovski"]'::jsonb, 2, 'genel_kultur'),
('Türk müziğinde makam kavramı neyi ifade eder?', '["Şarkı sözünü","Çalgı türünü","Sahne düzenini","Ezgisel dizi düzenini"]'::jsonb, 3, 'genel_kultur'),
('Mevlevîlikte dönerek yapılan törene ne ad verilir?', '["Sema","Semah","Zikir","Ayin"]'::jsonb, 0, 'genel_kultur'),
('Sefiller romanı hangi yazara aittir?', '["Emile Zola","Victor Hugo","Balzac","Stendhal"]'::jsonb, 1, 'genel_kultur'),
('Don Kişot hangi ülkenin edebiyatının başyapıtıdır?', '["İtalya","Portekiz","İspanya","Fransa"]'::jsonb, 2, 'genel_kultur'),
('Şehnâme adlı destanın şairi kimdir?', '["Sadi","Hafız","Ömer Hayyam","Firdevsî"]'::jsonb, 3, 'genel_kultur'),
('Safahat adlı eserin şairi kimdir?', '["Mehmet Akif Ersoy","Tevfik Fikret","Yahya Kemal","Namık Kemal"]'::jsonb, 0, 'genel_kultur'),
('Han Duvarları şiiri hangi şaire aittir?', '["Orhan Veli","Faruk Nafiz Çamlıbel","Cahit Sıtkı","Necip Fazıl"]'::jsonb, 1, 'genel_kultur'),
('Divan edebiyatında beyitlerle yazılan uzun anlatı türüne ne denir?', '["Gazel","Kaside","Mesnevi","Rubai"]'::jsonb, 2, 'genel_kultur'),
('Türk halk edebiyatında saz eşliğinde şiir söyleyenlere ne ad verilir?', '["Meddah","Ozanbaşı","Kıssahan","Âşık"]'::jsonb, 3, 'genel_kultur'),
('Mesnevî adlı eserin yazarı kimdir?', '["Mevlânâ","Yunus Emre","Hacı Bektaş Veli","Ahmet Yesevi"]'::jsonb, 0, 'genel_kultur'),
('Hamlet oyununun kahramanı hangi ülkenin prensidir?', '["İskoçya","Danimarka","Norveç","İsveç"]'::jsonb, 1, 'genel_kultur'),
('Otobiyografi türü neyi anlatır?', '["Başkasının yaşamını","Hayalî bir olayı","Yazarın kendi yaşamını","Bilimsel bir konuyu"]'::jsonb, 2, 'genel_kultur'),
('Roma mitolojisinde savaş tanrısı kimdir?', '["Jüpiter","Merkür","Neptün","Mars"]'::jsonb, 3, 'genel_kultur'),
('Mitolojiye göre Aşil''in zayıf noktası neresidir?', '["Topuğu","Kalbi","Eli","Gözü"]'::jsonb, 0, 'genel_kultur'),
('NATO''nun karargâhı hangi şehirdedir?', '["Lahey","Brüksel","Strazburg","Londra"]'::jsonb, 1, 'genel_kultur'),
('UNESCO hangi alanlarda çalışan bir kuruluştur?', '["Sağlık ve ilaç","Ticaret ve gümrük","Eğitim, bilim ve kültür","Enerji ve maden"]'::jsonb, 2, 'genel_kultur'),
('Kızılhaç örgütünün kurucusu kimdir?', '["Florence Nightingale","Alfred Nobel","Albert Schweitzer","Henry Dunant"]'::jsonb, 3, 'genel_kultur'),
('Nobel Ödülleri kimin vasiyetiyle kurulmuştur?', '["Alfred Nobel","Andrew Carnegie","Joseph Pulitzer","Henry Ford"]'::jsonb, 0, 'genel_kultur'),
('Uluslararası Adalet Divanı hangi şehirde bulunur?', '["Cenevre","Lahey","Brüksel","Roma"]'::jsonb, 1, 'genel_kultur'),
('Modern olimpiyat oyunlarının ilki hangi şehirde yapılmıştır?', '["Paris","Londra","Atina","Roma"]'::jsonb, 2, 'genel_kultur'),
('Interpol hangi alanda faaliyet gösterir?', '["Sağlık denetimi","Çevre koruma","Eğitim politikası","Uluslararası polis işbirliği"]'::jsonb, 3, 'genel_kultur'),
('Oscar ödülleri hangi sanat dalında verilir?', '["Sinema","Müzik","Edebiyat","Resim"]'::jsonb, 0, 'genel_kultur'),
('Machu Picchu hangi uygarlıktan kalmadır?', '["Maya","İnka","Aztek","Olmek"]'::jsonb, 1, 'genel_kultur'),
('Petra antik kenti hangi ülkede bulunur?', '["Mısır","Lübnan","Ürdün","Suriye"]'::jsonb, 2, 'genel_kultur'),
('Kolezyum hangi şehirde yer alır?', '["Atina","Napoli","Milano","Roma"]'::jsonb, 3, 'genel_kultur'),
('Nemrut Dağı''ndaki dev heykeller hangi krallıktan kalmadır?', '["Kommagene","Urartu","Frigya","Likya"]'::jsonb, 0, 'genel_kultur'),
('Ayasofya hangi dönemde inşa edilmiştir?', '["Osmanlı","Doğu Roma (Bizans)","Selçuklu","Roma Cumhuriyeti"]'::jsonb, 1, 'genel_kultur'),
('Kapadokya''daki peribacaları hangi doğal süreçle oluşmuştur?', '["Deprem","Buzul hareketi","Aşınma (erozyon)","Volkanik patlama"]'::jsonb, 2, 'genel_kultur'),
('Vikingler hangi bölgede yaşamıştır?', '["Balkanlar","İberya","Kafkasya","İskandinavya"]'::jsonb, 3, 'genel_kultur'),
('Flamenko dansı hangi ülkeye özgüdür?', '["İspanya","Portekiz","İtalya","Meksika"]'::jsonb, 0, 'genel_kultur'),
('Nevruz hangi mevsimin başlangıcı olarak kutlanır?', '["Yaz","İlkbahar","Sonbahar","Kış"]'::jsonb, 1, 'genel_kultur'),
('Kütleçekim yasasını formüle eden bilim insanı kimdir?', '["Galileo Galilei","Kepler","Isaac Newton","Kopernik"]'::jsonb, 2, 'genel_kultur'),
('Türlerin Kökeni adlı eserde evrim kuramını açıklayan kimdir?', '["Lamarck","Mendel","Linnaeus","Charles Darwin"]'::jsonb, 3, 'genel_kultur'),
('İki farklı bilim dalında Nobel Ödülü kazanan kişi kimdir?', '["Marie Curie","Albert Einstein","Niels Bohr","Ernest Rutherford"]'::jsonb, 0, 'genel_kultur'),
('Cebir biliminin kurucusu sayılan bilgin kimdir?', '["Farabi","Harezmî","Biruni","İbn Rüşd"]'::jsonb, 1, 'genel_kultur'),
('El-Kanun fi''t-Tıb adlı tıp eserinin yazarı kimdir?', '["Razi","İbn Haldun","İbn Sina","Cabir bin Hayyan"]'::jsonb, 2, 'genel_kultur'),
('Optik alanındaki çalışmalarıyla tanınan İslam bilgini kimdir?', '["Uluğ Bey","Ali Kuşçu","Piri Reis","İbn-i Heysem"]'::jsonb, 3, 'genel_kultur'),
('Mukaddime adlı eseriyle tarih felsefesinin öncüsü sayılan kimdir?', '["İbn Haldun","Katip Çelebi","Evliya Çelebi","Naima"]'::jsonb, 0, 'genel_kultur'),
('Wright Kardeşler hangi alanda öncü olmuştur?', '["Otomobil","Motorlu uçuş","Telgraf","Denizaltı"]'::jsonb, 1, 'genel_kultur'),
('Dünya''nın Güneş çevresinde döndüğünü ileri süren bilim insanı kimdir?', '["Batlamyus","Aristo","Kopernik","Öklid"]'::jsonb, 2, 'genel_kultur'),
('Bir devletin temel yasasına ne ad verilir?', '["Yönetmelik","Tüzük","Genelge","Anayasa"]'::jsonb, 3, 'genel_kultur'),
('Kuvvetler ayrılığı ilkesi neyi ifade eder?', '["Yasama, yürütme, yargı ayrılığı","Ordunun bağımsızlığını","Yerel yönetim yetkisini","Basın özgürlüğünü"]'::jsonb, 0, 'genel_kultur'),
('Referandum ne anlama gelir?', '["Meclis kararı","Halk oylaması","Mahkeme hükmü","Kanun tasarısı"]'::jsonb, 1, 'genel_kultur'),
('Veto yetkisi neyi ifade eder?', '["Bir kararı onaylama","Oy kullanma hakkı","Bir kararı geri çevirme","Aday gösterme"]'::jsonb, 2, 'genel_kultur'),
('Diplomaside büyükelçi kimdir?', '["Ticaret danışmanı","Askerî ateşe","Konsolosluk memuru","Devletin en üst düzey temsilcisi"]'::jsonb, 3, 'genel_kultur'),
('Ambargo kavramı neyi anlatır?', '["Ticaretin kısıtlanması","Vergi indirimi","Sınırın kapanması","Para basılması"]'::jsonb, 0, 'genel_kultur'),
('Enflasyon neyi ifade eder?', '["Üretimin azalması","Genel fiyat düzeyinin artması","İşsizliğin artması","Faizin düşmesi"]'::jsonb, 1, 'genel_kultur'),
('Bütçe kavramı neyi ifade eder?', '["Borç listesi","Vergi oranı","Gelir ve gider planı","Nüfus sayımı"]'::jsonb, 2, 'genel_kultur'),
('Sivil toplum kuruluşu ne demektir?', '["Kamu kurumu","Ticari şirket","Siyasi parti","Devlet dışı gönüllü örgüt"]'::jsonb, 3, 'genel_kultur'),
('Vestfalya Antlaşması hangi savaşı sona erdirmiştir?', '["Otuz Yıl Savaşları","Yüz Yıl Savaşları","Napolyon Savaşları","Kırım Savaşı"]'::jsonb, 0, 'genel_kultur'),
('Osmanlı''da ilk kez Avrupa''ya sürekli elçi gönderen padişah kimdir?', '["II. Mahmud","III. Selim","I. Abdülhamid","III. Ahmed"]'::jsonb, 1, 'genel_kultur'),
('İstanbul''daki Kapalıçarşı hangi padişah döneminde kurulmuştur?', '["Kanuni","Yavuz Selim","Fatih Sultan Mehmed","II. Bayezid"]'::jsonb, 2, 'genel_kultur'),
('Türkiye''de Medeni Kanun hangi ülkeden alınarak kabul edilmiştir?', '["Fransa","İtalya","Almanya","İsviçre"]'::jsonb, 3, 'genel_kultur'),
('Kurtuluş Savaşı''nda Sakarya Meydan Muharebesi''nin sonucu nedir?', '["Türk ordusunun savunma zaferi","Yunan ilerleyişi","Ateşkes reddi","İşgalin başlaması"]'::jsonb, 0, 'genel_kultur'),
('Milli Mücadele''de Amasya Genelgesi neyi duyurmuştur?', '["Saltanatın kaldırıldığını","Milletin bağımsızlığını sağlayacağını","Cumhuriyetin ilanını","Halifeliğin bittiğini"]'::jsonb, 1, 'genel_kultur'),
('Aydınlanma Çağı düşünürlerinden Toplum Sözleşmesi''nin yazarı kimdir?', '["Voltaire","Montesquieu","Jean-Jacques Rousseau","Diderot"]'::jsonb, 2, 'genel_kultur'),
('Kanunların Ruhu adlı eserde kuvvetler ayrılığını savunan düşünür kimdir?', '["John Locke","Rousseau","Thomas Hobbes","Montesquieu"]'::jsonb, 3, 'genel_kultur'),
('Devlet adlı eserin yazarı olan filozof kimdir?', '["Platon","Aristoteles","Sokrates","Epiktetos"]'::jsonb, 0, 'genel_kultur'),
('Ütopya adlı eseri kaleme alan yazar kimdir?', '["Francis Bacon","Thomas More","Machiavelli","Erasmus"]'::jsonb, 1, 'genel_kultur'),
('Divanü Lügati''t-Türk adlı sözlüğün yazarı kimdir?', '["Yusuf Has Hacip","Ali Şir Nevai","Kaşgarlı Mahmud","Edip Ahmet"]'::jsonb, 2, 'genel_kultur'),
('Kutadgu Bilig adlı eserin yazarı kimdir?', '["Kaşgarlı Mahmud","Ahmet Yesevi","Edip Ahmet Yükneki","Yusuf Has Hacip"]'::jsonb, 3, 'genel_kultur'),
('Seyahatname adlı gezi eserinin yazarı kimdir?', '["Evliya Çelebi","Katip Çelebi","Piri Reis","Naima"]'::jsonb, 0, 'genel_kultur'),
('Kitab-ı Bahriye adlı denizcilik eseri kime aittir?', '["Seydi Ali Reis","Piri Reis","Barbaros Hayreddin","Turgut Reis"]'::jsonb, 1, 'genel_kultur'),
('İlk Türkçe roman sayılan Taaşşuk-ı Talat ve Fitnat''ın yazarı kimdir?', '["Namık Kemal","Ahmet Mithat","Şemsettin Sami","Recaizade Ekrem"]'::jsonb, 2, 'genel_kultur'),
('Servet-i Fünun hangi alanda bir edebiyat topluluğudur?', '["Fransız edebiyatı","Rus edebiyatı","İran edebiyatı","Türk edebiyatı"]'::jsonb, 3, 'genel_kultur'),
('Tutunamayanlar romanı hangi yazara aittir?', '["Oğuz Atay","Yusuf Atılgan","Bilge Karasu","Adalet Ağaoğlu"]'::jsonb, 0, 'genel_kultur'),
('1984 adlı distopik romanın yazarı kimdir?', '["Aldous Huxley","George Orwell","Ray Bradbury","Franz Kafka"]'::jsonb, 1, 'genel_kultur'),
('Dönüşüm adlı uzun öykünün yazarı kimdir?', '["Albert Camus","Thomas Mann","Franz Kafka","Hermann Hesse"]'::jsonb, 2, 'genel_kultur'),
('İlahi Komedya adlı eserin şairi kimdir?', '["Petrarca","Boccaccio","Vergilius","Dante"]'::jsonb, 3, 'genel_kultur'),
('Odysseia destanının kahramanı kimdir?', '["Odysseus","Akhilleus","Hektor","Agamemnon"]'::jsonb, 0, 'genel_kultur'),
('Mısır mitolojisinde ölüler diyarının tanrısı kimdir?', '["Ra","Osiris","Horus","Anubis"]'::jsonb, 1, 'genel_kultur'),
('Yunan mitolojisinde insanlara ateşi veren kahraman kimdir?', '["Herakles","İkarus","Prometheus","Tantalos"]'::jsonb, 2, 'genel_kultur'),
('Mitolojide balmumu kanatlarıyla güneşe fazla yaklaşan kimdir?', '["Prometheus","Theseus","Orpheus","İkarus"]'::jsonb, 3, 'genel_kultur'),
('Uluslararası Para Fonu''nun kısaltması nedir?', '["IMF","WTO","OECD","WHO"]'::jsonb, 0, 'genel_kultur'),
('Avrupa İnsan Hakları Mahkemesi hangi şehirdedir?', '["Lahey","Strazburg","Brüksel","Cenevre"]'::jsonb, 1, 'genel_kultur'),
('İnsan Hakları Evrensel Bildirgesi hangi kuruluş tarafından kabul edilmiştir?', '["NATO","Avrupa Birliği","Birleşmiş Milletler","UNESCO"]'::jsonb, 2, 'genel_kultur'),
('Bir ülkenin sınırları içindeki yabancı temsilciliğe ne ad verilir?', '["Valilik","Kaymakamlık","Belediye","Elçilik"]'::jsonb, 3, 'genel_kultur'),
('Mutlak monarşi ile meşruti monarşi arasındaki temel fark nedir?', '["Anayasa ve meclisin varlığı","Hükümdarın yaşı","Ülkenin büyüklüğü","Ordunun gücü"]'::jsonb, 0, 'genel_kultur'),
('Laiklik ilkesi neyi ifade eder?', '["Dinin yasaklanması","Din ve devlet işlerinin ayrılığı","Tek partili yönetim","Halk oylaması"]'::jsonb, 1, 'genel_kultur'),
('Chichen Itza kalıntıları hangi uygarlığa aittir?', '["İnka","Aztek","Maya","Toltek"]'::jsonb, 2, 'genel_kultur'),
('Stonehenge hangi ülkede bulunur?', '["İrlanda","Fransa","Danimarka","İngiltere"]'::jsonb, 3, 'genel_kultur'),
('Kızıl Meydan hangi şehirde yer alır?', '["Moskova","Kiev","Varşova","Prag"]'::jsonb, 0, 'genel_kultur'),
('Çin Seddi hangi amaçla inşa edilmiştir?', '["Ticaret vergisi almak","Kuzeyden gelen akınlara karşı","Su taşımak","Tapınak yapmak"]'::jsonb, 1, 'genel_kultur'),
('Aya İrini kilisesi hangi şehirde bulunur?', '["İzmir","Antakya","İstanbul","Trabzon"]'::jsonb, 2, 'genel_kultur'),
('Divriği Ulu Camii hangi ilimizdedir?', '["Erzurum","Kayseri","Malatya","Sivas"]'::jsonb, 3, 'genel_kultur'),
('Safranbolu evleri hangi ilimizin sınırlarındadır?', '["Karabük","Kastamonu","Bartın","Zonguldak"]'::jsonb, 0, 'genel_kultur'),
('Hattuşa antik kenti hangi uygarlığın başkentiydi?', '["Urartu","Hitit","Frig","Lidya"]'::jsonb, 1, 'genel_kultur'),
('Türk kahvesi hangi kuruluşun kültür mirası listesindedir?', '["FIFA","OECD","UNESCO","NATO"]'::jsonb, 2, 'genel_kultur'),
('Geleneksel Türk gölge oyununda Hacivat''ın konuşma biçimi nasıldır?', '["Kaba ve halk ağzı","Sessiz","Şarkılı","Ağdalı ve kitabi"]'::jsonb, 3, 'genel_kultur'),
('Buluş yapan kişiye tanınan yasal korumaya ne ad verilir?', '["Patent","Lisans","Ruhsat","Sertifika"]'::jsonb, 0, 'genel_kultur'),
('Arkeoloji bilimi neyi inceler?', '["Yıldızları","Geçmişin maddi kalıntılarını","Kayaçları","Dilleri"]'::jsonb, 1, 'genel_kultur'),
('Antropoloji bilimi hangi konuyu araştırır?', '["Bitkileri","Denizleri","İnsanı ve kültürlerini","Metalleri"]'::jsonb, 2, 'genel_kultur'),
('Etimoloji hangi konuyla ilgilenir?', '["Cümle yapısıyla","Yazı sanatıyla","Şiir ölçüsüyle","Kelimelerin kökeniyle"]'::jsonb, 3, 'genel_kultur'),
('Bir yazının sonunda yer alan kaynak listesine ne ad verilir?', '["Kaynakça","Dizin","Önsöz","Özet"]'::jsonb, 0, 'genel_kultur'),
('Ansiklopedi ile sözlük arasındaki temel fark nedir?', '["Sözlüğün resimli olması","Ansiklopedinin konuyu açıklaması","Ansiklopedinin küçük olması","Sözlüğün yıllık çıkması"]'::jsonb, 1, 'genel_kultur')
on conflict (soru) do nothing;
