-- Soru havuzu genişletme — Parti 5: Karışık (orta-zor)
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Osmanlı''da padişah çocuklarının eğitiminden sorumlu hocalara ne denirdi?', '["Lala","Vezir","Kadı","Defterdar"]'::jsonb, 0, 'tarih'),
('Osmanlı donanmasının yakıldığı 1571 deniz savaşı hangisidir?', '["İnebahtı","Preveze","Çeşme","Navarin"]'::jsonb, 0, 'tarih'),
('Kanuni Sultan Süleyman hangi sefer sırasında vefat etmiştir?', '["Zigetvar","Mohaç","Viyana","Belgrad"]'::jsonb, 0, 'tarih'),
('Mohaç Meydan Savaşı hangi ülke topraklarında yapılmıştır?', '["Macaristan","Avusturya","Sırbistan","Romanya"]'::jsonb, 0, 'tarih'),
('Osmanlı''da yeniçerileri kaldıran padişah kimdir?', '["II. Mahmud","III. Selim","II. Abdülhamid","Abdülmecid"]'::jsonb, 0, 'tarih'),
('Yeniçeri Ocağı''nın kaldırılması tarihte ne olarak anılır?', '["Vaka-i Hayriye","Tanzimat","Islahat","31 Mart Vakası"]'::jsonb, 0, 'tarih'),
('İlk Osmanlı padişahı Osman Bey''in babası kimdir?', '["Ertuğrul Gazi","Süleyman Şah","Orhan Bey","Dündar Bey"]'::jsonb, 0, 'tarih'),
('Ankara Savaşı''nda Yıldırım Bayezid kime yenilmiştir?', '["Timur","Cengiz Han","Şah İsmail","Uzun Hasan"]'::jsonb, 0, 'tarih'),
('Ankara Savaşı sonrası Osmanlı''da yaşanan taht kavgası dönemi nedir?', '["Fetret Devri","Lale Devri","Tanzimat","Duraklama"]'::jsonb, 0, 'tarih'),
('Lale Devri hangi padişah dönemindedir?', '["III. Ahmed","IV. Murad","II. Mustafa","I. Mahmud"]'::jsonb, 0, 'tarih'),
('Osmanlı''ya matbaayı resmi olarak getiren kişi kimdir?', '["İbrahim Müteferrika","Katip Çelebi","Evliya Çelebi","Takiyüddin"]'::jsonb, 0, 'tarih'),
('Seyahatname''nin yazarı kimdir?', '["Evliya Çelebi","Katip Çelebi","Piri Reis","Naima"]'::jsonb, 0, 'tarih'),
('Hicret hangi yılda gerçekleşmiştir?', '["622","610","632","570"]'::jsonb, 0, 'tarih'),
('Endülüs Emevi Devleti bugünkü hangi ülkede kurulmuştur?', '["İspanya","Fas","Mısır","İtalya"]'::jsonb, 0, 'tarih'),
('Yüzyıl Savaşları hangi iki ülke arasında yapılmıştır?', '["İngiltere ve Fransa","Almanya ve Fransa","İspanya ve Portekiz","İngiltere ve İspanya"]'::jsonb, 0, 'tarih'),
('Jan Dark hangi ülkenin milli kahramanıdır?', '["Fransa","İngiltere","Belçika","İtalya"]'::jsonb, 0, 'tarih'),
('Rönesans hangi ülkede başlamıştır?', '["İtalya","Fransa","İngiltere","Almanya"]'::jsonb, 0, 'tarih'),
('Reform hareketini başlatan din adamı kimdir?', '["Martin Luther","Calvin","Zwingli","Erasmus"]'::jsonb, 0, 'tarih'),
('Sanayi Devrimi hangi ülkede başlamıştır?', '["İngiltere","Fransa","Almanya","ABD"]'::jsonb, 0, 'tarih'),
('Buhar makinesini geliştirerek sanayiye uygulayan mucit kimdir?', '["James Watt","Stephenson","Fulton","Newcomen"]'::jsonb, 0, 'tarih'),
('II. Dünya Savaşı''nda Normandiya Çıkarması hangi yıl yapılmıştır?', '["1944","1943","1945","1942"]'::jsonb, 0, 'tarih'),
('Hiroşima''ya atom bombası hangi yıl atılmıştır?', '["1945","1944","1946","1943"]'::jsonb, 0, 'tarih'),
('Soğuk Savaş hangi iki süper güç arasındaydı?', '["ABD ve SSCB","ABD ve Çin","İngiltere ve SSCB","Almanya ve ABD"]'::jsonb, 0, 'tarih'),
('Küba Krizi hangi yılda yaşanmıştır?', '["1962","1959","1968","1956"]'::jsonb, 0, 'tarih'),
('Türkiye''de çok partili hayata kesin geçiş hangi seçimle olmuştur?', '["1950","1946","1923","1960"]'::jsonb, 0, 'tarih'),
('Türkiye''nin ilk cumhurbaşkanı kimdir?', '["Mustafa Kemal Atatürk","İsmet İnönü","Celal Bayar","Fevzi Çakmak"]'::jsonb, 0, 'tarih'),
('Türkiye''nin ikinci cumhurbaşkanı kimdir?', '["İsmet İnönü","Celal Bayar","Cemal Gürsel","Adnan Menderes"]'::jsonb, 0, 'tarih'),
('Kafkasya''da Türkiye''ye komşu olan ülkelerden biri hangisidir?', '["Gürcistan","Kazakistan","Türkmenistan","Özbekistan"]'::jsonb, 0, 'cografya'),
('Dünyanın en uzun sıradağları hangisidir?', '["And Dağları","Himalayalar","Alpler","Kayalık Dağlar"]'::jsonb, 0, 'cografya'),
('Dünyanın en büyük yağmur ormanı hangisidir?', '["Amazon","Kongo","Borneo","Daintree"]'::jsonb, 0, 'cografya'),
('Victoria Şelalesi hangi kıtadadır?', '["Afrika","Güney Amerika","Asya","Avustralya"]'::jsonb, 0, 'cografya'),
('Niagara Şelalesi hangi iki ülkenin sınırındadır?', '["ABD ve Kanada","ABD ve Meksika","Kanada ve Grönland","ABD ve Küba"]'::jsonb, 0, 'cografya'),
('Dünyanın en tuzlu su kütlelerinden biri olan Lut Gölü nerededir?', '["Ürdün-İsrail sınırı","Mısır","Türkiye","Suudi Arabistan"]'::jsonb, 0, 'cografya'),
('Bağdat hangi nehrin kıyısındadır?', '["Dicle","Fırat","Nil","Asi"]'::jsonb, 0, 'cografya'),
('Londra hangi nehrin kıyısındadır?', '["Thames","Sen","Ren","Tuna"]'::jsonb, 0, 'cografya'),
('Paris hangi nehrin kıyısındadır?', '["Sen","Thames","Loire","Ron"]'::jsonb, 0, 'cografya'),
('Tuna Nehri hangi denize dökülür?', '["Karadeniz","Akdeniz","Baltık","Adriyatik"]'::jsonb, 0, 'cografya'),
('Volga Nehri hangi denize dökülür?', '["Hazar","Karadeniz","Baltık","Aral"]'::jsonb, 0, 'cografya'),
('Türkiye''nin Akdeniz''e dökülen önemli nehri hangisidir?', '["Seyhan","Kızılırmak","Sakarya","Çoruh"]'::jsonb, 0, 'cografya'),
('Çoruh Nehri hangi ülke üzerinden denize ulaşır?', '["Gürcistan","Ermenistan","İran","Azerbaycan"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en büyük adası hangisidir?', '["Gökçeada","Bozcaada","Marmara Adası","Büyükada"]'::jsonb, 0, 'cografya'),
('İzlanda''nın başkenti neresidir?', '["Reykjavik","Oslo","Helsinki","Kopenhag"]'::jsonb, 0, 'cografya'),
('Yeni Zelanda''nın başkenti neresidir?', '["Wellington","Auckland","Christchurch","Sidney"]'::jsonb, 0, 'cografya'),
('Güney Kore''nin başkenti neresidir?', '["Seul","Busan","Pyongyang","Incheon"]'::jsonb, 0, 'cografya'),
('Arjantin''in başkenti neresidir?', '["Buenos Aires","Santiago","Lima","Montevideo"]'::jsonb, 0, 'cografya'),
('Fas''ın başkenti neresidir?', '["Rabat","Kazablanka","Marakeş","Tanca"]'::jsonb, 0, 'cografya'),
('Kenya''nın başkenti neresidir?', '["Nairobi","Kampala","Addis Ababa","Dar es Salaam"]'::jsonb, 0, 'cografya'),
('Tayland''ın başkenti neresidir?', '["Bangkok","Hanoi","Manila","Cakarta"]'::jsonb, 0, 'cografya'),
('Endonezya''nın başkenti neresidir?', '["Cakarta","Bangkok","Manila","Kuala Lumpur"]'::jsonb, 0, 'cografya'),
('Portekiz''in başkenti neresidir?', '["Lizbon","Porto","Madrid","Sevilla"]'::jsonb, 0, 'cografya'),
('İsveç''in başkenti neresidir?', '["Stockholm","Oslo","Helsinki","Kopenhag"]'::jsonb, 0, 'cografya'),
('Finlandiya''nın başkenti neresidir?', '["Helsinki","Stockholm","Oslo","Tallinn"]'::jsonb, 0, 'cografya'),
('Polonya''nın başkenti neresidir?', '["Varşova","Krakov","Prag","Budapeşte"]'::jsonb, 0, 'cografya'),
('Macaristan''ın başkenti neresidir?', '["Budapeşte","Bükreş","Prag","Viyana"]'::jsonb, 0, 'cografya'),
('Çekya''nın başkenti neresidir?', '["Prag","Bratislava","Budapeşte","Viyana"]'::jsonb, 0, 'cografya'),
('Avusturya''nın başkenti neresidir?', '["Viyana","Zürih","Münih","Salzburg"]'::jsonb, 0, 'cografya'),
('Belçika''nın başkenti neresidir?', '["Brüksel","Amsterdam","Anvers","Lüksemburg"]'::jsonb, 0, 'cografya'),
('Ukrayna''nın başkenti neresidir?', '["Kiev","Minsk","Odessa","Harkov"]'::jsonb, 0, 'cografya'),
('Sesin sudaki hızı havadakine göre nasıldır?', '["Daha hızlı","Daha yavaş","Aynı","Su sesi iletmez"]'::jsonb, 0, 'bilim'),
('Mutlak sıfır kaç santigrat derecedir?', '["-273","-100","-200","-300"]'::jsonb, 0, 'bilim'),
('pH ölçeğinde 7''nin altındaki değerler neyi gösterir?', '["Asit","Baz","Nötr","Tuz"]'::jsonb, 0, 'bilim'),
('pH ölçeğinde 7''nin üstündeki değerler neyi gösterir?', '["Baz","Asit","Nötr","Mineral"]'::jsonb, 0, 'bilim'),
('Limonun tadının ekşi olmasının sebebi hangi maddedir?', '["Sitrik asit","Laktik asit","Asetik asit","Folik asit"]'::jsonb, 0, 'bilim'),
('Sirkenin içerdiği asit hangisidir?', '["Asetik asit","Sitrik asit","Sülfürik asit","Karbonik asit"]'::jsonb, 0, 'bilim'),
('İnsan DNA''sının yapısını keşfeden ikili kimdir?', '["Watson ve Crick","Curie ve Becquerel","Darwin ve Wallace","Hooke ve Leeuwenhoek"]'::jsonb, 0, 'bilim'),
('Mikroskop altında tek hücreli canlıları ilk gözlemleyen kişi kimdir?', '["Leeuwenhoek","Hooke","Pasteur","Koch"]'::jsonb, 0, 'bilim'),
('Çiçek aşısını geliştiren bilim insanı kimdir?', '["Edward Jenner","Pasteur","Fleming","Salk"]'::jsonb, 0, 'bilim'),
('Kan dolaşımını doğru tanımlayan bilim insanı kimdir?', '["William Harvey","Vesalius","Galen","Hipokrat"]'::jsonb, 0, 'bilim'),
('Tıbbın babası kabul edilen Antik Yunan hekimi kimdir?', '["Hipokrat","Galen","Avicenna","Asklepios"]'::jsonb, 0, 'bilim'),
('İslam dünyasının ünlü hekimi İbn-i Sina''nın Batı''daki adı nedir?', '["Avicenna","Averroes","Alhazen","Rhazes"]'::jsonb, 0, 'bilim'),
('Cebirin babası sayılan ünlü matematikçi kimdir?', '["Harezmi","Ömer Hayyam","Biruni","Cahit Arf"]'::jsonb, 0, 'bilim'),
('Pi sayısının yaklaşık değeri nedir?', '["3,14","3,41","3,12","3,16"]'::jsonb, 0, 'bilim'),
('Bir üçgenin iç açıları toplamı kaç derecedir?', '["180","360","90","270"]'::jsonb, 0, 'bilim'),
('Bir karenin iç açıları toplamı kaç derecedir?', '["360","180","270","400"]'::jsonb, 0, 'bilim'),
('Dik üçgende hipotenüs bağıntısını veren teorem hangisidir?', '["Pisagor","Tales","Öklid","Arşimet"]'::jsonb, 0, 'bilim'),
('"Bana bir dayanak noktası verin, Dünya''yı yerinden oynatayım" sözü kime aittir?', '["Arşimet","Pisagor","Newton","Galileo"]'::jsonb, 0, 'bilim'),
('Suya batan cisimlerin kaldırma kuvvetini açıklayan bilim insanı kimdir?', '["Arşimet","Newton","Pascal","Bernoulli"]'::jsonb, 0, 'bilim'),
('Asal olmayan en küçük çift sayı hangisidir?', '["4","2","6","8"]'::jsonb, 0, 'bilim'),
('En küçük asal sayı hangisidir?', '["2","1","3","0"]'::jsonb, 0, 'bilim'),
('Sıfırın bulunduğu sayı sistemini Avrupa''ya tanıtan medeniyet hangisidir?', '["İslam medeniyeti","Roma","Yunan","Mısır"]'::jsonb, 0, 'bilim'),
('Romen rakamlarında "X" kaçı ifade eder?', '["10","5","50","100"]'::jsonb, 0, 'bilim'),
('Romen rakamlarında "C" kaçı ifade eder?', '["100","50","500","1000"]'::jsonb, 0, 'bilim'),
('Bilgisayarların kullandığı ikilik sayı sistemi hangi rakamlardan oluşur?', '["0 ve 1","1 ve 2","0 ve 9","1 ve 10"]'::jsonb, 0, 'bilim'),
('Yapay zeka alanındaki ünlü test "insan mı makine mi" ayrımını ölçer; adı nedir?', '["Turing Testi","Einstein Testi","Tesla Testi","Lovelace Testi"]'::jsonb, 0, 'bilim'),
('Dünyanın ilk genel amaçlı elektronik bilgisayarı kabul edilen makine hangisidir?', '["ENIAC","UNIVAC","Apple I","Z3"]'::jsonb, 0, 'bilim'),
('İnternette site adreslerinin sonundaki ".tr" neyi ifade eder?', '["Türkiye","Trabzon","Turizm","Transfer"]'::jsonb, 0, 'bilim'),
('Bir ışık yılı neyin birimidir?', '["Uzaklık","Zaman","Hız","Parlaklık"]'::jsonb, 0, 'bilim'),
('Güneş sisteminin en sıcak gezegeni hangisidir?', '["Venüs","Merkür","Mars","Jüpiter"]'::jsonb, 0, 'bilim'),
('Uluslararası Uzay İstasyonu''nun kısaltması nedir?', '["ISS","NASA","ESA","MIR"]'::jsonb, 0, 'bilim'),
('Kuyruklu yıldız Halley yaklaşık kaç yılda bir görülür?', '["76","50","100","25"]'::jsonb, 0, 'bilim'),
('Ay''ın hep aynı yüzünü görmemizin sebebi nedir?', '["Dönüş süreleri eşittir","Ay dönmez","Dünya hızlı döner","Ay çok uzaktır"]'::jsonb, 0, 'bilim'),
('Deve kuşu hakkında hangisi doğrudur?', '["Uçamaz","Yüzemez","Koşamaz","Yumurtlamaz"]'::jsonb, 0, 'bilim'),
('Dünyanın en hızlı kuşu (dalışta) hangisidir?', '["Gökdoğan","Kartal","Atmaca","Albatros"]'::jsonb, 0, 'bilim'),
('Fillerin hortumu aslında neyin uzantısıdır?', '["Burun ve üst dudak","Sadece burun","Çene","Diş"]'::jsonb, 0, 'bilim'),
('Yunuslar uyurken beyinlerinin ne kadarı uyanık kalır?', '["Yarısı","Tamamı","Hiçbiri","Dörtte biri"]'::jsonb, 0, 'bilim'),
('Bal arısı soktuktan sonra ne olur?', '["Ölür","Yaşamaya devam eder","Uçamaz","Kraliçe olur"]'::jsonb, 0, 'bilim'),
('Kraliçe arının görevi nedir?', '["Yumurtlamak","Bal yapmak","Kovan korumak","Polen taşımak"]'::jsonb, 0, 'bilim'),
('İpek Yolu üzerindeki kervanların temel taşıma hayvanı hangisiydi?', '["Deve","At","Eşek","Fil"]'::jsonb, 0, 'bilim'),
('"Çöl gemisi" olarak anılan hayvan hangisidir?', '["Deve","At","Eşek","Lama"]'::jsonb, 0, 'bilim'),
('Hangi içecek dünyada sudan sonra en çok tüketilir?', '["Çay","Kahve","Süt","Kola"]'::jsonb, 0, 'genel'),
('Psikolojideki ünlü "ihtiyaçlar hiyerarşisi" piramidi kime aittir?', '["Maslow","Freud","Jung","Pavlov"]'::jsonb, 0, 'genel'),
('Psikanalizin kurucusu kimdir?', '["Freud","Jung","Adler","Pavlov"]'::jsonb, 0, 'genel'),
('Köpek deneyleriyle koşullu refleksi inceleyen bilim insanı kimdir?', '["Pavlov","Skinner","Freud","Watson"]'::jsonb, 0, 'genel'),
('Felsefede "Sorgulanmamış hayat yaşanmaya değmez" sözü kime aittir?', '["Sokrates","Platon","Aristoteles","Epikür"]'::jsonb, 0, 'genel'),
('Platon''un öğrencisi olan ünlü filozof kimdir?', '["Aristoteles","Sokrates","Diyojen","Epikür"]'::jsonb, 0, 'genel'),
('Fıçıda yaşadığı söylenen kinik filozof kimdir?', '["Diyojen","Sokrates","Zenon","Epiktetos"]'::jsonb, 0, 'genel'),
('"Düşünüyorum, öyleyse varım" sözü kime aittir?', '["Descartes","Kant","Spinoza","Hume"]'::jsonb, 0, 'genel'),
('Nobel ödülleri hangi ülkede verilir (barış hariç)?', '["İsveç","Norveç","İsviçre","Danimarka"]'::jsonb, 0, 'genel'),
('Nobel Barış Ödülü hangi şehirde verilir?', '["Oslo","Stockholm","Kopenhag","Helsinki"]'::jsonb, 0, 'genel'),
('Nobel ödüllerine adını veren Alfred Nobel neyi icat etmiştir?', '["Dinamit","Barut","Roket","Telgraf"]'::jsonb, 0, 'genel'),
('Aziz Sancar Nobel''i hangi alanda kazanmıştır?', '["Kimya","Fizik","Tıp","Edebiyat"]'::jsonb, 0, 'genel'),
('Dünya Sağlık Örgütü''nün kısaltması nedir?', '["WHO","UNICEF","UNESCO","FAO"]'::jsonb, 0, 'genel'),
('UNESCO neyle ilgilenir?', '["Eğitim, bilim ve kültür","Sağlık","Gıda","Çocuk hakları"]'::jsonb, 0, 'genel'),
('Birleşmiş Milletler''in merkezi hangi şehirdedir?', '["New York","Cenevre","Paris","Viyana"]'::jsonb, 0, 'genel'),
('Avrupa Birliği''nin merkezi hangi şehirdedir?', '["Brüksel","Strazburg","Paris","Berlin"]'::jsonb, 0, 'genel'),
('Interpol''ün merkezi hangi ülkededir?', '["Fransa","ABD","İngiltere","Belçika"]'::jsonb, 0, 'genel'),
('Hangi gezegen adını Roma savaş tanrısından alır?', '["Mars","Jüpiter","Venüs","Merkür"]'::jsonb, 0, 'genel'),
('Venüs adını hangi tanrıçadan alır?', '["Aşk ve güzellik","Savaş","Bilgelik","Av"]'::jsonb, 0, 'genel'),
('Yunan mitolojisinde tanrıların kralı kimdir?', '["Zeus","Poseidon","Hades","Apollon"]'::jsonb, 0, 'genel'),
('Yunan mitolojisinde denizlerin tanrısı kimdir?', '["Poseidon","Zeus","Hades","Hermes"]'::jsonb, 0, 'genel'),
('Yunan mitolojisinde yeraltı dünyasının tanrısı kimdir?', '["Hades","Poseidon","Ares","Kronos"]'::jsonb, 0, 'genel'),
('Truva Savaşı''nı anlatan destan hangisidir?', '["İlyada","Odysseia","Aeneis","Gılgamış"]'::jsonb, 0, 'genel'),
('Topuğundan vurulan ölümsüz Yunan kahramanı kimdir?', '["Aşil","Hektor","Odysseus","Paris"]'::jsonb, 0, 'genel'),
('Tek gözlü dev Tepegöz''ün Yunan mitolojisindeki karşılığı nedir?', '["Kiklop","Minotor","Hidra","Kerberos"]'::jsonb, 0, 'genel'),
('Bilinen en eski yazılı destan hangisidir?', '["Gılgamış","İlyada","Şehname","Kalevala"]'::jsonb, 0, 'edebiyat'),
('İran edebiyatının ünlü destanı Şehname''nin yazarı kimdir?', '["Firdevsi","Hafız","Sadi","Ömer Hayyam"]'::jsonb, 0, 'edebiyat'),
('Rubaileriyle ünlü İranlı şair ve matematikçi kimdir?', '["Ömer Hayyam","Firdevsi","Hafız","Mevlana"]'::jsonb, 0, 'edebiyat'),
('"Bin Bir Gece Masalları"ndaki hikaye anlatıcısı kimdir?', '["Şehrazat","Aladdin","Sinbad","Şehriyar"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında ilk kadın romancı kabul edilen yazar kimdir?', '["Fatma Aliye","Halide Edib","Suat Derviş","Nezihe Muhiddin"]'::jsonb, 0, 'edebiyat'),
('"Saatleri Ayarlama Enstitüsü" romanının yazarı kimdir?', '["Ahmet Hamdi Tanpınar","Oğuz Atay","Sait Faik","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('"Huzur" romanının yazarı kimdir?', '["Ahmet Hamdi Tanpınar","Peyami Safa","Yakup Kadri","Halid Ziya"]'::jsonb, 0, 'edebiyat'),
('"Dokuzuncu Hariciye Koğuşu" romanının yazarı kimdir?', '["Peyami Safa","Ahmet Hamdi","Refik Halid","Sabahattin Ali"]'::jsonb, 0, 'edebiyat'),
('Adalet Ağaoğlu hangi türün önemli yazarlarındandır?', '["Roman","Şiir","Tiyatro","Deneme"]'::jsonb, 0, 'edebiyat'),
('"Masal" şiiriyle başlayıp "İkinci Yeni"nin öncülerinden olan şair kimdir?', '["Cemal Süreya","Orhan Veli","İlhan Berk","Edip Cansever"]'::jsonb, 0, 'edebiyat'),
('Türk hikayeciliğinde "Semaver" ve "Lüzumsuz Adam" kimin eserleridir?', '["Sait Faik Abasıyanık","Sabahattin Ali","Memduh Şevket","Haldun Taner"]'::jsonb, 0, 'edebiyat'),
('Mizah dergiciliğinde iz bırakan "Gırgır" ne tür bir yayındı?', '["Karikatür dergisi","Edebiyat dergisi","Spor gazetesi","Moda dergisi"]'::jsonb, 0, 'genel'),
('Karikatürde konuşmaların yazıldığı baloncuğa ne denir?', '["Konuşma balonu","Çerçeve","Panel","Vinyet"]'::jsonb, 0, 'genel'),
('Tom ve Jerry çizgi filminde Jerry hangi hayvandır?', '["Fare","Kedi","Köpek","Tavşan"]'::jsonb, 0, 'genel'),
('Red Kit çizgi romanındaki atın adı nedir?', '["Düldül","Rüzgar","Şimşek","Karakaçan"]'::jsonb, 0, 'genel'),
('Süper kahraman Superman hangi gezegenden gelir?', '["Kripton","Mars","Vulcan","Asgard"]'::jsonb, 0, 'genel'),
('Örümcek Adam''ın gerçek adı nedir?', '["Peter Parker","Clark Kent","Bruce Wayne","Tony Stark"]'::jsonb, 0, 'genel'),
('Batman hangi şehri korur?', '["Gotham","Metropolis","New York","Star City"]'::jsonb, 0, 'genel'),
('Pikachu hangi oyun/çizgi film evreninin karakteridir?', '["Pokemon","Digimon","Mario","Zelda"]'::jsonb, 0, 'genel'),
('Super Mario hangi şirketin oyun karakteridir?', '["Nintendo","Sega","Sony","Atari"]'::jsonb, 0, 'genel'),
('Minecraft oyununun temel etkinliği nedir?', '["Blok inşa etmek","Araba yarışı","Futbol","Dans"]'::jsonb, 0, 'genel')
on conflict (soru) do nothing;
