-- ============================================================
-- Soru Partisi 11 — 400 GENEL KÜLTÜR + 100 karışık kategori
-- Zorluk: %40 kolay / %40 orta / %20 zor
--
-- Kalite: tek ve tartışmasız doğru cevap; zamanla değişen bilgi yok;
-- yoruma açık ifade yok; mevcut havuza (parti 10 dahil) karşı tekrar taraması
-- yapıldı; şıklar kısa. Migration sonunda YALNIZ bu partinin şıkları karıştırılır.
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- ===================== KOLAY =====================

-- Ülkeler ve başkentler
('Danimarka''nın başkenti neresidir?', '["Kopenhag","Aarhus","Odense","Aalborg"]'::jsonb, 0, 'genel_kultur'),
('İsviçre''nin başkenti neresidir?', '["Zürih","Bern","Cenevre","Basel"]'::jsonb, 1, 'genel_kultur'),
('Romanya''nın başkenti neresidir?', '["Timisoara","Kluj","Bükreş","Yaş"]'::jsonb, 2, 'genel_kultur'),
('Bulgaristan''ın başkenti neresidir?', '["Burgaz","Filibe","Varna","Sofya"]'::jsonb, 3, 'genel_kultur'),
('Azerbaycan''ın başkenti neresidir?', '["Bakü","Gence","Sumgayıt","Nahçıvan"]'::jsonb, 0, 'genel_kultur'),
('Gürcistan''ın başkenti neresidir?', '["Batum","Tiflis","Kutaisi","Rustavi"]'::jsonb, 1, 'genel_kultur'),
('Kazakistan''ın en kalabalık şehri hangisidir?', '["Şımkent","Aktau","Almatı","Oral"]'::jsonb, 2, 'genel_kultur'),
('Güney Afrika''nın yasama başkenti neresidir?', '["Pretoria","Johannesburg","Durban","Cape Town"]'::jsonb, 3, 'genel_kultur'),
('Nijerya''nın başkenti neresidir?', '["Abuja","Lagos","Kano","İbadan"]'::jsonb, 0, 'genel_kultur'),
('İrlanda''nın başkenti neresidir?', '["Cork","Dublin","Galway","Limerick"]'::jsonb, 1, 'genel_kultur'),

-- Bayraklar ve semboller
('Hangi ülkenin bayrağında akçaağaç yaprağı vardır?', '["Yeni Zelanda","Avustralya","Kanada","İrlanda"]'::jsonb, 2, 'genel_kultur'),
('Hangi ülkenin bayrağında kırmızı bir daire bulunur?', '["Vietnam","Çin","Kore","Japonya"]'::jsonb, 3, 'genel_kultur'),
('Hangi ülkenin bayrağı sadece kırmızı ve beyazdan oluşur?', '["Polonya","Almanya","Fransa","İtalya"]'::jsonb, 0, 'genel_kultur'),
('Fransa bayrağındaki renkler hangileridir?', '["Yeşil, beyaz, kırmızı","Mavi, beyaz, kırmızı","Sarı, kırmızı, mavi","Siyah, kırmızı, sarı"]'::jsonb, 1, 'genel_kultur'),
('İtalya bayrağındaki renkler hangileridir?', '["Sarı, kırmızı, yeşil","Mavi, beyaz, kırmızı","Yeşil, beyaz, kırmızı","Beyaz, siyah, kırmızı"]'::jsonb, 2, 'genel_kultur'),
('Almanya bayrağındaki renkler hangileridir?', '["Kırmızı, beyaz, mavi","Mavi, beyaz, kırmızı","Yeşil, beyaz, siyah","Siyah, kırmızı, sarı"]'::jsonb, 3, 'genel_kultur'),
('Hangi ülkenin bayrağında ejderha vardır?', '["Butan","Nepal","Tayland","Kamboçya"]'::jsonb, 0, 'genel_kultur'),
('Yunanistan bayrağının ana rengi hangisidir?', '["Yeşil","Mavi","Kırmızı","Turuncu"]'::jsonb, 1, 'genel_kultur'),
('Olimpiyat halkalarının renkleri arasında hangisi yoktur?', '["Sarı","Mavi","Mor","Yeşil"]'::jsonb, 2, 'genel_kultur'),
('Barışın simgesi kabul edilen kuş hangisidir?', '["Baykuş","Kartal","Karga","Güvercin"]'::jsonb, 3, 'genel_kultur'),

-- Hayvanlar ve doğa (kolay)
('Hangi hayvan tüy değiştirerek kışa hazırlanır?', '["Tilki","Balık","Kertenkele","Solucan"]'::jsonb, 0, 'genel_kultur'),
('Kış uykusuna yatan hayvanlardan biri hangisidir?', '["At","Ayı","İnek","Koyun"]'::jsonb, 1, 'genel_kultur'),
('Göç eden hayvan grubu hangisidir?', '["Salyangozlar","Köstebekler","Leylekler","Kirpiler"]'::jsonb, 2, 'genel_kultur'),
('Hangi hayvan ağ örer?', '["Kelebek","Karınca","Arı","Örümcek"]'::jsonb, 3, 'genel_kultur'),
('Hangi hayvan kabuklu bir deniz canlısıdır?', '["Istakoz","Yunus","Fok","Balina"]'::jsonb, 0, 'genel_kultur'),
('Hangi hayvan geceleri parlayan ışık üretir?', '["Kelebek","Ateş böceği","Karınca","Sinek"]'::jsonb, 1, 'genel_kultur'),
('Deve kaç hörgüçlü olabilir?', '["Sadece dört","Sadece üç","Bir veya iki","Hörgüçsüz"]'::jsonb, 2, 'genel_kultur'),
('Hangi hayvan sesini taklit edebilir?', '["Tavşan","Kedi","Koyun","Papağan"]'::jsonb, 3, 'genel_kultur'),
('Kuşların uçmasını sağlayan yapı hangisidir?', '["Kanat","Kuyruk","Gaga","Pençe"]'::jsonb, 0, 'genel_kultur'),
('Hangi ağaç yaprağını kışın dökmez?', '["Kavak","Çam","Söğüt","Meşe"]'::jsonb, 1, 'genel_kultur'),
('Kaktüs hangi ortamda yetişir?', '["Buzul","Bataklık","Çöl","Okyanus"]'::jsonb, 2, 'genel_kultur'),
('Ağacın yaşını nasıl anlayabiliriz?', '["Meyvesinden","Yaprağından","Kabuğundan","Gövdesindeki halkalardan"]'::jsonb, 3, 'genel_kultur'),
('Mantarlar hangi canlı grubundandır?', '["Mantarlar alemi","Bitkiler","Hayvanlar","Bakteriler"]'::jsonb, 0, 'genel_kultur'),
('Bir bitkinin en çok su kaybettiği kısım hangisidir?', '["Kök","Yapraklar","Tohum","Kabuk"]'::jsonb, 1, 'genel_kultur'),
('Bal arısının kovandaki görevlerinden biri nedir?', '["Yuva kazmak","Ağ örmek","Nektar toplamak","Avlanmak"]'::jsonb, 2, 'genel_kultur'),

-- Günlük fizik ve kimya
('Cisimlerin ağırlığını oluşturan kuvvet hangisidir?', '["Basınç","Sürtünme","Manyetizma","Yer çekimi"]'::jsonb, 3, 'genel_kultur'),
('Hareketi zorlaştıran kuvvet hangisidir?', '["Sürtünme","Çekim","İtme","Kaldırma"]'::jsonb, 0, 'genel_kultur'),
('Suda batmayan cisimler için ne söylenir?', '["Ağırdır","Yoğunluğu sudan azdır","Metaldir","Sıcaktır"]'::jsonb, 1, 'genel_kultur'),
('Sıcaklık arttıkça maddelerin hacmi genellikle ne olur?', '["Değişmez","Küçülür","Genleşir","Yok olur"]'::jsonb, 2, 'genel_kultur'),
('Işığın saydam bir ortamdan geçerken yön değiştirmesine ne denir?', '["Yayılma","Yansıma","Soğurma","Kırılma"]'::jsonb, 3, 'genel_kultur'),
('Işığın aynadan geri dönmesine ne denir?', '["Yansıma","Kırılma","Emilim","Kırınım"]'::jsonb, 0, 'genel_kultur'),
('Gölgenin oluşmasının sebebi nedir?', '["Sesin yayılması","Işığın engelle kesilmesi","Isının artması","Rüzgâr"]'::jsonb, 1, 'genel_kultur'),
('Elektrik devresinde akımı kesen eleman hangisidir?', '["Pil","Ampul","Anahtar","Kablo"]'::jsonb, 2, 'genel_kultur'),
('Pilin görevi nedir?', '["Isıyı düşürmek","Işık yaymak","Ses üretmek","Enerji sağlamak"]'::jsonb, 3, 'genel_kultur'),
('Elektriği iletmeyen maddeye ne denir?', '["Yalıtkan","İletken","Yarı iletken","Mıknatıs"]'::jsonb, 0, 'genel_kultur'),
('Tuzun kimyasal adı nedir?', '["Kalsiyum karbonat","Sodyum klorür","Potasyum nitrat","Demir oksit"]'::jsonb, 1, 'genel_kultur'),
('Sirke hangi tada sahiptir?', '["Acı","Tatlı","Ekşi","Tuzlu"]'::jsonb, 2, 'genel_kultur'),
('Bir maddenin gazdan sıvıya geçmesine ne denir?', '["Süblimleşme","Buharlaşma","Erime","Yoğuşma"]'::jsonb, 3, 'genel_kultur'),
('Karışımı ayırmak için kullanılan yöntemlerden biri hangisidir?', '["Süzme","Isıtma yasağı","Boyama","Karıştırma"]'::jsonb, 0, 'genel_kultur'),

-- Matematik günlük
('100 sayısının yarısı kaçtır?', '["25","50","200","10"]'::jsonb, 1, 'genel_kultur'),
('Bir sayının 10 katı nasıl bulunur?', '["10 çıkarılır","10 eklenir","10 ile çarpılır","10 bölünür"]'::jsonb, 2, 'genel_kultur'),
('Çift sayılara örnek hangisidir?', '["11","7","9","8"]'::jsonb, 3, 'genel_kultur'),
('Tek sayılara örnek hangisidir?', '["13","10","12","14"]'::jsonb, 0, 'genel_kultur'),
('Bir düzgün altıgenin kaç kenarı vardır?', '["5","6","7","8"]'::jsonb, 1, 'genel_kultur'),
('Dairenin merkezden kenarına olan uzaklığına ne denir?', '["Çevre","Çap","Yarıçap","Alan"]'::jsonb, 2, 'genel_kultur'),
('Çap, yarıçapın kaç katıdır?', '["1","3","4","2"]'::jsonb, 3, 'genel_kultur'),
('Bir dik açı kaç derecedir?', '["90","45","180","360"]'::jsonb, 0, 'genel_kultur'),
('Toplama işleminin sonucuna ne denir?', '["Fark","Toplam","Çarpım","Bölüm"]'::jsonb, 1, 'genel_kultur'),
('Çıkarma işleminin sonucuna ne denir?', '["Çarpım","Toplam","Fark","Bölüm"]'::jsonb, 2, 'genel_kultur'),
('Çarpma işleminin sonucuna ne denir?', '["Kalan","Toplam","Fark","Çarpım"]'::jsonb, 3, 'genel_kultur'),
('Bölme işleminde artan sayıya ne denir?', '["Kalan","Bölüm","Bölen","Çarpan"]'::jsonb, 0, 'genel_kultur'),
('Bir üçgende en fazla kaç dik açı olabilir?', '["2","1","3","0"]'::jsonb, 1, 'genel_kultur'),

-- ===================== ORTA =====================

-- Dünya tarihi
('Rönesans hangi yüzyıllarda etkili olmuştur?', '["18-19. yüzyıl","9-10. yüzyıl","14-16. yüzyıl","20. yüzyıl"]'::jsonb, 2, 'genel_kultur'),
('Roma İmparatorluğu kaça ayrılmıştır?', '["Beşe","Üçe","Dörde","İkiye"]'::jsonb, 3, 'genel_kultur'),
('Antik Yunan''da şehir devletlerine ne denirdi?', '["Polis","Forum","Senato","Agora"]'::jsonb, 0, 'genel_kultur'),
('Büyük İskender hangi ülkenin kralıydı?', '["Mısır","Makedonya","Pers","Roma"]'::jsonb, 1, 'genel_kultur'),
('İpek Yolu hangi iki bölgeyi bağlıyordu?', '["Avustralya ile Asya","Afrika ile Amerika","Asya ile Avrupa","Kutuplar"]'::jsonb, 2, 'genel_kultur'),
('Kavimler Göçü hangi kıtayı etkilemiştir?', '["Antarktika","Amerika","Avustralya","Avrupa"]'::jsonb, 3, 'genel_kultur'),
('Aztek uygarlığı hangi bölgede yaşamıştır?', '["Meksika","Peru","Mısır","Hindistan"]'::jsonb, 0, 'genel_kultur'),
('İnka uygarlığı hangi bölgede yaşamıştır?', '["Sahra","And Dağları","Balkanlar","Sibirya"]'::jsonb, 1, 'genel_kultur'),
('Soğuk Savaş hangi iki blok arasında yaşanmıştır?', '["Doğu ve Kuzey","Kuzey ve Güney","Doğu ve Batı","Batı ve Güney"]'::jsonb, 2, 'genel_kultur'),

-- Türk tarihi detay
('İlk Türk devletlerinden Göktürkler hangi bölgede kurulmuştur?', '["Kafkasya","Anadolu","Balkanlar","Orta Asya"]'::jsonb, 3, 'genel_kultur'),
('Uygurlar hangi özellikleriyle bilinir?', '["Yerleşik hayata geçmeleri","Denizciliği","Piramitleri","Cam sanatını"]'::jsonb, 0, 'genel_kultur'),
('Büyük Selçuklu Devleti''nin kurucusu kimdir?', '["Alparslan","Tuğrul Bey","Melikşah","Sencer"]'::jsonb, 1, 'genel_kultur'),
('Anadolu Selçuklu Devleti''ni kim kurmuştur?', '["Osman Bey","Alparslan","Süleyman Şah","Orhan Bey"]'::jsonb, 2, 'genel_kultur'),
('Osmanlı''da ilk medrese hangi şehirde açılmıştır?', '["Konya","Bursa","Edirne","İznik"]'::jsonb, 3, 'genel_kultur'),
('Osmanlı donanmasının ünlü denizcilerinden biri kimdir?', '["Barbaros Hayreddin Paşa","Mimar Sinan","Katip Çelebi","Evliya Çelebi"]'::jsonb, 0, 'genel_kultur'),
('Seyahatname adlı eserin yazarı kimdir?', '["Katip Çelebi","Evliya Çelebi","Piri Reis","Naima"]'::jsonb, 1, 'genel_kultur'),
('Kitab-ı Bahriye''nin yazarı kimdir?', '["Turgut Reis","Barbaros","Piri Reis","Seydi Ali Reis"]'::jsonb, 2, 'genel_kultur'),
('Osmanlı''da matbaayı kuran kişi kimdir?', '["Piri Reis","Evliya Çelebi","Katip Çelebi","İbrahim Müteferrika"]'::jsonb, 3, 'genel_kultur'),
('Amasya Genelgesi hangi yıl yayımlanmıştır?', '["1919","1920","1921","1918"]'::jsonb, 0, 'genel_kultur'),
('Türk kadınlarına belediye seçimlerinde seçme hakkı hangi yıl verilmiştir?', '["1934","1930","1926","1924"]'::jsonb, 1, 'genel_kultur'),
('Tevhid-i Tedrisat Kanunu neyle ilgilidir?', '["Vergi düzeni","Ordunun kurulması","Eğitimin birleştirilmesi","Ticaret"]'::jsonb, 2, 'genel_kultur'),

-- Sağlık ve beslenme orta
('Hangi besin grubu enerji verir?', '["Su","Vitaminler","Mineraller","Karbonhidratlar"]'::jsonb, 3, 'genel_kultur'),
('Kemik erimesini önlemede etkili vitamin hangisidir?', '["D vitamini","C vitamini","B12","K vitamini"]'::jsonb, 0, 'genel_kultur'),
('Gece körlüğüyle ilişkilendirilen vitamin hangisidir?', '["C vitamini","A vitamini","D vitamini","E vitamini"]'::jsonb, 1, 'genel_kultur'),
('Guatr hangi maddenin eksikliğiyle ilişkilidir?', '["Kalsiyum","Demir","İyot","Çinko"]'::jsonb, 2, 'genel_kultur'),
('Vücutta demir eksikliği neye yol açar?', '["Migren","Diyabet","Astım","Kansızlık"]'::jsonb, 3, 'genel_kultur'),
('Lifli besinler öncelikle hangi sistemi destekler?', '["Sindirim","Dolaşım","Solunum","Sinir"]'::jsonb, 0, 'genel_kultur'),
('Hangi davranış kalp sağlığını olumsuz etkiler?', '["Yürüyüş","Hareketsizlik","Su içmek","Sebze yemek"]'::jsonb, 1, 'genel_kultur'),
('Bağışıklığı güçlendiren en temel alışkanlıklardan biri nedir?', '["Aşırı şeker","Uykusuzluk","Düzenli uyku","Hareketsizlik"]'::jsonb, 2, 'genel_kultur'),
('Bir yetişkin için önerilen günlük adım hedefi yaklaşık kaçtır?', '["100.000","1.000","100","10.000"]'::jsonb, 3, 'genel_kultur'),
('Diş fırçalama günde en az kaç kez önerilir?', '["2","1","5","8"]'::jsonb, 0, 'genel_kultur'),
('Grip hangi tür etkenden kaynaklanır?', '["Bakteri","Virüs","Mantar","Parazit"]'::jsonb, 1, 'genel_kultur'),
('Alerjiye yol açan maddelere ne denir?', '["Enzim","Antikor","Alerjen","Hormon"]'::jsonb, 2, 'genel_kultur'),
('Vücuttaki hormonları salgılayan bezlere ne denir?', '["Tükürük bezleri","Ter bezleri","Yağ bezleri","İç salgı bezleri"]'::jsonb, 3, 'genel_kultur'),
('Kan basıncına halk arasında ne denir?', '["Tansiyon","Nabız","Ateş","Şeker"]'::jsonb, 0, 'genel_kultur'),

-- Müzik ve enstrümanlar
('Keman hangi çalgı grubundandır?', '["Nefesli","Yaylı","Vurmalı","Tuşlu"]'::jsonb, 1, 'genel_kultur'),
('Flüt hangi çalgı grubundandır?', '["Vurmalı","Yaylı","Nefesli","Tuşlu"]'::jsonb, 2, 'genel_kultur'),
('Ney hangi tür çalgıdır?', '["Telli mızraplı","Yaylı","Vurmalı","Nefesli"]'::jsonb, 3, 'genel_kultur'),
('Ud hangi tür çalgıdır?', '["Telli","Nefesli","Vurmalı","Tuşlu"]'::jsonb, 0, 'genel_kultur'),
('Kanun hangi tür çalgıdır?', '["Nefesli","Telli","Vurmalı","Yaylı"]'::jsonb, 1, 'genel_kultur'),
('Darbuka hangi tür çalgıdır?', '["Nefesli","Telli","Vurmalı","Tuşlu"]'::jsonb, 2, 'genel_kultur'),
('Üç veya daha fazla sesin birlikte çalınmasına ne denir?', '["Anahtar","Nota","Porte","Akor"]'::jsonb, 3, 'genel_kultur'),
('Müzikte sesin yüksekliğini belirten terim hangisidir?', '["Nüans","Tempo","Ritim","Ölçü"]'::jsonb, 0, 'genel_kultur'),
('Tango hangi ülkeyle özdeşleşmiştir?', '["İspanya","Arjantin","Meksika","Portekiz"]'::jsonb, 1, 'genel_kultur'),
('Flamenko hangi ülkenin dansıdır?', '["Yunanistan","İtalya","İspanya","Fransa"]'::jsonb, 2, 'genel_kultur'),
('Samba hangi ülkeyle özdeşleşmiştir?', '["Şili","Küba","Meksika","Brezilya"]'::jsonb, 3, 'genel_kultur'),

-- Dünya edebiyatı ve felsefe
('İlahi Komedya''nın yazarı kimdir?', '["Dante","Petrarca","Boccaccio","Machiavelli"]'::jsonb, 0, 'genel_kultur'),
('Robinson Crusoe''nun yazarı kimdir?', '["Jonathan Swift","Daniel Defoe","Jules Verne","Mark Twain"]'::jsonb, 1, 'genel_kultur'),
('Üç Silahşorler''in yazarı kimdir?', '["Balzac","Victor Hugo","Alexandre Dumas","Stendhal"]'::jsonb, 2, 'genel_kultur'),
('Küçük Prens''in yazarı kimdir?', '["Gide","Camus","Sartre","Saint-Exupéry"]'::jsonb, 3, 'genel_kultur'),
('"Bilgi güçtür" sözü hangi düşünürle anılır?', '["Francis Bacon","Descartes","Kant","Hume"]'::jsonb, 0, 'genel_kultur'),
('Sokrates hangi uygarlığın filozofudur?', '["Roma","Antik Yunan","Mısır","Pers"]'::jsonb, 1, 'genel_kultur'),
('Aristoteles hangi alanda da çalışmalar yapmıştır?', '["Denizcilik","Balıkçılık","Mantık","Mimarlık"]'::jsonb, 2, 'genel_kultur'),
('İbn Sina hangi alandaki eseriyle tanınır?', '["Şiir","Astronomi","Mimarlık","Tıp"]'::jsonb, 3, 'genel_kultur'),
('Farabi hangi lakapla anılır?', '["Muallim-i Sani","Şeyh","Hakim","Reis"]'::jsonb, 0, 'genel_kultur'),

-- Spor detay
('Bir voleybol setinde kazanmak için en az kaç sayı gerekir?', '["21","25","15","11"]'::jsonb, 1, 'genel_kultur'),
('Futbolda bir maç kaç dakikadır (normal süre)?', '["100","80","90","60"]'::jsonb, 2, 'genel_kultur'),
('Futbolda kaç sarı kart kırmızıya dönüşür?', '["1","3","4","2"]'::jsonb, 3, 'genel_kultur'),
('Tenis maçında kazanılan bölümlere ne denir?', '["Set","Devre","Periyot","Raunt"]'::jsonb, 0, 'genel_kultur'),
('Boksta bir bölüme ne denir?', '["Set","Raunt","Periyot","Devre"]'::jsonb, 1, 'genel_kultur'),
('Yüzmede sırtüstü dışında bir stil hangisidir?', '["Kayma","Tırmanma","Kurbağalama","Süzülme"]'::jsonb, 2, 'genel_kultur'),
('Atletizmde uzun atlama neyle ölçülür?', '["Yükseklik farkı","Süre","Ağırlık","Mesafe"]'::jsonb, 3, 'genel_kultur'),
('Halterde başarı neye göre belirlenir?', '["Kaldırılan ağırlık","Koşu süresi","Atış mesafesi","Puanlama jürisi"]'::jsonb, 0, 'genel_kultur'),
('Taekwondo hangi ülkede doğmuştur?', '["Japonya","Kore","Çin","Vietnam"]'::jsonb, 1, 'genel_kultur'),
('Kriket sporu en çok hangi ülkelerde yaygındır?', '["Norveç ve İsveç","Brezilya ve Arjantin","İngiltere ve Hindistan","Mısır ve Fas"]'::jsonb, 2, 'genel_kultur'),
('Rugby sporunda top hangi şekildedir?', '["Üçgen","Yuvarlak","Kare","Oval"]'::jsonb, 3, 'genel_kultur'),
('Buz hokeyinde topun yerine ne kullanılır?', '["Disk (puck)","Küre","Kutu","Halka"]'::jsonb, 0, 'genel_kultur'),
('Formula 1 hangi tür yarıştır?', '["Bisiklet","Otomobil","At","Tekne"]'::jsonb, 1, 'genel_kultur'),

-- Ulaşım, iletişim, icatlar
('Telgrafın icadı hangi alanı değiştirmiştir?', '["Madencilik","Tarım","İletişim","Dokuma"]'::jsonb, 2, 'genel_kultur'),
('Buhar makinesini geliştiren mühendis kimdir?', '["Alexander Bell","Thomas Edison","Nikola Tesla","James Watt"]'::jsonb, 3, 'genel_kultur'),
('Radyonun geliştirilmesinde adı geçen mucit kimdir?', '["Marconi","Ford","Diesel","Otto"]'::jsonb, 0, 'genel_kultur'),
('Dinamiti bulan kişi kimdir?', '["Michael Faraday","Alfred Nobel","Louis Pasteur","Gregor Mendel"]'::jsonb, 1, 'genel_kultur'),
('Fotoğraf makinesinin gelişiminde ilk kalıcı görüntüyü elde eden ülke hangisidir?', '["Rusya","Japonya","Fransa","Brezilya"]'::jsonb, 2, 'genel_kultur'),
('Sinemanın doğuşunda adı geçen kardeşler kimlerdir?', '["Warner Kardeşler","Wright Kardeşler","Grimm Kardeşler","Lumière Kardeşler"]'::jsonb, 3, 'genel_kultur'),
('İlk yapay uydunun adı nedir?', '["Sputnik","Apollo","Voyager","Explorer"]'::jsonb, 0, 'genel_kultur'),
('GPS teknolojisi ne işe yarar?', '["Ses kaydı","Konum belirleme","Isı ölçümü","Görüntü işleme"]'::jsonb, 1, 'genel_kultur'),
('Asansörün güvenliğini artıran fren sistemi neyi önler?', '["Elektrik kesintisini","Ses kirliliğini","Serbest düşüşü","Isınmayı"]'::jsonb, 2, 'genel_kultur'),
('Süveyş Kanalı hangi ülkededir?', '["Yunanistan","Panama","Türkiye","Mısır"]'::jsonb, 3, 'genel_kultur'),
('Deniz fenerlerinin görevi nedir?', '["Gemileri yönlendirmek","Balık avlamak","Rüzgâr ölçmek","Dalga üretmek"]'::jsonb, 0, 'genel_kultur'),
('Uçaklarda kara kutu ne işe yarar?', '["Yakıt taşır","Uçuş verilerini kaydeder","Bagaj tutar","Isı üretir"]'::jsonb, 1, 'genel_kultur'),
('Bir otomobilde direksiyonun görevi nedir?', '["Fren yapmak","Hızlanmak","Yön vermek","Isıtmak"]'::jsonb, 2, 'genel_kultur'),
('Bisikletin en temel güvenlik ekipmanı nedir?', '["Zil","Ayna","Sepet","Kask"]'::jsonb, 3, 'genel_kultur'),
('Bir gemide "iskele" hangi yönü belirtir?', '["Sol","Sağ","Ön","Arka"]'::jsonb, 0, 'genel_kultur'),

-- ===================== ZOR =====================

('Bir gemide "sancak" hangi yönü belirtir?', '["Sol","Sağ","Ön","Arka"]'::jsonb, 1, 'genel_kultur'),
('Denizcilikte geminin hızı hangi birimle ölçülür?', '["Ton","Beygir","Knot","Fersah"]'::jsonb, 2, 'genel_kultur'),
('Bir uçağın irtifası genellikle hangi birimle ifade edilir?', '["Kelvin","Litre","Newton","Feet"]'::jsonb, 3, 'genel_kultur'),
('Sıcaklıkta mutlak sıfırın birimi hangisidir?', '["Kelvin","Celsius","Fahrenheit","Joule"]'::jsonb, 0, 'genel_kultur'),
('Basınç biriminin adı nedir?', '["Newton","Pascal","Joule","Watt"]'::jsonb, 1, 'genel_kultur'),
('Enerji biriminin adı nedir?', '["Pascal","Newton","Joule","Amper"]'::jsonb, 2, 'genel_kultur'),
('Kuvvet biriminin adı nedir?', '["Volt","Joule","Watt","Newton"]'::jsonb, 3, 'genel_kultur'),
('Elektrik yükünün birimi nedir?', '["Coulomb","Ohm","Watt","Kelvin"]'::jsonb, 0, 'genel_kultur'),
('Direncin birimi nedir?', '["Volt","Ohm","Amper","Watt"]'::jsonb, 1, 'genel_kultur'),
('Gücün birimi nedir?', '["Newton","Joule","Watt","Coulomb"]'::jsonb, 2, 'genel_kultur'),

('Dünyanın en yüksek şelalesi hangi ülkededir?', '["Zambiya","Brezilya","Kanada","Venezuela"]'::jsonb, 3, 'genel_kultur'),
('Victoria Şelaleleri hangi kıtadadır?', '["Afrika","Güney Amerika","Asya","Avrupa"]'::jsonb, 0, 'genel_kultur'),
('Ölü Deniz''in en belirgin özelliği nedir?', '["Derinliği","Yüksek tuzluluk","Buzulları","Med-cezir"]'::jsonb, 1, 'genel_kultur'),
('Dünyanın en uzun sıradağ sistemi hangisidir?', '["Alpler","Himalayalar","Andlar","Kayalıklar"]'::jsonb, 2, 'genel_kultur'),
('En çok komşusu olan ülkelerden biri hangisidir?', '["Küba","Japonya","İzlanda","Çin"]'::jsonb, 3, 'genel_kultur'),
('Hangi ülkenin denize kıyısı yoktur?', '["Avusturya","Portekiz","Yunanistan","Hırvatistan"]'::jsonb, 0, 'genel_kultur'),
('Vatikan hangi şehrin içinde yer alır?', '["Milano","Roma","Floransa","Napoli"]'::jsonb, 1, 'genel_kultur'),
('Hangi ülke iki ayrı bölgeden oluşur ve arada başka ülke vardır?', '["Hollanda","Portekiz","Azerbaycan","Danimarka"]'::jsonb, 2, 'genel_kultur'),

('Anadolu''da ilk Türk beyliklerinden Danişmentliler hangi bölgede kurulmuştur?', '["Trakya","Ege","Akdeniz","Orta Karadeniz"]'::jsonb, 3, 'genel_kultur'),
('Osmanlı''da "Divan-ı Hümayun" ne işlevi görürdü?', '["Devlet meclisi","Askeri okul","Hastane","Kütüphane"]'::jsonb, 0, 'genel_kultur'),
('Osmanlı''da vakıf sisteminin temel amacı neydi?', '["Vergi toplama","Hayır hizmetleri","Ordu kurma","Ticaret yasağı"]'::jsonb, 1, 'genel_kultur'),
('Kapitülasyonlar neyle ilgilidir?', '["Toprak dağıtımı","Askeri eğitim","Ticari ayrıcalıklar","Eğitim reformu"]'::jsonb, 2, 'genel_kultur'),
('Osmanlı''da ilk kâğıt para hangi adla bilinir?', '["Para","Akçe","Kuruş","Kaime"]'::jsonb, 3, 'genel_kultur'),
('Osmanlı''nın kullandığı ilk gümüş para hangisidir?', '["Akçe","Kaime","Lira","Sikke"]'::jsonb, 0, 'genel_kultur'),
('Anadolu''da Türk-İslam mimarisinde kervansarayların işlevi neydi?', '["Askeri kışla","Yolcu konaklaması","Cami","Okul"]'::jsonb, 1, 'genel_kultur'),
('Kültür tarihinde "külliye" ne demektir?', '["Bir kitap","Tek bir cami","Yapılar topluluğu","Bir tören"]'::jsonb, 2, 'genel_kultur'),
('Osmanlı''da "şehzade" kime denirdi?', '["Kadıya","Vezire","Komutana","Padişahın oğluna"]'::jsonb, 3, 'genel_kultur'),
('Osmanlı''da adaleti sağlayan görevliye ne denirdi?', '["Kadı","Sipahi","Yeniçeri","Reis"]'::jsonb, 0, 'genel_kultur'),

('Hangi element periyodik tabloda "Fe" simgesiyle gösterilir?', '["Flor","Demir","Fosfor","Fermiyum"]'::jsonb, 1, 'genel_kultur'),
('Hangi element "Au" simgesiyle gösterilir?', '["Alüminyum","Gümüş","Altın","Argon"]'::jsonb, 2, 'genel_kultur'),
('Hangi element "Ag" simgesiyle gösterilir?', '["Aktinyum","Altın","Arsenik","Gümüş"]'::jsonb, 3, 'genel_kultur'),
('Hangi element "Cu" simgesiyle gösterilir?', '["Bakır","Kalsiyum","Karbon","Sezyum"]'::jsonb, 0, 'genel_kultur'),
('Hangi element "Na" simgesiyle gösterilir?', '["Azot","Sodyum","Neon","Nikel"]'::jsonb, 1, 'genel_kultur'),
('Soy gazlardan biri hangisidir?', '["Azot","Oksijen","Neon","Klor"]'::jsonb, 2, 'genel_kultur'),
('Elmas hangi elementin bir biçimidir?', '["Kükürt","Silisyum","Bor","Karbon"]'::jsonb, 3, 'genel_kultur'),
('Paslanmaz çelik hangi metalin katkısıyla üretilir?', '["Krom","Kurşun","Kalay","Çinko"]'::jsonb, 0, 'genel_kultur'),
('Cam üretiminin temel hammaddesi nedir?', '["Kireç taşı yok","Kum (silis)","Kil","Demir cevheri"]'::jsonb, 1, 'genel_kultur'),

('İnsanda kalın bağırsağın temel görevi nedir?', '["Oksijen taşıma","Protein sindirimi","Su emilimi","Hormon üretimi"]'::jsonb, 2, 'genel_kultur'),
('Sinir sisteminin temel hücresine ne denir?', '["Miyosit","Alyuvar","Osteosit","Nöron"]'::jsonb, 3, 'genel_kultur'),
('Gözde ışığı algılayan tabaka hangisidir?', '["Retina","Kornea","İris","Sklera"]'::jsonb, 0, 'genel_kultur'),
('Kulakta dengeyi sağlayan yapı hangisidir?', '["Kulak zarı","Yarım daire kanalları","Salyangoz","Çekiç"]'::jsonb, 1, 'genel_kultur'),
('Hücrenin enerji üreten organeli hangisidir?', '["Çekirdek","Ribozom","Mitokondri","Koful"]'::jsonb, 2, 'genel_kultur'),
('Bitki hücresinde bulunup hayvan hücresinde bulunmayan yapı hangisidir?', '["Ribozom","Çekirdek","Mitokondri","Hücre duvarı"]'::jsonb, 3, 'genel_kultur'),
('Kalıtım biliminin kurucusu sayılan kişi kimdir?', '["Mendel","Darwin","Pasteur","Linnaeus"]'::jsonb, 0, 'genel_kultur'),
('Canlıların sınıflandırılmasında en küçük birim hangisidir?', '["Cins","Tür","Familya","Sınıf"]'::jsonb, 1, 'genel_kultur'),
('Besin zincirinin başında hangi canlılar bulunur?', '["Ayrıştırıcılar","Tüketiciler","Üreticiler","Etçiller"]'::jsonb, 2, 'genel_kultur'),
('Ekosistemde ölü canlıları parçalayan canlılara ne denir?', '["Etçiller","Üreticiler","Otçullar","Ayrıştırıcılar"]'::jsonb, 3, 'genel_kultur'),

-- ===================== KARIŞIK KATEGORİLER (100) =====================

('Anadolu''da Urartuların başkenti neresiydi?', '["Tuşpa","Hattuşa","Gordion","Sardes"]'::jsonb, 0, 'tarih'),
('Frigyalıların ünlü kralı kimdir?', '["Krezüs","Midas","Priam","Kroisos"]'::jsonb, 1, 'tarih'),
('Lidyalıların son kralı kimdir?', '["Darius","Midas","Krezüs","Keyhüsrev"]'::jsonb, 2, 'tarih'),
('Pers İmparatorluğu''nun kurucusu kimdir?', '["Kambises","Darius","Serhas","Kiros"]'::jsonb, 3, 'tarih'),
('Kadeş Antlaşması hangi iki devlet arasında imzalanmıştır?', '["Hititler ve Mısırlılar","Sümerler ve Akadlar","Persler ve Yunanlar","Romalılar ve Kartacalılar"]'::jsonb, 0, 'tarih'),
('Pön Savaşları hangi iki güç arasında geçmiştir?', '["Atina ve Sparta","Roma ve Kartaca","Pers ve Yunan","Roma ve Mısır"]'::jsonb, 1, 'tarih'),
('Atina ve Sparta arasındaki savaşın adı nedir?', '["Pön Savaşı","Truva Savaşı","Peloponnes Savaşı","Med Savaşı"]'::jsonb, 2, 'tarih'),
('Yüz Yıl Savaşları hangi iki ülke arasında olmuştur?', '["Almanya ve İtalya","İspanya ve Portekiz","Rusya ve İsveç","İngiltere ve Fransa"]'::jsonb, 3, 'tarih'),
('Otuz Yıl Savaşları''nı sona erdiren antlaşma hangisidir?', '["Vestfalya","Versay","Viyana","Utrecht"]'::jsonb, 0, 'tarih'),
('Birinci Dünya Savaşı''nı bitiren antlaşmalardan biri hangisidir?', '["Lozan","Versay","Vestfalya","Utrecht"]'::jsonb, 1, 'tarih'),
('Osmanlı''nın Avrupa''da toprak kaybettiği Karlofça Antlaşması hangi yıldır?', '["1774","1606","1699","1829"]'::jsonb, 2, 'tarih'),
('İstanbul''un ilk adı nedir?', '["Efesos","Nikaia","Smyrna","Byzantion"]'::jsonb, 3, 'tarih'),
('Anadolu''da ilk madeni parayı basan uygarlık hangisidir?', '["Lidyalılar","Frigler","Urartular","Hititler"]'::jsonb, 0, 'tarih'),

('İnsan vücudunda en çok bulunan element hangisidir?', '["Demir","Oksijen","Kalsiyum","Çinko"]'::jsonb, 1, 'bilim'),
('Bir cismin kütlesi Ay''da nasıl değişir?', '["Artar","Azalır","Değişmez","Sıfırlanır"]'::jsonb, 2, 'bilim'),
('Sıvıların basıncını açıklayan ilke kime aittir?', '["Hooke","Arşimet","Boyle","Pascal"]'::jsonb, 3, 'bilim'),
('Bir maddenin yoğunluğu neyle hesaplanır?', '["Kütle bölü hacim","Kütle çarpı hacim","Hacim bölü kütle","Kütle artı hacim"]'::jsonb, 0, 'bilim'),
('Mercekler hangi olaydan yararlanır?', '["Sesin yansıması","Işığın kırılması","Isının iletimi","Manyetizma"]'::jsonb, 1, 'bilim'),
('Gökkuşağı hangi olayla oluşur?', '["Rüzgâr","Ses dalgaları","Işığın kırılması ve ayrışması","Manyetik alan"]'::jsonb, 2, 'bilim'),
('Isının katılarda yayılma yolu hangisidir?', '["Yansıma","Konveksiyon","Işıma","İletim"]'::jsonb, 3, 'bilim'),
('Termosun ısıyı korumasının sebebi nedir?', '["Yalıtım","İletim","Konveksiyon","Işıma artışı"]'::jsonb, 0, 'bilim'),
('Bir atomda proton sayısı neyi belirler?', '["Kütle numarasını","Elementi","Yükü","Bağ sayısını"]'::jsonb, 1, 'bilim'),
('Asit ve bazın tepkimesinden ne oluşur?', '["Sadece metal","Sadece gaz","Tuz ve su","Hiçbir şey"]'::jsonb, 2, 'bilim'),
('pH değeri 7 olan çözelti nasıldır?', '["Tuzlu","Asidik","Bazik","Nötr"]'::jsonb, 3, 'bilim'),
('Bir kimyasal tepkimede korunan şey nedir?', '["Kütle","Renk","Koku","Sıcaklık"]'::jsonb, 0, 'bilim'),

('Türkiye''nin en fazla göl bulunan bölgesi hangisidir?', '["Karadeniz","Akdeniz","Marmara","Güneydoğu Anadolu"]'::jsonb, 1, 'cografya'),
('Akarsuyun taşıdığı maddeleri biriktirmesine ne denir?', '["Taşıma","Aşındırma","Biriktirme","Buharlaşma"]'::jsonb, 2, 'cografya'),
('Rüzgârın oluşturduğu yer şekillerinden biri hangisidir?', '["Moren","Delta","Peribacası oluşumu","Kumul"]'::jsonb, 3, 'cografya'),
('Buzulların oluşturduğu birikinti şekline ne denir?', '["Moren","Kumul","Delta","Traverten"]'::jsonb, 0, 'cografya'),
('Kalker (kireç taşı) alanlarında oluşan yer şekline ne denir?', '["Kumul","Karst","Moren","Delta"]'::jsonb, 1, 'cografya'),
('Sıcak su kaynaklarının biriktirdiği taşa ne denir?', '["Granit","Bazalt","Traverten","Mermer"]'::jsonb, 2, 'cografya'),
('Volkanik faaliyetle oluşan kayaç türü hangisidir?', '["Organik","Tortul","Başkalaşım","Püskürük"]'::jsonb, 3, 'cografya'),
('Kömür hangi kayaç grubundadır?', '["Tortul","Püskürük","Başkalaşım","Volkanik"]'::jsonb, 0, 'cografya'),
('Mermer hangi kayacın başkalaşmasıyla oluşur?', '["Granit","Kireç taşı","Bazalt","Kum taşı"]'::jsonb, 1, 'cografya'),
('Muson iklimi en çok hangi bölgede görülür?', '["Batı Avrupa","Kuzey Afrika","Güney ve Güneydoğu Asya","Orta Amerika"]'::jsonb, 2, 'cografya'),
('Tundra iklimi nerede görülür?', '["Akdeniz kıyıları","Ekvator","Çöller","Kutuplara yakın bölgeler"]'::jsonb, 3, 'cografya'),
('Ekvator çevresinde görülen iklim hangisidir?', '["Ekvatoral","Tundra","Karasal","Akdeniz"]'::jsonb, 0, 'cografya'),

('Servet-i Fünun edebiyatı hangi dönemde ortaya çıkmıştır?', '["Cumhuriyet sonrası","Tanzimat sonrası","Divan dönemi","Halk edebiyatı dönemi"]'::jsonb, 1, 'edebiyat'),
('Garip akımının öncülerinden biri kimdir?', '["Yahya Kemal","Necip Fazıl","Orhan Veli","Ahmet Haşim"]'::jsonb, 2, 'edebiyat'),
('"Han Duvarları" şiiri kime aittir?', '["Nazım Hikmet","Orhan Veli","Cahit Sıtkı","Faruk Nafiz Çamlıbel"]'::jsonb, 3, 'edebiyat'),
('Kuyucaklı Yusuf romanının yazarı kimdir?', '["Sabahattin Ali","Sait Faik","Halit Ziya","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında hikâyeciliğiyle tanınan Sait Faik''in soyadı nedir?', '["Karaosmanoğlu","Abasıyanık","Uşaklıgil","Güntekin"]'::jsonb, 1, 'edebiyat'),
('Divan şiirinde gazelin ilk beytine ne denir?', '["Beyit","Makta","Matla","Mısra"]'::jsonb, 2, 'edebiyat'),
('Divan şiirinde şairin mahlasının geçtiği beyte ne denir?', '["Kıta","Matla","Nakarat","Makta"]'::jsonb, 3, 'edebiyat'),
('Halk edebiyatında saz şairlerine ne denir?', '["Aşık","Kadı","Meddah","Hattat"]'::jsonb, 0, 'edebiyat'),
('Türk halk edebiyatında 11''li hece ölçüsüyle yazılan nazım biçimi hangisidir?', '["Gazel","Koşma","Kaside","Rubai"]'::jsonb, 1, 'edebiyat'),
('Karacaoğlan hangi edebiyat geleneğindendir?', '["Servet-i Fünun","Divan edebiyatı","Halk edebiyatı","Fecr-i Ati"]'::jsonb, 2, 'edebiyat'),

('Voleybolda maç en fazla kaç sette biter?', '["7","3","4","5"]'::jsonb, 3, 'spor'),
('Basketbolda serbest atış kaç sayıdır?', '["1","2","3","4"]'::jsonb, 0, 'spor'),
('Hentbolda sahada kaç oyuncu bulunur?', '["6","7","5","8"]'::jsonb, 1, 'spor'),
('Olimpiyatlarda madalya sıralaması nasıldır?', '["Gümüş, altın, bronz","Bronz, gümüş, altın","Altın, gümüş, bronz","Altın, bronz, gümüş"]'::jsonb, 2, 'spor'),
('Modern olimpiyatların kurucusu kimdir?', '["Jacques Rogge","Juan Antonio Samaranch","Avery Brundage","Pierre de Coubertin"]'::jsonb, 3, 'spor'),
('Paralimpik Oyunlar kimler içindir?', '["Engelli sporcular","Gençler","Profesyoneller","Amatörler"]'::jsonb, 0, 'spor'),
('Satrançta piyonun sona ulaşmasına ne denir?', '["Rok","Terfi","Pat","Şah"]'::jsonb, 1, 'spor'),

('Empresyonizmin ünlü ressamlarından biri kimdir?', '["Vermeer","Rembrandt","Monet","Goya"]'::jsonb, 2, 'sanat'),
('Sürrealizm akımının ünlü ressamı kimdir?', '["Degas","Monet","Renoir","Salvador Dali"]'::jsonb, 3, 'sanat'),
('Bir yapının iç mekân düzenlemesine ne denir?', '["İç mimari","Peyzaj","Heykel","Grafik"]'::jsonb, 0, 'sanat'),
('Barok mimarinin özelliği nedir?', '["Sadeleşme","Zengin süsleme","Düz çizgiler","Renksizlik"]'::jsonb, 1, 'sanat'),
('Fresk nedir?', '["Bir müzik biçimi","Heykel türü","Duvar resmi","Bir dans"]'::jsonb, 2, 'sanat'),
('Mozaik sanatında kullanılan küçük parçalara ne denir?', '["Kalıp","Palet","Fırça","Tessera"]'::jsonb, 3, 'sanat'),
('Seramik yapımında son aşama hangisidir?', '["Pişirme","Yoğurma","Kesme","Kurutma öncesi"]'::jsonb, 0, 'sanat'),
('Perspektif ne sağlar?', '["Renk uyumu","Derinlik hissi","Ses dengesi","Işık kaybı"]'::jsonb, 1, 'sanat'),

('Animasyon filmlerde görüntüler nasıl hareket eder?', '["Sesle","Tek kareyle","Ardışık karelerle","Işıkla"]'::jsonb, 2, 'sinema'),
('Sinemada kameranın yavaşça yaklaşmasına ne denir?', '["Efekt","Kesme","Kurgu","Zoom"]'::jsonb, 3, 'sinema'),
('Bir filmin tanıtım videosuna ne denir?', '["Fragman","Jenerik","Altyazı","Afiş"]'::jsonb, 0, 'sinema'),
('Filmin başında veya sonunda geçen isim listesine ne denir?', '["Fragman","Jenerik","Senaryo","Dekor"]'::jsonb, 1, 'sinema'),
('Bir filmde oyuncuların konuşmalarına ne denir?', '["Kurgu","Dekor","Diyalog","Işık"]'::jsonb, 2, 'sinema'),
('Yeşilçam hangi ülkenin sinemasıyla anılır?', '["Mısır","İtalya","Yunanistan","Türkiye"]'::jsonb, 3, 'sinema'),
('Belgesel film neyi anlatır?', '["Gerçek olayları","Sadece kurguyu","Sadece çizgi filmi","Sadece reklamı"]'::jsonb, 0, 'sinema'),
('Sinemada "kurgu" ne demektir?', '["Işık ayarı","Çekimlerin birleştirilmesi","Ses kaydı","Kostüm seçimi"]'::jsonb, 1, 'sinema'),
('Bir dizinin bölümlerinden oluşan gruba ne denir?', '["Kıta","Perde","Sezon","Set"]'::jsonb, 2, 'sinema'),
('Filmde başrol oyuncusuna ne denir?', '["Suflör","Figüran","Dublör","Başrol"]'::jsonb, 3, 'sinema'),

('Bir bilgisayar dosyasının uzantısı neyi gösterir?', '["Dosya türünü","Dosya boyutunu","Oluşturma tarihini","Sahibini"]'::jsonb, 0, 'teknoloji'),
('HTML ne için kullanılır?', '["Resim çizmek","Web sayfası oluşturmak","Ses kaydetmek","Video kesmek"]'::jsonb, 1, 'teknoloji'),
('Bir yazılımın hatasına ne denir?', '["Bit","Byte","Bug","Bot"]'::jsonb, 2, 'teknoloji'),
('Verilerin en küçük birimi nedir?', '["Megabayt","Byte","Kilobayt","Bit"]'::jsonb, 3, 'teknoloji'),
('Bir byte kaç bittir?', '["8","4","16","32"]'::jsonb, 0, 'teknoloji'),
('SSD''nin sabit diske göre avantajı nedir?', '["Daha ağır olması","Daha hızlı olması","Daha gürültülü olması","Daha büyük olması"]'::jsonb, 1, 'teknoloji'),
('Ekran çözünürlüğü neyi ifade eder?', '["Parlaklığı","Renk sayısını","Piksel sayısını","Boyutu"]'::jsonb, 2, 'teknoloji'),
('Bir cihazın şarj süresini etkileyen temel bileşen hangisidir?', '["Hoparlör","Ekran","Kasa","Batarya"]'::jsonb, 3, 'teknoloji'),
('QR kod ne işe yarar?', '["Bilgi taşımak","Isı ölçmek","Ses üretmek","Işık yaymak"]'::jsonb, 0, 'teknoloji'),
('İki adımlı doğrulama neyi artırır?', '["Hızı","Güvenliği","Depolamayı","Parlaklığı"]'::jsonb, 1, 'teknoloji'),

('Notaların sırası nasıldır?', '["Re do mi fa sol si la","Do mi re fa la sol si","Do re mi fa sol la si","Mi do re fa sol la si"]'::jsonb, 2, 'muzik'),
('Bir müzik eserinde sesin şiddetini gösteren işaretlere ne denir?', '["Bağ","Anahtar","Ölçü çizgisi","Nüans işaretleri"]'::jsonb, 3, 'muzik'),
('Türk müziğinde kullanılan makam kavramı neyi belirler?', '["Ses dizisini","Ritmi","Sözleri","Enstrümanı"]'::jsonb, 0, 'muzik'),
('Bir şarkının sözlerini yazan kişiye ne denir?', '["Besteci","Söz yazarı","Aranjör","Şef"]'::jsonb, 1, 'muzik'),
('Aranjman ne demektir?', '["Söz yazmak","Bestelemek","Düzenleme","Sahnelemek"]'::jsonb, 2, 'muzik'),
('Koro nedir?', '["Bir salon","Tek kişi","Bir çalgı","Topluca söyleyen grup"]'::jsonb, 3, 'muzik'),
('Metronom ne işe yarar?', '["Tempo tutmak","Ses yükseltmek","Nota yazmak","Akort etmek"]'::jsonb, 0, 'muzik'),
('Bir çalgının doğru sese ayarlanmasına ne denir?', '["Nüans","Akort","Ritim","Ölçü"]'::jsonb, 1, 'muzik'),
('Türk halk müziğinde kullanılan uzun havanın özelliği nedir?', '["Sabit ölçü","Hızlı tempo","Serbest ritim","Elektronik ses"]'::jsonb, 2, 'muzik')

on conflict (soru) do nothing;

-- ===================== EK BÖLÜM =====================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- Türkiye: ilçeler, yöreler, simgeler
('Kapadokya''daki Göreme Açık Hava Müzesi hangi ilimizdedir?', '["Niğde","Kayseri","Aksaray","Nevşehir"]'::jsonb, 3, 'genel_kultur'),
('Kuşadası ilçesi hangi ilimize bağlıdır?', '["Aydın","İzmir","Muğla","Denizli"]'::jsonb, 0, 'genel_kultur'),
('Ayvalık ilçesi hangi ilimize bağlıdır?', '["Çanakkale","Balıkesir","İzmir","Manisa"]'::jsonb, 1, 'genel_kultur'),
('Şile ilçesi hangi ilimize bağlıdır?', '["Sakarya","Kocaeli","İstanbul","Zonguldak"]'::jsonb, 2, 'genel_kultur'),
('Karadeniz''de sis ve yağışın çok olmasının temel sebebi nedir?', '["Volkanik faaliyet","Çöl etkisi","Buzul etkisi","Dağların denize paralel uzanması"]'::jsonb, 3, 'genel_kultur'),
('Kaçkar Dağları hangi bölgemizdedir?', '["Karadeniz","Doğu Anadolu","İç Anadolu","Marmara"]'::jsonb, 0, 'genel_kultur'),
('Palandöken Kayak Merkezi hangi ilimizdedir?', '["Erzincan","Erzurum","Kars","Ardahan"]'::jsonb, 1, 'genel_kultur'),
('Kartepe Kayak Merkezi hangi ilimizdedir?', '["Bolu","Sakarya","Kocaeli","Düzce"]'::jsonb, 2, 'genel_kultur'),
('Kapıkule Sınır Kapısı hangi ilimizdedir?', '["Çanakkale","Kırklareli","Tekirdağ","Edirne"]'::jsonb, 3, 'genel_kultur'),
('Sarıkamış hangi ilimizin ilçesidir?', '["Kars","Ardahan","Erzurum","Iğdır"]'::jsonb, 0, 'genel_kultur'),
('Ortaçağda Anadolu''da kervan yollarındaki konaklama yapılarına ne ad verilirdi?', '["Kale","Han","Sur","Bedesten"]'::jsonb, 1, 'genel_kultur'),
('İshak Paşa Sarayı hangi ilimizdedir?', '["Bitlis","Van","Ağrı","Muş"]'::jsonb, 2, 'genel_kultur'),
('Akdamar Kilisesi hangi ilimizdedir?', '["Ağrı","Bitlis","Muş","Van"]'::jsonb, 3, 'genel_kultur'),
('Mardin hangi mimari özelliğiyle tanınır?', '["Taş evleri","Ahşap evleri","Kerpiç kubbeleri","Cam kuleleri"]'::jsonb, 0, 'genel_kultur'),
('Bir gölün suyunun tuzlu olmasının başlıca sebebi nedir?', '["Derin olması","Dışarıya gideğeninin olmaması","Soğuk olması","Küçük olması"]'::jsonb, 1, 'genel_kultur'),
('Diyarbakır surları hangi taştan yapılmıştır?', '["Granit","Mermer","Bazalt","Kum taşı"]'::jsonb, 2, 'genel_kultur'),
('Harran evleri hangi biçimiyle bilinir?', '["Cam cepheli","Düz çatılı","Ahşap iskeletli","Konik kubbeli"]'::jsonb, 3, 'genel_kultur'),
('Sultansazlığı Milli Parkı hangi ilimizdedir?', '["Kayseri","Niğde","Nevşehir","Yozgat"]'::jsonb, 0, 'genel_kultur'),
('Köyceğiz Gölü hangi ilimizdedir?', '["Aydın","Muğla","Antalya","Denizli"]'::jsonb, 1, 'genel_kultur'),
('Kaz Dağları hangi adla da anılır?', '["Nemrut","Olimpos","İda Dağı","Ararat"]'::jsonb, 2, 'genel_kultur'),
('Şirince köyü hangi ilimizdedir?', '["Muğla","Aydın","Manisa","İzmir"]'::jsonb, 3, 'genel_kultur'),
('Amasra hangi ilimizin ilçesidir?', '["Bartın","Zonguldak","Kastamonu","Sinop"]'::jsonb, 0, 'genel_kultur'),
('Beypazarı hangi ilimizin ilçesidir?', '["Eskişehir","Ankara","Bolu","Çankırı"]'::jsonb, 1, 'genel_kultur'),

-- Dünya şehirleri ve simge yapılar
('Sagrada Familia hangi şehirdedir?', '["Sevilla","Madrid","Barselona","Valensiya"]'::jsonb, 2, 'genel_kultur'),
('Louvre Müzesi hangi şehirdedir?', '["Viyana","Londra","Madrid","Paris"]'::jsonb, 3, 'genel_kultur'),
('British Museum hangi şehirdedir?', '["Londra","Paris","Berlin","Roma"]'::jsonb, 0, 'genel_kultur'),
('Prado Müzesi hangi şehirdedir?', '["Barselona","Madrid","Lizbon","Roma"]'::jsonb, 1, 'genel_kultur'),
('Uffizi Galerisi hangi şehirdedir?', '["Venedik","Roma","Floransa","Milano"]'::jsonb, 2, 'genel_kultur'),
('Hermitage Müzesi hangi şehirdedir?', '["Minsk","Moskova","Kiev","St. Petersburg"]'::jsonb, 3, 'genel_kultur'),
('Opera Binası simgesiyle bilinen şehir hangisidir?', '["Sidney","Melbourne","Auckland","Perth"]'::jsonb, 0, 'genel_kultur'),
('Brandenburg Kapısı hangi şehirdedir?', '["Münih","Berlin","Hamburg","Köln"]'::jsonb, 1, 'genel_kultur'),
('Atomium yapısı hangi şehirdedir?', '["Lüksemburg","Amsterdam","Brüksel","Bern"]'::jsonb, 2, 'genel_kultur'),
('Megalitik yapılar hangi dönemden kalmadır?', '["Orta Çağ sonu","Sanayi Devrimi","Rönesans","Tarih öncesi"]'::jsonb, 3, 'genel_kultur'),
('Moai heykelleri hangi adada bulunur?', '["Paskalya Adası","Bali","Sicilya","Malta"]'::jsonb, 0, 'genel_kultur'),
('Alhambra Sarayı hangi ülkededir?', '["Portekiz","İspanya","Fas","İtalya"]'::jsonb, 1, 'genel_kultur'),
('Neuschwanstein Şatosu hangi ülkededir?', '["İsviçre","Avusturya","Almanya","Fransa"]'::jsonb, 2, 'genel_kultur'),
('Notre-Dame Katedrali hangi şehirdedir?', '["Rouen","Reims","Lyon","Paris"]'::jsonb, 3, 'genel_kultur'),
('Sultan Ahmet Meydanı''ndaki dikilitaş hangi uygarlıktan gelmiştir?', '["Mısır","Roma","Yunan","Pers"]'::jsonb, 0, 'genel_kultur'),
('Times Meydanı hangi şehirdedir?', '["Los Angeles","New York","Chicago","Miami"]'::jsonb, 1, 'genel_kultur'),

-- Mutfak, baharat, beslenme
('Tarçın hangi bitkinin kabuğundan elde edilir?', '["Yaprak","Kök","Ağaç kabuğu","Çiçek"]'::jsonb, 2, 'genel_kultur'),
('Safran hangi bitki kısmından elde edilir?', '["Tohum","Kök","Kabuk","Çiçek tepeciği"]'::jsonb, 3, 'genel_kultur'),
('Karabiber hangi bitkinin ürünüdür?', '["Tırmanıcı bir bitki","Ağaç kökü","Yosun","Mantar"]'::jsonb, 0, 'genel_kultur'),
('Vanilya hangi bitkiden elde edilir?', '["Gül","Orkide","Papatya","Lale"]'::jsonb, 1, 'genel_kultur'),
('Zencefil hangi bitki kısmıdır?', '["Çiçek","Yaprak","Kök gövde","Meyve"]'::jsonb, 2, 'genel_kultur'),
('Kimyon hangi tür baharattır?', '["Kök","Kabuk","Yaprak","Tohum"]'::jsonb, 3, 'genel_kultur'),
('Nane hangi bitki kısmı olarak kullanılır?', '["Yaprak","Kök","Tohum","Kabuk"]'::jsonb, 0, 'genel_kultur'),
('Hangi pişirme yöntemi yağsızdır?', '["Kızartma","Haşlama","Kavurma","Sote"]'::jsonb, 1, 'genel_kultur'),
('Fırında pişirme hangi ısı yoluyla olur?', '["Su buharı yok","Doğrudan alev","Sıcak hava","Soğuk hava"]'::jsonb, 2, 'genel_kultur'),
('Buharda pişirmenin avantajı nedir?', '["Şeker katar","Yağ ekler","Tuz artırır","Besin değerini korur"]'::jsonb, 3, 'genel_kultur'),
('Hamur işlerinde kabartma tozu ne sağlar?', '["Kabarma","Renk","Tuzluluk","Sertlik"]'::jsonb, 0, 'genel_kultur'),
('Yoğurdun mayalanmasını sağlayan canlılar hangileridir?', '["Mantarlar","Bakteriler","Virüsler","Algler"]'::jsonb, 1, 'genel_kultur'),
('Ekmeğin bayatlamasını yavaşlatan saklama yöntemi hangisidir?', '["Isıtmak","Açıkta bırakmak","Dondurmak","Islatmak"]'::jsonb, 2, 'genel_kultur'),
('Konservenin amacı nedir?', '["Ağırlaştırmak","Tat vermek","Renk katmak","Uzun süre saklamak"]'::jsonb, 3, 'genel_kultur'),
('Pastörizasyon işlemi neyi hedefler?', '["Zararlı mikropları azaltmak","Şeker eklemek","Renk vermek","Yağ artırmak"]'::jsonb, 0, 'genel_kultur'),

-- Hayvanlar ileri
('Balinaların soluk alması nasıl olur?', '["Solungaçla","Su yüzeyine çıkarak","Deriyle","Hiç almazlar"]'::jsonb, 1, 'genel_kultur'),
('Deniz kaplumbağaları yumurtalarını nereye bırakır?', '["Ağaca","Denize","Kumsala","Kayalığa"]'::jsonb, 2, 'genel_kultur'),
('Fillerin en belirgin organı hangisidir?', '["Kabuk","Yele","Boynuz","Hortum"]'::jsonb, 3, 'genel_kultur'),
('Kanguruların yavrularını taşıdığı yapıya ne denir?', '["Kese","Kovan","Yuva","Kabuk"]'::jsonb, 0, 'genel_kultur'),
('Timsahlar hangi hayvan grubundandır?', '["Memeliler","Sürüngenler","İki yaşamlılar","Balıklar"]'::jsonb, 1, 'genel_kultur'),
('Köpekbalıkları hangi hayvan grubundandır?', '["Sürüngenler","Memeliler","Balıklar","Kuşlar"]'::jsonb, 2, 'genel_kultur'),
('Yarasalar hangi hayvan grubundandır?', '["Böcekler","Kuşlar","Sürüngenler","Memeliler"]'::jsonb, 3, 'genel_kultur'),
('Salyangozun sırtındaki yapıya ne denir?', '["Kabuk","Kanat","Yele","Pul"]'::jsonb, 0, 'genel_kultur'),
('Arı, karınca ve termitlerin ortak özelliği nedir?', '["Uçamamaları","Koloni halinde yaşamaları","Suda yaşamaları","Etçil olmaları"]'::jsonb, 1, 'genel_kultur'),
('Bir hayvanın çevresine uyum sağlayan renk değişimine ne denir?', '["Kış uykusu","Göç","Kamuflaj","Başkalaşım"]'::jsonb, 2, 'genel_kultur'),
('Kurbağanın gelişim evrelerinden biri hangisidir?', '["Yumurta kabuğu","Krizalit","Larva kozası","İribaş"]'::jsonb, 3, 'genel_kultur'),
('Hangi hayvan grubunun vücut sıcaklığı sabittir?', '["Memeliler","Sürüngenler","Balıklar","İki yaşamlılar"]'::jsonb, 0, 'genel_kultur'),
('Bir hayvanın avlanmak için kullandığı keskin dişlere ne denir?', '["Azı dişi","Köpek dişi","Kesici diş","Süt dişi"]'::jsonb, 1, 'genel_kultur'),
('Kuşlarda yumurtaların korunduğu yapı hangisidir?', '["İn","Kovan","Yuva","Kabuk kesesi"]'::jsonb, 2, 'genel_kultur'),

-- Uzay ileri
('Güneş sisteminde Dünya kaçıncı gezegendir?', '["5","2","4","3"]'::jsonb, 3, 'genel_kultur'),
('Asteroit kuşağı hangi iki gezegen arasındadır?', '["Mars ve Jüpiter","Dünya ve Mars","Venüs ve Dünya","Satürn ve Uranüs"]'::jsonb, 0, 'genel_kultur'),
('Kuyruklu yıldızların kuyruğu neden oluşur?', '["Yer çekimi","Güneş rüzgârı","Manyetik alan","Atmosfer"]'::jsonb, 1, 'genel_kultur'),
('Dünyamızın bulunduğu galaksinin adı nedir?', '["Üçgen","Andromeda","Samanyolu","Sombrero"]'::jsonb, 2, 'genel_kultur'),
('Yıldızların enerji kaynağı nedir?', '["Elektrik","Yanma","Sürtünme","Nükleer füzyon"]'::jsonb, 3, 'genel_kultur'),
('Güneş hangi tür gök cismidir?', '["Yıldız","Gezegen","Uydu","Asteroit"]'::jsonb, 0, 'genel_kultur'),
('Ay''ın evrelerinden biri hangisidir?', '["Gündönümü","Dolunay","Ekinoks","Tutulma yılı"]'::jsonb, 1, 'genel_kultur'),
('Uzayda ses neden duyulmaz?', '["Işık hızlı olduğu için","Çok soğuk olduğu için","Ortam boşluk olduğu için","Yer çekimi yok diye"]'::jsonb, 2, 'genel_kultur'),
('Teleskop ne işe yarar?', '["Konum belirlemek","Ses yükseltmek","Isı ölçmek","Uzak cisimleri gözlemlemek"]'::jsonb, 3, 'genel_kultur'),
('Bir gezegenin kendi ekseni etrafındaki dönüşüne ne denir?', '["Rotasyon","Revolüsyon","Yörünge","Eğim"]'::jsonb, 0, 'genel_kultur'),
('Bir gezegenin Güneş etrafındaki dolanımına ne denir?', '["Rotasyon","Revolüsyon","Tutulma","Evre"]'::jsonb, 1, 'genel_kultur'),
('Uzay giysisinin temel görevi nedir?', '["Renk vermek","Isıtmak","Basınç ve oksijen sağlamak","Hız kazandırmak"]'::jsonb, 2, 'genel_kultur'),
('Roketlerin uzaya çıkabilmesi için aşması gereken şey nedir?', '["Manyetik alan","Ses hızı","Işık hızı","Yer çekimi"]'::jsonb, 3, 'genel_kultur'),
('Bir yıldızın ömrünü tamamlayıp patlamasına ne denir?', '["Süpernova","Nebula","Kara delik","Meteor"]'::jsonb, 0, 'genel_kultur'),

-- Ekonomi, hukuk, vatandaşlık
('Türkiye''de yasama görevini kim yürütür?', '["Cumhurbaşkanlığı","TBMM","Yargıtay","Danıştay"]'::jsonb, 1, 'genel_kultur'),
('Bir suçun cezasının kanunla belirlenmesi ilkesine ne denir?', '["Adalet","Eşitlik","Kanunilik","Bağımsızlık"]'::jsonb, 2, 'genel_kultur'),
('Mahkemede iddia makamını kim temsil eder?', '["Katip","Avukat","Hakim","Savcı"]'::jsonb, 3, 'genel_kultur'),
('Bir kişinin suçsuz sayılması ilkesine ne denir?', '["Masumiyet karinesi","İtiraz hakkı","Temyiz","Tebligat"]'::jsonb, 0, 'genel_kultur'),
('Kanunları uygulama görevi kime aittir?', '["Yasama","Yürütme","Yargı","Basın"]'::jsonb, 1, 'genel_kultur'),
('Uyuşmazlıkları çözen erk hangisidir?', '["Yürütme","Yasama","Yargı","Basın"]'::jsonb, 2, 'genel_kultur'),
('Tüketici haklarından biri hangisidir?', '["Vergi muafiyeti","Ücretsiz her ürün","Sınırsız kredi","Ayıplı malı iade"]'::jsonb, 3, 'genel_kultur'),
('Bir sözleşmenin geçerli olması için ne gerekir?', '["Tarafların rızası","Sadece imza rengi","Tanık sayısı 10","Noter zorunluluğu her zaman"]'::jsonb, 0, 'genel_kultur'),
('Telif hakkı neyi korur?', '["Arsa sınırlarını","Eser sahibinin haklarını","Trafik kurallarını","Vergi oranlarını"]'::jsonb, 1, 'genel_kultur'),
('Patent neyi korur?', '["Şarkı sözünü","Marka adını","Buluşu","Fotoğrafı"]'::jsonb, 2, 'genel_kultur'),
('Marka tescili neyi korur?', '["Yazılım kodunu","Buluşu","Kitap metnini","Ticari işareti"]'::jsonb, 3, 'genel_kultur'),
('Bir işletmenin gelir ve giderlerini kaydeden dal hangisidir?', '["Muhasebe","Pazarlama","Lojistik","İnsan kaynakları"]'::jsonb, 0, 'genel_kultur'),
('Kredi kartında "limit" ne anlama gelir?', '["Faiz oranı","Harcanabilecek üst sınır","Kart ücreti","Puan miktarı"]'::jsonb, 1, 'genel_kultur'),
('Bir ürünün maliyetinin üzerine eklenen paya ne denir?', '["Vergi","Zarar","Kâr","İskonto"]'::jsonb, 2, 'genel_kultur'),
('İndirim oranı %50 olan 200 TL''lik ürün kaç TL olur?', '["120","150","50","100"]'::jsonb, 3, 'genel_kultur'),

-- Enerji, çevre, madencilik
('Hidroelektrik enerji neyden üretilir?', '["Akan sudan","Rüzgârdan","Güneşten","Kömürden"]'::jsonb, 0, 'genel_kultur'),
('Jeotermal enerji neyden elde edilir?', '["Rüzgârdan","Yer altı sıcak sularından","Dalgadan","Odundan"]'::jsonb, 1, 'genel_kultur'),
('Güneş panelleri neyi dönüştürür?', '["Isıyı sese","Sesi ışığa","Işığı elektriğe","Suyu yağa"]'::jsonb, 2, 'genel_kultur'),
('Fosil yakıtlardan biri hangisidir?', '["Dalga","Rüzgâr","Güneş","Petrol"]'::jsonb, 3, 'genel_kultur'),
('Sera etkisine en çok katkı yapan gazlardan biri hangisidir?', '["Karbondioksit","Azot","Helyum","Neon"]'::jsonb, 0, 'genel_kultur'),
('Atık suların temizlendiği tesise ne denir?', '["Termik santral","Arıtma tesisi","Rafineri","Fabrika"]'::jsonb, 1, 'genel_kultur'),
('Plastiklerin doğada kalıcı olmasının sebebi nedir?', '["Renkli olmaları","Hafif olmaları","Zor çözünmeleri","Ucuz olmaları"]'::jsonb, 2, 'genel_kultur'),
('Kompost nedir?', '["Bir yakıt","Bir tür plastik","Bir metal","Organik atıktan gübre"]'::jsonb, 3, 'genel_kultur'),
('Karbon ayak izi neyi ölçer?', '["Salınan sera gazını","Ayakkabı numarasını","Su tüketimini yalnızca","Elektrik faturasını"]'::jsonb, 0, 'genel_kultur'),
('Petrolün işlendiği tesise ne denir?', '["Maden ocağı","Rafineri","Arıtma","Santral"]'::jsonb, 1, 'genel_kultur'),
('Bor madeni hangi ülkede zengin olarak bulunur?', '["İrlanda","İzlanda","Türkiye","Portekiz"]'::jsonb, 2, 'genel_kultur'),
('Kömürün en çok kullanıldığı alan hangisidir?', '["İlaç yapımı","Cam yapımı","Kumaş üretimi","Enerji üretimi"]'::jsonb, 3, 'genel_kultur'),
('Doğal gazın taşınmasında kullanılan yapı hangisidir?', '["Boru hattı","Demiryolu tüneli","Kanal","Baraj"]'::jsonb, 0, 'genel_kultur'),
('Nükleer santrallerde enerji nasıl elde edilir?', '["Rüzgârla","Çekirdek tepkimesiyle","Dalgayla","Güneşle"]'::jsonb, 1, 'genel_kultur'),

-- Giyim, kumaş, moda
('İpek hangi böcekten elde edilir?', '["Karınca","Arı","İpek böceği","Kelebek"]'::jsonb, 2, 'genel_kultur'),
('Kot kumaşının bilinen adı nedir?', '["Saten","Keten","Kadife","Denim"]'::jsonb, 3, 'genel_kultur'),
('Yün hangi mevsimde tercih edilir?', '["Kış","Yaz","İlkbahar sonu","Hasat"]'::jsonb, 0, 'genel_kultur'),
('Kumaşın dokunduğu makineye ne denir?', '["Fırın","Dokuma tezgâhı","Pres","Torna"]'::jsonb, 1, 'genel_kultur'),
('Bir giysinin bedenini belirleyen ölçü nedir?', '["Kumaş türü","Renk","Vücut ölçüleri","Marka"]'::jsonb, 2, 'genel_kultur'),
('Ayakkabıda numara neyi gösterir?', '["Ağırlığı","Rengi","Malzemeyi","Uzunluğu"]'::jsonb, 3, 'genel_kultur'),
('Deri ürünlerin bakımında ne kullanılır?', '["Deri bakım kremi","Çamaşır suyu","Aseton","Tuz ruhu"]'::jsonb, 0, 'genel_kultur'),
('Kumaşın çekmesini önlemek için ne yapılır?', '["Kaynatmak","Uygun sıcaklıkta yıkamak","Ütüsüz bırakmak","Islak katlamak"]'::jsonb, 1, 'genel_kultur'),
('Bir giysideki etikette ne bilgisi bulunur?', '["Adres","Fiyat listesi","Yıkama talimatı","Telefon"]'::jsonb, 2, 'genel_kultur'),
('Geleneksel Türk el sanatlarından biri hangisidir?', '["Cam üfleme yalnızca İtalyan","Origami","Batik yalnızca Japon","Halı dokuma"]'::jsonb, 3, 'genel_kultur'),

-- Meteoroloji, zaman, ölçüm
('Havadaki nem oranını ölçen alet hangisidir?', '["Higrometre","Barometre","Anemometre","Sismograf"]'::jsonb, 0, 'genel_kultur'),
('Yağış miktarını ölçen alet hangisidir?', '["Anemometre","Plüviyometre","Barometre","Termometre"]'::jsonb, 1, 'genel_kultur'),
('Dünya kaç saat diliminden oluşur?', '["36","12","24","48"]'::jsonb, 2, 'genel_kultur'),
('Greenwich hangi ülkededir?', '["Belçika","Fransa","Hollanda","İngiltere"]'::jsonb, 3, 'genel_kultur'),
('Bir ışık yılı neyi ölçer?', '["Uzaklığı","Zamanı","Kütleyi","Sıcaklığı"]'::jsonb, 0, 'genel_kultur'),
('Miladi takvim neye göre düzenlenmiştir?', '["Ay yılına","Güneş yılına","Yıldızlara","Gelgite"]'::jsonb, 1, 'genel_kultur'),
('Hicri takvim neye göre düzenlenmiştir?', '["Yıldızlara","Güneş yılına","Ay yılına","Mevsimlere"]'::jsonb, 2, 'genel_kultur'),
('Bir artık yılda şubat kaç gün çeker?', '["31","28","30","29"]'::jsonb, 3, 'genel_kultur'),
('Saat kaç dilime bölünmüş bir kadrana sahiptir?', '["12","24","60","10"]'::jsonb, 0, 'genel_kultur'),
('Kronometre ne ölçer?', '["Ağırlığı","Süreyi","Uzunluğu","Sıcaklığı"]'::jsonb, 1, 'genel_kultur'),
('Bir milimetre kaç mikrometredir?', '["10","100","1000","10000"]'::jsonb, 2, 'genel_kultur'),
('Bir hektar kaç metrekaredir?', '["100","1000","100000","10000"]'::jsonb, 3, 'genel_kultur'),
('Bir dönüm yaklaşık kaç metrekaredir?', '["1000","100","10000","500"]'::jsonb, 0, 'genel_kultur'),
('Sıvı hacminde 1 metreküp kaç litredir?', '["100","1000","10","10000"]'::jsonb, 1, 'genel_kultur'),

-- Güvenlik, ilk yardım, afet
('Doğal gaz kokusu alındığında ilk ne yapılır?', '["Kibrit çakılır","Işık yakılır","Havalandırılır","Fan çalıştırılır"]'::jsonb, 2, 'genel_kultur'),
('Elektrik çarpmasında ilk yapılacak nedir?', '["Beklemek","Dokunmak","Su dökmek","Akımı kesmek"]'::jsonb, 3, 'genel_kultur'),
('Yangında dumandan korunmak için nasıl hareket edilir?', '["Eğilerek","Koşarak dik","Zıplayarak","Sürünmeden hızlı"]'::jsonb, 0, 'genel_kultur'),
('Deprem çantasında bulunması gerekenlerden biri nedir?', '["Cam eşya","Su ve el feneri","Ağır mobilya","Süs eşyası"]'::jsonb, 1, 'genel_kultur'),
('Deprem sonrası binaya girmeden önce ne yapılmalı?', '["Işık yakılmalı","Hemen girilmeli","Yetkili kontrolü beklenmeli","Asansör kullanılmalı"]'::jsonb, 2, 'genel_kultur'),
('Yüzme bilmeyen biri suda görülürse ne yapılır?', '["Bağırılmaz","Hemen atlanır","Beklenir","Yardım çağrılır"]'::jsonb, 3, 'genel_kultur'),
('Zehirlenme şüphesinde ne yapılmalıdır?', '["112 aranır","Su içirilir hemen","Kusturulur","Uyutulur"]'::jsonb, 0, 'genel_kultur'),
('Burun kanamasında baş nasıl tutulur?', '["Geriye atılır","Hafif öne eğilir","Yana yatırılır","Aşağı sarkıtılır"]'::jsonb, 1, 'genel_kultur'),
('İlk yardımda amaç nedir?', '["İlaç vermek","Tedavi etmek","Durumu kötüleştirmemek","Ameliyat yapmak"]'::jsonb, 2, 'genel_kultur'),
('Trafik kazasında yaralı ne zaman hareket ettirilmelidir?', '["Kalabalık varsa","Her zaman","Asla","Hayati tehlike varsa"]'::jsonb, 3, 'genel_kultur'),

-- Otomobil, havacılık, denizcilik
('Otomobilde motorun soğutulmasını sağlayan sıvı hangisidir?', '["Antifriz","Fren hidroliği","Motor yağı","Cam suyu"]'::jsonb, 0, 'genel_kultur'),
('Lastik basıncının düşük olması neye yol açar?', '["Hızın artmasına","Yakıt tüketiminin artmasına","Sesin azalmasına","Frenin güçlenmesine"]'::jsonb, 1, 'genel_kultur'),
('Aracın yön değiştirdiğini bildiren lamba hangisidir?', '["Stop","Far","Sinyal","Sis lambası"]'::jsonb, 2, 'genel_kultur'),
('Otomobilde ABS ne işe yarar?', '["Radyo açar","Hızı artırır","Klima çalıştırır","Frende tekerlek kilitlenmesini önler"]'::jsonb, 3, 'genel_kultur'),
('Hava yastığı ne zaman devreye girer?', '["Çarpışma anında","Park ederken","Motor çalışınca","Kapı açılınca"]'::jsonb, 0, 'genel_kultur'),
('Uçakta kabin basıncı neden ayarlanır?', '["Hız için","Yolcuların rahat solunumu için","Yakıt için","Ses için"]'::jsonb, 1, 'genel_kultur'),
('Uçakların kanat şekli neyi sağlar?', '["Isı yalıtımı","Ses yalıtımı","Kaldırma kuvveti","Renk uyumu"]'::jsonb, 2, 'genel_kultur'),
('Havalimanlarında uçakları yönlendiren birim hangisidir?', '["Güvenlik","Gişe","Bagaj","Kule"]'::jsonb, 3, 'genel_kultur'),
('Gemilerde denge sağlamak için kullanılan ağırlığa ne denir?', '["Safra","Çapa","Halat","Dümen"]'::jsonb, 0, 'genel_kultur'),
('Geminin durmasını sağlayan ağır demir parçası nedir?', '["Dümen","Çapa","Pervane","Direk"]'::jsonb, 1, 'genel_kultur'),

-- Türk büyükleri ve başarılar
('Aziz Sancar hangi alanda Nobel almıştır?', '["Tıp","Fizik","Kimya","Edebiyat"]'::jsonb, 2, 'genel_kultur'),
('Cahit Arf hangi alanda tanınır?', '["Müzik","Kimya","Tarih","Matematik"]'::jsonb, 3, 'genel_kultur'),
('Piri Reis hangi alanda tanınır?', '["Haritacılık","Mimarlık","Şiir","Tıp"]'::jsonb, 0, 'genel_kultur'),
('Ali Kuşçu hangi alanda çalışmıştır?', '["Mimarlık","Astronomi","Şiir","Denizcilik"]'::jsonb, 1, 'genel_kultur'),
('Uluğ Bey hangi alandaki çalışmalarıyla bilinir?', '["Hukuk","Tıp","Astronomi","Müzik"]'::jsonb, 2, 'genel_kultur'),
('Biruni hangi alanlarda eser vermiştir?', '["Sadece müzik","Sadece şiir","Sadece resim","Astronomi ve matematik"]'::jsonb, 3, 'genel_kultur'),
('Harezmi hangi kavramın gelişimine katkı sağlamıştır?', '["Cebir","Perspektif","Opera","Balet"]'::jsonb, 0, 'genel_kultur'),
('Itri hangi alanda tanınır?', '["Mimarlık","Müzik","Tıp","Coğrafya"]'::jsonb, 1, 'genel_kultur'),
('Katip Çelebi hangi alanda eser vermiştir?', '["Sadece dokuma","Sadece heykel","Bibliyografya ve coğrafya","Sadece resim"]'::jsonb, 2, 'genel_kultur'),

-- Genel kültür karışık ek
('Bir kütüphanede kitapların sınıflandırılması neye göre yapılır?', '["Fiyata göre","Renge göre","Ağırlığa göre","Konuya göre"]'::jsonb, 3, 'genel_kultur'),
('Ansiklopedi ne tür bir kaynaktır?', '["Başvuru kaynağı","Roman","Şiir kitabı","Günlük"]'::jsonb, 0, 'genel_kultur'),
('Bir haberin temel öğelerinden biri nedir?', '["Sadece başlık","Ne, nerede, ne zaman","Sadece fotoğraf","Sadece yorum"]'::jsonb, 1, 'genel_kultur'),
('Gazetenin ilk sayfasına ne denir?', '["Ek","Arka kapak","Manşet sayfası","İlan"]'::jsonb, 2, 'genel_kultur'),
('Reklamın temel amacı nedir?', '["Ölçüm","Eğitim","Yargılama","Tanıtım"]'::jsonb, 3, 'genel_kultur'),
('Bir anketin amacı nedir?', '["Görüş toplamak","Ürün satmak","Ceza vermek","İnşaat yapmak"]'::jsonb, 0, 'genel_kultur'),
('İstatistikte en sık tekrar eden değere ne denir?', '["Medyan","Mod","Ortalama","Aralık"]'::jsonb, 1, 'genel_kultur'),
('Sıralanmış verilerin ortasındaki değere ne denir?', '["Ortalama","Mod","Medyan","Sapma"]'::jsonb, 2, 'genel_kultur'),
('Bir grafikte sütunlar neyi gösterir?', '["Tarihleri yalnızca","Renkleri","İsimleri","Miktarları"]'::jsonb, 3, 'genel_kultur'),
('Pasta grafiği neyi göstermek için uygundur?', '["Oranları","Hızı","Sıcaklığı","Uzaklığı"]'::jsonb, 0, 'genel_kultur'),
('Bir toplantının yazılı kaydına ne denir?', '["Afiş","Tutanak","Broşür","Katalog"]'::jsonb, 1, 'genel_kultur'),
('Resmî yazışmalarda kullanılan üslup nasıldır?', '["Şiirsel","Şakacı","Resmî ve nesnel","Argo"]'::jsonb, 2, 'genel_kultur'),
('Bir dilekçede bulunması gereken bilgi hangisidir?', '["Sadece adres","Sadece tarih","Sadece konu","Ad, soyad ve imza"]'::jsonb, 3, 'genel_kultur'),
('İş görüşmesinde önemli olan davranış hangisidir?', '["Zamanında gelmek","Geç kalmak","Telefonla konuşmak","Sözü kesmek"]'::jsonb, 0, 'genel_kultur'),
('Takım çalışmasında en önemli unsur nedir?', '["Rekabet","İletişim","Sessizlik","Gizlilik"]'::jsonb, 1, 'genel_kultur'),
('Zaman yönetiminde ilk adım nedir?', '["Hızlanma","Erteleme","Önceliklendirme","Uyuma"]'::jsonb, 2, 'genel_kultur'),
('Bir problemi çözerken ilk aşama nedir?', '["Beklemek","Sonucu yazmak","Vazgeçmek","Problemi anlamak"]'::jsonb, 3, 'genel_kultur'),
('Eleştirel düşünme ne demektir?', '["Sorgulayarak değerlendirme","Kabul etme","Reddetme","Görmezden gelme"]'::jsonb, 0, 'genel_kultur'),
('Empati ne demektir?', '["Yargılamak","Kendini karşısındakinin yerine koymak","Susmak","Kaçmak"]'::jsonb, 1, 'genel_kultur'),
('Sağlıklı iletişimde önemli olan davranış hangisidir?', '["Bağırma","Sözü kesme","Etkin dinleme","Görmezden gelme"]'::jsonb, 2, 'genel_kultur'),
('Bir toplulukta ortak yaşam kurallarına ne denir?', '["Şarkılar","Hobiler","Sloganlar","Kurallar"]'::jsonb, 3, 'genel_kultur'),
('Gönüllülük ne demektir?', '["Karşılık beklemeden çalışmak","Ücretli çalışmak","Zorunlu görev","Ceza"]'::jsonb, 0, 'genel_kultur'),
('Bağış kampanyalarının amacı nedir?', '["Ürün satmak","Yardım toplamak","Ceza kesmek","Vergi almak"]'::jsonb, 1, 'genel_kultur'),
('Bir kurumun logosu neyi temsil eder?', '["Adresini","Fiyatını","Kimliğini","Personelini"]'::jsonb, 2, 'genel_kultur'),
('Kalite kontrol ne amaçlar?', '["Fiyat artışı","Hız artışı","Renk değişimi","Standartlara uygunluk"]'::jsonb, 3, 'genel_kultur'),
('Bir ürünün garanti süresi neyi ifade eder?', '["Ücretsiz onarım süresini","Raf ömrünü","Üretim süresini","Taşıma süresini"]'::jsonb, 0, 'genel_kultur'),
('Son kullanma tarihi neyi belirtir?', '["Üretim gününü","Güvenle tüketilebilecek son günü","Satış gününü","Teslim gününü"]'::jsonb, 1, 'genel_kultur'),
('Bir ilacın prospektüsü ne içerir?', '["Reklam","Fiyat listesi","Kullanım bilgisi","Anket"]'::jsonb, 2, 'genel_kultur'),
('Hijyen ne demektir?', '["Ağırlık","Hız","Renk","Temizlik ve sağlık koşulları"]'::jsonb, 3, 'genel_kultur'),
('Bir işyerinde iş güvenliği neyi hedefler?', '["Kazaları önlemek","Üretimi durdurmak","Maaş kesmek","Mesai artırmak"]'::jsonb, 0, 'genel_kultur'),
('Baret hangi amaçla kullanılır?', '["Görüş artırma","Baş koruma","Ses azaltma","Isınma"]'::jsonb, 1, 'genel_kultur'),
('Yangın tüpü kullanırken nereye püskürtülür?', '["Tavana","Dumana","Alevin dibine","Duvara"]'::jsonb, 2, 'genel_kultur'),
('Acil çıkış tabelaları genelde hangi renktedir?', '["Kahverengi","Mavi","Mor","Yeşil"]'::jsonb, 3, 'genel_kultur'),
('Kimyasal maddelerde tehlike işaretleri ne amaçlıdır?', '["Uyarı","Süsleme","Fiyatlandırma","Sınıflandırma yok"]'::jsonb, 0, 'genel_kultur'),
('Bir haritada ölçek 1/100.000 ise 1 cm kaç km''dir?', '["10","1","100","0,1"]'::jsonb, 1, 'genel_kultur'),
('Kroki ile harita arasındaki temel fark nedir?', '["Haritada yön yoktur","Krokide renk yoktur","Krokide ölçek yoktur","Fark yoktur"]'::jsonb, 2, 'genel_kultur'),
('Bir yerin coğrafi konumu neyle belirtilir?', '["Nüfus","Renk ve doku","Yükseklik yalnızca","Enlem ve boylam"]'::jsonb, 3, 'genel_kultur'),
('Pusulada kuzeyin kısaltması hangisidir?', '["K","G","D","B"]'::jsonb, 0, 'genel_kultur'),
('Doğu ile batı arasında kaç derece fark vardır (tam karşıt)?', '["90","180","270","360"]'::jsonb, 1, 'genel_kultur'),
('Yıldız kümelerine halk arasında ne denir?', '["Nebula","Gökada","Takımyıldız","Kuyruklu yıldız"]'::jsonb, 2, 'genel_kultur'),
('Büyükayı hangi tür gök cismi topluluğudur?', '["Uydu","Galaksi","Gezegen","Takımyıldız"]'::jsonb, 3, 'genel_kultur'),
('Denizde yön bulmada yıldızlardan yararlanmaya ne denir?', '["Gök seyri","Karasal seyir","Radar","Sonar"]'::jsonb, 0, 'genel_kultur'),
('Sualtında mesafe ölçmede kullanılan sistem hangisidir?', '["Radar","Sonar","GPS","Pusula"]'::jsonb, 1, 'genel_kultur'),
('Radar hangi dalgaları kullanır?', '["Su dalgaları","Ses dalgaları","Radyo dalgaları","Isı"]'::jsonb, 2, 'genel_kultur'),

-- Karışık kategori tamamlama
('Türk halk edebiyatında ninni hangi amaçla söylenir?', '["Yarışmak","Düğün açmak","Ağıt yakmak","Çocuğu uyutmak"]'::jsonb, 3, 'edebiyat'),
('Tiyatroda seyircinin oturduğu bölüme ne denir?', '["Salon","Kulis","Sahne","Fuaye kapısı"]'::jsonb, 0, 'sanat'),
('Bir filmde ışık düzenini kuran kişiye ne denir?', '["Kurgucu","Görüntü yönetmeni","Yapımcı","Senarist"]'::jsonb, 1, 'sinema'),
('Bir müzik parçasının başlangıç bölümüne ne denir?', '["Final","Nakarat","Giriş","Ara"]'::jsonb, 2, 'muzik'),
('Bilgisayarda klasörlerin işlevi nedir?', '["Isıtmak","Elektrik vermek","Ses üretmek","Dosyaları düzenlemek"]'::jsonb, 3, 'teknoloji'),
('Voleybolda topun filenin üzerinden sert vurulmasına ne denir?', '["Smaç","Manşet","Pas","Servis"]'::jsonb, 0, 'spor'),
('Futbolda topu ayakla ileriye taşımaya ne denir?', '["Çalım yasağı","Sürme","Ofsayt","Faul"]'::jsonb, 1, 'spor'),
('Basketbolda topu yere vurarak ilerlemeye ne denir?', '["Asist","Ribaund","Dripling","Blok"]'::jsonb, 2, 'spor'),
('Bir arkeolojik kazıda çıkan eserlerin sergilendiği yer neresidir?', '["Depo","Kütüphane","Arşiv","Müze"]'::jsonb, 3, 'sanat')

on conflict (soru) do nothing;

-- ===================== KARIŞTIRMA =====================
-- Doğru cevap hep aynı şıkta olmasın: SADECE bu partide eklenen soruların
-- şıkları karıştırılır. `created_at >= transaction_timestamp()` koşulu
-- ZORUNLUDUR; onsuz tüm havuzun şıkları karışır ve o an oynanan maçlarda
-- şık indeksleri kayar.
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
