-- Soru havuzu genişletme — Parti 6: Türkiye özel + dünya bilgisi
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Adana''nın plaka kodu kaçtır?', '["01","02","03","04"]'::jsonb, 0, 'genel'),
('Ankara''nın plaka kodu kaçtır?', '["06","05","07","08"]'::jsonb, 0, 'genel'),
('İstanbul''un plaka kodu kaçtır?', '["34","35","33","36"]'::jsonb, 0, 'genel'),
('İzmir''in plaka kodu kaçtır?', '["35","34","36","33"]'::jsonb, 0, 'genel'),
('Antalya''nın plaka kodu kaçtır?', '["07","06","08","09"]'::jsonb, 0, 'genel'),
('Bursa''nın plaka kodu kaçtır?', '["16","15","17","18"]'::jsonb, 0, 'genel'),
('Trabzon''un plaka kodu kaçtır?', '["61","60","62","63"]'::jsonb, 0, 'genel'),
('Konya''nın plaka kodu kaçtır?', '["42","41","43","44"]'::jsonb, 0, 'genel'),
('Gaziantep''in plaka kodu kaçtır?', '["27","26","28","25"]'::jsonb, 0, 'genel'),
('Plaka kodu 81 olan ilimiz hangisidir?', '["Düzce","Osmaniye","Karabük","Yalova"]'::jsonb, 0, 'genel'),
('Türkiye''nin nüfusu en az olan ili hangisidir?', '["Bayburt","Tunceli","Ardahan","Kilis"]'::jsonb, 0, 'cografya'),
('Safranbolu evleriyle ünlü ilimiz hangisidir?', '["Karabük","Kastamonu","Bolu","Zonguldak"]'::jsonb, 0, 'cografya'),
('Mardin hangi mimari özelliğiyle ünlüdür?', '["Taş evleri","Ahşap evleri","Yalıları","Gökdelenleri"]'::jsonb, 0, 'cografya'),
('Peri bacaları hangi bölgemizdedir?', '["İç Anadolu","Ege","Akdeniz","Karadeniz"]'::jsonb, 0, 'cografya'),
('Ayder Yaylası hangi ilimizdedir?', '["Rize","Trabzon","Artvin","Giresun"]'::jsonb, 0, 'cografya'),
('Uzungöl hangi ilimizdedir?', '["Trabzon","Rize","Ordu","Giresun"]'::jsonb, 0, 'cografya'),
('Salda Gölü hangi ilimizdedir?', '["Burdur","Isparta","Denizli","Antalya"]'::jsonb, 0, 'cografya'),
('Abant Gölü hangi ilimizdedir?', '["Bolu","Düzce","Sakarya","Bilecik"]'::jsonb, 0, 'cografya'),
('Sapanca Gölü hangi ilimizdedir?', '["Sakarya","Kocaeli","Bursa","Bilecik"]'::jsonb, 0, 'cografya'),
('Akdamar Adası hangi gölün üzerindedir?', '["Van Gölü","Tuz Gölü","Beyşehir","Eğirdir"]'::jsonb, 0, 'cografya'),
('Ani Harabeleri hangi ilimizdedir?', '["Kars","Erzurum","Ağrı","Iğdır"]'::jsonb, 0, 'cografya'),
('Aspendos Antik Tiyatrosu hangi ilimizdedir?', '["Antalya","Muğla","İzmir","Mersin"]'::jsonb, 0, 'cografya'),
('Hierapolis antik kenti hangi doğal güzelliğin yanındadır?', '["Pamukkale","Kapadokya","Salda","Ölüdeniz"]'::jsonb, 0, 'cografya'),
('Bodrum hangi ilimize bağlıdır?', '["Muğla","Aydın","İzmir","Antalya"]'::jsonb, 0, 'cografya'),
('Çeşme hangi ilimize bağlıdır?', '["İzmir","Aydın","Muğla","Balıkesir"]'::jsonb, 0, 'cografya'),
('Alanya hangi ilimize bağlıdır?', '["Antalya","Mersin","Muğla","Adana"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en güney ucundaki il hangisidir?', '["Hatay","Mersin","Antalya","Şırnak"]'::jsonb, 0, 'cografya'),
('Boğaz köprülerinden "15 Temmuz Şehitler Köprüsü"nün eski adı nedir?', '["Boğaziçi Köprüsü","Fatih Köprüsü","Galata Köprüsü","Haliç Köprüsü"]'::jsonb, 0, 'genel'),
('İstanbul''daki tarihi "Kız Kulesi" nerededir?', '["Üsküdar açıkları","Haliç","Adalar","Sarayburnu"]'::jsonb, 0, 'genel'),
('Galata Kulesi''ni hangi topluluk inşa etmiştir?', '["Cenevizliler","Venedikliler","Bizanslılar","Osmanlılar"]'::jsonb, 0, 'tarih'),
('Ayasofya''yı kimler inşa etmiştir?', '["Bizanslılar","Osmanlılar","Romalılar","Selçuklular"]'::jsonb, 0, 'tarih'),
('Topkapı Sarayı''nı yaptıran padişah kimdir?', '["Fatih Sultan Mehmet","Kanuni","Yavuz","II. Bayezid"]'::jsonb, 0, 'tarih'),
('Dolmabahçe Sarayı hangi dönemde yapılmıştır?', '["Abdülmecid dönemi","Fatih dönemi","Kanuni dönemi","II. Mahmud dönemi"]'::jsonb, 0, 'tarih'),
('Atatürk Dolmabahçe Sarayı''nda hangi odada vefat etmiştir?', '["71 numaralı oda","1 numaralı oda","100 numaralı oda","53 numaralı oda"]'::jsonb, 0, 'tarih'),
('Anıtkabir hangi şehirdedir?', '["Ankara","İstanbul","Selanik","İzmir"]'::jsonb, 0, 'genel'),
('Anıtkabir hangi yılda tamamlanmıştır?', '["1953","1944","1938","1960"]'::jsonb, 0, 'tarih'),
('ABD''nin para birimi nedir?', '["Dolar","Euro","Sterlin","Peso"]'::jsonb, 0, 'genel'),
('Rusya''nın para birimi nedir?', '["Ruble","Grivna","Zloti","Leva"]'::jsonb, 0, 'genel'),
('Çin''in para birimi nedir?', '["Yuan","Yen","Won","Rupi"]'::jsonb, 0, 'genel'),
('Hindistan''ın para birimi nedir?', '["Rupi","Riyal","Dinar","Taka"]'::jsonb, 0, 'genel'),
('Güney Kore''nin para birimi nedir?', '["Won","Yen","Yuan","Baht"]'::jsonb, 0, 'genel'),
('İsviçre''nin para birimi nedir?', '["Frank","Euro","Kron","Mark"]'::jsonb, 0, 'genel'),
('Brezilya''nın para birimi nedir?', '["Real","Peso","Dolar","Escudo"]'::jsonb, 0, 'genel'),
('Meksika''nın para birimi nedir?', '["Peso","Real","Dolar","Bolivar"]'::jsonb, 0, 'genel'),
('Suudi Arabistan''ın para birimi nedir?', '["Riyal","Dinar","Dirhem","Lira"]'::jsonb, 0, 'genel'),
('Birleşik Arap Emirlikleri''nin para birimi nedir?', '["Dirhem","Riyal","Dinar","Şekel"]'::jsonb, 0, 'genel'),
('Azerbaycan''ın para birimi nedir?', '["Manat","Som","Tenge","Ruble"]'::jsonb, 0, 'genel'),
('Kazakistan''ın para birimi nedir?', '["Tenge","Manat","Som","Ruble"]'::jsonb, 0, 'genel'),
('Polonya''nın para birimi nedir?', '["Zloti","Forint","Koruna","Leva"]'::jsonb, 0, 'genel'),
('Macaristan''ın para birimi nedir?', '["Forint","Zloti","Ley","Kuna"]'::jsonb, 0, 'genel'),
('İsveç''in para birimi nedir?', '["Kron","Euro","Frank","Mark"]'::jsonb, 0, 'genel'),
('Japonya''nın bayrağında ne vardır?', '["Kırmızı daire","Yıldız","Ay","Güneş ışınları"]'::jsonb, 0, 'genel'),
('Kanada''nın bayrağında hangi yaprak vardır?', '["Akçaağaç","Meşe","Çınar","Zeytin"]'::jsonb, 0, 'genel'),
('Hangi ülkenin bayrağı kare şeklindedir?', '["İsviçre","Almanya","İtalya","Belçika"]'::jsonb, 0, 'genel'),
('ABD bayrağında kaç yıldız vardır?', '["50","51","48","52"]'::jsonb, 0, 'genel'),
('ABD bayrağındaki çizgiler neyi temsil eder?', '["İlk 13 koloniyi","50 eyaleti","Başkanları","Savaşları"]'::jsonb, 0, 'genel'),
('Bayrağında ülke haritası bulunan Avrupa ülkesi hangisidir?', '["Kosova","Arnavutluk","Sırbistan","Karadağ"]'::jsonb, 0, 'genel'),
('Brezilya''nın resmi dili neden Portekizcedir?', '["Portekiz sömürgesiydi","İspanya sömürgesiydi","Halk seçti","Coğrafi yakınlık"]'::jsonb, 0, 'genel'),
('Avusturya''nın resmi dili nedir?', '["Almanca","Avusturyaca","Fransızca","İtalyanca"]'::jsonb, 0, 'genel'),
('İsviçre''nin resmi dillerinden biri DEĞİLDİR?', '["İngilizce","Almanca","Fransızca","İtalyanca"]'::jsonb, 0, 'genel'),
('Mısır''ın resmi dili nedir?', '["Arapça","Mısırca","Fransızca","İngilizce"]'::jsonb, 0, 'genel'),
('Arjantin''in resmi dili nedir?', '["İspanyolca","Portekizce","Arjantince","İtalyanca"]'::jsonb, 0, 'genel'),
('Dünyada en çok ülkede resmi dil olan dil hangisidir?', '["İngilizce","Fransızca","İspanyolca","Arapça"]'::jsonb, 0, 'genel'),
('Hiyeroglif yazısı hangi uygarlığa aittir?', '["Mısır","Sümer","Çin","Maya"]'::jsonb, 0, 'tarih'),
('Çivi yazısı hangi uygarlığa aittir?', '["Sümer","Mısır","Fenike","Hitit"]'::jsonb, 0, 'tarih'),
('Modern alfabenin temeli sayılan alfabe hangi uygarlığındır?', '["Fenike","Mısır","Yunan","Roma"]'::jsonb, 0, 'tarih'),
('Rosetta Taşı hangi yazının çözülmesini sağlamıştır?', '["Hiyeroglif","Çivi yazısı","Runik","Linear B"]'::jsonb, 0, 'tarih'),
('İstanbul''un eski adlarından biri hangisidir?', '["Konstantinopolis","Ankyra","Smyrna","Nikaia"]'::jsonb, 0, 'tarih'),
('İzmir''in antik çağdaki adı nedir?', '["Smyrna","Efes","Milet","Foça"]'::jsonb, 0, 'tarih'),
('Ankara''nın antik çağdaki adı nedir?', '["Ankyra","Gordion","Pessinus","Tavium"]'::jsonb, 0, 'tarih'),
('Antakya hangi antik uygarlığın önemli merkeziydi?', '["Roma","Pers","Mısır","Babil"]'::jsonb, 0, 'tarih'),
('Dünyanın yedi harikasından Türkiye sınırlarında olanlardan biri hangisidir?', '["Artemis Tapınağı","Babil''in Asma Bahçeleri","İskenderiye Feneri","Keops Piramidi"]'::jsonb, 0, 'tarih'),
('Halikarnas Mozolesi hangi ilimizdeydi?', '["Muğla (Bodrum)","İzmir","Aydın","Antalya"]'::jsonb, 0, 'tarih'),
('Dünyanın yedi harikasından günümüze ulaşan tek yapı hangisidir?', '["Keops Piramidi","Asma Bahçeler","Rodos Heykeli","Artemis Tapınağı"]'::jsonb, 0, 'tarih'),
('Zeus Heykeli hangi antik kentteydi?', '["Olympia","Atina","Delfi","Rodos"]'::jsonb, 0, 'tarih'),
('Çin Seddi''nin uzunluğu yaklaşık kaç bin kilometredir (ana hat)?', '["8-9 bin","2-3 bin","20-25 bin","50 bin"]'::jsonb, 0, 'cografya'),
('Eyfel Kulesi hangi yıl tamamlanmıştır?', '["1889","1900","1850","1920"]'::jsonb, 0, 'tarih'),
('Eyfel Kulesi neden inşa edilmiştir?', '["Dünya Fuarı için","Savunma için","Radyo vericisi için","Kraliyet anısına"]'::jsonb, 0, 'tarih'),
('Pisa Kulesi neyiyle ünlüdür?', '["Eğikliği","Yüksekliği","Rengi","Çanları"]'::jsonb, 0, 'genel'),
('Kolezyum hangi şehirdedir?', '["Roma","Atina","Verona","Napoli"]'::jsonb, 0, 'genel'),
('Kolezyum''da antik dönemde ne yapılırdı?', '["Gladyatör dövüşleri","Tiyatro","Senato toplantıları","Pazar"]'::jsonb, 0, 'tarih'),
('Parthenon hangi tanrıçaya adanmıştır?', '["Athena","Hera","Afrodit","Artemis"]'::jsonb, 0, 'tarih'),
('Kremlin hangi şehirdedir?', '["Moskova","St. Petersburg","Kiev","Minsk"]'::jsonb, 0, 'genel'),
('Beyaz Saray hangi şehirdedir?', '["Washington D.C.","New York","Filadelfiya","Boston"]'::jsonb, 0, 'genel'),
('Buckingham Sarayı hangi şehirdedir?', '["Londra","Edinburgh","Manchester","Dublin"]'::jsonb, 0, 'genel'),
('Rio de Janeiro''daki dev İsa heykelinin adı nedir?', '["Kurtarıcı İsa","Kutsal İsa","Yüce İsa","Aziz İsa"]'::jsonb, 0, 'genel'),
('Burj Khalifa hangi şehirdedir?', '["Dubai","Abu Dabi","Doha","Riyad"]'::jsonb, 0, 'genel'),
('Dünyanın en yüksek binası hangisidir?', '["Burj Khalifa","Şanghay Kulesi","Empire State","Petronas"]'::jsonb, 0, 'genel'),
('Petra antik kenti hangi ülkededir?', '["Ürdün","Mısır","Suriye","İsrail"]'::jsonb, 0, 'cografya'),
('Angkor Wat tapınağı hangi ülkededir?', '["Kamboçya","Tayland","Vietnam","Laos"]'::jsonb, 0, 'cografya'),
('Stonehenge hangi ülkededir?', '["İngiltere","İrlanda","İskoçya","Fransa"]'::jsonb, 0, 'cografya'),
('Dünyanın en işlek hava yollarından İstanbul Havalimanı hangi yakadadır?', '["Avrupa","Asya","Adalar","Her ikisi"]'::jsonb, 0, 'genel'),
('Türkiye''nin ilk yerli otomobil markası girişimi hangisidir?', '["Devrim","TOGG","Anadol","Murat"]'::jsonb, 0, 'genel'),
('TOGG''un ilk modeli hangi kasa tipindedir?', '["SUV","Sedan","Hatchback","Pikap"]'::jsonb, 0, 'genel'),
('Türk Hava Yolları''nın kısaltması nedir?', '["THY","TUA","TRH","THA"]'::jsonb, 0, 'genel'),
('Türkiye''de demiryollarını işleten kurum hangisidir?', '["TCDD","THY","TÜVTÜRK","KGM"]'::jsonb, 0, 'genel'),
('İlk Türk uydusu hangisidir?', '["Türksat 1B","Göktürk-1","Rasat","Bilsat"]'::jsonb, 0, 'bilim'),
('Türkiye''nin uzaya giden ilk astronotu kimdir?', '["Alper Gezeravcı","Tuva Atasever","İlk astronot yok","Cahit Arf"]'::jsonb, 0, 'bilim'),
('Türkiye''nin bilim insanı Cahit Arf hangi alanda ünlüdür?', '["Matematik","Fizik","Kimya","Tıp"]'::jsonb, 0, 'bilim'),
('Hulusi Behçet hangi alanda dünyaca tanınır?', '["Tıp","Matematik","Kimya","Astronomi"]'::jsonb, 0, 'bilim'),
('Behçet hastalığını tanımlayan bilim insanı hangi ülkedendir?', '["Türkiye","Almanya","Fransa","ABD"]'::jsonb, 0, 'bilim'),
('Pakize Tarzi Türkiye''nin ilk kadın ... olarak bilinir; boşluğa ne gelmeli?', '["Jinekoloğu","Pilotu","Hakimi","Mühendisi"]'::jsonb, 0, 'genel'),
('Türkiye''nin ilk kadın pilotu kimdir?', '["Sabiha Gökçen","Bedriye Tahir","Leman Bozkurt","Edibe Subaşı"]'::jsonb, 0, 'tarih'),
('Sabiha Gökçen kimin manevi kızıdır?', '["Atatürk","İnönü","Celal Bayar","Fevzi Çakmak"]'::jsonb, 0, 'tarih'),
('Türkiye''nin ilk kadın başbakanı kimdir?', '["Tansu Çiller","Türkan Akyol","Sema Ramazanoğlu","Meral Akşener"]'::jsonb, 0, 'tarih'),
('Keban Barajı hangi nehir üzerindedir?', '["Fırat","Dicle","Kızılırmak","Sakarya"]'::jsonb, 0, 'cografya'),
('Atatürk Barajı hangi nehir üzerindedir?', '["Fırat","Dicle","Seyhan","Ceyhan"]'::jsonb, 0, 'cografya'),
('GAP projesi hangi bölgemizi kalkındırmayı amaçlar?', '["Güneydoğu Anadolu","Doğu Anadolu","İç Anadolu","Karadeniz"]'::jsonb, 0, 'cografya'),
('Türkiye''de pamuk üretimiyle ünlü ova hangisidir?', '["Çukurova","Konya Ovası","Bafra Ovası","Gediz Ovası"]'::jsonb, 0, 'cografya'),
('Konya Ovası en çok hangi tarım ürünüyle anılır?', '["Buğday","Pamuk","Çay","Fındık"]'::jsonb, 0, 'cografya'),
('Zeytin üretimi en çok hangi bölgemizde yapılır?', '["Ege","Karadeniz","İç Anadolu","Doğu Anadolu"]'::jsonb, 0, 'cografya'),
('Muz üretimiyle ünlü ilçemiz hangisidir?', '["Anamur","Alanya","Finike","Köyceğiz"]'::jsonb, 0, 'cografya'),
('Portakalıyla ünlü ilçemiz hangisidir?', '["Finike","Anamur","Çeşme","Ayvalık"]'::jsonb, 0, 'cografya'),
('Kayısısıyla ünlü ilimiz hangisidir?', '["Malatya","Elazığ","Erzincan","Iğdır"]'::jsonb, 0, 'genel'),
('Üzümüyle ünlü Ege ilçemiz hangisidir?', '["Salihli","Bodrum","Datça","Foça"]'::jsonb, 0, 'genel'),
('İnciriyle ünlü ilimiz hangisidir?', '["Aydın","İzmir","Muğla","Denizli"]'::jsonb, 0, 'genel'),
('Lavanta tarlalarıyla ünlü Kuyucak köyü hangi ildedir?', '["Isparta","Burdur","Denizli","Afyon"]'::jsonb, 0, 'cografya'),
('Gül üretimiyle ünlü ilimiz hangisidir?', '["Isparta","Burdur","Konya","Afyon"]'::jsonb, 0, 'genel'),
('Türk lokumu hangi ilçeyle de özdeşleşmiştir?', '["Safranbolu","Beypazarı","Ürgüp","Taraklı"]'::jsonb, 0, 'genel'),
('Ezine neyiyle ünlüdür?', '["Peyniri","Zeytini","Üzümü","Baklavası"]'::jsonb, 0, 'genel'),
('Kars hangi ürünüyle ünlüdür?', '["Kaşar ve bal","Fındık","İncir","Çay"]'::jsonb, 0, 'genel'),
('Hatay hangi özelliğiyle "medeniyetler şehri" olarak anılır?', '["Farklı din ve kültürlerin birlikteliği","Sanayisi","Limanı","Üniversiteleri"]'::jsonb, 0, 'genel'),
('Şanlıurfa''nın meşhur lakabı nedir?', '["Peygamberler şehri","Kahramanlar şehri","Gaziler şehri","Evliyalar şehri"]'::jsonb, 0, 'genel'),
('Balıklıgöl hangi ilimizdedir?', '["Şanlıurfa","Gaziantep","Mardin","Adıyaman"]'::jsonb, 0, 'cografya'),
('Mevlana Müzesi hangi ilimizdedir?', '["Konya","Karaman","Aksaray","Nevşehir"]'::jsonb, 0, 'genel'),
('Hacı Bektaş Veli Türbesi hangi ilimizdedir?', '["Nevşehir","Kırşehir","Konya","Yozgat"]'::jsonb, 0, 'genel'),
('Ayasofya hangi ilimizdedir?', '["İstanbul","Trabzon","İznik","Edirne"]'::jsonb, 0, 'genel'),
('Dünya mirası listesini hangi kuruluş belirler?', '["UNESCO","UNICEF","WHO","BM Güvenlik Konseyi"]'::jsonb, 0, 'genel'),
('Türkiye''nin ilk milli parkı hangisidir?', '["Yozgat Çamlığı","Uludağ","Kaçkar","Munzur"]'::jsonb, 0, 'cografya'),
('Kelebekler Vadisi hangi ilimizdedir?', '["Muğla","Antalya","İzmir","Aydın"]'::jsonb, 0, 'cografya'),
('Düden Şelalesi hangi ilimizdedir?', '["Antalya","Muğla","Denizli","Mersin"]'::jsonb, 0, 'cografya'),
('Manavgat Şelalesi hangi ilimizdedir?', '["Antalya","Mersin","Muğla","Isparta"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en uzun mağaralarından Pınargözü hangi ildedir?', '["Isparta","Burdur","Antalya","Konya"]'::jsonb, 0, 'cografya'),
('Damlataş Mağarası hangi ilçededir?', '["Alanya","Side","Kaş","Marmaris"]'::jsonb, 0, 'cografya'),
('Nüfusa göre dünyanın en kalabalık şehirlerinden biri hangisidir?', '["Tokyo","Oslo","Viyana","Lizbon"]'::jsonb, 0, 'cografya'),
('Kuzey Kutbu''nda hangi kara parçası vardır?', '["Kara yoktur, buz vardır","Grönland","Antarktika","İzlanda"]'::jsonb, 0, 'cografya'),
('Antarktika kıtasında kalıcı yerleşim var mıdır?', '["Sadece araştırma istasyonları","Büyük şehirler","Köyler","Hiçbir şey yok"]'::jsonb, 0, 'cografya'),
('Dünyanın en kurak çöllerinden Atacama hangi ülkededir?', '["Şili","Peru","Meksika","Arjantin"]'::jsonb, 0, 'cografya'),
('Gobi Çölü hangi iki ülke arasındadır?', '["Moğolistan ve Çin","Rusya ve Çin","Kazakistan ve Çin","Hindistan ve Çin"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
