-- Soru havuzu genişletme: cografya +100
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Kars''ın Sarıkamış ilçesi hangi turizm dalıyla anılır?', '["Kış turizmi","Deniz turizmi","Termal turizm","Kruvaziyer"]'::jsonb, 0, 'cografya'),
('Erciyes kayak merkezi hangi ilimizdedir?', '["Niğde","Kayseri","Sivas","Nevşehir"]'::jsonb, 1, 'cografya'),
('Uludağ kayak merkezi hangi ilimizdedir?', '["Bilecik","Balıkesir","Bursa","Kütahya"]'::jsonb, 2, 'cografya'),
('Ilgaz kayak merkezi hangi iller arasındadır?', '["Bolu ve Düzce","Sinop ve Samsun","Amasya ve Tokat","Kastamonu ve Çankırı"]'::jsonb, 3, 'cografya'),
('Davraz kayak merkezi hangi ilimizdedir?', '["Isparta","Burdur","Antalya","Denizli"]'::jsonb, 0, 'cografya'),
('Yedigöller Milli Parkı hangi ilimizdedir?', '["Düzce","Bolu","Zonguldak","Karabük"]'::jsonb, 1, 'cografya'),
('Küre Dağları Milli Parkı hangi bölgemizdedir?', '["Doğu Karadeniz","Marmara","Batı Karadeniz","Ege"]'::jsonb, 2, 'cografya'),
('Altındere Vadisi Milli Parkı hangi manastırı barındırır?', '["Aya Yorgi","Akdamar","Sümbüllü","Sümela"]'::jsonb, 3, 'cografya'),
('Akdamar Kilisesi hangi gölde yer alır?', '["Van Gölü","Beyşehir Gölü","Eğirdir Gölü","İznik Gölü"]'::jsonb, 0, 'cografya'),
('Karagöl-Sahara Milli Parkı hangi ilimizdedir?', '["Rize","Artvin","Trabzon","Gümüşhane"]'::jsonb, 1, 'cografya'),
('Türkiye''de heyelan seti ile oluşan Uzungöl hangi ildedir?', '["Rize","Artvin","Trabzon","Bayburt"]'::jsonb, 2, 'cografya'),
('Yeşilırmak Nehri hangi ilimizden geçerek denize ulaşır?', '["Sinop","Ordu","Giresun","Samsun"]'::jsonb, 3, 'cografya'),
('Filyos Çayı hangi denize dökülür?', '["Karadeniz","Marmara","Ege","Akdeniz"]'::jsonb, 0, 'cografya'),
('Bakırçay hangi ilimizden geçer?', '["Denizli","İzmir","Muğla","Aydın"]'::jsonb, 1, 'cografya'),
('Küçük Menderes hangi bölgemizde akar?', '["Akdeniz","Marmara","Ege","Karadeniz"]'::jsonb, 2, 'cografya'),
('Dalaman Çayı hangi ilimizden geçer?', '["Antalya","Aydın","Denizli","Muğla"]'::jsonb, 3, 'cografya'),
('Manavgat Çayı hangi ilimizdedir?', '["Antalya","Mersin","Isparta","Burdur"]'::jsonb, 0, 'cografya'),
('Asi Nehri hangi ilimizden Akdeniz''e ulaşır?', '["Mersin","Hatay","Adana","Osmaniye"]'::jsonb, 1, 'cografya'),
('Murat Nehri hangi büyük nehrin koludur?', '["Dicle","Kızılırmak","Fırat","Sakarya"]'::jsonb, 2, 'cografya'),
('Batman Çayı hangi nehre karışır?', '["Fırat","Aras","Çoruh","Dicle"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en fazla su tutan barajlarından Atatürk Barajı hangi ildedir?', '["Şanlıurfa","Gaziantep","Adıyaman","Diyarbakır"]'::jsonb, 0, 'cografya'),
('Karakaya Barajı hangi nehir üzerindedir?', '["Dicle","Fırat","Aras","Seyhan"]'::jsonb, 1, 'cografya'),
('Oymapınar Barajı hangi ilimizdedir?', '["Mersin","Adana","Antalya","Burdur"]'::jsonb, 2, 'cografya'),
('Altınkaya Barajı hangi nehir üzerindedir?', '["Yeşilırmak","Sakarya","Çoruh","Kızılırmak"]'::jsonb, 3, 'cografya'),
('Deriner Barajı hangi nehir üzerindedir?', '["Çoruh","Aras","Fırat","Dicle"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en uzun karayolu tünellerinden Ovit Tüneli hangi illeri bağlar?', '["Bolu ve Düzce","Rize ve Erzurum","Artvin ve Ardahan","Trabzon ve Gümüşhane"]'::jsonb, 1, 'cografya'),
('Zigana Tüneli hangi geçidi kolaylaştırır?', '["Bolu geçişi","Sarıkamış geçişi","Trabzon-Gümüşhane geçişi","Antalya geçişi"]'::jsonb, 2, 'cografya'),
('Osmangazi Köprüsü hangi körfezi geçer?', '["Edremit Körfezi","Saros Körfezi","İskenderun Körfezi","İzmit Körfezi"]'::jsonb, 3, 'cografya'),
('Çanakkale 1915 Köprüsü hangi boğazı geçer?', '["Çanakkale Boğazı","İstanbul Boğazı","Cebelitarık","Süveyş"]'::jsonb, 0, 'cografya'),
('Yavuz Sultan Selim Köprüsü hangi boğazdadır?', '["Çanakkale Boğazı","İstanbul Boğazı","İzmit Körfezi","Ege"]'::jsonb, 1, 'cografya'),
('Türkiye''de yüksek hızlı tren hattı ilk hangi iller arasında açılmıştır?', '["İstanbul ve İzmir","Ankara ve Konya","Ankara ve Eskişehir","İzmir ve Denizli"]'::jsonb, 2, 'cografya'),
('Türkiye''nin doğal gaz boru hatlarından TANAP nereden gelir?', '["Rusya","İran","Irak","Azerbaycan"]'::jsonb, 3, 'cografya'),
('Mavi Akım doğal gaz hattı hangi denizin altından geçer?', '["Karadeniz","Akdeniz","Ege","Marmara"]'::jsonb, 0, 'cografya'),
('Kerkük-Yumurtalık boru hattı neyi taşır?', '["Doğal gaz","Ham petrol","Su","Elektrik"]'::jsonb, 1, 'cografya'),
('Türkiye''de rüzgâr enerjisi santrali yoğunluğu hangi ilde yüksektir?', '["Erzurum","Van","İzmir","Şırnak"]'::jsonb, 2, 'cografya'),
('Türkiye''de jeotermal ısıtma uygulanan illerden biri hangisidir?', '["Sinop","Bartın","Kilis","Afyonkarahisar"]'::jsonb, 3, 'cografya'),
('Türkiye''de kişi başına su miktarı hangi kavramla değerlendirilir?', '["Su varlığı sınıflandırması","Nüfus yoğunluğu","Yağış rejimi","Toprak verimi"]'::jsonb, 0, 'cografya'),
('İçme suyu arıtımında ilk aşama nedir?', '["Klorlama","Kaba filtreleme","Depolama","Dağıtım"]'::jsonb, 1, 'cografya'),
('Suyun klorlanmasının amacı nedir?', '["Tadını değiştirmek","Sertliği artırmak","Mikroorganizmaları etkisizleştirmek","Renk vermek"]'::jsonb, 2, 'cografya'),
('Sert su neyi ifade eder?', '["Tuzlu deniz suyu","Klorlu su","Buzlu su","Kalsiyum ve magnezyum oranı yüksek su"]'::jsonb, 3, 'cografya'),
('Yağmur suyu hasadı ne sağlar?', '["Yağışı toplayıp kullanmayı","Yağışı artırmayı","Sel yaratmayı","Toprağı kurutmayı"]'::jsonb, 0, 'cografya'),
('Kentlerde geçirimli yüzeylerin artırılması neyi azaltır?', '["Yeşil alanı","Sel riskini","Nüfusu","Trafiği"]'::jsonb, 1, 'cografya'),
('Türkiye''de tarım alanlarının amaç dışı kullanımı neye yol açar?', '["Verim artışına","Su artışına","Verimli toprak kaybına","Nüfus azalmasına"]'::jsonb, 2, 'cografya'),
('Toprak analizinin çiftçiye yararı nedir?', '["Ürünü hızlandırmak","Su gerektirmemek","Zararlıyı çoğaltmak","Doğru gübreleme yapabilmek"]'::jsonb, 3, 'cografya'),
('Aşırı gübrelemenin çevresel sonucu nedir?', '["Su kaynaklarının kirlenmesi","Toprağın zenginleşmesi","Verimin sürekli artması","Erozyonun bitmesi"]'::jsonb, 0, 'cografya'),
('Ötrofikasyon nedir?', '["Suyun tuzlanması","Aşırı besinle yosun patlaması","Suyun donması","Suyun buharlaşması"]'::jsonb, 1, 'cografya'),
('Tarımsal ilaç kullanımının riski nedir?', '["Verim düşüşü zorunluluğu","Su artışı","Kalıntı ve çevre kirliliği","Toprak zenginleşmesi"]'::jsonb, 2, 'cografya'),
('Biyolojik mücadele ne demektir?', '["Kimyasal ilaçlama","Sulama artırma","Nadas bırakma","Zararlıyla doğal düşmanıyla mücadele"]'::jsonb, 3, 'cografya'),
('Polinasyonda arıların rolü nedir?', '["Bitkilerin tozlaşmasını sağlamak","Toprağı sürmek","Su taşımak","Gübre üretmek"]'::jsonb, 0, 'cografya'),
('Arı popülasyonunun azalmasının tarımsal sonucu nedir?', '["Verimin artması","Ürün veriminin düşmesi","Su tüketiminin artması","Toprağın zenginleşmesi"]'::jsonb, 1, 'cografya'),
('Jeolojik zaman ölçeğinde en uzun birim hangisidir?', '["Devir","Dönem","Zaman (eon)","Kat"]'::jsonb, 2, 'cografya'),
('Dinozorların yaşadığı jeolojik dönem hangisidir?', '["Paleozoik","Senozoik","Prekambriyen","Mezozoik"]'::jsonb, 3, 'cografya'),
('İnsanın ortaya çıktığı jeolojik dönem hangisidir?', '["Senozoik","Mezozoik","Paleozoik","Prekambriyen"]'::jsonb, 0, 'cografya'),
('Kömür yataklarının oluştuğu jeolojik dönem hangisidir?', '["Jura","Karbonifer","Kretase","Neojen"]'::jsonb, 1, 'cografya'),
('Petrolün oluşumu neye dayanır?', '["Volkanik lav soğumasına","Buzul erimesine","Deniz canlılarının dönüşümüne","Rüzgâr birikimine"]'::jsonb, 2, 'cografya'),
('Doğal gazın petrolle birlikte bulunmasının nedeni nedir?', '["Aynı mineralden gelmeleri","Volkanik olmaları","Buzul kaynaklı olmaları","Aynı organik kökenden oluşmaları"]'::jsonb, 3, 'cografya'),
('Fay hattı üzerindeki yerleşimlerde alınan temel önlem nedir?', '["Depreme dayanıklı yapı","Yüksek bina yapmak","Zemini kazmak","Yol genişletmek"]'::jsonb, 0, 'cografya'),
('Zemin etüdü neden yapılır?', '["Manzarayı ölçmek","Yapının oturacağı zemini tanımak","Yağış saymak","Nüfus belirlemek"]'::jsonb, 1, 'cografya'),
('Alüvyal zeminin yapı açısından riski nedir?', '["Çok sert olması","Su geçirmemesi","Deprem dalgasını büyütmesi","Kayalık olması"]'::jsonb, 2, 'cografya'),
('Tsunami erken uyarı sistemleri neyi izler?', '["Yağış miktarını","Rüzgâr hızını","Nüfus hareketini","Deniz altı deprem ve dalga verilerini"]'::jsonb, 3, 'cografya'),
('Volkanik küllerin toprağa etkisi nedir?', '["Uzun vadede verimi artırması","Toprağı kalıcı kısırlaştırması","Suyu tuzlandırması","Erozyonu bitirmesi"]'::jsonb, 0, 'cografya'),
('Türkiye''de volkanik topraklara sahip bölgelerden biri hangisidir?', '["Trakya kıyısı","Kapadokya çevresi","Çukurova","Ergene Havzası"]'::jsonb, 1, 'cografya'),
('Şist ve gnays hangi kayaç grubuna girer?', '["Tortul","Püskürük","Başkalaşım","Volkanik cam"]'::jsonb, 2, 'cografya'),
('Obsidyen nasıl oluşur?', '["Tortullaşmayla","Basınç altında dönüşümle","Buzul aşındırmasıyla","Lavın hızla soğumasıyla"]'::jsonb, 3, 'cografya'),
('Kalkerin (kireçtaşı) başkalaşmış hâli nedir?', '["Mermer","Granit","Bazalt","Kum"]'::jsonb, 0, 'cografya'),
('Kumtaşı hangi süreçle oluşur?', '["Lavın soğumasıyla","Kum tanelerinin çimentolanmasıyla","Basınçla dönüşümle","Buzul erimesiyle"]'::jsonb, 1, 'cografya'),
('Minerallerin sertliğini ölçen ölçek hangisidir?', '["Richter","Beaufort","Mohs","Celsius"]'::jsonb, 2, 'cografya'),
('Mohs ölçeğinde en sert mineral hangisidir?', '["Kuvars","Talk","Kalsit","Elmas"]'::jsonb, 3, 'cografya'),
('Kuvars hangi kayaçların yaygın bileşenidir?', '["Granit ve kumtaşı","Bazalt ve kalker","Mermer ve tuz","Kil ve kömür"]'::jsonb, 0, 'cografya'),
('Bir bölgenin maden potansiyeli hangi kurum tarafından araştırılır?', '["TÜİK","MTA","DSİ","Meteoroloji"]'::jsonb, 1, 'cografya'),
('Krom madeni Türkiye''de hangi bölgede yoğun çıkarılır?', '["Trakya","Doğu Karadeniz","Ege ve Akdeniz","İç Anadolu kuzeyi"]'::jsonb, 2, 'cografya'),
('Bor mineralinin kullanım alanlarından biri nedir?', '["Ekmek üretimi","Kumaş boyama","Su arıtımı yalnızca","Cam ve seramik sanayisi"]'::jsonb, 3, 'cografya'),
('Alüminyum hangi cevherden elde edilir?', '["Boksit","Hematit","Galen","Pirit"]'::jsonb, 0, 'cografya'),
('Demir hangi cevherden elde edilir?', '["Boksit","Hematit","Sfalerit","Kalkopirit"]'::jsonb, 1, 'cografya'),
('Bakır hangi cevherden elde edilir?', '["Boksit","Hematit","Kalkopirit","Galen"]'::jsonb, 2, 'cografya'),
('Türkiye''de altın madenciliğinin öne çıktığı illerden biri hangisidir?', '["Rize","Sinop","Yalova","Erzincan"]'::jsonb, 3, 'cografya'),
('Madencilikte ''rehabilitasyon'' ne demektir?', '["Sahanın doğaya yeniden kazandırılması","Yeni maden açmak","Cevher zenginleştirmek","İşçi eğitmek"]'::jsonb, 0, 'cografya'),
('Bir bölgede tuz kubbesi oluşumu neyi gösterir?', '["Volkanik etkinliği","Kalın tuz katmanlarının hareketini","Buzullaşmayı","Delta oluşumunu"]'::jsonb, 1, 'cografya'),
('Meteoroloji istasyonlarının kurulma amacı nedir?', '["Deprem ölçmek","Maden aramak","Atmosfer verilerini düzenli ölçmek","Nüfus saymak"]'::jsonb, 2, 'cografya'),
('Bir bölgenin iklim verisi kaç yıllık ortalamaya dayanır?', '["Bir günlük veriye","Bir haftalık veriye","Bir aylık veriye","Uzun yıllar ortalamasına"]'::jsonb, 3, 'cografya'),
('Sıcaklık ortalamasının hesabında hangi veriler kullanılır?', '["Günlük en yüksek ve en düşük","Yalnız gece verisi","Yalnız öğlen verisi","Rüzgâr verisi"]'::jsonb, 0, 'cografya'),
('Yıllık sıcaklık farkı nasıl bulunur?', '["Günlük fark","En sıcak ve en soğuk ay farkı","Yağış farkı","Basınç farkı"]'::jsonb, 1, 'cografya'),
('Bir yerin denizellik derecesi neyle ölçülür?', '["Yağışın çokluğuyla","Rakımla","Sıcaklık farkının azlığıyla","Enlemle"]'::jsonb, 2, 'cografya'),
('Yağış rejimi düzensiz olan bir bölgede tarımın riski nedir?', '["Verimin sabitlenmesi","Sulamanın gereksizliği","Toprağın zenginleşmesi","Verimin yıldan yıla değişmesi"]'::jsonb, 3, 'cografya'),
('Kar örtüsünün tarımdaki yararı nedir?', '["Toprağı dondan koruyup su sağlaması","Toprağı kurutması","Ürünü yakması","Erozyonu artırması"]'::jsonb, 0, 'cografya'),
('Don olayı meyveciliği hangi dönemde en çok etkiler?', '["Hasat sonrası","Çiçeklenme döneminde","Kış uykusunda","Yaz ortasında"]'::jsonb, 1, 'cografya'),
('Zirai don uyarısı neyi amaçlar?', '["Fiyat belirlemeyi","Vergi toplamayı","Üreticinin önlem almasını","Nüfus saymayı"]'::jsonb, 2, 'cografya'),
('Sisin ulaşımdaki etkisi nedir?', '["Hızı artırması","Yolu kurutması","Trafiği azaltması","Görüşü azaltıp riski artırması"]'::jsonb, 3, 'cografya'),
('Buzlanmanın karayolundaki etkisi nedir?', '["Tutunmayı azaltması","Tutunmayı artırması","Görüşü artırması","Yolu genişletmesi"]'::jsonb, 0, 'cografya'),
('Fırtına uyarılarında kullanılan ölçek hangisidir?', '["Richter","Beaufort","Mohs","Mercalli"]'::jsonb, 1, 'cografya'),
('Bir bölgede mikroklima oluşumunun nedeni nedir?', '["Nüfus yoğunluğu","Yol ağı","Yerel yer şekli ve su etkisi","Vergi düzeni"]'::jsonb, 2, 'cografya'),
('Vadi tabanında don riskinin fazla olmasının nedeni nedir?', '["Rüzgârın şiddeti","Güneşin fazlalığı","Toprağın kumlu olması","Soğuk havanın çukurda birikmesi"]'::jsonb, 3, 'cografya'),
('Kıyı yerleşmelerinde ''meltem'' hangi rahatlığı sağlar?', '["Yaz sıcağını hafifletmesi","Kışı ısıtması","Yağış getirmesi","Sisi dağıtması"]'::jsonb, 0, 'cografya'),
('Şehir plancılığında rüzgâr koridoru neden korunur?', '["Bina yüksekliği için","Hava kirliliğinin dağılması için","Trafik için","Otopark için"]'::jsonb, 1, 'cografya'),
('Yeşil alanların kentteki iklimsel yararı nedir?', '["Sıcaklığı artırması","Yağışı engellemesi","Sıcaklığı düşürmesi","Rüzgârı durdurması"]'::jsonb, 2, 'cografya'),
('Kıyı dolgusunun ekolojik riski nedir?', '["Deniz suyunu temizlemesi","Balığı çoğaltması","Akıntıyı bitirmesi","Kıyı ekosistemini bozması"]'::jsonb, 3, 'cografya'),
('Deniz feneri hangi işlevi görür?', '["Gemilere yol göstermek","Balık avlamak","Rüzgâr ölçmek","Yük taşımak"]'::jsonb, 0, 'cografya'),
('Liman derinliğinin gemi türüne etkisi nedir?', '["Yükün cinsini belirler","Büyük gemilerin yanaşabilmesini belirler","Bayrağı belirler","Rotayı belirler"]'::jsonb, 1, 'cografya'),
('Konteyner taşımacılığının avantajı nedir?', '["Yükün açıkta taşınması","Küçük hacim","Standart kutularla hızlı elleçleme","Depolamasız olması"]'::jsonb, 2, 'cografya'),
('Serbest liman uygulaması ne sağlar?', '["Yasak koymayı","Vergi artırmayı","Nüfus azaltmayı","Gümrük kolaylıklarıyla ticaret çekmeyi"]'::jsonb, 3, 'cografya')
on conflict (soru) do nothing;
