-- Soru havuzu genişletme: cografya +99
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Barselona hangi ülkenin kentidir?', '["İspanya","Portekiz","İtalya","Fransa"]'::jsonb, 0, 'cografya'),
('Münih hangi ülkenin kentidir?', '["Avusturya","Almanya","İsviçre","Çekya"]'::jsonb, 1, 'cografya'),
('Salzburg hangi ülkenin kentidir?', '["Almanya","İsviçre","Avusturya","Slovenya"]'::jsonb, 2, 'cografya'),
('Cenevre hangi ülkenin kentidir?', '["Fransa","İtalya","Belçika","İsviçre"]'::jsonb, 3, 'cografya'),
('Anvers (Antwerp) hangi ülkenin liman kentidir?', '["Belçika","Hollanda","Fransa","Almanya"]'::jsonb, 0, 'cografya'),
('Hamburg hangi ülkenin liman kentidir?', '["Danimarka","Almanya","Polonya","Hollanda"]'::jsonb, 1, 'cografya'),
('Gdansk hangi ülkenin liman kentidir?', '["Litvanya","Almanya","Polonya","Rusya"]'::jsonb, 2, 'cografya'),
('Riga hangi ülkenin başkentidir?', '["Litvanya","Estonya","Finlandiya","Letonya"]'::jsonb, 3, 'cografya'),
('Tallinn hangi ülkenin başkentidir?', '["Estonya","Letonya","Litvanya","Finlandiya"]'::jsonb, 0, 'cografya'),
('Vilnius hangi ülkenin başkentidir?', '["Letonya","Litvanya","Estonya","Belarus"]'::jsonb, 1, 'cografya'),
('Minsk hangi ülkenin başkentidir?', '["Ukrayna","Moldova","Belarus","Litvanya"]'::jsonb, 2, 'cografya'),
('Kişinev hangi ülkenin başkentidir?', '["Romanya","Ukrayna","Bulgaristan","Moldova"]'::jsonb, 3, 'cografya'),
('Ljubljana hangi ülkenin başkentidir?', '["Slovenya","Hırvatistan","Avusturya","Slovakya"]'::jsonb, 0, 'cografya'),
('Bratislava hangi ülkenin başkentidir?', '["Çekya","Slovakya","Macaristan","Avusturya"]'::jsonb, 1, 'cografya'),
('Podgorica hangi ülkenin başkentidir?', '["Arnavutluk","Sırbistan","Karadağ","Bosna-Hersek"]'::jsonb, 2, 'cografya'),
('Üsküp hangi ülkenin başkentidir?', '["Arnavutluk","Kosova","Bulgaristan","Kuzey Makedonya"]'::jsonb, 3, 'cografya'),
('Priştine hangi bölgenin merkezidir?', '["Kosova","Karadağ","Vojvodina","Sancak"]'::jsonb, 0, 'cografya'),
('Sofya hangi ülkenin başkentidir?', '["Sırbistan","Bulgaristan","Romanya","Yunanistan"]'::jsonb, 1, 'cografya'),
('Bükreş hangi ülkenin başkentidir?', '["Bulgaristan","Moldova","Romanya","Macaristan"]'::jsonb, 2, 'cografya'),
('Atina hangi yarımadada yer alır?', '["İtalya Yarımadası","İber Yarımadası","Anadolu","Balkan Yarımadası"]'::jsonb, 3, 'cografya'),
('Selanik hangi denize kıyıdır?', '["Ege Denizi","Adriyatik","İyon Denizi","Karadeniz"]'::jsonb, 0, 'cografya'),
('Napoli hangi denize kıyıdır?', '["Adriyatik","Tiren Denizi","Ege","Karadeniz"]'::jsonb, 1, 'cografya'),
('Venedik hangi denize açılır?', '["Tiren Denizi","İyon Denizi","Adriyatik Denizi","Ege"]'::jsonb, 2, 'cografya'),
('Marsilya hangi denize kıyıdır?', '["Atlas Okyanusu","Manş","Kuzey Denizi","Akdeniz"]'::jsonb, 3, 'cografya'),
('Bordeaux hangi bölgesiyle ünlüdür?', '["Şarapçılık","Madencilik","Balıkçılık","Demir çelik"]'::jsonb, 0, 'cografya'),
('Milano hangi alanda öne çıkar?', '["Madencilik","Moda ve tasarım","Balıkçılık","Ormancılık"]'::jsonb, 1, 'cografya'),
('Silikon Vadisi hangi eyalettedir?', '["Teksas","Florida","Kaliforniya","New York"]'::jsonb, 2, 'cografya'),
('Detroit hangi sanayisiyle bilinir?', '["Tekstil","Gıda","Kâğıt","Otomotiv"]'::jsonb, 3, 'cografya'),
('Chicago hangi gölün kıyısındadır?', '["Michigan Gölü","Superior Gölü","Erie Gölü","Ontario Gölü"]'::jsonb, 0, 'cografya'),
('Las Vegas hangi doğal ortamda kurulmuştur?', '["Yağmur ormanı","Çöl","Tundra","Bataklık"]'::jsonb, 1, 'cografya'),
('Alaska hangi ülkeye bağlıdır?', '["Kanada","Rusya","ABD","Danimarka"]'::jsonb, 2, 'cografya'),
('Vancouver hangi ülkenin kentidir?', '["ABD","Avustralya","Yeni Zelanda","Kanada"]'::jsonb, 3, 'cografya'),
('Quebec bölgesinde yaygın konuşulan dil hangisidir?', '["Fransızca","İspanyolca","Almanca","İtalyanca"]'::jsonb, 0, 'cografya'),
('Rio de Janeiro hangi doğal simgesiyle tanınır?', '["Uluru","Şeker Somunu Tepesi","Table Mountain","Fuji"]'::jsonb, 1, 'cografya'),
('Buenos Aires hangi nehrin ağzında kurulmuştur?', '["Amazon","Orinoco","La Plata","Parana dışı hiçbiri"]'::jsonb, 2, 'cografya'),
('Lima hangi okyanusa kıyıdır?', '["Atlas","Hint","Arktik","Pasifik"]'::jsonb, 3, 'cografya'),
('Cusco kenti hangi uygarlığın merkeziydi?', '["İnka","Maya","Aztek","Olmek"]'::jsonb, 0, 'cografya'),
('Mexico City hangi jeolojik risk altındadır?', '["Buzul erimesi","Deprem ve zemin çökmesi","Tsunami","Çığ"]'::jsonb, 1, 'cografya'),
('Kahire''nin yakınındaki ünlü yapı grubu hangisidir?', '["Petra","Baalbek","Giza Piramitleri","Persepolis"]'::jsonb, 2, 'cografya'),
('Marakeş hangi ülkenin kentidir?', '["Cezayir","Tunus","Libya","Fas"]'::jsonb, 3, 'cografya'),
('Timbuktu hangi ülkededir?', '["Mali","Nijer","Çad","Sudan"]'::jsonb, 0, 'cografya'),
('Zanzibar hangi ülkeye bağlıdır?', '["Kenya","Tanzanya","Mozambik","Uganda"]'::jsonb, 1, 'cografya'),
('Cape Town hangi ülkenin kentidir?', '["Namibya","Botsvana","Güney Afrika","Angola"]'::jsonb, 2, 'cografya'),
('Dubai hangi ülkenin kentidir?', '["Katar","Kuveyt","Bahreyn","Birleşik Arap Emirlikleri"]'::jsonb, 3, 'cografya'),
('Doha hangi ülkenin başkentidir?', '["Katar","Bahreyn","Kuveyt","Umman"]'::jsonb, 0, 'cografya'),
('Maskat hangi ülkenin başkentidir?', '["Yemen","Umman","Katar","BAE"]'::jsonb, 1, 'cografya'),
('Şam hangi ülkenin başkentidir?', '["Lübnan","Ürdün","Suriye","Irak"]'::jsonb, 2, 'cografya'),
('Erbil hangi bölgenin merkezidir?', '["Güney İran","Doğu Suriye","Batı Ürdün","Kuzey Irak"]'::jsonb, 3, 'cografya'),
('Kabil hangi ülkenin başkentidir?', '["Afganistan","Pakistan","Tacikistan","İran"]'::jsonb, 0, 'cografya'),
('İslamabad hangi ülkenin başkentidir?', '["Hindistan","Pakistan","Bangladeş","Afganistan"]'::jsonb, 1, 'cografya'),
('Dakka hangi ülkenin başkentidir?', '["Hindistan","Myanmar","Bangladeş","Nepal"]'::jsonb, 2, 'cografya'),
('Katmandu hangi ülkenin başkentidir?', '["Butan","Tibet","Bangladeş","Nepal"]'::jsonb, 3, 'cografya'),
('Kolombo hangi ülkenin kentidir?', '["Sri Lanka","Maldivler","Hindistan","Myanmar"]'::jsonb, 0, 'cografya'),
('Pekin hangi ülkenin başkentidir?', '["Japonya","Çin","Kore","Moğolistan"]'::jsonb, 1, 'cografya'),
('Osaka hangi ülkenin kentidir?', '["Güney Kore","Çin","Japonya","Tayvan"]'::jsonb, 2, 'cografya'),
('Busan hangi ülkenin liman kentidir?', '["Japonya","Çin","Vietnam","Güney Kore"]'::jsonb, 3, 'cografya'),
('Taipei hangi bölgenin merkezidir?', '["Tayvan","Hong Kong","Makao","Hainan"]'::jsonb, 0, 'cografya'),
('Sidney hangi ülkenin kentidir?', '["Yeni Zelanda","Avustralya","Fiji","Papua Yeni Gine"]'::jsonb, 1, 'cografya'),
('Perth hangi kıyıda yer alır?', '["Doğusu","Kuzeyi","Avustralya''nın batısı","Güneyi"]'::jsonb, 2, 'cografya'),
('Auckland hangi ülkenin kentidir?', '["Avustralya","Fiji","Samoa","Yeni Zelanda"]'::jsonb, 3, 'cografya'),
('Bir ülkenin ''anakara'' dışındaki topraklarına ne ad verilir?', '["Denizaşırı toprak","Tampon bölge","Serbest bölge","Askerî bölge"]'::jsonb, 0, 'cografya'),
('Enklav kavramı neyi ifade eder?', '["Deniz kıyısı","Bir ülkenin içinde kalan başka toprak","Sınır kapısı","Ada"]'::jsonb, 1, 'cografya'),
('Tampon bölge ne amaçla oluşturulur?', '["Ticaret yapmak","Turizm için","Çatışmayı önlemek için ayırıcı alan","Tarım için"]'::jsonb, 2, 'cografya'),
('Sınır kapısının işlevi nedir?', '["Vergi belirleme","Nüfus sayımı","Hava tahmini","Ülkeler arası resmî giriş çıkış"]'::jsonb, 3, 'cografya'),
('Doğal sınır kavramına örnek hangisidir?', '["Nehir veya dağ","Enlem çizgisi","Yol","Duvar"]'::jsonb, 0, 'cografya'),
('Yapay (geometrik) sınıra örnek nedir?', '["Nehir sınırı","Enlem veya boylam boyunca çizilen sınır","Dağ sınırı","Göl sınırı"]'::jsonb, 1, 'cografya'),
('Afrika''daki birçok sınırın düz çizgi olmasının nedeni nedir?', '["Doğal engeller","Nüfus dağılımı","Sömürge paylaşımı","İklim kuşakları"]'::jsonb, 2, 'cografya'),
('Bir ülkenin ''jeopolitik konumu'' neyi anlatır?', '["Yüzölçümünü","Nüfusunu","İklimini","Siyasi ve stratejik önemini"]'::jsonb, 3, 'cografya'),
('Boğazların jeopolitik önemi neye dayanır?', '["Deniz ulaşımını denetlemeye","Balık zenginliğine","Tuz üretimine","Turizme"]'::jsonb, 0, 'cografya'),
('Montrö Sözleşmesi hangi konuyu düzenler?', '["Süveyş Kanalı''nı","Türk Boğazları''ndan geçiş rejimini","Panama Kanalı''nı","Cebelitarık''ı"]'::jsonb, 1, 'cografya'),
('Kutup bölgelerinin stratejik önemi neye dayanır?', '["Tarıma","Turizme","Kaynak ve yeni deniz yollarına","Sanayiye"]'::jsonb, 2, 'cografya'),
('Hazar Denizi''nin hukuki statüsü neden tartışmalıdır?', '["Derinliği","Tuzluluğu","Konumu","Deniz mi göl mü olduğu ayrımı"]'::jsonb, 3, 'cografya'),
('Ege Denizi''ne kıyısı olan ülkeler hangileridir?', '["Türkiye ve Yunanistan","Türkiye ve Bulgaristan","Yunanistan ve İtalya","Türkiye ve Kıbrıs"]'::jsonb, 0, 'cografya'),
('Baltık Denizi''ne kıyısı olmayan ülke hangisidir?', '["İsveç","Norveç","Finlandiya","Polonya"]'::jsonb, 1, 'cografya'),
('Kuzey Buz Denizi''ne kıyısı olan ülkelerden biri hangisidir?', '["Almanya","Fransa","Rusya","İspanya"]'::jsonb, 2, 'cografya'),
('Denize kıyısı olmayan Avrupa ülkelerinden biri hangisidir?', '["Hırvatistan","Slovenya","Portekiz","Avusturya"]'::jsonb, 3, 'cografya'),
('Denize kıyısı olmayan Güney Amerika ülkesi hangisidir?', '["Bolivya","Peru","Şili","Ekvador"]'::jsonb, 0, 'cografya'),
('Kıtaların oluşumunu açıklayan ilk kuramı öne süren kimdir?', '["Charles Lyell","Alfred Wegener","James Hutton","Charles Darwin"]'::jsonb, 1, 'cografya'),
('Kıta kayması kuramının kanıtlarından biri nedir?', '["Nüfus dağılımı","Dil benzerliği","Kıyı çizgilerinin birbirine uyması","İklim benzerliği yalnızca"]'::jsonb, 2, 'cografya'),
('Deniz tabanı yayılması kuramı neyi destekler?', '["Buzul kuramını","Karst kuramını","Erozyon kuramını","Levha tektoniğini"]'::jsonb, 3, 'cografya'),
('Yıkım (dalma-batma) zonlarında ne oluşur?', '["Derin deniz çukurları ve volkanlar","Delta ovaları","Kum çölleri","Buzul vadileri"]'::jsonb, 0, 'cografya'),
('Transform fay hareketinin özelliği nedir?', '["Levhaların çarpışması","Levhaların yanal kayması","Levhaların uzaklaşması","Levhaların durması"]'::jsonb, 1, 'cografya'),
('San Andreas Fayı hangi ülkededir?', '["Japonya","Şili","ABD","Yeni Zelanda"]'::jsonb, 2, 'cografya'),
('Bir bölgede sıcak su kaynaklarının çokluğu neyi gösterir?', '["Yağış çokluğunu","Buzul varlığını","Delta oluşumunu","Yer altı ısı akısının yüksekliğini"]'::jsonb, 3, 'cografya'),
('Maden suyunun oluşumu neye bağlıdır?', '["Suyun mineralli katmanlardan geçmesine","Deniz suyunun süzülmesine","Buzul erimesine","Yağmurun donmasına"]'::jsonb, 0, 'cografya'),
('Akiferin tanımı nedir?', '["Geçirimsiz kil tabakası","Su tutan ve ileten geçirimli katman","Volkanik koni","Buzul yatağı"]'::jsonb, 1, 'cografya'),
('Yeraltı suyunun aşırı çekilmesi kıyıda neye yol açar?', '["Yağış artışına","Toprak zenginleşmesine","Tuzlu su girişimine","Deprem azalmasına"]'::jsonb, 2, 'cografya'),
('Kum ve çakıl ocaklarının dere yatağındaki riski nedir?', '["Suyun temizlenmesi","Balığın çoğalması","Erozyonun bitmesi","Yatağın bozulup taşkın artması"]'::jsonb, 3, 'cografya'),
('Bir gölün ''kapalı havza'' göllerinden ayrılan yanı nedir?', '["Suyunu denize boşaltabilmesi","Tuzlu olması","Derin olması","Volkanik olması"]'::jsonb, 0, 'cografya'),
('Türkiye''de sulak alanların azalmasının başlıca nedeni nedir?', '["Yağış artışı","Kurutma ve aşırı su çekimi","Deprem","Volkan"]'::jsonb, 1, 'cografya'),
('Bir bölgede bitki örtüsünün tahrip edilmesi ilk olarak neyi artırır?', '["Yağışı","Nemi","Erozyonu","Verimi"]'::jsonb, 2, 'cografya'),
('Ağaçlandırmada tür seçimi neye göre yapılmalıdır?', '["Hızlı büyümeye yalnızca","Fiyata","Görünüşe","Yörenin iklim ve toprağına"]'::jsonb, 3, 'cografya'),
('Mera ıslahının amacı nedir?', '["Otlak verimini ve örtüyü iyileştirmek","Otlağı kapatmak","Hayvan sayısını azaltmak","Toprağı sürmek"]'::jsonb, 0, 'cografya'),
('Aşırı otlatmanın sonucu nedir?', '["Otun çoğalması","Bitki örtüsünün seyrelmesi","Toprağın zenginleşmesi","Suyun artması"]'::jsonb, 1, 'cografya'),
('Orman ekosisteminde ölü örtünün işlevi nedir?', '["Yangını önlemek","Ağacı kurutmak","Toprağı besleyip nemi korumak","Erozyonu artırmak"]'::jsonb, 2, 'cografya'),
('Bir ağacın yaşının belirlenmesinde neye bakılır?', '["Yaprak sayısına","Gövde rengine","Kök derinliğine","Yıllık halkalara"]'::jsonb, 3, 'cografya'),
('Dendrokronoloji neyi inceler?', '["Ağaç halkalarıyla tarihleme","Kayaç yaşını","Fosil türünü","Toprak rengini"]'::jsonb, 0, 'cografya'),
('Bir bölgenin geçmiş iklimini incelemek için hangi kayıtlar kullanılır?', '["Nüfus kayıtları","Buz karotları ve tortullar","Yol haritaları","Vergi defterleri"]'::jsonb, 1, 'cografya'),
('Polen analizi neyi ortaya koyar?', '["Deprem tarihini","Maden yatağını","Geçmişteki bitki örtüsünü","Nüfus sayısını"]'::jsonb, 2, 'cografya')
on conflict (soru) do nothing;
