-- Soru havuzu genişletme: cografya +73
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Sinop''un coğrafi özelliği nedir?', '["Türkiye''nin en kuzey noktasında olması","En doğu noktası","En yüksek ili","En büyük ili"]'::jsonb, 0, 'cografya'),
('Rize''nin iklim özelliği nedir?', '["En kurak olması","Türkiye''de en çok yağış alması","En sıcak olması","En soğuk olması"]'::jsonb, 1, 'cografya'),
('Şanlıurfa''nın tarımsal önemi nedir?', '["Çay üretimi","Fındık üretimi","GAP sulamasıyla üretim merkezi olması","Balıkçılık"]'::jsonb, 2, 'cografya'),
('Adana''nın sanayisinde öne çıkan alan nedir?', '["Gemi inşa","Kömür","Kereste","Tekstil ve gıda"]'::jsonb, 3, 'cografya'),
('Mersin''in ekonomik önemi nedir?', '["Büyük liman ve narenciye üretimi","Kömür madenciliği","Çay üretimi","Kayak turizmi"]'::jsonb, 0, 'cografya'),
('Muğla''nın turizmde öne çıkmasının nedeni nedir?', '["Kayak pistleri","Girintili çıkıntılı kıyı ve koylar","Termal kaynaklar","Maden yatakları"]'::jsonb, 1, 'cografya'),
('Çanakkale''nin stratejik önemi nedir?', '["Maden zenginliği","Tarım alanı","Boğaz geçişini denetlemesi","Kayak turizmi"]'::jsonb, 2, 'cografya'),
('Kocaeli''nin sanayi açısından önemi nedir?', '["Turizm merkezi","Tarım merkezi","Kayak merkezi","Ağır sanayi ve liman yoğunluğu"]'::jsonb, 3, 'cografya'),
('Eskişehir''in sanayisinde öne çıkan alan nedir?', '["Raylı sistem ve havacılık","Balıkçılık","Çay","Muz"]'::jsonb, 0, 'cografya'),
('Konya''nın tarımdaki yeri nedir?', '["Çay merkezi","Türkiye''nin tahıl ambarı sayılması","Fındık merkezi","Balıkçılık merkezi"]'::jsonb, 1, 'cografya'),
('Kayseri''nin sanayisinde öne çıkan alan nedir?', '["Gemi inşa","Petrol rafinerisi","Mobilya ve gıda","Çay işleme"]'::jsonb, 2, 'cografya'),
('Gaziantep sanayisinde hangi alan öne çıkar?', '["Gemi inşa","Kayak","Balıkçılık","Halı ve gıda"]'::jsonb, 3, 'cografya'),
('Diyarbakır''ın tarihi surlarının özelliği nedir?', '["Dünya mirası listesinde olması","Yeni yapılmış olması","Ahşap olması","Yıkılmış olması"]'::jsonb, 0, 'cografya'),
('Trabzon''un ekonomisinde öne çıkan alan nedir?', '["Pamuk","Liman, fındık ve turizm","Zeytin","Muz"]'::jsonb, 1, 'cografya'),
('Samsun''un tarımsal önemi nedir?', '["Kurak tarım","Kayak turizmi","Delta ovalarıyla verimli üretim","Maden"]'::jsonb, 2, 'cografya'),
('Zonguldak''ın ekonomisinde öne çıkan alan nedir?', '["Turizm","Zeytincilik","Muzculuk","Taş kömürü madenciliği"]'::jsonb, 3, 'cografya'),
('Balıkesir''in coğrafi özelliği nedir?', '["Hem Marmara hem Ege''ye kıyısı olması","Denize kıyısı olmaması","Yalnız Karadeniz kıyısı","Yalnız Akdeniz kıyısı"]'::jsonb, 0, 'cografya'),
('Aydın''ın tarımında öne çıkan ürün nedir?', '["Çay","İncir ve zeytin","Fındık","Muz"]'::jsonb, 1, 'cografya'),
('Manisa''nın tarımında öne çıkan ürün nedir?', '["Çay","Fındık","Üzüm","Muz"]'::jsonb, 2, 'cografya'),
('Antalya''nın tarımında öne çıkan üretim biçimi nedir?', '["Kuru tarım","Mera hayvancılığı","Ormancılık","Örtü altı (sera) üretimi"]'::jsonb, 3, 'cografya'),
('Isparta''nın sanayisinde öne çıkan alan nedir?', '["Gül ürünleri ve halıcılık","Gemi inşa","Otomotiv","Petrol"]'::jsonb, 0, 'cografya'),
('Erzincan''ın jeolojik riski nedir?', '["Volkan riski","Fay hattı üzerinde olması","Buzul riski","Tsunami riski"]'::jsonb, 1, 'cografya'),
('Van''ın coğrafi özelliği nedir?', '["En büyük ovaya sahip olması","Denize kıyısı olması","En büyük gölümüze kıyısı olması","En düşük rakımlı olması"]'::jsonb, 2, 'cografya'),
('Bitlis''in coğrafi özelliği nedir?', '["Kıyı ovası","Çöl","Delta","Yüksek dağlık ve karlı olması"]'::jsonb, 3, 'cografya'),
('Batman''ın ekonomisinde öne çıkan alan nedir?', '["Petrol ve rafineri","Çay üretimi","Fındık","Kayak"]'::jsonb, 0, 'cografya'),
('Siirt''in yöresel ürünü nedir?', '["Çay","Fıstık ve battaniye","Fındık","Kivi"]'::jsonb, 1, 'cografya'),
('Adıyaman''ın turizmde öne çıkan değeri nedir?', '["Uzungöl","Pamukkale","Nemrut Dağı","Ölüdeniz"]'::jsonb, 2, 'cografya'),
('Kahramanmaraş''ın yöresel ürünü nedir?', '["Çay","Fındık","Kivi","Dondurma ve biber"]'::jsonb, 3, 'cografya'),
('Osmaniye''nin tarımında öne çıkan ürün nedir?', '["Yer fıstığı","Çay","Fındık","Kivi"]'::jsonb, 0, 'cografya'),
('Tokat''ın yöresel ürünü nedir?', '["Muz","Yaprak (asma yaprağı)","Çay","Kivi"]'::jsonb, 1, 'cografya'),
('Amasya''nın tarihsel özelliği nedir?', '["Liman kenti olması","Kayak merkezi olması","Şehzadeler şehri olarak anılması","Çöl kenti olması"]'::jsonb, 2, 'cografya'),
('Çorum''un yöresel ürünü nedir?', '["Muz","Kivi","Çay","Leblebi"]'::jsonb, 3, 'cografya'),
('Nevşehir''in turizmde öne çıkan değeri nedir?', '["Peribacaları","Kayak pistleri","Ölüdeniz","Pamukkale"]'::jsonb, 0, 'cografya'),
('Aksaray''ın turizmde öne çıkan değeri nedir?', '["Sümela","Ihlara Vadisi","Nemrut","Uzungöl"]'::jsonb, 1, 'cografya'),
('Niğde''nin tarımında öne çıkan ürün nedir?', '["Çay","Muz","Patates ve elma","Zeytin"]'::jsonb, 2, 'cografya'),
('Karaman''ın yöresel ürünü nedir?', '["Çay","Fındık","Kivi","Elma"]'::jsonb, 3, 'cografya'),
('Burdur''un doğal değeri nedir?', '["Salda Gölü","Uzungöl","Abant","Çıldır"]'::jsonb, 0, 'cografya'),
('Denizli''nin turizmde öne çıkan değeri nedir?', '["Peribacaları","Pamukkale travertenleri","Nemrut","Sümela"]'::jsonb, 1, 'cografya'),
('Bartın''ın turizmde öne çıkan değeri nedir?', '["Kapadokya","Pamukkale","Amasra kıyıları","Nemrut"]'::jsonb, 2, 'cografya'),
('Kastamonu''nun doğal değeri nedir?', '["Çöl","Delta","Buzul","Küre Dağları ve kanyonlar"]'::jsonb, 3, 'cografya'),
('Düzce''nin coğrafi konumu nedir?', '["Batı Karadeniz","Doğu Karadeniz","Ege","Akdeniz"]'::jsonb, 0, 'cografya'),
('Sakarya''nın tarımında öne çıkan ürün nedir?', '["Muz","Fındık ve mısır","Zeytin","Antep fıstığı"]'::jsonb, 1, 'cografya'),
('Tekirdağ''ın tarımında öne çıkan ürün nedir?', '["Çay","Muz","Ayçiçeği ve buğday","Fındık"]'::jsonb, 2, 'cografya'),
('Kırklareli''nin coğrafi özelliği nedir?', '["Çöl","Volkan","Buzul","Istranca Dağları ve orman varlığı"]'::jsonb, 3, 'cografya'),
('Türkiye''de karaca ve yaban keçisi hangi ortamda yaşar?', '["Dağlık ve ormanlık alanlarda","Çöllerde","Bataklıklarda","Kutupta"]'::jsonb, 0, 'cografya'),
('Anadolu leoparının durumu nedir?', '["Yaygın","Nesli ciddi tehlike altında","Evcil","İstilacı"]'::jsonb, 1, 'cografya'),
('Akdeniz foku hangi ortamda yaşar?', '["Dağ zirvelerinde","Çölde","Kıyı mağaralarında","Buzulda"]'::jsonb, 2, 'cografya'),
('Caretta caretta kaplumbağası nerede yumurtlar?', '["Kayalıklarda","Ormanda","Bataklıkta","Kumsallarda"]'::jsonb, 3, 'cografya'),
('Caretta caretta için korunan kumsallardan biri nerededir?', '["Dalyan","Uzungöl","Abant","Kapadokya"]'::jsonb, 0, 'cografya'),
('Kelaynak kuşu Türkiye''de hangi ilde korunur?', '["Rize","Şanlıurfa (Birecik)","Trabzon","Edirne"]'::jsonb, 1, 'cografya'),
('Leylekler Türkiye''den hangi mevsimde göç eder?', '["İlkbaharda","Yazın","Sonbaharda","Kışın"]'::jsonb, 2, 'cografya'),
('Kuş göçlerinde Boğazlar''ın önemi nedir?', '["Yumurtlama alanı","Kışlama alanı","Beslenme yasağı","Göç yolu üzerinde geçiş noktası olması"]'::jsonb, 3, 'cografya'),
('Deniz kaplumbağalarının en büyük tehdidi nedir?', '["Kıyı yapılaşması ve plastik","Soğuk hava","Yağış","Rüzgâr"]'::jsonb, 0, 'cografya'),
('Kutup ayısı hangi bölgede yaşar?', '["Güney Kutbu","Kuzey Kutbu çevresi","Sahra","Amazon"]'::jsonb, 1, 'cografya'),
('Kanguru hangi kıtaya özgüdür?', '["Afrika","Asya","Avustralya","Güney Amerika"]'::jsonb, 2, 'cografya'),
('Lama hangi kıtada yaşar?', '["Afrika","Avrupa","Okyanusya","Güney Amerika"]'::jsonb, 3, 'cografya'),
('Zürafa hangi kıtada doğal olarak bulunur?', '["Afrika","Asya","Avrupa","Amerika"]'::jsonb, 0, 'cografya'),
('Panda hangi ülkeye özgüdür?', '["Japonya","Çin","Hindistan","Vietnam"]'::jsonb, 1, 'cografya'),
('Koala hangi ülkede yaşar?', '["Yeni Zelanda","Endonezya","Avustralya","Filipinler"]'::jsonb, 2, 'cografya'),
('Karada deniz seviyesine göre en alçak nokta hangisidir?', '["Hazar kıyısı","Vadi tabanı","Delta","Ölü Deniz kıyısı"]'::jsonb, 3, 'cografya'),
('Dünyanın en kurak yerlerinden biri sayılan çöl hangisidir?', '["Atacama","Gobi","Kalahari","Karakum"]'::jsonb, 0, 'cografya'),
('Dünyanın en yağışlı yerlerinden biri hangi bölgededir?', '["Sahra","Kuzeydoğu Hindistan","Sibirya","Patagonya"]'::jsonb, 1, 'cografya'),
('Dünyanın en soğuk yerleşim yerlerinden biri nerededir?', '["Sahra","Amazon","Sibirya","Akdeniz"]'::jsonb, 2, 'cografya'),
('Dünyanın en uzun kıyı şeridine sahip ülkesi hangisidir?', '["Rusya","Avustralya","Çin","Kanada"]'::jsonb, 3, 'cografya'),
('Ada devleti olmayan ülke hangisidir?', '["Moğolistan","Malta","Kıbrıs","İzlanda"]'::jsonb, 0, 'cografya'),
('Dünya nüfusunun büyük bölümü hangi yarım kürede yaşar?', '["Güney","Kuzey","Eşit dağılmış","Batı yalnızca"]'::jsonb, 1, 'cografya'),
('Nüfusun kıyı bölgelerinde yoğunlaşmasının nedeni nedir?', '["Maden varlığı","Yükselti","Ulaşım, ticaret ve ılıman iklim","Orman"]'::jsonb, 2, 'cografya'),
('Yüksek dağ ve kutup bölgelerinde nüfusun az olmasının nedeni nedir?', '["Toprak fazlalığı","Su fazlalığı","Ulaşım kolaylığı","Yaşam koşullarının zorluğu"]'::jsonb, 3, 'cografya'),
('Çöllerde nüfusun vahalarda toplanmasının nedeni nedir?', '["Su varlığı","Rüzgâr","Kum","Sıcaklık"]'::jsonb, 0, 'cografya'),
('Türk mutfağında bölgesel çeşitliliğin nedeni nedir?', '["Nüfus yoğunluğu","İklim ve ürün çeşitliliği","Yol ağı","Sanayi"]'::jsonb, 1, 'cografya'),
('Karadeniz mutfağında hangi ürün öne çıkar?', '["Antep fıstığı","Zeytinyağı","Hamsi ve mısır","Bulgur"]'::jsonb, 2, 'cografya'),
('Ege mutfağında öne çıkan malzeme nedir?', '["Tereyağı ve et","Hamsi","Mısır unu","Zeytinyağı ve ot yemekleri"]'::jsonb, 3, 'cografya'),
('Doğu Anadolu mutfağında öne çıkan ürün nedir?', '["Süt ürünleri ve et","Zeytinyağı","Hamsi","Muz"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
