-- Soru havuzu genişletme: sinema +15, teknoloji +15, muzik +14, spor +14, sanat +14, edebiyat +15, tarih +11, bilim +14, genel_kultur +15
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Sinemada ''kısa devre kurgu'' yerine kullanılan doğru terim nedir?', '["Paralel kurgu","Uzun plan","Yakın plan","Dış ses"]'::jsonb, 0, 'sinema'),
('Bir filmin ''ön gösterimi'' ne amaçla yapılır?', '["Bilet fiyatı belirlemek","Basın ve seçili izleyiciye sunmak","Kurgu yapmak","Senaryo yazmak"]'::jsonb, 1, 'sinema'),
('Film afişinin işlevi nedir?', '["Filmi özetlemek","Kurgu yapmak","Filmi görsel olarak tanıtmak","Bilet basmak"]'::jsonb, 2, 'sinema'),
('Sinemada ''devam filmi'' (sequel) nedir?', '["Öncesini anlatan yapım","Yeniden çekim","Belgesel","Hikâyenin sonrasını anlatan yapım"]'::jsonb, 3, 'sinema'),
('Film serisi (franchise) kavramı neyi anlatır?', '["Ortak evrende süren yapımlar bütünü","Tek film","Kısa film","Belgesel dizisi"]'::jsonb, 0, 'sinema'),
('Sinemada ''kamera hareketi pan'' nedir?', '["Dikey dönmesi","Kameranın yatay dönmesi","İleri gitmesi","Yükselmesi"]'::jsonb, 1, 'sinema'),
('Kameranın dikey dönmesine ne ad verilir?', '["Pan","Dolly","Tilt","Zoom"]'::jsonb, 2, 'sinema'),
('Vinç (crane) çekimi ne sağlar?', '["Yerden yakın çekim","Su altı çekim","Gece çekim","Yükselerek geniş bakış"]'::jsonb, 3, 'sinema'),
('Drone çekiminin sinemadaki katkısı nedir?', '["Havadan hareketli görüntü","Ses kaydı","Işık düzeni","Renk düzeltme"]'::jsonb, 0, 'sinema'),
('Sinemada ''yavaş çekim'' hangi etkiyi yaratır?', '["Zamanı kısaltmak","Anı uzatıp vurgulamak","Ses artırmak","Renk soldurmak"]'::jsonb, 1, 'sinema'),
('Hızlandırılmış çekim ne için kullanılır?', '["Anı uzatmak","Ses eklemek","Uzun süreci kısaca göstermek","Kadraj daraltmak"]'::jsonb, 2, 'sinema'),
('Sinemada ''donmuş kare'' etkisi nedir?', '["Görüntünün kararması","Sesin kesilmesi","Rengin değişmesi","Görüntünün sabitlenmesi"]'::jsonb, 3, 'sinema'),
('Bir filmde ''anlatıcı'' kullanımı neyi sağlar?', '["Olayı dışarıdan aktarmayı","Diyalogu kaldırmayı","Kurguyu hızlandırmayı","Işığı artırmayı"]'::jsonb, 0, 'sinema'),
('Sinemada ''kurgusal zaman'' ne demektir?', '["Filmin süresi","Filmde kurulan zaman düzeni","Çekim tarihi","Vizyon tarihi"]'::jsonb, 1, 'sinema'),
('Yapım şirketi ile dağıtımcı arasındaki fark nedir?', '["Yapımcının salon açması","İkisinin aynı olması","Dağıtımcının filmi salonlara ulaştırması","Dağıtımcının çekim yapması"]'::jsonb, 2, 'sinema'),
('Bilgisayarda ''çözünürlük 4K'' yaklaşık kaç yatay piksele karşılık gelir?', '["3840","1920","1280","7680"]'::jsonb, 0, 'teknoloji'),
('Yenilenebilir enerji ile çalışan veri merkezlerinin amacı nedir?', '["Hız artırmak","Karbon ayak izini azaltmak","Depolama artırmak","Şifre üretmek"]'::jsonb, 1, 'teknoloji'),
('E-imza hangi işlemde kullanılır?', '["Dosya sıkıştırmada","Ağ kurmada","Belgenin yasal olarak imzalanmasında","Renk düzeltmede"]'::jsonb, 2, 'teknoloji'),
('İki faktörlü doğrulamada ikinci faktör genelde nedir?', '["Kullanıcı adı","E-posta adresi","Doğum tarihi","Tek kullanımlık kod"]'::jsonb, 3, 'teknoloji'),
('Yazılımların düzenli yenilenmesi neden önemlidir?', '["Bilinen açıkları kapatması","Hız artırması","Depolama açması","Renk değiştirmesi"]'::jsonb, 0, 'teknoloji'),
('Kamuya açık kablosuz ağlarda risk nedir?', '["Hızın artması","Trafiğin izlenebilmesi","Pilin bitmesi","Ekranın kararması"]'::jsonb, 1, 'teknoloji'),
('Tarayıcı eklentilerinin riski nedir?', '["Ekran büyütmesi","Yazı tipi değiştirmesi","Geniş izinlerle veri erişimi","Sekme açması"]'::jsonb, 2, 'teknoloji'),
('Yazılımda ''kapalı kaynak'' ne demektir?', '["Ücretsiz olması","Açık geliştirilmesi","Lisanssız olması","Kaynak kodun paylaşılmaması"]'::jsonb, 3, 'teknoloji'),
('Bir uygulamanın ''gizlilik politikası'' neyi açıklar?', '["Hangi verinin nasıl işlendiğini","Fiyatı","Kurulum adımlarını","Sistem gereksinimini"]'::jsonb, 0, 'teknoloji'),
('Veri saklama süresi sınırının amacı nedir?', '["Depolama artırmak","Gereksiz veriyi tutmamak","Hız düşürmek","Yedek almak"]'::jsonb, 1, 'teknoloji'),
('Sunucusuz (serverless) mimaride geliştirici neyle ilgilenmez?', '["Kod yazımıyla","Test ile","Sunucu yönetimiyle","Tasarımla"]'::jsonb, 2, 'teknoloji'),
('API anahtarının gizli tutulması neden gerekir?', '["Hız için","Renk için","Boyut için","Yetkisiz kullanımı önlemek için"]'::jsonb, 3, 'teknoloji'),
('Yazılımda dış kütüphaneleri yenilemek neden gerekir?', '["Güvenlik açıklarını kapatmak","Kodu kısaltmak","Renk değiştirmek","Ekran açmak"]'::jsonb, 0, 'teknoloji'),
('Kod incelemesi (code review) ne sağlar?', '["Sunucu kurulumunu","Hataların erken yakalanmasını","Bilet satışını","Tasarımı"]'::jsonb, 1, 'teknoloji'),
('Teknik borç kavramı neyi ifade eder?', '["Yazılım fiyatını","Sunucu kirasını","Hızlı çözümlerin ileriki maliyetini","Lisans ücretini"]'::jsonb, 2, 'teknoloji'),
('Bir şarkıda ''köprü'' (bridge) bölümü ne sağlar?', '["Farklı bir geçiş bölümü","Nakaratın tekrarı","Girişin uzaması","Solo zorunluluğu"]'::jsonb, 0, 'muzik'),
('Şarkı yapısında ''intro'' nedir?', '["Bitiş bölümü","Giriş bölümü","Nakarat","Solo"]'::jsonb, 1, 'muzik'),
('Outro terimi neyi ifade eder?', '["Giriş","Nakarat","Bitiş bölümü","Köprü"]'::jsonb, 2, 'muzik'),
('Vokal ''ikinci ses'' (back vokal) ne yapar?', '["Ana ezgiyi taşır","Ritim tutar","Solo çalar","Ana sese eşlik eder"]'::jsonb, 3, 'muzik'),
('Kanon ile füg arasındaki temel fark nedir?', '["Fügün daha karmaşık işlenmesi","Kanonun sözlü olması","Fügün tek sesli olması","İkisinin aynı olması"]'::jsonb, 0, 'muzik'),
('Türk müziğinde ''kâr'' formu nedir?', '["Kısa saz eseri","Büyük formlu sözlü eser","Serbest doğaçlama","Halk türküsü"]'::jsonb, 1, 'muzik'),
('Türk müziğinde ''şarkı'' formunun özelliği nedir?', '["Sözsüz olması","Serbest ritimli olması","Belirli bölüm düzeni olan sözlü eser","Doğaçlama olması"]'::jsonb, 2, 'muzik'),
('Bir eserde ''nüans işaretleri'' neyi belirler?', '["Tempoyu","Tonu","Ölçüyü","Ses gürlüğü değişimini"]'::jsonb, 3, 'muzik'),
('Orkestra şefinin bagetle verdiği temel bilgi nedir?', '["Tempo ve giriş işaretleri","Nota adları","Şarkı sözü","Kostüm düzeni"]'::jsonb, 0, 'muzik'),
('Bir eserin ''partisyonu'' nedir?', '["Tek çalgının notası","Tüm çalgı partilerini gösteren nota","Şarkı sözü","Konser afişi"]'::jsonb, 1, 'muzik'),
('Bando topluluğunda ağırlıklı çalgı ailesi hangisidir?', '["Yaylılar","Tuşlular","Üflemeli ve vurmalılar","Telli mızraplılar"]'::jsonb, 2, 'muzik'),
('Mehter takımının tarihsel işlevi neydi?', '["Saray dansı","Dinî ayin","Halk düğünü","Askerî tören ve moral müziği"]'::jsonb, 3, 'muzik'),
('Türk müziğinde ''sazende'' kimdir?', '["Çalgı icra eden kişi","Şarkı söyleyen","Beste yapan","Şef"]'::jsonb, 0, 'muzik'),
('Türk müziğinde ''hanende'' kimdir?', '["Çalgı çalan","Şarkı söyleyen kişi","Şef","Besteci"]'::jsonb, 1, 'muzik'),
('Olimpiyat oyunlarında ''meşale'' neyi simgeler?', '["Sürekliliği ve barışı","Rekabeti","Zaferi","Ödülü"]'::jsonb, 0, 'spor'),
('Kış olimpiyatları hangi sporları kapsar?', '["Su sporlarını","Kar ve buz sporlarını","Salon sporlarını","Atletizmi"]'::jsonb, 1, 'spor'),
('Olimpiyatlarda madalya sıralaması neye göre yapılır?', '["Sporcu sayısına göre","Nüfusa göre","Altın madalya sayısına göre","Bütçeye göre"]'::jsonb, 2, 'spor'),
('Sporda ''rekor'' kavramı neyi ifade eder?', '["Ortalama derece","Antrenman süresi","Katılım sayısı","Resmî olarak ölçülmüş en iyi derece"]'::jsonb, 3, 'spor'),
('Bir sporcu ''diskalifiye'' edildiğinde ne olur?', '["Yarışmadan çıkarılır","Puanı yarıya iner","Uyarı alır","Sıralaması düşer"]'::jsonb, 0, 'spor'),
('Hakem kararına itiraz mekanizmasının amacı nedir?', '["Süreyi uzatmak","Hatalı kararı düzeltmek","Seyirciyi eğlendirmek","Maçı ertelemek"]'::jsonb, 1, 'spor'),
('Sporda ''video yardımcı hakem'' hangi kararlarda devreye girer?', '["Her pozisyonda","Yalnız faullerde","Belirlenmiş kritik durumlarda","Yalnız kartlarda"]'::jsonb, 2, 'spor'),
('Bir ligde ''averaj'' neye göre hesaplanır?', '["Maç sayısına","Seyirci sayısına","Kart sayısına","Atılan ve yenilen gol farkına"]'::jsonb, 3, 'spor'),
('Kupa formatında ''eleme usulü'' ne demektir?', '["Kaybedenin turnuvadan çıkması","Herkesin devam etmesi","Puan toplanması","Beraberlik olmaması"]'::jsonb, 0, 'spor'),
('Lig usulünde takımlar nasıl karşılaşır?', '["Tek maç eleme","Herkes herkesle oynar","Kura ile","Gruplarda kalır"]'::jsonb, 1, 'spor'),
('Sporda ''ev sahibi avantajı'' neye dayanır?', '["Kural farkı","Süre farkı","Taraftar desteği ve alışkanlık","Kadro farkı"]'::jsonb, 2, 'spor'),
('Sporda ''fikstür'' ne anlama gelir?', '["Puan cetveli","Kadro listesi","Bilet fiyatı","Maç takvimi"]'::jsonb, 3, 'spor'),
('Bir kulübün ''altyapısı'' neyi ifade eder?', '["Genç sporcu yetiştirme yapısı","Stadyum zemini","Yönetim kadrosu","Sponsor listesi"]'::jsonb, 0, 'spor'),
('Sporda ''transfer dönemi'' neyi belirler?', '["Maç takvimini","Oyuncu geçişlerine izin verilen süreyi","Bilet fiyatını","Antrenman saatini"]'::jsonb, 1, 'spor'),
('Bizans sanatında ''ikona'' nedir?', '["Dinî konulu taşınabilir resim","Duvar mozaiği","Heykel","Vitray"]'::jsonb, 0, 'sanat'),
('Rönesans''ta ''insan merkezli'' anlayışa ne ad verilir?', '["Skolastik","Hümanizm","Mistisizm","Determinizm"]'::jsonb, 1, 'sanat'),
('Leonardo da Vinci''nin çok yönlülüğü hangi kavramla anılır?', '["Barok usta","Gotik mimar","Rönesans insanı","Modern tasarımcı"]'::jsonb, 2, 'sanat'),
('Rönesans heykelinde ''kontrapost'' duruşu neyi anlatır?', '["Simetrik duruş","Oturur duruş","Yatık duruş","Ağırlığın tek bacağa verilmesi"]'::jsonb, 3, 'sanat'),
('Barok mimaride ışık kullanımı neyi amaçlar?', '["Dramatik etki yaratmak","Sadelik sağlamak","Maliyeti düşürmek","Simetri kurmak"]'::jsonb, 0, 'sanat'),
('Empresyonist ressamların açık havada çalışmasına ne ad verilir?', '["Sfumato","Plein air","Grisaille","Impasto"]'::jsonb, 1, 'sanat'),
('Impasto tekniği neyi ifade eder?', '["İnce saydam katman","Nokta tekniği","Boyanın kalın sürülmesi","Kolaj"]'::jsonb, 2, 'sanat'),
('Kolajın kübizmdeki rolü nedir?', '["Perspektifi güçlendirmek","Rengi azaltmak","Portre yapmak","Gerçek malzemeyi resme katmak"]'::jsonb, 3, 'sanat'),
('Ready-made (hazır nesne) kavramı kime aittir?', '["Marcel Duchamp","Picasso","Matisse","Warhol"]'::jsonb, 0, 'sanat'),
('Land art (arazi sanatı) nerede üretilir?', '["Galeride","Doğal arazide","Stüdyoda","Müzede"]'::jsonb, 1, 'sanat'),
('Sanatta ''seri üretim'' eleştirisini pop art nasıl yapar?', '["Doğa resmi yaparak","Portre yaparak","Tüketim imgelerini yineleyerek","Heykel dökerek"]'::jsonb, 2, 'sanat'),
('Dijital sanatın ayırt edici yanı nedir?', '["Yalnız tuval kullanması","Yalnız taş kullanması","Baskı olmaması","Sayısal araçlarla üretilmesi"]'::jsonb, 3, 'sanat'),
('Sanat kurumlarında ''rezidans programı'' ne sağlar?', '["Sanatçıya üretim için mekân ve süre","Eser satışı","Bilet indirimi","Katalog basımı"]'::jsonb, 0, 'sanat'),
('Sanat piyasasında ''müzayede'' ne demektir?', '["Sabit fiyat satışı","Açık artırmayla satış","Bağış","Kiralama"]'::jsonb, 1, 'sanat'),
('Türk edebiyatında ''Beş Hececiler'' hangi dönemde etkilidir?', '["Milli Edebiyat çevresi","Tanzimat","Servet-i Fünun","İkinci Yeni"]'::jsonb, 0, 'edebiyat'),
('Fecr-i Ati topluluğu hangi dönemde ortaya çıkmıştır?', '["Tanzimat öncesi","Servet-i Fünun sonrası","Cumhuriyet sonrası","Divan dönemi"]'::jsonb, 1, 'edebiyat'),
('Nurullah Ataç hangi türde tanınır?', '["Roman","Destan","Deneme ve eleştiri","Tiyatro"]'::jsonb, 2, 'edebiyat'),
('Melih Cevdet Anday hangi akımla anılır?', '["İkinci Yeni","Servet-i Fünun","Fecr-i Ati","Garip"]'::jsonb, 3, 'edebiyat'),
('Turgut Uyar hangi şiir akımıyla anılır?', '["İkinci Yeni","Garip","Beş Hececiler","Milli Edebiyat"]'::jsonb, 0, 'edebiyat'),
('Edip Cansever hangi türde eser vermiştir?', '["Roman","Şiir","Tiyatro","Deneme"]'::jsonb, 1, 'edebiyat'),
('İlhan Berk hangi şiir anlayışıyla anılır?', '["Garip","Toplumcu gerçekçi","İkinci Yeni","Divan"]'::jsonb, 2, 'edebiyat'),
('Behçet Necatigil hangi türde tanınır?', '["Roman","Anı","Gezi","Şiir"]'::jsonb, 3, 'edebiyat'),
('Attila İlhan şiirinde hangi izlek öne çıkar?', '["Aşk ve toplumsal duyarlık","Bilim kurgu","Fantastik","Polisiye"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında ''köy enstitüsü kuşağı'' hangi konuyu işler?', '["Saray hayatı","Kırsal yaşam ve eğitim","Uzay macerası","Deniz seferleri"]'::jsonb, 1, 'edebiyat'),
('Mahmut Makal''ın Bizim Köy eseri hangi türdedir?', '["Roman","Şiir","Anı-röportaj","Tiyatro"]'::jsonb, 2, 'edebiyat'),
('Tarık Buğra''nın Küçük Ağa romanı hangi dönemi anlatır?', '["Lale Devri","Tanzimat","Fetih dönemi","Milli Mücadele"]'::jsonb, 3, 'edebiyat'),
('Türk edebiyatında ''anlatı'' terimi neyi kapsar?', '["Olay aktaran metin türlerini","Yalnız şiiri","Yalnız tiyatroyu","Yalnız denemeyi"]'::jsonb, 0, 'edebiyat'),
('Çeviri edebiyatın işlevi nedir?', '["Yazarı gizlemek","Kültürler arası aktarım sağlamak","Eseri kısaltmak","Metni özetlemek"]'::jsonb, 1, 'edebiyat'),
('Edebiyat kuramında ''okur odaklı'' yaklaşım neye bakar?', '["Yazarın niyetine","Basım tarihine","Metnin okurda ürettiği anlama","Yayınevine"]'::jsonb, 2, 'edebiyat'),
('Osmanlı''nın ilk başkentlerinden biri olan Bursa hangi padişah döneminde alınmıştır?', '["Orhan Bey","Osman Bey","I. Murad","Yıldırım Bayezid"]'::jsonb, 0, 'tarih'),
('Kosova Savaşı hangi bölgede yapılmıştır?', '["Anadolu","Balkanlar","Kafkasya","Kuzey Afrika"]'::jsonb, 1, 'tarih'),
('Ankara Savaşı Osmanlı''da hangi döneme yol açmıştır?', '["Yükselme Dönemi","Lale Devri","Fetret Devri","Tanzimat"]'::jsonb, 2, 'tarih'),
('Çaldıran Savaşı hangi devletle yapılmıştır?', '["Memlükler","Venedik","Macaristan","Safeviler"]'::jsonb, 3, 'tarih'),
('Mercidabık ve Ridaniye savaşları hangi devletle yapılmıştır?', '["Memlükler","Safeviler","Bizans","Habsburg"]'::jsonb, 0, 'tarih'),
('İnebahtı Deniz Savaşı''nın sonucu ne olmuştur?', '["Osmanlı zaferi","Osmanlı donanmasının ağır kayıp vermesi","Ateşkes","Savaşın olmaması"]'::jsonb, 1, 'tarih'),
('Karlofça Antlaşması hangi süreci başlatmıştır?', '["Yükselme dönemini","Fetret devrini","Toprak kayıplarının başlaması","Kuruluş dönemini"]'::jsonb, 2, 'tarih'),
('Pasarofça Antlaşması hangi dönemin başlangıcı sayılır?', '["Tanzimat","Meşrutiyet","Fetret","Lale Devri"]'::jsonb, 3, 'tarih'),
('Sened-i İttifak neyi sınırlamıştır?', '["Padişahın yetkisini","Ayanların yetkisini tümüyle","Ordunun gücünü","Kilisenin yetkisini"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ''ayan'' kimlerdir?', '["Saray görevlileri","Taşrada güçlenen yerel ileri gelenler","Yeniçeriler","Ulema"]'::jsonb, 1, 'tarih'),
('Duyun-u Umumiye idaresi neyi yönetiyordu?', '["Orduyu","Eğitimi","Osmanlı dış borçlarını","Adliyeyi"]'::jsonb, 2, 'tarih'),
('Bir maddenin erime noktası neyi belirtir?', '["Katıdan sıvıya geçtiği sıcaklığı","Kaynadığı sıcaklığı","Donduğu basıncı","Yoğunluğunu"]'::jsonb, 0, 'bilim'),
('Saf maddelerin erime ve kaynama noktaları nasıldır?', '["Değişkendir","Belirli ve sabittir","Yoktur","Rastgeledir"]'::jsonb, 1, 'bilim'),
('Karışımların ayrılmasında ''damıtma'' neye dayanır?', '["Renk farkına","Kütle farkına","Kaynama noktası farkına","Sertlik farkına"]'::jsonb, 2, 'bilim'),
('Süzme yöntemi hangi karışımı ayırır?', '["Gaz karışımını","Sıvı-sıvı karışımını","Metal alaşımını","Katı-sıvı karışımını"]'::jsonb, 3, 'bilim'),
('Buharlaştırma yöntemi neyi ayırır?', '["Çözünmüş katıyı sıvıdan","İki katıyı","İki gazı","Metalleri"]'::jsonb, 0, 'bilim'),
('Mıknatısla ayırma hangi durumda kullanılır?', '["Renkler farklıysa","Manyetik madde varsa","Sıvı ise","Gaz ise"]'::jsonb, 1, 'bilim'),
('Çözelti derişimi neyi ifade eder?', '["Çözeltinin rengini","Çözeltinin sıcaklığını","Birim çözeltideki çözünen miktarını","Kabın hacmini"]'::jsonb, 2, 'bilim'),
('Sıcaklık artışı katıların çözünürlüğünü genelde nasıl etkiler?', '["Azaltır","Değiştirmez","Sıfırlar","Artırır"]'::jsonb, 3, 'bilim'),
('Gazların suda çözünürlüğü sıcaklıkla nasıl değişir?', '["Azalır","Artar","Değişmez","İkiye katlanır"]'::jsonb, 0, 'bilim'),
('Bitkilerde suyun köklerden yapraklara taşınmasını sağlayan doku hangisidir?', '["Soymuk borusu","Odun borusu (ksilem)","Epidermis","Kambiyum"]'::jsonb, 1, 'bilim'),
('Bitkilerde besin taşıyan doku hangisidir?', '["Odun borusu","Kambiyum","Soymuk borusu (floem)","Kütikula"]'::jsonb, 2, 'bilim'),
('Yaprakta gaz alışverişini sağlayan yapı nedir?', '["Kloroplast","Kütikula","Kök tüyü","Stoma"]'::jsonb, 3, 'bilim'),
('Bitkilerde terleme hangi yapıdan gerçekleşir?', '["Stomalardan","Kökten","Gövdeden yalnızca","Tohumdan"]'::jsonb, 0, 'bilim'),
('Tohumun çimlenmesi için gerekli koşullardan biri nedir?', '["Karanlık zorunluluğu","Uygun sıcaklık ve nem","Tuzlu ortam","Donmuş toprak"]'::jsonb, 1, 'bilim'),
('Bir ülkenin bayrağındaki renk ve simgeler neyi temsil eder?', '["Ulusal değer ve tarihi","Nüfusu","Yüzölçümünü","İklimini"]'::jsonb, 0, 'genel_kultur'),
('Milli marşın işlevi nedir?', '["Halk oyunu olmak","Ulusal birliği simgelemek","Dans müziği olmak","Reklam olmak"]'::jsonb, 1, 'genel_kultur'),
('Diplomatik dokunulmazlık kimlere tanınır?', '["Tüm turistlere","Öğrencilere","Diplomatik temsilcilere","Tüccarlara"]'::jsonb, 2, 'genel_kultur'),
('Pasaportun işlevi nedir?', '["Sürücü belgesi","Sağlık kartı","Vergi kaydı","Uluslararası kimlik ve seyahat belgesi"]'::jsonb, 3, 'genel_kultur'),
('Vize ne anlama gelir?', '["Bir ülkeye giriş izni","Kimlik belgesi","Çalışma sözleşmesi","Uçak bileti"]'::jsonb, 0, 'genel_kultur'),
('Çifte vatandaşlık ne demektir?', '["İki pasaport taşımak yalnızca","İki ülkenin vatandaşı olmak","İki dil bilmek","İki evi olmak"]'::jsonb, 1, 'genel_kultur'),
('İltica hakkı neyi ifade eder?', '["Turist vizesi","Öğrenci izni","Zulümden kaçana sığınma hakkı","Çalışma izni"]'::jsonb, 2, 'genel_kultur'),
('Sivil itaatsizlik kavramı neyi anlatır?', '["Silahlı direniş","Oy kullanmama","Vergi kaçırma","Haksız yasaya şiddetsiz karşı çıkma"]'::jsonb, 3, 'genel_kultur'),
('Kamuoyu kavramı neyi ifade eder?', '["Toplumun ortak eğilimini","Meclis kararını","Mahkeme hükmünü","Bakanlık genelgesini"]'::jsonb, 0, 'genel_kultur'),
('Basın özgürlüğünün demokrasideki rolü nedir?', '["Reklam geliri sağlamak","Denetim ve bilgilenmeyi sağlamak","Eğlence üretmek","Vergi toplamak"]'::jsonb, 1, 'genel_kultur'),
('Bilgi edinme hakkı neyi sağlar?', '["Özel yazışmaları okumayı","Sınav sorusu almayı","Kamu bilgilerine erişebilmeyi","Ticari sır öğrenmeyi"]'::jsonb, 2, 'genel_kultur'),
('Kişisel verilerin korunması neyi amaçlar?', '["Veriyi çoğaltmak","Reklamı artırmak","Kaydı silmemek","Bireyin mahremiyetini güvenceye almak"]'::jsonb, 3, 'genel_kultur'),
('Tüketici hakları kapsamında ''ayıplı mal'' ne demektir?', '["Sözleşmeye uygun olmayan ürün","Pahalı ürün","İthal ürün","İkinci el ürün"]'::jsonb, 0, 'genel_kultur'),
('Garanti belgesi neyi güvence altına alır?', '["Fiyat indirimini","Belirli süre onarım ve değişim hakkını","Kargo ücretini","Vergi iadesini"]'::jsonb, 1, 'genel_kultur'),
('Sigortanın temel işlevi nedir?', '["Kâr garantisi vermek","Vergi indirmek","Riski paylaşarak zararı karşılamak","Kredi vermek"]'::jsonb, 2, 'genel_kultur')
on conflict (soru) do nothing;
