-- Soru havuzu genişletme: sinema +15, teknoloji +20, muzik +15, spor +15, edebiyat +20, tarih +14, bilim +13
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Sinemada ''kurgu ekolü'' olarak Sovyet montajı neyi vurgular?', '["Çarpıştırmayla anlam üretmeyi","Kesintisiz plan","Doğal ses","Uzun diyalog"]'::jsonb, 0, 'sinema'),
('Bir filmde ''ritmik kurgu'' neye göre yapılır?', '["Renk sırasına","Planların süresine ve tempoya","Oyuncu boyuna","Bütçeye"]'::jsonb, 1, 'sinema'),
('Sinemada ''sürekli kurgu'' neyi hedefler?', '["Kesmelerin belirginleşmesini","Sesin kesilmesini","Kesmelerin fark edilmemesini","Rengin bozulmasını"]'::jsonb, 2, 'sinema'),
('Sinemada ''180 derece kuralı'' neyi korur?', '["Ses düzeyini","Renk dengesini","Süreyi","Mekânsal yön tutarlılığını"]'::jsonb, 3, 'sinema'),
('Bir sahnede ''göz hattı eşlemesi'' neyi sağlar?', '["Bakışların tutarlı görünmesini","Işığın eşitlenmesini","Sesin dengelenmesini","Rengin uyumunu"]'::jsonb, 0, 'sinema'),
('Sinemada ''kesme'' en temel geçiş türü olarak ne yapar?', '["Yavaşça karartır","Bir planı diğerine anında bağlar","Üst üste bindirir","Donuk kare koyar"]'::jsonb, 1, 'sinema'),
('Sinemada ''anlatı ekonomisi'' ne demektir?', '["Bütçeyi kısmak","Kadroyu küçültmek","Gereksiz sahnelerden kaçınmak","Süreyi uzatmak"]'::jsonb, 2, 'sinema'),
('Bir filmin ''ikinci perde'' bölümünde ne olur?', '["Karakter tanıtılır","Sorun çözülür","Jenerik akar","Çatışma derinleşir"]'::jsonb, 3, 'sinema'),
('Sinemada ''karakter motivasyonu'' neyi açıklar?', '["Eylemlerinin nedenini","Kostümünü","Adını","Yaşını"]'::jsonb, 0, 'sinema'),
('Sinemada ''gerilim'' ile ''sürpriz'' arasındaki fark nedir?', '["Sürprizde izleyicinin bilmesi","Gerilimde izleyicinin önceden bilmesi","İkisinin aynı olması","Gerilimde ses olmaması"]'::jsonb, 1, 'sinema'),
('Sinemada ''tempo'' neyle düşürülür?', '["Hızlı kesmelerle","Yüksek sesle","Uzun planlar ve durağan sahnelerle","Parlak renkle"]'::jsonb, 2, 'sinema'),
('Bir belgeselde ''arşiv görüntüsü'' neyi sağlar?', '["Kurgu hızını","Renk dengesini","Ses efektini","Geçmişe dair kanıt ve bağlam"]'::jsonb, 3, 'sinema'),
('Sinemada ''canlandırma'' (reenactment) belgeselde ne yapar?', '["Yaşanmış olayı yeniden sahneler","Kurgu hikâye anlatır","Arşiv gösterir","Röportaj yapar"]'::jsonb, 0, 'sinema'),
('Bir filmin ''yapım tasarımı'' neyi kapsar?', '["Kurgu ritmini","Mekân, dekor ve genel görsel dünyayı","Ses miksini","Dağıtımı"]'::jsonb, 1, 'sinema'),
('Sinemada ''atmosfer sesi'' (ambiyans) ne sağlar?', '["Diyalog netliğini","Müzik uyumunu","Mekân duygusunu","Renk dengesini"]'::jsonb, 2, 'sinema'),
('Bilişimde ''protokol'' ne demektir?', '["İletişim kuralları bütünü","Donanım parçası","Yazılım türü","Dosya biçimi"]'::jsonb, 0, 'teknoloji'),
('OSI modeli kaç katmandan oluşur?', '["Dört","Yedi","Beş","On"]'::jsonb, 1, 'teknoloji'),
('OSI modelinde en üst katman hangisidir?', '["Fiziksel katman","Ağ katmanı","Uygulama katmanı","Taşıma katmanı"]'::jsonb, 2, 'teknoloji'),
('Fiziksel katman neyle ilgilenir?', '["Uygulama arayüzüyle","Şifrelemeyle","Sorgulamayla","Kablo ve sinyal iletimiyle"]'::jsonb, 3, 'teknoloji'),
('Anahtar (switch) ile hub arasındaki fark nedir?', '["Anahtarın hedefe yönlendirmesi","Hub''ın yönlendirmesi","İkisinin aynı olması","Anahtarın yayın yapması"]'::jsonb, 0, 'teknoloji'),
('Ağ maskesi (subnet mask) ne belirler?', '["Şifreyi","Ağ ve host bölümünü","Hızı","Kablo türünü"]'::jsonb, 1, 'teknoloji'),
('Ping komutu ne ölçer?', '["Disk hızını","Ekran çözünürlüğünü","Erişilebilirlik ve gecikmeyi","Bellek miktarını"]'::jsonb, 2, 'teknoloji'),
('Traceroute komutu neyi gösterir?', '["Dosya boyutunu","Şifre gücünü","Ekran rengini","Paketin izlediği yolu"]'::jsonb, 3, 'teknoloji'),
('Bulutta ''yatay ölçekleme'' ne demektir?', '["Sunucu sayısını artırmak","Tek sunucuyu güçlendirmek","Veriyi silmek","Ağı kapatmak"]'::jsonb, 0, 'teknoloji'),
('Dikey ölçekleme neyi ifade eder?', '["Sunucu sayısını artırmak","Var olan sunucunun kaynağını artırmak","Ağ genişletmek","Yedek almak"]'::jsonb, 1, 'teknoloji'),
('Yüksek erişilebilirlik (HA) mimarisi neyi hedefler?', '["Düşük maliyeti","Yüksek hızı yalnızca","Kesintisiz hizmeti","Küçük veriyi"]'::jsonb, 2, 'teknoloji'),
('Mikro hizmetlerde ''API ağ geçidi'' ne yapar?', '["Veri saklar","Kod derler","Test yazar","İstekleri tek noktadan yönlendirir"]'::jsonb, 3, 'teknoloji'),
('Mesaj kuyruğu sistemleri ne sağlar?', '["Servisler arası asenkron iletişim","Senkron zorunluluk","Veri silme","Ekran açma"]'::jsonb, 0, 'teknoloji'),
('Önbellek sunucusunun (Redis gibi) amacı nedir?', '["Kalıcı arşiv","Sık erişilen veriyi hızlı sunmak","Kod derleme","Ağ kurma"]'::jsonb, 1, 'teknoloji'),
('CDN''in görüntü yüklemeye etkisi nedir?', '["Boyutu artırması","Rengi değiştirmesi","Gecikmeyi azaltması","Formatı bozması"]'::jsonb, 2, 'teknoloji'),
('Web''de ''lazy loading'' ne sağlar?', '["Hepsini önden yüklemeyi","Veriyi silmeyi","Şifrelemeyi","İçeriği gerektiğinde yüklemeyi"]'::jsonb, 3, 'teknoloji'),
('Progresif web uygulaması (PWA) ne sunar?', '["Uygulama benzeri web deneyimi","Yalnız masaüstü program","Yalnız mobil uygulama","Yalnız oyun"]'::jsonb, 0, 'teknoloji'),
('Service worker teknolojisi neyi mümkün kılar?', '["Veri tabanı kurma","Çevrim dışı çalışma ve önbellek","Sunucu kiralama","Kod derleme"]'::jsonb, 1, 'teknoloji'),
('Web''de ''responsive breakpoint'' ne belirler?', '["Renk paletini","Yazı tipini","Düzenin değişeceği ekran genişliğini","Sunucu hızını"]'::jsonb, 2, 'teknoloji'),
('Tasarımda ''mobil öncelikli'' yaklaşım ne demektir?', '["Önce masaüstüne göre","Yalnız tablet","Yalnız TV","Önce küçük ekrana göre tasarlamak"]'::jsonb, 3, 'teknoloji'),
('Bir korodaki dört temel parti hangileridir?', '["Soprano, alto, tenor, bas","Solo, koro, çalgı, şef","Ritim, ezgi, armoni, form","Do, re, mi, fa"]'::jsonb, 0, 'muzik'),
('Bir eserde ''akapella koro'' hangi eşlikle söylenir?', '["Piyano eşlikli","Eşliksiz","Orkestra eşlikli","Davul eşlikli"]'::jsonb, 1, 'muzik'),
('Müzikte ''aralık'' ne demektir?', '["İki ölçü arası","İki eser arası","İki ses arasındaki uzaklık","İki bölüm arası"]'::jsonb, 2, 'muzik'),
('Oktav aralığında iki ses nasıl algılanır?', '["Farklı iki ad","Uyumsuz","Sessiz","Aynı ses adının kalın ve incesi"]'::jsonb, 3, 'muzik'),
('Konsonans terimi neyi ifade eder?', '["Kulağa uyumlu gelen birliktelik","Gerilimli birliktelik","Sessizlik","Tempo"]'::jsonb, 0, 'muzik'),
('Disonans terimi neyi ifade eder?', '["Uyumlu birliktelik","Gerilim yaratan birliktelik","Sessizlik","Ritim"]'::jsonb, 1, 'muzik'),
('Bir eserde ''çözülme'' (rezolüsyon) ne anlama gelir?', '["Tempo artışı","Ton değişimi","Gerilimin uyuma dönmesi","Nüans artışı"]'::jsonb, 2, 'muzik'),
('Müzikte ''motif gelişimi'' nasıl yapılır?', '["Motifin silinmesiyle","Tempo sabitlemeyle","Nüans azaltmayla","Motifin değiştirilerek yinelenmesiyle"]'::jsonb, 3, 'muzik'),
('Halk müziğinde ''yöre'' bilgisi neden önemlidir?', '["Ezgi ve icra üslubunu belirlemesi","Nota sayısını","Tempoyu yalnızca","Çalgı fiyatını"]'::jsonb, 0, 'muzik'),
('Türkü derlemelerinde kaynak kişi kimdir?', '["Besteci","Ezgiyi aktaran yerel icracı","Şef","Yayıncı"]'::jsonb, 1, 'muzik'),
('Bir çalgının ''ses genişliği'' neyi ifade eder?', '["Gövde boyutunu","Tel sayısını","Çalabildiği en pes ve en tiz aralık","Ağırlığını"]'::jsonb, 2, 'muzik'),
('Transpoze çalgı ne demektir?', '["Yazıldığı gibi ses veren","Sessiz çalgı","Vurmalı çalgı","Yazıldığından farklı ses veren çalgı"]'::jsonb, 3, 'muzik'),
('Klarnet hangi çalgı grubuna örnektir?', '["Transpoze tahta üflemeli","Yaylı","Tuşlu","Vurmalı"]'::jsonb, 0, 'muzik'),
('Bir orkestrada çalgı yerleşimi neye göre yapılır?', '["Alfabetik sıraya göre","Ses dengesi ve tınıya göre","Yaşa göre","Boya göre"]'::jsonb, 1, 'muzik'),
('Konser salonlarında akustik tasarımın amacı nedir?', '["Işığı artırmak","Koltuk artırmak","Sesin dengeli yayılmasını sağlamak","Isıyı ayarlamak"]'::jsonb, 2, 'muzik'),
('Sporda ''esneklik'' hangi bileşene girer?', '["Motorik özelliklere","Zihinsel özelliklere","Beslenmeye","Ekipmana"]'::jsonb, 0, 'spor'),
('Sürat, kuvvet ve dayanıklılık neyi oluşturur?', '["Taktik bilgiyi","Temel motorik özellikleri","Kural bilgisini","Ekipmanı"]'::jsonb, 1, 'spor'),
('Koordinasyon becerisi neyi ifade eder?', '["Güç üretmeyi","Uzun koşmayı","Hareketleri uyumlu yapabilmeyi","Esnemeyi"]'::jsonb, 2, 'spor'),
('Denge becerisinin en belirgin olduğu spor hangisidir?', '["Halter","Yüzme","Bisiklet","Cimnastik"]'::jsonb, 3, 'spor'),
('Reaksiyon zamanı neyi ölçer?', '["Uyarana tepki süresini","Kas gücünü","Esnekliği","Dayanıklılığı"]'::jsonb, 0, 'spor'),
('Sporda ''çeviklik'' ne demektir?', '["Uzun süre koşma","Hızla yön değiştirebilme","Ağırlık kaldırma","Esneme"]'::jsonb, 1, 'spor'),
('Kuvvet antrenmanında ''maksimal kuvvet'' neyi ifade eder?', '["Uzun süre kaldırma","Hızlı kaldırma","Tek tekrarda kaldırılan en yüksek yük","Hafif yük"]'::jsonb, 2, 'spor'),
('Patlayıcı kuvvet hangi sporlarda kritiktir?', '["Maratonda","Satrançta","Okçulukta","Sıçrama ve atmalarda"]'::jsonb, 3, 'spor'),
('Sporda ''dayanıklılık'' türlerinden biri hangisidir?', '["Aerobik dayanıklılık","Statik kuvvet","Patlayıcı güç","Esneklik"]'::jsonb, 0, 'spor'),
('Isınmada ''genel ısınma'' bölümünde ne yapılır?', '["Maksimal yük","Hafif tempolu koşu ve hareket","Yarış temposu","Tam dinlenme"]'::jsonb, 1, 'spor'),
('Antrenmanda ''aşırı yüklenme ilkesi'' neyi anlatır?', '["Yükün sabit kalması","Yükün azalması","Gelişim için yükün kademeli artması","Hiç yüklenmemesi"]'::jsonb, 2, 'spor'),
('Antrenmanda ''özgüllük ilkesi'' ne demektir?', '["Genel olması","Rastgele olması","Kısa olması","Antrenmanın branşa özel olması"]'::jsonb, 3, 'spor'),
('Antrenmanda ''geri dönüşümlülük'' neyi ifade eder?', '["Ara verilince kazanımın kaybolması","Kazanımın kalıcılığı","Sakatlığın geçmesi","Yükün artması"]'::jsonb, 0, 'spor'),
('Sporcularda ''dinlenme nabzı'' neyi gösterir?', '["Kas kütlesini","Kardiyovasküler uygunluğu","Esnekliği","Boyu"]'::jsonb, 1, 'spor'),
('Antrenman günlüğü tutmanın yararı nedir?', '["Ceza kaydı","Kadro seçimi","Gelişimi izleyip planı ayarlamak","Bilet satışı"]'::jsonb, 2, 'spor'),
('Bir romanda ''mekân'' öğesinin işlevi nedir?', '["Olayı ve karakteri anlamlandırmak","Sayfa doldurmak","Başlık vermek","Kaynak göstermek"]'::jsonb, 0, 'edebiyat'),
('Anlatıda ''zaman'' öğesi neyi belirler?', '["Yazarın yaşını","Olayların akış düzenini","Baskı sayısını","Yayın yerini"]'::jsonb, 1, 'edebiyat'),
('Bir metinde ''üslup'' neyi yansıtır?', '["Baskı tekniğini","Kapak tasarımını","Yazarın dil ve anlatım özelliğini","Fiyatı"]'::jsonb, 2, 'edebiyat'),
('Yalın anlatımın özelliği nedir?', '["Ağdalı olması","Uzun cümleli olması","İmgeli olması","Süssüz ve açık olması"]'::jsonb, 3, 'edebiyat'),
('Şiirde ''ahenk'' neyle sağlanır?', '["Ölçü, kafiye ve ses yinelemeleriyle","Sayfa sayısıyla","Başlıkla","Yazı tipiyle"]'::jsonb, 0, 'edebiyat'),
('Halk hikâyesi ile destan arasındaki fark nedir?', '["Destanın kısa olması","Halk hikâyesinin daha gerçekçi olması","İkisinin aynı olması","Hikâyenin şiir olması"]'::jsonb, 1, 'edebiyat'),
('Türk edebiyatında ''tekke edebiyatı'' hangi çevrede gelişmiştir?', '["Saray çevresinde","Ordu çevresinde","Tasavvuf çevresinde","Ticaret çevresinde"]'::jsonb, 2, 'edebiyat'),
('Yunus Emre şiirinde hangi dil anlayışı öne çıkar?', '["Ağır Arapça","Ağır Farsça","Fransızca","Sade Türkçe"]'::jsonb, 3, 'edebiyat'),
('Pir Sultan Abdal hangi gelenekte anılır?', '["Alevi-Bektaşi halk şiiri","Divan şiiri","Servet-i Fünun","İkinci Yeni"]'::jsonb, 0, 'edebiyat'),
('Karacaoğlan şiirinde ağırlıklı tema nedir?', '["Savaş","Doğa ve aşk","Bilim","Siyaset"]'::jsonb, 1, 'edebiyat'),
('Köroğlu şiirinde öne çıkan tema nedir?', '["Aşk yalnızca","Doğa yalnızca","Yiğitlik ve başkaldırı","Din"]'::jsonb, 2, 'edebiyat'),
('Divan şiirinde ''mazmun'' ne demektir?', '["Ölçü türü","Kafiye şeması","Nazım biçimi","Kalıplaşmış imge ve anlam"]'::jsonb, 3, 'edebiyat'),
('Divan şiirinde ''sevgili'' tasviri nasıldır?', '["Kalıplaşmış ve idealize","Gerçekçi ve bireysel","Belgesel","Doğaçlama"]'::jsonb, 0, 'edebiyat'),
('Şeyh Galip hangi eseriyle tanınır?', '["Leyla ile Mecnun","Hüsn ü Aşk","Hayriyye","Garipname"]'::jsonb, 1, 'edebiyat'),
('Fuzuli''nin ünlü mesnevisi hangisidir?', '["Hüsn ü Aşk","Şehnâme","Leyla ile Mecnun","Mesnevî"]'::jsonb, 2, 'edebiyat'),
('Baki hangi türde ustalığıyla anılır?', '["Roman","Öykü","Tiyatro","Gazel"]'::jsonb, 3, 'edebiyat'),
('Nedim hangi dönemin şairidir?', '["Lale Devri","Tanzimat","Cumhuriyet","Kuruluş"]'::jsonb, 0, 'edebiyat'),
('Nef''i hangi türle anılır?', '["Roman","Kaside ve hiciv","Deneme","Anı"]'::jsonb, 1, 'edebiyat'),
('Evliya Çelebi''nin eseri hangi türdedir?', '["Roman","Şiir","Gezi yazısı","Tiyatro"]'::jsonb, 2, 'edebiyat'),
('Katip Çelebi''nin bibliyografya eseri hangisidir?', '["Seyahatname","Mukaddime","Divan","Keşfü''z-Zünun"]'::jsonb, 3, 'edebiyat'),
('Dandanakan Savaşı hangi devletin kuruluşunu sağlamıştır?', '["Büyük Selçuklu","Osmanlı","Gazneli","Karahanlı"]'::jsonb, 0, 'tarih'),
('Karahanlılar hangi alanda öne çıkmıştır?', '["Deniz ticareti","Türkçenin edebi dil olarak kullanımı","Piramit yapımı","Matbaa"]'::jsonb, 1, 'tarih'),
('Gazneliler''in en ünlü hükümdarı kimdir?', '["Tuğrul Bey","Alparslan","Gazneli Mahmud","Melikşah"]'::jsonb, 2, 'tarih'),
('Anadolu''da ilk Türk beyliklerinin kurulmasını sağlayan zafer hangisidir?', '["Miryokefalon","Kösedağ","Ankara","Malazgirt"]'::jsonb, 3, 'tarih'),
('Miryokefalon Savaşı''nın sonucu nedir?', '["Anadolu''nun Türk yurdu olması","Anadolu''nun kaybı","Bizans''ın güçlenmesi","Haçlı zaferi"]'::jsonb, 0, 'tarih'),
('Kösedağ Savaşı hangi devletin çöküşünü hızlandırmıştır?', '["Osmanlı","Anadolu Selçuklu","Bizans","Memlük"]'::jsonb, 1, 'tarih'),
('Osmanlı''da ''istimalet'' politikası neyi amaçlıyordu?', '["Vergi artırmayı","Göç ettirmeyi","Yerel halkı hoşnut edip kazanmayı","Ordu kurmayı"]'::jsonb, 2, 'tarih'),
('Osmanlı''da ''iskân'' politikası neyi sağlıyordu?', '["Vergi affını","Askerlik muafiyetini","Ticaret yasağını","Fethedilen yerlere nüfus yerleştirmeyi"]'::jsonb, 3, 'tarih'),
('Osmanlı''da ''devşirme'' uygulaması kimlerden asker toplardı?', '["Hristiyan tebaanın çocuklarından","Müslüman tebaadan","Yabancı paralı askerlerden","Göçebe aşiretlerden"]'::jsonb, 0, 'tarih'),
('Osmanlı donanmasının Akdeniz''de güçlenmesi hangi dönemde olmuştur?', '["Kuruluş dönemi","Kanuni dönemi","Tanzimat dönemi","Meşrutiyet dönemi"]'::jsonb, 1, 'tarih'),
('Osmanlı''da ilk denizaşırı sefer hangi bölgeye yapılmıştır?', '["Atlas Okyanusu","Baltık","Hint Okyanusu","Karayipler"]'::jsonb, 2, 'tarih'),
('Piri Reis''in dünya haritası hangi yüzyılda çizilmiştir?', '["On dördüncü yüzyıl","On sekizinci yüzyıl","On dokuzuncu yüzyıl","On altıncı yüzyıl"]'::jsonb, 3, 'tarih'),
('Osmanlı''da ilk resmî askerî mühendislik okulu hangi alanda kurulmuştur?', '["Topçuluk ve istihkâm","Tıp","Hukuk","Ziraat"]'::jsonb, 0, 'tarih'),
('Osmanlı''da Mekteb-i Tıbbiye ne amaçla kurulmuştur?', '["Mühendis yetiştirmek","Hekim yetiştirmek","Öğretmen yetiştirmek","Subay yetiştirmek"]'::jsonb, 1, 'tarih'),
('Hipotezin özelliği nedir?', '["Sınanabilir olması","Kanıtlanmış olması","Değişmez olması","Yorum olması"]'::jsonb, 0, 'bilim'),
('Kontrol grubunun deneydeki işlevi nedir?', '["Sonucu değiştirmek","Karşılaştırma sağlamak","Süreyi kısaltmak","Maliyeti düşürmek"]'::jsonb, 1, 'bilim'),
('Bağımsız değişken nedir?', '["Ölçülen sonuç","Sabit tutulan koşul","Araştırmacının değiştirdiği etken","Hata payı"]'::jsonb, 2, 'bilim'),
('Bağımlı değişken neyi ifade eder?', '["Değiştirilen etkeni","Sabit koşulu","Deney süresini","Ölçülen sonucu"]'::jsonb, 3, 'bilim'),
('Deneyin tekrarlanabilir olması neden önemlidir?', '["Sonucun güvenilirliğini göstermesi","Maliyeti düşürmesi","Süreyi kısaltması","Yayını kolaylaştırması"]'::jsonb, 0, 'bilim'),
('Bilimsel kuram ile hipotez arasındaki fark nedir?', '["Hipotezin kesin olması","Kuramın çok kanıtla desteklenmesi","İkisinin aynı olması","Kuramın tahmin olması"]'::jsonb, 1, 'bilim'),
('Bilimsel yasa neyi ifade eder?', '["Açıklamayı","Tahmini","Değişmez ilişkiyi tanımlayan ifadeyi","Görüşü"]'::jsonb, 2, 'bilim'),
('Hakem denetimli (peer review) yayın ne sağlar?', '["Hızlı yayını","Ücretsizliği","Popülerliği","Bilimsel niteliğin denetlenmesini"]'::jsonb, 3, 'bilim'),
('Bilimde ''yanlışlanabilirlik'' ölçütü kime aittir?', '["Karl Popper","Thomas Kuhn","Francis Bacon","Auguste Comte"]'::jsonb, 0, 'bilim'),
('Paradigma kavramını bilim felsefesine kazandıran kimdir?', '["Karl Popper","Thomas Kuhn","Descartes","Newton"]'::jsonb, 1, 'bilim'),
('Ölçümde ''hassasiyet'' neyi ifade eder?', '["Gerçek değere yakınlığı","Ölçüm süresini","Tekrarlı ölçümlerin yakınlığını","Alet fiyatını"]'::jsonb, 2, 'bilim'),
('Ölçümde ''doğruluk'' neyi ifade eder?', '["Tekrarların yakınlığını","Ölçüm sayısını","Alet markasını","Gerçek değere yakınlığı"]'::jsonb, 3, 'bilim'),
('Uluslararası birim sisteminde kütle birimi nedir?', '["Kilogram","Newton","Joule","Pascal"]'::jsonb, 0, 'bilim')
on conflict (soru) do nothing;
