-- Soru havuzu genişletme — Parti 1: Tarih + Coğrafya
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('İstanbul''un fethi hangi yılda gerçekleşmiştir?', '["1453","1071","1517","1389"]'::jsonb, 0, 'tarih'),
('Malazgirt Savaşı hangi yılda yapılmıştır?', '["1071","1453","1176","923"]'::jsonb, 0, 'tarih'),
('Osmanlı Devleti''nin kurucusu kimdir?', '["Osman Bey","Orhan Bey","Ertuğrul Gazi","Alparslan"]'::jsonb, 0, 'tarih'),
('Türkiye Cumhuriyeti hangi tarihte ilan edilmiştir?', '["29 Ekim 1923","23 Nisan 1920","30 Ağustos 1922","19 Mayıs 1919"]'::jsonb, 0, 'tarih'),
('Kurtuluş Savaşı''nı başlatan olay sayılan Samsun''a çıkış hangi tarihtedir?', '["19 Mayıs 1919","23 Nisan 1920","29 Ekim 1923","30 Ağustos 1922"]'::jsonb, 0, 'tarih'),
('TBMM hangi tarihte açılmıştır?', '["23 Nisan 1920","29 Ekim 1923","19 Mayıs 1919","1 Kasım 1922"]'::jsonb, 0, 'tarih'),
('Fransız İhtilali hangi yılda başlamıştır?', '["1789","1776","1804","1750"]'::jsonb, 0, 'tarih'),
('II. Dünya Savaşı hangi yıllar arasında yaşanmıştır?', '["1939-1945","1914-1918","1936-1942","1941-1947"]'::jsonb, 0, 'tarih'),
('I. Dünya Savaşı hangi yılda başlamıştır?', '["1914","1918","1912","1920"]'::jsonb, 0, 'tarih'),
('Amerika kıtasına 1492''de ulaşan denizci kimdir?', '["Kristof Kolomb","Vasco da Gama","Macellan","Amerigo Vespucci"]'::jsonb, 0, 'tarih'),
('Mısır piramitlerinin en büyüğü hangisidir?', '["Keops","Kefren","Mikerinos","Sakkara"]'::jsonb, 0, 'tarih'),
('Roma İmparatorluğu''nun ilk imparatoru kimdir?', '["Augustus","Jül Sezar","Neron","Konstantin"]'::jsonb, 0, 'tarih'),
('Kanuni Sultan Süleyman hangi yüzyılda yaşamıştır?', '["16. yüzyıl","15. yüzyıl","17. yüzyıl","14. yüzyıl"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ilk anayasa olan Kanun-i Esasi hangi yılda ilan edilmiştir?', '["1876","1839","1908","1856"]'::jsonb, 0, 'tarih'),
('Tanzimat Fermanı hangi padişah döneminde ilan edilmiştir?', '["Abdülmecid","II. Mahmud","Abdülaziz","II. Abdülhamid"]'::jsonb, 0, 'tarih'),
('İlk Türk devletlerinden Göktürkler''in alfabesi hangisidir?', '["Orhun Alfabesi","Uygur Alfabesi","Arap Alfabesi","Latin Alfabesi"]'::jsonb, 0, 'tarih'),
('Orhun Yazıtları hangi devlete aittir?', '["II. Göktürk Kağanlığı","Uygurlar","Hunlar","Selçuklular"]'::jsonb, 0, 'tarih'),
('Anadolu Selçuklu Devleti''nin başkenti hangi şehirdi?', '["Konya","Bursa","İznik","Sivas"]'::jsonb, 0, 'tarih'),
('Osmanlı Devleti''nin ilk başkenti hangi şehirdir?', '["Söğüt","İstanbul","Bursa","Edirne"]'::jsonb, 0, 'tarih'),
('İstanbul''dan önce Osmanlı''nın başkenti hangi şehirdi?', '["Edirne","Bursa","Konya","Söğüt"]'::jsonb, 0, 'tarih'),
('Preveze Deniz Savaşı''nı kazanan Osmanlı amirali kimdir?', '["Barbaros Hayreddin Paşa","Turgut Reis","Piri Reis","Kılıç Ali Paşa"]'::jsonb, 0, 'tarih'),
('Dünya haritasıyla ünlü Osmanlı denizcisi kimdir?', '["Piri Reis","Barbaros Hayreddin","Turgut Reis","Seydi Ali Reis"]'::jsonb, 0, 'tarih'),
('Atatürk''ün doğum yılı kaçtır?', '["1881","1880","1885","1878"]'::jsonb, 0, 'tarih'),
('Atatürk hangi şehirde doğmuştur?', '["Selanik","İstanbul","Ankara","İzmir"]'::jsonb, 0, 'tarih'),
('Atatürk hangi tarihte vefat etmiştir?', '["10 Kasım 1938","10 Kasım 1937","29 Ekim 1938","19 Mayıs 1938"]'::jsonb, 0, 'tarih'),
('Soyadı Kanunu hangi yılda kabul edilmiştir?', '["1934","1928","1923","1937"]'::jsonb, 0, 'tarih'),
('Harf İnkılabı hangi yılda yapılmıştır?', '["1928","1923","1934","1931"]'::jsonb, 0, 'tarih'),
('Türkiye''de kadınlara milletvekili seçme ve seçilme hakkı hangi yılda verilmiştir?', '["1934","1923","1930","1945"]'::jsonb, 0, 'tarih'),
('Lozan Antlaşması hangi yılda imzalanmıştır?', '["1923","1920","1922","1925"]'::jsonb, 0, 'tarih'),
('Sevr Antlaşması hangi yılda imzalanmıştır?', '["1920","1918","1923","1919"]'::jsonb, 0, 'tarih'),
('Çanakkale Deniz Zaferi hangi tarihte kazanılmıştır?', '["18 Mart 1915","19 Mayıs 1915","18 Mart 1916","30 Ağustos 1915"]'::jsonb, 0, 'tarih'),
('Büyük Taarruz hangi tarihte başlamıştır?', '["26 Ağustos 1922","30 Ağustos 1922","9 Eylül 1922","23 Nisan 1922"]'::jsonb, 0, 'tarih'),
('İzmir''in kurtuluşu hangi tarihtedir?', '["9 Eylül 1922","30 Ağustos 1922","29 Ekim 1922","26 Ağustos 1922"]'::jsonb, 0, 'tarih'),
('Berlin Duvarı hangi yılda yıkılmıştır?', '["1989","1991","1985","1979"]'::jsonb, 0, 'tarih'),
('Sovyetler Birliği hangi yılda dağılmıştır?', '["1991","1989","1993","1985"]'::jsonb, 0, 'tarih'),
('Magna Carta hangi ülkede imzalanmıştır?', '["İngiltere","Fransa","Almanya","İtalya"]'::jsonb, 0, 'tarih'),
('Napolyon Bonapart hangi ülkenin imparatoruydu?', '["Fransa","İtalya","İspanya","Avusturya"]'::jsonb, 0, 'tarih'),
('Napolyon''un son yenilgisini aldığı savaş hangisidir?', '["Waterloo","Austerlitz","Borodino","Leipzig"]'::jsonb, 0, 'tarih'),
('Cengiz Han hangi imparatorluğun kurucusudur?', '["Moğol İmparatorluğu","Timur İmparatorluğu","Babür İmparatorluğu","Hun İmparatorluğu"]'::jsonb, 0, 'tarih'),
('İpek Yolu hangi iki kıtayı birbirine bağlardı?', '["Asya ve Avrupa","Asya ve Afrika","Avrupa ve Afrika","Asya ve Amerika"]'::jsonb, 0, 'tarih'),
('Matbaayı Avrupa''da geliştirerek yaygınlaştıran kişi kimdir?', '["Gutenberg","Da Vinci","Newton","Kopernik"]'::jsonb, 0, 'tarih'),
('Osmanlı Devleti I. Dünya Savaşı''nda hangi blokta yer almıştır?', '["İttifak Devletleri","İtilaf Devletleri","Tarafsız kaldı","Müttefik Devletler"]'::jsonb, 0, 'tarih'),
('Yavuz Sultan Selim hangi seferle halifeliği Osmanlı''ya getirmiştir?', '["Mısır Seferi","İran Seferi","Balkan Seferi","Viyana Seferi"]'::jsonb, 0, 'tarih'),
('Fatih Sultan Mehmet İstanbul''u fethettiğinde kaç yaşındaydı?', '["21","18","25","30"]'::jsonb, 0, 'tarih'),
('Antik Yunan''da demokrasi hangi şehir devletinde doğmuştur?', '["Atina","Sparta","Korint","Teb"]'::jsonb, 0, 'tarih'),
('Truva antik kenti bugün hangi ilimizin sınırları içindedir?', '["Çanakkale","İzmir","Balıkesir","Muğla"]'::jsonb, 0, 'tarih'),
('Efes antik kenti hangi ilimizdedir?', '["İzmir","Aydın","Muğla","Denizli"]'::jsonb, 0, 'tarih'),
('Göbeklitepe hangi ilimizde bulunur?', '["Şanlıurfa","Mardin","Diyarbakır","Gaziantep"]'::jsonb, 0, 'tarih'),
('Dünyanın bilinen en eski tapınak kompleksi hangisidir?', '["Göbeklitepe","Stonehenge","Karnak Tapınağı","Parthenon"]'::jsonb, 0, 'tarih'),
('Hititler''in başkenti hangisidir?', '["Hattuşa","Truva","Gordion","Sardes"]'::jsonb, 0, 'tarih'),
('Lidyalılar tarihte ilk kez neyi kullanmıştır?', '["Parayı","Yazıyı","Tekerleği","Pusulayı"]'::jsonb, 0, 'tarih'),
('Yazıyı tarihte ilk kullanan uygarlık hangisidir?', '["Sümerler","Mısırlılar","Hititler","Fenikeliler"]'::jsonb, 0, 'tarih'),
('Hammurabi Kanunları hangi uygarlığa aittir?', '["Babil","Sümer","Asur","Mısır"]'::jsonb, 0, 'tarih'),
('ABD''nin bağımsızlık bildirgesi hangi yılda yayımlanmıştır?', '["1776","1789","1750","1801"]'::jsonb, 0, 'tarih'),
('Amerikan İç Savaşı''nda kuzeyin lideri olan başkan kimdir?', '["Abraham Lincoln","George Washington","Thomas Jefferson","Theodore Roosevelt"]'::jsonb, 0, 'tarih'),
('Hindistan''ın bağımsızlık hareketinin sembol ismi kimdir?', '["Mahatma Gandhi","Nehru","Cinnah","Tagore"]'::jsonb, 0, 'tarih'),
('Güney Afrika''da ırk ayrımcılığına karşı mücadelesiyle tanınan lider kimdir?', '["Nelson Mandela","Desmond Tutu","Kwame Nkrumah","Haile Selassie"]'::jsonb, 0, 'tarih'),
('Aya ayak basan ilk insan kimdir?', '["Neil Armstrong","Buzz Aldrin","Yuri Gagarin","John Glenn"]'::jsonb, 0, 'tarih'),
('Uzaya çıkan ilk insan kimdir?', '["Yuri Gagarin","Neil Armstrong","Alan Shepard","Buzz Aldrin"]'::jsonb, 0, 'tarih'),
('Ay''a ilk insanlı iniş hangi yılda yapılmıştır?', '["1969","1965","1972","1959"]'::jsonb, 0, 'tarih'),
('Titanic gemisi hangi yılda batmıştır?', '["1912","1905","1918","1923"]'::jsonb, 0, 'tarih'),
('Çernobil nükleer kazası hangi yılda yaşanmıştır?', '["1986","1979","1991","1981"]'::jsonb, 0, 'tarih'),
('Osmanlı''nın Avrupa''daki ilerleyişini durduran II. Viyana Kuşatması hangi yıldadır?', '["1683","1529","1717","1645"]'::jsonb, 0, 'tarih'),
('Mimar Sinan hangi padişahların döneminde baş mimarlık yapmıştır?', '["Kanuni, II. Selim ve III. Murad","Fatih ve II. Bayezid","Yavuz ve Kanuni","IV. Murad ve İbrahim"]'::jsonb, 0, 'tarih'),
('Süleymaniye Camii''nin mimarı kimdir?', '["Mimar Sinan","Mimar Hayreddin","Sedefkar Mehmed Ağa","Davud Ağa"]'::jsonb, 0, 'tarih'),
('Sultanahmet Camii''nin mimarı kimdir?', '["Sedefkar Mehmed Ağa","Mimar Sinan","Mimar Kemaleddin","Davud Ağa"]'::jsonb, 0, 'tarih'),
('Mimar Sinan''ın "ustalık eserim" dediği cami hangisidir?', '["Selimiye Camii","Süleymaniye Camii","Şehzade Camii","Mihrimah Sultan Camii"]'::jsonb, 0, 'tarih'),
('Selimiye Camii hangi şehirdedir?', '["Edirne","İstanbul","Bursa","Konya"]'::jsonb, 0, 'tarih'),
('Birleşmiş Milletler hangi yılda kurulmuştur?', '["1945","1919","1950","1939"]'::jsonb, 0, 'tarih'),
('NATO hangi yılda kurulmuştur?', '["1949","1945","1952","1955"]'::jsonb, 0, 'tarih'),
('Türkiye NATO''ya hangi yılda üye olmuştur?', '["1952","1949","1960","1945"]'::jsonb, 0, 'tarih'),
('Vikingler hangi bölgeden gelmiştir?', '["İskandinavya","Britanya","Sibirya","Orta Asya"]'::jsonb, 0, 'tarih'),
('İnka İmparatorluğu hangi kıtada hüküm sürmüştür?', '["Güney Amerika","Kuzey Amerika","Afrika","Asya"]'::jsonb, 0, 'tarih'),
('Maçu Piçu hangi uygarlığın eseridir?', '["İnka","Aztek","Maya","Olmek"]'::jsonb, 0, 'tarih'),
('Aztek İmparatorluğu bugünkü hangi ülkenin topraklarındaydı?', '["Meksika","Peru","Brezilya","Arjantin"]'::jsonb, 0, 'tarih'),
('Türkiye''nin başkenti hangi şehirdir?', '["Ankara","İstanbul","İzmir","Bursa"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en kalabalık şehri hangisidir?', '["İstanbul","Ankara","İzmir","Bursa"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en yüksek dağı hangisidir?', '["Ağrı Dağı","Erciyes","Kaçkar","Süphan"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en uzun nehri hangisidir?', '["Kızılırmak","Fırat","Sakarya","Yeşilırmak"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en büyük gölü hangisidir?', '["Van Gölü","Tuz Gölü","Beyşehir Gölü","Eğirdir Gölü"]'::jsonb, 0, 'cografya'),
('Türkiye kaç coğrafi bölgeye ayrılır?', '["7","5","6","8"]'::jsonb, 0, 'cografya'),
('Türkiye''nin yüzölçümü en büyük ili hangisidir?', '["Konya","Ankara","Sivas","Erzurum"]'::jsonb, 0, 'cografya'),
('Dünyanın en büyük okyanusu hangisidir?', '["Büyük Okyanus","Atlas Okyanusu","Hint Okyanusu","Arktik Okyanusu"]'::jsonb, 0, 'cografya'),
('Dünyanın en uzun nehri hangisi kabul edilir?', '["Nil","Amazon","Mississippi","Yangtze"]'::jsonb, 0, 'cografya'),
('Dünyanın en yüksek dağı hangisidir?', '["Everest","K2","Kangchenjunga","Ağrı Dağı"]'::jsonb, 0, 'cografya'),
('Dünyanın en büyük çölü hangisidir?', '["Sahra","Gobi","Kalahari","Atacama"]'::jsonb, 0, 'cografya'),
('Dünyanın en kalabalık ülkesi hangisidir?', '["Hindistan","Çin","ABD","Endonezya"]'::jsonb, 0, 'cografya'),
('Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?', '["Rusya","Kanada","Çin","ABD"]'::jsonb, 0, 'cografya'),
('Dünyanın en küçük ülkesi hangisidir?', '["Vatikan","Monako","San Marino","Lihtenştayn"]'::jsonb, 0, 'cografya'),
('Japonya''nın başkenti hangisidir?', '["Tokyo","Kyoto","Osaka","Hiroşima"]'::jsonb, 0, 'cografya'),
('Avustralya''nın başkenti hangisidir?', '["Kanberra","Sidney","Melbourne","Brisbane"]'::jsonb, 0, 'cografya'),
('Kanada''nın başkenti hangisidir?', '["Ottava","Toronto","Vancouver","Montreal"]'::jsonb, 0, 'cografya'),
('ABD''nin başkenti hangisidir?', '["Washington D.C.","New York","Los Angeles","Chicago"]'::jsonb, 0, 'cografya'),
('Brezilya''nın başkenti hangisidir?', '["Brasilia","Rio de Janeiro","Sao Paulo","Salvador"]'::jsonb, 0, 'cografya'),
('Mısır''ın başkenti hangisidir?', '["Kahire","İskenderiye","Luksor","Asvan"]'::jsonb, 0, 'cografya'),
('Almanya''nın başkenti hangisidir?', '["Berlin","Münih","Frankfurt","Hamburg"]'::jsonb, 0, 'cografya'),
('İtalya''nın başkenti hangisidir?', '["Roma","Milano","Venedik","Napoli"]'::jsonb, 0, 'cografya'),
('İspanya''nın başkenti hangisidir?', '["Madrid","Barselona","Sevilla","Valensiya"]'::jsonb, 0, 'cografya'),
('Yunanistan''ın başkenti hangisidir?', '["Atina","Selanik","Patra","Girit"]'::jsonb, 0, 'cografya'),
('Rusya''nın başkenti hangisidir?', '["Moskova","St. Petersburg","Kazan","Novosibirsk"]'::jsonb, 0, 'cografya'),
('Çin''in başkenti hangisidir?', '["Pekin","Şanghay","Hong Kong","Guangzhou"]'::jsonb, 0, 'cografya'),
('Hindistan''ın başkenti hangisidir?', '["Yeni Delhi","Mumbai","Kalküta","Bangalore"]'::jsonb, 0, 'cografya'),
('Hollanda''nın başkenti hangisidir?', '["Amsterdam","Rotterdam","Lahey","Utrecht"]'::jsonb, 0, 'cografya'),
('İsviçre''nin başkenti hangisidir?', '["Bern","Zürih","Cenevre","Basel"]'::jsonb, 0, 'cografya'),
('Norveç''in başkenti hangisidir?', '["Oslo","Bergen","Stockholm","Helsinki"]'::jsonb, 0, 'cografya'),
('Azerbaycan''ın başkenti hangisidir?', '["Bakü","Gence","Sumgayıt","Nahçıvan"]'::jsonb, 0, 'cografya'),
('İran''ın başkenti hangisidir?', '["Tahran","İsfahan","Tebriz","Şiraz"]'::jsonb, 0, 'cografya'),
('Suriye''nin başkenti hangisidir?', '["Şam","Halep","Humus","Lazkiye"]'::jsonb, 0, 'cografya'),
('Irak''ın başkenti hangisidir?', '["Bağdat","Basra","Musul","Erbil"]'::jsonb, 0, 'cografya'),
('Türkiye''nin kaç ili vardır?', '["81","80","82","78"]'::jsonb, 0, 'cografya'),
('İstanbul Boğazı hangi iki denizi birbirine bağlar?', '["Karadeniz ve Marmara","Marmara ve Ege","Ege ve Akdeniz","Karadeniz ve Ege"]'::jsonb, 0, 'cografya'),
('Çanakkale Boğazı hangi iki denizi birbirine bağlar?', '["Marmara ve Ege","Karadeniz ve Marmara","Ege ve Akdeniz","Karadeniz ve Ege"]'::jsonb, 0, 'cografya'),
('Asya ile Afrika''yı ayıran kanal hangisidir?', '["Süveyş Kanalı","Panama Kanalı","Korint Kanalı","Kiel Kanalı"]'::jsonb, 0, 'cografya'),
('Panama Kanalı hangi iki okyanusu birbirine bağlar?', '["Atlas ve Büyük Okyanus","Atlas ve Hint","Büyük ve Hint","Atlas ve Arktik"]'::jsonb, 0, 'cografya'),
('Ekvator çizgisi dünyayı hangi iki yarım küreye ayırır?', '["Kuzey ve Güney","Doğu ve Batı","İç ve Dış","Üst ve Alt"]'::jsonb, 0, 'cografya'),
('Dünyanın en derin okyanus çukuru hangisidir?', '["Mariana Çukuru","Tonga Çukuru","Java Çukuru","Porto Riko Çukuru"]'::jsonb, 0, 'cografya'),
('Sahra Çölü hangi kıtadadır?', '["Afrika","Asya","Avustralya","Güney Amerika"]'::jsonb, 0, 'cografya'),
('Amazon Ormanları en çok hangi ülkededir?', '["Brezilya","Peru","Kolombiya","Venezuela"]'::jsonb, 0, 'cografya'),
('Dünyanın en büyük adası hangisidir?', '["Grönland","Avustralya","Borneo","Madagaskar"]'::jsonb, 0, 'cografya'),
('Kıbrıs adası hangi denizdedir?', '["Akdeniz","Ege","Karadeniz","Kızıldeniz"]'::jsonb, 0, 'cografya'),
('Dünya üzerindeki kıta sayısı kaçtır?', '["7","5","6","8"]'::jsonb, 0, 'cografya'),
('Hem Avrupa hem Asya kıtasında toprağı bulunan şehir hangisidir?', '["İstanbul","Atina","Moskova","Kahire"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en doğusundaki il hangisidir?', '["Iğdır","Van","Kars","Hakkari"]'::jsonb, 0, 'cografya'),
('Türkiye hangi yarım kürededir?', '["Kuzey Yarım Küre","Güney Yarım Küre","Her ikisi","Ekvator üzerinde"]'::jsonb, 0, 'cografya'),
('Kapadokya bölgesi hangi ilimizde yer alır?', '["Nevşehir","Konya","Kayseri","Niğde"]'::jsonb, 0, 'cografya'),
('Pamukkale travertenleri hangi ilimizdedir?', '["Denizli","Aydın","Muğla","Burdur"]'::jsonb, 0, 'cografya'),
('Nemrut Dağı''ndaki dev heykeller hangi ilimizdedir?', '["Adıyaman","Malatya","Şanlıurfa","Diyarbakır"]'::jsonb, 0, 'cografya'),
('Sümela Manastırı hangi ilimizdedir?', '["Trabzon","Rize","Artvin","Giresun"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en büyük yüzölçümlü bölgesi hangisidir?', '["Doğu Anadolu","İç Anadolu","Karadeniz","Akdeniz"]'::jsonb, 0, 'cografya'),
('Fırat ve Dicle nehirleri hangi denize/körfeze dökülür?', '["Basra Körfezi","Akdeniz","Hazar Denizi","Kızıldeniz"]'::jsonb, 0, 'cografya'),
('Hazar Denizi aslında ne tür bir su kütlesidir?', '["Göl","Deniz","Okyanus","Nehir"]'::jsonb, 0, 'cografya'),
('Everest Dağı hangi sıradağlar üzerindedir?', '["Himalayalar","Andlar","Alpler","Kafkaslar"]'::jsonb, 0, 'cografya'),
('And Dağları hangi kıtadadır?', '["Güney Amerika","Kuzey Amerika","Asya","Afrika"]'::jsonb, 0, 'cografya'),
('Nil Nehri hangi denize dökülür?', '["Akdeniz","Kızıldeniz","Hint Okyanusu","Atlas Okyanusu"]'::jsonb, 0, 'cografya'),
('Venedik şehri hangi ülkededir?', '["İtalya","Fransa","İspanya","Yunanistan"]'::jsonb, 0, 'cografya'),
('Eyfel Kulesi hangi şehirdedir?', '["Paris","Londra","Roma","Berlin"]'::jsonb, 0, 'cografya'),
('Big Ben hangi şehirdedir?', '["Londra","Paris","New York","Dublin"]'::jsonb, 0, 'cografya'),
('Özgürlük Heykeli hangi şehirdedir?', '["New York","Washington","Los Angeles","Boston"]'::jsonb, 0, 'cografya'),
('Tac Mahal hangi ülkededir?', '["Hindistan","Pakistan","İran","Bangladeş"]'::jsonb, 0, 'cografya'),
('Çin Seddi''nin yapılma amacı neydi?', '["Savunma","Ticaret","Sulama","Ulaşım"]'::jsonb, 0, 'cografya'),
('Kuzey Işıkları (Aurora) en iyi nereden gözlemlenir?', '["Kutup bölgeleri","Ekvator","Çöller","Tropikal adalar"]'::jsonb, 0, 'cografya'),
('Türkiye''ye komşu olmayan ülke hangisidir?', '["Ukrayna","Bulgaristan","İran","Gürcistan"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en kuzey ucu hangi ildedir?', '["Sinop","Samsun","Kastamonu","Zonguldak"]'::jsonb, 0, 'cografya'),
('Tuz Gölü hangi bölgemizdedir?', '["İç Anadolu","Akdeniz","Ege","Doğu Anadolu"]'::jsonb, 0, 'cografya'),
('Uludağ hangi ilimizdedir?', '["Bursa","Bolu","Kütahya","Bilecik"]'::jsonb, 0, 'cografya'),
('Erciyes Dağı hangi ilimizdedir?', '["Kayseri","Nevşehir","Sivas","Niğde"]'::jsonb, 0, 'cografya'),
('Ölüdeniz hangi ilimizdedir?', '["Muğla","Antalya","İzmir","Aydın"]'::jsonb, 0, 'cografya'),
('Dünyaca ünlü Kapalıçarşı hangi şehirdedir?', '["İstanbul","Bursa","İzmir","Ankara"]'::jsonb, 0, 'cografya'),
('Afrika''nın en yüksek dağı hangisidir?', '["Kilimanjaro","Kenya Dağı","Atlas Dağı","Tubkal"]'::jsonb, 0, 'cografya'),
('Sidney Opera Binası hangi ülkededir?', '["Avustralya","Yeni Zelanda","İngiltere","Kanada"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
