-- Soru havuzu genişletme: teknoloji +25, sinema +18, muzik +19, spor +19, sanat +15, genel_kultur +15
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Bilgisayar biliminde ''soyutlama'' ne sağlar?', '["Ayrıntıyı gizleyip özü öne çıkarmayı","Kodu uzatmayı","Hız artışını","Bellek artışını"]'::jsonb, 0, 'teknoloji'),
('Sözde kod (pseudocode) ne için kullanılır?', '["Programı çalıştırmak","Algoritmayı dilden bağımsız anlatmak","Veri saklamak","Ağ kurmak"]'::jsonb, 1, 'teknoloji'),
('Akış şeması neyi gösterir?', '["Veri tabanı şemasını","Ağ topolojisini","İşlem adımlarının sırasını","Dosya boyutunu"]'::jsonb, 2, 'teknoloji'),
('Değişken ''kapsamı'' (scope) neyi belirler?', '["Değişkenin boyutunu","Değişkenin adını","Değişkenin hızını","Değişkenin erişilebildiği alanı"]'::jsonb, 3, 'teknoloji'),
('Global değişkenin riski nedir?', '["Her yerden değiştirilebilmesi","Hiç kullanılamaması","Yavaş olması","Bellek almaması"]'::jsonb, 0, 'teknoloji'),
('Hata yakalama (try-catch) yapısı ne sağlar?', '["Hız artışını","Hata durumunda programın çökmemesini","Bellek artışını","Kod kısalmasını"]'::jsonb, 1, 'teknoloji'),
('Yazılımda ''girdi doğrulama'' neden yapılır?', '["Hız artırmak","Renk vermek","Hatalı ve kötü niyetli veriyi engellemek","Boyut küçültmek"]'::jsonb, 2, 'teknoloji'),
('SQL enjeksiyonu saldırısı neyi hedefler?', '["Ekranı kapatmayı","Kabloyu kesmeyi","Yazıcıyı bozmayı","Sorguyu değiştirip veriye erişmeyi"]'::jsonb, 3, 'teknoloji'),
('XSS saldırısı hangi ortamda gerçekleşir?', '["Sayfada zararlı betik çalıştırarak","Yazıcıda","Modemde","Bellekte"]'::jsonb, 0, 'teknoloji'),
('Sunucu günlüklerinin (log) güvenlikteki değeri nedir?', '["Hız artırmak","Olayları geriye dönük izlemek","Şifre üretmek","Veri silmek"]'::jsonb, 1, 'teknoloji'),
('Yedeklemenin şifrelenmesi neden önemlidir?', '["Yedeği hızlandırmak","Boyut küçültmek","Yedek çalınırsa veriyi korumak","Renk vermek"]'::jsonb, 2, 'teknoloji'),
('Sürüm kontrolünde ''merge'' işlemi ne yapar?', '["Dal siler","Dosya siler","Sunucu kurar","Farklı dalları birleştirir"]'::jsonb, 3, 'teknoloji'),
('Sürüm kontrolünde ''conflict'' ne zaman oluşur?', '["Aynı satır iki dalda değiştiğinde","Dosya silindiğinde","Sunucu kapandığında","Test başarısızsa"]'::jsonb, 0, 'teknoloji'),
('Belgeleme (documentation) yazılımda ne sağlar?', '["Hız artışını","Kodun anlaşılır ve sürdürülebilirliği","Bellek artışını","Renk düzenini"]'::jsonb, 1, 'teknoloji'),
('Yazılım testinde ''regresyon testi'' neyi denetler?', '["Yeni tasarımı","Sunucu hızını","Eski özelliklerin bozulmadığını","Ağ genişliğini"]'::jsonb, 2, 'teknoloji'),
('Yük testi neyi ölçer?', '["Renk doğruluğunu","Metin uzunluğunu","Dosya adını","Sistemin yoğun kullanımdaki davranışını"]'::jsonb, 3, 'teknoloji'),
('Sızma testi (pentest) ne amaçlar?', '["Güvenlik açıklarını izinli olarak bulmak","Veri silmek","Sunucu satmak","Kod yazmak"]'::jsonb, 0, 'teknoloji'),
('Yazılımda ''sanal ortam'' ne sağlar?', '["Donanım hızlandırma","Projeye özel bağımlılık yalıtımı","Ağ kurma","Ekran açma"]'::jsonb, 1, 'teknoloji'),
('Paket yöneticisinin işlevi nedir?', '["Kod yazmak","Test yazmak","Kütüphaneleri kurup güncellemek","Tasarım yapmak"]'::jsonb, 2, 'teknoloji'),
('Derleme ile yorumlama arasındaki performans farkı nedir?', '["Yorumlananın hep hızlı olması","Farkın olmaması","Derlemenin hep yavaş olması","Derlenmiş kodun daha hızlı çalışması"]'::jsonb, 3, 'teknoloji'),
('Bellek sızıntısı (memory leak) nedir?', '["Kullanılmayan belleğin bırakılmaması","Belleğin dolması gerektiği","Diskin bozulması","Ağın kopması"]'::jsonb, 0, 'teknoloji'),
('Çöp toplayıcı (garbage collector) ne yapar?', '["Dosya siler","Kullanılmayan belleği otomatik boşaltır","Ağ temizler","Ekran kapatır"]'::jsonb, 1, 'teknoloji'),
('Eşzamanlılık (concurrency) neyi ifade eder?', '["Tek iş yapmayı","Sıralı bekleme","Birden çok işin iç içe yürütülmesini","Kod silme"]'::jsonb, 2, 'teknoloji'),
('Kilitlenme (deadlock) ne zaman oluşur?', '["Bellek dolduğunda","Disk bittiğinde","Ağ koptuğunda","İki süreç birbirinin kaynağını beklerken"]'::jsonb, 3, 'teknoloji'),
('Önbellek tutarsızlığı neden sorun yaratır?', '["Eski verinin gösterilmesine yol açar","Hızı artırır","Bellek açar","Ağı hızlandırır"]'::jsonb, 0, 'teknoloji'),
('Sinemada ''ışıkla yazma'' anlamına gelen kökensel terim hangisidir?', '["Fotografi","Sinematografi dışı hiçbiri","Sekans","Montaj"]'::jsonb, 0, 'sinema'),
('Sessiz filmlerde anlatımı destekleyen yazılı kartlara ne denir?', '["Altyazı","Ara yazı","Jenerik","Afiş"]'::jsonb, 1, 'sinema'),
('Altyazı ile dublaj arasındaki temel fark nedir?', '["Dublajın yazılı olması","İkisinin aynı olması","Altyazının özgün sesi koruması","Altyazının sesli olması"]'::jsonb, 2, 'sinema'),
('Sinemada ''kurgu masası'' yerini neye bırakmıştır?', '["Kameraya","Projeksiyona","Perdeye","Dijital kurgu yazılımlarına"]'::jsonb, 3, 'sinema'),
('Sinemada ''negatif film'' neyi ifade eder?', '["Çekimde kullanılan ham malzemeyi","Gösterim kopyasını","Fragmanı","Afişi"]'::jsonb, 0, 'sinema'),
('Dijital sinemada ''DCP'' ne işe yarar?', '["Fragman formatı","Filmin salon gösterim paketi olması","Afiş dosyası","Ses efekti"]'::jsonb, 1, 'sinema'),
('Bir filmde ''kadro dışı ses'' hangi terimle anılır?', '["Diegetik ses","Foley","Off ses","Skor"]'::jsonb, 2, 'sinema'),
('Sinemada ''senaryo doktoru'' ne yapar?', '["Yeni senaryo yazar","Kurgu yapar","Oyuncu seçer","Var olan senaryoyu iyileştirir"]'::jsonb, 3, 'sinema'),
('Bir yapımda ''yönetmen yardımcısı'' neyi koordine eder?', '["Çekim planını ve seti","Bütçeyi","Dağıtımı","Afişi"]'::jsonb, 0, 'sinema'),
('Sinemada ''script supervisor'' neyi izler?', '["Bütçeyi","Süreklilik ve devamlılığı","Bilet satışını","Işığı"]'::jsonb, 1, 'sinema'),
('Devamlılık hatası ne demektir?', '["Ses kaybı","Renk hatası","Sahneler arası tutarsızlık","Odak kayması"]'::jsonb, 2, 'sinema'),
('Sinemada ''stüdyo sistemi'' hangi dönemi tanımlar?', '["Yeni dalgayı","Dogma 95''i","Yeni gerçekçiliği","Hollywood''un klasik dönemini"]'::jsonb, 3, 'sinema'),
('Yıldız sistemi (star system) neyi ifade eder?', '["Oyuncu ününün pazarlama aracı olmasını","Yönetmen ününü","Bütçe düzenini","Kurgu tekniğini"]'::jsonb, 0, 'sinema'),
('Sinemada ''tip oyunculuk'' ne demektir?', '["Her rolü oynamak","Belirli bir rol kalıbında oynamak","Sessiz oynamak","Dublörlük"]'::jsonb, 1, 'sinema'),
('Sinemada ''method acting'' neyi savunur?', '["Dış teknikle oynamayı","Doğaçlamayı","Oyuncunun rolü derinden yaşamasını","Sessiz oyunu"]'::jsonb, 2, 'sinema'),
('Bir filmin ''ana teması'' neyi ifade eder?', '["Müziğini","Afişini","Süresini","Anlatının temel izleğini"]'::jsonb, 3, 'sinema'),
('Bir filmde ''açık son'' ne demektir?', '["Sonucun yoruma bırakılması","Sonucun net verilmesi","Filmin kısa olması","Devam filmi olması"]'::jsonb, 0, 'sinema'),
('Sinema ile edebiyat ilişkisinde ''uyarlama sadakati'' tartışması nedir?', '["Bütçe miktarı","Kaynağa ne kadar bağlı kalınacağı","Oyuncu seçimi","Salon sayısı"]'::jsonb, 1, 'sinema'),
('Notada ''anahtar'' işaretinin işlevi nedir?', '["Seslerin portedeki yerini belirlemek","Tempoyu vermek","Nüansı vermek","Ölçüyü vermek"]'::jsonb, 0, 'muzik'),
('Do anahtarı hangi çalgılarda yaygın kullanılır?', '["Piccolo","Viyola gibi orta sesli çalgılarda","Kontrbas","Trompet"]'::jsonb, 1, 'muzik'),
('Bir eserde ''tekrar işareti'' ne sağlar?', '["Eserin bitmesini","Tempo değişimini","Belirli bölümün yeniden çalınmasını","Ton değişimini"]'::jsonb, 2, 'muzik'),
('Müzikte ''ostinato'' nedir?', '["Tek seferlik motif","Serbest doğaçlama","Sessizlik","Israrla yinelenen kalıp"]'::jsonb, 3, 'muzik'),
('Glissando tekniği ne yapar?', '["Sesler arasında kaydırarak geçmek","Kesik çalmak","Vurgulu çalmak","Sessiz çalmak"]'::jsonb, 0, 'muzik'),
('Vibrato tekniği neyi sağlar?', '["Sesin kesilmesi","Sesin hafifçe titreşerek zenginleşmesi","Tempo artışı","Ton değişimi"]'::jsonb, 1, 'muzik'),
('Pizzicato tekniği yaylı çalgılarda ne yapar?', '["Yayla sürtülmesi","Vurulması","Telin parmakla çekilmesi","Üflenmesi"]'::jsonb, 2, 'muzik'),
('Tremolo tekniği neyi ifade eder?', '["Sesin uzatılması","Sesin susturulması","Sesin kalınlaşması","Sesin hızlı yinelenmesi"]'::jsonb, 3, 'muzik'),
('Müzikte ''kontrast'' neyle sağlanır?', '["Hız, gürlük ve doku değişimiyle","Yalnız nota sayısıyla","Yalnız süre ile","Yalnız çalgı sayısıyla"]'::jsonb, 0, 'muzik'),
('Bir eserin ''formu'' neyi belirler?', '["Ses şiddetini","Bölümlerin düzenini","Tonunu","Çalgı markasını"]'::jsonb, 1, 'muzik'),
('Tema ve çeşitlemeler formu neyi işler?', '["Farklı temaları","Tek akoru","Bir temanın değiştirilerek tekrarını","Sessizliği"]'::jsonb, 2, 'muzik'),
('Müzikte ''atonal'' ne demektir?', '["Ritim olmaması","Söz olmaması","Çalgı olmaması","Belirli bir ton merkezi olmaması"]'::jsonb, 3, 'muzik'),
('On iki ton tekniğini geliştiren besteci kimdir?', '["Arnold Schönberg","Igor Stravinski","Claude Debussy","Maurice Ravel"]'::jsonb, 0, 'muzik'),
('Minimal müzik akımının özelliği nedir?', '["Karmaşık armoni","Kısa kalıpların yinelenmesi","Uzun formlar","Doğaçlama zorunluluğu"]'::jsonb, 1, 'muzik'),
('Elektronik müzikte ''sequencer'' ne yapar?', '["Ses üretmez","Nota basar","Sesleri zaman çizgisinde düzenler","Konser verir"]'::jsonb, 2, 'muzik'),
('Türk müziğinde ''perde'' terimi neyi ifade eder?', '["Sahne perdesini","Nüansı","Usulü","Belirli bir ses yüksekliğini"]'::jsonb, 3, 'muzik'),
('Türk müziğinde ''dizi'' ne anlama gelir?', '["Makamı oluşturan ses sırası","Ritim kalıbı","Çalgı topluluğu","Eser formu"]'::jsonb, 0, 'muzik'),
('Türk müziğinde ''karar sesi'' neyi belirtir?', '["En tiz sesi","Makamın son bulduğu sesi","En pes sesi","Başlangıç temposunu"]'::jsonb, 1, 'muzik'),
('Türk müziğinde ''güçlü'' perdesi ne işlev görür?', '["Bitiş sesi","En tiz ses","Seyirde ikinci önemli durak","Usul adı"]'::jsonb, 2, 'muzik'),
('Futbolda 4-4-2 gibi ifadeler neyi anlatır?', '["Takım dizilişini","Maç süresini","Skoru","Oyuncu numarasını"]'::jsonb, 0, 'spor'),
('Futbolda ''pres'' taktiği neyi hedefler?', '["Geri çekilmeyi","Rakibi kendi sahasında baskılamak","Topu bekletmeyi","Süre öldürmeyi"]'::jsonb, 1, 'spor'),
('Futbolda ''kontra atak'' ne demektir?', '["Savunmaya çekilmek","Oyunu durdurmak","Topu kapıp hızla hücuma çıkmak","Uzun pas yapmamak"]'::jsonb, 2, 'spor'),
('Basketbolda ''pick and roll'' nedir?', '["Blok yapmak","Ribaund almak","Faul yapmak","Perde kurup içeri dalma hareketi"]'::jsonb, 3, 'spor'),
('Basketbolda ''zone savunma'' ne demektir?', '["Bölge esaslı savunma","Adam adama savunma","Pres yapmamak","Faul yapmak"]'::jsonb, 0, 'spor'),
('Voleybolda ''pasör'' hangi görevi üstlenir?', '["Savunma uzmanı","Hücumu kuran oyuncu","Blok uzmanı","Servis uzmanı"]'::jsonb, 1, 'spor'),
('Voleybolda ''rotasyon'' ne demektir?', '["Oyuncu değişikliği","Mola","Oyuncuların saat yönünde kayması","Set arası"]'::jsonb, 2, 'spor'),
('Tenis maçında ''break'' ne anlama gelir?', '["Mola vermek","Set kazanmak","Faul yapmak","Rakibin servisini kırmak"]'::jsonb, 3, 'spor'),
('Tenis maçında ''tie-break'' ne zaman oynanır?', '["Sette skor eşitlendiğinde","Maç başında","Her oyunda","Mola sonrası"]'::jsonb, 0, 'spor'),
('Yüzmede ''dönüş'' tekniğinin önemi nedir?', '["Nefes vermesi","Süre kazandırması","Stil değiştirmesi","Kural gereği"]'::jsonb, 1, 'spor'),
('Atletizmde ''çıkış takozu'' ne için kullanılır?', '["Uzun mesafe için","Atlama için","Sürat koşusunda güçlü başlangıç","Atma için"]'::jsonb, 2, 'spor'),
('Maratonda ''duvara toslamak'' ne anlama gelir?', '["Rakibe çarpmak","Yolu şaşırmak","Diskalifiye olmak","Enerji depolarının tükenmesi"]'::jsonb, 3, 'spor'),
('Dayanıklılık sporlarında karbonhidrat yüklemesi neden yapılır?', '["Glikojen depolarını artırmak için","Kilo almak için","Su tutmak için","Kas yıkmak için"]'::jsonb, 0, 'spor'),
('Yüksek irtifa kampının amacı nedir?', '["Kilo vermek","Oksijen taşıma kapasitesini artırmak","Esneklik kazanmak","Teknik öğrenmek"]'::jsonb, 1, 'spor'),
('Sporda ''periyodik test'' neden yapılır?', '["Ceza vermek","Kadro açıklamak","Gelişimi ölçüp planı güncellemek","Bilet satmak"]'::jsonb, 2, 'spor'),
('Takım sporlarında ''kaptan bandı'' neyi simgeler?', '["En iyi oyuncuyu","En yaşlı oyuncuyu","Kaleciyi","Saha içi liderliği"]'::jsonb, 3, 'spor'),
('Sporda ''seyirci şiddeti'' ile mücadelede temel yöntem nedir?', '["Güvenlik ve yaptırım düzenlemeleri","Maçı iptal etmek","Bileti ucuzlatmak","Süreyi kısaltmak"]'::jsonb, 0, 'spor'),
('Sporun toplumsal işlevlerinden biri nedir?', '["Ayrışma","Kaynaşma ve sağlıklı yaşam","Rekabetin yasaklanması","Göç"]'::jsonb, 1, 'spor'),
('Okul sporlarının amacı nedir?', '["Yalnız şampiyon çıkarmak","Ders saatini azaltmak","Katılım ve gelişimi desteklemek","Sınav yapmak"]'::jsonb, 2, 'spor'),
('Bir müzenin ''geçici sergi'' düzenlemesinin amacı nedir?', '["Belirli bir temayı süreli sunmak","Koleksiyonu satmak","Bilet artırmak yalnızca","Depoyu boşaltmak"]'::jsonb, 0, 'sanat'),
('Sanat eserinde ''imza'' neyi belirtir?', '["Fiyatını","Yaratıcısını","Boyutunu","Tarihini yalnızca"]'::jsonb, 1, 'sanat'),
('Bir eserin ''edisyon'' numarası neyi gösterir?', '["Fiyatını","Boyutunu","Baskı adedindeki sırasını","Rengini"]'::jsonb, 2, 'sanat'),
('Sanatta ''atölye'' geleneği neyi ifade eder?', '["Tek başına üretmeyi","Fabrika üretimini","Dijital üretimi","Usta yanında öğrenerek üretmeyi"]'::jsonb, 3, 'sanat'),
('Bir sanat eserinin ''ikonografisi'' neyi inceler?', '["İmge ve simgelerin anlamını","Malzeme türünü","Fiyatını","Boyutunu"]'::jsonb, 0, 'sanat'),
('Sanat tarihinde ''üslup'' kavramı neyi anlatır?', '["Eserin fiyatını","Ortak biçim dilini","Sanatçının yaşını","Müze adını"]'::jsonb, 1, 'sanat'),
('Portre resmin amacı nedir?', '["Manzara vermek","Nesne göstermek","Kişiyi betimlemek","Soyut biçim kurmak"]'::jsonb, 2, 'sanat'),
('Natürmort ne anlama gelir?', '["Manzara resmi","Portre","Savaş resmi","Cansız nesnelerin resmi"]'::jsonb, 3, 'sanat'),
('Manzara resminin İngilizce karşılığı hangi kavramla anılır?', '["Landscape","Portrait","Still life","Sketch"]'::jsonb, 0, 'sanat'),
('Otoportre nedir?', '["Başkasının portresi","Sanatçının kendi portresi","Grup resmi","Manzara"]'::jsonb, 1, 'sanat'),
('Sanat eserinde ''kompozisyon çizgisi'' neyi yönlendirir?', '["Rengin tonunu","Malzemeyi","İzleyicinin bakışını","Boyutu"]'::jsonb, 2, 'sanat'),
('Rölyefte ''yüksek kabartma'' ne demektir?', '["Çok az çıkıntı","Oyuk biçim","Düz yüzey","Yüzeyden belirgin çıkıntı"]'::jsonb, 3, 'sanat'),
('Heykelde ''kaide'' ne işe yarar?', '["Eseri taşıyıp sunmak","Renk vermek","Işık vermek","Ses vermek"]'::jsonb, 0, 'sanat'),
('Sanatta ''monokrom'' ne anlama gelir?', '["Çok renk kullanımı","Tek renk kullanımı","Renksizlik","Işıksızlık"]'::jsonb, 1, 'sanat'),
('Sanatta ''doku'' (tekstür) neyi ifade eder?', '["Rengin adını","Boyutu","Yüzeyin dokunsal niteliğini","Ağırlığı"]'::jsonb, 2, 'sanat'),
('Bir kütüphanede sınıflandırma sistemi ne sağlar?', '["Kaynağa düzenli erişimi","Kitap basımını","Ödünç ücretini","Kitap yazımını"]'::jsonb, 0, 'genel_kultur'),
('ISBN numarası neyi tanımlar?', '["Yazarı","Bir kitabı benzersiz olarak","Yayınevini yalnızca","Baskı sayısını"]'::jsonb, 1, 'genel_kultur'),
('Ansiklopedik bilgi ile uzman bilgisi arasındaki fark nedir?', '["Ansiklopedinin daha derin olması","İkisinin aynı olması","Uzman bilginin derinliği","Uzmanın yüzeyselliği"]'::jsonb, 2, 'genel_kultur'),
('Kaynak güvenilirliğini değerlendirmede ilk ölçüt nedir?', '["Yazının uzunluğu","Yazı tipi","Renk düzeni","Yazar ve yayıncının yetkinliği"]'::jsonb, 3, 'genel_kultur'),
('Doğrulama (fact-checking) neyi amaçlar?', '["İddianın kanıtla sınanmasını","Haberi yaymayı","Yorum eklemeyi","Metni kısaltmayı"]'::jsonb, 0, 'genel_kultur'),
('Dezenformasyon ne anlama gelir?', '["Yanlışlıkla hata yapma","Kasıtlı yanlış bilgi yayma","Doğru bilgi verme","Bilgi saklama"]'::jsonb, 1, 'genel_kultur'),
('Yankı odası etkisi neyi anlatır?', '["Ses yankısını","Haber çeşitliliğini","Benzer görüşlerle çevrelenmeyi","Tarafsızlığı"]'::jsonb, 2, 'genel_kultur'),
('Medya okuryazarlığı neyi kazandırır?', '["Hızlı okumayı","Yazı yazmayı","Kamera kullanmayı","İçeriği eleştirel değerlendirmeyi"]'::jsonb, 3, 'genel_kultur'),
('Reklamda ''hedef kitle'' ne demektir?', '["Ulaşılmak istenen tüketici grubu","Reklam süresi","Yayın saati","Bütçe"]'::jsonb, 0, 'genel_kultur'),
('Marka bilinirliği neyi ölçer?', '["Ürün fiyatını","Tüketicinin markayı tanıma düzeyini","Üretim miktarını","Mağaza sayısını"]'::jsonb, 1, 'genel_kultur'),
('Kamu spotunun amacı nedir?', '["Ürün satmak","Şirket tanıtmak","Toplumsal fayda için bilgilendirmek","Bilet satmak"]'::jsonb, 2, 'genel_kultur'),
('Gönüllülük çalışmasının topluma katkısı nedir?', '["Vergi geliri","İhracat artışı","Nüfus artışı","Dayanışma ve hizmet üretimi"]'::jsonb, 3, 'genel_kultur'),
('Bağış ile sponsorluk arasındaki fark nedir?', '["Sponsorlukta tanıtım beklenmesi","Bağışta karşılık beklenmesi","İkisinin aynı olması","Sponsorlukta karşılık olmaması"]'::jsonb, 0, 'genel_kultur'),
('Kamu yararına dernek statüsü neyi sağlar?', '["Ticari tekel","Belirli hukuki ve mali kolaylıklar","Vergi muafiyeti mutlak","Kamu görevi"]'::jsonb, 1, 'genel_kultur'),
('Toplumsal cinsiyet eşitliği kavramı neyi hedefler?', '["Farkların yok sayılmasını","Tek cinsiyete öncelik","Fırsat ve haklara eşit erişimi","Yasal ayrım"]'::jsonb, 2, 'genel_kultur')
on conflict (soru) do nothing;
