-- Soru havuzu genişletme: teknoloji +48, sinema +32, muzik +40, spor +39
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('HTML dilinin işlevi nedir?', '["Sayfanın içerik yapısını tanımlamak","Sayfayı biçimlendirmek","Veri saklamak","Ağ kurmak"]'::jsonb, 0, 'teknoloji'),
('CSS ne için kullanılır?', '["Veri tabanı sorgusu","Sayfanın görsel biçimlendirmesi","Sunucu kurulumu","Ağ yönlendirme"]'::jsonb, 1, 'teknoloji'),
('JavaScript''in web sayfasındaki rolü nedir?', '["Yalnız stil vermek","Yalnız içerik yazmak","Etkileşim ve davranış eklemek","Sunucu kurmak"]'::jsonb, 2, 'teknoloji'),
('Bir web tarayıcısının temel işi nedir?', '["Dosya sıkıştırmak","Kod derlemek","Ağ kablosu kurmak","Web içeriğini yorumlayıp göstermek"]'::jsonb, 3, 'teknoloji'),
('Önbelleğe alma (caching) web''de ne sağlar?', '["Tekrar eden isteklerde hız","Güvenlik artışı","Veri şifreleme","Ağ genişliği artışı"]'::jsonb, 0, 'teknoloji'),
('CDN kısaltmasının işlevi nedir?', '["Veri şifrelemek","İçeriği yakın sunucudan dağıtmak","Kod derlemek","Dosya silmek"]'::jsonb, 1, 'teknoloji'),
('Duyarlı (responsive) tasarım neyi hedefler?', '["Yalnız masaüstü uyum","Renk azaltma","Farklı ekranlarda uyumlu görünüm","Ses eklemek"]'::jsonb, 2, 'teknoloji'),
('SEO çalışmasının amacı nedir?', '["Sayfayı şifrelemek","Sunucu kurmak","Veri silmek","Arama sonuçlarında görünürlüğü artırmak"]'::jsonb, 3, 'teknoloji'),
('Alan adı (domain) neyi ifade eder?', '["Sitenin insan okunur adresini","Sunucunun markasını","Sayfanın başlığını","Şifre anahtarını"]'::jsonb, 0, 'teknoloji'),
('Barındırma (hosting) hizmeti ne sağlar?', '["Alan adı satışı","Site dosyalarının sunucuda tutulması","Tasarım hizmeti","Reklam yayını"]'::jsonb, 1, 'teknoloji'),
('SSL sertifikası neyi sağlar?', '["Sayfa hızı","Renk düzeni","Şifreli bağlantı ve kimlik doğrulama","Veri yedeği"]'::jsonb, 2, 'teknoloji'),
('Sunucu ile istemci arasındaki fark nedir?', '["İkisinin aynı olması","İstemcinin hizmet vermesi","Sunucunun ekran olması","Sunucunun hizmet vermesi"]'::jsonb, 3, 'teknoloji'),
('Mikroservis mimarisinin özelliği nedir?', '["Bağımsız küçük servislere bölünme","Tek büyük yapı","Veritabanı olmaması","Arayüz olmaması"]'::jsonb, 0, 'teknoloji'),
('Sürekli entegrasyon (CI) ne sağlar?', '["Tasarım yapmayı","Değişikliklerin otomatik test edilmesi","Sunucu satın almayı","Kullanıcı eğitimini"]'::jsonb, 1, 'teknoloji'),
('Yazılım geliştirmede ''refactoring'' nedir?', '["Yeni özellik eklemek","Hata çıkarmak","Davranışı bozmadan kodu iyileştirmek","Sunucu değiştirmek"]'::jsonb, 2, 'teknoloji'),
('Çevik (agile) yaklaşımın temel ilkesi nedir?', '["Uzun tek teslim","Belge önceliği","Değişime kapalılık","Kısa döngülerle sürekli teslim"]'::jsonb, 3, 'teknoloji'),
('Scrum''da ''sprint'' ne anlama gelir?', '["Belirli süreli çalışma döngüsü","Günlük toplantı","Hata listesi","Test aracı"]'::jsonb, 0, 'teknoloji'),
('Kanban panosunun amacı nedir?', '["Kod derlemek","İş akışını görselleştirmek","Test yazmak","Sunucu kurmak"]'::jsonb, 1, 'teknoloji'),
('İşletim sisteminde ''süreç'' (process) nedir?', '["Disk dosyası","Ağ kablosu","Çalışmakta olan program örneği","Bellek çipi"]'::jsonb, 2, 'teknoloji'),
('Çoklu görev (multitasking) ne sağlar?', '["Tek iş yapılması","Belleğin silinmesi","Diskin bölünmesi","Birden çok işin sırayla yürütülmesi"]'::jsonb, 3, 'teknoloji'),
('Biçimlendirme (format) işlemi ne yapar?', '["Depolama alanını yeniden hazırlar","Dosya kopyalar","Ağ kurar","Bellek ekler"]'::jsonb, 0, 'teknoloji'),
('Bölümlendirme (partition) neyi ifade eder?', '["Diski silmeyi","Diski mantıksal parçalara ayırmayı","Dosya sıkıştırmayı","Yedek almayı"]'::jsonb, 1, 'teknoloji'),
('RAID teknolojisinin amacı nedir?', '["Ekran çözünürlüğü","Ağ hızı","Performans veya veri güvenliği artırmak","Ses kalitesi"]'::jsonb, 2, 'teknoloji'),
('Veri merkezi nedir?', '["Yazılım mağazası","Ağ kablosu","Ekran türü","Sunucuların toplu barındırıldığı tesis"]'::jsonb, 3, 'teknoloji'),
('Yedekli güç kaynağı (UPS) ne sağlar?', '["Elektrik kesintisinde kesintisiz çalışma","Veri şifreleme","Ağ hızlandırma","Soğutma"]'::jsonb, 0, 'teknoloji'),
('Dijital imza neyi doğrular?', '["Belgenin uzunluğunu","Belgenin kaynağını ve bütünlüğünü","Belgenin rengini","Belgenin tarihini yalnızca"]'::jsonb, 1, 'teknoloji'),
('Açık anahtar altyapısı (PKI) neye dayanır?', '["Tek parolaya","Fiziksel anahtara","Sertifika ve anahtar çiftlerine","Barkoda"]'::jsonb, 2, 'teknoloji'),
('Sıfır gün (zero-day) açığı ne demektir?', '["Eski bir açık","Kapatılmış açık","Donanım arızası","Henüz yaması olmayan güvenlik açığı"]'::jsonb, 3, 'teknoloji'),
('Sosyal mühendislik saldırısı neye dayanır?', '["İnsan davranışını manipüle etmeye","Şifre kırma yazılımına","Donanım sökmeye","Ağ kablosuna"]'::jsonb, 0, 'teknoloji'),
('Parola yöneticisi ne sağlar?', '["Ağ hızlandırmak","Parolaları şifreli saklayıp doldurmak","Virüs silmek","Dosya sıkıştırmak"]'::jsonb, 1, 'teknoloji'),
('Uçtan uca şifrelemede mesajı kim okuyabilir?', '["Sunucu da","Herkes","Yalnız gönderen ve alan","Servis sağlayıcı"]'::jsonb, 2, 'teknoloji'),
('Veri anonimleştirme neyi amaçlar?', '["Veriyi silmeyi","Veriyi yedeklemeyi","Veriyi sıkıştırmayı","Kişiyi tanımlanamaz kılmayı"]'::jsonb, 3, 'teknoloji'),
('Yapay zekâda ''model eğitimi'' ne demektir?', '["Veriden parametre öğrenilmesi","Kod yazılması","Sunucu kurulması","Test edilmesi"]'::jsonb, 0, 'teknoloji'),
('Bilgisayarlı görü hangi veriyle çalışır?', '["Metin","Görüntü ve video","Ses","Tablo"]'::jsonb, 1, 'teknoloji'),
('Konuşma tanıma sistemi ne yapar?', '["Metni sese çevirir","Görüntü üretir","Sesi metne çevirir","Veri şifreler"]'::jsonb, 2, 'teknoloji'),
('Öneri sistemi neye dayanır?', '["Rastgele seçime","Alfabetik sıraya","Dosya boyutuna","Kullanıcı davranış örüntülerine"]'::jsonb, 3, 'teknoloji'),
('Büyük veri (big data) hangi özellikleriyle tanımlanır?', '["Hacim, hız ve çeşitlilik","Renk ve boyut","Fiyat ve süre","Ad ve tarih"]'::jsonb, 0, 'teknoloji'),
('Veri madenciliğinin amacı nedir?', '["Veri silmek","Veriden anlamlı örüntü çıkarmak","Veri şifrelemek","Veri yedeklemek"]'::jsonb, 1, 'teknoloji'),
('İş zekâsı (BI) araçları ne sağlar?', '["Kod derlemek","Ağ kurmak","Veriyi karar için görselleştirmek","Sunucu satmak"]'::jsonb, 2, 'teknoloji'),
('Sayısal ikiz (digital twin) nedir?', '["Yedek disk","Sanal makine","Kopya dosya","Gerçek sistemin sayısal kopyası"]'::jsonb, 3, 'teknoloji'),
('Sanal gerçeklik (VR) ile AR arasındaki fark nedir?', '["VR''ın tümüyle sanal ortam sunması","AR''ın tümüyle sanal olması","İkisinin aynı olması","VR''ın ses olması"]'::jsonb, 0, 'teknoloji'),
('Sensörün robotikteki işlevi nedir?', '["Hareket üretmek","Çevreden veri toplamak","Enerji sağlamak","Kod yazmak"]'::jsonb, 1, 'teknoloji'),
('Otonom araçlarda LIDAR ne yapar?', '["Radyo dalgası yayar","Ses ölçer","Lazerle çevreyi haritalar","Isı üretir"]'::jsonb, 2, 'teknoloji'),
('Drone teknolojisinin sivil kullanımına örnek nedir?', '["Ağ kurulumu","Veri şifreleme","Kod derleme","Haritalama ve tarımsal izleme"]'::jsonb, 3, 'teknoloji'),
('Kuantum bilgisayarın klasikten farkı nedir?', '["Kübit ile üst üste durum kullanması","Daha büyük olması","Elektriksiz çalışması","Yazılım gerektirmemesi"]'::jsonb, 0, 'teknoloji'),
('Kübit (qubit) neyi ifade eder?', '["Klasik biti","Kuantum bilgi birimini","Bayt katını","Ağ paketini"]'::jsonb, 1, 'teknoloji'),
('Uydu iletişiminde gecikmenin nedeni nedir?', '["Kablo direnci","Yazılım hatası","Sinyalin uzun mesafe kat etmesi","Anten rengi"]'::jsonb, 2, 'teknoloji'),
('GPS konum belirlemede kaç uydu sinyali yeterlidir?', '["Bir","İki","On","En az dört"]'::jsonb, 3, 'teknoloji'),
('Sinemada ''uzun plan'' neyi anlatır?', '["Kesmeden uzun süre çeken plan","Uzak mesafe çekimi","Uzun film","Uzun senaryo"]'::jsonb, 0, 'sinema'),
('''Establishing shot'' ne işe yarar?', '["Duyguyu vurgulamak","Mekânı ve durumu tanıtmak","Sahneyi bitirmek","Ses eklemek"]'::jsonb, 1, 'sinema'),
('''Omuz üstü çekim'' hangi durumda kullanılır?', '["Kalabalık sahnede","Manzarada","Karşılıklı diyaloglarda","Kovalamacada"]'::jsonb, 2, 'sinema'),
('''Fade in'' geçişi neyi ifade eder?', '["Görüntüden karanlığa","Ani kesme","Bulanıklaşma","Karanlıktan görüntüye açılma"]'::jsonb, 3, 'sinema'),
('''Dissolve'' geçiş türü nedir?', '["İki görüntünün üst üste erimesi","Ani kesme","Karartma","Donmuş kare"]'::jsonb, 0, 'sinema'),
('Sinemada ''montaj dizisi'' neyi sağlar?', '["Tek anı uzatmak","Uzun süreyi kısaca özetlemek","Sesi yükseltmek","Rengi değiştirmek"]'::jsonb, 1, 'sinema'),
('Sinemada ''diegetik ses'' ne demektir?', '["Fon müziği","Dış ses anlatımı","Sahne dünyasının içinden gelen ses","Jenerik müziği"]'::jsonb, 2, 'sinema'),
('Film müziğinin ''leitmotif'' kullanımı nedir?', '["Rastgele müzik","Sessizlik","Doğal ses","Karaktere bağlı yinelenen ezgi"]'::jsonb, 3, 'sinema'),
('Sinemada ''ses tasarımı'' neyi kapsar?', '["Tüm işitsel öğelerin kurgulanması","Yalnız diyalogu","Yalnız müziği","Yalnız efekti"]'::jsonb, 0, 'sinema'),
('Sinemada ''ADR'' işlemi nedir?', '["Efekt üretimi","Diyalogun stüdyoda yeniden kaydı","Müzik bestesi","Renk düzeltme"]'::jsonb, 1, 'sinema'),
('''Boom mikrofon'' ne için kullanılır?', '["Işık vermek","Kamera taşımak","Kadraj dışından ses almak","Renk ölçmek"]'::jsonb, 2, 'sinema'),
('Sinemada ''anahtar ışık'' (key light) nedir?', '["Arka ışık","Dolgu ışığı","Gölge kaynağı","Ana aydınlatma kaynağı"]'::jsonb, 3, 'sinema'),
('''Low-key'' aydınlatma hangi türde yaygındır?', '["Film noir ve gerilim","Müzikal komedi","Çocuk filmi","Belgesel"]'::jsonb, 0, 'sinema'),
('Sinemada ''renk sıcaklığı'' neyi belirtir?', '["Işığın şiddetini","Işığın mavi-sarı eğilimini","Kameranın hızını","Lensin açısını"]'::jsonb, 1, 'sinema'),
('Geniş açı lens hangi etkiyi verir?', '["Uzağı yakınlaştırır","Bulanıklaştırır","Geniş alanı ve derinliği kapsar","Renk katar"]'::jsonb, 2, 'sinema'),
('Telefoto lens ne sağlar?', '["Geniş alan çekmek","Alan derinliğini artırmak","Işık artırmak","Uzak nesneyi yakın göstermek"]'::jsonb, 3, 'sinema'),
('Belgeselde ''sinema verite'' yaklaşımı nedir?', '["Gözlemci ve müdahalesiz çekim","Sahneleme ağırlıklı","Animasyonlu","Yalnız arşivli"]'::jsonb, 0, 'sinema'),
('''Docudrama'' türü neyi birleştirir?', '["Animasyon ve müzikali","Belgesel ve kurguyu","Korku ve komediyi","Reklam ve haberi"]'::jsonb, 1, 'sinema'),
('Sinemada ''kısa metraj'' festivalleri neyi destekler?', '["Gişe rekorlarını","Reklam gelirini","Yeni yönetmenlerin görünürlüğünü","Televizyon dizisini"]'::jsonb, 2, 'sinema'),
('Sinemada ''yapım öncesi'' aşamasında ne yapılır?', '["Kurgu","Vizyon","Fragman yayını","Senaryo, bütçe ve planlama"]'::jsonb, 3, 'sinema'),
('''Yapım sonrası'' aşamada neler yapılır?', '["Kurgu, ses ve renk çalışması","Oyuncu seçimi","Mekân bulma","Senaryo yazımı"]'::jsonb, 0, 'sinema'),
('Sinemada ''senaryo taslağı'' kaç aşamadan geçer?', '["Tek yazımda biter","Birden çok yeniden yazım","Yazılmaz","Çekimde yazılır hep"]'::jsonb, 1, 'sinema'),
('Üç perde yapısı hangi bölümlerden oluşur?', '["Giriş, ara, final","Ses, ışık, kurgu","Kuruluş, çatışma, çözüm","Fragman, film, jenerik"]'::jsonb, 2, 'sinema'),
('Türk sinemasında ''toplumsal gerçekçilik'' hangi konuları işler?', '["Fantastik dünyalar","Uzay yolculuğu","Kraliyet yaşamı","Göç, yoksulluk ve emek"]'::jsonb, 3, 'sinema'),
('Lütfi Ö. Akad hangi alanda öncü sayılır?', '["Yönetmenlik","Oyunculuk","Müzik","Kurgu"]'::jsonb, 0, 'sinema'),
('Türk sinemasında ''göç üçlemesi'' kime aittir?', '["Metin Erksan","Lütfi Ö. Akad","Yılmaz Güney","Atıf Yılmaz"]'::jsonb, 1, 'sinema'),
('Atıf Yılmaz hangi konularda film üretmiştir?', '["Bilim kurgu","Savaş","Kadın kimliği ve toplumsal değişim","Uzay"]'::jsonb, 2, 'sinema'),
('Şerif Gören hangi filmiyle anılır?', '["Uzak","Sürü dışı hiçbiri","Susuz Yaz","Yol"]'::jsonb, 3, 'sinema'),
('Ömer Kavur sinemasının belirgin teması nedir?', '["Kimlik arayışı ve gizem","Komedi","Savaş","Müzikal"]'::jsonb, 0, 'sinema'),
('Türkiye''de sinema salonu sayısının artışı neyi etkiler?', '["Film süresini","Seyirci erişimini","Senaryo kalitesini","Kurgu hızını"]'::jsonb, 1, 'sinema'),
('Dijital dağıtımın sinemaya etkisi nedir?', '["Film süresini kısaltması","Kurguyu bitirmesi","Erişimi genişletmesi","Ses kalitesini düşürmesi"]'::jsonb, 2, 'sinema'),
('Akış (streaming) platformlarının yapım alanındaki rolü nedir?', '["Yalnız dağıtım yapmaları","Salon işletmeleri","Festival düzenlemeleri","Kendi içeriklerini üretmeleri"]'::jsonb, 3, 'sinema'),
('Nota değerlerinden birlik nota kaç dörtlük nota eder?', '["Dört","İki","Sekiz","On altı"]'::jsonb, 0, 'muzik'),
('İkilik nota kaç dörtlük nota değerindedir?', '["Dört","İki","Sekiz","Bir"]'::jsonb, 1, 'muzik'),
('Uzatma noktası bir notaya ne yapar?', '["İki katına çıkarır","Yarıya indirir","Süresinin yarısı kadar uzatır","Susturur"]'::jsonb, 2, 'muzik'),
('Ölçü çizgisinin işlevi nedir?', '["Notayı uzatmak","Sesi yükseltmek","Tempoyu artırmak","Porteyi ölçülere bölmek"]'::jsonb, 3, 'muzik'),
('Dört dörtlük ölçüde bir ölçüde kaç dörtlük vardır?', '["Dört","İki","Üç","Altı"]'::jsonb, 0, 'muzik'),
('Üç dörtlük ölçü hangi dans türüyle özdeşleşmiştir?', '["Marş","Vals","Tango","Polka"]'::jsonb, 1, 'muzik'),
('Marş türü genellikle hangi ölçüde yazılır?', '["Üç zamanlı","Beş zamanlı","İki veya dört zamanlı","Yedi zamanlı"]'::jsonb, 2, 'muzik'),
('Türk müziğinde aksak usul ne demektir?', '["İki eşit vuruş","Serbest ritim","Ölçüsüz akış","Eşit olmayan zaman gruplu usul"]'::jsonb, 3, 'muzik'),
('Dokuz sekizlik usul hangi halk oyunuyla anılır?', '["Zeybek","Halay","Horon","Bar"]'::jsonb, 0, 'muzik'),
('Tonalite (ton) neyi belirler?', '["Tempoyu","Eserin merkez sesini ve dizisini","Ses şiddetini","Çalgı sayısını"]'::jsonb, 1, 'muzik'),
('Modülasyon müzikte ne demektir?', '["Tempo değiştirme","Nüans değiştirme","Ton değiştirme","Çalgı değiştirme"]'::jsonb, 2, 'muzik'),
('Transpoze etmek ne anlama gelir?', '["Eseri hızlandırmak","Eseri kısaltmak","Eseri seslendirmek","Eseri başka bir tona taşımak"]'::jsonb, 3, 'muzik'),
('Kadans (karar) müzikte neyi sağlar?', '["Cümlenin sonlanma duygusunu","Tempoyu artırmayı","Nüansı değiştirmeyi","Çalgı eklemeyi"]'::jsonb, 0, 'muzik'),
('Pentatonik dizi kaç sesten oluşur?', '["Yedi","Beş","On iki","Üç"]'::jsonb, 1, 'muzik'),
('Kromatik dizi neyi içerir?', '["Yalnız tam sesleri","Beş sesi","Tüm yarım sesleri","Üç sesi"]'::jsonb, 2, 'muzik'),
('Blues dizisinde kullanılan karakteristik ses nedir?', '["Koma sesi","Diyez","Bemol dışı hiçbiri","Blue note"]'::jsonb, 3, 'muzik'),
('Bir eserde ''anahtar donanımı'' neyi gösterir?', '["Eserin tonundaki diyez veya bemolleri","Tempoyu","Ölçü sayısını","Çalgı listesini"]'::jsonb, 0, 'muzik'),
('Solfej çalışmasının amacı nedir?', '["Çalgı yapmak","Notaları okuyup seslendirebilmek","Beste yapmak","Konser vermek"]'::jsonb, 1, 'muzik'),
('Deşifre (ilk görüşte okuma) becerisi nedir?', '["Ezberden çalmak","Kulaktan çalmak","Notayı ilk kez görüp çalabilmek","Doğaçlama"]'::jsonb, 2, 'muzik'),
('Mutlak kulak ne anlama gelir?', '["Yüksek sesle söylemek","Hızlı çalmak","Nota yazmak","Bir sesi referanssız tanıyabilmek"]'::jsonb, 3, 'muzik'),
('Rölatif (bağıl) kulak neyi ölçer?', '["Sesler arası aralığı algılamayı","Sesin şiddetini","Tempoyu","Tınıyı"]'::jsonb, 0, 'muzik'),
('Bir orkestrada ''tutti'' terimi neyi ifade eder?', '["Solo bölüm","Tüm topluluğun birlikte çalması","Sessizlik","Tempo değişimi"]'::jsonb, 1, 'muzik'),
('Konçertoda ''kadenza'' bölümü nedir?', '["Orkestra girişi","Koro bölümü","Solistin sergilediği virtüöz bölüm","Final akoru"]'::jsonb, 2, 'muzik'),
('Süit (suite) formu neyi bir araya getirir?', '["Tek uzun bölümü","Yalnız koro parçalarını","Sadece uvertürleri","Bir dizi dans parçasını"]'::jsonb, 3, 'muzik'),
('Divertimento türünün amacı nedir?', '["Eğlendirici hafif müzik","Dinî tören müziği","Ağıt","Marş"]'::jsonb, 0, 'muzik'),
('Serenad türü geleneksel olarak nerede seslendirilirdi?', '["Sabah kilisede","Akşam açık havada","Öğlen sarayda","Gece mahzende"]'::jsonb, 1, 'muzik'),
('Nokturn (gece parçası) hangi karakterdedir?', '["Hızlı ve gürültülü","Marş temposunda","Dingin ve lirik","Dans ritminde"]'::jsonb, 2, 'muzik'),
('Etüt (etude) hangi amaçla yazılır?', '["Konser açılışı için","Dans için","Dinî tören için","Teknik gelişim için"]'::jsonb, 3, 'muzik'),
('Prelüd ve füg birlikteliğiyle tanınan besteci kimdir?', '["Bach","Chopin","Liszt","Debussy"]'::jsonb, 0, 'muzik'),
('Opera sahnesinde ''libretto'' nedir?', '["Sahne dekoru","Operanın metni","Orkestra partisi","Kostüm listesi"]'::jsonb, 1, 'muzik'),
('Operada ''resitatif'' bölümün işlevi nedir?', '["Duyguyu ezgiyle yoğunlaştırmak","Dans etmek","Olayı konuşur gibi ilerletmek","Ara vermek"]'::jsonb, 2, 'muzik'),
('Operet ile opera arasındaki fark nedir?', '["Operetin daha uzun olması","Operanın konuşmalı olması","İkisinin aynı olması","Operetin hafif ve konuşmalı olması"]'::jsonb, 3, 'muzik'),
('Bale sanatında ''pas de deux'' nedir?', '["İki dansçının birlikte dansı","Solo dans","Koro dansı","Sahne dekoru"]'::jsonb, 0, 'muzik'),
('Bale ayakkabısı ''pointe'' ne sağlar?', '["Hızlı koşmayı","Parmak ucunda durabilmeyi","Yüksek sıçramayı","Ses çıkarmayı"]'::jsonb, 1, 'muzik'),
('Türk müziğinde ''peşrev'' hangi bölümde çalınır?', '["Fasılın sonunda","Ara vermede","Fasılın başında","Şarkı arasında"]'::jsonb, 2, 'muzik'),
('Türk müziğinde ''saz semaisi'' fasılda nerede yer alır?', '["En başta","Ortada zorunlu","Hiç yer almaz","Sonlara doğru"]'::jsonb, 3, 'muzik'),
('Türk müziğinde ''gazel'' nasıl icra edilir?', '["Serbest ritimle sesle","Sabit usulle","Yalnız çalgıyla","Koroyla"]'::jsonb, 0, 'muzik'),
('Türk halk müziğinde ''ağıt'' hangi konuyu işler?', '["Düğün","Ölüm ve acı","Bahar","Yolculuk"]'::jsonb, 1, 'muzik'),
('Türkü çeşitlerinden ''bozlak'' hangi yöreyle anılır?', '["Doğu Karadeniz","Trakya","Orta Anadolu","Ege"]'::jsonb, 2, 'muzik'),
('Halk müziğinde ''zeybek'' havalarının karakteri nasıldır?', '["Çok hızlı","Hüzünlü ve serbest","Marş gibi","Ağır ve mağrur"]'::jsonb, 3, 'muzik'),
('Futbolda uzatma devreleri kaç dakikadır?', '["İki devre 15''er dakika","Tek devre 30 dakika","İki devre 10''ar dakika","Tek devre 15 dakika"]'::jsonb, 0, 'spor'),
('Futbolda sarı kartın anlamı nedir?', '["Oyundan atılma","Uyarı","Gol iptali","Penaltı"]'::jsonb, 1, 'spor'),
('Futbolda ikinci sarı kart neye yol açar?', '["Uyarıya","Penaltıya","Kırmızı kart ve oyundan atılma","Korner atışına"]'::jsonb, 2, 'spor'),
('Basketbolda serbest atış kaç sayı değerindedir?', '["İki","Üç","Dört","Bir"]'::jsonb, 3, 'spor'),
('Basketbolda ''çift ribaund'' hangi ihlaldir?', '["Topu iki kez sektirme","Adım atma","Üç saniye","Faul"]'::jsonb, 0, 'spor'),
('Basketbolda ''adım'' ihlali ne demektir?', '["İki el kullanmak","Top sürmeden fazla adım atmak","Potaya asılmak","Faul yapmak"]'::jsonb, 1, 'spor'),
('Voleybolda beşinci set kaç sayıya oynanır?', '["25","21","15","11"]'::jsonb, 2, 'spor'),
('Hentbolde bir maç kaç dakikadır?', '["İki devre 45''er dakika","Dört periyot","Tek devre 60 dakika","İki devre 30''ar dakika"]'::jsonb, 3, 'spor'),
('Su topunda bir takımda sahada kaç oyuncu bulunur?', '["Yedi","Beş","Altı","On bir"]'::jsonb, 0, 'spor'),
('Ragbi sporunda sayı yapılan bölgeye ne ad verilir?', '["Ceza sahası","Deneme alanı","Orta saha","Kale önü"]'::jsonb, 1, 'spor'),
('Amerikan futbolunda ''touchdown'' kaç puan getirir?', '["Üç","İki","Altı","Yedi"]'::jsonb, 2, 'spor'),
('Beyzbolda saha kaç kaleden (base) oluşur?', '["Üç","Beş","Altı","Dört"]'::jsonb, 3, 'spor'),
('Kriket sporu hangi ülkede doğmuştur?', '["İngiltere","Hindistan","Avustralya","Güney Afrika"]'::jsonb, 0, 'spor'),
('Badmintonda kullanılan topa ne ad verilir?', '["Raket topu","Tüylü top","Sert top","Yumuşak top"]'::jsonb, 1, 'spor'),
('Squash sporu nerede oynanır?', '["Açık çim sahada","Buz pistinde","Dört duvarlı kapalı kortta","Havuzda"]'::jsonb, 2, 'spor'),
('Masa tenisinde top hangi malzemedendir?', '["Deri","Kauçuk","Ahşap","Plastik"]'::jsonb, 3, 'spor'),
('Tenis raketiyle vurulan ''servis'' nedir?', '["Sayıyı başlatan ilk vuruş","Son vuruş","Ağ vuruşu","Smaç"]'::jsonb, 0, 'spor'),
('Tenis maçında bir seti kazanmak için kaç oyun gerekir?', '["Dört","Altı (iki fark)","Beş","Sekiz"]'::jsonb, 1, 'spor'),
('Yüzmede olimpiyat havuzunun uzunluğu kaç metredir?', '["25","100","50","75"]'::jsonb, 2, 'spor'),
('Atlama (dalış) sporunda puanlama neye göre yapılır?', '["Süreye","Mesafeye","Sıçrama yüksekliğine","Teknik ve zorluk derecesine"]'::jsonb, 3, 'spor'),
('Senkronize yüzmenin belirgin özelliği nedir?', '["Müzikle uyumlu ortak hareket","Hız yarışı","Dalış derinliği","Uzun mesafe"]'::jsonb, 0, 'spor'),
('Atletizmde ''engelli koşu'' hangi zorluğu içerir?', '["Ağırlık taşımak","Belirli aralıklarla engel aşmak","Su geçmek yalnızca","Ters koşmak"]'::jsonb, 1, 'spor'),
('Üç adım atlamanın aşamaları hangileridir?', '["Koşu, dönüş, atlama","Zıplama, düşme, kalkma","Sıçrama, adım, atlama","Atlama, koşu, dönüş"]'::jsonb, 2, 'spor'),
('Çekiç atma hangi hareketle yapılır?', '["Düz itme","Yukarı fırlatma","Yandan atma","Dönerek savurma"]'::jsonb, 3, 'spor'),
('Disk atmada sporcu nerede durur?', '["Daire içinde","Kare içinde","Çizgi üstünde","Serbest alanda"]'::jsonb, 0, 'spor'),
('Judo sporunda kuşak renkleri neyi gösterir?', '["Kiloyu","Derece ve deneyimi","Yaşı","Ülkeyi"]'::jsonb, 1, 'spor'),
('Boksta ''nakavt'' ne anlama gelir?', '["Puanla yenilgi","Diskalifiye","Rakibin sayılamayacak biçimde düşmesi","Beraberlik"]'::jsonb, 2, 'spor'),
('Eskrimde puan nasıl kazanılır?', '["Rakibi düşürerek","Silahı düşürerek","Süreyi bitirerek","Geçerli bölgeye dokunarak"]'::jsonb, 3, 'spor'),
('Okçulukta yay çekme gücü neyle ölçülür?', '["Libre (pound)","Metre","Saniye","Derece"]'::jsonb, 0, 'spor'),
('Bisiklette ''peloton'' ne demektir?', '["Kaçış grubu","Ana yarışçı grubu","Yedek takım","Bitiş çizgisi"]'::jsonb, 1, 'spor'),
('Bisiklet yarışında ''etap'' nedir?', '["Tüm yarış","Antrenman","Turun bir günlük bölümü","Ödül töreni"]'::jsonb, 2, 'spor'),
('Formula 1''de yarış sonunda gösterilen bayrak hangisidir?', '["Sarı bayrak","Kırmızı bayrak","Mavi bayrak","Damalı bayrak"]'::jsonb, 3, 'spor'),
('Motor sporlarında sarı bayrak neyi bildirir?', '["Tehlike ve yavaşlama uyarısı","Yarış bitişi","Yarış başlangıcı","Pit girişi"]'::jsonb, 0, 'spor'),
('Kayakla atlamada puanlama neye göre yapılır?', '["Yalnız süreye","Mesafe ve stil puanına","Yalnız yüksekliğe","Rakip sayısına"]'::jsonb, 1, 'spor'),
('Artistik patinajda puanlama neyi değerlendirir?', '["Yalnız hızı","Yalnız mesafeyi","Teknik öğeler ve sanatsal sunum","Yalnız süreyi"]'::jsonb, 2, 'spor'),
('Dağcılıkta ''akklimatizasyon'' ne demektir?', '["Ekipman seçimi","Rota çizimi","Kamp kurma","Yüksekliğe uyum sağlama"]'::jsonb, 3, 'spor'),
('Yelken yarışlarında ''start hattı'' nasıl belirlenir?', '["İki şamandıra arasındaki hayali çizgiyle","Kıyı çizgisiyle","Rüzgâr yönüyle","Hakem düdüğüyle"]'::jsonb, 0, 'spor'),
('Kürek ve kano arasındaki temel fark nedir?', '["Kanoda tekne olmaması","Kürekte sırtın gidiş yönüne dönük olması","Kürekte küreğin olmaması","Kanonun karada yapılması"]'::jsonb, 1, 'spor'),
('Sporda ''sakatlık önleme'' için en temel uygulama nedir?', '["Ağır yük kaldırma","Uykusuz antrenman","Doğru ısınma ve teknik","Öğün atlama"]'::jsonb, 2, 'spor')
on conflict (soru) do nothing;
