-- Soru havuzu genişletme — Parti 7: Tarih + Bilim derinleşme
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Osmanlı Devleti kaç yılında resmen sona ermiştir?', '["1922","1918","1923","1920"]'::jsonb, 0, 'tarih'),
('Saltanat hangi yılda kaldırılmıştır?', '["1922","1923","1924","1920"]'::jsonb, 0, 'tarih'),
('Halifelik hangi yılda kaldırılmıştır?', '["1924","1922","1923","1926"]'::jsonb, 0, 'tarih'),
('Cumhuriyet döneminde ilk muhalefet partisi hangisidir?', '["Terakkiperver Cumhuriyet Fırkası","Serbest Fırka","Demokrat Parti","Millet Partisi"]'::jsonb, 0, 'tarih'),
('Türkiye''de ilk genel nüfus sayımı hangi yılda yapılmıştır?', '["1927","1923","1930","1935"]'::jsonb, 0, 'tarih'),
('Kabotaj Kanunu hangi alanla ilgilidir?', '["Denizcilik","Tarım","Eğitim","Sanayi"]'::jsonb, 0, 'tarih'),
('Medeni Kanun hangi ülkeden uyarlanmıştır?', '["İsviçre","Fransa","Almanya","İtalya"]'::jsonb, 0, 'tarih'),
('Türkiye''de takvim ve saat değişikliği hangi yıl kabul edilmiştir?', '["1925","1923","1928","1931"]'::jsonb, 0, 'tarih'),
('İzmir İktisat Kongresi hangi yılda toplanmıştır?', '["1923","1920","1925","1930"]'::jsonb, 0, 'tarih'),
('Köy Enstitüleri hangi amaçla kurulmuştur?', '["Köye öğretmen yetiştirmek","Tarımı sanayileştirmek","Askeri eğitim","Sağlık taraması"]'::jsonb, 0, 'tarih'),
('Erzurum Kongresi hangi tarihte toplanmıştır?', '["23 Temmuz 1919","4 Eylül 1919","19 Mayıs 1919","23 Nisan 1920"]'::jsonb, 0, 'tarih'),
('Sivas Kongresi hangi ayda toplanmıştır?', '["Eylül 1919","Temmuz 1919","Mayıs 1919","Ocak 1920"]'::jsonb, 0, 'tarih'),
('Misak-ı Milli hangi mecliste kabul edilmiştir?', '["Son Osmanlı Mebusan Meclisi","TBMM","Sivas Kongresi","Erzurum Kongresi"]'::jsonb, 0, 'tarih'),
('Sakarya Meydan Muharebesi hangi yıldadır?', '["1921","1922","1920","1919"]'::jsonb, 0, 'tarih'),
('"Hattı müdafaa yoktur, sathı müdafaa vardır" sözü hangi savaşta söylenmiştir?', '["Sakarya","Büyük Taarruz","I. İnönü","Çanakkale"]'::jsonb, 0, 'tarih'),
('İnönü Savaşları kime karşı yapılmıştır?', '["Yunanistan","İngiltere","Fransa","İtalya"]'::jsonb, 0, 'tarih'),
('Mudanya Ateşkesi hangi savaşı sona erdirmiştir?', '["Kurtuluş Savaşı''nın silahlı dönemini","I. Dünya Savaşı''nı","Balkan Savaşı''nı","Trablusgarp''ı"]'::jsonb, 0, 'tarih'),
('Montrö Boğazlar Sözleşmesi hangi yılda imzalanmıştır?', '["1936","1923","1939","1930"]'::jsonb, 0, 'tarih'),
('Hatay Türkiye''ye hangi yılda katılmıştır?', '["1939","1936","1938","1945"]'::jsonb, 0, 'tarih'),
('Türkiye Kore Savaşı''na hangi yıl asker göndermiştir?', '["1950","1952","1948","1955"]'::jsonb, 0, 'tarih'),
('Kıbrıs Barış Harekatı hangi yılda yapılmıştır?', '["1974","1963","1980","1971"]'::jsonb, 0, 'tarih'),
('Osmanlı tarihinde en uzun süre tahtta kalan padişah kimdir?', '["Kanuni Sultan Süleyman","II. Abdülhamid","Fatih","IV. Mehmed"]'::jsonb, 0, 'tarih'),
('Osmanlı''nın son padişahı kimdir?', '["VI. Mehmed (Vahdettin)","II. Abdülhamid","V. Mehmed Reşad","Abdülmecid Efendi"]'::jsonb, 0, 'tarih'),
('Son halife kimdir?', '["Abdülmecid Efendi","Vahdettin","II. Abdülhamid","Mehmed Reşad"]'::jsonb, 0, 'tarih'),
('II. Abdülhamid kaç yıl tahtta kalmıştır?', '["33","20","13","40"]'::jsonb, 0, 'tarih'),
('Genç Osman hangi olayla tahttan indirilmiştir?', '["Yeniçeri isyanı","Savaş yenilgisi","Hastalık","Saray darbesi olmadan öldü"]'::jsonb, 0, 'tarih'),
('"Avcı" lakaplı Osmanlı padişahı kimdir?', '["IV. Mehmed","IV. Murad","II. Osman","III. Selim"]'::jsonb, 0, 'tarih'),
('"Yıldırım" lakaplı padişah kimdir?', '["I. Bayezid","II. Bayezid","I. Murad","Çelebi Mehmed"]'::jsonb, 0, 'tarih'),
('"Fatih" unvanı II. Mehmed''e neden verilmiştir?', '["İstanbul''u fethettiği için","Çok sefer yaptığı için","Genç tahta çıktığı için","Bilime önem verdiği için"]'::jsonb, 0, 'tarih'),
('Kosova Savaşı''nda şehit olan Osmanlı padişahı kimdir?', '["I. Murad","I. Bayezid","Orhan Gazi","II. Murad"]'::jsonb, 0, 'tarih'),
('İstanbul kuşatmasında kullanılan dev topların dökümcüsü kimdir?', '["Urban","Sinan","Davud","Saruca"]'::jsonb, 0, 'tarih'),
('Fatih''in İstanbul kuşatmasında gemileri nereden yürüttüğü anlatılır?', '["Karadan Haliç''e","Boğazdan Marmara''ya","Adalardan kıyıya","Üsküdar''dan Sarayburnu''na"]'::jsonb, 0, 'tarih'),
('Enderun Mektebi nedir?', '["Saray okulu","Askeri kışla","Medrese","Kütüphane"]'::jsonb, 0, 'tarih'),
('Devşirme sistemi neyi amaçlardı?', '["Asker ve devlet adamı yetiştirmek","Vergi toplamak","Toprak dağıtmak","Ticareti geliştirmek"]'::jsonb, 0, 'tarih'),
('Tımar sistemi neyle ilgilidir?', '["Toprak ve asker","Ticaret","Eğitim","Din"]'::jsonb, 0, 'tarih'),
('Osmanlı''da para işlerinden sorumlu görevli kimdir?', '["Defterdar","Kazasker","Nişancı","Reisülküttab"]'::jsonb, 0, 'tarih'),
('Osmanlı''da adalet işlerinden sorumlu divan üyesi kimdir?', '["Kazasker","Defterdar","Vezir","Şeyhülislam"]'::jsonb, 0, 'tarih'),
('Kapıkulu ocaklarının en ünlü birliği hangisidir?', '["Yeniçeriler","Sipahiler","Akıncılar","Azaplar"]'::jsonb, 0, 'tarih'),
('Akıncılar hangi görevde uzmandı?', '["Sınır ötesi keşif ve akın","Saray koruması","Top dökümü","Donanma"]'::jsonb, 0, 'tarih'),
('Mısır''ı Osmanlı topraklarına katan padişah kimdir?', '["Yavuz Sultan Selim","Kanuni","Fatih","II. Bayezid"]'::jsonb, 0, 'tarih'),
('Ridaniye Savaşı hangi devlete karşı yapılmıştır?', '["Memlükler","Safeviler","Akkoyunlular","Bizans"]'::jsonb, 0, 'tarih'),
('Çaldıran Savaşı kime karşı yapılmıştır?', '["Safeviler","Memlükler","Venedik","Macarlar"]'::jsonb, 0, 'tarih'),
('Rodos''u fetheden padişah kimdir?', '["Kanuni Sultan Süleyman","Fatih","Yavuz","II. Mehmed"]'::jsonb, 0, 'tarih'),
('Kıbrıs hangi padişah döneminde fethedilmiştir?', '["II. Selim","Kanuni","III. Murad","Yavuz"]'::jsonb, 0, 'tarih'),
('Girit''in fethi hangi yüzyılda tamamlanmıştır?', '["17. yüzyıl","16. yüzyıl","15. yüzyıl","18. yüzyıl"]'::jsonb, 0, 'tarih'),
('Karlofça Antlaşması''nın önemi nedir?', '["İlk büyük toprak kaybı","İlk ticaret anlaşması","Savaş başlatması","Sınır düzeltmesi"]'::jsonb, 0, 'tarih'),
('93 Harbi hangi devletle yapılmıştır?', '["Rusya","Yunanistan","Avusturya","İran"]'::jsonb, 0, 'tarih'),
('93 Harbi hangi yıllara denk gelir?', '["1877-1878","1893-1894","1853-1856","1828-1829"]'::jsonb, 0, 'tarih'),
('Kırım Savaşı''nda Osmanlı''nın müttefikleri kimlerdi?', '["İngiltere ve Fransa","Almanya ve Avusturya","Rusya ve İran","İtalya ve İspanya"]'::jsonb, 0, 'tarih'),
('Trablusgarp Savaşı hangi devletle yapılmıştır?', '["İtalya","Fransa","İngiltere","Yunanistan"]'::jsonb, 0, 'tarih'),
('Balkan Savaşları hangi yıllarda yaşanmıştır?', '["1912-1913","1908-1909","1914-1915","1910-1911"]'::jsonb, 0, 'tarih'),
('I. Dünya Savaşı''nı bitiren Osmanlı ateşkesi hangisidir?', '["Mondros","Mudanya","Sevr","Lozan"]'::jsonb, 0, 'tarih'),
('Çanakkale Cephesi''nde Anzaklar hangi ülkelerden gelmiştir?', '["Avustralya ve Yeni Zelanda","İngiltere ve İrlanda","Kanada ve ABD","Hindistan ve Mısır"]'::jsonb, 0, 'tarih'),
('Kutü''l-Amare zaferi hangi cephededir?', '["Irak","Kafkas","Filistin","Galiçya"]'::jsonb, 0, 'tarih'),
('Mustafa Kemal''in Çanakkale''de komuta ettiği ünlü tepe hangisidir?', '["Conkbayırı","Alçıtepe","Kireçtepe","Kanlısırt"]'::jsonb, 0, 'tarih'),
('Periyodik tabloda kaç element vardır (resmi olarak)?', '["118","100","108","120"]'::jsonb, 0, 'bilim'),
('Helyumun kimyasal sembolü nedir?', '["He","H","Hl","Hm"]'::jsonb, 0, 'bilim'),
('Karbonun kimyasal sembolü nedir?', '["C","Ca","K","Cr"]'::jsonb, 0, 'bilim'),
('Azotun kimyasal sembolü nedir?', '["N","A","Az","Ni"]'::jsonb, 0, 'bilim'),
('Kalsiyumun kimyasal sembolü nedir?', '["Ca","K","Cl","C"]'::jsonb, 0, 'bilim'),
('Potasyumun kimyasal sembolü nedir?', '["K","P","Po","Pt"]'::jsonb, 0, 'bilim'),
('Sodyumun kimyasal sembolü nedir?', '["Na","S","So","N"]'::jsonb, 0, 'bilim'),
('Cıvanın kimyasal sembolü nedir?', '["Hg","Cv","Ci","Me"]'::jsonb, 0, 'bilim'),
('Kurşunun kimyasal sembolü nedir?', '["Pb","Ku","Pl","Le"]'::jsonb, 0, 'bilim'),
('Oda sıcaklığında sıvı olan tek metal hangisidir?', '["Cıva","Kurşun","Galyum","Sodyum"]'::jsonb, 0, 'bilim'),
('Havadan hafif olduğu için balonlarda kullanılan güvenli gaz hangisidir?', '["Helyum","Hidrojen","Azot","Neon"]'::jsonb, 0, 'bilim'),
('Karbondioksitin formülü nedir?', '["CO2","CO","C2O","CO3"]'::jsonb, 0, 'bilim'),
('Metan gazının formülü nedir?', '["CH4","CO2","C2H6","CH3"]'::jsonb, 0, 'bilim'),
('Ozonun formülü nedir?', '["O3","O2","O","O4"]'::jsonb, 0, 'bilim'),
('Glikoz hangi tür besin maddesidir?', '["Karbonhidrat","Protein","Yağ","Vitamin"]'::jsonb, 0, 'bilim'),
('Proteinlerin yapı taşı nedir?', '["Amino asit","Glikoz","Yağ asidi","Nükleotid"]'::jsonb, 0, 'bilim'),
('DNA''nın yapı taşı nedir?', '["Nükleotid","Amino asit","Glikoz","Lipit"]'::jsonb, 0, 'bilim'),
('Kasların çalışması için temel enerji molekülü hangisidir?', '["ATP","DNA","RNA","Glikojen"]'::jsonb, 0, 'bilim'),
('Sindirim hangi organda başlar?', '["Ağız","Mide","İnce bağırsak","Yemek borusu"]'::jsonb, 0, 'bilim'),
('Besinlerin emilimi en çok hangi organda gerçekleşir?', '["İnce bağırsak","Mide","Kalın bağırsak","Karaciğer"]'::jsonb, 0, 'bilim'),
('Safra hangi organda üretilir?', '["Karaciğer","Safra kesesi","Pankreas","Mide"]'::jsonb, 0, 'bilim'),
('İdrar hangi organda üretilir?', '["Böbrek","Mesane","Karaciğer","İdrar yolu"]'::jsonb, 0, 'bilim'),
('Soluk alıp vermede görevli kas hangisidir?', '["Diyafram","Kalp kası","Karın kası","Boyun kası"]'::jsonb, 0, 'bilim'),
('Ses telleri nerede bulunur?', '["Gırtlak","Yutak","Soluk borusu","Ağız"]'::jsonb, 0, 'bilim'),
('Vücudun en güçlü kası (kuvvet/boyut oranıyla) hangisi kabul edilir?', '["Çene kası","Kol kası","Bacak kası","Karın kası"]'::jsonb, 0, 'bilim'),
('Tat alma duyusu hangi organda bulunur?', '["Dil","Damak","Diş","Dudak"]'::jsonb, 0, 'bilim'),
('Koku alma duyusu hangi organdadır?', '["Burun","Ağız","Kulak","Göz"]'::jsonb, 0, 'bilim'),
('Görme olayında görüntü gözün neresinde oluşur?', '["Retina","Kornea","İris","Mercek"]'::jsonb, 0, 'bilim'),
('Renk körlüğü en çok hangi renkleri ayırt etmeyi zorlaştırır?', '["Kırmızı ve yeşil","Mavi ve sarı","Siyah ve beyaz","Mor ve turuncu"]'::jsonb, 0, 'bilim'),
('Bebeklerin kemik sayısı yetişkinlerden nasıldır?', '["Daha fazla","Daha az","Aynı","Yarısı kadar"]'::jsonb, 0, 'bilim'),
('Parmak izleri kimlerde aynıdır?', '["Hiç kimsede","Tek yumurta ikizlerinde","Kardeşlerde","Anne ve çocukta"]'::jsonb, 0, 'bilim'),
('İnsan kalbi günde yaklaşık kaç kez atar?', '["100.000","10.000","1.000.000","50.000"]'::jsonb, 0, 'bilim'),
('Yetişkin bir insanda yaklaşık kaç litre kan bulunur?', '["5","2","10","8"]'::jsonb, 0, 'bilim'),
('Kan hangi organda üretilir?', '["Kemik iliği","Kalp","Karaciğer","Dalak"]'::jsonb, 0, 'bilim'),
('Aşı vücudu nasıl korur?', '["Bağışıklık sistemini eğiterek","Mikropları anında öldürerek","Kanı temizleyerek","Ateşi düşürerek"]'::jsonb, 0, 'bilim'),
('Antibiyotikler neye karşı etkilidir?', '["Bakteriler","Virüsler","Mantarlar","Parazitler"]'::jsonb, 0, 'bilim'),
('Grip hastalığına ne sebep olur?', '["Virüs","Bakteri","Mantar","Soğuk hava"]'::jsonb, 0, 'bilim'),
('Mikropları ilk kez sistematik inceleyen ve pastörizasyonu bulan kişi kimdir?', '["Louis Pasteur","Robert Koch","Fleming","Lister"]'::jsonb, 0, 'bilim'),
('Tüberküloz basilini keşfeden bilim insanı kimdir?', '["Robert Koch","Pasteur","Fleming","Behring"]'::jsonb, 0, 'bilim'),
('Dünyanın yuvarlak olduğunu antik çağda hesaplayan bilgin kimdir?', '["Eratosthenes","Batlamyus","Aristo","Pisagor"]'::jsonb, 0, 'bilim'),
('Gezegenlerin eliptik yörüngelerde döndüğünü bulan bilim insanı kimdir?', '["Kepler","Kopernik","Galileo","Newton"]'::jsonb, 0, 'bilim'),
('Elektromanyetik indüksiyonu keşfeden bilim insanı kimdir?', '["Faraday","Maxwell","Ohm","Volta"]'::jsonb, 0, 'bilim'),
('İlk pili icat eden bilim insanı kimdir?', '["Volta","Galvani","Faraday","Edison"]'::jsonb, 0, 'bilim'),
('Telsiz telgrafın öncüsü kimdir?', '["Marconi","Bell","Morse","Hertz"]'::jsonb, 0, 'bilim'),
('Mors alfabesini geliştiren kişi kimdir?', '["Samuel Morse","Marconi","Bell","Edison"]'::jsonb, 0, 'bilim'),
('Dinamiti icat eden kişi kimdir?', '["Alfred Nobel","Curie","Faraday","Goodyear"]'::jsonb, 0, 'bilim'),
('Uçağı icat eden kardeşler kimdir?', '["Wright Kardeşler","Montgolfier Kardeşler","Lumiere Kardeşler","Grimm Kardeşler"]'::jsonb, 0, 'bilim'),
('Sıcak hava balonunu icat eden kardeşler kimdir?', '["Montgolfier","Wright","Lumiere","Michelin"]'::jsonb, 0, 'bilim'),
('Sinematografı icat eden kardeşler kimdir?', '["Lumiere","Wright","Montgolfier","Warner"]'::jsonb, 0, 'bilim'),
('Buharlı lokomotifiyle demiryolu çağını başlatan mühendis kimdir?', '["George Stephenson","James Watt","Robert Fulton","Karl Benz"]'::jsonb, 0, 'bilim'),
('Otomobilde seri üretimi başlatan kişi kimdir?', '["Henry Ford","Karl Benz","Daimler","Porsche"]'::jsonb, 0, 'bilim'),
('İlk benzinli otomobili geliştiren kişi kimdir?', '["Karl Benz","Henry Ford","Rudolf Diesel","Ferdinand Porsche"]'::jsonb, 0, 'bilim'),
('Dizel motoru kim icat etmiştir?', '["Rudolf Diesel","Karl Benz","Otto","Ford"]'::jsonb, 0, 'bilim'),
('Dünyayı dolaşan ilk denizci ekibinin komutanı kimdir?', '["Macellan","Kolomb","Vasco da Gama","Drake"]'::jsonb, 0, 'tarih'),
('Hindistan''a deniz yolunu bulan denizci kimdir?', '["Vasco da Gama","Kolomb","Macellan","Cabot"]'::jsonb, 0, 'tarih'),
('Ümit Burnu hangi kıtanın güney ucundadır?', '["Afrika","Güney Amerika","Avustralya","Asya"]'::jsonb, 0, 'cografya'),
('Horn Burnu hangi kıtanın güney ucundadır?', '["Güney Amerika","Afrika","Avustralya","Antarktika"]'::jsonb, 0, 'cografya'),
('Aydınlanma Çağı hangi yüzyılda zirve yapmıştır?', '["18. yüzyıl","16. yüzyıl","19. yüzyıl","15. yüzyıl"]'::jsonb, 0, 'tarih'),
('"Toplum Sözleşmesi" adlı eserin yazarı kimdir?', '["Rousseau","Voltaire","Montesquieu","Locke"]'::jsonb, 0, 'tarih'),
('Kuvvetler ayrılığı ilkesini sistemleştiren düşünür kimdir?', '["Montesquieu","Rousseau","Hobbes","Machiavelli"]'::jsonb, 0, 'tarih'),
('"Prens" adlı siyaset kitabının yazarı kimdir?', '["Machiavelli","Dante","Erasmus","More"]'::jsonb, 0, 'tarih'),
('"Ütopya" adlı eserin yazarı kimdir?', '["Thomas More","Machiavelli","Bacon","Campanella"]'::jsonb, 0, 'edebiyat'),
('Einstein Nobel Ödülü''nü hangi çalışmasıyla almıştır?', '["Fotoelektrik etki","Görelilik","Kuantum çekim","Atom modeli"]'::jsonb, 0, 'bilim'),
('Kuantum kuramının öncüsü olan "kuanta" fikrini ortaya atan kimdir?', '["Max Planck","Einstein","Bohr","Heisenberg"]'::jsonb, 0, 'bilim'),
('Atom modelinde elektronların yörüngelerde dolandığını öne süren bilim insanı kimdir?', '["Niels Bohr","Rutherford","Dalton","Thomson"]'::jsonb, 0, 'bilim'),
('Elektronu keşfeden bilim insanı kimdir?', '["J.J. Thomson","Rutherford","Bohr","Chadwick"]'::jsonb, 0, 'bilim'),
('Nötronu keşfeden bilim insanı kimdir?', '["James Chadwick","Thomson","Rutherford","Fermi"]'::jsonb, 0, 'bilim'),
('Atom çekirdeğini keşfeden bilim insanı kimdir?', '["Rutherford","Bohr","Thomson","Dalton"]'::jsonb, 0, 'bilim')
on conflict (soru) do nothing;
