-- Soru havuzu genişletme: cografya +121
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('İskandinavya''nın en büyük yüzölçümlü ülkesi hangisidir?', '["İsveç","Norveç","Finlandiya","Danimarka"]'::jsonb, 0, 'cografya'),
('Finlandiya hangi özelliğiyle anılır?', '["Çöl alanlarıyla","Binlerce göle sahip olması","Volkanlarıyla","Yüksek dağlarıyla"]'::jsonb, 1, 'cografya'),
('İzlanda hangi okyanusta yer alır?', '["Hint Okyanusu","Pasifik","Atlas Okyanusu","Arktik dışı hiçbiri"]'::jsonb, 2, 'cografya'),
('Danimarka''nın anakarası hangi yarımadadadır?', '["İberya","Balkan","Anadolu","Jutland"]'::jsonb, 3, 'cografya'),
('Hollanda''nın önemli limanı Rotterdam hangi denize açılır?', '["Kuzey Denizi","Baltık Denizi","Akdeniz","Karadeniz"]'::jsonb, 0, 'cografya'),
('Belçika''nın resmî dillerinden biri hangisidir?', '["İtalyanca","Flamanca","Portekizce","Yunanca"]'::jsonb, 1, 'cografya'),
('İsviçre''nin coğrafi özelliği nedir?', '["Kıyı ovası ağırlıklı","Çöl ülkesi","Dağlık ve denize kıyısı olmayan","Ada ülkesi"]'::jsonb, 2, 'cografya'),
('Avusturya''nın büyük bölümü hangi dağ sisteminde yer alır?', '["Karpatlar","Pireneler","Apeninler","Alpler"]'::jsonb, 3, 'cografya'),
('Almanya''nın sanayi bölgesi olan Ruhr neye dayanıyordu?', '["Kömür ve demir çelik","Turizm","Balıkçılık","Tarım"]'::jsonb, 0, 'cografya'),
('Polonya''nın kuzeyinde hangi deniz yer alır?', '["Kuzey Denizi","Baltık Denizi","Karadeniz","Adriyatik"]'::jsonb, 1, 'cografya'),
('Romanya''nın Karadeniz kıyısındaki limanı hangisidir?', '["Varna","Odessa","Köstence","Burgaz"]'::jsonb, 2, 'cografya'),
('Bulgaristan''ın Karadeniz kıyısındaki limanı hangisidir?', '["Köstence","Selanik","Pire","Varna"]'::jsonb, 3, 'cografya'),
('Yunanistan''ın en büyük limanı hangisidir?', '["Pire","Selanik","Patras","Volos"]'::jsonb, 0, 'cografya'),
('Ege Denizi''ndeki Yunan takımadalarından biri hangisidir?', '["Kanarya Adaları","Kiklad Adaları","Balear Adaları","Azor Adaları"]'::jsonb, 1, 'cografya'),
('İtalya''nın kuzeyindeki büyük ovası hangisidir?', '["Ren Ovası","Tuna Ovası","Po Ovası","Ebro Ovası"]'::jsonb, 2, 'cografya'),
('İspanya''nın en uzun nehri hangisidir?', '["Ebro","Duero","Guadalquivir","Tajo"]'::jsonb, 3, 'cografya'),
('Portekiz hangi okyanusa kıyısıdır?', '["Atlas Okyanusu","Akdeniz","Hint Okyanusu","Pasifik"]'::jsonb, 0, 'cografya'),
('Fransa''nın güneydoğusundaki büyük limanı hangisidir?', '["Bordeaux","Marsilya","Le Havre","Nantes"]'::jsonb, 1, 'cografya'),
('İngiltere, İskoçya ve Galler hangi adada yer alır?', '["İrlanda Adası","İzlanda","Britanya Adası","Man Adası"]'::jsonb, 2, 'cografya'),
('Manş Denizi hangi iki ülkeyi ayırır?', '["İrlanda ve İngiltere","Hollanda ve Belçika","Norveç ve Danimarka","İngiltere ve Fransa"]'::jsonb, 3, 'cografya'),
('Rusya''nın Uzak Doğu''daki büyük limanı hangisidir?', '["Vladivostok","Murmansk","Kaliningrad","Soçi"]'::jsonb, 0, 'cografya'),
('Sibirya''nın büyük nehirlerinden biri hangisidir?', '["Tuna","Yenisey","Ren","Elbe"]'::jsonb, 1, 'cografya'),
('Trans-Sibirya Demiryolu hangi iki ucu bağlar?', '["Petersburg ve Kiev","Pekin ve Şangay","Moskova ve Vladivostok","Berlin ve Varşova"]'::jsonb, 2, 'cografya'),
('Kazakistan hangi deniz kıyısında yer alır?', '["Karadeniz","Baltık Denizi","Aral dışında hiçbiri","Hazar Denizi"]'::jsonb, 3, 'cografya'),
('Aral Gölü''nün küçülmesinin başlıca nedeni nedir?', '["Nehirlerin sulamaya yönlendirilmesi","Deprem","Volkanik etkinlik","İklimin soğuması"]'::jsonb, 0, 'cografya'),
('Türkmenistan''ın büyük çölü hangisidir?', '["Kızılkum","Karakum","Gobi","Taklamakan"]'::jsonb, 1, 'cografya'),
('Özbekistan''ın tarihi İpek Yolu kenti hangisidir?', '["Bakü","Tebriz","Semerkant","Kabil"]'::jsonb, 2, 'cografya'),
('Pamir Dağları ağırlıklı olarak hangi ülkededir?', '["Kırgızistan","Kazakistan","Türkmenistan","Tacikistan"]'::jsonb, 3, 'cografya'),
('Çin''in en kalabalık kenti hangisidir?', '["Şangay","Pekin","Guangzhou","Şenzen"]'::jsonb, 0, 'cografya'),
('Çin''in Taklamakan Çölü hangi bölgededir?', '["Tibet","Sincan","Mançurya","Yunnan"]'::jsonb, 1, 'cografya'),
('Tibet Platosu hangi adla anılır?', '["Dünyanın bahçesi","Dünyanın çölü","Dünyanın çatısı","Dünyanın ormanı"]'::jsonb, 2, 'cografya'),
('Japonya kaç ana adadan oluşur?', '["İki","Altı","On","Dört"]'::jsonb, 3, 'cografya'),
('Japonya''nın deprem riskinin yüksek olmasının nedeni nedir?', '["Levha sınırında yer alması","Ada ülkesi olması","Nüfus yoğunluğu","Volkansız olması"]'::jsonb, 0, 'cografya'),
('Kore Yarımadası kaç devlete bölünmüştür?', '["Üç","İki","Dört","Bir"]'::jsonb, 1, 'cografya'),
('Hindistan''ın güneyindeki büyük platosu hangisidir?', '["Tibet Platosu","Anadolu Platosu","Dekkan Platosu","Brezilya Platosu"]'::jsonb, 2, 'cografya'),
('Bangladeş''in sık sel yaşamasının nedeni nedir?', '["Dağlık olması","Çöl olması","Buzul olması","Alçak delta ülkesi olması"]'::jsonb, 3, 'cografya'),
('Endonezya''nın en kalabalık adası hangisidir?', '["Java","Sumatra","Borneo","Sulawesi"]'::jsonb, 0, 'cografya'),
('Filipinler coğrafi olarak nasıl bir ülkedir?', '["Karayla çevrili","Takımada ülkesi","Yarımada ülkesi","Kıta ülkesi"]'::jsonb, 1, 'cografya'),
('Avustralya''nın merkezindeki ünlü kayalık hangisidir?', '["Everest","Kilimanjaro","Uluru","Table Mountain"]'::jsonb, 2, 'cografya'),
('Yeni Zelanda kaç ana adadan oluşur?', '["Üç","Dört","Bir","İki"]'::jsonb, 3, 'cografya'),
('Papua Yeni Gine hangi adayı Endonezya ile paylaşır?', '["Yeni Gine","Borneo","Timor","Sulawesi"]'::jsonb, 0, 'cografya'),
('Fiji ve Samoa hangi bölgede yer alır?', '["Karayipler","Okyanusya","Akdeniz","Baltık"]'::jsonb, 1, 'cografya'),
('Kanada''nın en kalabalık eyaleti hangisidir?', '["Quebec","Alberta","Ontario","Manitoba"]'::jsonb, 2, 'cografya'),
('ABD''nin en kalabalık eyaleti hangisidir?', '["Teksas","New York","Florida","Kaliforniya"]'::jsonb, 3, 'cografya'),
('Büyük Göller hangi iki ülke arasında yer alır?', '["ABD ve Kanada","ABD ve Meksika","Kanada ve Grönland","Meksika ve Guatemala"]'::jsonb, 0, 'cografya'),
('Meksika''nın büyük yarımadası hangisidir?', '["Florida","Yucatan","Kaliforniya dışı hiçbiri","Alaska"]'::jsonb, 1, 'cografya'),
('Orta Amerika''yı Güney Amerika''ya bağlayan ülke hangisidir?', '["Kosta Rika","Nikaragua","Panama","Honduras"]'::jsonb, 2, 'cografya'),
('Karayipler''in en büyük adası hangisidir?', '["Jamaika","Haiti","Porto Riko","Küba"]'::jsonb, 3, 'cografya'),
('Brezilya''nın en kalabalık kenti hangisidir?', '["Sao Paulo","Rio de Janeiro","Brasilia","Salvador"]'::jsonb, 0, 'cografya'),
('And Dağları kaç ülkeden geçer?', '["İki ülke","Yediden fazla ülke","Üç ülke","Tek ülke"]'::jsonb, 1, 'cografya'),
('Titicaca Gölü hangi iki ülke arasında yer alır?', '["Şili ve Arjantin","Ekvador ve Kolombiya","Peru ve Bolivya","Brezilya ve Paraguay"]'::jsonb, 2, 'cografya'),
('Patagonya bölgesi hangi ülkeleri kapsar?', '["Brezilya ve Peru","Kolombiya ve Venezuela","Uruguay ve Paraguay","Arjantin ve Şili"]'::jsonb, 3, 'cografya'),
('Şili''nin coğrafi biçimi nasıl tanımlanır?', '["Uzun ve dar","Kare biçimli","Dairesel","Üçgen"]'::jsonb, 0, 'cografya'),
('Uruguay hangi iki ülke arasındadır?', '["Şili ve Peru","Brezilya ve Arjantin","Bolivya ve Paraguay","Kolombiya ve Ekvador"]'::jsonb, 1, 'cografya'),
('Afrika''nın en büyük yüzölçümlü ülkesi hangisidir?', '["Sudan","Libya","Cezayir","Mısır"]'::jsonb, 2, 'cografya'),
('Kongo Havzası hangi bitki örtüsüyle kaplıdır?', '["Tundra","Çöl","Bozkır","Yağmur ormanı"]'::jsonb, 3, 'cografya'),
('Namib Çölü hangi ülkeye adını vermiştir?', '["Namibya","Nijerya","Nijer","Angola"]'::jsonb, 0, 'cografya'),
('Kalahari Çölü hangi ülkelerde uzanır?', '["Mısır ve Sudan","Botsvana ve çevresi","Fas ve Cezayir","Kenya ve Somali"]'::jsonb, 1, 'cografya'),
('Madagaskar''ın biyolojik özelliği nedir?', '["Tür çeşitliliğinin azlığı","Buzullarla kaplı olması","Endemik tür oranının yüksekliği","Çöl olması"]'::jsonb, 2, 'cografya'),
('Afrika Boynuzu hangi ülkeleri kapsar?', '["Fas ve Tunus","Angola ve Zambiya","Gana ve Togo","Somali ve çevresi"]'::jsonb, 3, 'cografya'),
('Süveyş Kanalı''nın açılması hangi rotayı kısaltmıştır?', '["Avrupa-Asya deniz yolunu","Amerika-Avrupa yolunu","Kutup rotasını","Atlantik geçişini"]'::jsonb, 0, 'cografya'),
('Nil Nehri''nin iki ana kolu hangileridir?', '["Kuzey Nil ve Güney Nil","Beyaz Nil ve Mavi Nil","Doğu Nil ve Batı Nil","Sarı Nil ve Kızıl Nil"]'::jsonb, 1, 'cografya'),
('Asvan Barajı hangi nehir üzerindedir?', '["Kongo","Nijer","Nil","Zambezi"]'::jsonb, 2, 'cografya'),
('Ölü Deniz hangi ülkeler arasındadır?', '["Mısır ve Sudan","Suriye ve Lübnan","Irak ve İran","İsrail ve Ürdün"]'::jsonb, 3, 'cografya'),
('Mezopotamya hangi iki nehir arasındaki bölgedir?', '["Fırat ve Dicle","Nil ve Kongo","Ganj ve İndus","Tuna ve Ren"]'::jsonb, 0, 'cografya'),
('Zagros Dağları ağırlıklı olarak hangi ülkededir?', '["Irak","İran","Suriye","Afganistan"]'::jsonb, 1, 'cografya'),
('Umman Denizi hangi okyanusun parçasıdır?', '["Pasifik","Atlas","Hint Okyanusu","Arktik"]'::jsonb, 2, 'cografya'),
('Bir kentin ''nüfus çekim gücü'' neye bağlıdır?', '["İklimine yalnızca","Yüzölçümüne","Rakımına","İş, eğitim ve hizmet olanaklarına"]'::jsonb, 3, 'cografya'),
('Kentleşme oranı neyi gösterir?', '["Kentte yaşayan nüfusun payını","Kent sayısını","Kentin alanını","Bina sayısını"]'::jsonb, 0, 'cografya'),
('Metropoliten alan neyi kapsar?', '["Yalnız kent merkezini","Kent ve etkileşimdeki çevresini","Yalnız kırsalı","Yalnız sanayi bölgesini"]'::jsonb, 1, 'cografya'),
('Kent merkezinde iş yerlerinin yoğunlaştığı alana ne denir?', '["Sanayi bölgesi","Konut alanı","Merkezî iş alanı","Yeşil alan"]'::jsonb, 2, 'cografya'),
('Kentsel dönüşümün temel amacı nedir?', '["Nüfusu artırmak","Yeşil alanı azaltmak","Trafiği artırmak","Sağlıksız yapı stokunu yenilemek"]'::jsonb, 3, 'cografya'),
('Bir kentte toplu taşımanın yaygınlaşmasının çevresel yararı nedir?', '["Emisyonun azalması","Trafiğin artması","Gürültünün artması","Enerji tüketiminin artması"]'::jsonb, 0, 'cografya'),
('Yaya bölgeleri kentlerde neyi amaçlar?', '["Araç trafiğini artırmak","Yaşanabilirliği ve ticareti artırmak","Yeşil alanı azaltmak","Nüfusu azaltmak"]'::jsonb, 1, 'cografya'),
('İmar planı neyi belirler?', '["Vergi oranlarını","Nüfus sayısını","Arazi kullanım kararlarını","İklim tipini"]'::jsonb, 2, 'cografya'),
('Deprem yönetmeliğinin amacı nedir?', '["Kira belirlemek","Arsa satmak","Nüfus saymak","Yapıların dayanımını güvenceye almak"]'::jsonb, 3, 'cografya'),
('Afet risk yönetiminde ilk aşama nedir?', '["Risk belirleme ve haritalama","Yardım dağıtımı","Yeniden inşa","Sigorta ödemesi"]'::jsonb, 0, 'cografya'),
('Tarımda ''kuru tarım'' ne demektir?', '["Sulamalı tarım","Yalnız yağışla yapılan tarım","Serada tarım","Su kültürü"]'::jsonb, 1, 'cografya'),
('Sulu tarımın kuru tarıma üstünlüğü nedir?', '["Maliyetinin sıfır olması","Emek gerektirmemesi","Verimin iklime daha az bağlı olması","Toprak istememesi"]'::jsonb, 2, 'cografya'),
('Ekstansif tarımın özelliği nedir?', '["Dar alanda yoğun girdi","Serada üretim","Su kültürü","Geniş alanda düşük girdiyle üretim"]'::jsonb, 3, 'cografya'),
('İntansif (yoğun) tarımın özelliği nedir?', '["Dar alanda yüksek girdi ve verim","Geniş alanda düşük verim","Girdisiz üretim","Nadas ağırlıklı"]'::jsonb, 0, 'cografya'),
('Plantasyon tarımı hangi kuşakta yaygındır?', '["Kutup","Tropikal","Tundra","Çöl"]'::jsonb, 1, 'cografya'),
('Kakao üretiminde öne çıkan bölge hangisidir?', '["Kuzey Avrupa","Orta Asya","Batı Afrika","Sibirya"]'::jsonb, 2, 'cografya'),
('Kahve üretiminde öne çıkan ülkelerden biri hangisidir?', '["Norveç","Kanada","Rusya","Brezilya"]'::jsonb, 3, 'cografya'),
('Pirinç üretiminin en yoğun olduğu kıta hangisidir?', '["Asya","Avrupa","Afrika","Okyanusya"]'::jsonb, 0, 'cografya'),
('Buğday kuşağı hangi iklim kuşağında yer alır?', '["Ekvatoral kuşak","Orta kuşak","Kutup kuşağı","Tundra"]'::jsonb, 1, 'cografya'),
('Palmiye yağı üretiminde öne çıkan ülke hangisidir?', '["Kanada","Rusya","Endonezya","İsveç"]'::jsonb, 2, 'cografya'),
('Zeytin üretiminin dünyada yoğunlaştığı bölge neresidir?', '["Kuzey Avrupa","Sibirya","Amazon","Akdeniz havzası"]'::jsonb, 3, 'cografya'),
('Bağcılık için elverişli iklim hangisidir?', '["Akdeniz iklimi","Tundra iklimi","Ekvatoral iklim","Kutup iklimi"]'::jsonb, 0, 'cografya'),
('Küçükbaş hayvancılık hangi arazi tipinde yaygındır?', '["Bataklık","Bozkır ve dağlık meralar","Yağmur ormanı","Kutup buzu"]'::jsonb, 1, 'cografya'),
('Ren geyiği yetiştiriciliği hangi bölgede yapılır?', '["Sahra","Amazon","Kuzey kutup çevresi","Akdeniz"]'::jsonb, 2, 'cografya'),
('Lama ve alpaka hangi bölgede yetiştirilir?', '["Alpler","Himalayalar","Uralar","And Dağları"]'::jsonb, 3, 'cografya'),
('Deve hangi ortama uyum sağlamıştır?', '["Çöl","Kutup","Yağmur ormanı","Bataklık"]'::jsonb, 0, 'cografya'),
('Balıkçılığın en verimli olduğu alanlar hangileridir?', '["Derin okyanus ortası","Kıta sahanlığı ve akıntı kavşakları","Kutup buzu altı","Çöl gölleri"]'::jsonb, 1, 'cografya'),
('Aşırı avlanmanın sonucu nedir?', '["Balık artışı","Suyun temizlenmesi","Stokların tükenmesi","Tuzluluk artışı"]'::jsonb, 2, 'cografya'),
('Deniz koruma alanlarının amacı nedir?', '["Avlanmayı artırmak","Turizmi yasaklamak","Gemi trafiğini artırmak","Ekosistemi ve stokları korumak"]'::jsonb, 3, 'cografya'),
('Kutuplarda buz erimesi hangi türü doğrudan tehdit eder?', '["Kutup ayısı","Deve","Zürafa","Kanguru"]'::jsonb, 0, 'cografya'),
('Mercan ağarması (bleaching) neden olur?', '["Suyun soğumasından","Deniz suyunun ısınmasından","Gelgitten","Rüzgârdan"]'::jsonb, 1, 'cografya'),
('Okyanus asitlenmesinin nedeni nedir?', '["Tuz artışı","Buzul erimesi","Karbondioksitin suda çözünmesi","Rüzgâr"]'::jsonb, 2, 'cografya'),
('Deniz seviyesi yükselmesinden en çok etkilenecek ülke tipi hangisidir?', '["Dağlık ülkeler","Karayla çevrili ülkeler","Çöl ülkeleri","Alçak ada devletleri"]'::jsonb, 3, 'cografya'),
('Kuraklık göstergesi olarak hangi veri izlenir?', '["Yağış ve toprak nemi","Nüfus sayısı","Deniz tuzluluğu","Rüzgâr yönü"]'::jsonb, 0, 'cografya'),
('Sel riskini artıran kentsel etken nedir?', '["Ağaçlandırma","Geçirimsiz yüzeylerin artması","Yeşil çatı","Dere ıslahı"]'::jsonb, 1, 'cografya'),
('Çığ riski hangi koşulda artar?', '["Düz arazide","Kurak havada","Dik yamaçta ağır kar birikiminde","Yaz ortasında"]'::jsonb, 2, 'cografya'),
('Orman yangınlarını artıran hava koşulu nedir?', '["Serin ve yağışlı hava","Sisli hava","Karlı hava","Sıcak, kuru ve rüzgârlı hava"]'::jsonb, 3, 'cografya'),
('Yangın sonrası ilk yapılması gereken çevresel önlem nedir?', '["Erozyona karşı toprağı korumak","Yol açmak","Yapı yapmak","Maden aramak"]'::jsonb, 0, 'cografya'),
('Meteorolojik uyarı sisteminin amacı nedir?', '["Turizm reklamı","Riskli hava olaylarına hazırlık","Ürün fiyatı belirleme","Nüfus sayımı"]'::jsonb, 1, 'cografya'),
('Hava tahmininde model kullanımı neye dayanır?', '["Rastgele tahmine","Takvim hesabına","Atmosfer verilerinin sayısal çözümüne","Halk deneyimine"]'::jsonb, 2, 'cografya'),
('Uydu görüntüleri meteorolojide ne sağlar?', '["Toprak sürümü","Nüfus sayımı","Yol yapımı","Bulut ve sistem hareketinin izlenmesi"]'::jsonb, 3, 'cografya'),
('Radar meteorolojide neyi ölçer?', '["Yağış yoğunluğu ve hareketini","Toprak nemini","Deniz derinliğini","Nüfusu"]'::jsonb, 0, 'cografya'),
('İklim ile hava durumu arasındaki fark nedir?', '["Havanın uzun süreli olması","İklimin uzun süreli ortalama olması","İkisinin aynı olması","İklimin günlük olması"]'::jsonb, 1, 'cografya'),
('İklim değişikliğinin tarımsal etkisi ne olabilir?', '["Verimin her yerde artması","Toprağın zenginleşmesi","Ürün kuşaklarının kayması","Su ihtiyacının bitmesi"]'::jsonb, 2, 'cografya'),
('Karbon yutağı olarak en önemli ekosistem hangisidir?', '["Çöller","Kentler","Kara yolları","Ormanlar ve okyanuslar"]'::jsonb, 3, 'cografya'),
('Yenilenebilir enerjinin iklim açısından yararı nedir?', '["Sera gazı salımını azaltması","Su tüketimini artırması","Toprağı bozması","Nüfusu azaltması"]'::jsonb, 0, 'cografya'),
('Sürdürülebilir tarımın ilkelerinden biri nedir?', '["Aşırı gübreleme","Toprak ve suyu koruyarak üretmek","Tek ürüne bağımlılık","Sürekli sürüm"]'::jsonb, 1, 'cografya'),
('Tarımda ''gen kaynağı'' korumanın amacı nedir?', '["Verimi düşürmek","Üretimi durdurmak","Tür çeşitliliğini gelecek için saklamak","İhracatı azaltmak"]'::jsonb, 2, 'cografya'),
('Tohum bankalarının işlevi nedir?', '["Tohum satmak","Gübre üretmek","Sulama yapmak","Bitki genetik kaynaklarını korumak"]'::jsonb, 3, 'cografya'),
('Yerel tohum kullanımının avantajı nedir?', '["Yöre koşullarına uyumlu olması","Her yerde aynı verimi vermesi","Su gerektirmemesi","Hastalanmaması"]'::jsonb, 0, 'cografya'),
('Coğrafi keşiflerin tarımsal sonucu ne olmuştur?', '["Tarımın durması","Ürünlerin kıtalar arasında yayılması","Ekili alanın azalması","Tohumun yok olması"]'::jsonb, 1, 'cografya'),
('Patates ve mısırın anavatanı neresidir?', '["Asya","Afrika","Amerika","Avrupa"]'::jsonb, 2, 'cografya'),
('Buğday ve arpanın ilk kez ehlileştirildiği bölge neresidir?', '["Amazon","Sibirya","Avustralya","Bereketli Hilal"]'::jsonb, 3, 'cografya'),
('Bereketli Hilal hangi bölgeyi kapsar?', '["Mezopotamya ve çevresi","Nil deltası yalnızca","İndus vadisi","Sarı Irmak havzası"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
