-- Soru havuzu genişletme: muzik +135
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Müzikte ses şiddetini belirten işaretlere ne ad verilir?', '["Nüans","Tempo","Ritim","Ton"]'::jsonb, 0, 'muzik'),
('Sol anahtarı porte üzerinde hangi çizgiden başlar?', '["Birinci çizgi","İkinci çizgi","Üçüncü çizgi","Dördüncü çizgi"]'::jsonb, 1, 'muzik'),
('Bir oktav kaç tam ses aralığı içerir?', '["Beş nota","On iki nota","Sekiz nota","Üç nota"]'::jsonb, 2, 'muzik'),
('Diyez işareti bir notaya ne yapar?', '["Yarım ses kalınlaştırır","Sesi uzatır","Sesi susturur","Yarım ses inceltir"]'::jsonb, 3, 'muzik'),
('Bemol işareti bir notaya ne yapar?', '["Yarım ses kalınlaştırır","Yarım ses inceltir","Sesi kısaltır","Sesi iki katına çıkarır"]'::jsonb, 0, 'muzik'),
('Bekar (naturel) işaretinin işlevi nedir?', '["Sesi uzatmak","Diyez ve bemolü iptal etmek","Tempoyu artırmak","Ölçüyü bitirmek"]'::jsonb, 1, 'muzik'),
('Müzikte ''senkop'' ne anlama gelir?', '["Tempoyu yavaşlatmak","Sesi kesmek","Vurgunun zayıf zamana kayması","Akoru bozmak"]'::jsonb, 2, 'muzik'),
('Legato terimi nasıl çalmayı belirtir?', '["Kesik kesik","Çok hızlı","Çok gürültülü","Bağlı ve akıcı"]'::jsonb, 3, 'muzik'),
('Staccato terimi nasıl çalmayı belirtir?', '["Kesik kesik","Bağlı ve akıcı","Çok yavaş","Çok yüksek sesle"]'::jsonb, 0, 'muzik'),
('Crescendo işareti neyi belirtir?', '["Sesin azalmasını","Sesin giderek güçlenmesini","Tempo artışını","Susmayı"]'::jsonb, 1, 'muzik'),
('Diminuendo işareti neyi belirtir?', '["Sesin güçlenmesini","Hızlanmayı","Sesin giderek azalmasını","Duraklamayı"]'::jsonb, 2, 'muzik'),
('Forte terimi ne anlama gelir?', '["Hafif","Hızlı","Yavaş","Kuvvetli"]'::jsonb, 3, 'muzik'),
('Piano terimi müzikte ne anlama gelir?', '["Hafif","Kuvvetli","Hızlı","Bağlı"]'::jsonb, 0, 'muzik'),
('Allegro terimi hangi hızı belirtir?', '["Çok yavaş","Hızlı ve neşeli","Ağır","Orta"]'::jsonb, 1, 'muzik'),
('Adagio terimi hangi hızı belirtir?', '["Çok hızlı","Neşeli","Ağır","Orta hızlı"]'::jsonb, 2, 'muzik'),
('Andante terimi hangi hızı belirtir?', '["Çok hızlı","Çok ağır","Duraksayarak","Yürüyüş hızında"]'::jsonb, 3, 'muzik'),
('Presto terimi hangi hızı belirtir?', '["Çok hızlı","Çok yavaş","Orta","Serbest"]'::jsonb, 0, 'muzik'),
('Metronom neyi belirlemeye yarar?', '["Tonu","Tempoyu","Ses şiddetini","Akordu"]'::jsonb, 1, 'muzik'),
('Bir eserin ana ezgi çekirdeğine ne ad verilir?', '["Nüans","Koda","Motif","Ölçü"]'::jsonb, 2, 'muzik'),
('Eserin sonunda yer alan bitiriş bölümüne ne denir?', '["Prelüd","Motif","Kadans","Koda"]'::jsonb, 3, 'muzik'),
('Bir eserin giriş bölümüne ne ad verilir?', '["Prelüd","Koda","Final","Röpriz"]'::jsonb, 0, 'muzik'),
('Aynı ezginin farklı seslerce gecikmeli söylenmesine ne denir?', '["Kadans","Kanon","Nüans","Koda"]'::jsonb, 1, 'muzik'),
('Çok sesli müzikte bağımsız ezgilerin örülmesine ne denir?', '["Monofoni","Homofoni","Polifoni","Senkop"]'::jsonb, 2, 'muzik'),
('Tek ezgiden oluşan müzik dokusuna ne ad verilir?', '["Polifoni","Homofoni","Heterofoni","Monofoni"]'::jsonb, 3, 'muzik'),
('Bir akor en az kaç sesin birlikte duyulmasıdır?', '["Üç ses","İki ses","Dört ses","Beş ses"]'::jsonb, 0, 'muzik'),
('Majör dizinin genel karakteri nasıl tanımlanır?', '["Hüzünlü","Parlak ve neşeli","Gerilimli","Belirsiz"]'::jsonb, 1, 'muzik'),
('Armoni bilimi neyi inceler?', '["Ritmi","Tempoyu","Seslerin birlikte kullanımını","Çalgı yapımını"]'::jsonb, 2, 'muzik'),
('Kontrpuan tekniği neyi konu alır?', '["Akor kurulumunu","Ritim kalıplarını","Nüans yazımını","Bağımsız ezgilerin birlikte işlenmesini"]'::jsonb, 3, 'muzik'),
('Füg formunun temel özelliği nedir?', '["Bir temanın seslerde taklit edilmesi","Tek ezgili olması","Doğaçlama olması","Sözlü olması"]'::jsonb, 0, 'muzik'),
('Sonat formu kaç ana bölümden oluşur?', '["Giriş ve final","Sergi, gelişme, yeniden sergi","Tek bölüm","Beş bölüm"]'::jsonb, 1, 'muzik'),
('Oda müziği hangi ölçekte icra edilir?', '["Büyük orkestrayla","Yalnız koroyla","Küçük topluluklarla","Bando ile"]'::jsonb, 2, 'muzik'),
('Yaylı çalgılar dörtlüsü hangi çalgılardan oluşur?', '["Keman, flüt, obua, çello","Piyano, keman, çello, arp","Dört keman","İki keman, viyola, çello"]'::jsonb, 3, 'muzik'),
('Senfoni orkestrasında en kalabalık çalgı ailesi hangisidir?', '["Yaylılar","Vurmalılar","Bakır üflemeliler","Tahta üflemeliler"]'::jsonb, 0, 'muzik'),
('Kontrbas hangi çalgı ailesindendir?', '["Vurmalılar","Yaylılar","Üflemeliler","Tuşlular"]'::jsonb, 1, 'muzik'),
('Obua hangi çalgı ailesindendir?', '["Bakır üflemeliler","Yaylılar","Tahta üflemeliler","Vurmalılar"]'::jsonb, 2, 'muzik'),
('Trombon hangi çalgı ailesindendir?', '["Tahta üflemeliler","Yaylılar","Tuşlular","Bakır üflemeliler"]'::jsonb, 3, 'muzik'),
('Timpani hangi çalgı ailesindendir?', '["Vurmalılar","Yaylılar","Üflemeliler","Tuşlular"]'::jsonb, 0, 'muzik'),
('Arp çalgısının sesi nasıl üretilir?', '["Yayla sürtülerek","Tellerin parmakla çekilmesiyle","Üflenerek","Vurularak"]'::jsonb, 1, 'muzik'),
('Org çalgısının sesi nasıl oluşur?', '["Tellere vurularak","Yayla","Borulardan hava geçirilerek","Deriye vurarak"]'::jsonb, 2, 'muzik'),
('Klavsen ile piyano arasındaki temel fark nedir?', '["Klavsen elektroniktir","Piyano telsizdir","İkisi de üflemelidir","Klavsende tel çekilir, piyanoda vurulur"]'::jsonb, 3, 'muzik'),
('Piyanonun tam adı olan ''pianoforte'' neyi anlatır?', '["Hafif ve kuvvetli çalabilmesini","İki klavyeli olmasını","Ayakla çalınmasını","Telsiz olmasını"]'::jsonb, 0, 'muzik'),
('Keman ailesinin en kalın sesli üyesi hangisidir?', '["Viyola","Kontrbas","Çello","Keman"]'::jsonb, 1, 'muzik'),
('Viyolanın keman ile farkı nedir?', '["Daha küçük olması","Telsiz olması","Daha büyük ve pes sesli olması","Üflemeli olması"]'::jsonb, 2, 'muzik'),
('Klarnetin ses üretimi nasıl gerçekleşir?', '["Çift kamışla","Telle","Deriyle","Tek kamışın titreşimiyle"]'::jsonb, 3, 'muzik'),
('Fagot hangi ses bölgesinde çalar?', '["Pes (kalın)","Çok tiz","Yalnız orta","Ses üretmez"]'::jsonb, 0, 'muzik'),
('Saksofon hangi malzemeden yapılmasına rağmen tahta üflemeli sayılır?', '["Ahşap","Metal","Cam","Plastik"]'::jsonb, 1, 'muzik'),
('Bağlamada perdeler neye göre bağlanır?', '["Rastgele","Batı diyatonik dizisine göre","Makam dizilerine göre","Vurmalı düzene göre"]'::jsonb, 2, 'muzik'),
('Kanun çalgısı nasıl çalınır?', '["Yayla","Üflenerek","Elle vurularak","Mızrapla tellere vurularak"]'::jsonb, 3, 'muzik'),
('Ud çalgısının en belirgin özelliği nedir?', '["Perdesiz sapı","Perdeli sapı","Yaylı çalınması","Tuşlu olması"]'::jsonb, 0, 'muzik'),
('Ney çalgısı hangi malzemeden yapılır?', '["Metal","Kamış","Ahşap gövde","Deri"]'::jsonb, 1, 'muzik'),
('Kemençe hangi bölgemizin halk müziğiyle özdeşleşmiştir?', '["Ege","Güneydoğu","Karadeniz","İç Anadolu"]'::jsonb, 2, 'muzik'),
('Kabak kemane hangi teknikle çalınır?', '["Mızrapla","Üflenerek","Vurularak","Yayla"]'::jsonb, 3, 'muzik'),
('Tulum çalgısı hangi yörede yaygındır?', '["Doğu Karadeniz","Trakya","Akdeniz","İç Anadolu"]'::jsonb, 0, 'muzik'),
('Sipsi çalgısı hangi yöreye özgüdür?', '["Doğu Karadeniz","Batı Akdeniz","Güneydoğu","Marmara"]'::jsonb, 1, 'muzik'),
('Darbuka hangi çalgı grubuna girer?', '["Telli","Üflemeli","Vurmalı","Tuşlu"]'::jsonb, 2, 'muzik'),
('Türk müziğinde bir oktav kaç eşit olmayan aralığa bölünür?', '["On iki","Yedi","Otuz altı","Yirmi dört"]'::jsonb, 3, 'muzik'),
('Hüseyni, rast ve nihavend neyi ifade eder?', '["Makam adlarını","Usul adlarını","Çalgı adlarını","Form adlarını"]'::jsonb, 0, 'muzik'),
('Türk müziğinde ''taksim'' ne demektir?', '["Toplu söyleme","Doğaçlama solo icra","Ritim kalıbı","Şarkı formu"]'::jsonb, 1, 'muzik'),
('Mevlevi ayinlerinde kullanılan temel çalgı hangisidir?', '["Zurna","Darbuka","Ney","Kanun"]'::jsonb, 2, 'muzik'),
('Türk Halk Müziği''nde uzun hava türünün özelliği nedir?', '["Sabit tempolu olması","Çok sesli olması","Sözsüz olması","Serbest ritimli olması"]'::jsonb, 3, 'muzik'),
('Kırık hava türünün özelliği nedir?', '["Belirli usule bağlı olması","Serbest ritimli olması","Yalnız enstrümantal olması","Doğaçlama olması"]'::jsonb, 0, 'muzik'),
('Türkü sözlerini derleyip notaya alan kişiye ne denir?', '["Besteci","Derleyici","Şef","Solist"]'::jsonb, 1, 'muzik'),
('Halay hangi bölgemizin halk oyunudur?', '["Karadeniz","Trakya","Doğu ve Güneydoğu Anadolu","Ege"]'::jsonb, 2, 'muzik'),
('Horon hangi bölgemizin halk oyunudur?', '["Ege","Akdeniz","İç Anadolu","Karadeniz"]'::jsonb, 3, 'muzik'),
('Bar oyunu hangi bölgemizle özdeşleşmiştir?', '["Doğu Anadolu","Marmara","Akdeniz","Ege"]'::jsonb, 0, 'muzik'),
('Türkiye''de çok sesli müziğin öncüsü sayılan besteci topluluğu hangisidir?', '["Altılar Grubu","Türk Beşleri","Rus Beşlisi","Viyana Okulu"]'::jsonb, 1, 'muzik'),
('Ahmed Adnan Saygun hangi alanda tanınır?', '["Şiir","Resim","Beste","Mimari"]'::jsonb, 2, 'muzik'),
('Ulvi Cemal Erkin hangi müzik akımının temsilcisidir?', '["Caz","Rock","Arabesk","Çok sesli Türk müziği"]'::jsonb, 3, 'muzik'),
('Cemal Reşit Rey hangi alanda öne çıkmıştır?', '["Besteci ve orkestra şefi","Ressam","Yazar","Mimar"]'::jsonb, 0, 'muzik'),
('Itri hangi eseriyle tanınır?', '["Beşinci Senfoni","Tekbir ve Segâh Ayin","Requiem","Bolero"]'::jsonb, 1, 'muzik'),
('Tanburi Cemil Bey hangi çalgının ustası olarak bilinir?', '["Piyano","Keman","Tanbur","Flüt"]'::jsonb, 2, 'muzik'),
('Johann Sebastian Bach hangi dönemin bestecisidir?', '["Klasik","Romantik","Empresyonist","Barok"]'::jsonb, 3, 'muzik'),
('Wolfgang Amadeus Mozart hangi dönemin bestecisidir?', '["Klasik","Barok","Romantik","Çağdaş"]'::jsonb, 0, 'muzik'),
('Beethoven hangi iki dönem arasında köprü sayılır?', '["Barok ve Klasik","Klasik ve Romantik","Romantik ve Çağdaş","Rönesans ve Barok"]'::jsonb, 1, 'muzik'),
('Handel''in ''Su Müziği'' hangi ortam için bestelenmiştir?', '["Kilise ayini","Askerî tören","Nehir üzerindeki kraliyet gezisi","Opera sahnesi"]'::jsonb, 2, 'muzik'),
('Mozart''ın ünlü operalarından biri hangisidir?', '["Aida","Carmen","Rigoletto","Sihirli Flüt"]'::jsonb, 3, 'muzik'),
('Verdi''nin Mısır''da geçen ünlü operası hangisidir?', '["Aida","Carmen","Tosca","Fidelio"]'::jsonb, 0, 'muzik'),
('Bizet''nin İspanya''da geçen ünlü operası hangisidir?', '["Aida","Carmen","Otello","Turandot"]'::jsonb, 1, 'muzik'),
('Puccini''nin Çin''de geçen operası hangisidir?', '["Carmen","Aida","Turandot","Fidelio"]'::jsonb, 2, 'muzik'),
('Wagner''in dört operadan oluşan dev döngüsü hangisidir?', '["Dört Mevsim","Brandenburg Konçertoları","Su Müziği","Nibelung''un Yüzüğü"]'::jsonb, 3, 'muzik'),
('Çaykovski''nin ünlü balesi hangisidir?', '["Kuğu Gölü","Carmen","Aida","Bolero"]'::jsonb, 0, 'muzik'),
('Stravinski''nin skandal yaratan balesi hangisidir?', '["Kuğu Gölü","Bahar Ayini","Fındıkkıran","Giselle"]'::jsonb, 1, 'muzik'),
('Ravel''in tek bir ritim üzerine kurulu ünlü eseri hangisidir?', '["Bahar Ayini","Dört Mevsim","Bolero","Peer Gynt"]'::jsonb, 2, 'muzik'),
('Chopin ağırlıklı olarak hangi çalgı için beste yapmıştır?', '["Keman","Flüt","Org","Piyano"]'::jsonb, 3, 'muzik'),
('Franz Liszt hangi çalgının virtüözüydü?', '["Piyano","Keman","Çello","Arp"]'::jsonb, 0, 'muzik'),
('Paganini hangi çalgının virtüözü olarak bilinir?', '["Piyano","Keman","Gitar","Flüt"]'::jsonb, 1, 'muzik'),
('Schubert hangi müzik türündeki eserleriyle tanınır?', '["Opera","Bale","Lied (sanat şarkısı)","Marş"]'::jsonb, 2, 'muzik'),
('Requiem hangi amaçla bestelenen eserdir?', '["Düğün müziği","Askerî marş","Dans müziği","Ölüler için ayin müziği"]'::jsonb, 3, 'muzik'),
('Oratoryo ile opera arasındaki temel fark nedir?', '["Oratoryonun sahnelenmemesi","Oratoryonun sözsüz olması","Operanın korosuz olması","Operanın enstrümansız olması"]'::jsonb, 0, 'muzik'),
('Kantat türünün özelliği nedir?', '["Yalnız solo piyano olması","Solist, koro ve çalgı için yazılması","Sahnelenmesi","Doğaçlama olması"]'::jsonb, 1, 'muzik'),
('Madrigal hangi dönemin çok sesli vokal türüdür?', '["Romantik","Çağdaş","Rönesans","Klasik"]'::jsonb, 2, 'muzik'),
('Gregoryen ilahi hangi dokuyla söylenir?', '["Çok sesli","Enstrümantal","Ritimli","Tek sesli"]'::jsonb, 3, 'muzik'),
('Caz müziğinin doğduğu şehir hangisidir?', '["New Orleans","Chicago","New York","Detroit"]'::jsonb, 0, 'muzik'),
('Louis Armstrong hangi çalgıyla tanınır?', '["Saksofon","Trompet","Piyano","Bas"]'::jsonb, 1, 'muzik'),
('Miles Davis hangi çalgının cazdaki ustasıdır?', '["Gitar","Davul","Trompet","Klarnet"]'::jsonb, 2, 'muzik'),
('John Coltrane hangi çalgıyla tanınır?', '["Trompet","Piyano","Kontrbas","Saksofon"]'::jsonb, 3, 'muzik'),
('Swing dönemi hangi müzik türüne aittir?', '["Caz","Rock","Blues","Country"]'::jsonb, 0, 'muzik'),
('Bebop akımı hangi türün alt dalıdır?', '["Rock","Caz","Pop","Reggae"]'::jsonb, 1, 'muzik'),
('Rock and roll müziği hangi türlerin birleşiminden doğmuştur?', '["Caz ve opera","Klasik ve halk","Blues ve country","Reggae ve funk"]'::jsonb, 2, 'muzik'),
('Elvis Presley hangi müzik türüyle özdeşleşmiştir?', '["Caz","Opera","Reggae","Rock and roll"]'::jsonb, 3, 'muzik'),
('The Beatles hangi ülkeden çıkmıştır?', '["İngiltere","ABD","Avustralya","İrlanda"]'::jsonb, 0, 'muzik'),
('Bob Marley hangi müzik türüyle anılır?', '["Caz","Reggae","Blues","Country"]'::jsonb, 1, 'muzik'),
('Samba müziği hangi ülkeye özgüdür?', '["Arjantin","Meksika","Brezilya","Küba"]'::jsonb, 2, 'muzik'),
('Salsa müziğinin kökenleri hangi bölgeye dayanır?', '["İskandinavya","Balkanlar","Doğu Asya","Karayipler"]'::jsonb, 3, 'muzik'),
('Fado müziği hangi ülkeye aittir?', '["Portekiz","İspanya","İtalya","Yunanistan"]'::jsonb, 0, 'muzik'),
('Rebetiko müziği hangi ülkeyle özdeşleşmiştir?', '["İtalya","Yunanistan","Bulgaristan","Romanya"]'::jsonb, 1, 'muzik'),
('Country müziği hangi ülkede gelişmiştir?', '["Kanada","İngiltere","ABD","Avustralya"]'::jsonb, 2, 'muzik'),
('Hip hop müziğinde konuşur gibi söyleme biçimine ne denir?', '["Skat","Yodel","Falsetto","Rap"]'::jsonb, 3, 'muzik'),
('Skat söyleyiş tekniği hangi türde kullanılır?', '["Caz","Opera","Reggae","Country"]'::jsonb, 0, 'muzik'),
('Yodel söyleyiş tekniği hangi bölgeyle özdeşleşmiştir?', '["Karayipler","Alpler","Sahra","Sibirya"]'::jsonb, 1, 'muzik'),
('Falsetto ne anlama gelir?', '["Çok kalın ses","Fısıltıyla söyleme","Doğal sınırın üstünde ince ses","Sessiz söyleme"]'::jsonb, 2, 'muzik'),
('Soprano hangi ses grubudur?', '["En kalın kadın sesi","İnce erkek sesi","Kalın erkek sesi","En ince kadın sesi"]'::jsonb, 3, 'muzik'),
('Alto hangi ses grubudur?', '["Kalın kadın sesi","İnce kadın sesi","Kalın erkek sesi","Çocuk sesi"]'::jsonb, 0, 'muzik'),
('Tenor hangi ses grubudur?', '["Kalın erkek sesi","İnce erkek sesi","İnce kadın sesi","Orta kadın sesi"]'::jsonb, 1, 'muzik'),
('Bas hangi ses grubudur?', '["En ince erkek sesi","Kalın kadın sesi","En kalın erkek sesi","Orta ses"]'::jsonb, 2, 'muzik'),
('Bariton hangi ses aralığındadır?', '["Soprano ile alto arasında","Alto üstü","Bas altı","Tenor ile bas arasında"]'::jsonb, 3, 'muzik'),
('A cappella ne demektir?', '["Çalgısız, yalnız sesle","Yalnız çalgıyla","Doğaçlama","Çok hızlı"]'::jsonb, 0, 'muzik'),
('Bir koroda partileri birleştiren kişi kimdir?', '["Solist","Koro şefi","Konsermayster","Besteci"]'::jsonb, 1, 'muzik'),
('Konsermayster orkestrada hangi görevi üstlenir?', '["Vurmalıların başı","Şefin yardımcısı değil","Birinci kemanların başı","Koro şefi"]'::jsonb, 2, 'muzik'),
('Orkestranın akort için referans aldığı çalgı hangisidir?', '["Trombon","Timpani","Arp","Obua"]'::jsonb, 3, 'muzik'),
('La sesi akort standardında kaç hertz kabul edilir?', '["440 Hz","220 Hz","880 Hz","330 Hz"]'::jsonb, 0, 'muzik'),
('Sesin yüksekliğini (tiz-pes) belirleyen fiziksel büyüklük nedir?', '["Genlik","Frekans","Hız","Süre"]'::jsonb, 1, 'muzik'),
('Tını (renk) neyi ifade eder?', '["Sesin yüksekliğini","Sesin süresini","Sesin kendine özgü niteliğini","Sesin şiddetini"]'::jsonb, 2, 'muzik'),
('Rezonans olayı çalgılarda neyi sağlar?', '["Sesin sönmesini","Frekansın düşmesini","Tempo artışını","Sesin güçlenmesini"]'::jsonb, 3, 'muzik'),
('Gitarda ses gövdesinin işlevi nedir?', '["Sesi yankılayarak güçlendirmek","Teli germek","Perde belirlemek","Akort tutmak"]'::jsonb, 0, 'muzik'),
('Sentezleyici (synthesizer) neyi yapar?', '["Sesi yalnız kaydeder","Sesi elektronik olarak üretir","Notayı yazar","Tempoyu ölçer"]'::jsonb, 1, 'muzik'),
('MIDI protokolü ne aktarır?', '["Ses dalgasını","Video görüntüsünü","Nota ve performans verisini","Metin dosyasını"]'::jsonb, 2, 'muzik'),
('Stüdyoda ''miks'' aşamasında ne yapılır?', '["Şarkı bestelenir","Nota yazılır","Konser verilir","Kanallar dengelenip birleştirilir"]'::jsonb, 3, 'muzik'),
('Mastering aşamasının amacı nedir?', '["Yayına hazır son ses düzenlemesi","Şarkı sözü yazımı","Enstrüman kaydı","Klip çekimi"]'::jsonb, 0, 'muzik'),
('Akustik yalıtımın stüdyodaki amacı nedir?', '["Sesi yükseltmek","Dış sesleri engellemek","Tempoyu tutmak","Akordu korumak"]'::jsonb, 1, 'muzik'),
('Bir şarkının nakarat bölümü neyi ifade eder?', '["Giriş çalgısını","Sonu","Tekrarlanan ana bölümü","Solo bölümü"]'::jsonb, 2, 'muzik'),
('Şarkı sözü yazan kişiye ne ad verilir?', '["Aranjör","Şef","Prodüktör","Söz yazarı"]'::jsonb, 3, 'muzik'),
('Prodüktörün müzik üretimindeki rolü nedir?', '["Kaydın bütününü yönetmek","Yalnız çalmak","Yalnız söylemek","Bilet satmak"]'::jsonb, 0, 'muzik'),
('Türkiye''de Devlet Opera ve Balesi hangi alanda hizmet verir?', '["Sinema","Sahne sanatları","Resim","Edebiyat"]'::jsonb, 1, 'muzik'),
('Eurovision Şarkı Yarışması hangi kuruluş tarafından düzenlenir?', '["UNESCO","FIFA","Avrupa Yayın Birliği","Avrupa Konseyi"]'::jsonb, 2, 'muzik')
on conflict (soru) do nothing;
