-- Soru havuzu genişletme: cografya +85
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Türkiye''de kış yağışlarının baskın olduğu iklim tipi hangisidir?', '["Akdeniz iklimi","Karadeniz iklimi","Karasal iklim","Muson iklimi"]'::jsonb, 0, 'cografya'),
('Türkiye''de bağıl nemin en yüksek olduğu bölge hangisidir?', '["İç Anadolu","Karadeniz","Güneydoğu Anadolu","Doğu Anadolu"]'::jsonb, 1, 'cografya'),
('Türkiye''de don olaylarının en sık görüldüğü bölge hangisidir?', '["Akdeniz","Ege","Doğu Anadolu","Marmara"]'::jsonb, 2, 'cografya'),
('Türkiye''de tarımda vejetasyon süresi hangi bölgede en uzundur?', '["Doğu Anadolu","İç Anadolu","Doğu Karadeniz","Akdeniz"]'::jsonb, 3, 'cografya'),
('Türkiye''de ilk turfanda sebzeciliğin yapıldığı kıyı hangisidir?', '["Akdeniz","Karadeniz","Marmara","Doğu Anadolu"]'::jsonb, 0, 'cografya'),
('Türkiye''de üç tarafı denizle çevrili yarımadalardan biri hangisidir?', '["Ergene","Kapıdağ","Konya","Harran"]'::jsonb, 1, 'cografya'),
('Datça Yarımadası hangi ilimizdedir?', '["Antalya","Aydın","Muğla","İzmir"]'::jsonb, 2, 'cografya'),
('Biga Yarımadası hangi bölgemizdedir?', '["Ege","Karadeniz","Akdeniz","Marmara"]'::jsonb, 3, 'cografya'),
('Gelibolu Yarımadası hangi savaşla anılır?', '["Çanakkale Savaşları","Sakarya","Dumlupınar","Malazgirt"]'::jsonb, 0, 'cografya'),
('Saros Körfezi hangi denizde yer alır?', '["Karadeniz","Ege","Marmara","Akdeniz"]'::jsonb, 1, 'cografya'),
('Edremit Körfezi hangi denizdedir?', '["Akdeniz","Marmara","Ege","Karadeniz"]'::jsonb, 2, 'cografya'),
('İskenderun Körfezi hangi denizdedir?', '["Ege","Karadeniz","Marmara","Akdeniz"]'::jsonb, 3, 'cografya'),
('İzmit Körfezi hangi denizin uzantısıdır?', '["Marmara","Karadeniz","Ege","Akdeniz"]'::jsonb, 0, 'cografya'),
('Türkiye''de kıyı ile iç kesim arasındaki iklim farkının nedeni nedir?', '["Enlem farkı","Kıyı dağlarının engel oluşturması","Boylam farkı","Nüfus farkı"]'::jsonb, 1, 'cografya'),
('Karadeniz kıyısında kışların ılık geçmesinin nedeni nedir?', '["Yükselti","Enlem","Deniz etkisi","Rüzgâr yönü"]'::jsonb, 2, 'cografya'),
('Ege''de kıyıdan iç kesime doğru yağışın azalmasının nedeni nedir?', '["Enlem artışı","Toprak değişimi","Nüfus artışı","Denizellik etkisinin azalması"]'::jsonb, 3, 'cografya'),
('Türkiye''de tarımsal don riskinin yüksek olduğu bölge hangisidir?', '["İç ve Doğu Anadolu","Akdeniz kıyısı","Ege kıyısı","Güney Marmara"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en fazla tarım alanına sahip bölgesi hangisidir?', '["Doğu Karadeniz","İç Anadolu","Doğu Anadolu","Marmara"]'::jsonb, 1, 'cografya'),
('Türkiye''de ekili dikili alan oranı en düşük bölge hangisidir?', '["Marmara","Ege","Doğu Anadolu","Akdeniz"]'::jsonb, 2, 'cografya'),
('Türkiye''de sanayi bitkilerinden biri hangisidir?', '["Buğday","Arpa","Mercimek","Şeker pancarı"]'::jsonb, 3, 'cografya'),
('Türkiye''de yağlı tohum bitkilerinden biri hangisidir?', '["Ayçiçeği","Pirinç","Nohut","Arpa"]'::jsonb, 0, 'cografya'),
('Türkiye''de lif bitkisi olarak öne çıkan ürün hangisidir?', '["Şeker pancarı","Pamuk","Çay","Fındık"]'::jsonb, 1, 'cografya'),
('Çay bitkisinin yetişme koşulu nedir?', '["Kurak iklim","Tuzlu toprak","Bol yağış ve asitli toprak","Soğuk step"]'::jsonb, 2, 'cografya'),
('Fındığın yetişme koşulu nedir?', '["Çöl iklimi","Tundra","Sert karasal","Nemli ılıman iklim"]'::jsonb, 3, 'cografya'),
('Zeytinin yetişme sınırı Türkiye''de neyi gösterir?', '["Akdeniz ikliminin etki alanını","Karasal iklimi","Muson iklimini","Tundra sınırını"]'::jsonb, 0, 'cografya'),
('Turunçgillerin yetişme koşulu nedir?', '["Soğuk karasal iklim","Kışı ılık geçen kıyı iklimi","Kutup iklimi","Yüksek plato"]'::jsonb, 1, 'cografya'),
('Türkiye''de tarımsal üretimi sınırlayan başlıca doğal etken nedir?', '["Toprak fazlalığı","Nüfus yoğunluğu","Su yetersizliği","Yol azlığı"]'::jsonb, 2, 'cografya'),
('Toprak koruma tedbirlerinden biri hangisidir?', '["Aşırı sürüm","Anız yakma","Aşırı otlatma","Nöbetleşe ekim"]'::jsonb, 3, 'cografya'),
('Anız yakmanın zararı nedir?', '["Toprak canlılarını yok etmesi","Toprağı zenginleştirmesi","Suyu artırması","Verimi artırması"]'::jsonb, 0, 'cografya'),
('Türkiye''de tarım sigortasının amacı nedir?', '["Ürün fiyatını belirlemek","Doğal afet zararını karşılamak","Vergi almak","Tohum satmak"]'::jsonb, 1, 'cografya'),
('Kooperatifleşmenin çiftçiye yararı nedir?', '["Vergi muafiyeti","Toprak bağışı","Girdi ve pazarlamada güç birliği","Su hakkı"]'::jsonb, 2, 'cografya'),
('Tarımsal destekleme politikasının amacı nedir?', '["Üretimi azaltmak","İthalatı artırmak","Fiyatı yükseltmek","Üretimi sürdürülebilir kılmak"]'::jsonb, 3, 'cografya'),
('Bir bölgede sanayinin gelişmesi nüfusu nasıl etkiler?', '["Göçle nüfusu artırır","Nüfusu azaltır","Etkilemez","Doğumu azaltır"]'::jsonb, 0, 'cografya'),
('Türkiye''de iç göçün yönü genelde nasıldır?', '["Batıdan doğuya","Doğudan batıya ve kıyılara","Kıyıdan içeriye","Kuzeyden güneye yalnızca"]'::jsonb, 1, 'cografya'),
('Mevsimlik tarım işçiliğinin en yoğun olduğu bölge hangisidir?', '["Doğu Karadeniz","Trakya","Çukurova","Doğu Anadolu"]'::jsonb, 2, 'cografya'),
('Nüfus sayımının temel amacı nedir?', '["Vergi cezası kesmek","Askerlik yapmak","Seçim yapmak","Planlamaya veri sağlamak"]'::jsonb, 3, 'cografya'),
('Adrese dayalı nüfus kayıt sistemi neyi kolaylaştırır?', '["Güncel nüfus verisine erişimi","Vergi toplamayı yalnızca","Harita çizmeyi","Yol yapmayı"]'::jsonb, 0, 'cografya'),
('Bir bölgede bağımlı nüfus oranının yüksekliği neyi gösterir?', '["İşsizliğin sıfır olduğunu","Çalışan başına yükün fazlalığını","Gelirin yüksekliğini","Göç almadığını"]'::jsonb, 1, 'cografya'),
('Kentsel nüfusun kırsal nüfusu geçmesi neyi gösterir?', '["Tarımın büyüdüğünü","Nüfusun azaldığını","Ekonomik yapının değiştiğini","İklimin değiştiğini"]'::jsonb, 2, 'cografya'),
('Bir haritada ''lejant'' ne gösterir?', '["Ölçeği","Başlığı","Kuzey yönünü","Sembollerin anlamlarını"]'::jsonb, 3, 'cografya'),
('Harita ölçeği 1/25.000 ise 1 cm kaç metredir?', '["250 metre","25 metre","2500 metre","25 kilometre"]'::jsonb, 0, 'cografya'),
('Harita ölçeği 1/100.000 ise 1 cm kaç kilometredir?', '["10 kilometre","1 kilometre","100 metre","10 metre"]'::jsonb, 1, 'cografya'),
('Bir haritada gerçek alan hesaplanırken ölçek nasıl kullanılır?', '["Ölçek aynen kullanılır","Ölçek ikiye bölünür","Ölçeğin karesi alınır","Ölçek toplanır"]'::jsonb, 2, 'cografya'),
('Eş yükselti eğrilerinin iç içe kapalı olması neyi gösterir?', '["Düzlüğü","Nehri","Sınırı","Tepe veya çukuru"]'::jsonb, 3, 'cografya'),
('Profil çıkarmak neyi gösterir?', '["Arazinin yandan kesitini","Nüfus dağılımını","Yağış miktarını","Bitki örtüsünü"]'::jsonb, 0, 'cografya'),
('Topoğrafik haritada mavi renk neyi gösterir?', '["Ormanları","Su öğelerini","Yolları","Yerleşimleri"]'::jsonb, 1, 'cografya'),
('Bir haritada ''eğim'' nasıl anlaşılır?', '["Renk sayısından","Başlıktan","Eş yükselti eğrilerinin sıklığından","Lejanttan"]'::jsonb, 2, 'cografya'),
('Coğrafi koordinat sisteminde enlem hangi aralıktadır?', '["0-180 derece","0-360 derece","0-45 derece","0-90 derece"]'::jsonb, 3, 'cografya'),
('Boylam hangi aralıkta ifade edilir?', '["0-180 derece","0-90 derece","0-360 derece","0-60 derece"]'::jsonb, 0, 'cografya'),
('İki meridyen arası mesafe Ekvator''da yaklaşık kaç kilometredir?', '["11 kilometre","111 kilometre","1110 kilometre","50 kilometre"]'::jsonb, 1, 'cografya'),
('Kutuplara gidildikçe meridyenler arası mesafe nasıl değişir?', '["Artar","Sabit kalır","Azalır","İkiye katlanır"]'::jsonb, 2, 'cografya'),
('Bir yerin yerel saati neye göre hesaplanır?', '["Enlem derecesine göre","Yükseltiye göre","İklime göre","Boylam derecesine göre"]'::jsonb, 3, 'cografya'),
('Uluslararası saat dilimleri kaç derecelik aralıklarla belirlenmiştir?', '["15 derece","5 derece","30 derece","45 derece"]'::jsonb, 0, 'cografya'),
('Yaz saati uygulamasının amacı nedir?', '["Saat farkını kaldırmak","Gün ışığından daha çok yararlanmak","Enerji üretmek","Takvimi değiştirmek"]'::jsonb, 1, 'cografya'),
('Çevresel etki değerlendirmesinin amacı nedir?', '["Maliyeti düşürmek","İnşaatı hızlandırmak","Projenin çevreye etkisini önceden ölçmek","Vergi almak"]'::jsonb, 2, 'cografya'),
('Doğal sit alanı ile arkeolojik sit alanı arasındaki fark nedir?', '["Alanın büyüklüğü","Nüfus sayısı","İklim","Korunan değerin türü"]'::jsonb, 3, 'cografya'),
('Biyosfer rezervi kavramı neyi ifade eder?', '["Korumayla kullanımı birleştiren alan","Yalnız yasak bölge","Sanayi bölgesi","Askerî alan"]'::jsonb, 0, 'cografya'),
('Ekolojik koridorun işlevi nedir?', '["Yol açmak","Yaşam alanlarını birbirine bağlamak","Sınır çizmek","Baraj yapmak"]'::jsonb, 1, 'cografya'),
('Yaban hayatı koruma sahasının amacı nedir?', '["Avlanmayı artırmak","Turizm geliri","Türlerin yaşam alanını güvenceye almak","Maden çıkarmak"]'::jsonb, 2, 'cografya'),
('Av yasağı dönemlerinin gerekçesi nedir?', '["Turizmi artırmak","Silah satışını azaltmak","Yolları boşaltmak","Üreme dönemini korumak"]'::jsonb, 3, 'cografya'),
('İstilacı tür ne demektir?', '["Yeni ortamda dengeyi bozan yabancı tür","Yerli tür","Nesli tükenen tür","Evcil tür"]'::jsonb, 0, 'cografya'),
('Balık geçitlerinin barajlardaki işlevi nedir?', '["Su tutmak","Balıkların göçünü sürdürebilmesi","Enerji üretmek","Sulama yapmak"]'::jsonb, 1, 'cografya'),
('Doğal denge kavramı neyi ifade eder?', '["İklim ortalamasını","Nüfus sayısını","Ekosistemdeki karşılıklı düzeni","Ürün fiyatını"]'::jsonb, 2, 'cografya'),
('Kirlilik yükünün taşınmasında en etkili ortam hangisidir?', '["Kayaçlar","Buzullar","Çöl kumu","Su ve hava"]'::jsonb, 3, 'cografya'),
('Toprak kirliliğinin başlıca kaynağı nedir?', '["Sanayi atığı ve tarım kimyasalları","Yağmur","Rüzgâr","Kar"]'::jsonb, 0, 'cografya'),
('Gürültü kirliliğinin insan üzerindeki etkisi nedir?', '["Görme kaybı","Stres ve işitme sorunları","Kemik erimesi","Diş çürüğü"]'::jsonb, 1, 'cografya'),
('Işık kirliliği hangi alanı olumsuz etkiler?', '["Toprak verimini","Su kalitesini","Gökyüzü gözlemi ve gece canlıları","Rüzgâr hızını"]'::jsonb, 2, 'cografya'),
('Bir kentte hava kalitesi izleme istasyonları neyi ölçer?', '["Nüfusu","Trafik cezasını","Yağışı yalnızca","Kirletici madde derişimlerini"]'::jsonb, 3, 'cografya'),
('Partikül madde (PM) neden sağlık riski taşır?', '["Solunumla derinlere ulaşması","Renk vermesi","Ses çıkarması","Ağır olması"]'::jsonb, 0, 'cografya'),
('Sanayide baca filtrelerinin işlevi nedir?', '["Isı üretmek","Kirleticileri tutmak","Enerji sağlamak","Su vermek"]'::jsonb, 1, 'cografya'),
('Emisyon standardı ne belirler?', '["Üretim miktarını","Çalışan sayısını","İzin verilen kirletici salım sınırını","Vergi oranını"]'::jsonb, 2, 'cografya'),
('Karbon ticareti sisteminin mantığı nedir?', '["Karbonun depolanması","Ormanın satılması","Enerji üretimi","Salım hakkının alınıp satılması"]'::jsonb, 3, 'cografya'),
('Ağaçlandırma kampanyalarının iklime katkısı nedir?', '["Karbon tutulmasını artırmak","Yağışı durdurmak","Sıcaklığı artırmak","Rüzgârı kesmek"]'::jsonb, 0, 'cografya'),
('Kentsel tarım (bahçe) uygulamasının yararı nedir?', '["Trafiği artırması","Yerel üretim ve yeşil alan sağlaması","Isıyı artırması","Suyu tüketmesi"]'::jsonb, 1, 'cografya'),
('Yeşil çatı uygulamasının kentsel yararı nedir?', '["Bina yüksekliği artışı","Trafik azalması","Isı yalıtımı ve yağmur suyu tutma","Nüfus artışı"]'::jsonb, 2, 'cografya'),
('Bisiklet yollarının kentsel yararı nedir?', '["Yol genişliğini artırması","Otopark artırması","Hız artırması","Emisyon ve trafiği azaltması"]'::jsonb, 3, 'cografya'),
('Toplu taşımada raylı sistemin avantajı nedir?', '["Yüksek kapasite ve düzenli sefer","Esnek güzergâh","Düşük kapasite","Yol gerektirmemesi"]'::jsonb, 0, 'cografya'),
('Bir kentin ''trafik yoğunluğu'' neyle azaltılabilir?', '["Yol genişletmeyle yalnızca","Toplu taşıma ve yaya önceliğiyle","Otopark azaltmayla","Hız artırmayla"]'::jsonb, 1, 'cografya'),
('Akıllı şehir uygulamalarının amacı nedir?', '["Nüfusu artırmak","Yapılaşmayı artırmak","Kaynakları verimli yönetmek","Trafiği artırmak"]'::jsonb, 2, 'cografya'),
('Kent ekonomisinde ''hizmet sektörü'' hangi işleri kapsar?', '["Tarım ve hayvancılık","Madencilik","Balıkçılık","Ticaret, eğitim, sağlık, ulaşım"]'::jsonb, 3, 'cografya'),
('Turizm sezonunun uzatılması neyi hedefler?', '["İstihdam ve geliri sürekli kılmak","Nüfusu azaltmak","Yol yapmak","Vergi artırmak"]'::jsonb, 0, 'cografya'),
('Bir yörenin ''taşıma kapasitesi'' turizmde neyi anlatır?', '["Otel sayısını","Kaldırabileceği ziyaretçi sayısını","Yol uzunluğunu","Bilet fiyatını"]'::jsonb, 1, 'cografya'),
('Aşırı turizmin (overtourism) sonucu nedir?', '["Gelirin azalması","Ziyaretçi azalması","Doğal ve kültürel dokunun yıpranması","Altyapının bozulmaması"]'::jsonb, 2, 'cografya'),
('Kırsal turizmin yerel halka yararı nedir?', '["Tarımın bitmesi","Nüfusun azalması","Toprak kaybı","Ek gelir ve göçün azalması"]'::jsonb, 3, 'cografya'),
('Coğrafi işaretli ürünlerin turizme katkısı nedir?', '["Yöreyi tanıtıp ziyaretçi çekmesi","Fiyatı düşürmesi","Üretimi azaltması","İhracatı engellemesi"]'::jsonb, 0, 'cografya')
on conflict (soru) do nothing;
