-- Soru havuzu genişletme: sinema +112
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Sinematograf aygıtını geliştiren kardeşler kimlerdir?', '["Lumiere Kardeşler","Warner Kardeşler","Wright Kardeşler","Grimm Kardeşler"]'::jsonb, 0, 'sinema'),
('İlk halka açık film gösterimi hangi şehirde yapılmıştır?', '["Londra","Paris","New York","Berlin"]'::jsonb, 1, 'sinema'),
('Sessiz sinemanın en tanınmış komedyeni kimdir?', '["Marlon Brando","James Dean","Charlie Chaplin","Humphrey Bogart"]'::jsonb, 2, 'sinema'),
('Georges Melies sinemaya hangi katkısıyla anılır?', '["Belgesel sinema","Sesli film","Renkli film","Özel efekt ve fantastik anlatım"]'::jsonb, 3, 'sinema'),
('Alman Dışavurumcu sinemasının simge filmi hangisidir?', '["Dr. Caligari''nin Muayenehanesi","Bisiklet Hırsızları","Vatandaş Kane","Serseri Aşıklar"]'::jsonb, 0, 'sinema'),
('İtalyan Yeni Gerçekçiliği hangi dönemde doğmuştur?', '["Birinci Dünya Savaşı öncesi","İkinci Dünya Savaşı sonrası","1970''ler","1990''lar"]'::jsonb, 1, 'sinema'),
('İtalyan Yeni Gerçekçiliğinin ayırt edici özelliği nedir?', '["Stüdyo dekorları","Fantastik konular","Sokakta, amatör oyuncularla çekim","Yoğun efekt kullanımı"]'::jsonb, 2, 'sinema'),
('Bisiklet Hırsızları filminin yönetmeni kimdir?', '["Federico Fellini","Roberto Rossellini","Luchino Visconti","Vittorio De Sica"]'::jsonb, 3, 'sinema'),
('Fransız Yeni Dalga akımı hangi dergiden beslenmiştir?', '["Cahiers du Cinema","Sight and Sound","Variety","Positif"]'::jsonb, 0, 'sinema'),
('Fransız Yeni Dalga''nın öncü yönetmenlerinden biri kimdir?', '["Sergio Leone","Jean-Luc Godard","Stanley Kubrick","Akira Kurosawa"]'::jsonb, 1, 'sinema'),
('400 Darbe filminin yönetmeni kimdir?', '["Godard","Chabrol","François Truffaut","Rohmer"]'::jsonb, 2, 'sinema'),
('Alfred Hitchcock hangi türün ustası sayılır?', '["Müzikal","Western","Belgesel","Gerilim"]'::jsonb, 3, 'sinema'),
('Sergio Leone hangi alt türle özdeşleşmiştir?', '["Spagetti western","Film noir","Müzikal","Bilim kurgu"]'::jsonb, 0, 'sinema'),
('Andrei Tarkovski hangi ülkenin yönetmenidir?', '["Polonya","Rusya","Macaristan","Çekya"]'::jsonb, 1, 'sinema'),
('Luis Bunuel hangi akımla ilişkilendirilir?', '["Yeni gerçekçilik","Dogma 95","Gerçeküstücülük","Yeni Hollywood"]'::jsonb, 2, 'sinema'),
('Taksi Şoförü filminin yönetmeni kimdir?', '["Coppola","Spielberg","Lucas","Martin Scorsese"]'::jsonb, 3, 'sinema'),
('Jaws ve E.T. filmlerinin yönetmeni kimdir?', '["Steven Spielberg","George Lucas","Robert Zemeckis","John Carpenter"]'::jsonb, 0, 'sinema'),
('Blade Runner filminin yönetmeni kimdir?', '["James Cameron","Ridley Scott","David Lynch","Paul Verhoeven"]'::jsonb, 1, 'sinema'),
('Dövüş Kulübü filminin yönetmeni kimdir?', '["Christopher Nolan","Darren Aronofsky","David Fincher","Spike Jonze"]'::jsonb, 2, 'sinema'),
('Matrix filminin yönetmenleri kimlerdir?', '["Coen Kardeşler","Russo Kardeşler","Farrelly Kardeşler","Wachowski Kardeşler"]'::jsonb, 3, 'sinema'),
('Coen Kardeşler hangi tarzda film yapmasıyla bilinir?', '["Kara mizah","Müzikal","Belgesel","Çizgi film"]'::jsonb, 0, 'sinema'),
('Pedro Almodovar hangi ülkenin yönetmenidir?', '["Meksika","İspanya","Arjantin","Portekiz"]'::jsonb, 1, 'sinema'),
('Wong Kar-wai hangi bölgenin yönetmenidir?', '["Japonya","Güney Kore","Hong Kong","Tayvan"]'::jsonb, 2, 'sinema'),
('Parazit filminin yönetmeni kimdir?', '["Park Chan-wook","Kim Ki-duk","Lee Chang-dong","Bong Joon-ho"]'::jsonb, 3, 'sinema'),
('Dogma 95 akımı hangi ülkeden çıkmıştır?', '["Danimarka","İsveç","Hollanda","Belçika"]'::jsonb, 0, 'sinema'),
('Dogma 95 manifestosu neyi reddeder?', '["Doğal ışığı","Yapay efekt ve stüdyo aydınlatmasını","El kamerasını","Gerçek mekânları"]'::jsonb, 1, 'sinema'),
('Bollywood hangi ülkenin sinema endüstrisidir?', '["Pakistan","Nijerya","Hindistan","Endonezya"]'::jsonb, 2, 'sinema'),
('Nollywood hangi ülkenin sinemasını anlatır?', '["Gana","Kenya","Mısır","Nijerya"]'::jsonb, 3, 'sinema'),
('Film noir türünün belirgin görsel özelliği nedir?', '["Sert kontrastlı karanlık aydınlatma","Parlak renkler","Doğal ışık","Geniş açı"]'::jsonb, 0, 'sinema'),
('Western türünün geçtiği tipik coğrafya neresidir?', '["Sibirya","Amerikan batısı","Amazon","Sahra"]'::jsonb, 1, 'sinema'),
('Kısa film süre olarak genelde neyi aşmaz?', '["İki saat","Üç saat","Kırk dakika","Doksan dakika"]'::jsonb, 2, 'sinema'),
('Animasyon filmde hareket nasıl yaratılır?', '["Tek kare çekerek","Ses ekleyerek","Renk vererek","Ardışık kareleri sıralayarak"]'::jsonb, 3, 'sinema'),
('Stop motion tekniğinde ne yapılır?', '["Nesneler kare kare oynatılıp çekilir","Bilgisayarda çizilir","Canlı oyuncu kullanılır","Ses kaydedilir"]'::jsonb, 0, 'sinema'),
('Rotoskopi tekniği neye dayanır?', '["Kil model kullanımı","Gerçek görüntü üzerine çizim","Yeşil perde","Ses senkronu"]'::jsonb, 1, 'sinema'),
('Pixar stüdyosunun ilk uzun metraj animasyonu hangisidir?', '["Aslan Kral","Shrek","Oyuncak Hikayesi","Buz Devri"]'::jsonb, 2, 'sinema'),
('Hayao Miyazaki hangi alanda tanınır?', '["Belgesel","Müzikal","Kısa film","Animasyon yönetmenliği"]'::jsonb, 3, 'sinema'),
('Sinemada ''plan'' terimi neyi ifade eder?', '["Kesintisiz çekilen görüntü parçası","Senaryo bölümü","Ses kaydı","Kurgu masası"]'::jsonb, 0, 'sinema'),
('Sekans terimi neyi anlatır?', '["Tek kare","Anlamlı bütün oluşturan sahneler dizisi","Ses efekti","Işık düzeni"]'::jsonb, 1, 'sinema'),
('Yakın plan (close-up) hangi amaçla kullanılır?', '["Mekânı tanıtmak","Kalabalığı göstermek","Duyguyu vurgulamak","Zaman geçişi vermek"]'::jsonb, 2, 'sinema'),
('Kuşbakışı çekim neyi sağlar?', '["Alttan güçlü görünüm","Yakın duygu","Yan profil","Yukarıdan geniş bakış"]'::jsonb, 3, 'sinema'),
('Alt açı (low angle) çekim karakteri nasıl gösterir?', '["Güçlü ve heybetli","Zayıf ve küçük","Uzak","Belirsiz"]'::jsonb, 0, 'sinema'),
('Travelling çekim nedir?', '["Kameranın sabit durması","Kameranın raylı biçimde hareketi","Objektif değişimi","Ses kaydı"]'::jsonb, 1, 'sinema'),
('Zoom ile travelling arasındaki fark nedir?', '["Zoom''da kamera hareket eder","İkisi aynıdır","Zoom''da kamera yerinde kalır","Travelling optiktir"]'::jsonb, 2, 'sinema'),
('Steadicam aygıtı ne sağlar?', '["Havadan çekim","Su altı çekim","Gece çekim","Yürürken titremesiz çekim"]'::jsonb, 3, 'sinema'),
('Kurgu (montaj) aşamasında ne yapılır?', '["Çekimler sıralanıp birleştirilir","Senaryo yazılır","Oyuncu seçilir","Mekân bulunur"]'::jsonb, 0, 'sinema'),
('Sovyet kurgu kuramının öncüsü kimdir?', '["D.W. Griffith","Sergey Eisenstein","Orson Welles","Jean Renoir"]'::jsonb, 1, 'sinema'),
('Kuleşov etkisi neyi gösterir?', '["Sesin görüntüyü bozmasını","Işığın rengi değiştirmesini","Yan yana görüntülerin anlam yaratması","Kameranın titremesini"]'::jsonb, 2, 'sinema'),
('Jump cut (sıçramalı kesme) etkisi nedir?', '["Akıcı geçiş","Yavaşlama","Renk değişimi","Zamanda kopukluk hissi"]'::jsonb, 3, 'sinema'),
('Cross cutting (çapraz kurgu) neyi anlatır?', '["İki olayın dönüşümlü gösterimi","Geriye dönüş","Yavaş çekim","Sabit plan"]'::jsonb, 0, 'sinema'),
('Flashback tekniği neyi sağlar?', '["Geleceğe atlama","Geçmişe dönüş","Yavaşlatma","Hızlandırma"]'::jsonb, 1, 'sinema'),
('Sinemada ''mizansen'' neyi kapsar?', '["Yalnız kurguyu","Yalnız sesi","Kadraj içindeki her şeyin düzenlenmesi","Yalnız senaryoyu"]'::jsonb, 2, 'sinema'),
('Storyboard neye yarar?', '["Bütçe hazırlamak","Bilet satmak","Ses kaydetmek","Çekimleri önceden çizerek planlamak"]'::jsonb, 3, 'sinema'),
('Senaryoda ''logline'' nedir?', '["Filmin tek cümlelik özeti","Diyalog listesi","Çekim planı","Oyuncu listesi"]'::jsonb, 0, 'sinema'),
('Figüran ile dublör arasındaki fark nedir?', '["Figüranın baş rol olması","Dublörün tehlikeli sahneleri yapması","İkisinin aynı olması","Dublörün seslendirmesi"]'::jsonb, 1, 'sinema'),
('Seslendirme (dublaj) hangi aşamada yapılır?', '["Çekimden önce hep","Kurgudan önce hep","Çekim sonrasında","Vizyondan sonra"]'::jsonb, 2, 'sinema'),
('Foley sanatçısı ne üretir?', '["Film müziğini","Diyalogları","Görsel efektleri","Filmdeki günlük ses efektlerini"]'::jsonb, 3, 'sinema'),
('Film müziğinin genel adı nedir?', '["Skor","Foley","Mix","Sekans"]'::jsonb, 0, 'sinema'),
('Ennio Morricone hangi alanda tanınır?', '["Yönetmenlik","Film müziği","Oyunculuk","Kurgu"]'::jsonb, 1, 'sinema'),
('John Williams hangi alanda ödüller kazanmıştır?', '["Senaryo","Kostüm","Film müziği","Kurgu"]'::jsonb, 2, 'sinema'),
('Motion capture tekniği ne yapar?', '["Sesi kaydeder","Işık ölçer","Renk dengeler","Oyuncunun hareketini sayısallaştırır"]'::jsonb, 3, 'sinema'),
('Renk düzenleme (color grading) neyi belirler?', '["Filmin görsel atmosferini","Ses düzeyini","Kurgu hızını","Oyuncu seçimini"]'::jsonb, 0, 'sinema'),
('Alan derinliği neyi ifade eder?', '["Ekran genişliğini","Netliğin kapsadığı derinlik aralığını","Ses derinliğini","Film süresini"]'::jsonb, 1, 'sinema'),
('Sığ alan derinliği hangi etkiyi yaratır?', '["Her yerin net olması","Renklerin solması","Arka planın bulanıklaşması","Sesin azalması"]'::jsonb, 2, 'sinema'),
('Diyafram açıklığının artması görüntüye ne yapar?', '["Işığı azaltır","Rengi değiştirir","Sesi artırır","Daha çok ışık girmesini sağlar"]'::jsonb, 3, 'sinema'),
('Kare hızı (fps) neyi belirtir?', '["Saniyedeki görüntü sayısını","Ses kalitesini","Çözünürlüğü","Film süresini"]'::jsonb, 0, 'sinema'),
('Sinemada standart kare hızı kaçtır?', '["12","24","60","100"]'::jsonb, 1, 'sinema'),
('IMAX formatının ayırt edici özelliği nedir?', '["Sessiz gösterim","Siyah beyaz olması","Çok büyük perde ve yüksek çözünürlük","Kısa süresi"]'::jsonb, 2, 'sinema'),
('Türk sinemasının ilk filmi olarak anılan yapım hangisidir?', '["Vurun Kahpeye","Susuz Yaz","Sürü","Ayastefanos Rus Abidesi''nin Yıkılışı"]'::jsonb, 3, 'sinema'),
('Yeşilçam dönemi hangi alanı tanımlar?', '["Türk sinemasının popüler dönemi","Bir yayınevi","Bir tiyatro","Bir müzik akımı"]'::jsonb, 0, 'sinema'),
('Susuz Yaz filminin yönetmeni kimdir?', '["Ömer Lütfi Akad","Metin Erksan","Atıf Yılmaz","Halit Refiğ"]'::jsonb, 1, 'sinema'),
('Susuz Yaz hangi festivalde büyük ödül kazanmıştır?', '["Cannes","Venedik","Berlin Film Festivali","Oscar"]'::jsonb, 2, 'sinema'),
('Yol filminin Cannes''da kazandığı ödül hangisidir?', '["Altın Ayı","Altın Aslan","Oscar","Altın Palmiye"]'::jsonb, 3, 'sinema'),
('Yılmaz Güney hangi alanlarda üretmiştir?', '["Oyunculuk, yönetmenlik, senaryo","Yalnız oyunculuk","Yalnız yapımcılık","Yalnız kurgu"]'::jsonb, 0, 'sinema'),
('Sürü filminin senaryosunu kim yazmıştır?', '["Zeki Demirkubuz","Yılmaz Güney","Nuri Bilge Ceylan","Şerif Gören"]'::jsonb, 1, 'sinema'),
('Nuri Bilge Ceylan''ın Cannes''da Altın Palmiye kazanan filmi hangisidir?', '["Uzak","Üç Maymun","Kış Uykusu","Ahlat Ağacı"]'::jsonb, 2, 'sinema'),
('Uzak filmi Cannes''da hangi ödülü kazanmıştır?', '["Altın Palmiye","Altın Ayı","Altın Aslan","Büyük Ödül"]'::jsonb, 3, 'sinema'),
('Zeki Demirkubuz sinemasının belirgin teması nedir?', '["Suçluluk ve bunalım","Fantastik macera","Müzikal komedi","Savaş"]'::jsonb, 0, 'sinema'),
('Reha Erdem hangi alanda tanınır?', '["Oyunculuk","Yönetmenlik","Kurgu","Görüntü yönetmenliği"]'::jsonb, 1, 'sinema'),
('Türkiye''nin en uzun soluklu sinema festivali hangisidir?', '["İstanbul Film Festivali","Ankara Film Festivali","Antalya Altın Portakal","Adana Altın Koza"]'::jsonb, 2, 'sinema'),
('Altın Portakal ödülü hangi şehirde verilir?', '["İstanbul","İzmir","Adana","Antalya"]'::jsonb, 3, 'sinema'),
('Sundance Film Festivali hangi tür sinemaya odaklanır?', '["Bağımsız sinema","Gişe filmleri","Belgesel dışı","Animasyon dışı"]'::jsonb, 0, 'sinema'),
('Oscar ödüllerini hangi kurum verir?', '["Cannes Kurulu","Sinema Sanatları Akademisi","BAFTA","Altın Küre Derneği"]'::jsonb, 1, 'sinema'),
('BAFTA ödülleri hangi ülkenin sinema ödülleridir?', '["Fransa","Almanya","İngiltere","İtalya"]'::jsonb, 2, 'sinema'),
('Sezar (Cesar) ödülleri hangi ülkeye aittir?', '["İspanya","İtalya","Belçika","Fransa"]'::jsonb, 3, 'sinema'),
('Altın Küre ödüllerini hangi topluluk verir?', '["Hollywood Yabancı Basın Birliği","Akademi","BAFTA","Cannes jürisi"]'::jsonb, 0, 'sinema'),
('Bir filmin ''gişe'' başarısı neyi ölçer?', '["Eleştirmen puanını","Bilet gelirini","Ödül sayısını","Süresini"]'::jsonb, 1, 'sinema'),
('Bağımsız sinema kavramı neyi vurgular?', '["Yüksek bütçeyi","Yıldız oyuncuları","Büyük stüdyo dışında üretimi","Geniş dağıtımı"]'::jsonb, 2, 'sinema'),
('Vizyon terimi sinemada ne anlama gelir?', '["Filmin çekilmesi","Filmin kurgulanması","Senaryonun yazılması","Filmin salonlarda gösterime girmesi"]'::jsonb, 3, 'sinema'),
('Fragman (trailer) hangi amaçla hazırlanır?', '["Filmi tanıtmak","Filmi özetlemek","Kurguyu bitirmek","Sesi düzeltmek"]'::jsonb, 0, 'sinema'),
('Bir filmin ''remake'' olması ne demektir?', '["Devam filmi olması","Yeniden çevrilmiş olması","Ön hikâye olması","Belgesel olması"]'::jsonb, 1, 'sinema'),
('Prequel terimi neyi anlatır?', '["Devamını anlatan film","Yeniden çekim","Öncesini anlatan film","Uyarlama"]'::jsonb, 2, 'sinema'),
('Spin-off terimi neyi ifade eder?', '["Yeniden çekim","Belgesel","Kısa film","Yan karakter üzerinden türetilen yapım"]'::jsonb, 3, 'sinema'),
('Uyarlama (adaptasyon) filmi neye dayanır?', '["Başka bir esere","Doğaçlamaya","Belgesel kayda","Reklama"]'::jsonb, 0, 'sinema'),
('Sinemada ''MacGuffin'' kavramı neyi anlatır?', '["Baş karakteri","Olayı başlatan ama önemsiz nesne","Filmin sonunu","Ses efektini"]'::jsonb, 1, 'sinema'),
('Sinemada ''dördüncü duvarı yıkmak'' ne demektir?', '["Dekorun yıkılması","Sesin kesilmesi","Karakterin izleyiciye seslenmesi","Kurgunun bozulması"]'::jsonb, 2, 'sinema'),
('Belgeselde ''talking head'' ne anlama gelir?', '["Arşiv görüntüsü","Canlandırma","Dış ses","Konuşan kişinin sabit çekimi"]'::jsonb, 3, 'sinema'),
('Dış ses (voice-over) neyi sağlar?', '["Görüntü dışından anlatım","Diyaloğu bastırmak","Müziği artırmak","Efekt eklemek"]'::jsonb, 0, 'sinema'),
('Sinemada ''kamera arkası'' terimi neyi kapsar?', '["Fragmanı","Çekim sürecinin görüntülenmesi","Afişi","Jeneriği"]'::jsonb, 1, 'sinema'),
('Jenerik neyi gösterir?', '["Filmin özetini","Bilet fiyatını","Emeği geçenlerin listesini","Gösterim saatini"]'::jsonb, 2, 'sinema'),
('Sinemada ''sansür'' uygulamasının amacı olarak neye başvurulur?', '["Bütçenin artırılmasına","Kurgunun hızlanmasına","Ses düzeyine","İçeriğin sınırlanmasına"]'::jsonb, 3, 'sinema'),
('Yaş sınırı işaretleri neyi belirtir?', '["İzleyici uygunluğunu","Film süresini","Bilet fiyatını","Ödül sayısını"]'::jsonb, 0, 'sinema'),
('Sinemada 3B (üç boyut) etkisi nasıl elde edilir?', '["Renk artırımıyla","İki görüntünün gözlere ayrı verilmesiyle","Ses yükseltimiyle","Kare hızıyla"]'::jsonb, 1, 'sinema'),
('Sinemaskop formatı neyi değiştirmiştir?', '["Ses sistemini","Kare hızını","Perdenin en-boy oranını","Film uzunluğunu"]'::jsonb, 2, 'sinema'),
('Sinemada ''ışık yönetmeni'' hangi ekiple çalışır?', '["Kurgu ekibiyle","Kostüm ekibiyle","Yapım ekibiyle","Görüntü yönetmeni ekibiyle"]'::jsonb, 3, 'sinema'),
('Sanat yönetmeninin sorumluluğu nedir?', '["Dekor ve görsel tasarım","Ses kaydı","Kurgu","Dağıtım"]'::jsonb, 0, 'sinema'),
('Kostüm tasarımcısının işlevi nedir?', '["Işığı ayarlamak","Karakterlerin giysilerini kurgulamak","Kamerayı taşımak","Senaryo yazmak"]'::jsonb, 1, 'sinema'),
('Yapımcının filmdeki temel rolü nedir?', '["Kamera kullanımı","Oyunculuk","Finansman ve süreç yönetimi","Kurgu"]'::jsonb, 2, 'sinema'),
('Ko-prodüksiyon ne anlama gelir?', '["Tek kişilik yapım","Reklam filmi","Kısa film","Birden çok ülkenin ortak yapımı"]'::jsonb, 3, 'sinema'),
('Festival ''seçki''si neyi ifade eder?', '["Gösterilecek filmlerin listesi","Jüri üyeleri","Ödül töreni","Bilet fiyatı"]'::jsonb, 0, 'sinema'),
('Sinemada ''yeniden gösterim'' ne demektir?', '["Filmin yeniden çekilmesi","Eski filmin yeniden vizyona girmesi","Fragman yayını","Televizyon uyarlaması"]'::jsonb, 1, 'sinema'),
('Film arşivciliğinin amacı nedir?', '["Bilet satmak","Ödül vermek","Filmleri koruyup geleceğe aktarmak","Fragman çekmek"]'::jsonb, 2, 'sinema'),
('Sinemateklerin işlevi nedir?', '["Film çekmek","Oyuncu yetiştirmek","Bilet dağıtmak","Sinema mirasını göstermek ve korumak"]'::jsonb, 3, 'sinema')
on conflict (soru) do nothing;
