-- Soru havuzu genişletme — Parti 9: 500 yeni soru
-- Mevcut kategoriler + yeni kategoriler (sinema, müzik, teknoloji)
-- Doğru cevap şıkkı karışık (hep 0. şıkta değil).
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
-- ===================== TARİH (50) =====================
('Osmanlı İmparatorluğu''nun en uzun süre tahtta kalan padişahı kimdir?', '["II. Abdülhamid","Kanuni Sultan Süleyman","Fatih Sultan Mehmet","IV. Murad"]'::jsonb, 1, 'tarih'),
('İstanbul''u fetheden Osmanlı padişahı kimdir?', '["II. Bayezid","Yavuz Selim","Fatih Sultan Mehmet","I. Murad"]'::jsonb, 2, 'tarih'),
('Çanakkale Deniz Zaferi hangi yılda kazanılmıştır?', '["1915","1918","1912","1922"]'::jsonb, 0, 'tarih'),
('Lozan Antlaşması hangi yılda imzalanmıştır?', '["1920","1923","1919","1925"]'::jsonb, 1, 'tarih'),
('Sakarya Meydan Muharebesi hangi yılda yapılmıştır?', '["1921","1919","1923","1918"]'::jsonb, 0, 'tarih'),
('Mustafa Kemal Atatürk hangi şehirde doğmuştur?', '["İstanbul","Selanik","İzmir","Manastır"]'::jsonb, 1, 'tarih'),
('Harf İnkılabı (yeni Türk alfabesi) hangi yılda kabul edilmiştir?', '["1928","1924","1930","1926"]'::jsonb, 0, 'tarih'),
('Türkiye''de kadınlara milletvekili seçme ve seçilme hakkı hangi yıl verilmiştir?', '["1930","1934","1926","1940"]'::jsonb, 1, 'tarih'),
('Berlin Duvarı hangi yılda yıkılmıştır?', '["1989","1991","1985","1993"]'::jsonb, 0, 'tarih'),
('Sovyetler Birliği hangi yılda dağılmıştır?', '["1989","1991","1993","1990"]'::jsonb, 1, 'tarih'),
('Fransız İhtilali hangi yılda başlamıştır?', '["1789","1776","1804","1815"]'::jsonb, 0, 'tarih'),
('Amerika Birleşik Devletleri bağımsızlığını hangi yılda ilan etmiştir?', '["1776","1789","1801","1750"]'::jsonb, 0, 'tarih'),
('İkinci Dünya Savaşı hangi yılda sona ermiştir?', '["1945","1939","1918","1950"]'::jsonb, 0, 'tarih'),
('Napolyon''un yenildiği ünlü savaş hangisidir?', '["Waterloo","Austerlitz","Trafalgar","Marengo"]'::jsonb, 0, 'tarih'),
('Rönesans hareketi hangi ülkede başlamıştır?', '["Fransa","İtalya","İngiltere","İspanya"]'::jsonb, 1, 'tarih'),
('Antik çağda Mısır''ı yöneten kadın firavun kimdir?', '["Nefertiti","Kleopatra","Hatşepsut","Meritamon"]'::jsonb, 1, 'tarih'),
('İpek Yolu hangi iki kıtayı birbirine bağlardı?', '["Afrika-Avrupa","Asya-Avrupa","Amerika-Asya","Afrika-Asya"]'::jsonb, 1, 'tarih'),
('Malazgirt Savaşı''nda Bizans''ı yenen Selçuklu sultanı kimdir?', '["Alparslan","Tuğrul Bey","Melikşah","Çağrı Bey"]'::jsonb, 0, 'tarih'),
('Haçlı Seferleri''nin temel hedefi neresiydi?', '["Roma","Kudüs","İstanbul","Kahire"]'::jsonb, 1, 'tarih'),
('Kavimler Göçü''ne neden olan kavim hangisidir?', '["Hunlar","Gotlar","Vandallar","Franklar"]'::jsonb, 0, 'tarih'),
('Türkiye Cumhuriyeti''nin ilk cumhurbaşkanı kimdir?', '["İsmet İnönü","Mustafa Kemal Atatürk","Celal Bayar","Fevzi Çakmak"]'::jsonb, 1, 'tarih'),
('Türkiye''nin ikinci cumhurbaşkanı kimdir?', '["Celal Bayar","İsmet İnönü","Cemal Gürsel","Adnan Menderes"]'::jsonb, 1, 'tarih'),
('Cumhuriyet hangi tarihte ilan edilmiştir?', '["29 Ekim 1923","23 Nisan 1920","19 Mayıs 1919","30 Ağustos 1922"]'::jsonb, 0, 'tarih'),
('Kurtuluş Savaşı''nda düzenlenen ilk kongre hangisidir?', '["Erzurum Kongresi","Sivas Kongresi","Amasya Kongresi","Balıkesir Kongresi"]'::jsonb, 0, 'tarih'),
('Soğuk Savaş hangi iki süper güç arasında yaşanmıştır?', '["ABD-Çin","ABD-SSCB","İngiltere-Almanya","Fransa-SSCB"]'::jsonb, 1, 'tarih'),
('Piri Reis hangi alanda ünlüdür?', '["Denizcilik ve haritacılık","Astronomi","Şairlik","Matematik"]'::jsonb, 0, 'tarih'),
('Mimar Sinan''ın ustalık eseri olarak nitelediği cami hangisidir?', '["Selimiye Camii","Süleymaniye Camii","Şehzade Camii","Sultanahmet Camii"]'::jsonb, 0, 'tarih'),
('Osmanlı Devleti hangi savaşla dağılma sürecine girmiştir?', '["I. Dünya Savaşı","Kırım Savaşı","Balkan Savaşları","93 Harbi"]'::jsonb, 0, 'tarih'),
('Türklerin İslamiyeti kabul etmesinde etkili olan savaş hangisidir?', '["Talas Savaşı","Malazgirt Savaşı","Dandanakan Savaşı","Katvan Savaşı"]'::jsonb, 0, 'tarih'),
('İlk Türk devleti olarak kabul edilen devlet hangisidir?', '["Asya Hun Devleti","Göktürkler","Uygurlar","Avarlar"]'::jsonb, 0, 'tarih'),
('Atatürk''ün doğum yılı hangisidir?', '["1881","1878","1885","1890"]'::jsonb, 0, 'tarih'),
('Atatürk hangi yıl vefat etmiştir?', '["1938","1940","1935","1945"]'::jsonb, 0, 'tarih'),
('Türkiye Büyük Millet Meclisi hangi yıl açılmıştır?', '["1920","1923","1919","1921"]'::jsonb, 0, 'tarih'),
('İkinci Dünya Savaşı''nda atom bombası atılan Japon şehirleri hangileridir?', '["Tokyo ve Osaka","Hiroşima ve Nagazaki","Kyoto ve Kobe","Nagoya ve Sapporo"]'::jsonb, 1, 'tarih'),
('Yeniçeri Ocağı hangi padişah döneminde kaldırılmıştır?', '["II. Mahmud","III. Selim","Abdülmecid","II. Abdülhamid"]'::jsonb, 0, 'tarih'),
('Osmanlı''da Tanzimat Fermanı hangi yılda ilan edilmiştir?', '["1839","1856","1876","1908"]'::jsonb, 0, 'tarih'),
('Antik Yunan''da demokrasinin doğduğu şehir devleti hangisidir?', '["Sparta","Atina","Korint","Thebai"]'::jsonb, 1, 'tarih'),
('Roma İmparatorluğu''nu ikiye bölen imparator kimdir?', '["Konstantin","Diocletianus","Neron","Sezar"]'::jsonb, 1, 'tarih'),
('İstanbul''un ilk adı neydi?', '["Byzantion","Konstantinopolis","Nova Roma","Antakya"]'::jsonb, 0, 'tarih'),
('Kanuni Sultan Süleyman kaçıncı Osmanlı padişahıdır?', '["10.","8.","12.","6."]'::jsonb, 0, 'tarih'),
('Ünlü ''Bileşik Kaplar'' değil, Magna Carta hangi ülkede imzalanmıştır?', '["Fransa","İngiltere","İtalya","Almanya"]'::jsonb, 1, 'tarih'),
('Endülüs Emevi Devleti hangi bölgede kurulmuştur?', '["İber Yarımadası","Kuzey Afrika","Anadolu","Arap Yarımadası"]'::jsonb, 0, 'tarih'),
('Moğol İmparatorluğu''nun kurucusu kimdir?', '["Cengiz Han","Kubilay Han","Timur","Hülagu"]'::jsonb, 0, 'tarih'),
('Amerika kıtasını 1492''de keşfeden denizci kimdir?', '["Macellan","Kristof Kolomb","Vasco da Gama","Amerigo Vespucci"]'::jsonb, 1, 'tarih'),
('Dünya turunu tamamlayan ilk sefer kimin komutasında başlamıştır?', '["Macellan","Kolomb","Marco Polo","Cook"]'::jsonb, 0, 'tarih'),
('Osmanlı''nın kurucusu kimdir?', '["Osman Bey","Orhan Bey","Ertuğrul Gazi","Ozan Bey"]'::jsonb, 0, 'tarih'),
('Türkiye Cumhuriyeti''nin başkenti hangi şehirdir?', '["İstanbul","Ankara","İzmir","Bursa"]'::jsonb, 1, 'tarih'),
('Birinci Dünya Savaşı hangi yılda başlamıştır?', '["1914","1912","1918","1910"]'::jsonb, 0, 'tarih'),
('İnkılap tarihimizde saltanat hangi yıl kaldırılmıştır?', '["1922","1923","1924","1920"]'::jsonb, 0, 'tarih'),
('Halifelik hangi yıl kaldırılmıştır?', '["1924","1922","1928","1926"]'::jsonb, 0, 'tarih'),
-- ===================== BİLİM (50) =====================
('Suyun kimyasal formülü nedir?', '["CO2","H2O","O2","NaCl"]'::jsonb, 1, 'bilim'),
('İnsan vücudundaki en büyük organ hangisidir?', '["Karaciğer","Deri","Akciğer","Beyin"]'::jsonb, 1, 'bilim'),
('Işık hızı yaklaşık olarak saniyede kaç kilometredir?', '["300.000 km","150.000 km","1.000.000 km","30.000 km"]'::jsonb, 0, 'bilim'),
('Periyodik tabloda ''O'' sembolü hangi elementi gösterir?', '["Altın","Oksijen","Osmiyum","Karbon"]'::jsonb, 1, 'bilim'),
('Yerçekimini keşfeden bilim insanı kimdir?', '["Einstein","Newton","Galileo","Kepler"]'::jsonb, 1, 'bilim'),
('İzafiyet (görelilik) teorisini geliştiren bilim insanı kimdir?', '["Newton","Einstein","Bohr","Tesla"]'::jsonb, 1, 'bilim'),
('İnsan vücudunda kaç çift kromozom bulunur?', '["23","46","21","44"]'::jsonb, 0, 'bilim'),
('Kanı vücutta pompalayan organ hangisidir?', '["Böbrek","Kalp","Akciğer","Mide"]'::jsonb, 1, 'bilim'),
('Bitkilerin güneş ışığını kullanarak besin üretmesine ne denir?', '["Solunum","Fotosentez","Terleme","Sindirim"]'::jsonb, 1, 'bilim'),
('Ses boşlukta (uzayda) yayılabilir mi?', '["Evet","Hayır","Sadece geceleri","Sadece ışıkla"]'::jsonb, 1, 'bilim'),
('Dünya''nın uydusu hangisidir?', '["Mars","Ay","Venüs","Titan"]'::jsonb, 1, 'bilim'),
('Güneş sistemindeki en büyük gezegen hangisidir?', '["Satürn","Jüpiter","Dünya","Neptün"]'::jsonb, 1, 'bilim'),
('Güneş''e en yakın gezegen hangisidir?', '["Venüs","Merkür","Dünya","Mars"]'::jsonb, 1, 'bilim'),
('Kırmızı gezegen olarak bilinen gezegen hangisidir?', '["Mars","Jüpiter","Venüs","Satürn"]'::jsonb, 0, 'bilim'),
('Suyun kaç santigrat derecede kaynadığı bilinir (deniz seviyesinde)?', '["100","90","80","120"]'::jsonb, 0, 'bilim'),
('Suyun kaç santigrat derecede donduğu bilinir?', '["0","10","-10","5"]'::jsonb, 0, 'bilim'),
('DNA''nın açılımındaki ilk kelime nedir?', '["Deoksiribonükleik","Diribonükleik","Dinükleik","Dioksinükleik"]'::jsonb, 0, 'bilim'),
('Elektrik akımının birimi nedir?', '["Volt","Amper","Watt","Ohm"]'::jsonb, 1, 'bilim'),
('Kuvvetin birimi nedir?', '["Joule","Newton","Pascal","Watt"]'::jsonb, 1, 'bilim'),
('Enerjinin birimi nedir?', '["Joule","Newton","Amper","Volt"]'::jsonb, 0, 'bilim'),
('Atomun merkezinde bulunan yapıya ne denir?', '["Elektron","Çekirdek","Proton","Molekül"]'::jsonb, 1, 'bilim'),
('Negatif yüklü atom altı parçacık hangisidir?', '["Proton","Elektron","Nötron","Foton"]'::jsonb, 1, 'bilim'),
('İnsan vücudunda oksijeni taşıyan kan hücresi hangisidir?', '["Akyuvar","Alyuvar","Trombosit","Plazma"]'::jsonb, 1, 'bilim'),
('Penisilini keşfeden bilim insanı kimdir?', '["Fleming","Pasteur","Koch","Darwin"]'::jsonb, 0, 'bilim'),
('Evrim teorisini geliştiren bilim insanı kimdir?', '["Mendel","Darwin","Lamarck","Wallace"]'::jsonb, 1, 'bilim'),
('İnsan vücudundaki en uzun kemik hangisidir?', '["Uyluk kemiği (femur)","Kaval kemiği","Kol kemiği","Omurga"]'::jsonb, 0, 'bilim'),
('Görme organımız hangisidir?', '["Kulak","Göz","Burun","Dil"]'::jsonb, 1, 'bilim'),
('Fotosentezde bitkilerin havadan aldığı gaz hangisidir?', '["Oksijen","Karbondioksit","Azot","Hidrojen"]'::jsonb, 1, 'bilim'),
('Bir maddenin katı halden doğrudan gaz haline geçmesine ne denir?', '["Erime","Süblimleşme","Buharlaşma","Yoğuşma"]'::jsonb, 1, 'bilim'),
('Termometre hangi büyüklüğü ölçer?', '["Basınç","Sıcaklık","Nem","Hız"]'::jsonb, 1, 'bilim'),
('Dünya kendi ekseni etrafında bir turunu yaklaşık kaç saatte tamamlar?', '["24 saat","12 saat","48 saat","36 saat"]'::jsonb, 0, 'bilim'),
('İnsan beyninin düşünme ve hafızayla ilgili bölümü hangisidir?', '["Beyincik","Beyin (büyük beyin)","Omurilik","Soğanilik"]'::jsonb, 1, 'bilim'),
('Hangi vitamin güneş ışığıyla vücutta üretilir?', '["A vitamini","D vitamini","C vitamini","B12 vitamini"]'::jsonb, 1, 'bilim'),
('C vitamini eksikliğinde görülen hastalık hangisidir?', '["Raşitizm","Skorbüt","Anemi","Guatr"]'::jsonb, 1, 'bilim'),
('Sesin şiddet birimi nedir?', '["Hertz","Desibel","Watt","Volt"]'::jsonb, 1, 'bilim'),
('Frekansın birimi nedir?', '["Desibel","Hertz","Newton","Joule"]'::jsonb, 1, 'bilim'),
('En hafif kimyasal element hangisidir?', '["Helyum","Hidrojen","Oksijen","Karbon"]'::jsonb, 1, 'bilim'),
('Altının kimyasal sembolü nedir?', '["Ag","Au","Al","Fe"]'::jsonb, 1, 'bilim'),
('Demirin kimyasal sembolü nedir?', '["Fe","Fr","Ir","In"]'::jsonb, 0, 'bilim'),
('Tuzun (sofra tuzu) kimyasal formülü nedir?', '["NaCl","KCl","CaCO3","H2O"]'::jsonb, 0, 'bilim'),
('Bir cismin hızının zamana göre değişimine ne denir?', '["Kuvvet","İvme","Momentum","Yer değiştirme"]'::jsonb, 1, 'bilim'),
('Kanın pıhtılaşmasını sağlayan kan hücresi hangisidir?', '["Alyuvar","Trombosit","Akyuvar","Lenfosit"]'::jsonb, 1, 'bilim'),
('Bir dik üçgende hipotenüs karesi ile ilgili teorem kime aittir?', '["Öklid","Pisagor","Thales","Arşimet"]'::jsonb, 1, 'bilim'),
('Sıvıların kaldırma kuvvetini açıklayan bilim insanı kimdir?', '["Newton","Arşimet","Pascal","Galileo"]'::jsonb, 1, 'bilim'),
('Radyoaktiviteyi araştıran ve iki Nobel kazanan bilim insanı kimdir?', '["Marie Curie","Rosalind Franklin","Ada Lovelace","Lise Meitner"]'::jsonb, 0, 'bilim'),
('İnsan vücudundaki kanın rengini veren protein hangisidir?', '["Keratin","Hemoglobin","Kollajen","İnsülin"]'::jsonb, 1, 'bilim'),
('Kan şekerini düzenleyen hormon hangisidir?', '["Adrenalin","İnsülin","Tiroksin","Östrojen"]'::jsonb, 1, 'bilim'),
('Dünyanın en dıştaki gaz katmanına ne denir?', '["Atmosfer","Litosfer","Hidrosfer","Biyosfer"]'::jsonb, 0, 'bilim'),
('Bilgisayarların ikili sayı sisteminde kullandığı rakamlar nelerdir?', '["0 ve 1","1 ve 2","0-9 arası","A ve B"]'::jsonb, 0, 'bilim'),
('Bir maddenin asit mi baz mı olduğunu gösteren ölçek hangisidir?', '["pH","dB","Hz","kW"]'::jsonb, 0, 'bilim'),
-- ===================== COĞRAFYA (50) =====================
('Türkiye''nin başkenti neresidir?', '["İstanbul","Ankara","İzmir","Antalya"]'::jsonb, 1, 'cografya'),
('Dünyanın en uzun nehri hangisidir?', '["Amazon","Nil","Yangtze","Mississippi"]'::jsonb, 1, 'cografya'),
('Dünyanın en yüksek dağı hangisidir?', '["K2","Everest","Kilimanjaro","Ağrı Dağı"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en yüksek dağı hangisidir?', '["Erciyes","Ağrı Dağı","Uludağ","Kaçkar"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en büyük gölü hangisidir?', '["Tuz Gölü","Van Gölü","Beyşehir Gölü","İznik Gölü"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en uzun nehri hangisidir?', '["Kızılırmak","Fırat","Sakarya","Yeşilırmak"]'::jsonb, 0, 'cografya'),
('Japonya''nın başkenti neresidir?', '["Osaka","Tokyo","Kyoto","Seul"]'::jsonb, 1, 'cografya'),
('Fransa''nın başkenti neresidir?', '["Lyon","Paris","Marsilya","Nice"]'::jsonb, 1, 'cografya'),
('İtalya''nın başkenti neresidir?', '["Milano","Roma","Napoli","Venedik"]'::jsonb, 1, 'cografya'),
('Almanya''nın başkenti neresidir?', '["Münih","Berlin","Hamburg","Frankfurt"]'::jsonb, 1, 'cografya'),
('İspanya''nın başkenti neresidir?', '["Barselona","Madrid","Sevilla","Valencia"]'::jsonb, 1, 'cografya'),
('Rusya''nın başkenti neresidir?', '["St. Petersburg","Moskova","Kiev","Kazan"]'::jsonb, 1, 'cografya'),
('İngiltere''nin başkenti neresidir?', '["Manchester","Londra","Liverpool","Birmingham"]'::jsonb, 1, 'cografya'),
('ABD''nin başkenti neresidir?', '["New York","Washington D.C.","Los Angeles","Chicago"]'::jsonb, 1, 'cografya'),
('Mısır''ın başkenti neresidir?', '["İskenderiye","Kahire","Luxor","Giza"]'::jsonb, 1, 'cografya'),
('Dünyanın en büyük okyanusu hangisidir?', '["Atlas Okyanusu","Büyük Okyanus (Pasifik)","Hint Okyanusu","Arktik Okyanus"]'::jsonb, 1, 'cografya'),
('Dünyanın en büyük çölü hangisidir?', '["Sahra","Antarktika Çölü","Gobi","Kalahari"]'::jsonb, 1, 'cografya'),
('En kalabalık nüfusa sahip kıta hangisidir?', '["Afrika","Asya","Avrupa","Amerika"]'::jsonb, 1, 'cografya'),
('Türkiye kaç coğrafi bölgeye ayrılır?', '["7","6","8","5"]'::jsonb, 0, 'cografya'),
('İstanbul Boğazı hangi iki denizi birbirine bağlar?', '["Karadeniz-Marmara","Ege-Akdeniz","Marmara-Ege","Karadeniz-Ege"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en kalabalık şehri hangisidir?', '["Ankara","İstanbul","İzmir","Bursa"]'::jsonb, 1, 'cografya'),
('Pamukkale hangi ilimizde yer alır?', '["Denizli","Antalya","Muğla","Aydın"]'::jsonb, 0, 'cografya'),
('Kapadokya hangi bölgede yer alır?', '["Ege","İç Anadolu","Akdeniz","Karadeniz"]'::jsonb, 1, 'cografya'),
('Dünyanın en büyük adası hangisidir?', '["Madagaskar","Grönland","Yeni Gine","Borneo"]'::jsonb, 1, 'cografya'),
('Avustralya''nın başkenti neresidir?', '["Sidney","Kanberra","Melbourne","Perth"]'::jsonb, 1, 'cografya'),
('Kanada''nın başkenti neresidir?', '["Toronto","Ottava","Montreal","Vancouver"]'::jsonb, 1, 'cografya'),
('Brezilya''nın başkenti neresidir?', '["Rio de Janeiro","Brasília","Sao Paulo","Salvador"]'::jsonb, 1, 'cografya'),
('Yunanistan''ın başkenti neresidir?', '["Selanik","Atina","Patras","Girit"]'::jsonb, 1, 'cografya'),
('Hollanda''nın başkenti neresidir?', '["Rotterdam","Amsterdam","Lahey","Utrecht"]'::jsonb, 1, 'cografya'),
('Çin''in başkenti neresidir?', '["Şangay","Pekin","Hong Kong","Kanton"]'::jsonb, 1, 'cografya'),
('Hindistan''ın başkenti neresidir?', '["Mumbai","Yeni Delhi","Kalküta","Bangalor"]'::jsonb, 1, 'cografya'),
('Dünyanın en büyük yağmur ormanı hangisidir?', '["Kongo","Amazon","Borneo","Tayga"]'::jsonb, 1, 'cografya'),
('Türkiye''nin güneyinde hangi deniz bulunur?', '["Karadeniz","Akdeniz","Ege Denizi","Marmara"]'::jsonb, 1, 'cografya'),
('Dünyanın en soğuk kıtası hangisidir?', '["Asya","Antarktika","Avrupa","Amerika"]'::jsonb, 1, 'cografya'),
('Ekvator hangi büyüklüğün sıfır derecesini gösterir?', '["Boylam","Enlem","Yükseklik","Meridyen"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en batısındaki ili hangisidir?', '["Çanakkale","Edirne","İzmir","Balıkesir"]'::jsonb, 1, 'cografya'),
('Volkanik patlamayla oluşan Nemrut Krater Gölü hangi ildedir?', '["Bitlis","Van","Ağrı","Muş"]'::jsonb, 0, 'cografya'),
('Süveyş Kanalı hangi iki denizi birbirine bağlar?', '["Akdeniz-Kızıldeniz","Karadeniz-Akdeniz","Hint-Pasifik","Ege-Marmara"]'::jsonb, 0, 'cografya'),
('Panama Kanalı hangi iki okyanusu birbirine bağlar?', '["Atlas-Pasifik","Hint-Pasifik","Atlas-Hint","Arktik-Pasifik"]'::jsonb, 0, 'cografya'),
('Dünyanın en derin okyanus çukuru hangisidir?', '["Mariana Çukuru","Java Çukuru","Tonga Çukuru","Porto Riko Çukuru"]'::jsonb, 0, 'cografya'),
('Türkiye''nin komşusu olmayan ülke hangisidir?', '["İran","Suriye","Mısır","Yunanistan"]'::jsonb, 2, 'cografya'),
('Karadeniz''e kıyısı olmayan ülke hangisidir?', '["Bulgaristan","Gürcistan","Macaristan","Ukrayna"]'::jsonb, 2, 'cografya'),
('Dünyanın en kalabalık ülkesi (nüfusça) hangilerindendir?', '["Hindistan","İzlanda","Portekiz","Norveç"]'::jsonb, 0, 'cografya'),
('Sahra Çölü ağırlıklı olarak hangi kıtadadır?', '["Asya","Afrika","Avustralya","Amerika"]'::jsonb, 1, 'cografya'),
('Vezüv Yanardağı hangi ülkede bulunur?', '["Yunanistan","İtalya","İspanya","Türkiye"]'::jsonb, 1, 'cografya'),
('Türkiye''nin en kalabalık üçüncü şehri hangisidir?', '["Bursa","İzmir","Antalya","Adana"]'::jsonb, 1, 'cografya'),
('Everest Dağı hangi sıradağlarda yer alır?', '["Alpler","Himalayalar","And Dağları","Toroslar"]'::jsonb, 1, 'cografya'),
('And Dağları hangi kıtada bulunur?', '["Afrika","Güney Amerika","Asya","Avrupa"]'::jsonb, 1, 'cografya'),
('Dünyanın yüzölçümü en büyük ülkesi hangisidir?', '["Kanada","Rusya","Çin","ABD"]'::jsonb, 1, 'cografya'),
('Fiyortlarıyla ünlü İskandinav ülkesi hangisidir?', '["Norveç","İspanya","Yunanistan","İtalya"]'::jsonb, 0, 'cografya'),
-- ===================== EDEBİYAT (40) =====================
('''Sefiller'' romanının yazarı kimdir?', '["Victor Hugo","Balzac","Zola","Flaubert"]'::jsonb, 0, 'edebiyat'),
('''Suç ve Ceza'' romanının yazarı kimdir?', '["Tolstoy","Dostoyevski","Çehov","Gogol"]'::jsonb, 1, 'edebiyat'),
('''Savaş ve Barış'' romanının yazarı kimdir?', '["Dostoyevski","Tolstoy","Turgenyev","Puşkin"]'::jsonb, 1, 'edebiyat'),
('''Hamlet'' oyununun yazarı kimdir?', '["Shakespeare","Molière","Goethe","Dante"]'::jsonb, 0, 'edebiyat'),
('İstiklal Marşı''nın şairi kimdir?', '["Mehmet Akif Ersoy","Yahya Kemal","Namık Kemal","Tevfik Fikret"]'::jsonb, 0, 'edebiyat'),
('''Çalıkuşu'' romanının yazarı kimdir?', '["Reşat Nuri Güntekin","Halide Edib","Yakup Kadri","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('''İnce Memed'' romanının yazarı kimdir?', '["Orhan Kemal","Yaşar Kemal","Kemal Tahir","Sabahattin Ali"]'::jsonb, 1, 'edebiyat'),
('Nobel Edebiyat Ödülü kazanan ilk Türk yazar kimdir?', '["Yaşar Kemal","Orhan Pamuk","Nazım Hikmet","Ahmet Hamdi Tanpınar"]'::jsonb, 1, 'edebiyat'),
('''Kürk Mantolu Madonna'' romanının yazarı kimdir?', '["Sabahattin Ali","Sait Faik","Yusuf Atılgan","Oğuz Atay"]'::jsonb, 0, 'edebiyat'),
('''Tutunamayanlar'' romanının yazarı kimdir?', '["Oğuz Atay","Orhan Pamuk","Yusuf Atılgan","Bilge Karasu"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında ''Servet-i Fünun'' hangi dönemin akımıdır?', '["Tanzimat","Edebiyat-ı Cedide","Milli Edebiyat","Divan"]'::jsonb, 1, 'edebiyat'),
('''Don Kişot'' romanının yazarı kimdir?', '["Cervantes","Lope de Vega","Dante","Boccaccio"]'::jsonb, 0, 'edebiyat'),
('''İlahi Komedya'' eserinin yazarı kimdir?', '["Petrarca","Dante","Boccaccio","Machiavelli"]'::jsonb, 1, 'edebiyat'),
('''Faust'' eserinin yazarı kimdir?', '["Goethe","Schiller","Kafka","Mann"]'::jsonb, 0, 'edebiyat'),
('''Dönüşüm'' (Die Verwandlung) eserinin yazarı kimdir?', '["Kafka","Camus","Sartre","Nietzsche"]'::jsonb, 0, 'edebiyat'),
('''Yabancı'' (L''Étranger) romanının yazarı kimdir?', '["Sartre","Camus","Proust","Gide"]'::jsonb, 1, 'edebiyat'),
('Türk şiirinde ''Garip Akımı''nın önde gelen ismi kimdir?', '["Orhan Veli","Cemal Süreya","Necip Fazıl","Attila İlhan"]'::jsonb, 0, 'edebiyat'),
('''Yaban'' romanının yazarı kimdir?', '["Yakup Kadri Karaosmanoğlu","Reşat Nuri","Halit Ziya","Refik Halit"]'::jsonb, 0, 'edebiyat'),
('''Mai ve Siyah'' romanının yazarı kimdir?', '["Halit Ziya Uşaklıgil","Mehmet Rauf","Recaizade","Namık Kemal"]'::jsonb, 0, 'edebiyat'),
('''Eylül'' romanının yazarı kimdir?', '["Mehmet Rauf","Halit Ziya","Yakup Kadri","Peyami Safa"]'::jsonb, 0, 'edebiyat'),
('Divan edebiyatının ünlü şairi ''Fuzuli''nin en bilinen eseri hangisidir?', '["Leyla ile Mecnun","Hüsn ü Aşk","Mesnevi","Divan-ı Kebir"]'::jsonb, 0, 'edebiyat'),
('''Mesnevi'' adlı eseriyle tanınan mutasavvıf kimdir?', '["Yunus Emre","Mevlana","Hacı Bektaş","Fuzuli"]'::jsonb, 1, 'edebiyat'),
('Türk halk edebiyatının ünlü âşığı ''Karacaoğlan'' hangi türde eser verir?', '["Halk şiiri","Roman","Tiyatro","Deneme"]'::jsonb, 0, 'edebiyat'),
('''1984'' distopik romanının yazarı kimdir?', '["George Orwell","Aldous Huxley","Ray Bradbury","H.G. Wells"]'::jsonb, 0, 'edebiyat'),
('''Cesur Yeni Dünya'' romanının yazarı kimdir?', '["Orwell","Aldous Huxley","Bradbury","Asimov"]'::jsonb, 1, 'edebiyat'),
('''Yüzüklerin Efendisi'' serisinin yazarı kimdir?', '["J.R.R. Tolkien","C.S. Lewis","G.R.R. Martin","J.K. Rowling"]'::jsonb, 0, 'edebiyat'),
('''Harry Potter'' serisinin yazarı kimdir?', '["J.K. Rowling","Roald Dahl","Tolkien","Lewis"]'::jsonb, 0, 'edebiyat'),
('''Simyacı'' kitabının yazarı kimdir?', '["Paulo Coelho","Gabriel García Márquez","Borges","Isabel Allende"]'::jsonb, 0, 'edebiyat'),
('''Yüzyıllık Yalnızlık'' romanının yazarı kimdir?', '["Gabriel García Márquez","Vargas Llosa","Borges","Cortázar"]'::jsonb, 0, 'edebiyat'),
('''Beyaz Diş'' ve ''Vahşetin Çağrısı'' eserlerinin yazarı kimdir?', '["Jack London","Mark Twain","Hemingway","Steinbeck"]'::jsonb, 0, 'edebiyat'),
('''İhtiyar Adam ve Deniz'' eserinin yazarı kimdir?', '["Steinbeck","Hemingway","Faulkner","Fitzgerald"]'::jsonb, 1, 'edebiyat'),
('''Anna Karenina'' romanının yazarı kimdir?', '["Tolstoy","Dostoyevski","Çehov","Puşkin"]'::jsonb, 0, 'edebiyat'),
('''Vişne Bahçesi'' oyununun yazarı kimdir?', '["Çehov","Gogol","Tolstoy","İbsen"]'::jsonb, 0, 'edebiyat'),
('''Kırmızı Saçlı Kadın'' romanının yazarı kimdir?', '["Orhan Pamuk","Elif Şafak","Ahmet Ümit","Yaşar Kemal"]'::jsonb, 0, 'edebiyat'),
('''Aşk'' (Aşk-ı Memnu değil, The Forty Rules) romanıyla tanınan yazar kimdir?', '["Elif Şafak","Buket Uzuner","Ayşe Kulin","Perihan Mağden"]'::jsonb, 0, 'edebiyat'),
('Şiirlerinde ''memleket'' teması işleyen ''Nazım Hikmet'' hangi türde eser verir?', '["Şiir","Roman","Deneme","Anı"]'::jsonb, 0, 'edebiyat'),
('''Otel Odaları'' şiiriyle tanınan şair kimdir?', '["Attila İlhan","Cemal Süreya","Turgut Uyar","İkinci Yeni"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında ilk yerli roman hangisidir?', '["Taaşşuk-ı Talat ve Fitnat","İntibah","Araba Sevdası","Felatun Bey"]'::jsonb, 0, 'edebiyat'),
('''Romeo ve Juliet'' hangi türde bir eserdir?', '["Trajedi","Komedi","Roman","Destan"]'::jsonb, 0, 'edebiyat'),
('''Kaplumbağa ile Tavşan'' gibi hayvan hikâyeleriyle ünlü Antik Yunan yazarı kimdir?', '["Ezop","Homeros","Sofokles","Platon"]'::jsonb, 0, 'edebiyat'),
-- ===================== SPOR (40) =====================
('Bir futbol takımında sahada kaç oyuncu bulunur?', '["11","10","12","9"]'::jsonb, 0, 'spor'),
('Basketbolda bir takım sahada kaç oyuncuyla oynar?', '["5","6","7","4"]'::jsonb, 0, 'spor'),
('Voleybolda bir takım sahada kaç oyuncuyla oynar?', '["6","5","7","4"]'::jsonb, 0, 'spor'),
('Dünya Kupası hangi sporun en büyük turnuvasıdır?', '["Basketbol","Futbol","Voleybol","Hentbol"]'::jsonb, 1, 'spor'),
('Olimpiyat Oyunları kaç yılda bir düzenlenir?', '["4","2","3","5"]'::jsonb, 0, 'spor'),
('2002 Dünya Kupası''nda Türkiye kaçıncı olmuştur?', '["3.","2.","4.","1."]'::jsonb, 0, 'spor'),
('Formula 1''de en çok şampiyonluğa ulaşan pilotlardan Michael Schumacher hangi ülkedendir?', '["Almanya","İngiltere","İtalya","Fransa"]'::jsonb, 0, 'spor'),
('Tenis turnuvası Wimbledon hangi ülkede oynanır?', '["ABD","İngiltere","Fransa","Avustralya"]'::jsonb, 1, 'spor'),
('Bir futbol maçı normal süresi kaç dakikadır?', '["90","80","100","120"]'::jsonb, 0, 'spor'),
('Basketbolda üç sayılık atış çizgi dışından yapılırsa kaç sayı kazandırır?', '["3","2","1","4"]'::jsonb, 0, 'spor'),
('Boks ringinin şekli nedir?', '["Kare","Daire","Altıgen","Üçgen"]'::jsonb, 0, 'spor'),
('Ünlü basketbolcu Michael Jordan hangi takımla efsaneleşmiştir?', '["Chicago Bulls","LA Lakers","Boston Celtics","Miami Heat"]'::jsonb, 0, 'spor'),
('Futbolda ''hat-trick'' ne anlama gelir?', '["Bir oyuncunun bir maçta 3 gol atması","Üç kırmızı kart","Üç penaltı","Üç korner"]'::jsonb, 0, 'spor'),
('Maraton koşusunun mesafesi yaklaşık kaç kilometredir?', '["42 km","21 km","50 km","30 km"]'::jsonb, 0, 'spor'),
('Buz hokeyinde kullanılan disk şeklindeki nesneye ne denir?', '["Puck","Top","Raket","Sopa"]'::jsonb, 0, 'spor'),
('Lionel Messi hangi ülkenin milli takımındandır?', '["Brezilya","Arjantin","Portekiz","İspanya"]'::jsonb, 1, 'spor'),
('Cristiano Ronaldo hangi ülkenin milli takımındandır?', '["İspanya","Portekiz","Brezilya","Arjantin"]'::jsonb, 1, 'spor'),
('2022 Dünya Kupası''nı hangi ülke kazanmıştır?', '["Fransa","Arjantin","Brezilya","Almanya"]'::jsonb, 1, 'spor'),
('Golf sporunda topun sokulmaya çalışıldığı deliğe ne denir?', '["Hole","Green","Par","Tee"]'::jsonb, 0, 'spor'),
('Yüzmede en hızlı stil hangisidir?', '["Serbest (krol)","Kurbağalama","Sırtüstü","Kelebek"]'::jsonb, 0, 'spor'),
('Türkiye''de ''Üç Büyükler'' olarak anılan futbol kulüplerinden değildir?', '["Trabzonspor","Galatasaray","Fenerbahçe","Beşiktaş"]'::jsonb, 0, 'spor'),
('Tenniste ''0'' sayısı nasıl ifade edilir?', '["Love","Deuce","Ace","Set"]'::jsonb, 0, 'spor'),
('Ragbi topunun şekli nasıldır?', '["Oval","Yuvarlak","Kare","Üçgen"]'::jsonb, 0, 'spor'),
('Satrançta oyunun kazanılması için hangi taş mat edilmelidir?', '["Şah","Vezir","Kale","Fil"]'::jsonb, 0, 'spor'),
('Bir voleybol setini kazanmak için genelde kaç sayıya ulaşmak gerekir?', '["25","21","15","30"]'::jsonb, 0, 'spor'),
('Olimpiyatların sembolü kaç halkadan oluşur?', '["5","4","6","3"]'::jsonb, 0, 'spor'),
('Ünlü tenisçi Serena Williams hangi ülkedendir?', '["ABD","İngiltere","Avustralya","Rusya"]'::jsonb, 0, 'spor'),
('Bisiklet yarışı ''Tour de France'' hangi ülkede yapılır?', '["İtalya","Fransa","İspanya","Belçika"]'::jsonb, 1, 'spor'),
('Amerikan futbolunda sayı bölgesine ulaşarak yapılan büyük sayıya ne denir?', '["Touchdown","Home run","Slam dunk","Goal"]'::jsonb, 0, 'spor'),
('Beyzbolda topa vurulan sopanın adı nedir?', '["Bat","Stick","Racket","Club"]'::jsonb, 0, 'spor'),
('Futbolda kaleciler dışında topa elle dokunmak neye yol açar?', '["Faul (el)","Gol","Korner","Aut"]'::jsonb, 0, 'spor'),
('NBA hangi sporun ligidir?', '["Basketbol","Beyzbol","Amerikan futbolu","Buz hokeyi"]'::jsonb, 0, 'spor'),
('Judo, karate gibi sporlar hangi kategoriye girer?', '["Dövüş sanatları","Su sporları","Kış sporları","Atletizm"]'::jsonb, 0, 'spor'),
('Türkiye''nin güreşte olimpiyat şampiyonu efsane sporcusu ''Yaşar Doğu'' hangi branştandır?', '["Güreş","Boks","Halter","Judo"]'::jsonb, 0, 'spor'),
('Halterde sporcular neyi kaldırır?', '["Ağırlık (halter)","Top","Disk","Mızrak"]'::jsonb, 0, 'spor'),
('Kayak sporu hangi mevsimde yapılır?', '["Kış","Yaz","İlkbahar","Sonbahar"]'::jsonb, 0, 'spor'),
('Bir futbol sahasında kaleye en yakın yarım daire alana ne denir?', '["Ceza sahası","Orta yuvarlak","Taç çizgisi","Kale direği"]'::jsonb, 0, 'spor'),
('Masa tenisinde kullanılan ekipman hangisidir?', '["Raket","Sopa","Eldiven","Kask"]'::jsonb, 0, 'spor'),
('Usain Bolt hangi branşta dünya rekortmenidir?', '["100 metre koşu","Yüzme","Uzun atlama","Halter"]'::jsonb, 0, 'spor'),
('Satranç tahtası kaç kareden oluşur?', '["64","81","100","49"]'::jsonb, 0, 'spor'),
-- ===================== SANAT (30) =====================
('''Mona Lisa'' tablosunu kim yapmıştır?', '["Leonardo da Vinci","Michelangelo","Raphael","Botticelli"]'::jsonb, 0, 'sanat'),
('''Yıldızlı Gece'' tablosunun ressamı kimdir?', '["Van Gogh","Monet","Picasso","Cézanne"]'::jsonb, 0, 'sanat'),
('''Guernica'' tablosunun ressamı kimdir?', '["Picasso","Dalí","Miró","Goya"]'::jsonb, 0, 'sanat'),
('Sistine Şapeli''nin tavan freskini kim yapmıştır?', '["Michelangelo","Da Vinci","Raphael","Donatello"]'::jsonb, 0, 'sanat'),
('''Çığlık'' tablosunun ressamı kimdir?', '["Edvard Munch","Klimt","Kandinsky","Matisse"]'::jsonb, 0, 'sanat'),
('Kübizm akımının öncüsü kabul edilen ressam kimdir?', '["Picasso","Monet","Van Gogh","Rembrandt"]'::jsonb, 0, 'sanat'),
('İzlenimcilik (Empresyonizm) akımının önemli ismi kimdir?', '["Claude Monet","Salvador Dalí","Andy Warhol","Frida Kahlo"]'::jsonb, 0, 'sanat'),
('''Erimiş saatler'' imgesiyle bilinen sürrealist ressam kimdir?', '["Salvador Dalí","Picasso","Magritte","Miró"]'::jsonb, 0, 'sanat'),
('''Düşünen Adam'' heykelinin sanatçısı kimdir?', '["Auguste Rodin","Michelangelo","Bernini","Donatello"]'::jsonb, 0, 'sanat'),
('''Davut'' heykelini yapan sanatçı kimdir?', '["Michelangelo","Rodin","Bernini","Donatello"]'::jsonb, 0, 'sanat'),
('Pop Art akımının en ünlü temsilcisi kimdir?', '["Andy Warhol","Jackson Pollock","Mark Rothko","Roy Lichtenstein"]'::jsonb, 0, 'sanat'),
('Türk resminde ''Kaplumbağa Terbiyecisi'' tablosunun ressamı kimdir?', '["Osman Hamdi Bey","İbrahim Çallı","Bedri Rahmi","Fikret Mualla"]'::jsonb, 0, 'sanat'),
('Rönesans''ın üç büyük ustasından biri değildir?', '["Van Gogh","Leonardo","Michelangelo","Raphael"]'::jsonb, 0, 'sanat'),
('Bale hangi sanat dalıdır?', '["Dans","Resim","Heykel","Müzik"]'::jsonb, 0, 'sanat'),
('Opera hangi sanat dallarını bir arada barındırır?', '["Müzik ve tiyatro","Resim ve heykel","Sinema ve dans","Şiir ve mimari"]'::jsonb, 0, 'sanat'),
('Ünlü ''Ayasofya'' hangi mimari üslubun eseridir?', '["Bizans","Gotik","Barok","Rönesans"]'::jsonb, 0, 'sanat'),
('Fotoğrafçılıkta ışığı kontrol eden ayara ne denir?', '["Diyafram","Piksel","Filtre","Zoom"]'::jsonb, 0, 'sanat'),
('Ebru hangi geleneksel Türk sanatıdır?', '["Kâğıt üzerine su marmelaj sanatı","Ahşap oymacılığı","Cam işlemeciliği","Halı dokuma"]'::jsonb, 0, 'sanat'),
('Hat sanatı neyin güzel yazılması sanatıdır?', '["Yazı","Resim","Müzik","Heykel"]'::jsonb, 0, 'sanat'),
('Çini sanatı ağırlıklı olarak hangi Osmanlı şehriyle özdeşleşmiştir?', '["İznik","Bursa","Konya","Edirne"]'::jsonb, 0, 'sanat'),
('''Öpücük'' (The Kiss) tablosunun altın yaldızlı ressamı kimdir?', '["Gustav Klimt","Egon Schiele","Munch","Renoir"]'::jsonb, 0, 'sanat'),
('Meksikalı ünlü kadın ressam kimdir?', '["Frida Kahlo","Georgia O''Keeffe","Mary Cassatt","Tamara"]'::jsonb, 0, 'sanat'),
('Empresyonizm''de ''su zambakları'' serisiyle bilinen ressam kimdir?', '["Monet","Manet","Degas","Renoir"]'::jsonb, 0, 'sanat'),
('Antik Yunan heykel sanatında ''Venüs de Milo'' hangi malzemeden yapılmıştır?', '["Mermer","Bronz","Ahşap","Kil"]'::jsonb, 0, 'sanat'),
('Bir tabloda kullanılan renk, ışık ve gölge düzenine ne denir?', '["Kompozisyon","Perspektif değil, palet","Melodi","Ritim"]'::jsonb, 0, 'sanat'),
('Uzaklık ve derinlik hissi veren resim tekniğine ne denir?', '["Perspektif","Kolaj","Gravür","Mozaik"]'::jsonb, 0, 'sanat'),
('Küçük renkli taş veya cam parçalarıyla yapılan resme ne denir?', '["Mozaik","Fresk","Vitray","Gravür"]'::jsonb, 0, 'sanat'),
('Renkli cam parçalarıyla yapılan pencere sanatı hangisidir?', '["Vitray","Mozaik","Fresk","Ebru"]'::jsonb, 0, 'sanat'),
('Ünlü ''Truva Atı'' hikâyesi hangi uygarlığa aittir?', '["Antik Yunan","Roma","Mısır","Pers"]'::jsonb, 0, 'sanat'),
('Türk gölge oyununun iki ana karakteri kimlerdir?', '["Karagöz ve Hacivat","Nasrettin ve Timur","Keloğlan ve Dev","İncili Çavuş"]'::jsonb, 0, 'sanat'),
-- ===================== SİNEMA (50) =====================
('''Titanic'' filminin yönetmeni kimdir?', '["James Cameron","Steven Spielberg","Ridley Scott","Christopher Nolan"]'::jsonb, 0, 'sinema'),
('''Baba'' (The Godfather) filminin yönetmeni kimdir?', '["Coppola","Scorsese","Kubrick","Tarantino"]'::jsonb, 0, 'sinema'),
('''Inception'' (Başlangıç) filminin yönetmeni kimdir?', '["Christopher Nolan","Denis Villeneuve","David Fincher","Cameron"]'::jsonb, 0, 'sinema'),
('''Pulp Fiction'' filminin yönetmeni kimdir?', '["Quentin Tarantino","Scorsese","Coppola","Nolan"]'::jsonb, 0, 'sinema'),
('''Jurassic Park'' filminin yönetmeni kimdir?', '["Steven Spielberg","James Cameron","George Lucas","Ridley Scott"]'::jsonb, 0, 'sinema'),
('''Star Wars'' serisinin yaratıcısı kimdir?', '["George Lucas","Spielberg","J.J. Abrams","Lucasfilm"]'::jsonb, 0, 'sinema'),
('''Matrix'' filminde başrol oyuncusu kimdir?', '["Keanu Reeves","Brad Pitt","Tom Cruise","Will Smith"]'::jsonb, 0, 'sinema'),
('''Forrest Gump'' filminde başrolü kim oynamıştır?', '["Tom Hanks","Robin Williams","Kevin Costner","Nicolas Cage"]'::jsonb, 0, 'sinema'),
('''Titanic'' filminde başrol erkek oyuncu kimdir?', '["Leonardo DiCaprio","Brad Pitt","Johnny Depp","Matt Damon"]'::jsonb, 0, 'sinema'),
('En prestijli film ödüllerinden ''Oscar''ları hangi kurum verir?', '["Akademi (AMPAS)","Cannes","BAFTA","Altın Küre"]'::jsonb, 0, 'sinema'),
('Cannes Film Festivali''nin en büyük ödülü hangisidir?', '["Altın Palmiye","Altın Ayı","Altın Aslan","Oscar"]'::jsonb, 0, 'sinema'),
('''Yüzüklerin Efendisi'' film üçlemesinin yönetmeni kimdir?', '["Peter Jackson","Guillermo del Toro","Ridley Scott","Christopher Nolan"]'::jsonb, 0, 'sinema'),
('''Avatar'' (2009) filminin yönetmeni kimdir?', '["James Cameron","Spielberg","Lucas","Nolan"]'::jsonb, 0, 'sinema'),
('Türk sinemasının ''Yeşilçam'' efsanesi ''Kemal Sunal'' hangi türde ünlüdür?', '["Komedi","Aksiyon","Korku","Belgesel"]'::jsonb, 0, 'sinema'),
('''Eşkıya'' filminin başrol oyuncusu kimdir?', '["Şener Şen","Kadir İnanır","Cüneyt Arkın","Tarık Akan"]'::jsonb, 0, 'sinema'),
('''Babam ve Oğlum'' filminin yönetmeni kimdir?', '["Çağan Irmak","Nuri Bilge Ceylan","Zeki Demirkubuz","Yılmaz Erdoğan"]'::jsonb, 0, 'sinema'),
('Cannes''da ''Kış Uykusu'' ile Altın Palmiye kazanan Türk yönetmen kimdir?', '["Nuri Bilge Ceylan","Fatih Akın","Ferzan Özpetek","Reha Erdem"]'::jsonb, 0, 'sinema'),
('''Joker'' (2019) filminde başrol oyuncusu kimdir?', '["Joaquin Phoenix","Heath Ledger","Jared Leto","Jack Nicholson"]'::jsonb, 0, 'sinema'),
('''The Dark Knight'' filminde Joker''i canlandıran oyuncu kimdir?', '["Heath Ledger","Joaquin Phoenix","Christian Bale","Jared Leto"]'::jsonb, 0, 'sinema'),
('''Interstellar'' filminin yönetmeni kimdir?', '["Christopher Nolan","Ridley Scott","Denis Villeneuve","James Cameron"]'::jsonb, 0, 'sinema'),
('''Parasite'' (Parazit) filmi hangi ülkenin yapımıdır?', '["Güney Kore","Japonya","Çin","ABD"]'::jsonb, 0, 'sinema'),
('''Gladyatör'' filminde başrolü kim oynamıştır?', '["Russell Crowe","Brad Pitt","Gerard Butler","Colin Farrell"]'::jsonb, 0, 'sinema'),
('''Fight Club'' filminde başrol oyuncularından biri kimdir?', '["Brad Pitt","Tom Cruise","George Clooney","Matt Damon"]'::jsonb, 0, 'sinema'),
('''Pirates of the Caribbean'' serisinde Jack Sparrow''u kim canlandırır?', '["Johnny Depp","Orlando Bloom","Javier Bardem","Geoffrey Rush"]'::jsonb, 0, 'sinema'),
('''Iron Man'' karakterini canlandıran oyuncu kimdir?', '["Robert Downey Jr.","Chris Evans","Chris Hemsworth","Mark Ruffalo"]'::jsonb, 0, 'sinema'),
('Marvel evreninde ''Thor'' karakterini kim canlandırır?', '["Chris Hemsworth","Chris Evans","Chris Pratt","Tom Hiddleston"]'::jsonb, 0, 'sinema'),
('''Kaptan Amerika'' karakterini kim canlandırır?', '["Chris Evans","Chris Hemsworth","Sebastian Stan","Anthony Mackie"]'::jsonb, 0, 'sinema'),
('''Schindler''in Listesi'' filminin yönetmeni kimdir?', '["Steven Spielberg","Roman Polanski","Scorsese","Coppola"]'::jsonb, 0, 'sinema'),
('''Esaretin Bedeli'' (The Shawshank Redemption) hangi ünlü yazarın öyküsünden uyarlanmıştır?', '["Stephen King","John Grisham","Dan Brown","Michael Crichton"]'::jsonb, 0, 'sinema'),
('''The Silence of the Lambs'' filminde Hannibal Lecter''i kim canlandırır?', '["Anthony Hopkins","Al Pacino","Robert De Niro","Gary Oldman"]'::jsonb, 0, 'sinema'),
('''Léon: The Professional'' filminde küçük kız rolündeki oyuncu kimdir?', '["Natalie Portman","Scarlett Johansson","Kirsten Dunst","Anne Hathaway"]'::jsonb, 0, 'sinema'),
('''Kill Bill'' filminin yönetmeni kimdir?', '["Quentin Tarantino","Robert Rodriguez","Guy Ritchie","David Fincher"]'::jsonb, 0, 'sinema'),
('''Alien'' (Yaratık) filminin yönetmeni kimdir?', '["Ridley Scott","James Cameron","John Carpenter","Spielberg"]'::jsonb, 0, 'sinema'),
('''The Terminator'' filminde başrol oyuncusu kimdir?', '["Arnold Schwarzenegger","Sylvester Stallone","Bruce Willis","Jean-Claude Van Damme"]'::jsonb, 0, 'sinema'),
('''Rocky'' filminin başrol oyuncusu ve senaristi kimdir?', '["Sylvester Stallone","Arnold Schwarzenegger","Chuck Norris","Dolph Lundgren"]'::jsonb, 0, 'sinema'),
('''The Lion King'' hangi tür bir filmdir?', '["Animasyon","Belgesel","Aksiyon","Korku"]'::jsonb, 0, 'sinema'),
('''Toy Story'' filmini üreten animasyon stüdyosu hangisidir?', '["Pixar","DreamWorks","Disney (2B)","Illumination"]'::jsonb, 0, 'sinema'),
('''Frozen'' (Karlar Ülkesi) filmini hangi stüdyo yapmıştır?', '["Disney","Pixar","DreamWorks","Warner"]'::jsonb, 0, 'sinema'),
('''Spirited Away'' animesinin yönetmeni kimdir?', '["Hayao Miyazaki","Makoto Shinkai","Satoshi Kon","Isao Takahata"]'::jsonb, 0, 'sinema'),
('''The Matrix'' serisini yöneten kardeşler hangisidir?', '["Wachowski Kardeşler","Coen Kardeşler","Russo Kardeşler","Nolan Kardeşler"]'::jsonb, 0, 'sinema'),
('''Avengers: Endgame'' hangi film evrenine aittir?', '["Marvel","DC","Star Wars","Harry Potter"]'::jsonb, 0, 'sinema'),
('''Batman'' hangi çizgi roman evreninin kahramanıdır?', '["DC","Marvel","Image","Dark Horse"]'::jsonb, 0, 'sinema'),
('''Spider-Man'' hangi çizgi roman evreninin kahramanıdır?', '["Marvel","DC","Image","Valiant"]'::jsonb, 0, 'sinema'),
('''La La Land'' filminin başrol kadın oyuncusu kimdir?', '["Emma Stone","Jennifer Lawrence","Anne Hathaway","Natalie Portman"]'::jsonb, 0, 'sinema'),
('''Kaç Para Kaç'' değil, ''Vizontele'' filminin yönetmenlerinden biri kimdir?', '["Yılmaz Erdoğan","Cem Yılmaz","Şahan Gökbakar","Çağan Irmak"]'::jsonb, 0, 'sinema'),
('''G.O.R.A.'' filminin başrol oyuncusu ve senaristi kimdir?', '["Cem Yılmaz","Yılmaz Erdoğan","Şahan Gökbakar","Ata Demirer"]'::jsonb, 0, 'sinema'),
('''Recep İvedik'' karakterini canlandıran oyuncu kimdir?', '["Şahan Gökbakar","Cem Yılmaz","Ata Demirer","Yılmaz Erdoğan"]'::jsonb, 0, 'sinema'),
('''Hababam Sınıfı'' filmleri hangi türdedir?', '["Komedi","Korku","Bilim kurgu","Belgesel"]'::jsonb, 0, 'sinema'),
('''E.T.'' filminin yönetmeni kimdir?', '["Steven Spielberg","George Lucas","Ridley Scott","James Cameron"]'::jsonb, 0, 'sinema'),
('''Dune'' (2021) filminin yönetmeni kimdir?', '["Denis Villeneuve","Christopher Nolan","Ridley Scott","David Lynch"]'::jsonb, 0, 'sinema'),
-- ===================== MÜZİK (50) =====================
('''Beethoven'' hangi müzik türünün bestecisidir?', '["Klasik","Caz","Rock","Pop"]'::jsonb, 0, 'muzik'),
('''Dokuzuncu Senfoni'' hangi bestecinin eseridir?', '["Beethoven","Mozart","Bach","Chopin"]'::jsonb, 0, 'muzik'),
('''The Beatles'' grubu hangi ülkedendir?', '["İngiltere","ABD","Almanya","Avustralya"]'::jsonb, 0, 'muzik'),
('''Bohemian Rhapsody'' şarkısı hangi gruba aittir?', '["Queen","The Rolling Stones","Led Zeppelin","Pink Floyd"]'::jsonb, 0, 'muzik'),
('''King of Pop'' olarak anılan sanatçı kimdir?', '["Michael Jackson","Elvis Presley","Prince","Freddie Mercury"]'::jsonb, 0, 'muzik'),
('''King of Rock and Roll'' olarak anılan sanatçı kimdir?', '["Elvis Presley","Chuck Berry","Little Richard","Buddy Holly"]'::jsonb, 0, 'muzik'),
('Bir orkestrayı yöneten kişiye ne denir?', '["Şef (orkestra şefi)","Solist","Besteci","Prodüktör"]'::jsonb, 0, 'muzik'),
('Piyano kaç tuşa sahiptir (standart)?', '["88","76","61","100"]'::jsonb, 0, 'muzik'),
('Bir gitarda genellikle kaç tel bulunur?', '["6","4","5","7"]'::jsonb, 0, 'muzik'),
('Kemanda ses yayı neyle sürtülerek çıkarılır?', '["Yay","Mızrap","Çubuk","Parmak"]'::jsonb, 0, 'muzik'),
('''Nefesli çalgı'' olan enstrüman hangisidir?', '["Flüt","Keman","Gitar","Piyano"]'::jsonb, 0, 'muzik'),
('''Vurmalı çalgı'' olan enstrüman hangisidir?', '["Davul","Keman","Flüt","Gitar"]'::jsonb, 0, 'muzik'),
('''Yaylı çalgı'' olan enstrüman hangisidir?', '["Keman","Trompet","Davul","Klarnet"]'::jsonb, 0, 'muzik'),
('Türk halk müziğinin en yaygın telli çalgısı hangisidir?', '["Bağlama (saz)","Ud","Kanun","Ney"]'::jsonb, 0, 'muzik'),
('''Ney'' hangi tür bir çalgıdır?', '["Nefesli","Telli","Vurmalı","Yaylı"]'::jsonb, 0, 'muzik'),
('Türk sanat müziğinin efsane sesi ''Zeki Müren'' hangi lakapla anılır?', '["Sanat Güneşi","Paşa","Beyefendi","Üstad"]'::jsonb, 0, 'muzik'),
('Rock and Roll müziği ilk olarak hangi ülkede popülerleşmiştir?', '["ABD","İngiltere","Almanya","Fransa"]'::jsonb, 0, 'muzik'),
('''Thriller'' albümü hangi sanatçıya aittir?', '["Michael Jackson","Prince","Madonna","Whitney Houston"]'::jsonb, 0, 'muzik'),
('''Like a Prayer'' şarkısıyla tanınan ''Pop Kraliçesi'' kimdir?', '["Madonna","Whitney Houston","Cher","Janet Jackson"]'::jsonb, 0, 'muzik'),
('''Shape of You'' şarkısı hangi sanatçıya aittir?', '["Ed Sheeran","Justin Bieber","Bruno Mars","Sam Smith"]'::jsonb, 0, 'muzik'),
('''Rolling in the Deep'' şarkısı hangi sanatçıya aittir?', '["Adele","Rihanna","Beyoncé","Lady Gaga"]'::jsonb, 0, 'muzik'),
('''Bad Guy'' şarkısıyla tanınan genç sanatçı kimdir?', '["Billie Eilish","Ariana Grande","Dua Lipa","Olivia Rodrigo"]'::jsonb, 0, 'muzik'),
('Bir müzik eserinin hızını belirten terim nedir?', '["Tempo","Nota","Akort","Ritim"]'::jsonb, 0, 'muzik'),
('Notaların yazıldığı beş çizgili sisteme ne denir?', '["Porte","Anahtar","Akort","Oktav"]'::jsonb, 0, 'muzik'),
('Do-Re-Mi-Fa-Sol-La-Si dizisine ne denir?', '["Nota dizisi (gam)","Akor","Ritim","Tempo"]'::jsonb, 0, 'muzik'),
('''Caz'' (Jazz) müziği ağırlıklı olarak hangi ülkede doğmuştur?', '["ABD","Küba","Brezilya","İngiltere"]'::jsonb, 0, 'muzik'),
('''Tango'' müziği ve dansı hangi ülkeyle özdeşleşir?', '["Arjantin","İspanya","Meksika","Brezilya"]'::jsonb, 0, 'muzik'),
('''Reggae'' müziği hangi ülkeden çıkmıştır?', '["Jamaika","Küba","Brezilya","Nijerya"]'::jsonb, 0, 'muzik'),
('''Samba'' müziği hangi ülkeyle özdeşleşir?', '["Brezilya","Arjantin","Portekiz","İspanya"]'::jsonb, 0, 'muzik'),
('''Flamenko'' hangi ülkenin geleneksel müzik/dansıdır?', '["İspanya","İtalya","Yunanistan","Fransa"]'::jsonb, 0, 'muzik'),
('''Sultans of Swing'' şarkısı hangi gruba aittir?', '["Dire Straits","Eagles","Pink Floyd","U2"]'::jsonb, 0, 'muzik'),
('''Hotel California'' şarkısı hangi gruba aittir?', '["Eagles","Queen","The Doors","Nirvana"]'::jsonb, 0, 'muzik'),
('''Smells Like Teen Spirit'' şarkısı hangi gruba aittir?', '["Nirvana","Pearl Jam","Metallica","Soundgarden"]'::jsonb, 0, 'muzik'),
('''Imagine'' şarkısı hangi sanatçıya aittir?', '["John Lennon","Paul McCartney","Bob Dylan","David Bowie"]'::jsonb, 0, 'muzik'),
('Türk rock müziğinin öncülerinden ''Barış Manço'' hangi enstrümanı çalardı?', '["Gitar","Keman","Piyano","Davul"]'::jsonb, 0, 'muzik'),
('''Sarı Çizmeli Mehmet Ağa'' şarkısı hangi sanatçıya aittir?', '["Barış Manço","Cem Karaca","Erkin Koray","MFÖ"]'::jsonb, 0, 'muzik'),
('Arabesk müziğin efsane ismi ''Orhan Gencebay'' hangi enstrümanla ünlüdür?', '["Bağlama","Keman","Ud","Kanun"]'::jsonb, 0, 'muzik'),
('''Megastar'' lakabıyla tanınan Türk pop sanatçısı kimdir?', '["Tarkan","Kenan Doğulu","Mustafa Sandal","Serdar Ortaç"]'::jsonb, 0, 'muzik'),
('''Şımarık'' (Kiss Kiss) şarkısıyla dünyaca ünlenen Türk sanatçı kimdir?', '["Tarkan","Sezen Aksu","Ajda Pekkan","Sertab Erener"]'::jsonb, 0, 'muzik'),
('2003 Eurovision''u ''Everyway That I Can'' ile kazanan Türk sanatçı kimdir?', '["Sertab Erener","Sezen Aksu","Hadise","Athena"]'::jsonb, 0, 'muzik'),
('Türk pop müziğinin ''Minik Serçe'' lakaplı sanatçısı kimdir?', '["Sezen Aksu","Ajda Pekkan","Nilüfer","Aşkın Nur Yengi"]'::jsonb, 0, 'muzik'),
('''Süperstar'' lakaplı Türk sanatçı kimdir?', '["Ajda Pekkan","Sezen Aksu","Nilüfer","Bülent Ersoy"]'::jsonb, 0, 'muzik'),
('Bir şarkının tekrar eden ana bölümüne ne denir?', '["Nakarat","Kıta","Intro","Solo"]'::jsonb, 0, 'muzik'),
('Opera sanatçılarının en tiz kadın ses türü hangisidir?', '["Soprano","Alto","Tenor","Bas"]'::jsonb, 0, 'muzik'),
('Erkeklerde en kalın (pes) ses türü hangisidir?', '["Bas","Tenor","Soprano","Alto"]'::jsonb, 0, 'muzik'),
('''DJ'' kısaltması neyi ifade eder?', '["Disc Jockey","Digital Jam","Dance Join","Drum Jockey"]'::jsonb, 0, 'muzik'),
('''Hip-hop'' müzik türünde konuşur gibi ritmik söyleme tarzına ne denir?', '["Rap","Scat","Yodel","Beatbox"]'::jsonb, 0, 'muzik'),
('Mozart hangi ülkede doğmuştur?', '["Avusturya","Almanya","İtalya","Fransa"]'::jsonb, 0, 'muzik'),
('''Dört Mevsim'' konçertosunun bestecisi kimdir?', '["Vivaldi","Bach","Handel","Mozart"]'::jsonb, 0, 'muzik'),
('Elektronik müzikte tekrarlayan ritim kalıbına ne denir?', '["Beat (ritim)","Akort","Porte","Nota"]'::jsonb, 0, 'muzik'),
-- ===================== TEKNOLOJİ (50) =====================
('''WWW'' kısaltmasının açılımı nedir?', '["World Wide Web","World Web Wide","Wide World Web","Web World Wide"]'::jsonb, 0, 'teknoloji'),
('Apple şirketinin kurucularından biri kimdir?', '["Steve Jobs","Bill Gates","Mark Zuckerberg","Larry Page"]'::jsonb, 0, 'teknoloji'),
('Microsoft''un kurucusu kimdir?', '["Bill Gates","Steve Jobs","Elon Musk","Jeff Bezos"]'::jsonb, 0, 'teknoloji'),
('Facebook''un kurucusu kimdir?', '["Mark Zuckerberg","Jack Dorsey","Larry Page","Evan Spiegel"]'::jsonb, 0, 'teknoloji'),
('Tesla ve SpaceX şirketlerinin CEO''su kimdir?', '["Elon Musk","Jeff Bezos","Tim Cook","Sundar Pichai"]'::jsonb, 0, 'teknoloji'),
('Amazon''un kurucusu kimdir?', '["Jeff Bezos","Bill Gates","Larry Ellison","Michael Dell"]'::jsonb, 0, 'teknoloji'),
('Google arama motorunu kuran isimlerden biri kimdir?', '["Larry Page","Steve Jobs","Bill Gates","Jack Ma"]'::jsonb, 0, 'teknoloji'),
('Bilgisayarın ''beyni'' olarak adlandırılan bileşen hangisidir?', '["İşlemci (CPU)","RAM","Ekran kartı","Sabit disk"]'::jsonb, 0, 'teknoloji'),
('''RAM'' ne tür bir bellektir?', '["Geçici (rastgele erişimli)","Kalıcı","Sadece okunabilir","Optik"]'::jsonb, 0, 'teknoloji'),
('''HTML'' ne için kullanılır?', '["Web sayfası oluşturma","Video düzenleme","Resim çizme","Ağ yönetimi"]'::jsonb, 0, 'teknoloji'),
('Bir bilgisayar ağında verilerin gönderildiği en küçük birime ne denir?', '["Paket","Piksel","Bit dizisi","Klasör"]'::jsonb, 0, 'teknoloji'),
('1 byte kaç bit''ten oluşur?', '["8","4","16","2"]'::jsonb, 0, 'teknoloji'),
('''USB'' kısaltmasının açılımı nedir?', '["Universal Serial Bus","United System Bus","Ultra Speed Bus","Universal Serial Board"]'::jsonb, 0, 'teknoloji'),
('İnternette bir web sitesinin adresine ne denir?', '["URL","HTML","HTTP kodu","IP dosyası"]'::jsonb, 0, 'teknoloji'),
('''Wi-Fi'' teknolojisi neyi sağlar?', '["Kablosuz internet","Kablolu ağ","Uydu yayını","Bluetooth ses"]'::jsonb, 0, 'teknoloji'),
('Android işletim sistemi hangi şirkete aittir?', '["Google","Apple","Microsoft","Samsung"]'::jsonb, 0, 'teknoloji'),
('iPhone hangi şirket tarafından üretilir?', '["Apple","Samsung","Google","Huawei"]'::jsonb, 0, 'teknoloji'),
('''AI'' kısaltması neyi ifade eder?', '["Yapay Zekâ","Otomatik İşlem","İleri İnternet","Analog İşlemci"]'::jsonb, 0, 'teknoloji'),
('''Bug'' yazılım dünyasında ne anlama gelir?', '["Yazılım hatası","Yeni özellik","Güncelleme","Virüs koruması"]'::jsonb, 0, 'teknoloji'),
('Bilgisayarları zararlı şekilde etkileyen kötü amaçlı yazılıma ne denir?', '["Virüs","Piksel","Çerez","Sürücü"]'::jsonb, 0, 'teknoloji'),
('''Cloud'' (bulut) bilişim neyi ifade eder?', '["Uzak sunucularda veri depolama","Hava durumu tahmini","Yerel disk yedekleme","Kablosuz şarj"]'::jsonb, 0, 'teknoloji'),
('Verileri şifreleyip fidye isteyen zararlı yazılım türü hangisidir?', '["Fidye yazılımı (ransomware)","Solucan","Truva atı","Reklam yazılımı"]'::jsonb, 0, 'teknoloji'),
('Bitcoin hangi teknolojiyle çalışır?', '["Blok zinciri","Yapay zekâ","Bulut","5G"]'::jsonb, 0, 'teknoloji'),
('''5G'' hangi alanda kullanılan bir teknolojidir?', '["Mobil iletişim","Görüntü işleme","Yazılım dili","Veritabanı"]'::jsonb, 0, 'teknoloji'),
('Python nedir?', '["Programlama dili","İşletim sistemi","Antivirüs","Web tarayıcısı"]'::jsonb, 0, 'teknoloji'),
('''CPU'' kısaltmasının açılımı nedir?', '["Central Processing Unit","Computer Personal Unit","Central Power Unit","Core Processing Utility"]'::jsonb, 0, 'teknoloji'),
('İlk programlanabilir elektronik bilgisayarlardan biri hangisidir?', '["ENIAC","MacBook","Windows 95","Commodore 64"]'::jsonb, 0, 'teknoloji'),
('Bir e-postada gönderilen dosya ekine İngilizce ne denir?', '["Attachment","Cookie","Banner","Cache"]'::jsonb, 0, 'teknoloji'),
('Web tarayıcısı olan hangisidir?', '["Google Chrome","Photoshop","Excel","Windows"]'::jsonb, 0, 'teknoloji'),
('''SSD'' ne tür bir depolama birimidir?', '["Katı hal sürücüsü","Optik disk","Manyetik teyp","Disket"]'::jsonb, 0, 'teknoloji'),
('Bir web sitesine girildiğinde tarayıcıda saklanan küçük verilere ne denir?', '["Çerez (cookie)","Piksel","Widget","Byte"]'::jsonb, 0, 'teknoloji'),
('''QR kod'' ile ne yapılır?', '["Kamerayla okutup bilgiye erişme","Şifre kırma","Dosya sıkıştırma","Ses kaydı"]'::jsonb, 0, 'teknoloji'),
('''VPN'' temel olarak neyi sağlar?', '["Güvenli/özel ağ bağlantısı","Ekran büyütme","Pil tasarrufu","Ses artırma"]'::jsonb, 0, 'teknoloji'),
('Bilgisayar faresini (mouse) icat eden mühendis kimdir?', '["Douglas Engelbart","Alan Turing","Steve Wozniak","Dennis Ritchie"]'::jsonb, 0, 'teknoloji'),
('Modern bilgisayar biliminin babası sayılan ve şifre çözen matematikçi kimdir?', '["Alan Turing","Charles Babbage","John von Neumann","Ada Lovelace"]'::jsonb, 0, 'teknoloji'),
('İlk bilgisayar programcısı kabul edilen kişi kimdir?', '["Ada Lovelace","Grace Hopper","Marie Curie","Hedy Lamarr"]'::jsonb, 0, 'teknoloji'),
('Bir yazılımın kaynak kodunun herkese açık olduğu modele ne denir?', '["Açık kaynak","Kapalı kaynak","Freemium","Lisanslı"]'::jsonb, 0, 'teknoloji'),
('''GPS'' teknolojisi ne için kullanılır?', '["Konum belirleme","Ses kaydı","Görüntü işleme","Veri şifreleme"]'::jsonb, 0, 'teknoloji'),
('Sanal gerçeklik için kullanılan cihaz tipine ne denir?', '["VR gözlüğü","Klavye","Yazıcı","Modem"]'::jsonb, 0, 'teknoloji'),
('''Streaming'' ne anlama gelir?', '["İçeriği indirmeden anlık izleme/dinleme","Dosya sıkıştırma","Yazıcı kuyruğu","Yedekleme"]'::jsonb, 0, 'teknoloji'),
('YouTube hangi şirkete aittir?', '["Google","Meta","Amazon","Microsoft"]'::jsonb, 0, 'teknoloji'),
('Instagram ve WhatsApp hangi şirkete aittir?', '["Meta (Facebook)","Google","Twitter","Apple"]'::jsonb, 0, 'teknoloji'),
('Bir bilgisayarın açılırken çalıştırdığı temel yazılıma ne denir?', '["İşletim sistemi","Tarayıcı","Antivirüs","Editör"]'::jsonb, 0, 'teknoloji'),
('Windows işletim sistemi hangi şirkete aittir?', '["Microsoft","Apple","Google","IBM"]'::jsonb, 0, 'teknoloji'),
('macOS işletim sistemi hangi şirkete aittir?', '["Apple","Microsoft","Google","Linux"]'::jsonb, 0, 'teknoloji'),
('''e-posta'' göndermek için kullanılan işaret hangisidir?', '["@","#","&","%"]'::jsonb, 0, 'teknoloji'),
('Bir ekranın çözünürlüğünü oluşturan en küçük noktaya ne denir?', '["Piksel","Bit","Byte","Voksel"]'::jsonb, 0, 'teknoloji'),
('Yapay zekâ sohbet uygulamalarının temelindeki modele genel olarak ne denir?', '["Dil modeli","Tablo modeli","Grafik motoru","Derleyici"]'::jsonb, 0, 'teknoloji'),
('''Open source'' işletim sistemi çekirdeği olan Linux''u geliştiren kişi kimdir?', '["Linus Torvalds","Bill Gates","Steve Jobs","Richard Stallman"]'::jsonb, 0, 'teknoloji'),
('Bir bilgisayara bağlanan çevre birimlerinden ''çıkış birimi'' olan hangisidir?', '["Yazıcı","Klavye","Fare","Tarayıcı"]'::jsonb, 0, 'teknoloji'),
-- ===================== KARIŞIK / GENEL (40) =====================
('Bir yılda kaç ay vardır?', '["12","10","11","13"]'::jsonb, 0, 'karisik'),
('Bir haftada kaç gün vardır?', '["7","5","6","8"]'::jsonb, 0, 'karisik'),
('Gökkuşağında kaç ana renk vardır?', '["7","5","6","8"]'::jsonb, 0, 'karisik'),
('Trafik ışıklarında ''dur'' anlamına gelen renk hangisidir?', '["Kırmızı","Yeşil","Sarı","Mavi"]'::jsonb, 0, 'karisik'),
('Bir düzine kaç adettir?', '["12","10","6","20"]'::jsonb, 0, 'karisik'),
('Satrançta oyuna hangi taş başlar?', '["Beyaz","Siyah","Kırmızı","Yeşil"]'::jsonb, 0, 'karisik'),
('Bir üçgenin iç açıları toplamı kaç derecedir?', '["180","360","90","270"]'::jsonb, 0, 'karisik'),
('Bir karenin kaç kenarı vardır?', '["4","3","5","6"]'::jsonb, 0, 'karisik'),
('Dünyada en çok konuşulan ana dil hangisidir?', '["Çince (Mandarin)","İngilizce","İspanyolca","Hintçe"]'::jsonb, 0, 'karisik'),
('Bir asır kaç yıldır?', '["100","10","50","1000"]'::jsonb, 0, 'karisik'),
('İnsan elinde kaç parmak vardır?', '["5","4","6","10"]'::jsonb, 0, 'karisik'),
('Bir futbol topunun şekli nasıldır?', '["Küre","Oval","Küp","Silindir"]'::jsonb, 0, 'karisik'),
('Arıların ürettiği tatlı besin nedir?', '["Bal","Süt","Reçel","Pekmez"]'::jsonb, 0, 'karisik'),
('İneklerden elde edilen içecek nedir?', '["Süt","Bal","Su","Çay"]'::jsonb, 0, 'karisik'),
('Türk bayrağında hangi iki sembol bulunur?', '["Ay ve yıldız","Güneş ve kartal","Aslan ve kılıç","Zeytin dalı"]'::jsonb, 0, 'karisik'),
('Trafikte yaya geçidi genellikle hangi desende olur?', '["Beyaz şeritler (zebra)","Kırmızı daireler","Sarı üçgenler","Mavi kareler"]'::jsonb, 0, 'karisik'),
('Buzdolabının temel işlevi nedir?', '["Soğutma","Isıtma","Kurutma","Aydınlatma"]'::jsonb, 0, 'karisik'),
('Pusula hangi yönü gösterir?', '["Kuzey","Güney","Doğu","Batı"]'::jsonb, 0, 'karisik'),
('Bir günde kaç saat vardır?', '["24","12","36","48"]'::jsonb, 0, 'karisik'),
('Bir saatte kaç dakika vardır?', '["60","100","30","90"]'::jsonb, 0, 'karisik'),
('Deveyi çölde ünlü yapan özelliği nedir?', '["Uzun süre susuz kalabilmesi","Uçabilmesi","Yüzebilmesi","Kar sevmesi"]'::jsonb, 0, 'karisik'),
('En hızlı kara hayvanı hangisidir?', '["Çita","Aslan","Fil","Zürafa"]'::jsonb, 0, 'karisik'),
('Karada yaşayan en büyük hayvan hangisidir?', '["Fil","Zürafa","Gergedan","Su aygırı"]'::jsonb, 0, 'karisik'),
('Denizde yaşayan en büyük hayvan hangisidir?', '["Mavi balina","Köpekbalığı","Yunus","Ahtapot"]'::jsonb, 0, 'karisik'),
('Örümceğin kaç bacağı vardır?', '["8","6","10","4"]'::jsonb, 0, 'karisik'),
('Bir zar kaç yüzlüdür?', '["6","4","8","12"]'::jsonb, 0, 'karisik'),
('Gece gökyüzünde bize en yakın yıldız hangisidir?', '["Güneş","Ay","Kutup Yıldızı","Sirius"]'::jsonb, 0, 'karisik'),
('Mevsimlerin sırasıyla ilki ilkbahardan sonra hangisidir?', '["Yaz","Kış","Sonbahar","İlkbahar"]'::jsonb, 0, 'karisik'),
('Bir yılda kaç mevsim vardır?', '["4","2","3","6"]'::jsonb, 0, 'karisik'),
('Kaplumbağalar neyle ünlüdür?', '["Yavaş yürümeleri","Uçmaları","Hızlı koşmaları","Şarkı söylemeleri"]'::jsonb, 0, 'karisik'),
('Elektriği ileten en yaygın metal hangisidir?', '["Bakır","Tahta","Plastik","Cam"]'::jsonb, 0, 'karisik'),
('Bir kilogramda kaç gram vardır?', '["1000","100","500","10"]'::jsonb, 0, 'karisik'),
('Bir metrede kaç santimetre vardır?', '["100","10","1000","50"]'::jsonb, 0, 'karisik'),
('Kırmızı ve sarı renkleri karıştırınca hangi renk oluşur?', '["Turuncu","Yeşil","Mor","Kahverengi"]'::jsonb, 0, 'karisik'),
('Mavi ve sarı renkleri karıştırınca hangi renk oluşur?', '["Yeşil","Turuncu","Mor","Gri"]'::jsonb, 0, 'karisik'),
('Sağlıklı beslenmede günde önerilen su miktarı yaklaşık ne kadardır?', '["2 litre","5 litre","0,5 litre","10 litre"]'::jsonb, 0, 'karisik'),
('Bir baklava genellikle hangi tatlı türüdür?', '["Şerbetli tatlı","Sütlü tatlı","Meyveli tatlı","Çikolatalı pasta"]'::jsonb, 0, 'karisik'),
('İnsan kalbi dakikada ortalama kaç kez atar (dinlenme)?', '["70","30","150","10"]'::jsonb, 0, 'karisik'),
('Ampulü icat ederek yaygınlaştıran mucit kimdir?', '["Thomas Edison","Nikola Tesla","Graham Bell","Newton"]'::jsonb, 0, 'karisik'),
('Telefonu icat eden kişi kimdir?', '["Graham Bell","Edison","Tesla","Marconi"]'::jsonb, 0, 'karisik'),
-- ===================== TÜRKİYE / DÜNYA (50) =====================
('Türkiye''nin para birimi nedir?', '["Türk Lirası","Euro","Dolar","Dinar"]'::jsonb, 0, 'genel'),
('Türkiye''nin resmi dili hangisidir?', '["Türkçe","İngilizce","Arapça","Farsça"]'::jsonb, 0, 'genel'),
('Türkiye''nin en kalabalık ikinci şehri hangisidir?', '["Ankara","İstanbul","İzmir","Bursa"]'::jsonb, 0, 'genel'),
('Türkiye kaç ile ayrılmıştır?', '["81","67","73","85"]'::jsonb, 0, 'genel'),
('Anıtkabir hangi şehirdedir?', '["Ankara","İstanbul","İzmir","Samsun"]'::jsonb, 0, 'genel'),
('Efes Antik Kenti hangi ilimizdedir?', '["İzmir","Antalya","Muğla","Aydın"]'::jsonb, 0, 'genel'),
('Türkiye''nin milli marşı hangisidir?', '["İstiklal Marşı","Onuncu Yıl Marşı","İzmir Marşı","Ankara Marşı"]'::jsonb, 0, 'genel'),
('Türkiye''nin en büyük adası hangisidir?', '["Gökçeada","Bozcaada","Marmara Adası","Büyükada"]'::jsonb, 0, 'genel'),
('Boğaz Köprüsü hangi şehirdedir?', '["İstanbul","İzmit","Çanakkale","İzmir"]'::jsonb, 0, 'genel'),
('Nemrut Dağı''ndaki dev heykeller hangi ilimizdedir?', '["Adıyaman","Malatya","Gaziantep","Şanlıurfa"]'::jsonb, 0, 'genel'),
('Sümela Manastırı hangi ilimizdedir?', '["Trabzon","Rize","Artvin","Giresun"]'::jsonb, 0, 'genel'),
('Göbeklitepe hangi ilimizdedir?', '["Şanlıurfa","Mardin","Diyarbakır","Batman"]'::jsonb, 0, 'genel'),
('Türkiye''nin en uzun sahil şeridine sahip bölgesi hangisidir?', '["Ege","Karadeniz","Akdeniz","Marmara"]'::jsonb, 0, 'genel'),
('Türkiye''de çay üretimiyle ünlü il hangisidir?', '["Rize","Trabzon","Ordu","Giresun"]'::jsonb, 0, 'genel'),
('Türkiye''de fındık üretimiyle ünlü il hangisidir?', '["Giresun","Rize","Antalya","Mersin"]'::jsonb, 0, 'genel'),
('Türkiye''de kayısı üretimiyle ünlü il hangisidir?', '["Malatya","Adana","Bursa","Konya"]'::jsonb, 0, 'genel'),
('BM (Birleşmiş Milletler) merkezi hangi şehirdedir?', '["New York","Cenevre","Paris","Brüksel"]'::jsonb, 0, 'genel'),
('NATO''nun merkezi hangi şehirdedir?', '["Brüksel","Paris","Londra","Washington"]'::jsonb, 0, 'genel'),
('Avrupa Birliği''nin ortak para birimi nedir?', '["Euro","Dolar","Sterlin","Frank"]'::jsonb, 0, 'genel'),
('Olimpiyatların modern haliyle ilk düzenlendiği şehir hangisidir?', '["Atina","Paris","Londra","Roma"]'::jsonb, 0, 'genel'),
('Eyfel Kulesi hangi şehirdedir?', '["Paris","Londra","Roma","Berlin"]'::jsonb, 0, 'genel'),
('Özgürlük Heykeli hangi şehirdedir?', '["New York","Washington","Boston","Chicago"]'::jsonb, 0, 'genel'),
('Big Ben saat kulesi hangi şehirdedir?', '["Londra","Paris","Berlin","Dublin"]'::jsonb, 0, 'genel'),
('Kolezyum hangi şehirdedir?', '["Roma","Atina","Napoli","Milano"]'::jsonb, 0, 'genel'),
('Çin Seddi hangi ülkededir?', '["Çin","Japonya","Moğolistan","Kore"]'::jsonb, 0, 'genel'),
('Taj Mahal hangi ülkededir?', '["Hindistan","Pakistan","İran","Bangladeş"]'::jsonb, 0, 'genel'),
('Piramitler hangi ülkededir?', '["Mısır","Meksika","Sudan","Irak"]'::jsonb, 0, 'genel'),
('Machu Picchu hangi ülkededir?', '["Peru","Meksika","Bolivya","Şili"]'::jsonb, 0, 'genel'),
('Kızıl Meydan hangi şehirdedir?', '["Moskova","St. Petersburg","Kiev","Minsk"]'::jsonb, 0, 'genel'),
('Sidney Opera Binası hangi ülkededir?', '["Avustralya","Yeni Zelanda","İngiltere","ABD"]'::jsonb, 0, 'genel'),
('Dünyanın en kalabalık şehirlerinden biri olan Tokyo hangi ülkededir?', '["Japonya","Çin","Güney Kore","Tayland"]'::jsonb, 0, 'genel'),
('İsviçre hangi ürünüyle dünyaca ünlüdür?', '["Çikolata ve saat","Kahve","Çay","Zeytin"]'::jsonb, 0, 'genel'),
('Vatikan neyin merkezidir?', '["Katolik Kilisesi","Ortodoks Kilisesi","İslam","Budizm"]'::jsonb, 0, 'genel'),
('Dünyanın en küçük ülkesi hangisidir?', '["Vatikan","Monako","Malta","San Marino"]'::jsonb, 0, 'genel'),
('İngiltere''nin para birimi nedir?', '["Sterlin","Euro","Dolar","Kron"]'::jsonb, 0, 'genel'),
('Japonya''nın para birimi nedir?', '["Yen","Won","Yuan","Ringgit"]'::jsonb, 0, 'genel'),
('ABD''nin para birimi nedir?', '["Dolar","Euro","Peso","Real"]'::jsonb, 0, 'genel'),
('Almanya, Fransa gibi ülkelerin bulunduğu kıta hangisidir?', '["Avrupa","Asya","Afrika","Amerika"]'::jsonb, 0, 'genel'),
('Nil Nehri hangi kıtadan geçer?', '["Afrika","Asya","Avrupa","Amerika"]'::jsonb, 0, 'genel'),
('Dünyanın en büyük çölü Sahra hangi kıtadadır?', '["Afrika","Asya","Avustralya","Amerika"]'::jsonb, 0, 'genel'),
('Kanguru hangi ülkeyle özdeşleşmiştir?', '["Avustralya","Brezilya","Hindistan","Kenya"]'::jsonb, 0, 'genel'),
('Panda hangi ülkeyle özdeşleşmiştir?', '["Çin","Japonya","Hindistan","Nepal"]'::jsonb, 0, 'genel'),
('Yılbaşı (yeni yıl) hangi ayın hangi günü kutlanır?', '["1 Ocak","31 Aralık","1 Aralık","24 Aralık"]'::jsonb, 0, 'genel'),
('29 Ekim hangi bayram olarak kutlanır?', '["Cumhuriyet Bayramı","Zafer Bayramı","Ulusal Egemenlik","Gençlik Bayramı"]'::jsonb, 0, 'genel'),
('23 Nisan hangi bayram olarak kutlanır?', '["Ulusal Egemenlik ve Çocuk Bayramı","Cumhuriyet Bayramı","Zafer Bayramı","Emek Bayramı"]'::jsonb, 0, 'genel'),
('19 Mayıs hangi bayram olarak kutlanır?', '["Gençlik ve Spor Bayramı","Cumhuriyet Bayramı","Zafer Bayramı","Egemenlik Bayramı"]'::jsonb, 0, 'genel'),
('30 Ağustos hangi bayram olarak kutlanır?', '["Zafer Bayramı","Cumhuriyet Bayramı","Gençlik Bayramı","Egemenlik Bayramı"]'::jsonb, 0, 'genel'),
('Dünyanın yedi harikasından ''Zeugma'' değil, hangisi Türkiye''dedir sorusunda İstanbul''daki tarihi yapı hangisidir?', '["Ayasofya","Kolezyum","Eyfel","Big Ben"]'::jsonb, 0, 'genel'),
('Türkiye hangi iki kıta üzerinde yer alır?', '["Asya ve Avrupa","Avrupa ve Afrika","Asya ve Afrika","Avrupa ve Amerika"]'::jsonb, 0, 'genel'),
('Kızılay ve Kızılhaç hangi alanda faaliyet gösterir?', '["İnsani yardım","Spor","Eğitim teknolojisi","Uzay"]'::jsonb, 0, 'genel')
on conflict (soru) do nothing;

-- Havuzda zaten var olan sorularla çakışanların yerine ek benzersiz sorular
-- (böylece net 500 yeni soru hedefi korunur; çakışanlar yukarıda atlanır).
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Osmanlı Devleti hangi yüzyılda kurulmuştur?', '["13. yüzyıl","15. yüzyıl","11. yüzyıl","17. yüzyıl"]'::jsonb, 0, 'tarih'),
('Kurtuluş Savaşı''nda Büyük Taarruz hangi yılda yapılmıştır?', '["1922","1920","1919","1923"]'::jsonb, 0, 'tarih'),
('Mondros Ateşkes Antlaşması hangi yılda imzalanmıştır?', '["1918","1920","1923","1915"]'::jsonb, 0, 'tarih'),
('Türkiye''de çok partili hayata geçiş hangi yıllarda başlamıştır?', '["1946","1923","1938","1960"]'::jsonb, 0, 'tarih'),
('Fatih Sultan Mehmet İstanbul''u fethettiğinde kaç yaşındaydı (yaklaşık)?', '["21","30","40","15"]'::jsonb, 0, 'tarih'),
('Antik Mısır''da ölülerin mumyalanmasının nedeni neydi?', '["Öbür dünya inancı","Süsleme","Ticaret","Savaş"]'::jsonb, 0, 'tarih'),
('İlk Çağ''da yazıyı bulan uygarlık hangisidir?', '["Sümerler","Hititler","Frigler","Lidyalılar"]'::jsonb, 0, 'tarih'),
('Parayı (madeni) ilk kullanan uygarlık hangisidir?', '["Lidyalılar","Sümerler","Persler","Fenikeliler"]'::jsonb, 0, 'tarih'),
('Alfabeyi geliştirip yayan Antik Çağ uygarlığı hangisidir?', '["Fenikeliler","Hititler","İyonlar","Urartular"]'::jsonb, 0, 'tarih'),
('Işığın bir prizmadan geçince renklere ayrılmasına ne denir?', '["Dispersiyon (ayrışma)","Yansıma","Kırılma","Soğurma"]'::jsonb, 0, 'bilim'),
('Bir cismin ağırlığı hangi büyüklüğe bağlıdır?', '["Yerçekimi","Renk","Sıcaklık","Hacim"]'::jsonb, 0, 'bilim'),
('İnsanda solunum sırasında dışarı verilen gaz ağırlıklı olarak hangisidir?', '["Karbondioksit","Oksijen","Azot","Hidrojen"]'::jsonb, 0, 'bilim'),
('Sindirim sistemimizde besinlerin emildiği ana organ hangisidir?', '["İnce bağırsak","Mide","Yemek borusu","Karaciğer"]'::jsonb, 0, 'bilim'),
('Bir maddenin sıvı halden gaz haline geçmesine ne denir?', '["Buharlaşma","Erime","Donma","Yoğuşma"]'::jsonb, 0, 'bilim'),
('Ay tutulması nasıl gerçekleşir?', '["Dünya, Güneş ile Ay arasına girince","Ay, Güneş''i kapatınca","Güneş sönünce","Ay büyüyünce"]'::jsonb, 0, 'bilim'),
('Bir bitkinin kök, gövde dışında besin ürettiği organ hangisidir?', '["Yaprak","Çiçek","Meyve","Tohum"]'::jsonb, 0, 'bilim'),
('Manyetik pusulanın iğnesi hangi kutba yönelir?', '["Kuzey","Güney","Doğu","Batı"]'::jsonb, 0, 'bilim'),
('Sesin bir engelden yansıyarak geri dönmesine ne denir?', '["Yankı (eko)","Kırılma","Titreşim","Rezonans"]'::jsonb, 0, 'bilim'),
('İnsan iskeletinde yaklaşık kaç kemik bulunur (yetişkin)?', '["206","150","300","100"]'::jsonb, 0, 'bilim'),
('Hangi gezegenin belirgin halkaları vardır?', '["Satürn","Mars","Venüs","Merkür"]'::jsonb, 0, 'bilim'),
('Türkiye''nin en kalabalık dördüncü şehri hangisidir?', '["Bursa","Antalya","Konya","Gaziantep"]'::jsonb, 0, 'cografya'),
('Ege Denizi Türkiye''nin hangi yönündedir?', '["Batı","Doğu","Kuzey","Güney"]'::jsonb, 0, 'cografya'),
('Karadeniz Türkiye''nin hangi yönündedir?', '["Kuzey","Güney","Batı","Doğu"]'::jsonb, 0, 'cografya'),
('Toros Dağları ağırlıklı olarak hangi bölgede uzanır?', '["Akdeniz","Karadeniz","Marmara","Ege"]'::jsonb, 0, 'cografya'),
('Portekiz''in başkenti neresidir?', '["Lizbon","Porto","Madrid","Faro"]'::jsonb, 0, 'cografya'),
('İsveç''in başkenti neresidir?', '["Stockholm","Oslo","Helsinki","Kopenhag"]'::jsonb, 0, 'cografya'),
('Norveç''in başkenti neresidir?', '["Oslo","Bergen","Stockholm","Helsinki"]'::jsonb, 0, 'cografya'),
('Meksika''nın başkenti neresidir?', '["Meksiko","Cancún","Guadalajara","Tijuana"]'::jsonb, 0, 'cografya'),
('Arjantin''in başkenti neresidir?', '["Buenos Aires","Córdoba","Rosario","Mendoza"]'::jsonb, 0, 'cografya'),
('Güney Kore''nin başkenti neresidir?', '["Seul","Busan","Incheon","Daegu"]'::jsonb, 0, 'cografya'),
('İran''ın başkenti neresidir?', '["Tahran","İsfahan","Şiraz","Tebriz"]'::jsonb, 0, 'cografya'),
('Fırat ve Dicle nehirleri arasındaki verimli bölgeye ne denir?', '["Mezopotamya","Anadolu","Trakya","Kafkasya"]'::jsonb, 0, 'cografya'),
('Bir haritada denizler genellikle hangi renkle gösterilir?', '["Mavi","Yeşil","Kahverengi","Sarı"]'::jsonb, 0, 'cografya'),
('''Ölü Deniz'' hangi özelliğiyle ünlüdür?', '["Çok tuzlu olması","Çok soğuk olması","Çok derin olması","Tatlı su olması"]'::jsonb, 0, 'cografya'),
('''Sefiller'' hangi ülke edebiyatının eseridir?', '["Fransız","Rus","İngiliz","Alman"]'::jsonb, 0, 'edebiyat'),
('''Karamazov Kardeşler'' romanının yazarı kimdir?', '["Dostoyevski","Tolstoy","Gogol","Turgenyev"]'::jsonb, 0, 'edebiyat'),
('Türk edebiyatında ''Sait Faik Abasıyanık'' hangi türde ünlüdür?', '["Öykü","Roman","Şiir","Tiyatro"]'::jsonb, 0, 'edebiyat'),
('''Safahat'' adlı eser hangi şaire aittir?', '["Mehmet Akif Ersoy","Yahya Kemal","Tevfik Fikret","Necip Fazıl"]'::jsonb, 0, 'edebiyat'),
('Ünlü ''Sherlock Holmes'' karakterini yaratan yazar kimdir?', '["Arthur Conan Doyle","Agatha Christie","Edgar Allan Poe","Jules Verne"]'::jsonb, 0, 'edebiyat'),
('''Denizler Altında Yirmi Bin Fersah'' romanının yazarı kimdir?', '["Jules Verne","H.G. Wells","Daniel Defoe","Robert L. Stevenson"]'::jsonb, 0, 'edebiyat'),
('Ünlü dedektif romanları yazarı ''Agatha Christie'' hangi ülkedendir?', '["İngiltere","Fransa","ABD","İtalya"]'::jsonb, 0, 'edebiyat'),
('Futbolda kaleciye geri pas elle alınırsa ne verilir?', '["Dolaylı serbest vuruş","Penaltı","Korner","Taç"]'::jsonb, 0, 'spor'),
('Bir basketbol maçı kaç periyottan oluşur (NBA)?', '["4","2","3","5"]'::jsonb, 0, 'spor'),
('Formula 1''de yarışın başlama iznini veren ışık rengi hangisidir?', '["Yeşil (ışıkların sönmesi)","Kırmızı","Sarı","Mavi"]'::jsonb, 0, 'spor'),
('Türkiye''nin milli sporlarından sayılan ''yağlı güreş'' hangi ilde yapılır?', '["Edirne (Kırkpınar)","Bursa","Manisa","Antalya"]'::jsonb, 0, 'spor'),
('Bir tenis maçında oyuncular arasındaki ağa ne denir?', '["File","Kale","Direk","Çizgi"]'::jsonb, 0, 'spor'),
('Okçulukta hedefin tam ortasına ne denir?', '["On (bullseye)","Çizgi","Kale","Set"]'::jsonb, 0, 'spor'),
('''Titanic'' filmi kaç Oscar kazanmıştır (11 ile rekora ortak)?', '["11","5","3","8"]'::jsonb, 0, 'sinema'),
('''Seven'' (Yedi) filminin yönetmeni kimdir?', '["David Fincher","Christopher Nolan","Ridley Scott","Martin Scorsese"]'::jsonb, 0, 'sinema'),
('''Gelecek'' değil, ''Geleceğe Dönüş'' filminde zaman makinesi hangi araçtır?', '["DeLorean","Batmobil","Uçan halı","Denizaltı"]'::jsonb, 0, 'sinema'),
('''Requiem for a Dream'' ve ''Black Swan'' yönetmeni kimdir?', '["Darren Aronofsky","David Lynch","Lars von Trier","Gaspar Noé"]'::jsonb, 0, 'sinema'),
('Animasyon filmi ''Shrek'' hangi stüdyonun yapımıdır?', '["DreamWorks","Pixar","Disney","Illumination"]'::jsonb, 0, 'sinema'),
('''We Will Rock You'' şarkısı hangi gruba aittir?', '["Queen","AC/DC","Kiss","The Who"]'::jsonb, 0, 'muzik'),
('''Stairway to Heaven'' şarkısı hangi gruba aittir?', '["Led Zeppelin","Deep Purple","Black Sabbath","The Rolling Stones"]'::jsonb, 0, 'muzik'),
('''Billie Jean'' şarkısı hangi sanatçıya aittir?', '["Michael Jackson","Prince","Lionel Richie","Stevie Wonder"]'::jsonb, 0, 'muzik'),
('Klasik müzikte ''Kuğu Gölü'' balesinin bestecisi kimdir?', '["Çaykovski","Beethoven","Chopin","Wagner"]'::jsonb, 0, 'muzik'),
('Bir bilgisayarda geçici olmayan, kalıcı depolama birimi hangisidir?', '["Sabit disk/SSD","RAM","İşlemci ön belleği","Ekran"]'::jsonb, 0, 'teknoloji'),
('''ChatGPT'' benzeri araçların ürettiği metinlere genel olarak ne denir?', '["Üretken yapay zekâ çıktısı","Donanım","Çerez","Sürücü"]'::jsonb, 0, 'teknoloji'),
('İki cihaz arasında kısa mesafeli kablosuz bağlantıyı sağlayan teknoloji hangisidir?', '["Bluetooth","GPS","Fiber","Uydu"]'::jsonb, 0, 'teknoloji'),
('Bir web adresinin başındaki güvenli protokol kısaltması hangisidir?', '["HTTPS","FTP","SMTP","POP3"]'::jsonb, 0, 'teknoloji'),
('Türk mutfağının dünyaca ünlü tatlısı ''baklava'' hangi şehirle özdeşleşmiştir?', '["Gaziantep","Trabzon","İzmir","Erzurum"]'::jsonb, 0, 'genel'),
('Klavyede en uzun tuş hangisidir?', '["Boşluk (space)","Enter","Shift","Tab"]'::jsonb, 0, 'teknoloji'),
('Bir futbol müsabakasında sahayı yöneten kişiye ne denir?', '["Hakem","Antrenör","Kaleci","Kaptan"]'::jsonb, 0, 'spor')
on conflict (soru) do nothing;

-- Doğru cevap hep A (0. şık) olmasın: SADECE bu partide eklenen soruların
-- şıklarını karıştır. Yeni sorular henüz hiçbir aktif maçta yer almadığı için
-- bu işlem devam eden maçları etkilemez (cevaplari_karistir mantığının aynısı).
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
