-- Genişletilmiş soru havuzu (Claude tarafından üretildi, API maliyeti yok)
-- Orta zorlukta, doğruluğu kesin genel kültür soruları
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
-- TARİH
('Malazgirt Savaşı hangi yıl yapılmıştır?', '["1071","1453","1299","1176"]', 0, 'tarih'),
('İstanbul hangi yıl fethedilmiştir?', '["1451","1453","1461","1444"]', 1, 'tarih'),
('Osmanlı Devleti''nin kuruluş yılı olarak genel kabul gören tarih hangisidir?', '["1299","1326","1281","1354"]', 0, 'tarih'),
('Fransız İhtilali hangi yıl başlamıştır?', '["1776","1789","1799","1804"]', 1, 'tarih'),
('II. Dünya Savaşı hangi yıl sona ermiştir?', '["1943","1944","1945","1946"]', 2, 'tarih'),
('Türkiye Büyük Millet Meclisi hangi tarihte açılmıştır?', '["23 Nisan 1920","29 Ekim 1923","19 Mayıs 1919","30 Ağustos 1922"]', 0, 'tarih'),
('Türkiye''nin ikinci cumhurbaşkanı kimdir?', '["Celal Bayar","Cemal Gürsel","İsmet İnönü","Fevzi Çakmak"]', 2, 'tarih'),
('Kurtuluş Savaşı sonunda imzalanan barış antlaşması hangisidir?', '["Sevr Antlaşması","Mudanya Ateşkesi","Lozan Antlaşması","Ankara Antlaşması"]', 2, 'tarih'),
('Lale Devri hangi padişah döneminde yaşanmıştır?', '["IV. Murad","III. Ahmet","II. Mahmud","I. Abdülhamid"]', 1, 'tarih'),
('Tarihte bilinen ilk Türk devleti hangisidir?', '["Göktürk Devleti","Uygur Devleti","Asya Hun Devleti","Avar Devleti"]', 2, 'tarih'),
('Berlin Duvarı hangi yıl yıkılmıştır?', '["1985","1989","1991","1993"]', 1, 'tarih'),
('1492''de Amerika kıtasına ulaşan denizci kimdir?', '["Vasco da Gama","Macellan","Kristof Kolomb","Amerigo Vespucci"]', 2, 'tarih'),
('Osmanlı''da ilk anayasa olan Kanun-i Esasi hangi yıl ilan edilmiştir?', '["1839","1856","1876","1908"]', 2, 'tarih'),
('Preveze Deniz Savaşı''nı kazanan ünlü Osmanlı denizcisi kimdir?', '["Turgut Reis","Barbaros Hayreddin Paşa","Piri Reis","Kılıç Ali Paşa"]', 1, 'tarih'),
('Mustafa Kemal Atatürk Samsun''a hangi tarihte çıkmıştır?', '["23 Nisan 1920","19 Mayıs 1919","29 Ekim 1923","10 Kasım 1918"]', 1, 'tarih'),
('Soyadı Kanunu hangi yıl kabul edilmiştir?', '["1928","1931","1934","1937"]', 2, 'tarih'),
('Türkiye''de kadınlara milletvekili seçme ve seçilme hakkı hangi yıl tanınmıştır?', '["1923","1930","1934","1946"]', 2, 'tarih'),
('I. Dünya Savaşı hangi yıl başlamıştır?', '["1912","1914","1916","1918"]', 1, 'tarih'),
('Bizans İmparatorluğu''nun başkenti hangi şehirdi?', '["Atina","Roma","Konstantinopolis","İskenderiye"]', 2, 'tarih'),
('Moğol İmparatorluğu''nun kurucusu kimdir?', '["Kubilay Han","Cengiz Han","Timur","Hülagü Han"]', 1, 'tarih'),
('Pasif direniş yöntemiyle Hindistan''ın bağımsızlığına öncülük eden lider kimdir?', '["Nehru","Mahatma Gandhi","Cinnah","Tagore"]', 1, 'tarih'),
('Amerika Birleşik Devletleri''nin ilk başkanı kimdir?', '["Thomas Jefferson","Abraham Lincoln","George Washington","John Adams"]', 2, 'tarih'),
('Titanic gemisi hangi yıl batmıştır?', '["1905","1912","1918","1923"]', 1, 'tarih'),
-- COĞRAFYA
('Türkiye''nin en yüksek dağı hangisidir?', '["Erciyes Dağı","Kaçkar Dağı","Ağrı Dağı","Uludağ"]', 2, 'cografya'),
('Türkiye kaç coğrafi bölgeye ayrılır?', '["5","6","7","8"]', 2, 'cografya'),
('Dünyanın en büyük sıcak çölü hangisidir?', '["Gobi Çölü","Sahra Çölü","Kalahari Çölü","Atacama Çölü"]', 1, 'cografya'),
('Avustralya''nın başkenti hangi şehirdir?', '["Sidney","Melbourne","Kanberra","Brisbane"]', 2, 'cografya'),
('Kanada''nın başkenti hangi şehirdir?', '["Toronto","Vancouver","Montreal","Ottawa"]', 3, 'cografya'),
('Brezilya''nın başkenti hangi şehirdir?', '["Rio de Janeiro","Sao Paulo","Brasilia","Salvador"]', 2, 'cografya'),
('Mısır''ın başkenti hangi şehirdir?', '["İskenderiye","Kahire","Luksor","Port Said"]', 1, 'cografya'),
('Aşağıdaki ülkelerden hangisinin toprakları hem Avrupa hem Asya kıtasındadır?', '["Yunanistan","Bulgaristan","Türkiye","Suriye"]', 2, 'cografya'),
('Van Gölü hangi coğrafi bölgededir?', '["Güneydoğu Anadolu","Doğu Anadolu","İç Anadolu","Karadeniz"]', 1, 'cografya'),
('Dünyanın en derin noktası olan çukur hangisidir?', '["Tonga Çukuru","Mariana Çukuru","Java Çukuru","Porto Riko Çukuru"]', 1, 'cografya'),
('Peri bacalarıyla ünlü Kapadokya''nın merkezi hangi ildedir?', '["Kayseri","Aksaray","Nevşehir","Niğde"]', 2, 'cografya'),
('Beyaz travertenleriyle ünlü Pamukkale hangi ildedir?', '["Aydın","Denizli","Muğla","Burdur"]', 1, 'cografya'),
('Türkiye''nin en büyük adası hangisidir?', '["Bozcaada","Marmara Adası","Gökçeada","Büyükada"]', 2, 'cografya'),
('Dünyanın en küçük kıtası hangisidir?', '["Antarktika","Avrupa","Avustralya","Güney Amerika"]', 2, 'cografya'),
('Amazon Ormanları''nın en büyük bölümü hangi ülkededir?', '["Peru","Kolombiya","Venezuela","Brezilya"]', 3, 'cografya'),
('Tac Mahal hangi ülkededir?', '["Pakistan","Hindistan","Bangladeş","İran"]', 1, 'cografya'),
('Norveç, İsveç ve Danimarka''nın bulunduğu bölgeye ne ad verilir?', '["Balkanlar","Baltık","İskandinavya","İberya"]', 2, 'cografya'),
('Türkiye''nin en doğusundaki il hangisidir?', '["Kars","Van","Iğdır","Hakkari"]', 2, 'cografya'),
('Dünyanın en büyük gölü hangisidir?', '["Superior Gölü","Hazar Denizi","Victoria Gölü","Baykal Gölü"]', 1, 'cografya'),
('Fırat ve Dicle nehirleri hangi körfeze dökülür?', '["Aden Körfezi","Umman Körfezi","Basra Körfezi","Süveyş Körfezi"]', 2, 'cografya'),
('İstanbul Boğazı hangi iki denizi birbirine bağlar?', '["Karadeniz - Ege","Marmara - Ege","Karadeniz - Marmara","Marmara - Akdeniz"]', 2, 'cografya'),
('Türkiye''nin en kuzey ucu olan İnceburun hangi ildedir?', '["Samsun","Sinop","Kastamonu","Zonguldak"]', 1, 'cografya'),
('Arjantin''in başkenti hangi şehirdir?', '["Santiago","Montevideo","Buenos Aires","Lima"]', 2, 'cografya'),
('"Yükselen Güneşin Ülkesi" olarak bilinen ülke hangisidir?', '["Çin","Güney Kore","Japonya","Tayland"]', 2, 'cografya'),
-- BİLİM
('Yetişkin bir insanın vücudunda kaç kemik bulunur?', '["186","206","226","246"]', 1, 'bilim'),
('İnsan kalbi kaç odacıktan oluşur?', '["2","3","4","5"]', 2, 'bilim'),
('Bitkiler fotosentez sırasında havadan hangi gazı alır?', '["Oksijen","Karbondioksit","Azot","Hidrojen"]', 1, 'bilim'),
('Atom çekirdeğinde hangi parçacıklar bulunur?', '["Proton ve elektron","Elektron ve nötron","Proton ve nötron","Sadece elektron"]', 2, 'bilim'),
('Evrensel kütle çekim yasasını ortaya koyan bilim insanı kimdir?', '["Galileo Galilei","Isaac Newton","Albert Einstein","Kepler"]', 1, 'bilim'),
('Görelilik kuramını geliştiren bilim insanı kimdir?', '["Isaac Newton","Nikola Tesla","Albert Einstein","Max Planck"]', 2, 'bilim'),
('Periyodik tabloda "H" simgesi hangi elementi gösterir?', '["Helyum","Hidrojen","Hafniyum","Cıva"]', 1, 'bilim'),
('Periyodik tabloda "Fe" simgesi hangi elementi gösterir?', '["Flor","Fosfor","Demir","Fermiyum"]', 2, 'bilim'),
('Periyodik tabloda "Ag" simgesi hangi elementi gösterir?', '["Altın","Gümüş","Alüminyum","Argon"]', 1, 'bilim'),
('Ses hangi ortamda en hızlı yayılır?', '["Boşlukta","Havada","Suda","Katılarda"]', 3, 'bilim'),
('Güneş''e en yakın gezegen hangisidir?', '["Venüs","Mars","Merkür","Dünya"]', 2, 'bilim'),
('Halley kuyruklu yıldızı yaklaşık kaç yılda bir Dünya''dan görülür?', '["26","50","76","100"]', 2, 'bilim'),
('Kırmızı kan hücrelerinin temel görevi nedir?', '["Mikroplarla savaşmak","Oksijen taşımak","Kanı pıhtılaştırmak","Hormon üretmek"]', 1, 'bilim'),
('Hangi vitamin güneş ışığı yardımıyla vücutta sentezlenir?', '["A vitamini","B12 vitamini","C vitamini","D vitamini"]', 3, 'bilim'),
('Su deniz seviyesinde kaç derecede kaynar?', '["90","100","110","120"]', 1, 'bilim'),
('Elektrik akımının birimi nedir?', '["Volt","Watt","Amper","Ohm"]', 2, 'bilim'),
('Kuvvetin birimi nedir?', '["Joule","Newton","Pascal","Watt"]', 1, 'bilim'),
('Mors alfabesini geliştiren mucit kimdir?', '["Graham Bell","Samuel Morse","Guglielmo Marconi","Nikola Tesla"]', 1, 'bilim'),
('Ampulü ticari olarak kullanılabilir hale getiren mucit olarak bilinen kişi kimdir?', '["Nikola Tesla","Thomas Edison","Benjamin Franklin","Michael Faraday"]', 1, 'bilim'),
('Radyoaktivite üzerine çalışmalarıyla iki Nobel Ödülü kazanan bilim insanı kimdir?', '["Lise Meitner","Marie Curie","Rosalind Franklin","Ada Lovelace"]', 1, 'bilim'),
('DNA''nın çift sarmal yapısını keşfeden bilim insanları kimlerdir?', '["Watson ve Crick","Curie ve Becquerel","Darwin ve Wallace","Bohr ve Rutherford"]', 0, 'bilim'),
('"Türlerin Kökeni" kitabıyla evrim teorisini ortaya koyan bilim insanı kimdir?', '["Gregor Mendel","Charles Darwin","Alfred Wallace","Jean-Baptiste Lamarck"]', 1, 'bilim'),
('Bilgisayarda geçici veri depolayan bellek türü hangisidir?', '["ROM","SSD","RAM","HDD"]', 2, 'bilim'),
('"WWW" kısaltmasının açılımı nedir?', '["World Wide Web","World Web Window","Wide World Web","Web World Wide"]', 0, 'bilim'),
('Gözün renkli kısmına ne ad verilir?', '["Retina","Kornea","İris","Göz bebeği"]', 2, 'bilim'),
('Vücut dengesinden sorumlu beyin bölümü hangisidir?', '["Beyincik","Omurilik soğanı","Hipotalamus","Beyin kabuğu"]', 0, 'bilim'),
('Kanın pıhtılaşmasında görev alan kan hücreleri hangileridir?', '["Alyuvarlar","Akyuvarlar","Trombositler","Plazma hücreleri"]', 2, 'bilim'),
('Işık yılı neyin ölçü birimidir?', '["Zamanın","Uzaklığın","Hızın","Parlaklığın"]', 1, 'bilim'),
('Doğada bilinen en sert mineral hangisidir?', '["Kuvars","Elmas","Topaz","Korindon"]', 1, 'bilim'),
('Hangi gezegen belirgin halkalarıyla ünlüdür?', '["Jüpiter","Uranüs","Satürn","Neptün"]', 2, 'bilim'),
('Ozon tabakası hangi zararlı ışınları süzer?', '["Kızılötesi","Ultraviyole","X ışınları","Gama ışınları"]', 1, 'bilim'),
('Mikroorganizmaları mikroskopla ilk kez gözlemleyen bilim insanı kimdir?', '["Louis Pasteur","Robert Hooke","Antonie van Leeuwenhoek","Robert Koch"]', 2, 'bilim'),
('Penguenler doğal olarak ağırlıklı hangi yarım kürede yaşar?', '["Kuzey Yarım Küre","Güney Yarım Küre","Her ikisinde eşit","Sadece Ekvator''da"]', 1, 'bilim'),
('Dinlenme halindeki yetişkin bir insanın kalbi dakikada ortalama kaç kez atar?', '["30-40","70-80","120-130","160-170"]', 1, 'bilim'),
('Vücut hücrelerinin çoğalmasını sağlayan hücre bölünmesi türü hangisidir?', '["Mayoz","Mitoz","Amitoz","Sitokinez"]', 1, 'bilim'),
('"Sabah Yıldızı" olarak da bilinen gezegen hangisidir?', '["Mars","Jüpiter","Venüs","Merkür"]', 2, 'bilim'),
-- SANAT
('"Guernica" tablosunun ressamı kimdir?', '["Salvador Dali","Pablo Picasso","Joan Miro","Henri Matisse"]', 1, 'sanat'),
('"Çığlık" tablosunun ressamı kimdir?', '["Edvard Munch","Gustav Klimt","Paul Cezanne","Claude Monet"]', 0, 'sanat'),
('"Son Akşam Yemeği" freskinin sanatçısı kimdir?', '["Michelangelo","Rafael","Leonardo da Vinci","Caravaggio"]', 2, 'sanat'),
('"Düşünen Adam" heykelinin sanatçısı kimdir?', '["Michelangelo","Auguste Rodin","Donatello","Bernini"]', 1, 'sanat'),
('"Dokuzuncu Senfoni" hangi bestecinin eseridir?', '["Mozart","Bach","Beethoven","Chopin"]', 2, 'sanat'),
('"Türk Beşleri" hangi sanat dalında tanınan gruptur?', '["Resim","Klasik müzik","Tiyatro","Heykel"]', 1, 'sanat'),
('"Carmen" operasının bestecisi kimdir?', '["Verdi","Puccini","Georges Bizet","Wagner"]', 2, 'sanat'),
('Karagöz ve Hacivat hangi geleneksel sanatın kahramanlarıdır?', '["Meddahlık","Gölge oyunu","Ortaoyunu","Kukla tiyatrosu"]', 1, 'sanat'),
('"Yıldızlı Gece" tablosunun ressamı kimdir?', '["Claude Monet","Paul Gauguin","Vincent van Gogh","Edouard Manet"]', 2, 'sanat'),
('Salvador Dali hangi sanat akımının temsilcisidir?', '["Kübizm","Empresyonizm","Sürrealizm","Ekspresyonizm"]', 2, 'sanat'),
('Bir oktavda kaç farklı nota adı vardır?', '["5","6","7","8"]', 2, 'sanat'),
('"Yedi Samuray" filminin yönetmeni kimdir?', '["Hayao Miyazaki","Akira Kurosawa","Yasujiro Ozu","Takeshi Kitano"]', 1, 'sanat'),
('Türk sinemasının ilk önemli yönetmeni kabul edilen kişi kimdir?', '["Lütfi Akad","Muhsin Ertuğrul","Metin Erksan","Halit Refiğ"]', 1, 'sanat'),
('Mimar Sinan''ın "ustalık eserim" dediği cami hangisidir?', '["Süleymaniye Camii","Şehzade Camii","Selimiye Camii","Mihrimah Sultan Camii"]', 2, 'sanat'),
('İstanbul''daki Süleymaniye Camii''nin mimarı kimdir?', '["Mimar Kemaleddin","Mimar Sinan","Sedefkar Mehmed Ağa","Davud Ağa"]', 1, 'sanat'),
('"Kuğu Gölü" balesinin bestecisi kimdir?', '["Stravinski","Çaykovski","Prokofyev","Rahmaninov"]', 1, 'sanat'),
('"Mavi Cami" olarak da bilinen İstanbul''daki cami hangisidir?', '["Süleymaniye Camii","Fatih Camii","Sultanahmet Camii","Yeni Cami"]', 2, 'sanat'),
('Geleneksel ebru sanatı nasıl yapılır?', '["Kağıt katlanarak","Su üzerine boya damlatılarak","Kumaş boyanarak","Cam üfleyerek"]', 1, 'sanat'),
-- SPOR
('Voleybolda bir takım sahada aynı anda kaç oyuncuyla oynar?', '["5","6","7","8"]', 1, 'spor'),
('Tenisin Grand Slam turnuvalarından hangisi çim kortta oynanır?', '["Roland Garros","ABD Açık","Wimbledon","Avustralya Açık"]', 2, 'spor'),
('Formula 1 tarihinde 7 şampiyonluğu bulunan Alman pilot kimdir?', '["Sebastian Vettel","Michael Schumacher","Nico Rosberg","Niki Lauda"]', 1, 'spor'),
('Basketbol hangi ülkede icat edilmiştir?', '["İngiltere","Kanada","ABD","Fransa"]', 2, 'spor'),
('Olimpiyat bayrağında kaç halka bulunur?', '["4","5","6","7"]', 1, 'spor'),
('Maraton koşusunun mesafesi yaklaşık kaç kilometredir?', '["32","38","42","50"]', 2, 'spor'),
('Naim Süleymanoğlu hangi spor dalında dünya çapında başarılar kazanmıştır?', '["Güreş","Boks","Halter","Atletizm"]', 2, 'spor'),
('Galatasaray UEFA Kupası''nı hangi yıl kazanmıştır?', '["1998","1999","2000","2001"]', 2, 'spor'),
('Satrançta her oyuncu oyuna kaç taşla başlar?', '["12","14","16","18"]', 2, 'spor'),
('Futbolda penaltı noktası kale çizgisine kaç metre uzaklıktadır?', '["9","10","11","12"]', 2, 'spor'),
('FIFA Dünya Kupası''nı en çok kazanan ülke hangisidir?', '["Almanya","İtalya","Arjantin","Brezilya"]', 3, 'spor'),
('Judo hangi ülkede doğmuş bir spor dalıdır?', '["Çin","Kore","Japonya","Tayland"]', 2, 'spor'),
('Hentbolda bir takım sahada kaç oyuncuyla oynar?', '["6","7","8","9"]', 1, 'spor'),
('Roland Garros tenis turnuvası hangi şehirde düzenlenir?', '["Londra","New York","Paris","Melbourne"]', 2, 'spor'),
('Türkiye A Milli Futbol Takımı 2002 Dünya Kupası''nda kaçıncı olmuştur?', '["Birinci","İkinci","Üçüncü","Dördüncü"]', 2, 'spor'),
('Hamza Yerlikaya hangi spor dalında olimpiyat şampiyonu olmuştur?', '["Halter","Güreş","Boks","Judo"]', 1, 'spor'),
('"Filenin Sultanları" lakabı hangi milli takımımıza aittir?', '["Kadın Basketbol","Kadın Voleybol","Kadın Hentbol","Kadın Futbol"]', 1, 'spor'),
-- EDEBİYAT
('"Kürk Mantolu Madonna" romanının yazarı kimdir?', '["Sait Faik Abasıyanık","Sabahattin Ali","Orhan Kemal","Kemal Tahir"]', 1, 'edebiyat'),
('"İnce Memed" romanının yazarı kimdir?', '["Yaşar Kemal","Orhan Kemal","Fakir Baykurt","Kemal Tahir"]', 0, 'edebiyat'),
('"Tutunamayanlar" romanının yazarı kimdir?', '["Ahmet Hamdi Tanpınar","Yusuf Atılgan","Oğuz Atay","Bilge Karasu"]', 2, 'edebiyat'),
('"Saatleri Ayarlama Enstitüsü" romanının yazarı kimdir?', '["Ahmet Hamdi Tanpınar","Peyami Safa","Halid Ziya Uşaklıgil","Refik Halid Karay"]', 0, 'edebiyat'),
('"Çalıkuşu" romanının yazarı kimdir?', '["Halide Edib Adıvar","Reşat Nuri Güntekin","Yakup Kadri Karaosmanoğlu","Hüseyin Rahmi Gürpınar"]', 1, 'edebiyat'),
('"Romeo ve Juliet" adlı eserin yazarı kimdir?', '["Charles Dickens","William Shakespeare","Oscar Wilde","Christopher Marlowe"]', 1, 'edebiyat'),
('"Sefiller" romanının yazarı kimdir?', '["Emile Zola","Honore de Balzac","Victor Hugo","Gustave Flaubert"]', 2, 'edebiyat'),
('"Don Kişot" romanının yazarı kimdir?', '["Cervantes","Lope de Vega","Calderon","Garcia Marquez"]', 0, 'edebiyat'),
('"Küçük Prens" kitabının yazarı kimdir?', '["Jules Verne","Antoine de Saint-Exupery","Albert Camus","Victor Hugo"]', 1, 'edebiyat'),
('"Simyacı" romanının yazarı kimdir?', '["Gabriel Garcia Marquez","Paulo Coelho","Jorge Luis Borges","Isabel Allende"]', 1, 'edebiyat'),
('"Nutuk" kimin eseridir?', '["İsmet İnönü","Mustafa Kemal Atatürk","Ziya Gökalp","Halide Edib Adıvar"]', 1, 'edebiyat'),
('"Beyaz Diş" ve "Vahşetin Çağrısı" romanlarının yazarı kimdir?', '["Mark Twain","Ernest Hemingway","Jack London","John Steinbeck"]', 2, 'edebiyat'),
('Kahramanı bir sabah böceğe dönüşen "Dönüşüm" adlı eserin yazarı kimdir?', '["Albert Camus","Franz Kafka","Hermann Hesse","Thomas Mann"]', 1, 'edebiyat'),
('Divan edebiyatında şairlerin şiirlerini topladıkları kitaba ne ad verilir?', '["Tezkire","Divan","Mesnevi","Münşeat"]', 1, 'edebiyat'),
('"Memleketimden İnsan Manzaraları" kimin eseridir?', '["Orhan Veli Kanık","Nazım Hikmet","Attila İlhan","Cemal Süreya"]', 1, 'edebiyat'),
('"Harry Potter" serisinin yazarı kimdir?', '["J.R.R. Tolkien","J.K. Rowling","C.S. Lewis","Roald Dahl"]', 1, 'edebiyat'),
('İlyada ve Odysseia destanlarının ozanı kimdir?', '["Sophokles","Homeros","Euripides","Hesiodos"]', 1, 'edebiyat'),
('"Savaş ve Barış" romanının yazarı kimdir?', '["Dostoyevski","Tolstoy","Turgenyev","Puşkin"]', 1, 'edebiyat'),
('Dede Korkut Hikayeleri hangi Türk boyunun yaşamını anlatır?', '["Kıpçaklar","Karluklar","Oğuzlar","Uygurlar"]', 2, 'edebiyat'),
('"Şeker Portakalı" romanının yazarı kimdir?', '["Paulo Coelho","Jose Mauro de Vasconcelos","Jorge Amado","Mario Vargas Llosa"]', 1, 'edebiyat'),
('Sait Faik Abasıyanık Türk edebiyatında hangi türün ustası olarak bilinir?', '["Roman","Şiir","Öykü","Deneme"]', 2, 'edebiyat'),
('"Fareler ve İnsanlar" romanının yazarı kimdir?', '["Ernest Hemingway","John Steinbeck","William Faulkner","F. Scott Fitzgerald"]', 1, 'edebiyat'),
-- GENEL
('Bir düzine kaç adettir?', '["6","10","12","24"]', 2, 'genel'),
('Artık yıl kaç günden oluşur?', '["364","365","366","367"]', 2, 'genel'),
('Birleşmiş Milletler''in genel merkezi hangi şehirdedir?', '["Cenevre","New York","Paris","Viyana"]', 1, 'genel'),
('NATO''nun genel merkezi hangi şehirdedir?', '["Cenevre","Paris","Brüksel","Londra"]', 2, 'genel'),
('Japonya''nın para birimi nedir?', '["Yuan","Won","Yen","Ringgit"]', 2, 'genel'),
('İngiltere''nin para birimi nedir?', '["Euro","Dolar","Sterlin","Frank"]', 2, 'genel'),
('Kızılay''ın uluslararası karşılığı olan kuruluş hangisidir?', '["UNICEF","Kızılhaç","UNESCO","WHO"]', 1, 'genel'),
('"QWERTY" adı nereden gelmektedir?', '["Mucidinin adından","Klavyenin ilk altı harfinden","Bir kısaltmadan","Üretici firmadan"]', 1, 'genel'),
('Bir saat kaç saniyedir?', '["600","1800","3600","6000"]', 2, 'genel'),
('Dünya Kadınlar Günü hangi tarihte kutlanır?', '["8 Mart","8 Mayıs","25 Kasım","5 Aralık"]', 0, 'genel'),
('Türkiye''de Öğretmenler Günü hangi tarihte kutlanır?', '["10 Kasım","24 Kasım","23 Nisan","5 Ekim"]', 1, 'genel'),
('Roma rakamlarında "L" hangi sayıyı gösterir?', '["5","50","100","500"]', 1, 'genel'),
('Roma rakamlarında "C" hangi sayıyı gösterir?', '["50","100","500","1000"]', 1, 'genel'),
('Satranç tahtasında toplam kaç kare vardır?', '["36","49","64","81"]', 2, 'genel'),
('Gökkuşağında geleneksel olarak kaç renk sayılır?', '["5","6","7","8"]', 2, 'genel'),
('Pi sayısının yaklaşık değeri nedir?', '["2,71","3,14","3,41","4,13"]', 1, 'genel'),
('Türkiye''de tüm acil çağrılar için kullanılan numara hangisidir?', '["110","112","155","156"]', 1, 'genel'),
('Türk Lirası''nın ₺ simgesi hangi yıl kullanılmaya başlanmıştır?', '["2005","2009","2012","2015"]', 2, 'genel')
on conflict (soru) do nothing;
