-- ============================================================
-- Soru Partisi 12 — 500 soru, 9 kategoriye yaklaşık eşit dağıtılmış
-- (tarih, bilim, cografya, edebiyat, spor, sanat, sinema, muzik, teknoloji)
-- Zorluk: %40 kolay / %40 orta / %20 zor
--
-- Kalite: tek ve tartışmasız doğru cevap; zamanla değişen bilgi yok;
-- yoruma açık ifade yok; mevcut havuza (parti 10 ve 11 dahil) karşı tekrar
-- taraması yapıldı. Migration sonunda YALNIZ bu partinin şıkları karıştırılır.
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- ===================== TARİH =====================
('Mezopotamya hangi iki nehir arasındadır?', '["Fırat ve Dicle","Nil ve Kızıldeniz","Tuna ve Ren","İndus ve Ganj"]'::jsonb, 0, 'tarih'),
('Tarih öncesi dönemlerin sonu neyle başlar?', '["Ateşin bulunması","Yazının bulunması","Tekerleğin bulunması","Tarımın başlaması"]'::jsonb, 1, 'tarih'),
('Neolitik dönemin en önemli gelişmesi nedir?', '["Matbaa","Uzay yolculuğu","Yerleşik hayata geçiş","Buhar makinesi"]'::jsonb, 2, 'tarih'),
('Tarihte ilk kez tekerleği kullanan uygarlık hangisidir?', '["Persler","Romalılar","Yunanlar","Sümerler"]'::jsonb, 3, 'tarih'),
('Antik Mısır''da ölülerin korunma yöntemine ne denir?', '["Mumyalama","Yakma","Gömme törenleri yok","Denize bırakma"]'::jsonb, 0, 'tarih'),
('Antik Yunan''da halk meclisinin toplandığı alana ne denirdi?', '["Forum","Agora","Colosseum","Akropol tapınağı"]'::jsonb, 1, 'tarih'),
('Roma''da halkın toplandığı meydana ne denirdi?', '["Stadyum","Agora","Forum","Hipodrom"]'::jsonb, 2, 'tarih'),
('Gladyatör dövüşleri hangi yapıda yapılırdı?', '["Parthenon","Panteon","Akropol","Kolezyum"]'::jsonb, 3, 'tarih'),
('Roma İmparatorluğu''nun Batı kısmı hangi yıl yıkılmıştır?', '["476","1453","395","1204"]'::jsonb, 0, 'tarih'),
('Bizans hangi imparatorluğun devamıdır?', '["Pers","Doğu Roma","Makedonya","Mısır"]'::jsonb, 1, 'tarih'),
('Ayasofya hangi imparatorluk döneminde yapılmıştır?', '["Selçuklu","Osmanlı","Doğu Roma","Roma Cumhuriyeti"]'::jsonb, 2, 'tarih'),
('Türklerin Anadolu''ya yerleşmesini hızlandıran zafer hangisidir?', '["Varna","Ankara","Niğbolu","Malazgirt"]'::jsonb, 3, 'tarih'),
('Miryokefalon Savaşı hangi devletler arasındadır?', '["Anadolu Selçuklu ve Bizans","Osmanlı ve Memlük","Osmanlı ve Safevi","Selçuklu ve Moğol"]'::jsonb, 0, 'tarih'),
('Anadolu Selçuklu Devleti''ni sarsan Kösedağ Savaşı kime karşıdır?', '["Bizans","Moğollar","Memlükler","Haçlılar"]'::jsonb, 1, 'tarih'),
('Ankara Savaşı hangi iki hükümdar arasında olmuştur?', '["Yavuz ve Şah İsmail","Fatih ve Uzun Hasan","Yıldırım Bayezid ve Timur","Kanuni ve Şarlken"]'::jsonb, 2, 'tarih'),
('Osmanlı''da Fetret Devri neyin ardından yaşanmıştır?', '["Preveze","İstanbul''un fethi","Mohaç","Ankara Savaşı"]'::jsonb, 3, 'tarih'),
('Çaldıran Savaşı hangi padişah döneminde olmuştur?', '["Yavuz Sultan Selim","Fatih","Kanuni","II. Bayezid"]'::jsonb, 0, 'tarih'),
('Mohaç Meydan Muharebesi hangi padişah döneminde kazanılmıştır?', '["Fatih","Kanuni Sultan Süleyman","Yavuz","II. Selim"]'::jsonb, 1, 'tarih'),
('Preveze Deniz Zaferi''nin komutanı kimdir?', '["Piri Reis","Turgut Reis","Barbaros Hayreddin Paşa","Kılıç Ali Paşa"]'::jsonb, 2, 'tarih'),
('İstanbul''un fethinde kullanılan büyük topu döken usta kimdir?', '["Ali Kuşçu","Sinan","Hasan","Urban"]'::jsonb, 3, 'tarih'),
('Osmanlı''da lale yetiştiriciliğinin öne çıktığı döneme ne denir?', '["Lale Devri","Tanzimat","Meşrutiyet","Fetret"]'::jsonb, 0, 'tarih'),
('II. Meşrutiyet hangi yıl ilan edilmiştir?', '["1876","1908","1839","1856"]'::jsonb, 1, 'tarih'),
('Trablusgarp Savaşı hangi ülkeyle yapılmıştır?', '["Rusya","Yunanistan","İtalya","Fransa"]'::jsonb, 2, 'tarih'),
('Balkan Savaşları hangi yıllarda olmuştur?', '["1897","1914-1918","1919-1922","1912-1913"]'::jsonb, 3, 'tarih'),
('İnönü Savaşları hangi cephede yaşanmıştır?', '["Batı","Doğu","Güney","Kafkas"]'::jsonb, 0, 'tarih'),
('Kütahya-Eskişehir Muharebeleri sonrası ordu nereye çekilmiştir?', '["Ege kıyıları","Sakarya Nehri doğusu","Toroslar","Trakya"]'::jsonb, 1, 'tarih'),
('Mudanya Ateşkes Antlaşması hangi yıl imzalanmıştır?', '["1923","1920","1922","1921"]'::jsonb, 2, 'tarih'),
('Cumhuriyetin ilanıyla hangi yönetim biçimine geçilmiştir?', '["Teokrasi","Monarşi","Oligarşi","Cumhuriyet"]'::jsonb, 3, 'tarih'),
('Türk Medeni Kanunu hangi ülkeden uyarlanmıştır?', '["İsviçre","Fransa","Almanya","İtalya"]'::jsonb, 0, 'tarih'),
('Ölçü ve tartı birimlerinde değişiklik hangi amaçla yapılmıştır?', '["Vergi artışı","Uluslararası uyum","Tarım desteği","Askeri düzen"]'::jsonb, 1, 'tarih'),
('Türk Tarih Kurumu hangi amaçla kurulmuştur?', '["Sağlık hizmeti","Dil çalışmaları","Tarih araştırmaları","Ulaşım planı"]'::jsonb, 2, 'tarih'),
('Montrö Boğazlar Sözleşmesi neyle ilgilidir?', '["Sanayi planı","Tarım destekleri","Eğitim reformu","Boğazların yönetimi"]'::jsonb, 3, 'tarih'),
('Hatay''ın Türkiye''ye katılımı hangi yıldadır?', '["1939","1923","1945","1930"]'::jsonb, 0, 'tarih'),
('Türkiye NATO''ya hangi yıl katılmıştır?', '["1945","1952","1963","1974"]'::jsonb, 1, 'tarih'),
('Milletler Cemiyeti hangi savaştan sonra kurulmuştur?', '["Kore Savaşı","İkinci Dünya Savaşı","Birinci Dünya Savaşı","Balkan Savaşları"]'::jsonb, 2, 'tarih'),
('Rönesans''ın yayılmasında hangi buluş etkili olmuştur?', '["Teleskop","Pusula","Barut","Matbaa"]'::jsonb, 3, 'tarih'),
('Coğrafi Keşifler''i kolaylaştıran alet hangisidir?', '["Pusula","Mikroskop","Termometre","Barometre"]'::jsonb, 0, 'tarih'),
('Reform hareketi hangi alanda başlamıştır?', '["Bilim","Din","Sanat","Ticaret"]'::jsonb, 1, 'tarih'),
('Aydınlanma Çağı''nın temel vurgusu nedir?', '["Mit","Gelenek","Akıl","Rastlantı"]'::jsonb, 2, 'tarih'),
('Sanayi Devrimi''nde üretimin merkezi neresi olmuştur?', '["Manastır","Tarla","Ev","Fabrika"]'::jsonb, 3, 'tarih'),
('Amerikan İç Savaşı''nın temel konularından biri neydi?', '["Kölelik","Uzay yarışı","Petrol","Deniz ticareti"]'::jsonb, 0, 'tarih'),
('Rus Devrimi hangi yıl gerçekleşmiştir?', '["1905","1917","1921","1930"]'::jsonb, 1, 'tarih'),
('Kore Savaşı hangi yıllarda olmuştur?', '["1914-1918","1939-1945","1950-1953","1960-1965"]'::jsonb, 2, 'tarih'),
('Avrupa Birliği''nin temeli hangi toplulukla atılmıştır?', '["OPEC","NATO","BM","Kömür ve Çelik Topluluğu"]'::jsonb, 3, 'tarih'),
('İlk uzay yarışının tarafları kimlerdi?', '["ABD ve SSCB","İngiltere ve Fransa","Çin ve Japonya","Almanya ve İtalya"]'::jsonb, 0, 'tarih'),
('Tarihte "Bereketli Hilal" hangi bölgeyi tanımlar?', '["Kuzey Avrupa","Ortadoğu","Sibirya","Amazon"]'::jsonb, 1, 'tarih'),
('Anadolu''da Selçuklu mimarisinin tipik yapılarından biri hangisidir?', '["Ziggurat","Piramit","Kervansaray","Akropol"]'::jsonb, 2, 'tarih'),
('Ziggurat hangi uygarlığa aittir?', '["Persler","Mısırlılar","Yunanlar","Sümerler"]'::jsonb, 3, 'tarih'),
('Truva kazılarını yapan ünlü kişi kimdir?', '["Schliemann","Champollion","Carter","Layard"]'::jsonb, 0, 'tarih'),
('Osmanlı''da ilk deniz üssü nerede kurulmuştur?', '["Sinop","Gelibolu","İzmir","Trabzon"]'::jsonb, 1, 'tarih'),
('Kanuni döneminde hazırlanan kanunlara ne denir?', '["Berat","Ferman","Kanunname","Buyruldu"]'::jsonb, 2, 'tarih'),

-- ===================== BİLİM =====================
('Hücreyi ilk gözlemleyen bilim insanı kimdir?', '["Gregor Mendel","Louis Pasteur","Charles Darwin","Robert Hooke"]'::jsonb, 3, 'bilim'),
('Mikroorganizmaların hastalık yaptığını gösteren bilim insanı kimdir?', '["Pasteur","Newton","Kepler","Faraday"]'::jsonb, 0, 'bilim'),
('Gezegen hareketleri yasalarını bulan bilim insanı kimdir?', '["Kopernik","Kepler","Galileo","Brahe"]'::jsonb, 1, 'bilim'),
('Güneş merkezli evren modelini öne süren bilim insanı kimdir?', '["Aristo","Batlamyus","Kopernik","Kepler"]'::jsonb, 2, 'bilim'),
('Teleskopu gökyüzü gözlemine ilk yönelten bilim insanı kimdir?', '["Halley","Newton","Kepler","Galileo"]'::jsonb, 3, 'bilim'),
('Bir cismin hareket halinde kalma eğilimine ne denir?', '["Eylemsizlik","Sürtünme","Basınç","Tork"]'::jsonb, 0, 'bilim'),
('Etki-tepki ilkesi hangi bilim insanına aittir?', '["Einstein","Newton","Bohr","Planck"]'::jsonb, 1, 'bilim'),
('İş yapabilme yeteneğine ne denir?', '["Basınç","Kuvvet","Enerji","Hız"]'::jsonb, 2, 'bilim'),
('Yüksekteki bir cismin sahip olduğu enerji türü hangisidir?', '["Işık","Kinetik","Isı","Potansiyel"]'::jsonb, 3, 'bilim'),
('Hareket halindeki cismin enerjisine ne denir?', '["Kinetik","Potansiyel","Kimyasal","Nükleer"]'::jsonb, 0, 'bilim'),
('Enerjinin korunumu ilkesi neyi söyler?', '["Enerji yok olur","Enerji yoktan var edilemez","Enerji artar","Enerji sabit değildir"]'::jsonb, 1, 'bilim'),
('Bir devrede gerilim neyle ölçülür?', '["Ohmmetre","Ampermetre","Voltmetre","Termometre"]'::jsonb, 2, 'bilim'),
('Bir devrede akım neyle ölçülür?', '["Higrometre","Voltmetre","Barometre","Ampermetre"]'::jsonb, 3, 'bilim'),
('Seri bağlı devrede ampullerden biri sönerse ne olur?', '["Diğerleri de söner","Hiçbiri sönmez","Işık artar","Devre hızlanır"]'::jsonb, 0, 'bilim'),
('Manyetik alanı en güçlü olan bölge hangisidir?', '["Orta","Kutuplar","Yüzey","Dış çevre"]'::jsonb, 1, 'bilim'),
('Aynı kutuplar birbirini ne yapar?', '["Etkilemez","Çeker","İter","Isıtır"]'::jsonb, 2, 'bilim'),
('Bir maddenin ısıyı iletme özelliğine ne denir?', '["Sertlik","Yoğunluk","Esneklik","Isı iletkenliği"]'::jsonb, 3, 'bilim'),
('Sıvıların ısınmasında ısı hangi yolla yayılır?', '["Konveksiyon","İletim","Işıma","Yansıma"]'::jsonb, 0, 'bilim'),
('Güneşten Dünya''ya ısı hangi yolla gelir?', '["İletim","Işıma","Konveksiyon","Titreşim"]'::jsonb, 1, 'bilim'),
('Bir maddenin erime ve donma sıcaklığı nasıldır?', '["Sıfırdır","Farklıdır","Aynıdır","Değişkendir"]'::jsonb, 2, 'bilim'),
('Saf maddelerin kaynama sıcaklığı nasıldır?', '["Rastgeledir","Sürekli artar","Sürekli azalır","Sabittir"]'::jsonb, 3, 'bilim'),
('Buzun suda yüzmesinin sebebi nedir?', '["Yoğunluğunun daha az olması","Soğuk olması","Beyaz olması","Sert olması"]'::jsonb, 0, 'bilim'),
('Deniz suyunun donma sıcaklığı saf suya göre nasıldır?', '["Daha yüksektir","Daha düşüktür","Aynıdır","Sıfırdır"]'::jsonb, 1, 'bilim'),
('Karışımlara örnek hangisidir?', '["Oksijen gazı","Saf su","Tuzlu su","Demir"]'::jsonb, 2, 'bilim'),
('Bileşiklere örnek hangisidir?', '["Bakır","Hava","Demir","Su"]'::jsonb, 3, 'bilim'),
('Elementlere örnek hangisidir?', '["Altın","Su","Hava","Tuzlu su"]'::jsonb, 0, 'bilim'),
('Aynı elementin farklı nötron sayılı atomlarına ne denir?', '["İyon","İzotop","Molekül","Bileşik"]'::jsonb, 1, 'bilim'),
('Yük kazanmış atoma ne denir?', '["Molekül","İzotop","İyon","Element"]'::jsonb, 2, 'bilim'),
('Asitlerin ortak özelliği nedir?', '["Renksizlik","Kaygan his","Tatlı tat","Ekşi tat"]'::jsonb, 3, 'bilim'),
('Bazların ortak özelliği nedir?', '["Kaygan his","Ekşi tat","Yanıcılık","Manyetiklik"]'::jsonb, 0, 'bilim'),
('Turnusol kâğıdı ne belirler?', '["Sıcaklığı","Asit-baz özelliğini","Ağırlığı","Rengi"]'::jsonb, 1, 'bilim'),
('Paslanma hangi olayla gerçekleşir?', '["Donma","Erime","Oksijenle tepkime","Buharlaşma"]'::jsonb, 2, 'bilim'),
('Fotosentezde hangi gaz açığa çıkar?', '["Metan","Karbondioksit","Azot","Oksijen"]'::jsonb, 3, 'bilim'),
('Solunumda hangi gaz açığa çıkar?', '["Karbondioksit","Oksijen","Helyum","Argon"]'::jsonb, 0, 'bilim'),
('Bitkilerde su ve mineralleri taşıyan boru sistemine ne denir?', '["Soymuk boruları","Odun boruları","Kök tüyleri","Stoma"]'::jsonb, 1, 'bilim'),
('Yapraklardaki gaz alışverişini sağlayan yapı hangisidir?', '["Kök","Klorofil","Stoma","Gövde"]'::jsonb, 2, 'bilim'),
('Canlıların ortak özelliklerinden biri hangisidir?', '["Konuşma","Uçma","Yüzme","Beslenme"]'::jsonb, 3, 'bilim'),
('Tek hücreli canlılara örnek hangisidir?', '["Amip","İnsan","Kedi","Meşe"]'::jsonb, 0, 'bilim'),
('Bakteriler hangi tür canlılardır?', '["Çok hücreli","Tek hücreli","Bitki","Mantar"]'::jsonb, 1, 'bilim'),
('Virüsler hangi ortamda çoğalabilir?', '["Havada tek başına","Toprakta","Canlı hücre içinde","Suda tek başına"]'::jsonb, 2, 'bilim'),
('Antibiyotiklerin bilinçsiz kullanımı neye yol açar?', '["Kilo kaybına","Bağışıklık artışına","Vitamin eksikliğine","Direnç gelişimine"]'::jsonb, 3, 'bilim'),
('İnsanda kalıtsal bilgiyi taşıyan molekül hangisidir?', '["DNA","ATP","Glikoz","Kolesterol"]'::jsonb, 0, 'bilim'),
('Genler nerede bulunur?', '["Hücre zarında","Kromozomlarda","Kofulda","Ribozomda"]'::jsonb, 1, 'bilim'),
('Bir canlının dış görünüşüne ne denir?', '["Kromozom","Genotip","Fenotip","Alel"]'::jsonb, 2, 'bilim'),
('Aynı türden canlıların oluşturduğu topluluğa ne denir?', '["Biyom","Komünite","Ekosistem","Popülasyon"]'::jsonb, 3, 'bilim'),
('Bir ekosistemde enerji akışı hangi yönde ilerler?', '["Üreticiden tüketiciye","Tüketiciden üreticiye","Daireseldir","Yoktur"]'::jsonb, 0, 'bilim'),
('Doğada azot döngüsünde etkili canlılar hangileridir?', '["Balıklar","Bakteriler","Kuşlar","Mantarlar yalnızca"]'::jsonb, 1, 'bilim'),
('Bir maddenin çözünürlüğü genellikle sıcaklıkla nasıl değişir?', '["Değişmez","Her zaman azalır","Katılarda artar","Sıfırlanır"]'::jsonb, 2, 'bilim'),
('Homojen karışımlara ne denir?', '["Bileşik","Süspansiyon","Emülsiyon","Çözelti"]'::jsonb, 3, 'bilim'),
('Kum ve suyu ayırmak için hangi yöntem uygundur?', '["Süzme","Damıtma","Mıknatısla ayırma","Yoğunlaştırma"]'::jsonb, 0, 'bilim'),
('Tuzlu sudan saf su elde etmek için hangi yöntem kullanılır?', '["Süzme","Damıtma","Eleme","Mıknatıs"]'::jsonb, 1, 'bilim'),
('Demir tozu ile kükürdü ayırmak için ne kullanılır?', '["Elek","Süzgeç","Mıknatıs","Damıtma"]'::jsonb, 2, 'bilim'),

-- ===================== COĞRAFYA =====================
('Türkiye''nin matematik konumu neye göre belirlenir?', '["İklim","Komşuları","Yükseklik","Enlem ve boylam"]'::jsonb, 3, 'cografya'),
('Türkiye hangi yarım kürelerdedir?', '["Kuzey ve doğu","Güney ve batı","Kuzey ve batı","Güney ve doğu"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en alçak yeri hangi kıyıdadır?', '["Dağ zirveleri","Deniz kıyıları","Platolar","Yaylalar"]'::jsonb, 1, 'cografya'),
('Ege Bölgesi''nde denize dik uzanan dağların oluşturduğu ova türü hangisidir?', '["Yayla ovaları","Delta ovaları","Çöküntü ovaları","Buzul ovaları"]'::jsonb, 2, 'cografya'),
('Türkiye''de en fazla orman hangi bölgededir?', '["Doğu Anadolu","Güneydoğu Anadolu","İç Anadolu","Karadeniz"]'::jsonb, 3, 'cografya'),
('Türkiye''de tahıl üretiminin en yoğun olduğu bölge hangisidir?', '["İç Anadolu","Karadeniz","Marmara","Ege"]'::jsonb, 0, 'cografya'),
('Türkiye''de zeytin üretimi en çok hangi bölgededir?', '["Doğu Anadolu","Ege","Karadeniz","İç Anadolu"]'::jsonb, 1, 'cografya'),
('Türkiye''de en fazla sanayi tesisi hangi bölgededir?', '["Güneydoğu Anadolu","Doğu Anadolu","Marmara","Karadeniz"]'::jsonb, 2, 'cografya'),
('Türkiye''nin en yoğun nüfuslu bölgesi hangisidir?', '["Karadeniz","Doğu Anadolu","İç Anadolu","Marmara"]'::jsonb, 3, 'cografya'),
('Türkiye''de nüfusun en seyrek olduğu bölge hangisidir?', '["Doğu Anadolu","Marmara","Ege","Akdeniz"]'::jsonb, 0, 'cografya'),
('Türkiye''de kış turizmi hangi bölgede öne çıkar?', '["Güneydoğu Anadolu","Doğu Anadolu","Ege","Akdeniz"]'::jsonb, 1, 'cografya'),
('Türkiye''de deniz turizmi en çok hangi kıyılarda gelişmiştir?', '["Marmara","Karadeniz","Ege ve Akdeniz","Hepsi eşit"]'::jsonb, 2, 'cografya'),
('Bir bölgenin bitki örtüsünü belirleyen en önemli etken nedir?', '["Ulaşım","Nüfus","Sanayi","İklim"]'::jsonb, 3, 'cografya'),
('Akdeniz ikliminin doğal bitki örtüsü nedir?', '["Maki","Bozkır","Tundra","Tayga"]'::jsonb, 0, 'cografya'),
('Karasal iklimin doğal bitki örtüsü nedir?', '["Maki","Bozkır","Orman","Savan"]'::jsonb, 1, 'cografya'),
('Kuzey ormanlarına verilen ad nedir?', '["Bozkır","Maki","Tayga","Savan"]'::jsonb, 2, 'cografya'),
('Afrika''da geniş otlaklara ne denir?', '["Maki","Tayga","Tundra","Savan"]'::jsonb, 3, 'cografya'),
('Dünyanın en sıcak bölgeleri hangi kuşaktadır?', '["Ekvatoral kuşak","Kutup kuşağı","Ilıman kuşak","Soğuk kuşak"]'::jsonb, 0, 'cografya'),
('Bir yerin iklimini etkileyen faktörlerden biri nedir?', '["Nüfus sayısı","Denize uzaklık","Dil","Din"]'::jsonb, 1, 'cografya'),
('Dağların denize bakan yamaçları neden daha çok yağış alır?', '["Rüzgâr yoktur","Sıcak olur","Nemli hava yükselir","Toprak farklıdır"]'::jsonb, 2, 'cografya'),
('Akarsuların denize ulaştığı yere ne denir?', '["Menderes","Kaynak","Havza","Ağız"]'::jsonb, 3, 'cografya'),
('Akarsuyun kıvrımlar yaparak akmasına ne denir?', '["Menderes","Delta","Şelale","Boğaz"]'::jsonb, 0, 'cografya'),
('Yer altı sularının yüzeye çıktığı yere ne denir?', '["Delta","Kaynak","Kumul","Falez"]'::jsonb, 1, 'cografya'),
('Deniz kıyısındaki dik yamaçlara ne denir?', '["Lagün","Kumul","Falez","Delta"]'::jsonb, 2, 'cografya'),
('Kıyıda kum setiyle denizden ayrılan göle ne denir?', '["Set gölü yok","Krater gölü","Buzul gölü","Lagün"]'::jsonb, 3, 'cografya'),
('Volkan ağzında oluşan göle ne denir?', '["Krater gölü","Lagün","Buzul gölü","Baraj gölü"]'::jsonb, 0, 'cografya'),
('İnsan eliyle oluşturulan göllere ne denir?', '["Krater gölü","Baraj gölü","Lagün","Buzul gölü"]'::jsonb, 1, 'cografya'),
('Yer altında kalker erimesiyle oluşan boşluklara ne denir?', '["Kumul","Delta","Mağara","Moren"]'::jsonb, 2, 'cografya'),
('Mağaralarda tavandan sarkan oluşumlara ne denir?', '["Traverten","Dikit","Sütun","Sarkıt"]'::jsonb, 3, 'cografya'),
('Mağara tabanından yükselen oluşumlara ne denir?', '["Dikit","Sarkıt","Kumul","Moren"]'::jsonb, 0, 'cografya'),
('Yeryüzünün en büyük kara parçalarına ne denir?', '["Ada","Kıta","Yarımada","Kıstak"]'::jsonb, 1, 'cografya'),
('Levha hareketleri neye yol açar?', '["Nüfus artışı","Yağış artışı","Deprem ve volkanizma","İklim sabitliği"]'::jsonb, 2, 'cografya'),
('Dünyanın iç yapısında en dışta bulunan katman hangisidir?', '["Astenosfer","Manto","Çekirdek","Yer kabuğu"]'::jsonb, 3, 'cografya'),
('Yer kabuğunun altındaki akışkan katmana ne denir?', '["Manto","Çekirdek","Litosfer","Atmosfer"]'::jsonb, 0, 'cografya'),
('Atmosferin en alt katmanı hangisidir?', '["Stratosfer","Troposfer","Mezosfer","İyonosfer"]'::jsonb, 1, 'cografya'),
('Ozon tabakası hangi katmandadır?', '["Mezosfer","Troposfer","Stratosfer","Ekzosfer"]'::jsonb, 2, 'cografya'),
('Hava olayları hangi katmanda gerçekleşir?', '["İyonosfer","Stratosfer","Mezosfer","Troposfer"]'::jsonb, 3, 'cografya'),
('Rüzgârın yönünü belirleyen temel etken nedir?', '["Basınç farkı","Nem","Sıcaklık eşitliği","Yükseklik yok"]'::jsonb, 0, 'cografya'),
('Alçak basınç merkezinde hava nasıl hareket eder?', '["Alçalır","Yükselir","Durur","Yatay kalır"]'::jsonb, 1, 'cografya'),
('Yüksek basınç genellikle nasıl hava getirir?', '["Karlı hava","Yağmurlu hava","Açık hava","Fırtına"]'::jsonb, 2, 'cografya'),
('Muson rüzgârları hangi mevsimde yağış getirir?', '["İlkbahar","Kış","Sonbahar","Yaz"]'::jsonb, 3, 'cografya'),
('Türkiye''de yaz aylarında kuzeyden esen serin rüzgâra ne denir?', '["Meltem","Poyraz gibi kışlık","Lodos","Samyeli"]'::jsonb, 0, 'cografya'),
('Karadan denize doğru esen rüzgâra ne denir?', '["Deniz meltemi","Kara meltemi","Muson","Alize"]'::jsonb, 1, 'cografya'),
('Ekvator çevresinde esen sürekli rüzgârlara ne denir?', '["Meltemler","Musonlar","Alizeler","Föhn"]'::jsonb, 2, 'cografya'),
('Dünyanın şekli nedir?', '["Koni","Tam küre","Silindir","Geoid"]'::jsonb, 3, 'cografya'),
('Dünyanın kendi ekseni etrafındaki dönüşü kaç saat sürer?', '["24","12","365","30"]'::jsonb, 0, 'cografya'),
('Mevsimlerin oluşmasının temel sebebi nedir?', '["Dünyanın büyüklüğü","Eksen eğikliği","Ay","Bulutlar"]'::jsonb, 1, 'cografya'),
('Ekvatorun uzunluğu yaklaşık kaç kilometredir?', '["100.000","10.000","40.000","4.000"]'::jsonb, 2, 'cografya'),
('Başlangıç meridyeni kaç derecedir?', '["45","90","180","0"]'::jsonb, 3, 'cografya'),
('Enlem dereceleri en fazla kaç olabilir?', '["90","180","360","45"]'::jsonb, 0, 'cografya'),
('Boylam dereceleri en fazla kaç olabilir?', '["90","180","360","270"]'::jsonb, 1, 'cografya'),
('İki meridyen arasındaki zaman farkı kaç dakikadır?', '["15","1","4","60"]'::jsonb, 2, 'cografya'),
('Şehirleşmenin en önemli sonuçlarından biri nedir?', '["Orman artışı","Nüfus azalması","Tarım artışı","Kırdan kente göç"]'::jsonb, 3, 'cografya'),
('Bir ülkede doğum oranının ölüm oranından fazla olması neye yol açar?', '["Nüfus artışına","Nüfus azalışına","Göçe","Kuraklığa"]'::jsonb, 0, 'cografya'),

-- ===================== EDEBİYAT =====================
('Şiirde dizelerin sonundaki ses benzerliğine ne denir?', '["Redif dışı yok","Kafiye","Ölçü","Nazım"]'::jsonb, 1, 'edebiyat'),
('Şiirde dize sonlarında tekrar eden aynı görevdeki eklere ne denir?', '["Ölçü","Kafiye","Redif","Durak"]'::jsonb, 2, 'edebiyat'),
('Hece ölçüsünde dizeler neye göre sayılır?', '["Ses tonuna","Harf sayısına","Kelime sayısına","Hece sayısına"]'::jsonb, 3, 'edebiyat'),
('Divan şiirinde kullanılan ölçü hangisidir?', '["Aruz","Hece","Serbest","Karışık"]'::jsonb, 0, 'edebiyat'),
('Serbest ölçüde ne aranmaz?', '["Anlam","Belirli hece sayısı","Duygu","İmge"]'::jsonb, 1, 'edebiyat'),
('Bir olayın kişi, yer ve zamanla anlatıldığı türe ne denir?', '["Makale","Deneme","Hikâye","Fıkra"]'::jsonb, 2, 'edebiyat'),
('Yazarın bir konudaki düşüncelerini serbestçe anlattığı türe ne denir?', '["Masal","Roman","Destan","Deneme"]'::jsonb, 3, 'edebiyat'),
('Bilimsel bir konuyu kanıtlarla anlatan yazı türü hangisidir?', '["Makale","Masal","Fıkra","Şiir"]'::jsonb, 0, 'edebiyat'),
('Gazetelerde güncel konuların kısaca ele alındığı türe ne denir?', '["Roman","Fıkra","Destan","Ağıt"]'::jsonb, 1, 'edebiyat'),
('Bir kişinin hayatını başkasının anlattığı türe ne denir?', '["Günlük","Otobiyografi","Biyografi","Anı"]'::jsonb, 2, 'edebiyat'),
('Yazarın günü gününe tuttuğu yazılara ne denir?', '["Eleştiri","Makale","Deneme","Günlük"]'::jsonb, 3, 'edebiyat'),
('Uzak yerlerin anlatıldığı yazı türü hangisidir?', '["Gezi yazısı","Fıkra","Makale","Eleştiri"]'::jsonb, 0, 'edebiyat'),
('Bir eserin değerlendirildiği yazı türü hangisidir?', '["Günlük","Eleştiri","Masal","Destan"]'::jsonb, 1, 'edebiyat'),
('Ölen kişinin ardından yakılan halk şiirine ne denir?', '["Semai","Koşma","Ağıt","Destan"]'::jsonb, 2, 'edebiyat'),
('Halk edebiyatında yiğitlik konulu şiirlere ne denir?', '["Ağıt","Güzelleme","Taşlama","Koçaklama"]'::jsonb, 3, 'edebiyat'),
('Halk edebiyatında doğa ve güzellik konulu şiirlere ne denir?', '["Güzelleme","Koçaklama","Taşlama","Ağıt"]'::jsonb, 0, 'edebiyat'),
('Eleştirel ve iğneleyici halk şiirine ne denir?', '["Güzelleme","Taşlama","Koçaklama","Ninni"]'::jsonb, 1, 'edebiyat'),
('Karşılıklı söyleşme biçimindeki halk şiirine ne denir?', '["Ninni","Ağıt","Atışma","Mani"]'::jsonb, 2, 'edebiyat'),
('Dört dizeden oluşan ve genelde 7''li heceyle yazılan halk şiiri hangisidir?', '["Kaside","Koşma","Gazel","Mani"]'::jsonb, 3, 'edebiyat'),
('Divan edebiyatında övgü şiirlerine ne denir?', '["Kaside","Gazel","Mesnevi","Rubai"]'::jsonb, 0, 'edebiyat'),
('Divan edebiyatında aşk konulu kısa şiirlere ne denir?', '["Kaside","Gazel","Mesnevi","Şarkı yalnızca"]'::jsonb, 1, 'edebiyat'),
('Divan edebiyatında uzun hikâye şiirlerine ne denir?', '["Rubai","Gazel","Mesnevi","Mani"]'::jsonb, 2, 'edebiyat'),
('Dört dizelik divan nazım biçimi hangisidir?', '["Mesnevi","Gazel","Kaside","Rubai"]'::jsonb, 3, 'edebiyat'),
('Tanzimat edebiyatının amaçlarından biri neydi?', '["Halkı eğitmek","Sadece sarayı övmek","Yabancı dil öğretmek","Ticaret yapmak"]'::jsonb, 0, 'edebiyat'),
('Şinasi hangi alanda öncülük yapmıştır?', '["Resim","Gazetecilik ve tiyatro","Heykel","Müzik"]'::jsonb, 1, 'edebiyat'),
('Namık Kemal hangi kavramlarla anılır?', '["Tarım","Ticaret ve kâr","Vatan ve hürriyet","Denizcilik"]'::jsonb, 2, 'edebiyat'),
('Ziya Paşa hangi dönemin şairidir?', '["Fecr-i Ati","Cumhuriyet","Divan öncesi","Tanzimat"]'::jsonb, 3, 'edebiyat'),
('Milli Edebiyat akımının dil anlayışı nasıldır?', '["Sade Türkçe","Ağır Osmanlıca","Yabancı dil","Karışık"]'::jsonb, 0, 'edebiyat'),
('Ömer Seyfettin hangi türde ünlüdür?', '["Roman","Hikâye","Destan","Opera"]'::jsonb, 1, 'edebiyat'),
('Ziya Gökalp hangi alanda etkili olmuştur?', '["Mimarlık","Denizcilik","Sosyoloji ve düşünce","Tıp"]'::jsonb, 2, 'edebiyat'),
('Mehmet Emin Yurdakul hangi konuları işlemiştir?', '["Denizcilik","Doğa bilimleri","Ticaret","Milli duygular"]'::jsonb, 3, 'edebiyat'),
('Ahmet Haşim hangi akımla anılır?', '["Sembolizm","Realizm","Natüralizm","Klasisizm"]'::jsonb, 0, 'edebiyat'),
('Yahya Kemal hangi konuda tanınır?', '["Roman","Şiir","Tiyatro","Deneme yalnızca"]'::jsonb, 1, 'edebiyat'),
('Necip Fazıl hangi türde de eser vermiştir?', '["Sadece deneme","Sadece roman","Tiyatro","Sadece anı"]'::jsonb, 2, 'edebiyat'),
('Peyami Safa''nın bilinen romanlarından biri hangisidir?', '["Çalıkuşu","İnce Memed","Yaban","Dokuzuncu Hariciye Koğuşu"]'::jsonb, 3, 'edebiyat'),
('Ahmet Hamdi Tanpınar''ın ünlü romanı hangisidir?', '["Huzur","Yaban","Sinekli Bakkal","Kuyucaklı Yusuf"]'::jsonb, 0, 'edebiyat'),
('Refik Halid Karay hangi türde ünlüdür?', '["Opera","Hikâye ve roman","Heykel","Bale"]'::jsonb, 1, 'edebiyat'),
('Orhan Kemal hangi konuları işlemiştir?', '["Uzay","Saray yaşamı","Emekçi hayatı","Sihir"]'::jsonb, 2, 'edebiyat'),
('Kemal Tahir hangi türde eser vermiştir?', '["Heykel","Opera","Bale","Roman"]'::jsonb, 3, 'edebiyat'),
('Aziz Nesin hangi türde tanınır?', '["Mizah","Destan","Ağıt","İlahi"]'::jsonb, 0, 'edebiyat'),
('Cevat Şakir Kabaağaçlı hangi takma adla bilinir?', '["Deli Ozan","Halikarnas Balıkçısı","Servet","Kul Ahmet"]'::jsonb, 1, 'edebiyat'),
('Bir romanda olayların geçtiği yer ve zamana ne denir?', '["Tema","Konu","Mekân ve zaman","Üslup"]'::jsonb, 2, 'edebiyat'),
('Bir eserde anlatılan temel düşünceye ne denir?', '["Kişi","Olay örgüsü","Mekân","Tema"]'::jsonb, 3, 'edebiyat'),
('Romanda olayların sıralanışına ne denir?', '["Olay örgüsü","Tema","Üslup","Bakış açısı"]'::jsonb, 0, 'edebiyat'),
('Anlatıcının olayları "ben" diliyle aktarmasına ne denir?', '["Üçüncü kişi","Birinci kişi anlatım","Gözlemci","İlahi bakış"]'::jsonb, 1, 'edebiyat'),
('Benzetme sanatına ne denir?', '["Kinaye","Tezat","Teşbih","Tevriye"]'::jsonb, 2, 'edebiyat'),
('Karşıt kavramların bir arada kullanılmasına ne denir?', '["Telmih","Teşbih","Mecaz","Tezat"]'::jsonb, 3, 'edebiyat'),
('İnsan dışı varlıklara insan özelliği verilmesine ne denir?', '["Kişileştirme","Abartma","Tezat","Kinaye"]'::jsonb, 0, 'edebiyat'),
('Bir olayı ya da kişiyi hatırlatmaya ne denir?', '["Teşbih","Telmih","Tezat","Cinas"]'::jsonb, 1, 'edebiyat'),
('Yazılışı aynı anlamı farklı sözcüklerle yapılan sanata ne denir?', '["Telmih","Tezat","Cinas","Teşbih"]'::jsonb, 2, 'edebiyat'),
('Abartma sanatına ne denir?', '["Cinas","Tezat","Telmih","Mübalağa"]'::jsonb, 3, 'edebiyat'),
('Bir sözü söylemeden ima etmeye ne denir?', '["Kinaye","Teşbih","Tekrir","Mübalağa"]'::jsonb, 0, 'edebiyat'),
('Aynı sesin şiirde tekrarına ne denir?', '["Kafiye","Aliterasyon","Redif","Ölçü"]'::jsonb, 1, 'edebiyat'),
('Bir metnin duygusal etkisini artıran anlatım özelliğine ne denir?', '["Başlık","Konu","Üslup","Sayfa"]'::jsonb, 2, 'edebiyat'),
('Masalların başında söylenen kalıp sözlere ne denir?', '["Ağıt","Nakarat","Redif","Tekerleme"]'::jsonb, 3, 'edebiyat'),

-- ===================== SPOR =====================
('Futbolda korner atışı ne zaman verilir?', '["Top savunmadan dışarı çıkınca","Faul olunca","Ofsaytta","Penaltıda"]'::jsonb, 0, 'spor'),
('Futbolda ofsayt kuralı neyi engeller?', '["Faulü","Kaleye yakın beklemeyi","Korneri","Taç atışını"]'::jsonb, 1, 'spor'),
('Futbolda taç atışı nasıl yapılır?', '["Tek elle","Ayakla","İki elle baş üstünden","Kafayla"]'::jsonb, 2, 'spor'),
('Futbolda kaleci ceza sahası dışında ne yapamaz?', '["Kaleye dönemez","Koşamaz","Pas veremez","Elle oynayamaz"]'::jsonb, 3, 'spor'),
('Bir futbol sahasının orta çizgisi neyi ayırır?', '["İki yarı sahayı","Ceza sahasını","Kale alanını","Taç çizgisini"]'::jsonb, 0, 'spor'),
('Basketbolda potanın yüksekliği yaklaşık kaç metredir?', '["2,50","3,05","4,00","2,00"]'::jsonb, 1, 'spor'),
('Basketbolda takım kaç faulden sonra ceza atışı verir?', '["7","3","5","10"]'::jsonb, 2, 'spor'),
('Basketbolda topu alan oyuncunun yürümesine ne denir?', '["Asist","Ribaund","Blok","Hatalı adım"]'::jsonb, 3, 'spor'),
('Basketbolda gol pası veren oyuncunun istatistiğine ne denir?', '["Asist","Ribaund","Blok","Top çalma"]'::jsonb, 0, 'spor'),
('Basketbolda sekmiş topu almaya ne denir?', '["Asist","Ribaund","Smaç","Faul"]'::jsonb, 1, 'spor'),
('Voleybolda oyuna başlama vuruşuna ne denir?', '["Blok","Smaç","Servis","Pas"]'::jsonb, 2, 'spor'),
('Voleybolda file üzerinde savunma yapmaya ne denir?', '["Parmak pas","Servis","Manşet","Blok"]'::jsonb, 3, 'spor'),
('Voleybolda alttan karşılama tekniğine ne denir?', '["Manşet","Smaç","Blok","Servis"]'::jsonb, 0, 'spor'),
('Voleybolda savunma uzmanı oyuncuya ne denir?', '["Pasör","Libero","Smaçör","Orta oyuncu"]'::jsonb, 1, 'spor'),
('Tenis maçında ilk sayıya ne denir?', '["5","10","15","1"]'::jsonb, 2, 'spor'),
('Teniste beraberlik durumuna ne denir?', '["Break","Set","Servis","Döys"]'::jsonb, 3, 'spor'),
('Teniste rakibin servisini kırmaya ne denir?', '["Break","Ace","Let","Smaç"]'::jsonb, 0, 'spor'),
('Teniste karşılıksız servis sayısına ne denir?', '["Break","Ace","Döys","Let"]'::jsonb, 1, 'spor'),
('Yüzme havuzu olimpik uzunlukta kaç metredir?', '["100","25","50","75"]'::jsonb, 2, 'spor'),
('Atletizmde en kısa sprint mesafesi hangisidir?', '["1500 metre","400 metre","800 metre","100 metre"]'::jsonb, 3, 'spor'),
('Atletizmde engelli koşuda ne aşılır?', '["Engeller","Su birikintisi yalnızca","Kum","Duvar"]'::jsonb, 0, 'spor'),
('Gülle atmada başarı neye göre ölçülür?', '["Atış süresi","Atış mesafesi","Gülle ağırlığı","Yükseklik"]'::jsonb, 1, 'spor'),
('Sırıkla yüksek atlamada sporcu neyi kullanır?', '["Trambolin","Halat","Sırık","Yay"]'::jsonb, 2, 'spor'),
('Cirit atmada kullanılan alet nasıldır?', '["Disk","Yuvarlak","Ağır küre","Uzun ve ince"]'::jsonb, 3, 'spor'),
('Güreşte rakibi sırtı yere gelecek şekilde yenmeye ne denir?', '["Tuş","Sayı","Pas","Puan"]'::jsonb, 0, 'spor'),
('Yağlı güreşte sporcuların giydiği kıyafete ne denir?', '["Mayo","Kıspet","Şort","Kimono"]'::jsonb, 1, 'spor'),
('Judo ve karatede giyilen kıyafete ne denir?', '["Mayo","Kıspet","Kimono","Forma"]'::jsonb, 2, 'spor'),
('Karatede ustalık seviyeleri neyle gösterilir?', '["Bandana","Forma numarası","Ayakkabı","Kuşak rengi"]'::jsonb, 3, 'spor'),
('Okçulukta hedefin merkezine ne denir?', '["On puanlık alan","Kale","Pota","File"]'::jsonb, 0, 'spor'),
('Binicilikte engel atlama neyle yapılır?', '["Bisiklet","At","Motosiklet","Kızak"]'::jsonb, 1, 'spor'),
('Halterde iki temel hareketten biri hangisidir?', '["Servis","Smaç","Koparma","Blok"]'::jsonb, 2, 'spor'),
('Jimnastikte kullanılan aletlerden biri hangisidir?', '["File","Raket","Sopa","Barfiks"]'::jsonb, 3, 'spor'),
('Artistik patinajda hangi yüzey kullanılır?', '["Buz","Kum","Çim","Tartan"]'::jsonb, 0, 'spor'),
('Kayakta slalom neyi ifade eder?', '["Düz iniş","Kapılar arasından geçiş","Atlayış","Tırmanış"]'::jsonb, 1, 'spor'),
('Snowboard hangi zeminde yapılır?', '["Çim","Su","Kar","Buz pisti"]'::jsonb, 2, 'spor'),
('Sörf hangi doğal etkenden yararlanır?', '["Volkan","Kar","Rüzgâr gülü","Dalga"]'::jsonb, 3, 'spor'),
('Yelken sporunda temel itici güç nedir?', '["Rüzgâr","Motor","Kürek","Akıntı yalnızca"]'::jsonb, 0, 'spor'),
('Kürek sporunda tekneyi yönlendiren kişiye ne denir?', '["Kaptan","Dümenci","Pilot","Şef"]'::jsonb, 1, 'spor'),
('Bisiklet yarışlarında etaplı yarışa ne denir?', '["Kriteryum yalnızca","Sprint","Tur","Zaman denemesi yalnızca"]'::jsonb, 2, 'spor'),
('Maraton adını hangi ülkeden alır?', '["İran","İtalya","Mısır","Yunanistan"]'::jsonb, 3, 'spor'),
('Olimpiyat meşalesi nerede yakılır?', '["Olympia","Atina","Roma","Paris"]'::jsonb, 0, 'spor'),
('Olimpiyat sloganı neyi vurgular?', '["Kazanmak tek amaç","Daha hızlı, daha yüksek, daha güçlü","Rekabet yok","Sadece katılım yasak"]'::jsonb, 1, 'spor'),
('Kış Olimpiyatları hangi sporları içerir?', '["Atletizm","Su sporları","Kar ve buz sporları","Güreş"]'::jsonb, 2, 'spor'),
('Bir spor müsabakasında beraberlik bozmak için oynanan bölüme ne denir?', '["Antrenman","Devre arası","Isınma","Uzatma"]'::jsonb, 3, 'spor'),
('Sporcuların yarışma öncesi yaptığı hazırlığa ne denir?', '["Isınma","Soğuma","Dinlenme","Beslenme"]'::jsonb, 0, 'spor'),
('Doping ne anlama gelir?', '["Antrenman türü","Yasaklı performans artırıcı madde","Beslenme planı","Taktik"]'::jsonb, 1, 'spor'),
('Fair play ne demektir?', '["Hızlı oyun","Sert oyun","Dürüst oyun","Uzun oyun"]'::jsonb, 2, 'spor'),
('Bir takımın oyun planını hazırlayan kişi kimdir?', '["Spiker","Hakem","Gözlemci","Antrenör"]'::jsonb, 3, 'spor'),
('Sporda kondisyon ne anlama gelir?', '["Dayanıklılık düzeyi","Boy uzunluğu","Kilo","Yaş"]'::jsonb, 0, 'spor'),
('Bir maçta oyuncu değişikliği neden yapılır?', '["Sadece hakem isteğiyle","Performans ve sakatlık","Sadece seyirci isteğiyle","Hiçbir sebeple"]'::jsonb, 1, 'spor'),
('Sporda esneme hareketlerinin amacı nedir?', '["Kilo almak","Hız kaybı","Sakatlanmayı azaltmak","Yorulmak"]'::jsonb, 2, 'spor'),
('Takım sporlarında kaptanın görevi nedir?', '["Saha çizmek","Hakemlik yapmak","Bilet satmak","Takımı temsil etmek"]'::jsonb, 3, 'spor'),
('Bir ligde takımların sıralandığı tabloya ne denir?', '["Puan durumu","Fikstür","Kadro","Bilanço"]'::jsonb, 0, 'spor'),

-- ===================== SANAT =====================
('Bir resimde ışık ve gölge kullanımına ne denir?', '["Perspektif","Valör","Kompozisyon","Doku"]'::jsonb, 1, 'sanat'),
('Resimde nesnelerin düzenlenişine ne denir?', '["Doku","Valör","Kompozisyon","Ton"]'::jsonb, 2, 'sanat'),
('Bir yüzeyin dokunma hissini veren özelliğine ne denir?', '["Leke","Ton","Çizgi","Doku"]'::jsonb, 3, 'sanat'),
('Renk çemberinde birbirinin karşısındaki renklere ne denir?', '["Zıt renkler","Ana renkler","Ara renkler","Nötr renkler"]'::jsonb, 0, 'sanat'),
('Kırmızı, sarı ve mavi hangi renk grubudur?', '["Ara renkler","Ana renkler","Zıt renkler","Nötr renkler"]'::jsonb, 1, 'sanat'),
('Yeşil hangi iki rengin karışımıdır?', '["Sarı ve kırmızı","Kırmızı ve mavi","Mavi ve sarı","Beyaz ve siyah"]'::jsonb, 2, 'sanat'),
('Sıcak renklere örnek hangisidir?', '["Mor","Mavi","Yeşil","Turuncu"]'::jsonb, 3, 'sanat'),
('Soğuk renklere örnek hangisidir?', '["Mavi","Kırmızı","Turuncu","Sarı"]'::jsonb, 0, 'sanat'),
('Suluboya hangi çözücüyle kullanılır?', '["Yağ","Su","Alkol","Tiner"]'::jsonb, 1, 'sanat'),
('Karakalem çalışmalarda temel malzeme nedir?', '["Pastel yalnızca","Yağlı boya","Kurşun kalem","Mürekkep yalnızca"]'::jsonb, 2, 'sanat'),
('Heykelde kullanılan malzemelerden biri hangisidir?', '["Cam yalnızca","Kâğıt hamuru yalnızca","Su","Mermer"]'::jsonb, 3, 'sanat'),
('Kabartma heykel türüne ne denir?', '["Rölyef","Büst","Anıt","Torso"]'::jsonb, 0, 'sanat'),
('Bir kişinin baş ve omuz heykeline ne denir?', '["Rölyef","Büst","Anıt","Vitray"]'::jsonb, 1, 'sanat'),
('Renkli camlarla yapılan pencere sanatına ne denir?', '["Fresk","Mozaik","Vitray","Ebru"]'::jsonb, 2, 'sanat'),
('Bir binanın taşıyıcı sistemi ne işe yarar?', '["Süslemek","Renk vermek","Isıtmak","Yükü taşımak"]'::jsonb, 3, 'sanat'),
('Kubbe hangi mimari öğedir?', '["Örtü öğesi","Taşıyıcı sütun","Kapı","Merdiven"]'::jsonb, 0, 'sanat'),
('Kemer mimaride ne sağlar?', '["Isıtmak","Açıklık geçmek","Aydınlatmak","Süsleme yalnızca"]'::jsonb, 1, 'sanat'),
('Sütunun üstündeki başlığa ne denir?', '["Kemer","Kaide","Sütun başlığı","Sacak"]'::jsonb, 2, 'sanat'),
('Antik Yunan mimarisinde bir sütun düzeni hangisidir?', '["Rokoko","Gotik","Barok","Dor"]'::jsonb, 3, 'sanat'),
('Osmanlı mimarisinde son cemaat yeri nerededir?', '["Caminin girişinde","Minarede","Kubbede","Mihrapta"]'::jsonb, 0, 'sanat'),
('Camide kıble yönünü gösteren öğe hangisidir?', '["Minber","Mihrap","Şerefe","Kubbe"]'::jsonb, 1, 'sanat'),
('Camide hutbe okunan yer neresidir?', '["Şadırvan","Mihrap","Minber","Avlu"]'::jsonb, 2, 'sanat'),
('Minarede ezan okunan bölüme ne denir?', '["Gövde","Külah","Kaide","Şerefe"]'::jsonb, 3, 'sanat'),
('Türk çini sanatında en çok kullanılan renk hangisidir?', '["Mavi","Kahverengi","Gri","Siyah"]'::jsonb, 0, 'sanat'),
('Halıda düğüm sıklığı neyi etkiler?', '["Rengi","Kaliteyi","Kokuyu","Ağırlığı yalnızca"]'::jsonb, 1, 'sanat'),
('Kilim ile halı arasındaki temel fark nedir?', '["Halı düz dokumadır","Kilim daha ağırdır","Kilim düğümsüzdür","Fark yoktur"]'::jsonb, 2, 'sanat'),
('Bakır işlemeciliğinde kullanılan teknik hangisidir?', '["Üfleme","Dokuma","Örme","Dövme"]'::jsonb, 3, 'sanat'),
('Cam sanatında şekil vermek için kullanılan yöntem hangisidir?', '["Üfleme","Dokuma","Örme","Kesme yalnızca"]'::jsonb, 0, 'sanat'),
('Ahşap oymacılığında kullanılan alet hangisidir?', '["Mala","Iskarpela","Fırça","Rende yalnızca"]'::jsonb, 1, 'sanat'),
('Bir sanat eserinin sergilendiği geçici etkinliğe ne denir?', '["Gösteri","Konser","Sergi","Yarışma"]'::jsonb, 2, 'sanat'),
('Sanat eserlerinin korunduğu kuruma ne denir?', '["Ofis","Fabrika","Depo","Müze"]'::jsonb, 3, 'sanat'),
('Bir eserin sahteliğini araştıran uzmana ne denir?', '["Eksper","Küratör","Restoratör","Rehber"]'::jsonb, 0, 'sanat'),
('Eski eserlerin onarılmasına ne denir?', '["Rekonstrüksiyon yalnızca","Restorasyon","Demolisyon","Prodüksiyon"]'::jsonb, 1, 'sanat'),
('Sergi düzenleyen ve içeriğini kuran kişiye ne denir?', '["Rehber","Eksper","Küratör","Kasiyer"]'::jsonb, 2, 'sanat'),
('Tiyatroda sahne arkasına ne denir?', '["Loca","Fuaye","Balkon","Kulis"]'::jsonb, 3, 'sanat'),
('Tiyatroda oyuncuya unuttuğu sözü hatırlatan kişiye ne denir?', '["Suflör","Rejisör","Dramaturg","Işıkçı"]'::jsonb, 0, 'sanat'),
('Tiyatroda sahneyi düzenleyen öğelere ne denir?', '["Kostüm","Dekor","Işık","Efekt"]'::jsonb, 1, 'sanat'),
('Trajedi ve komedi hangi sanatın türleridir?', '["Heykel","Resim","Tiyatro","Mimari"]'::jsonb, 2, 'sanat'),
('Pandomim hangi anlatım biçimini kullanır?', '["Yazı","Şarkı","Konuşma","Beden dili"]'::jsonb, 3, 'sanat'),
('Modern dans klasik baleden hangi yönüyle ayrılır?', '["Serbest hareket","Müziksizlik","Kostümsüzlük","Sahnesizlik"]'::jsonb, 0, 'sanat'),
('Fotoğrafta netlik ayarına ne denir?', '["Pozlama","Odaklama","Kadraj","Baskı"]'::jsonb, 1, 'sanat'),
('Fotoğrafta çerçeveleme işlemine ne denir?', '["Poz","Odak","Kadraj","Baskı"]'::jsonb, 2, 'sanat'),
('Grafik tasarımda logo ne işe yarar?', '["Depolamak","Isıtmak","Ölçmek","Kimlik oluşturmak"]'::jsonb, 3, 'sanat'),
('Tipografi neyle ilgilidir?', '["Yazı karakterleri","Renk karışımı","Heykel","Dans"]'::jsonb, 0, 'sanat'),
('Bir afişte en önemli unsur nedir?', '["Kâğıt ağırlığı","Mesajın hızlı anlaşılması","Yazı sayısı","Fiyat"]'::jsonb, 1, 'sanat'),
('Karikatürün temel amacı nedir?', '["Ölçüm","Belgeleme","Eleştiri ve mizah","Kayıt"]'::jsonb, 2, 'sanat'),
('İllüstrasyon nerede kullanılır?', '["Sadece halıda","Sadece heykelde","Sadece binada","Kitap ve dergilerde"]'::jsonb, 3, 'sanat'),
('Bir müzikalde hangi sanatlar birleşir?', '["Müzik, dans ve tiyatro","Sadece resim","Sadece heykel","Sadece mimari"]'::jsonb, 0, 'sanat'),
('Konser salonlarında akustik neyi ifade eder?', '["Işık düzeni","Ses kalitesi","Koltuk sayısı","Sahne rengi"]'::jsonb, 1, 'sanat'),
('Sanat akımlarından Ekspresyonizm neyi öne çıkarır?', '["Ticari kaygıyı","Bilimsel ölçümü","İç duyguları","Belgeselliği"]'::jsonb, 2, 'sanat'),
('Minimalizm neyi savunur?', '["Renk bolluğunu","Aşırı süslemeyi","Karmaşayı","Sadeliği"]'::jsonb, 3, 'sanat'),
('Pop art hangi öğelerden beslenir?', '["Popüler kültür","Antik mitoloji","Dini metinler","Bilimsel formüller"]'::jsonb, 0, 'sanat'),
('Sanatta soyut anlatım ne demektir?', '["Fotoğraf gibi çizme","Gerçeği birebir yansıtmama","Sadece portre","Sadece manzara"]'::jsonb, 1, 'sanat'),
('Bir sanat eserinin özgünlüğü neyi ifade eder?', '["Ucuz olması","Kopya olması","Kendine ait olması","Büyük olması"]'::jsonb, 2, 'sanat'),

-- ===================== SİNEMA =====================
('Sinemada senaryoyu yazan kişiye ne denir?', '["Kurgucu","Yönetmen","Yapımcı","Senarist"]'::jsonb, 3, 'sinema'),
('Filmi finanse eden kişiye ne denir?', '["Yapımcı","Yönetmen","Senarist","Oyuncu"]'::jsonb, 0, 'sinema'),
('Bir sahnenin tek seferde çekilen bölümüne ne denir?', '["Sahne","Plan","Sekans","Perde"]'::jsonb, 1, 'sinema'),
('Oyuncuların tehlikeli sahnelerinde yerine geçen kişiye ne denir?', '["Figüran","Suflör","Dublör","Kurgucu"]'::jsonb, 2, 'sinema'),
('Arka planda görünen ek oyunculara ne denir?', '["Yardımcı yönetmen","Dublör","Başrol","Figüran"]'::jsonb, 3, 'sinema'),
('Filmde seslerin yeniden kaydedilmesine ne denir?', '["Dublaj","Kurgu","Kadraj","Montaj yalnızca görüntü"]'::jsonb, 0, 'sinema'),
('Yabancı filmin alt kısmındaki çeviri yazıya ne denir?', '["Jenerik","Altyazı","Fragman","Afiş"]'::jsonb, 1, 'sinema'),
('Filmde kullanılan müziklerin bütününe ne denir?', '["Diyalog","Efekt","Film müziği","Gürültü"]'::jsonb, 2, 'sinema'),
('Bilgisayarla üretilen görsel efektlerin kısaltması nedir?', '["USB","GPS","HTML","CGI"]'::jsonb, 3, 'sinema'),
('Yeşil perde tekniği ne sağlar?', '["Arka planı değiştirme","Ses artırma","Işık azaltma","Kurgu hızlandırma"]'::jsonb, 0, 'sinema'),
('Stop motion tekniği neye dayanır?', '["Canlı çekim","Kare kare hareket","Ses kaydı","Çizgi olmayan"]'::jsonb, 1, 'sinema'),
('Bir filmin türlerinden biri hangisidir?', '["Roman","Gazete","Komedi","Heykel"]'::jsonb, 2, 'sinema'),
('Korku filmlerinde amaç nedir?', '["Dans öğretmek","Bilgi vermek","Ürün satmak","Gerilim yaratmak"]'::jsonb, 3, 'sinema'),
('Bilim kurgu filmleri neyi konu edinir?', '["Gelecek ve teknoloji","Sadece geçmiş","Sadece tarım","Sadece spor"]'::jsonb, 0, 'sinema'),
('Bir filmin süresine ne denir?', '["Kadraj","Gösterim süresi","Poz","Sekans"]'::jsonb, 1, 'sinema'),
('Sinemada kamera hareketiyle sağa sola dönmeye ne denir?', '["Tilt yalnızca dikey","Zoom","Pan","Kesme"]'::jsonb, 2, 'sinema'),
('Kameranın yukarı aşağı hareketine ne denir?', '["Travelling","Pan","Zoom","Tilt"]'::jsonb, 3, 'sinema'),
('Kameranın raylar üzerinde hareketine ne denir?', '["Travelling","Pan","Tilt","Zoom"]'::jsonb, 0, 'sinema'),
('Bir karakterin yüzünün ekranı doldurduğu plana ne denir?', '["Genel plan","Yakın plan","Boy plan","Omuz plan"]'::jsonb, 1, 'sinema'),
('Mekânın tümünü gösteren plana ne denir?', '["Detay plan","Yakın plan","Genel plan","Omuz plan"]'::jsonb, 2, 'sinema'),
('Sinemada geriye dönüş anlatımına ne denir?', '["Zoom","Fade","Cut","Flashback"]'::jsonb, 3, 'sinema'),
('Sahnenin kararak bitmesine ne denir?', '["Kararma","Kesme","Zoom","Pan"]'::jsonb, 0, 'sinema'),
('Sinemada ilk gösterime ne denir?', '["Fragman","Galası","Tekrar","Prova"]'::jsonb, 1, 'sinema'),
('Bir filmin devam halkalarının tümüne ne denir?', '["Bölüm","Sezon","Seri","Perde"]'::jsonb, 2, 'sinema'),
('Bir yapımın çekimden önceki hazırlık aşamasına ne denir?', '["Dağıtım","Post prodüksiyon","Gösterim","Ön yapım"]'::jsonb, 3, 'sinema'),
('Çekim sonrası kurgu aşamasına ne denir?', '["Post prodüksiyon","Ön yapım","Gala","Fragman"]'::jsonb, 0, 'sinema'),
('Belgesel çekiminde en önemli unsur nedir?', '["Kurgusal olay","Gerçeğe bağlılık","Süper kahraman","Animasyon"]'::jsonb, 1, 'sinema'),
('Bir filmde başrolü destekleyen role ne denir?', '["Dublör","Figüran","Yardımcı rol","Kurgucu"]'::jsonb, 2, 'sinema'),
('Oyuncu seçim sürecine ne denir?', '["Dublaj","Kurgu","Kadraj","Casting"]'::jsonb, 3, 'sinema'),
('Bir filmin yapımında kostümleri hazırlayan kişiye ne denir?', '["Kostüm tasarımcısı","Işıkçı","Kurgucu","Yapımcı"]'::jsonb, 0, 'sinema'),
('Sahne dekorlarını hazırlayan kişiye ne denir?', '["Senarist","Sanat yönetmeni","Yapımcı","Spiker"]'::jsonb, 1, 'sinema'),
('Sinemada "sessiz film" dönemi neyle sona ermiştir?', '["Dijital kamerayla","Renkli filmle","Sesli filmin gelişiyle","3 boyutla"]'::jsonb, 2, 'sinema'),
('Animasyonda saniyede gösterilen kare sayısına ne denir?', '["Doygunluk","Çözünürlük","Kontrast","Kare hızı"]'::jsonb, 3, 'sinema'),
('Sinema salonlarında perdeye görüntüyü yansıtan cihaz hangisidir?', '["Projeksiyon","Hoparlör","Mikser","Kamera"]'::jsonb, 0, 'sinema'),
('Bir dizinin tekrar eden açılış müziğine ne denir?', '["Efekt","Jenerik müziği","Diyalog","Dublaj"]'::jsonb, 1, 'sinema'),
('Sinemada "uyarlama" ne demektir?', '["Ses ekleme","Yeniden çekim yalnızca","Bir eserden filme çevirme","Altyazı"]'::jsonb, 2, 'sinema'),
('Bir filmin yeniden çekilmesine ne denir?', '["Kısa film","Devam filmi","Ön hikâye","Yeniden yapım"]'::jsonb, 3, 'sinema'),
('Ana hikâyenin öncesini anlatan filme ne denir?', '["Ön hikâye","Devam filmi","Yeniden yapım","Belgesel"]'::jsonb, 0, 'sinema'),
('Kısa filmlerin genel özelliği nedir?', '["Renksiz olması","Kısa süreli olması","Sessiz olması","Oyuncusuz olması"]'::jsonb, 1, 'sinema'),
('Sinemada gişe ne anlama gelir?', '["Ses stüdyosu","Kurgu odası","Bilet satışı","Kamera"]'::jsonb, 2, 'sinema'),
('Bir filmin yaş sınırı neyi belirtir?', '["Ülkeyi","Süreyi","Bütçeyi","İzleyici uygunluğunu"]'::jsonb, 3, 'sinema'),
('Yeşilçam adı nereden gelir?', '["İstanbul''daki bir sokaktan","Bir ağaçtan","Bir oyuncudan","Bir filmden"]'::jsonb, 0, 'sinema'),
('Sinemada "kült film" ne demektir?', '["Yeni çıkan film","Sadık bir izleyici kitlesi kazanan film","Kısa film","Sessiz film"]'::jsonb, 1, 'sinema'),
('Film festivallerinin temel amacı nedir?', '["Oyuncu seçmek","Bilet satmak yalnızca","Filmleri tanıtmak","Kamera satmak"]'::jsonb, 2, 'sinema'),
('Bir filmde "mizansen" ne demektir?', '["Yaş sınırı","Ses seviyesi","Bilet fiyatı","Sahne düzeni"]'::jsonb, 3, 'sinema'),
('Sinemada ışığın az kullanıldığı karanlık atmosferli stile ne denir?', '["Kara film","Komedi","Müzikal","Belgesel"]'::jsonb, 0, 'sinema'),
('Animasyon filmlerinde seslendirme kim tarafından yapılır?', '["Kurgucular","Seslendirme sanatçıları","Yapımcılar","Işıkçılar"]'::jsonb, 1, 'sinema'),
('Bir dizi bölümünün sonundaki merak uyandıran kesintiye ne denir?', '["Fragman","Jenerik","Cliffhanger","Dublaj"]'::jsonb, 2, 'sinema'),
('Sinemada 3 boyutlu izleme için ne gerekir?', '["Mikrofon","Kulaklık","Eldiven","Özel gözlük"]'::jsonb, 3, 'sinema'),
('Bir filmin tanıtım afişine ne denir?', '["Poster","Jenerik","Altyazı","Kadraj"]'::jsonb, 0, 'sinema'),
('Sinemada senaryonun bölümlerine ne denir?', '["Perde yalnızca tiyatro","Sahne","Kıta","Beyit"]'::jsonb, 1, 'sinema'),
('Bir filmin çekildiği yere ne denir?', '["Fuaye","Kulis","Set","Loca"]'::jsonb, 2, 'sinema'),
('Filmde "efekt" ne anlama gelir?', '["Perde","Bilet","Koltuk","Özel görsel veya işitsel etki"]'::jsonb, 3, 'sinema'),
('Bir yapımın çekim planını gösteren çizimlere ne denir?', '["Storyboard","Afiş","Bilet","Program"]'::jsonb, 0, 'sinema'),
('Sinemada "final" ne demektir?', '["Filmin başı","Filmin sonu","Ara","Fragman"]'::jsonb, 1, 'sinema'),

-- ===================== MÜZİK =====================
('Müzikte sesin inceliği kalınlığına ne denir?', '["Tını","Şiddet","Ses yüksekliği","Süre"]'::jsonb, 2, 'muzik'),
('Aynı notayı çalan iki farklı çalgının ayırt edilmesini sağlayan özellik nedir?', '["Ölçü","Tempo","Nüans","Tını"]'::jsonb, 3, 'muzik'),
('Müzikte sessizliği gösteren işaretlere ne denir?', '["Es","Nota","Bağ","Nokta"]'::jsonb, 0, 'muzik'),
('Notaların süresini uzatan işaret hangisidir?', '["Es","Uzatma bağı","Anahtar","Ölçü çizgisi"]'::jsonb, 1, 'muzik'),
('Portenin başına konan işarete ne denir?', '["Nüans","Es","Anahtar","Bağ"]'::jsonb, 2, 'muzik'),
('Sol anahtarı hangi çizgide yazılır?', '["Dördüncü","Birinci","Üçüncü","İkinci"]'::jsonb, 3, 'muzik'),
('Bir sesin yarım ton yükseltilmesini sağlayan işaret hangisidir?', '["Diyez","Bemol","Bekar","Nokta"]'::jsonb, 0, 'muzik'),
('Bir sesin yarım ton alçaltılmasını sağlayan işaret hangisidir?', '["Diyez","Bemol","Bekar","Bağ"]'::jsonb, 1, 'muzik'),
('Diyez ve bemolün etkisini kaldıran işaret hangisidir?', '["Es","Nokta","Bekar","Bağ"]'::jsonb, 2, 'muzik'),
('Bir oktavda kaç ses bulunur (tam ses aralıklarıyla)?', '["3","5","12","8"]'::jsonb, 3, 'muzik'),
('Piyanoda siyah tuşlar neyi gösterir?', '["Diyez ve bemolleri","Sadece doları","Sadece re''yi","Es işaretlerini"]'::jsonb, 0, 'muzik'),
('Gitarda ses yüksekliği neyle değişir?', '["Renk","Perde basma","Kılıf","Askı"]'::jsonb, 1, 'muzik'),
('Bir çalgı topluluğuna ne denir?', '["Solo","Koro","Orkestra","Resital"]'::jsonb, 2, 'muzik'),
('Tek bir sanatçının verdiği konsere ne denir?', '["Düet","Orkestra","Koro","Resital"]'::jsonb, 3, 'muzik'),
('İki kişinin birlikte söylediği parçaya ne denir?', '["Düet","Solo","Trio","Kuartet"]'::jsonb, 0, 'muzik'),
('Üç kişilik müzik topluluğuna ne denir?', '["Düet","Trio","Kuartet","Kuintet"]'::jsonb, 1, 'muzik'),
('Beş kişilik müzik topluluğuna ne denir?', '["Trio","Kuartet","Kuintet","Düet"]'::jsonb, 2, 'muzik'),
('Senfoni hangi topluluk tarafından seslendirilir?', '["Koro yalnızca","Tek kişi","İki kişi","Orkestra"]'::jsonb, 3, 'muzik'),
('Konçerto neyi öne çıkarır?', '["Solo çalgıyı","Koroyu","Dansı","Dekoru"]'::jsonb, 0, 'muzik'),
('Operada şarkı söyleyerek oynayan sanatçıya ne denir?', '["Balerin","Opera sanatçısı","Ressam","Şef"]'::jsonb, 1, 'muzik'),
('Operet operadan hangi yönüyle ayrılır?', '["Dansız olması","Sessiz olması","Daha hafif konulu olması","Kısa olmaması"]'::jsonb, 2, 'muzik'),
('Bale gösterilerinde müzik nasıl kullanılır?', '["Sadece başta","Hiç kullanılmaz","Sadece sonda","Dansa eşlik eder"]'::jsonb, 3, 'muzik'),
('Türk halk müziğinde kırık hava neyi ifade eder?', '["Ölçülü ezgi","Serbest ezgi","Sessizlik","Nakarat"]'::jsonb, 0, 'muzik'),
('Türk halk müziğinde bağlamanın tellerine ne denir?', '["Perde","Tel","Sap","Tekne"]'::jsonb, 1, 'muzik'),
('Bağlamanın gövde kısmına ne denir?', '["Burgu","Sap","Tekne","Eşik"]'::jsonb, 2, 'muzik'),
('Bağlamada tellerin gerginliğini ayarlayan parça hangisidir?', '["Perde","Tekne","Eşik","Burgu"]'::jsonb, 3, 'muzik'),
('Kaval hangi tür çalgıdır?', '["Nefesli","Telli","Vurmalı","Tuşlu"]'::jsonb, 0, 'muzik'),
('Zurna genellikle hangi çalgıyla birlikte çalınır?', '["Keman","Davul","Piyano","Ud"]'::jsonb, 1, 'muzik'),
('Tulum hangi bölgemizin çalgısıdır?', '["Akdeniz","Ege","Karadeniz","İç Anadolu"]'::jsonb, 2, 'muzik'),
('Kemençe hangi bölgemizle özdeşleşmiştir?', '["Marmara","Güneydoğu","İç Anadolu","Karadeniz"]'::jsonb, 3, 'muzik'),
('Def hangi tür çalgıdır?', '["Vurmalı","Telli","Nefesli","Tuşlu"]'::jsonb, 0, 'muzik'),
('Kaşık hangi tür çalgı olarak kullanılır?', '["Telli","Vurmalı","Nefesli","Yaylı"]'::jsonb, 1, 'muzik'),
('Klarnet hangi tür çalgıdır?', '["Vurmalı","Telli","Nefesli","Tuşlu"]'::jsonb, 2, 'muzik'),
('Trompet hangi tür çalgıdır?', '["Tuşlu","Yaylı","Vurmalı","Bakır nefesli"]'::jsonb, 3, 'muzik'),
('Arp hangi tür çalgıdır?', '["Telli","Nefesli","Vurmalı","Tuşlu"]'::jsonb, 0, 'muzik'),
('Org hangi tür çalgıdır?', '["Yaylı","Tuşlu","Vurmalı","Telli mızraplı"]'::jsonb, 1, 'muzik'),
('Ksilofon hangi tür çalgıdır?', '["Nefesli","Yaylı","Vurmalı","Tuşlu"]'::jsonb, 2, 'muzik'),
('Bir şarkının sözsüz çalınan haline ne denir?', '["Koro","Akapella","Düet","Enstrümantal"]'::jsonb, 3, 'muzik'),
('Sadece insan sesiyle söylenen müziğe ne denir?', '["Akapella","Enstrümantal","Senfoni","Konçerto"]'::jsonb, 0, 'muzik'),
('Blues müziği hangi kültürden doğmuştur?', '["İskandinav","Afroamerikan","Kelt","Slav"]'::jsonb, 1, 'muzik'),
('Reggae müziği hangi ada ülkesiyle özdeşleşmiştir?', '["Malta","İzlanda","Jamaika","Kıbrıs"]'::jsonb, 2, 'muzik'),
('Rock müziğinin temel çalgılarından biri hangisidir?', '["Arp","Ney","Kanun","Elektro gitar"]'::jsonb, 3, 'muzik'),
('Rap müziğinde öne çıkan öğe nedir?', '["Sözlerin ritmik söylenişi","Bale","Opera","Senfoni"]'::jsonb, 0, 'muzik'),
('Elektronik müzikte sesler nasıl üretilir?', '["Sadece yaylılarla","Elektronik cihazlarla","Sadece nefeslilerle","Sadece koroyla"]'::jsonb, 1, 'muzik'),
('Bir müzik kaydında miksaj ne yapar?', '["Bilet satar","Işık ayarlar","Sesleri dengeler","Sahne kurar"]'::jsonb, 2, 'muzik'),
('Stüdyo kayıtlarında mikrofon ne işe yarar?', '["Tempo tutmak","Işık vermek","Notaları yazmak","Sesi kaydetmek"]'::jsonb, 3, 'muzik'),
('Kulaklıkla dinlemenin uzun sürede riski nedir?', '["İşitme kaybı","Görme kaybı","Tat kaybı","Koku kaybı"]'::jsonb, 0, 'muzik'),
('Bir eserin nota yazısına ne denir?', '["Afiş","Partisyon","Broşür","Bilet"]'::jsonb, 1, 'muzik'),
('Orkestra şefinin elindeki çubuğa ne denir?', '["Mızrap","Yay","Baget","Tel"]'::jsonb, 2, 'muzik'),
('Yaylı çalgılarda kullanılan araca ne denir?', '["Tokmak","Mızrap","Baget","Yay"]'::jsonb, 3, 'muzik'),
('Ud ve bağlamada tellere vurmak için kullanılan araca ne denir?', '["Mızrap","Yay","Baget","Tokmak"]'::jsonb, 0, 'muzik'),
('Bir konserde sahne düzenini kuran ekip hangisidir?', '["Kurgu ekibi","Sahne ekibi","Bilet ekibi","Güvenlik yalnızca"]'::jsonb, 1, 'muzik'),
('Müzikte "canlı performans" ne demektir?', '["Nota okuma","Kayıttan çalma","Sahnede anlık icra","Prova"]'::jsonb, 2, 'muzik'),
('Bir müzik albümündeki parçalara ne denir?', '["Sahne","Bölüm","Perde","Şarkı"]'::jsonb, 3, 'muzik'),

-- ===================== TEKNOLOJİ =====================
('Bilgisayarda kalıcı bellek hangisidir?', '["Sabit disk","RAM","Ön bellek","Kayıtçı"]'::jsonb, 0, 'teknoloji'),
('Ekran kartının görevi nedir?', '["Ses üretmek","Görüntü işlemek","Veri saklamak","Ağa bağlanmak"]'::jsonb, 1, 'teknoloji'),
('Anakart ne işe yarar?', '["Ses kaydeder","Görüntü üretir","Parçaları birbirine bağlar","İnternet sağlar"]'::jsonb, 2, 'teknoloji'),
('Bir bilgisayarın açılışını yöneten temel yazılım hangisidir?', '["Oyun","Tarayıcı","Ofis programı","BIOS"]'::jsonb, 3, 'teknoloji'),
('İşletim sistemine örnek hangisidir?', '["Linux","Excel","Photoshop","Chrome"]'::jsonb, 0, 'teknoloji'),
('Web tarayıcısına örnek hangisidir?', '["Windows","Firefox","Linux","Android"]'::jsonb, 1, 'teknoloji'),
('Arama motoruna örnek hangisidir?', '["Excel","Word","Google","Paint"]'::jsonb, 2, 'teknoloji'),
('Bir sitenin alan adındaki ".com" ne ifade eder?', '["IP adresi","Şifre","Sunucu adı","Üst düzey alan adı"]'::jsonb, 3, 'teknoloji'),
('DNS ne işe yarar?', '["Alan adını IP''ye çevirir","Ses üretir","Görüntü işler","Dosya siler"]'::jsonb, 0, 'teknoloji'),
('Bir ağda yönlendirme yapan cihaz hangisidir?', '["Yazıcı","Router","Tarayıcı","Hoparlör"]'::jsonb, 1, 'teknoloji'),
('Wi-Fi şifresinin güçlü olması neyi sağlar?', '["Menzili artırır","Hızı artırır","Yetkisiz erişimi engeller","Pil ömrünü uzatır"]'::jsonb, 2, 'teknoloji'),
('VPN ne sağlar?', '["Daha çok RAM","Daha büyük ekran","Daha çok pil","Şifreli bağlantı"]'::jsonb, 3, 'teknoloji'),
('Kimlik avı (phishing) saldırısı neyi hedefler?', '["Kullanıcı bilgilerini çalmak","Ekranı büyütmek","Sesi kısmak","Dosya oluşturmak"]'::jsonb, 0, 'teknoloji'),
('Fidye yazılımı ne yapar?', '["Ekranı temizler","Dosyaları kilitler","Pil şarj eder","Ses açar"]'::jsonb, 1, 'teknoloji'),
('Güvenlik duvarı ne işe yarar?', '["Dosya yazar","Ekran parlatır","Ağ trafiğini denetler","Ses üretir"]'::jsonb, 2, 'teknoloji'),
('Yedekleme neden önemlidir?', '["Pil ömrünü uzatır","Hızı artırır","Ekranı büyütür","Veri kaybını önler"]'::jsonb, 3, 'teknoloji'),
('Şifreleme ne yapar?', '["Veriyi okunamaz hale getirir","Veriyi siler","Veriyi çoğaltır","Veriyi yazdırır"]'::jsonb, 0, 'teknoloji'),
('Bir yazılımın güncellenmesi neden gerekir?', '["Yer kaplamak","Güvenlik açıklarını kapatmak","Yavaşlatmak","Renk değiştirmek"]'::jsonb, 1, 'teknoloji'),
('Açık kaynak bir işletim sistemi hangisidir?', '["macOS","Windows","Linux","iOS"]'::jsonb, 2, 'teknoloji'),
('Programlama dillerine örnek hangisidir?', '["Zip","Word","Excel","Python"]'::jsonb, 3, 'teknoloji'),
('Bir programın çalışması için yazılan komut dizisine ne denir?', '["Kod","Piksel","Bit","Klasör"]'::jsonb, 0, 'teknoloji'),
('Kodda tekrarlanan işlemler için ne kullanılır?', '["Değişken yalnızca","Döngü","Yorum","Boşluk"]'::jsonb, 1, 'teknoloji'),
('Veriyi geçici tutan kod öğesine ne denir?', '["Yorum","Döngü","Değişken","Fonksiyon çağrısı"]'::jsonb, 2, 'teknoloji'),
('Kod içinde açıklama satırlarına ne denir?', '["Dizi","Döngü","Değişken","Yorum"]'::jsonb, 3, 'teknoloji'),
('Bir veri tabanında bilgiler nasıl saklanır?', '["Tablolarda","Resimlerde","Seslerde","Videolarda"]'::jsonb, 0, 'teknoloji'),
('SQL ne için kullanılır?', '["Resim çizme","Veri tabanı sorgulama","Video kesme","Ses kaydetme"]'::jsonb, 1, 'teknoloji'),
('Bir web sayfasının görünümünü belirleyen dil hangisidir?', '["PDF","SQL","CSS","ZIP"]'::jsonb, 2, 'teknoloji'),
('Bir web sayfasına etkileşim katan dil hangisidir?', '["XML","CSS","HTML","JavaScript"]'::jsonb, 3, 'teknoloji'),
('Mobil uygulamaların dağıtıldığı platformlara ne denir?', '["Uygulama mağazası","Tarayıcı","Modem","Yazıcı"]'::jsonb, 0, 'teknoloji'),
('Bir cihazın işletim sistemini güncellemek neyi sağlar?', '["Daha az pil","Yeni özellik ve güvenlik","Daha küçük ekran","Daha az bellek"]'::jsonb, 1, 'teknoloji'),
('Dokunmatik ekranlarda çoklu dokunma ne sağlar?', '["Daha çok ses","Daha çok pil","Yakınlaştırma gibi hareketler","Daha çok bellek"]'::jsonb, 2, 'teknoloji'),
('Bir fotoğrafın çözünürlüğü neyle ölçülür?', '["Litre","Desibel","Newton","Piksel"]'::jsonb, 3, 'teknoloji'),
('JPEG ne tür bir dosya biçimidir?', '["Görüntü","Ses","Video","Metin"]'::jsonb, 0, 'teknoloji'),
('MP3 ne tür bir dosya biçimidir?', '["Görüntü","Ses","Metin","Tablo"]'::jsonb, 1, 'teknoloji'),
('PDF biçiminin avantajı nedir?', '["Otomatik çevirisi","Sesli olması","Biçimin korunması","Sonsuz boyut"]'::jsonb, 2, 'teknoloji'),
('Bir dosyanın sıkıştırılması neyi azaltır?', '["Adını","Kaliteyi her zaman","Sayısını","Boyutu"]'::jsonb, 3, 'teknoloji'),
('Bulut depolamanın avantajı nedir?', '["Her yerden erişim","Sonsuz hız","Elektrik üretimi","Isıtma"]'::jsonb, 0, 'teknoloji'),
('Yapay zekâda "veri seti" ne demektir?', '["Bir donanım","Öğrenme için kullanılan veriler","Bir kablo","Bir ekran"]'::jsonb, 1, 'teknoloji'),
('Robotlar hangi alanda yaygın kullanılır?', '["Resim yalnızca","Şiir","Üretim","Dans yalnızca"]'::jsonb, 2, 'teknoloji'),
('3B yazıcı ne yapar?', '["Video çeker","Kâğıda basar","Ses üretir","Katman katman nesne üretir"]'::jsonb, 3, 'teknoloji'),
('Drone en çok hangi amaçla kullanılır?', '["Havadan görüntüleme","Yer altı kazısı","Su arıtma","Isıtma"]'::jsonb, 0, 'teknoloji'),
('Sanal gerçeklik gözlüğü ne sağlar?', '["Isı ölçümü","Üç boyutlu ortam deneyimi","Ağırlık ölçümü","Koku üretimi"]'::jsonb, 1, 'teknoloji'),
('Artırılmış gerçeklik ne yapar?', '["Sesi keser","Ekranı kapatır","Gerçek görüntüye dijital öğe ekler","Pili şarj eder"]'::jsonb, 2, 'teknoloji'),
('Nesnelerin interneti ne demektir?', '["Ekran büyütme","İnternetin kapanması","Kablo üretimi","Cihazların ağa bağlanması"]'::jsonb, 3, 'teknoloji'),
('Akıllı saatler hangi verileri ölçebilir?', '["Adım ve nabız","Kan grubu","Boy","Göz numarası"]'::jsonb, 0, 'teknoloji'),
('Bir bilgisayarın aşırı ısınmasını önleyen parça hangisidir?', '["Klavye","Fan","Fare","Hoparlör"]'::jsonb, 1, 'teknoloji'),
('USB bağlantısı ne için kullanılır?', '["Aydınlatma","Isıtma","Veri aktarımı","Ölçüm"]'::jsonb, 2, 'teknoloji'),
('HDMI kablosu neyi taşır?', '["Sadece veri yok","Sadece elektrik","Sadece su","Görüntü ve ses"]'::jsonb, 3, 'teknoloji'),
('Bir cihazın fabrika ayarlarına dönmesi ne yapar?', '["Ayarları sıfırlar","Donanımı değiştirir","Ekranı büyütür","Pil ekler"]'::jsonb, 0, 'teknoloji'),
('Çevrim içi güvenlikte en temel önlem nedir?', '["Şifreyi paylaşmak","Güçlü ve farklı şifreler","Aynı şifreyi kullanmak","Şifresiz gezmek"]'::jsonb, 1, 'teknoloji'),
('Bir e-postadaki şüpheli bağlantıya ne yapılmalı?', '["Paylaşılmalı","Hemen tıklanmalı","Tıklanmamalı","İndirilmeli"]'::jsonb, 2, 'teknoloji'),
('Dijital ayak izi ne demektir?', '["Pil ömrü","Ayakkabı numarası","Ekran boyutu","İnternette bıraktığımız veri izi"]'::jsonb, 3, 'teknoloji'),
('Çerezler (cookie) ne işe yarar?', '["Site tercihlerini saklamak","Ekran temizlemek","Ses açmak","Pil şarj etmek"]'::jsonb, 0, 'teknoloji'),
('Bir yazılımın lisansı neyi belirler?', '["Renk paletini","Kullanım koşullarını","Ekran boyutunu","Pil ömrünü"]'::jsonb, 1, 'teknoloji'),
('Klavyede kopyalama kısayolu genellikle hangisidir?', '["Ctrl+S","Ctrl+P","Ctrl+C","Ctrl+N"]'::jsonb, 2, 'teknoloji')

on conflict (soru) do nothing;

-- ===================== EK (denetimde elenenlerin yerine) =====================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Osmanlı''da şehzadelerin yönetim tecrübesi kazandığı uygulamaya ne denirdi?', '["Müsadere","Devşirme","Tımar","Sancağa çıkma"]'::jsonb, 3, 'tarih'),
('Anadolu''da Karahanlılar hangi alanda ilk sayılır?', '["İlk Müslüman Türk devleti olma","İlk denizci devlet","İlk matbaa","İlk üniversite"]'::jsonb, 0, 'tarih'),
('Osmanlı''da esnaf birliklerine ne ad verilirdi?', '["Divan","Lonca","Medrese","Vakıf"]'::jsonb, 1, 'tarih'),
('Kavimler Göçü''nü başlatan topluluk hangisidir?', '["Normanlar","Vikingler","Hunlar","Keltler"]'::jsonb, 2, 'tarih'),
('Osmanlı''da devlet gelirlerinin kaydedildiği deftere ne denirdi?', '["Menakıpname","Seyahatname","Divan şiiri","Tahrir defteri"]'::jsonb, 3, 'tarih'),
('Bir cismin birim hacmindeki kütlesine ne denir?', '["Yoğunluk","Ağırlık","Hacim","Basınç"]'::jsonb, 0, 'bilim'),
('Kaldıraçta yükü kaldırmayı kolaylaştıran nokta hangisidir?', '["Yük noktası","Destek noktası","Kuvvet ucu","Kol ucu"]'::jsonb, 1, 'bilim'),
('Bir cismin şekli bozulduktan sonra eski haline dönmesine ne denir?', '["Kırılganlık","Sertlik","Esneklik","Yoğunluk"]'::jsonb, 2, 'bilim'),
('Bitkilerin ışığa yönelmesine ne denir?', '["Çimlenme","Fotosentez","Terleme","Fototropizma"]'::jsonb, 3, 'bilim'),
('Voleybolda bir takım topa en fazla kaç kez dokunabilir?', '["3","2","4","5"]'::jsonb, 0, 'spor'),
('Futbolda hakemin yardımcılarına ne denir?', '["Gözlemci","Yardımcı hakem","Delege","Spiker"]'::jsonb, 1, 'spor'),
('Bir turnuvada eleme usulüyle oynanan sisteme ne denir?', '["Puanlı sistem","Lig sistemi","Kupa sistemi","Devreli sistem"]'::jsonb, 2, 'spor'),
('Bir bölgenin doğal bitki örtüsünü bozan insan etkinliği hangisidir?', '["Sulak alan koruma","Ağaçlandırma","Erozyon önleme","Aşırı otlatma"]'::jsonb, 3, 'cografya'),
('Kıyı çizgisinin girintili çıkıntılı olması neyi artırır?', '["Doğal liman sayısını","Yağış miktarını","Deprem riskini","Nüfusu doğrudan"]'::jsonb, 0, 'cografya'),
('Bir eserin hangi hızda çalınacağını gösteren İtalyanca terimlerden biri hangisidir?', '["Forte","Allegro","Piano","Crescendo"]'::jsonb, 1, 'muzik'),
('Müzikte sesin gürlüğünü artırmayı gösteren terim hangisidir?', '["Allegro","Diminuendo","Crescendo","Adagio"]'::jsonb, 2, 'muzik'),
('Bir binanın cephesindeki süsleme öğelerine genel olarak ne denir?', '["İzolasyon","Taşıyıcı","Temel","Bezeme"]'::jsonb, 3, 'sanat')
on conflict (soru) do nothing;

-- ===================== KARIŞTIRMA =====================
-- Doğru cevap hep aynı şıkta olmasın: SADECE bu partide eklenen soruların
-- şıkları karıştırılır. `created_at >= transaction_timestamp()` koşulu
-- ZORUNLUDUR; onsuz tüm havuzun şıkları karışır ve o an oynanan maçlarda
-- şık indeksleri kayar.
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
