-- Soru havuzu genişletme: cografya +134
-- Tüm sorular canlı havuza karşı birebir ve anahtar kelime örtüşme
-- süzgecinden geçirildi; doğru şık dağılımı kategori içinde dengelidir.
insert into public.questions (soru, secenekler, dogru_cevap, kategori) values
('Türkiye''nin kara sınırı en uzun olduğu komşusu hangisidir?', '["Suriye","İran","Irak","Bulgaristan"]'::jsonb, 0, 'cografya'),
('Türkiye''nin Avrupa''daki komşuları hangileridir?', '["Romanya ve Sırbistan","Yunanistan ve Bulgaristan","Arnavutluk ve Makedonya","Moldova ve Ukrayna"]'::jsonb, 1, 'cografya'),
('Nahçıvan üzerinden Türkiye hangi ülkeyle sınır komşusudur?', '["Ermenistan","Gürcistan","Azerbaycan","Türkmenistan"]'::jsonb, 2, 'cografya'),
('Türkiye''nin doğudaki en uç ili hangisidir?', '["Kars","Ağrı","Van","Iğdır"]'::jsonb, 3, 'cografya'),
('Türkiye''nin en yüksek rakımlı ili hangisidir?', '["Erzurum","Kars","Van","Bitlis"]'::jsonb, 0, 'cografya'),
('Hakkari hangi bölgemizde yer alır?', '["Güneydoğu Anadolu","Doğu Anadolu","İç Anadolu","Akdeniz"]'::jsonb, 1, 'cografya'),
('Mardin hangi bölgemizde yer alır?', '["Doğu Anadolu","Akdeniz","Güneydoğu Anadolu","İç Anadolu"]'::jsonb, 2, 'cografya'),
('Bilecik hangi bölgemizde yer alır?', '["Ege","İç Anadolu","Karadeniz","Marmara"]'::jsonb, 3, 'cografya'),
('Afyonkarahisar hangi bölgemizde yer alır?', '["Ege","İç Anadolu","Akdeniz","Marmara"]'::jsonb, 0, 'cografya'),
('Karaman hangi bölgemizde yer alır?', '["Akdeniz","İç Anadolu","Ege","Güneydoğu Anadolu"]'::jsonb, 1, 'cografya'),
('Bartın hangi denize kıyısı olan ildir?', '["Marmara","Ege","Karadeniz","Akdeniz"]'::jsonb, 2, 'cografya'),
('Osmaniye hangi bölgemizde yer alır?', '["Güneydoğu Anadolu","İç Anadolu","Doğu Anadolu","Akdeniz"]'::jsonb, 3, 'cografya'),
('Türkiye''nin yedi coğrafi bölgesinden hangisi en büyük yüzölçümüne sahiptir?', '["Doğu Anadolu","İç Anadolu","Karadeniz","Akdeniz"]'::jsonb, 0, 'cografya'),
('Türkiye''nin en küçük coğrafi bölgesi hangisidir?', '["Marmara","Güneydoğu Anadolu","Ege","Akdeniz"]'::jsonb, 1, 'cografya'),
('Ergene Havzası hangi bölgemizde yer alır?', '["Ege","Karadeniz","Marmara","İç Anadolu"]'::jsonb, 2, 'cografya'),
('Amik Ovası hangi ilimizdedir?', '["Adana","Mersin","Osmaniye","Hatay"]'::jsonb, 3, 'cografya'),
('Gediz Ovası hangi ilimizin sınırlarındadır?', '["Manisa","Denizli","Aydın","Muğla"]'::jsonb, 0, 'cografya'),
('Söke Ovası hangi nehrin oluşturduğu ovadır?', '["Gediz","Büyük Menderes","Küçük Menderes","Bakırçay"]'::jsonb, 1, 'cografya'),
('Muş Ovası hangi bölgemizdedir?', '["Güneydoğu Anadolu","Karadeniz","Doğu Anadolu","İç Anadolu"]'::jsonb, 2, 'cografya'),
('Harran Ovası hangi ilimizde yer alır?', '["Mardin","Diyarbakır","Gaziantep","Şanlıurfa"]'::jsonb, 3, 'cografya'),
('Çukurova''nın sulanmasında hangi baraj öne çıkar?', '["Seyhan Barajı","Keban Barajı","Hirfanlı Barajı","Altınkaya Barajı"]'::jsonb, 0, 'cografya'),
('Hirfanlı Barajı hangi nehir üzerindedir?', '["Yeşilırmak","Kızılırmak","Sakarya","Fırat"]'::jsonb, 1, 'cografya'),
('Türkiye''de en çok baraj hangi amaçla kurulmuştur?', '["Balıkçılık","Turizm","Sulama ve enerji","Ulaşım"]'::jsonb, 2, 'cografya'),
('Ilısu Barajı hangi nehir üzerindedir?', '["Fırat","Aras","Murat","Dicle"]'::jsonb, 3, 'cografya'),
('Türkiye''nin akarsularının genel özelliği nedir?', '["Rejimlerinin düzensiz olması","Yıl boyu sabit debili olması","Ulaşıma elverişli olması","Uzunluklarının fazlalığı"]'::jsonb, 0, 'cografya'),
('Türkiye''de akarsuların ulaşıma elverişsiz olmasının nedeni nedir?', '["Suyun tuzlu olması","Eğimin fazla ve debinin değişken olması","Kışın donmaları","Kısa olmaları"]'::jsonb, 1, 'cografya'),
('Türkiye''nin hidroelektrik potansiyeli en yüksek nehri hangisidir?', '["Meriç","Susurluk","Fırat","Bakırçay"]'::jsonb, 2, 'cografya'),
('Doğal göllerin en yoğun olduğu bölgemiz hangisidir?', '["Trakya","Çukurova","Ergene","Göller Yöresi"]'::jsonb, 3, 'cografya'),
('Göller Yöresi hangi bölgemizde yer alır?', '["Akdeniz","Ege","İç Anadolu","Marmara"]'::jsonb, 0, 'cografya'),
('Acıgöl hangi özelliğiyle bilinir?', '["Balıkçılığıyla","Tuz üretimiyle","Kayak turizmiyle","Sulamayla"]'::jsonb, 1, 'cografya'),
('Çıldır Gölü hangi ilimizin sınırlarındadır?', '["Kars","Iğdır","Ardahan","Erzurum"]'::jsonb, 2, 'cografya'),
('Türkiye''nin en büyük sulak alanlarından Kızılırmak Deltası hangi ildedir?', '["Sinop","Ordu","Trabzon","Samsun"]'::jsonb, 3, 'cografya'),
('Kuş göç yollarının korunmasının amacı nedir?', '["Biyolojik çeşitliliği sürdürmek","Tarımı artırmak","Turizmi kısıtlamak","Su tüketimini artırmak"]'::jsonb, 0, 'cografya'),
('Milli park ilan edilmenin temel amacı nedir?', '["Sanayi kurmak","Doğal ve kültürel değeri korumak","Yol yapmak","Maden çıkarmak"]'::jsonb, 1, 'cografya'),
('Nemrut Dağı Milli Parkı hangi ilimizdedir?', '["Bitlis","Malatya","Adıyaman","Kahramanmaraş"]'::jsonb, 2, 'cografya'),
('Ağrı Dağı Milli Parkı''nın en belirgin özelliği nedir?', '["En büyük mağarası","En uzun kanyonu","En geniş deltası","Türkiye''nin en yüksek zirvesi"]'::jsonb, 3, 'cografya'),
('Damlataş Mağarası hangi ilçemizdedir?', '["Alanya","Kaş","Marmaris","Bodrum"]'::jsonb, 0, 'cografya'),
('Karain Mağarası hangi bakımdan önemlidir?', '["Termal suyu","Tarih öncesi yerleşim izleri","Buz oluşumu","Maden yatağı"]'::jsonb, 1, 'cografya'),
('Ülkelerin başkentleri arasında Portekiz''in başkenti hangisidir?', '["Porto","Braga","Lizbon","Coimbra"]'::jsonb, 2, 'cografya'),
('Finlandiya''nın başkenti hangisidir?', '["Tampere","Turku","Espoo","Helsinki"]'::jsonb, 3, 'cografya'),
('İrlanda''nın başkenti hangisidir?', '["Dublin","Cork","Galway","Belfast"]'::jsonb, 0, 'cografya'),
('Hırvatistan''ın başkenti hangisidir?', '["Split","Zagreb","Dubrovnik","Rijeka"]'::jsonb, 1, 'cografya'),
('Sırbistan''ın başkenti hangisidir?', '["Novi Sad","Niş","Belgrad","Priştine"]'::jsonb, 2, 'cografya'),
('Ukrayna''nın başkenti hangisidir?', '["Harkov","Odessa","Lviv","Kiev"]'::jsonb, 3, 'cografya'),
('Polonya''nın başkenti hangisidir?', '["Varşova","Krakow","Gdansk","Wroclaw"]'::jsonb, 0, 'cografya'),
('Çekya''nın başkenti hangisidir?', '["Brno","Prag","Ostrava","Bratislava"]'::jsonb, 1, 'cografya'),
('Macaristan''ın başkenti hangisidir?', '["Debrecen","Szeged","Budapeşte","Pécs"]'::jsonb, 2, 'cografya'),
('Arnavutluk''un başkenti hangisidir?', '["Draç","İşkodra","Vlora","Tiran"]'::jsonb, 3, 'cografya'),
('Bosna-Hersek''in başkenti hangisidir?', '["Saraybosna","Mostar","Banja Luka","Tuzla"]'::jsonb, 0, 'cografya'),
('Gürcistan''ın başkenti hangisidir?', '["Batum","Tiflis","Kutaisi","Gori"]'::jsonb, 1, 'cografya'),
('Özbekistan''ın başkenti hangisidir?', '["Semerkant","Buhara","Taşkent","Hive"]'::jsonb, 2, 'cografya'),
('Türkmenistan''ın başkenti hangisidir?', '["Merv","Türkmenbaşı","Daşoğuz","Aşkabat"]'::jsonb, 3, 'cografya'),
('Kırgızistan''ın başkenti hangisidir?', '["Bişkek","Oş","Celalabad","Karakol"]'::jsonb, 0, 'cografya'),
('Moğolistan''ın başkenti hangisidir?', '["Darhan","Ulan Batur","Erdenet","Hovd"]'::jsonb, 1, 'cografya'),
('Endonezya''nın başkenti hangisidir?', '["Surabaya","Bandung","Cakarta","Medan"]'::jsonb, 2, 'cografya'),
('Filipinler''in başkenti hangisidir?', '["Cebu","Davao","Quezon","Manila"]'::jsonb, 3, 'cografya'),
('Malezya''nın başkenti hangisidir?', '["Kuala Lumpur","Penang","Johor Bahru","Ipoh"]'::jsonb, 0, 'cografya'),
('Tayland''ın başkenti hangisidir?', '["Chiang Mai","Bangkok","Phuket","Pattaya"]'::jsonb, 1, 'cografya'),
('Suudi Arabistan''ın başkenti hangisidir?', '["Cidde","Mekke","Riyad","Dammam"]'::jsonb, 2, 'cografya'),
('Ürdün''ün başkenti hangisidir?', '["Akabe","İrbid","Zerka","Amman"]'::jsonb, 3, 'cografya'),
('Lübnan''ın başkenti hangisidir?', '["Beyrut","Trablus","Sayda","Sur"]'::jsonb, 0, 'cografya'),
('Etiyopya''nın başkenti hangisidir?', '["Nairobi","Addis Ababa","Kampala","Hartum"]'::jsonb, 1, 'cografya'),
('Kenya''nın başkenti hangisidir?', '["Mombasa","Kisumu","Nairobi","Nakuru"]'::jsonb, 2, 'cografya'),
('Cezayir''in başkenti hangisidir?', '["Oran","Konstantin","Annaba","Cezayir"]'::jsonb, 3, 'cografya'),
('Tunus''un başkenti hangisidir?', '["Tunus","Sfaks","Sus","Bizerte"]'::jsonb, 0, 'cografya'),
('Arjantin''in başkenti hangisidir?', '["Córdoba","Buenos Aires","Rosario","Mendoza"]'::jsonb, 1, 'cografya'),
('Şili''nin başkenti hangisidir?', '["Valparaiso","Concepción","Santiago","Antofagasta"]'::jsonb, 2, 'cografya'),
('Peru''nun başkenti hangisidir?', '["Cusco","Arequipa","Trujillo","Lima"]'::jsonb, 3, 'cografya'),
('Kolombiya''nın başkenti hangisidir?', '["Bogota","Medellin","Cali","Cartagena"]'::jsonb, 0, 'cografya'),
('New York şehri hangi nehrin ağzında kurulmuştur?', '["Mississippi","Hudson","Colorado","Potomac"]'::jsonb, 1, 'cografya'),
('Londra hangi nehir üzerinde kurulmuştur?', '["Ren","Sen","Thames","Tuna"]'::jsonb, 2, 'cografya'),
('Paris hangi nehir üzerinde kurulmuştur?', '["Ren","Loire","Rhone","Sen (Seine)"]'::jsonb, 3, 'cografya'),
('Roma hangi nehir kıyısında kurulmuştur?', '["Tiber","Po","Arno","Adige"]'::jsonb, 0, 'cografya'),
('Viyana hangi nehir kıyısındadır?', '["Ren","Tuna","Elbe","Oder"]'::jsonb, 1, 'cografya'),
('Kahire hangi nehir kıyısındadır?', '["Kongo","Nijer","Nil","Zambezi"]'::jsonb, 2, 'cografya'),
('Bağdat hangi nehir kıyısında kurulmuştur?', '["Fırat","Aras","Karun","Dicle"]'::jsonb, 3, 'cografya'),
('Şangay hangi nehrin ağzında yer alır?', '["Yangtze","Sarı Irmak","Mekong","İnci Nehri"]'::jsonb, 0, 'cografya'),
('Venedik şehrinin en belirgin coğrafi özelliği nedir?', '["Dağ tepesinde olması","Lagün üzerine kurulmuş olması","Çölde olması","Buzul üstünde olması"]'::jsonb, 1, 'cografya'),
('Amsterdam''ın deniz seviyesine göre konumu nasıldır?', '["Dağlık ve yüksek","Volkanik plato üzerinde","Büyük bölümü deniz seviyesinin altında","Çöl kenarında"]'::jsonb, 2, 'cografya'),
('Hollanda''da denizden kazanılan tarım arazilerine ne ad verilir?', '["Delta","Lagün","Fiyort","Polder"]'::jsonb, 3, 'cografya'),
('Singapur coğrafi olarak nasıl bir devlettir?', '["Ada şehir devleti","Karayla çevrili ülke","Yarımada devleti","Federal cumhuriyet"]'::jsonb, 0, 'cografya'),
('Monako hangi denizin kıyısındadır?', '["Atlas Okyanusu","Akdeniz","Karadeniz","Baltık Denizi"]'::jsonb, 1, 'cografya'),
('Nepal hangi iki ülke arasında yer alır?', '["Hindistan ve Pakistan","Çin ve Moğolistan","Çin ve Hindistan","İran ve Afganistan"]'::jsonb, 2, 'cografya'),
('Everest Dağı hangi iki ülkenin sınırındadır?', '["Hindistan ve Nepal","Pakistan ve Çin","Butan ve Hindistan","Nepal ve Çin"]'::jsonb, 3, 'cografya'),
('K2 zirvesi hangi sıradağdadır?', '["Karakurum","Himalaya","Hindukuş","Pamir"]'::jsonb, 0, 'cografya'),
('Aconcagua zirvesi hangi kıtadadır?', '["Kuzey Amerika","Güney Amerika","Afrika","Asya"]'::jsonb, 1, 'cografya'),
('Denali (McKinley) zirvesi hangi ülkededir?', '["Kanada","Meksika","ABD","Rusya"]'::jsonb, 2, 'cografya'),
('Mont Blanc hangi sıradağın en yüksek noktasıdır?', '["Pireneler","Karpatlar","Apeninler","Alpler"]'::jsonb, 3, 'cografya'),
('Elbruz Dağı hangi sıradağdadır?', '["Kafkaslar","Uralar","Altaylar","Zagros"]'::jsonb, 0, 'cografya'),
('Fuji Dağı hangi tür dağdır?', '["Kıvrım","Volkanik","Kırık","Buzul"]'::jsonb, 1, 'cografya'),
('Vezüv Yanardağı hangi şehri yok etmiştir?', '["Roma","Atina","Pompei","Kartaca"]'::jsonb, 2, 'cografya'),
('Etna Yanardağı hangi adadadır?', '["Sardunya","Girit","Korsika","Sicilya"]'::jsonb, 3, 'cografya'),
('Krakatoa Yanardağı hangi ülkededir?', '["Endonezya","Filipinler","Japonya","Şili"]'::jsonb, 0, 'cografya'),
('Yellowstone hangi ülkenin milli parkıdır?', '["Kanada","ABD","Avustralya","Şili"]'::jsonb, 1, 'cografya'),
('Serengeti Milli Parkı hangi ülkededir?', '["Kenya","Güney Afrika","Tanzanya","Namibya"]'::jsonb, 2, 'cografya'),
('Amazon Yağmur Ormanları en çok hangi ülkede yer alır?', '["Peru","Kolombiya","Venezuela","Brezilya"]'::jsonb, 3, 'cografya'),
('Amazon ormanlarının küresel önemi nedir?', '["Oksijen üretimi ve karbon tutumu","Petrol üretimi","Buzul dengesi","Tuz üretimi"]'::jsonb, 0, 'cografya'),
('Ormansızlaşmanın iklime en önemli etkisi nedir?', '["Yağışın artması","Karbondioksitin artması","Sıcaklığın düşmesi","Rüzgârın durması"]'::jsonb, 1, 'cografya'),
('Biyoçeşitliliğin en yüksek olduğu iklim kuşağı hangisidir?', '["Kutup","Çöl","Ekvatoral","Tundra"]'::jsonb, 2, 'cografya'),
('Endemik tür ne demektir?', '["Göçmen tür","Evcil tür","Yok olmuş tür","Yalnız belirli bir bölgede yaşayan tür"]'::jsonb, 3, 'cografya'),
('Türkiye''nin biyoçeşitlilik bakımından zengin olmasının nedeni nedir?', '["Farklı iklim ve yer şekilleri","Yüzölçümünün büyüklüğü","Nüfusunun azlığı","Denize kıyısı olmaması"]'::jsonb, 0, 'cografya'),
('Geri dönüşümün çevresel yararı nedir?', '["Nüfus artışı","Hammadde ve enerji tasarrufu","Toprak kaybı","Su kirliliği"]'::jsonb, 1, 'cografya'),
('Su ayak izi kavramı neyi ifade eder?', '["Yağış miktarını","Nem oranını","Tüketilen toplam su miktarını","Deniz seviyesini"]'::jsonb, 2, 'cografya'),
('Sürdürülebilir kalkınma neyi hedefler?', '["Kısa vadeli kârı","Hızlı sanayileşmeyi","Nüfus artışını","Gelecek kuşakların hakkını korumayı"]'::jsonb, 3, 'cografya'),
('Kentsel ısı adası etkisi neden oluşur?', '["Beton ve asfaltın ısı tutmasından","Ağaç fazlalığından","Yağış artışından","Rüzgâr hızından"]'::jsonb, 0, 'cografya'),
('Hava kirliliğinin kışın artmasının nedeni nedir?', '["Yağışın artması","Isınma amaçlı yakıt kullanımı","Rüzgârın güçlenmesi","Gündüz süresinin uzaması"]'::jsonb, 1, 'cografya'),
('Termik inversiyon hava kirliliğini nasıl etkiler?', '["Kirliliği dağıtır","Yağış oluşturur","Kirli havayı yere yakın hapseder","Rüzgârı hızlandırır"]'::jsonb, 2, 'cografya'),
('Deniz seviyesinin yükselmesinin başlıca nedeni nedir?', '["Yağışın azalması","Volkanik patlamalar","Depremler","Buzulların erimesi ve suyun genleşmesi"]'::jsonb, 3, 'cografya'),
('Küresel ısınmadan en çok etkilenecek yerleşimler hangileridir?', '["Alçak kıyı yerleşmeleri","Dağ köyleri","Plato kentleri","Çöl vahaları"]'::jsonb, 0, 'cografya'),
('Buzul çağlarında deniz seviyesi nasıl olmuştur?', '["Yükselmiştir","Alçalmıştır","Değişmemiştir","İkiye katlanmıştır"]'::jsonb, 1, 'cografya'),
('Akdeniz iklimi Türkiye dışında hangi bölgede daha görülür?', '["Sibirya","Amazon Havzası","Kaliforniya kıyıları","Kuzey Kanada"]'::jsonb, 2, 'cografya'),
('Kalıcı donmuş toprak tabakasına ne ad verilir?', '["Humus","Terra rossa","Podzol","Permafrost"]'::jsonb, 3, 'cografya'),
('Vaha nedir?', '["Çölde su bulunan verimli alan","Buzul gölü","Yüksek plato","Delta ovası"]'::jsonb, 0, 'cografya'),
('Kuzey Afrika''daki Atlas Dağları hangi ülkelerde uzanır?', '["Mısır, Sudan, Libya","Fas, Cezayir, Tunus","Nijerya, Gana, Mali","Kenya, Uganda, Tanzanya"]'::jsonb, 1, 'cografya'),
('Afrika''nın en kalabalık ülkesi hangisidir?', '["Mısır","Etiyopya","Nijerya","Güney Afrika"]'::jsonb, 2, 'cografya'),
('Afrika''yı ikiye bölen hayali çizgi hangisidir?', '["Başlangıç meridyeni","Yengeç Dönencesi","Kutup dairesi","Ekvator"]'::jsonb, 3, 'cografya'),
('Doğu Afrika Rift Vadisi nasıl oluşmuştur?', '["Levhaların birbirinden uzaklaşmasıyla","Buzul aşındırmasıyla","Akarsu birikimiyle","Rüzgâr etkisiyle"]'::jsonb, 0, 'cografya'),
('Sahel bölgesinin en büyük çevre sorunu nedir?', '["Sel","Çölleşme","Buzul erimesi","Deniz yükselmesi"]'::jsonb, 1, 'cografya'),
('Güney Amerika''daki geniş otlaklara ne ad verilir?', '["Step","Savan","Pampa","Tundra"]'::jsonb, 2, 'cografya'),
('Kuzey Amerika''daki geniş otlaklara ne ad verilir?', '["Pampa","Savan","Maki","Preri"]'::jsonb, 3, 'cografya'),
('Rusya''daki geniş otlak kuşağına ne ad verilir?', '["Step","Preri","Pampa","Savan"]'::jsonb, 0, 'cografya'),
('Avustralya''nın iç kesimleri için kullanılan terim nedir?', '["Pampa","Outback","Sahel","Tayga"]'::jsonb, 1, 'cografya'),
('Yeni Zelanda hangi levha sınırında yer alır?', '["Afrika ve Avrupa","Nazca ve Güney Amerika","Pasifik ve Avustralya","Hint ve Avrasya"]'::jsonb, 2, 'cografya'),
('Okyanusya''nın en büyük ülkesi hangisidir?', '["Yeni Zelanda","Papua Yeni Gine","Fiji","Avustralya"]'::jsonb, 3, 'cografya'),
('Kutup gecesinin görüldüğü bölge neresidir?', '["Kutup daireleri içi","Ekvator","Dönenceler arası","Orta kuşak"]'::jsonb, 0, 'cografya'),
('Kuzey ışıkları (aurora) hangi bölgede görülür?', '["Ekvatorda","Kutuplara yakın enlemlerde","Çöllerde","Tropiklerde"]'::jsonb, 1, 'cografya'),
('Antarktika''da ülkelerin bilimsel üs kurmasını düzenleyen antlaşma hangisidir?', '["Kyoto Protokolü","Paris Anlaşması","Antarktika Antlaşması","Montreal Protokolü"]'::jsonb, 2, 'cografya'),
('Montreal Protokolü hangi sorunla ilgilidir?', '["Deniz kirliliği","Gürültü kirliliği","Erozyon","Ozon tabakasının incelmesi"]'::jsonb, 3, 'cografya'),
('Paris İklim Anlaşması''nın temel hedefi nedir?', '["Küresel sıcaklık artışını sınırlamak","Nüfusu azaltmak","Ticareti artırmak","Orman açmak"]'::jsonb, 0, 'cografya'),
('Türkiye''de UNESCO Dünya Mirası listesindeki Hierapolis hangi ildedir?', '["Aydın","Denizli","Muğla","Manisa"]'::jsonb, 1, 'cografya'),
('Bursa''nın UNESCO listesine girmesini sağlayan özellik nedir?', '["Roma tiyatrosu","Bizans surları","Erken Osmanlı kent dokusu","Hitit kalıntıları"]'::jsonb, 2, 'cografya'),
('Türkiye''nin en kuzeydeki kara sınırı hangi ülkeyledir?', '["Bulgaristan","Ermenistan","Yunanistan","Gürcistan"]'::jsonb, 3, 'cografya'),
('Türkiye''nin güneydeki kara komşularından biri hangisidir?', '["Irak","Gürcistan","Bulgaristan","Yunanistan"]'::jsonb, 0, 'cografya'),
('Türkiye''de coğrafi bölge sınırlarını belirleyen temel ölçüt nedir?', '["İl sınırları","İklim ve yer şekilleri","Nüfus sayısı","Ekonomik gelir"]'::jsonb, 1, 'cografya')
on conflict (soru) do nothing;
