-- ============================================================
-- Soru Partisi 15 — 500 soru
--   spor 200 · sanat 200 · sinema 100
--
-- Kalite: tek ve tartışmasız doğru cevap; zamanla değişen bilgi yok
-- (güncel şampiyon/transfer/rekor sorusu YOK); mevcut havuza karşı
-- tekrar taraması yapıldı. Sonunda yalnız bu partinin şıkları karışır.
-- ============================================================

insert into public.questions (soru, secenekler, dogru_cevap, kategori) values

-- ===================== SPOR (200) =====================
('Futbolda bir takım sahada kaç oyuncuyla başlar?', '["11","10","12","9"]'::jsonb, 0, 'spor'),
('Futbolda bir devre kaç dakikadır?', '["40","45","50","30"]'::jsonb, 1, 'spor'),
('Futbolda ofsayt hangi durumda değerlendirilmez?', '["Pasta","Ortada","Taç atışında","Şutta"]'::jsonb, 2, 'spor'),
('Futbolda VAR sisteminin görevi nedir?', '["Bilet satmak","Süre tutmak","Skor yazmak","Video ile hakem kararlarını incelemek"]'::jsonb, 3, 'spor'),
('İlk FIFA Dünya Kupası hangi ülkede düzenlenmiştir?', '["Uruguay","Brezilya","İtalya","Fransa"]'::jsonb, 0, 'spor'),
('UEFA hangi kıtanın futbol federasyonudur?', '["Güney Amerika","Avrupa","Afrika","Asya"]'::jsonb, 1, 'spor'),
('CONMEBOL hangi kıtanın futbol konfederasyonudur?', '["Afrika","Avrupa","Güney Amerika","Asya"]'::jsonb, 2, 'spor'),
('Basketbolda üç sayılık atış çizgi neresinden yapılır?', '["Orta sahadan zorunlu","Serbest atış çizgisinden","Pota altından","Üç sayı çizgisi dışından"]'::jsonb, 3, 'spor'),
('Basketbolda normal saha içi basket kaç sayıdır?', '["2","1","3","4"]'::jsonb, 0, 'spor'),
('Basketbolda bir oyuncu kaç faulle oyun dışı kalır (FIBA)?', '["6","5","4","7"]'::jsonb, 1, 'spor'),
('Basketbolda hücum süresi kaç saniyedir?', '["20","30","24","35"]'::jsonb, 2, 'spor'),
('Basketbolda "ribaund" ne demektir?', '["Faul yapmak","Şut atmak","Pas vermek","Sekmiş topu almak"]'::jsonb, 3, 'spor'),
('Basketbolda "asist" ne demektir?', '["Sayı olan pası vermek","Ribaund almak","Blok yapmak","Faul yapmak"]'::jsonb, 0, 'spor'),
('Voleybolda "libero" hangi görevi üstlenir?', '["Smaç","Savunma uzmanlığı","Blok","Servis atma zorunlu"]'::jsonb, 1, 'spor'),
('Voleybolda "smaç" ne demektir?', '["Pas vermek","Servis atmak","Sert vuruşla topu yere indirmek","Blok yapmak"]'::jsonb, 2, 'spor'),
('Hentbolda maç süresi kaç dakikadır?', '["70","90","40","60"]'::jsonb, 3, 'spor'),
('Tenis maçlarında "deuce" ne anlama gelir?', '["40-40 beraberlik","Oyun bitti","Set bitti","Servis hatası"]'::jsonb, 0, 'spor'),
('Teniste bir set kazanmak için genelde kaç oyun gerekir?', '["4","6","5","8"]'::jsonb, 1, 'spor'),
('Tenis Grand Slam turnuvası sayısı kaçtır?', '["5","3","4","6"]'::jsonb, 2, 'spor'),
('Australian Open hangi ülkede düzenlenir?', '["İngiltere","Yeni Zelanda","ABD","Avustralya"]'::jsonb, 3, 'spor'),
('US Open hangi ülkede düzenlenir?', '["ABD","İngiltere","Fransa","Kanada"]'::jsonb, 0, 'spor'),
('Masa tenisinde bir set kaç sayı üzerinden oynanır?', '["21","11","15","25"]'::jsonb, 1, 'spor'),
('Badmintonda kullanılan topun adı nedir?', '["Golf topu","Tenis topu","Tüylü top (shuttlecock)","Ping pong topu"]'::jsonb, 2, 'spor'),
('Golfte topu deliğe en az vuruşla sokan ne olur?', '["Diskalifiye olur","Kaybeder","Beraberdir","Kazanır"]'::jsonb, 3, 'spor'),
('Golfte "birdie" ne demektir?', '["Par''ın bir altında bitirmek","Par''ın bir üstü","Deliği ıskalamak","İlk vuruş"]'::jsonb, 0, 'spor'),
('Golfte "eagle" ne demektir?', '["Par''ın iki üstü","Par''ın iki altında bitirmek","Delik dışı","Ceza vuruşu"]'::jsonb, 1, 'spor'),
('Golfte tek vuruşta deliğe atmaya ne denir?', '["Bogey","Birdie","Hole in one","Par"]'::jsonb, 2, 'spor'),
('Yüzmede "kelebek" hangi kategoriye girer?', '["Ekipman","Mesafe","Zemin","Stil (kulaç)"]'::jsonb, 3, 'spor'),
('Atletizmde 100 metre hangi kategoriye girer?', '["Sürat koşusu","Dayanıklılık","Atma","Atlama"]'::jsonb, 0, 'spor'),
('Sırıkla yüksek atlamada kullanılan araç nedir?', '["Halter","Sırık","Disk","Cirit"]'::jsonb, 1, 'spor'),
('Atletizmde "gülle atma" hangi grupta yer alır?', '["Atlama","Koşu","Atma","Yürüyüş"]'::jsonb, 2, 'spor'),
('Cirit atma hangi tür bir branştır?', '["Yüzme","Koşu","Atlama","Atma"]'::jsonb, 3, 'spor'),
('Üç adım atlama hangi kategoridedir?', '["Atlama","Atma","Koşu","Halter"]'::jsonb, 0, 'spor'),
('Modern Olimpiyat Oyunları ilk kez hangi yıl düzenlenmiştir?', '["1900","1896","1912","1924"]'::jsonb, 1, 'spor'),
('İlk modern olimpiyatlar hangi şehirde yapılmıştır?', '["Londra","Paris","Atina","Roma"]'::jsonb, 2, 'spor'),
('Olimpiyat halkalarının sayısı kaçtır?', '["3","4","6","5"]'::jsonb, 3, 'spor'),
('Yaz Olimpiyatları kaç yılda bir yapılır?', '["4","2","3","5"]'::jsonb, 0, 'spor'),
('Paralimpik Oyunlar kimler için düzenlenir?', '["Gençler","Engelli sporcular","Yaşlılar","Amatörler"]'::jsonb, 1, 'spor'),
('Olimpiyat sloganı hangi kavramları içerir?', '["Daha uzun","Daha ucuz","Daha hızlı, daha yüksek, daha güçlü","Daha kolay"]'::jsonb, 2, 'spor'),
('Kış Olimpiyatlarında yer almayan spor hangisidir?', '["Hokey","Kayak","Curling","Yüzme"]'::jsonb, 3, 'spor'),
('Curling hangi zeminde oynanır?', '["Buz","Çim","Kum","Parke"]'::jsonb, 0, 'spor'),
('Kayakta "slalom" ne anlama gelir?', '["Düz inmek","Kapılar arasından geçerek inmek","Atlamak","Buzda kaymak"]'::jsonb, 1, 'spor'),
('Snowboard hangi mevsim sporudur?', '["İlkbahar","Yaz","Kış","Sonbahar"]'::jsonb, 2, 'spor'),
('Boksta bir raunt kaç dakikadır (profesyonel)?', '["1","2","5","3"]'::jsonb, 3, 'spor'),
('Boksta "nakavt" ne demektir?', '["Rakibin sayılamaması","Puan üstünlüğü","Beraberlik","Diskalifiye"]'::jsonb, 0, 'spor'),
('Güreşte "serbest" ve "grekoromen" nedir?', '["İki sıklet","İki güreş stili","İki lig","İki kural dışı"]'::jsonb, 1, 'spor'),
('Grekoromen güreşte hangi bölgeye müdahale yasaktır?', '["Baş","Kollar","Bel altı","Omuz"]'::jsonb, 2, 'spor'),
('Yağlı güreşin geleneksel merkezi Türkiye''de neresidir?', '["Truva","Kapadokya","Efes","Kırkpınar"]'::jsonb, 3, 'spor'),
('Karate hangi ülkeyle özdeşleşmiştir?', '["Japonya","Kore","Çin","Vietnam"]'::jsonb, 0, 'spor'),
('Taekwondo hangi ülkenin geleneksel sporudur?', '["Japonya","Kore","Çin","Moğolistan"]'::jsonb, 1, 'spor'),
('Judo ve karatede kuşak rengi neyi gösterir?', '["Yaş","Takım","Seviye","Sıklet"]'::jsonb, 2, 'spor'),
('Bisiklette Fransa''da düzenlenen ünlü tur yarışı hangisidir?', '["Paris-Roubaix","Giro d''Italia","Vuelta","Tour de France"]'::jsonb, 3, 'spor'),
('Giro d''Italia hangi ülkede düzenlenir?', '["İtalya","İspanya","Fransa","Belçika"]'::jsonb, 0, 'spor'),
('Formula 1''de yarış başlangıcındaki sıralamayı belirleyen tur hangisidir?', '["Isınma turu","Sıralama turları","Zafer turu","Antrenman"]'::jsonb, 1, 'spor'),
('Formula 1''de "pit stop" ne için yapılır?', '["Yemek","Dinlenmek","Lastik değişimi ve bakım","Seyirci selamlamak"]'::jsonb, 2, 'spor'),
('Formula 1''de siyah-beyaz damalı bayrak neyi gösterir?', '["Cezayı","Tehlikeyi","Kırmızı bayrağı","Yarışın bitişini"]'::jsonb, 3, 'spor'),
('Ralli yarışlarında sürücünün yanındaki kişiye ne denir?', '["Co-pilot (seyirci notçu)","Teknisyen","Hakem","Antrenör"]'::jsonb, 0, 'spor'),
('MotoGP hangi araçlarla yapılır?', '["Otomobil","Motosiklet","Kamyon","Bisiklet"]'::jsonb, 1, 'spor'),
('Amerikan futbolunda "touchdown" kaç puandır?', '["7","3","6","2"]'::jsonb, 2, 'spor'),
('Beyzbolda bir takım savunmada kaç oyuncuyla sahada bulunur?', '["11","10","8","9"]'::jsonb, 3, 'spor'),
('Beyzbolda "home run" ne demektir?', '["Topu sahadan çıkararak tur atmak","Vuruşu kaçırmak","Kale değişimi","Faul"]'::jsonb, 0, 'spor'),
('Kriket hangi ülkede çok popülerdir?', '["Brezilya","Hindistan","Rusya","Norveç"]'::jsonb, 1, 'spor'),
('Su topunda oyuncular hangi ortamda yarışır?', '["Buzda","Kumda","Havuzda","Çimde"]'::jsonb, 2, 'spor'),
('Rafting hangi ortamda yapılır?', '["Havuz","Göl","Deniz dibi","Akarsu"]'::jsonb, 3, 'spor'),
('Dalgıçlıkta kullanılan tüpün içinde ne bulunur?', '["Sıkıştırılmış hava","Su","Yağ","Helyum yalnızca"]'::jsonb, 0, 'spor'),
('Sörf sporunda kullanılan araç nedir?', '["Kayak","Sörf tahtası","Kızak","Paten"]'::jsonb, 1, 'spor'),
('Artistik patinajda sporcular hangi zeminde yarışır?', '["Çim","Parke","Buz","Kum"]'::jsonb, 2, 'spor'),
('Jimnastikte "denge aleti" hangi branşta kullanılır?', '["Okçuluk","Halter","Yüzme","Artistik jimnastik"]'::jsonb, 3, 'spor'),
('Trambolin hangi spor dalında kullanılır?', '["Jimnastik","Güreş","Boks","Okçuluk"]'::jsonb, 0, 'spor'),
('Satrançta en değerli taş hangisidir?', '["Vezir","Şah","Kale","At"]'::jsonb, 1, 'spor'),
('Satrançta "rok" hamlesi hangi taşları içerir?', '["At ve piyon","Vezir ve fil","Şah ve kale","İki kale"]'::jsonb, 2, 'spor'),
('Satrançta oyunun berabere bitmesine ne denir?', '["Rok","Mat","Şah","Pat veya remi"]'::jsonb, 3, 'spor'),
('Sporcuların performans artırıcı yasaklı madde kullanmasına ne denir?', '["Doping","Antrenman","Taktik","Rehabilitasyon"]'::jsonb, 0, 'spor'),
('WADA''nın görevi nedir?', '["Bilet satışı","Dopingle mücadele","Saha yapımı","Yayın hakkı"]'::jsonb, 1, 'spor'),
('Sporda "fair play" ne anlama gelir?', '["Sert oyun","Hızlı oyun","Dürüst ve centilmence oyun","Savunma taktiği"]'::jsonb, 2, 'spor'),
('Bir sporcunun ısınma yapmasının amacı nedir?', '["Kas kaybı","Kilo vermek","Uykuyu artırmak","Sakatlanma riskini azaltmak"]'::jsonb, 3, 'spor'),
('Aerobik egzersizin temel özelliği nedir?', '["Uzun süreli ve oksijenli","Kısa ve patlayıcı","Hareketsiz","Ağırlık odaklı"]'::jsonb, 0, 'spor'),
('Anaerobik egzersize örnek hangisidir?', '["Uzun yürüyüş","Sprint","Yavaş koşu","Yoga"]'::jsonb, 1, 'spor'),
('Kas kütlesi artışını en çok destekleyen makro besin hangisidir?', '["Yağ","Şeker","Protein","Lif"]'::jsonb, 2, 'spor'),
('Sporcularda sıvı kaybını karşılamak için önerilen içecek nedir?', '["Alkol","Gazlı içecek","Kahve","Su"]'::jsonb, 3, 'spor'),
('Kramp genellikle neyle ilişkilidir?', '["Sıvı ve mineral kaybı","Fazla uyku","Soğuk hava zorunlu","Yüksek irtifa"]'::jsonb, 0, 'spor'),
('Sporcularda dinlenme gününün amacı nedir?', '["Performans düşürmek","Toparlanma","Kas kaybı","Kilo almak"]'::jsonb, 1, 'spor'),
('Maraton koşucularının antrenmanında öne çıkan özellik nedir?', '["Esneklik yalnızca","Patlayıcı güç","Dayanıklılık","Denge yalnızca"]'::jsonb, 2, 'spor'),
('Sporda "kondisyon" neyi ifade eder?', '["Ekipman","Teknik bilgi","Taktik plan","Genel fiziksel uygunluk"]'::jsonb, 3, 'spor'),
('Esneme egzersizlerinin faydası nedir?', '["Hareket açıklığını artırmak","Kas yırtmak","Kilo almak","Nabzı durdurmak"]'::jsonb, 0, 'spor'),
('Futbolda "çalım" ne demektir?', '["Gol atmak","Rakibi geçmek için yapılan hareket","Kaleci çıkışı","Taç atışı"]'::jsonb, 1, 'spor'),
('Futbolda "duran top" ne anlama gelir?', '["Ofsayt","Oyun içi pas","Serbest vuruş, korner gibi durumlar","Uzatma"]'::jsonb, 2, 'spor'),
('Futbolda "libero" hangi bölgede oynar?', '["Kale","Forvet","Kanat","Savunma"]'::jsonb, 3, 'spor'),
('Futbolda "kaleci eldiveni" hangi amaçla kullanılır?', '["Kavrama ve koruma","Süs","Hız","Isınma"]'::jsonb, 0, 'spor'),
('Futbol sahasında orta yuvarlağın işlevi nedir?', '["Penaltı atmak","Başlama vuruşunu düzenlemek","Korner atmak","Taç kullanmak"]'::jsonb, 1, 'spor'),
('Futbolda oyuncu değişikliği kim tarafından onaylanır?', '["Seyirci","Kaptan","Hakem","Kaleci"]'::jsonb, 2, 'spor'),
('Futbolda dördüncü hakemin görevlerinden biri nedir?', '["Penaltı vermek","Gol vermek","Kart göstermek","Uzatma süresini göstermek"]'::jsonb, 3, 'spor'),
('Futbolda yardımcı hakem hangi kararda etkilidir?', '["Ofsayt","Kart rengi","Skor","Süre"]'::jsonb, 0, 'spor'),
('Futbolda "clean sheet" ne demektir?', '["Gol atmak","Gol yememek","Beraberlik","Kart görmemek"]'::jsonb, 1, 'spor'),
('Futbolda takımın en çok gol atan oyuncusuna genelde ne denir?', '["Kaleci","Stoper","Golcü","Libero"]'::jsonb, 2, 'spor'),
('Basketbolda "double-double" ne demektir?', '["İki devre","İki maç kazanmak","İki faul","İki istatistikte çift haneye ulaşmak"]'::jsonb, 3, 'spor'),
('Basketbolda "blok" ne anlama gelir?', '["Şutu engellemek","Pas atmak","Sayı yapmak","Faul yapmak"]'::jsonb, 0, 'spor'),
('Basketbolda "turnover" ne demektir?', '["Sayı","Top kaybı","Ribaund","Blok"]'::jsonb, 1, 'spor'),
('Basketbolda "pivot" oyuncu genelde nerede oynar?', '["Kale","Dış saha","Pota altı","Kanat çizgisi"]'::jsonb, 2, 'spor'),
('Voleybolda "servis" ne zaman kullanılır?', '["Oyuncu değişiminde","Set sonunda","Molada","Sayı başlangıcında"]'::jsonb, 3, 'spor'),
('Voleybolda "blok" hangi amaçla yapılır?', '["Rakip smacını engellemek","Servis atmak","Pas vermek","Sayı saymak"]'::jsonb, 0, 'spor'),
('Voleybolda file yüksekliği erkeklerde kaç metredir?', '["2,24","2,43","2,00","2,60"]'::jsonb, 1, 'spor'),
('Voleybolda "pasör" oyuncunun görevi nedir?', '["Servis karşılamak yalnızca","Blok yapmak","Hücumu kurmak","Sayı yazmak"]'::jsonb, 2, 'spor'),
('Voleybolda rotasyon ne anlama gelir?', '["Set arası","Oyuncu değişimi","Mola","Oyuncuların saat yönünde yer değiştirmesi"]'::jsonb, 3, 'spor'),
('Teniste "break" ne demektir?', '["Rakip servisinde oyun kazanmak","Servis atmak","Sette beraberlik","Mola"]'::jsonb, 0, 'spor'),
('Teniste "tie-break" ne zaman oynanır?', '["Maç başında","Sette 6-6 olduğunda","İlk oyunda","Molada"]'::jsonb, 1, 'spor'),
('Teniste "çift hata" ne demektir?', '["İki set kaybı","İki faul","İki servisin de hatalı olması","İki puan"]'::jsonb, 2, 'spor'),
('Teniste raketin vurma yüzeyine ne denir?', '["Taban","Sap","Kafa dışı","Kordaj yüzeyi"]'::jsonb, 3, 'spor'),
('Tenis kortunda tek erkekler maçında kaç oyuncu vardır?', '["2","4","1","3"]'::jsonb, 0, 'spor'),
('Sporda "amatör" ne anlama gelir?', '["Profesyonel olmak","Kazanç amacı gütmeden yapmak","Antrenör olmak","Hakem olmak"]'::jsonb, 1, 'spor'),
('Bir spor kulübünün altyapısı ne amaçla kurulur?', '["Saha kiralamak","Bilet satmak","Genç sporcu yetiştirmek","Yayın yapmak"]'::jsonb, 2, 'spor'),
('Sporda "transfer" ne demektir?', '["Sakatlık","Antrenman planı","Maç taktiği","Sporcunun kulüp değiştirmesi"]'::jsonb, 3, 'spor'),
('Sporda "derbi" ne anlama gelir?', '["Önemli rakipler arası maç","Hazırlık maçı","Kupa finali zorunlu","Antrenman"]'::jsonb, 0, 'spor'),
('Bir ligde puan sıralamasında eşitlik durumunda sık kullanılan ölçüt nedir?', '["Şehir nüfusu","Averaj","Kulüp yaşı","Seyirci sayısı"]'::jsonb, 1, 'spor'),
('Averaj neyi ifade eder?', '["Kart sayısı","Maç sayısı","Atılan ve yenen gol farkı","Puan"]'::jsonb, 2, 'spor'),
('Play-off sistemi ne için kullanılır?', '["Bilet satmak","Lig başlatmak","Transfer yapmak","Şampiyonu eleme usulü belirlemek"]'::jsonb, 3, 'spor'),
('Eleme usulü turnuvada kaybeden takım ne olur?', '["Elenir","Devam eder","Puan alır","Final oynar"]'::jsonb, 0, 'spor'),
('Lig usulü turnuvada takımlar nasıl karşılaşır?', '["Tek maç","Herkes birbiriyle oynar","Kura ile bir kez","Yalnız final"]'::jsonb, 1, 'spor'),
('Sporda "rekor" ne demektir?', '["En kötü derece","Ortalama derece","En iyi derece","Katılım sayısı"]'::jsonb, 2, 'spor'),
('Atletizmde bayrak yarışında sporcular neyi devreder?', '["Cirit","Top","Disk","Bayrak (baton)"]'::jsonb, 3, 'spor'),
('4x100 bayrak yarışında toplam mesafe kaç metredir?', '["400","200","800","1000"]'::jsonb, 0, 'spor'),
('Engelli koşularda sporcular neyin üzerinden atlar?', '["Çukur","Engel","İp","Duvar"]'::jsonb, 1, 'spor'),
('3000 metre engelli koşuda ek olarak hangi engel bulunur?', '["Duvar","Kum havuzu","Su birikintisi","Tünel"]'::jsonb, 2, 'spor'),
('Yürüyüş yarışlarında temel kural nedir?', '["Durmak","Koşmak","Zıplamak","Bir ayağın sürekli yerle teması"]'::jsonb, 3, 'spor'),
('Triatlon hangi üç branşı içerir?', '["Yüzme, bisiklet, koşu","Koşu, atış, kürek","Yüzme, güreş, koşu","Bisiklet, boks, yüzme"]'::jsonb, 0, 'spor'),
('Modern pentatlonda kaç branş vardır?', '["3","5","7","10"]'::jsonb, 1, 'spor'),
('Biatlon hangi iki branşı birleştirir?', '["Bisiklet ve atış","Yüzme ve koşu","Kayak ve atıcılık","Kayak ve kürek"]'::jsonb, 2, 'spor'),
('Sporda "antrenör" ne yapar?', '["Yayın yapar","Bilet satar","Saha yapar","Sporcuyu hazırlar ve yönlendirir"]'::jsonb, 3, 'spor'),
('Sporda "kaptan" kimdir?', '["Takımı sahada temsil eden oyuncu","Kulüp başkanı","Antrenör","Hakem"]'::jsonb, 0, 'spor'),
('Sporda "masör"ün görevi nedir?', '["Taktik vermek","Kas bakımı ve masaj","Skor tutmak","Kart göstermek"]'::jsonb, 1, 'spor'),
('Sakatlıklarda ilk müdahalede sık kullanılan yöntem nedir?', '["Ağır koşu","Sıcak duş","Soğuk uygulama","Ağırlık kaldırma"]'::jsonb, 2, 'spor'),
('Sporcularda "rehabilitasyon" ne demektir?', '["Ceza","Antrenman artışı","Transfer","Sakatlık sonrası toparlanma süreci"]'::jsonb, 3, 'spor'),
('Futbolda ısınma turlarının ardından yapılan çalışma nedir?', '["Esneme ve top çalışması","Maç","Ceza koşusu","Toplantı"]'::jsonb, 0, 'spor'),
('Basketbolda "hızlı hücum" ne demektir?', '["Yavaş oyun","Savunmadan hızla hücuma geçmek","Faul yapmak","Zaman harcamak"]'::jsonb, 1, 'spor'),
('Futbolda "presleme" ne anlama gelir?', '["Top saklamak","Geri çekilmek","Rakibe yakın baskı yapmak","Uzun pas"]'::jsonb, 2, 'spor'),
('Futbolda "kontratak" ne demektir?', '["Taç atışı","Geri pas","Oyunu yavaşlatma","Savunmadan hızlı hücum"]'::jsonb, 3, 'spor'),
('Futbolda 4-4-2 ne ifade eder?', '["Diziliş","Skor","Süre","Kart sayısı"]'::jsonb, 0, 'spor'),
('Bir takımın "forma"sı ne işe yarar?', '["Hız artırmak","Takımı ayırt etmek","Puan getirmek","Isınmak"]'::jsonb, 1, 'spor'),
('Futbolda "kramponsuz" oynanan zemin hangisidir?', '["Toprak saha","Çim saha","Salon parkesi","Sentetik çim"]'::jsonb, 2, 'spor'),
('Futsal hangi ortamda oynanır?', '["Buz","Açık çim","Kum","Kapalı salon"]'::jsonb, 3, 'spor'),
('Plaj voleybolunda takım kaç oyuncudan oluşur?', '["2","6","4","3"]'::jsonb, 0, 'spor'),
('Squash hangi ortamda oynanır?', '["Açık çim","Duvarlı kapalı kort","Kum","Buz"]'::jsonb, 1, 'spor'),
('Dartta tahtanın merkezine ne denir?', '["Double","Triple","Bullseye","Miss"]'::jsonb, 2, 'spor'),
('Atlı sporlardan "polo" nasıl oynanır?', '["Bisikletle","Yürüyerek","Yüzerek","At üstünde topa vurarak"]'::jsonb, 3, 'spor'),
('Dağcılıkta zirveye ulaşma çabasına ne denir?', '["Tırmanış","Dalış","Yüzüş","Kayak"]'::jsonb, 0, 'spor'),
('Yamaç paraşütünde kalkış için ne gerekir?', '["Motor","Uygun rüzgâr ve eğim","Havuz","Pist"]'::jsonb, 1, 'spor'),
('Paten sporunda kullanılan ayakkabıda ne bulunur?', '["Yüzgeç","Kramp","Tekerlek veya bıçak","Zil"]'::jsonb, 2, 'spor'),
('Kaykay sporunun İngilizce adı nedir?', '["Longbow","Snowboard","Surfboard","Skateboard"]'::jsonb, 3, 'spor'),
('Tırmanış duvarında güvenlik için kullanılan ekipman nedir?', '["Emniyet ipi ve kemer","Kask yalnızca","Eldiven yalnızca","Gözlük"]'::jsonb, 0, 'spor'),
('E-spor ne anlama gelir?', '["Elektrikli araç yarışı","Elektronik oyun müsabakaları","Enerji sporu","Engelli sporu"]'::jsonb, 1, 'spor'),
('Sporda seyircinin takımını desteklemesine ne denir?', '["Ofsayt","Faul","Tezahürat","Rotasyon"]'::jsonb, 2, 'spor'),
('Bir maçın seyircisiz oynanmasına ne denir?', '["Rövanş","Derbi","Play-off","Kapalı gişe cezası değil, seyircisiz maç"]'::jsonb, 3, 'spor'),
('Sporda "rövanş" ne demektir?', '["İkinci karşılaşma","İlk maç","Antrenman","Kupa"]'::jsonb, 0, 'spor'),
('Turnuvada "kura çekimi" ne için yapılır?', '["Skoru belirlemek","Eşleşmeleri belirlemek","Kart vermek","Bilet satmak"]'::jsonb, 1, 'spor'),
('Sporda "grup aşaması" ne anlama gelir?', '["Eleme turu tek maç","Final","Takımların gruplarda karşılaşması","Antrenman"]'::jsonb, 2, 'spor'),
('Bir sporcunun "sıklet"i neyi ifade eder?', '["Deneyim","Boy","Yaş","Kilo kategorisi"]'::jsonb, 3, 'spor'),
('Boksta sıkletlerin amacı nedir?', '["Adil eşleşme sağlamak","Bilet fiyatı","Süre belirleme","Kart sayısı"]'::jsonb, 0, 'spor'),
('Sporcuların lisansı ne işe yarar?', '["İndirim","Resmî müsabakada yarışma hakkı","Ulaşım","Konaklama"]'::jsonb, 1, 'spor'),
('Bir spor federasyonunun görevi nedir?', '["Forma satmak","Bilet basmak","Branşı düzenlemek ve yönetmek","Stadyum işletmek"]'::jsonb, 2, 'spor'),
('Olimpiyat meşalesinin yakılması neyi simgeler?', '["Molayı","Bitişi","Ödül törenini","Oyunların başlangıcını"]'::jsonb, 3, 'spor'),
('Olimpiyatlarda birinciye verilen madalya hangisidir?', '["Altın","Gümüş","Bronz","Demir"]'::jsonb, 0, 'spor'),
('Olimpiyatlarda üçüncüye verilen madalya hangisidir?', '["Altın","Bronz","Gümüş","Platin"]'::jsonb, 1, 'spor'),

-- ===================== SANAT (200) =====================
('Resimde üç ana renk hangileridir?', '["Siyah, beyaz, gri","Yeşil, mor, turuncu","Kırmızı, sarı, mavi","Pembe, lacivert, bej"]'::jsonb, 2, 'sanat'),
('Kırmızı ile sarı karıştırılırsa hangi renk elde edilir?', '["Kahverengi","Yeşil","Mor","Turuncu"]'::jsonb, 3, 'sanat'),
('Kırmızı ile mavi karıştırılırsa hangi renk oluşur?', '["Mor","Yeşil","Turuncu","Sarı"]'::jsonb, 0, 'sanat'),
('Sıcak renklerden biri hangisidir?', '["Mavi","Kırmızı","Yeşil","Mor"]'::jsonb, 1, 'sanat'),
('Soğuk renklerden biri hangisidir?', '["Turuncu","Kırmızı","Mavi","Sarı"]'::jsonb, 2, 'sanat'),
('Resimde "ton" ne anlama gelir?', '["Fırça sayısı","Çerçeve","Tuval boyutu","Rengin açıklık-koyuluğu"]'::jsonb, 3, 'sanat'),
('Resimde "kompozisyon" ne demektir?', '["Öğelerin düzenlenişi","Boya markası","Tuval türü","Sergi yeri"]'::jsonb, 0, 'sanat'),
('Perspektif neyi sağlar?', '["Renk parlaklığı","Derinlik duygusu","Doku","Ses"]'::jsonb, 1, 'sanat'),
('Tek kaçış noktalı perspektifte çizgiler nerede birleşir?', '["Hiçbir yerde","İki noktada","Ufuk çizgisinde bir noktada","Köşede"]'::jsonb, 2, 'sanat'),
('Resimde "ışık-gölge" çalışmasına ne denir?', '["Kolaj","Perspektif","Doku","Valör"]'::jsonb, 3, 'sanat'),
('Sfumato tekniği neyi ifade eder?', '["Yumuşak geçişli sisli etki","Sert kontur","Nokta tekniği","Kalın boya"]'::jsonb, 0, 'sanat'),
('Chiaroscuro terimi neyi anlatır?', '["Renk karışımı","Güçlü ışık-gölge karşıtlığı","Perspektif","Doku"]'::jsonb, 1, 'sanat'),
('Fresko tekniği hangi yüzeye uygulanır?', '["Kâğıt","Tuval","Islak sıva","Cam"]'::jsonb, 2, 'sanat'),
('Suluboya tekniğinde bağlayıcı olarak ne kullanılır?', '["Balmumu","Yağ","Reçine","Su ve arap zamkı"]'::jsonb, 3, 'sanat'),
('Yağlıboyada bağlayıcı nedir?', '["Bitkisel yağ","Su","Süt","Bal"]'::jsonb, 0, 'sanat'),
('Akrilik boyanın avantajı nedir?', '["Hiç kurumaması","Hızlı kuruması","Kokusuz olmaması","Suda çözünmemesi"]'::jsonb, 1, 'sanat'),
('Guaj boya hangi boya ailesindendir?', '["Reçine","Yağ bazlı","Su bazlı","Mum"]'::jsonb, 2, 'sanat'),
('Pastel boya hangi biçimde kullanılır?', '["Toz macun","Sıvı","Sprey","Kuru çubuk halinde"]'::jsonb, 3, 'sanat'),
('Gravür nedir?', '["Baskı resim tekniği","Heykel","Mozaik","Vitray"]'::jsonb, 0, 'sanat'),
('Litografi hangi malzemeye dayanır?', '["Ahşap","Taş baskı","Metal döküm","Cam"]'::jsonb, 1, 'sanat'),
('Serigrafi hangi teknikle baskı yapar?', '["Ahşap oyma","Taş baskı","Elek/ipek baskı","Metal kazıma"]'::jsonb, 2, 'sanat'),
('Kolaj tekniğinde ne yapılır?', '["Kil pişirilir","Yalnız boya kullanılır","Taş yontulur","Farklı malzemeler yapıştırılır"]'::jsonb, 3, 'sanat'),
('Vitray hangi malzemeyle yapılır?', '["Renkli cam","Ahşap","Kil","Metal levha"]'::jsonb, 0, 'sanat'),
('Heykelde "yontma" ne demektir?', '["Malzeme eklemek","Malzemeden parça çıkarmak","Boyamak","Pişirmek"]'::jsonb, 1, 'sanat'),
('Heykelde "modelleme" hangi malzemeyle yapılır?', '["Granit","Mermer","Kil","Çelik levha"]'::jsonb, 2, 'sanat'),
('Bronz heykel üretiminde kullanılan yöntem hangisidir?', '["Örgü","Yontma","Kaynak yalnızca","Döküm"]'::jsonb, 3, 'sanat'),
('Kabartma (rölyef) nedir?', '["Yüzeyden hafif yükselen figür","Serbest heykel","Resim","Baskı"]'::jsonb, 0, 'sanat'),
('Seramik sanatında çamur hangi işlemle sertleşir?', '["Dondurma","Pişirme","Kurutma yalnızca","Boyama"]'::jsonb, 1, 'sanat'),
('Çini sanatı Türkiye''de hangi şehirle özdeşleşmiştir?', '["Erzurum","Trabzon","İznik","Sinop"]'::jsonb, 2, 'sanat'),
('Tezhip sanatı ne yapar?', '["Cam üfler","Heykel yontar","Halı dokur","El yazmalarını altın ve boyayla süsler"]'::jsonb, 3, 'sanat'),
('Minyatür sanatının özelliği nedir?', '["Perspektifsiz ayrıntılı küçük resim","Devasa duvar resmi","Soyut boyama","Fotoğraf"]'::jsonb, 0, 'sanat'),
('Kat''ı sanatı neyi ifade eder?', '["Cam boyama","Kâğıt oyma","Taş yontma","Halı dokuma"]'::jsonb, 1, 'sanat'),
('Kalemişi hangi yüzeye uygulanır?', '["Cam","Kâğıt","Duvar ve tavan bezemesi","Deri"]'::jsonb, 2, 'sanat'),
('Rönesans resminde öne çıkan yenilik nedir?', '["Fotoğraf","Soyutlama","Kolaj","Perspektif kullanımı"]'::jsonb, 3, 'sanat'),
('Leonardo da Vinci''nin ünlü duvar resmi hangisidir?', '["Son Akşam Yemeği","Davut","Pieta","Yıldızlı Gece"]'::jsonb, 0, 'sanat'),
('Michelangelo''nun Sistine Şapeli''ndeki eseri nerededir?', '["Zeminde","Tavanda","Kapıda","Bahçede"]'::jsonb, 1, 'sanat'),
('Rafael hangi dönemin sanatçısıdır?', '["Rokoko","Barok","Rönesans","Empresyonizm"]'::jsonb, 2, 'sanat'),
('Barok sanatın belirgin özelliği nedir?', '["Nokta tekniği","Sadelik","Geometrik soyutlama","Hareket ve görkem"]'::jsonb, 3, 'sanat'),
('Caravaggio hangi teknikle ünlüdür?', '["Sert ışık-gölge","Pointilizm","Kübizm","Kolaj"]'::jsonb, 0, 'sanat'),
('Rembrandt hangi ülkenin ressamıdır?', '["İtalya","Hollanda","İspanya","Fransa"]'::jsonb, 1, 'sanat'),
('Vermeer''in resimlerinde öne çıkan unsur nedir?', '["Soyut lekeler","Savaş sahneleri","İç mekân ve ışık","Kolaj"]'::jsonb, 2, 'sanat'),
('Rokoko üslubunun özelliği nedir?', '["Endüstriyel","Ağır ve karanlık","Geometrik","Zarif ve süslü"]'::jsonb, 3, 'sanat'),
('Neoklasisizm neyden esinlenmiştir?', '["Antik Yunan ve Roma","Orta Çağ","Uzak Doğu","Afrika"]'::jsonb, 0, 'sanat'),
('Romantizm resminde öne çıkan tema nedir?', '["Geometrik düzen","Duygu ve doğanın gücü","Endüstri","Reklam"]'::jsonb, 1, 'sanat'),
('Goya hangi ülkenin ressamıdır?', '["Fransa","İtalya","İspanya","Almanya"]'::jsonb, 2, 'sanat'),
('Empresyonizmin temel ilgisi nedir?', '["Geometri","Kesin çizgi","Dinî konu","Işığın anlık etkisi"]'::jsonb, 3, 'sanat'),
('Claude Monet hangi akımın öncüsüdür?', '["Empresyonizm","Kübizm","Sürrealizm","Barok"]'::jsonb, 0, 'sanat'),
('"İzlenim: Gün Doğumu" tablosu hangi akıma adını vermiştir?', '["Ekspresyonizm","Empresyonizm","Fovizm","Dadaizm"]'::jsonb, 1, 'sanat'),
('Edgar Degas resimlerinde sıkça hangi konuyu işlemiştir?', '["Deniz fenerleri","Savaş","Bale ve dansçılar","Uzay"]'::jsonb, 2, 'sanat'),
('Renoir hangi akımla anılır?', '["Pop art","Kübizm","Minimalizm","Empresyonizm"]'::jsonb, 3, 'sanat'),
('Post-empresyonizm sanatçılarından biri kimdir?', '["Paul Cezanne","Jacques-Louis David","Rubens","Botticelli"]'::jsonb, 0, 'sanat'),
('Vincent van Gogh''un ünlü tablosu hangisidir?', '["Guernica","Yıldızlı Gece","Mona Lisa","Çığlık"]'::jsonb, 1, 'sanat'),
('Van Gogh''un fırça kullanımının özelliği nedir?', '["Sprey","İnce ve düz","Kalın ve devinimli darbeler","Nokta"]'::jsonb, 2, 'sanat'),
('Paul Gauguin resimlerinde hangi bölgeden esinlenmiştir?', '["Kanada","Sibirya","Kutuplar","Polinezya"]'::jsonb, 3, 'sanat'),
('Pointilizm tekniğinde resim nasıl oluşur?', '["Küçük renk noktalarıyla","Geniş lekelerle","Çizgilerle","Kolajla"]'::jsonb, 0, 'sanat'),
('Georges Seurat hangi teknikle anılır?', '["Kübizm","Pointilizm","Kolaj","Fresk"]'::jsonb, 1, 'sanat'),
('Fovizmin belirgin özelliği nedir?', '["Fotoğrafik gerçeklik","Gri tonlar","Çarpıcı ve serbest renkler","Geometrik düzen"]'::jsonb, 2, 'sanat'),
('Henri Matisse hangi akımla anılır?', '["Neoklasisizm","Barok","Rokoko","Fovizm"]'::jsonb, 3, 'sanat'),
('Kübizmin kurucularından biri kimdir?', '["Pablo Picasso","Claude Monet","Salvador Dali","Andy Warhol"]'::jsonb, 0, 'sanat'),
('Kübizmde nesneler nasıl gösterilir?', '["Tek bakış açısıyla","Çok yönlü geometrik parçalarla","Fotoğraf gibi","Soyut leke"]'::jsonb, 1, 'sanat'),
('Picasso''nun savaş karşıtı ünlü eseri hangisidir?', '["Yıldızlı Gece","Avignonlu Kızlar''ın devamı değil","Guernica","Çığlık"]'::jsonb, 2, 'sanat'),
('Georges Braque hangi akımın kurucularındandır?', '["Pop art","Empresyonizm","Sürrealizm","Kübizm"]'::jsonb, 3, 'sanat'),
('Gustav Klimt eserlerinde hangi malzemeyi sıkça kullanmıştır?', '["Altın varak","Kum","Cam kırığı","Metal levha"]'::jsonb, 0, 'sanat'),
('Fütürizm neyi yüceltmiştir?', '["Doğa","Hız ve makine","Geçmiş","Dinginlik"]'::jsonb, 1, 'sanat'),
('Dadaizm hangi tutumla ortaya çıkmıştır?', '["Dinî sanat","Klasik düzen","Geleneksel sanata başkaldırı","Portre geleneği"]'::jsonb, 2, 'sanat'),
('Marcel Duchamp''ın "hazır nesne" yaklaşımı ne demektir?', '["Kolaj","Mermer yontmak","Fresk yapmak","Sıradan nesneyi sanat eseri ilan etmek"]'::jsonb, 3, 'sanat'),
('Salvador Dali hangi akımın sanatçısıdır?', '["Sürrealizm","Kübizm","Fovizm","Barok"]'::jsonb, 0, 'sanat'),
('Rene Magritte''in eserlerinde öne çıkan özellik nedir?', '["Fotogerçekçilik","Şaşırtıcı imge birleşimleri","Pointilizm","Fresk"]'::jsonb, 1, 'sanat'),
('Soyut sanatta neyin temsili terk edilir?', '["Doku","Renk","Nesnenin görünür biçimi","Kompozisyon"]'::jsonb, 2, 'sanat'),
('Wassily Kandinsky hangi alanın öncülerindendir?', '["Fresk","Fotogerçekçilik","Barok heykel","Soyut resim"]'::jsonb, 3, 'sanat'),
('Piet Mondrian''ın resimlerinde ne öne çıkar?', '["Dik açılar ve ana renkler","Kıvrımlı formlar","Doğa manzarası","Portre"]'::jsonb, 0, 'sanat'),
('Bauhaus neyi savunmuştur?', '["Yalnız resmi","Sanat ile tasarım-üretim birliğini","Yalnız heykeli","Yalnız müziği"]'::jsonb, 1, 'sanat'),
('Soyut dışavurumculuk hangi ülkede güçlenmiştir?', '["İspanya","İtalya","ABD","Rusya"]'::jsonb, 2, 'sanat'),
('Jackson Pollock hangi teknikle tanınır?', '["Gravür","Fresk","Mozaik","Damlatma (dripping)"]'::jsonb, 3, 'sanat'),
('Pop art hangi kaynaklardan beslenir?', '["Popüler kültür ve reklam","Antik mitoloji","Dinî ikonografi","Doğa manzarası"]'::jsonb, 0, 'sanat'),
('Andy Warhol''un ünlü konularından biri nedir?', '["Antik tanrılar","Konserve kutuları","Buzullar","Uzay gemileri"]'::jsonb, 1, 'sanat'),
('Roy Lichtenstein hangi görsel dili kullanmıştır?', '["Minyatür","Fresk","Çizgi roman estetiği","Mozaik"]'::jsonb, 2, 'sanat'),
('Minimalizm neyi amaçlar?', '["Bol renk","Aşırı süsleme","Anlatısal karmaşa","Az öğeyle yalın anlatım"]'::jsonb, 3, 'sanat'),
('Kavramsal sanatta öncelik nedir?', '["Fikir","Malzeme","Boyut","Fiyat"]'::jsonb, 0, 'sanat'),
('Performans sanatında ana malzeme nedir?', '["Mermer","Sanatçının bedeni ve eylemi","Tuval","Kil"]'::jsonb, 1, 'sanat'),
('Enstalasyon (yerleştirme) nedir?', '["Baskı","Tek tuval","Mekâna kurgulanan üç boyutlu iş","Fotoğraf albümü"]'::jsonb, 2, 'sanat'),
('Land art nerede üretilir?', '["Bilgisayarda","Müze deposunda","Stüdyoda yalnızca","Doğal arazide"]'::jsonb, 3, 'sanat'),
('Video art hangi aracı kullanır?', '["Hareketli görüntü","Mermer","Yağlıboya","Kil"]'::jsonb, 0, 'sanat'),
('Dijital sanatta eser hangi ortamda üretilir?', '["Fresk duvarı","Bilgisayar ortamı","Taş ocağı","Dokuma tezgâhı"]'::jsonb, 1, 'sanat'),
('Grafik tasarımın temel amacı nedir?', '["Bina inşa etmek","Heykel yapmak","Görsel iletişim kurmak","Beste yapmak"]'::jsonb, 2, 'sanat'),
('Tipografi neyle ilgilenir?', '["Işık","Renk kimyası","Heykel","Yazı karakterlerinin düzeni"]'::jsonb, 3, 'sanat'),
('Logo tasarımında aranan özellik nedir?', '["Akılda kalıcılık ve sadelik","Karmaşıklık","Uzun metin","Çok renk zorunluluğu"]'::jsonb, 0, 'sanat'),
('Amblem ile logo arasındaki fark nedir?', '["Fark yoktur","Amblem simge, logo yazı ağırlıklıdır","Amblem renklidir","Logo çizimdir"]'::jsonb, 1, 'sanat'),
('Afiş tasarımının işlevi nedir?', '["Depolamak","Uzun metin sunmak","Kısa sürede mesaj iletmek","Ölçmek"]'::jsonb, 2, 'sanat'),
('Endüstriyel tasarımın konusu nedir?', '["Opera","Tek tuval","Fresk","Seri üretilecek ürünler"]'::jsonb, 3, 'sanat'),
('İç mimarlık neyle ilgilenir?', '["Mekânın iç düzenlemesi","Yol yapımı","Köprü statiği","Baraj"]'::jsonb, 0, 'sanat'),
('Mimaride "cephe" ne demektir?', '["Çatı katı","Yapının dış yüzü","Bodrum","Merdiven"]'::jsonb, 1, 'sanat'),
('Gotik mimarinin belirgin öğesi nedir?', '["Düz çatı","Yuvarlak kubbe","Sivri kemer","Sütunsuz duvar"]'::jsonb, 2, 'sanat'),
('Gotik katedrallerde ağırlığı taşımak için kullanılan öğe nedir?', '["Kum torbası","Kalkan duvar","Ahşap kiriş","Payanda"]'::jsonb, 3, 'sanat'),
('Romanesk mimaride kemer biçimi nasıldır?', '["Yuvarlak","Sivri","Kırık","At nalı zorunlu"]'::jsonb, 0, 'sanat'),
('Klasik Yunan mimarisinde sütun düzenlerinden biri hangisidir?', '["Gotik","Dor","Barok","Rokoko"]'::jsonb, 1, 'sanat'),
('İyon sütun başlığının özelliği nedir?', '["Düz blok","Yaprak bezeme","Kıvrımlı volütler","Hayvan figürü"]'::jsonb, 2, 'sanat'),
('Korint sütun başlığında ne bulunur?', '["Zincir motifi","Volüt yalnızca","Düz yüzey","Akantus yaprakları"]'::jsonb, 3, 'sanat'),
('Osmanlı mimarisinde kubbeyi taşıyan geçiş öğesi nedir?', '["Pandantif ve tromp","Payanda","Sütun başlığı","Saçak"]'::jsonb, 0, 'sanat'),
('Mimar Sinan''ın ustalık eseri olarak tanımladığı yapı hangisidir?', '["Süleymaniye Camii","Selimiye Camii","Şehzade Camii","Mihrimah Camii"]'::jsonb, 1, 'sanat'),
('Mimar Sinan''ın kalfalık eseri olarak andığı yapı hangisidir?', '["Şehzade Camii","Selimiye Camii","Süleymaniye Camii","Rüstem Paşa"]'::jsonb, 2, 'sanat'),
('Mimar Sinan''ın çıraklık eseri olarak andığı yapı hangisidir?', '["Sokollu Camii","Selimiye Camii","Süleymaniye Camii","Şehzade Camii"]'::jsonb, 3, 'sanat'),
('Cami mimarisinde "mihrap" ne işe yarar?', '["Kıble yönünü göstermek","Ezan okumak","Su tutmak","Kitap saklamak"]'::jsonb, 0, 'sanat'),
('Camide "minber" ne için kullanılır?', '["Abdest almak","Hutbe okumak","Kitap koymak","Işık vermek"]'::jsonb, 1, 'sanat'),
('Medrese yapılarının işlevi neydi?', '["Ticaret","Konaklama yalnızca","Eğitim","Savunma"]'::jsonb, 2, 'sanat'),
('Türk mimarisinde "şadırvan" ne işe yarar?', '["Depolamak","Isınmak","Aydınlatmak","Abdest almak"]'::jsonb, 3, 'sanat'),
('Süsleme sanatlarında "rumi" motifi neye dayanır?', '["Stilize hayvan formları","Geometrik kare","Yazı","İnsan portresi"]'::jsonb, 0, 'sanat'),
('"Hatayi" motifi neye dayanır?', '["Hayvan figürü","Stilize bitkisel form","Geometrik yıldız","Harf"]'::jsonb, 1, 'sanat'),
('Türk süslemesinde "mukarnas" nerede kullanılır?', '["Bahçede","Zeminde","Kubbe ve taç kapı geçişlerinde","Duvar dibinde"]'::jsonb, 2, 'sanat'),
('Müzelerin temel işlevi nedir?', '["Eser yok etmek","Eser satmak","Eser üretmek","Eserleri korumak ve sergilemek"]'::jsonb, 3, 'sanat'),
('Restorasyon ne demektir?', '["Eseri özgün haline uygun onarmak","Yeniden yapmak","Yıkmak","Boyamak"]'::jsonb, 0, 'sanat'),
('Konservasyon neyi amaçlar?', '["Eseri değiştirmek","Eserin bozulmasını önlemek","Eseri satmak","Eseri kopyalamak"]'::jsonb, 1, 'sanat'),
('Bir eserin sahteciliğini belirlemede kullanılan yöntemlerden biri nedir?', '["Seyirci oylaması","Fiyat karşılaştırma","Malzeme analizi","Reklam"]'::jsonb, 2, 'sanat'),
('Küratörün görevi nedir?', '["Çerçeve yapmak","Eseri boyamak","Bilet kesmek","Sergiyi kurgulamak"]'::jsonb, 3, 'sanat'),
('Bienal ne demektir?', '["İki yılda bir düzenlenen sanat etkinliği","Yıllık festival","Aylık sergi","Haftalık gösteri"]'::jsonb, 0, 'sanat'),
('Retrospektif sergi neyi sunar?', '["Tek eseri","Bir sanatçının uzun dönem işlerini","Yeni sanatçıları","Yalnız fotoğrafı"]'::jsonb, 1, 'sanat'),
('Sanat eserinde "özgünlük" ne anlama gelir?', '["Büyük olması","Pahalı olması","Kopya olmaması","Eski olması"]'::jsonb, 2, 'sanat'),
('Fotoğrafta "diyafram" neyi ayarlar?', '["Odak uzaklığını","Sesi","Rengi yalnızca","Işık miktarını ve alan derinliğini"]'::jsonb, 3, 'sanat'),
('Fotoğrafta "enstantane" neyi belirler?', '["Poz süresini","Renk sıcaklığını","Lens çapını","Dosya adını"]'::jsonb, 0, 'sanat'),
('Fotoğrafta ISO değeri neyi gösterir?', '["Odak mesafesini","Işığa duyarlılığı","Kare oranını","Ses seviyesini"]'::jsonb, 1, 'sanat'),
('Fotoğrafta "alan derinliği" nedir?', '["Poz süresi","Renk sayısı","Net görünen alanın genişliği","Kadraj oranı"]'::jsonb, 2, 'sanat'),
('Fotoğrafta "kadraj" ne demektir?', '["Renk profili","Baskı boyutu","Işık ölçümü","Çerçeveleme"]'::jsonb, 3, 'sanat'),
('Üçte bir kuralı neyle ilgilidir?', '["Kompozisyon","Renk kimyası","Baskı","Odak"]'::jsonb, 0, 'sanat'),
('Siyah-beyaz fotoğrafta neye dikkat edilir?', '["Renk doygunluğu","Ton ve kontrast","Beyaz dengesi yalnızca","Renk profili"]'::jsonb, 1, 'sanat'),
('Portre fotoğrafında genelde hangi ışık tercih edilir?', '["Karanlık","Sert flaş zorunlu","Yumuşak ışık","Renkli lazer"]'::jsonb, 2, 'sanat'),
('Sinema ve fotoğrafta "altın saat" nedir?', '["Sabah 10","Öğle güneşi","Gece yarısı","Gün doğumu ve batımına yakın ışık"]'::jsonb, 3, 'sanat'),
('Tiyatroda sahne tasarımının amacı nedir?', '["Oyunun mekânını kurmak","Bilet satmak","Metin yazmak","Işık kesmek"]'::jsonb, 0, 'sanat'),
('Sahne ışıklandırmasının işlevlerinden biri nedir?', '["Sesi artırmak","Atmosfer yaratmak","Kostüm dikmek","Metin yazmak"]'::jsonb, 1, 'sanat'),
('Kostüm tasarımı neye hizmet eder?', '["Bilet fiyatına","Ses düzenine","Karakteri görsel olarak anlatmak","Sahne süresine"]'::jsonb, 2, 'sanat'),
('Modern dansın klasik baleden farkı nedir?', '["Kostümsüzlük","Daha katı kurallar","Müziksizlik zorunlu","Serbest hareket dili"]'::jsonb, 3, 'sanat'),
('Opera hangi sanatları birleştirir?', '["Müzik ve tiyatro","Resim ve heykel","Mimari ve dans","Fotoğraf ve baskı"]'::jsonb, 0, 'sanat'),
('Halk dansları neyi yansıtır?', '["Bilimsel veriyi","Yerel kültürü","Ticareti","Askerî düzeni"]'::jsonb, 1, 'sanat'),
('"Zeybek" hangi bölgeyle özdeşleşmiştir?', '["Doğu Anadolu","Karadeniz","Ege","Marmara"]'::jsonb, 2, 'sanat'),
('"Halay" hangi bölgede yaygındır?', '["Trakya","Karadeniz","Ege","Güneydoğu ve Doğu Anadolu"]'::jsonb, 3, 'sanat'),
('Sanat eleştirisinde "biçim" neyi kapsar?', '["Çizgi, renk, kompozisyon","Fiyat","Sanatçının yaşı","Sergi tarihi"]'::jsonb, 0, 'sanat'),
('Sanatta "içerik" ne demektir?', '["Boya markası","Eserin anlattığı anlam","Çerçeve","Ölçü"]'::jsonb, 1, 'sanat'),
('İkonografi neyi inceler?', '["Tuval dokusunu","Boya kimyasını","İmgelerin anlamını","Fiyatları"]'::jsonb, 2, 'sanat'),
('Estetik hangi soruyla ilgilenir?', '["Ağırlık nedir","Kâr nedir","Hız nedir","Güzel nedir"]'::jsonb, 3, 'sanat'),
('Bir eserin "orijinal boyutu" neden önemlidir?', '["Algıyı ve etkiyi değiştirir","Fiyatı sabitler","Rengi belirler","Adı belirler"]'::jsonb, 0, 'sanat'),
('Sanat akımlarının ortaya çıkışında etkili olan temel etken nedir?', '["Rastlantı","Toplumsal ve düşünsel değişim","Hava durumu","Nüfus sayımı"]'::jsonb, 1, 'sanat'),
('Duvar resmi (mural) nerede yapılır?', '["Kâğıtta","Tuval üzerinde","Duvar yüzeyinde","Camda"]'::jsonb, 2, 'sanat'),
('Grafiti sanatının yaygın mekânı neresidir?', '["Kütüphane rafı","Müze deposu","Kilise tavanı","Kentsel yüzeyler"]'::jsonb, 3, 'sanat'),
('Çizgi roman hangi iki öğeyi birleştirir?', '["Görsel ve metin","Ses ve koku","Işık ve gölge yalnızca","Renk ve müzik"]'::jsonb, 0, 'sanat'),
('İllüstrasyon ne işe yarar?', '["Bina çizmek","Metni görselle desteklemek","Ses düzenlemek","Ölçüm yapmak"]'::jsonb, 1, 'sanat'),
('Animasyonda hareket nasıl elde edilir?', '["Ses efekti","Tek kare","Ardışık karelerin hızlı gösterimi","Işık patlaması"]'::jsonb, 2, 'sanat'),
('Stop-motion tekniğinde ne yapılır?', '["Ses eklenir","Çizim taranır","Video hızlandırılır","Nesneler kare kare hareket ettirilir"]'::jsonb, 3, 'sanat'),
('Storyboard ne işe yarar?', '["Sahneleri önceden görselleştirmek","Bilet basmak","Işık ölçmek","Kostüm dikmek"]'::jsonb, 0, 'sanat'),
('Moda tasarımında "koleksiyon" ne demektir?', '["Tek parça","Bir tema etrafındaki ürün dizisi","Kumaş adı","Dikiş türü"]'::jsonb, 1, 'sanat'),
('Takı tasarımında sık kullanılan değerli metal hangisidir?', '["Kurşun","Demir","Altın","Çinko"]'::jsonb, 2, 'sanat'),
('Cam üfleme tekniğinde cam nasıl şekillendirilir?', '["Örülerek","Soğuk kesilerek","Dökülerek yalnızca","Isıtılıp üflenerek"]'::jsonb, 3, 'sanat'),
('Bakır işlemeciliğinde uygulanan teknik nedir?', '["Dövme ve kazıma","Dokuma","Pişirme","Üfleme"]'::jsonb, 0, 'sanat'),
('Deri işlemeciliğinde eserin dayanıklılığı neye bağlıdır?', '["Renk seçimine","Tabaklama işlemine","Boyuta","Desene"]'::jsonb, 1, 'sanat'),
('Sanat terapisinin amacı nedir?', '["Sergi açmak","Eser satmak","Sanat yoluyla ruhsal iyileşmeye destek","Ödül almak"]'::jsonb, 2, 'sanat'),
('Sanat eğitiminde "atölye" ne sağlar?', '["Depolama","Teori dersi yalnızca","Sınav salonu","Uygulamalı üretim ortamı"]'::jsonb, 3, 'sanat'),
('Bir sanatçının "üslubu" nedir?', '["Kendine özgü anlatım biçimi","Doğum yeri","Eser sayısı","Fiyatı"]'::jsonb, 0, 'sanat'),
('Sanatta "esin (ilham)" ne anlama gelir?', '["Boya türü","Yaratıcı fikri tetikleyen kaynak","Sergi salonu","Ödül"]'::jsonb, 1, 'sanat'),
('Bir müzede eserin yanındaki bilgi etiketine ne denir?', '["Afiş","Katalog","Künye","Broşür"]'::jsonb, 2, 'sanat'),
('Sanat eserinin telif hakkı kime aittir?', '["Devlete her zaman","Müzeye","Ziyaretçiye","Eseri yaratan sanatçıya"]'::jsonb, 3, 'sanat'),
('Bir eserin çoğaltılmış sınırlı sayıdaki baskısına ne denir?', '["Edisyon","Orijinal","Eskiz","Maket"]'::jsonb, 0, 'sanat'),
('Eskiz ne demektir?', '["Bitmiş eser","Ön çalışma çizimi","Çerçeve","Sergi"]'::jsonb, 1, 'sanat'),
('Maket neyi temsil eder?', '["Boya","Bitmiş yapı","Küçültülmüş model","Fotoğraf"]'::jsonb, 2, 'sanat'),
('Sanatta "natürmort" ne anlamına gelir?', '["Savaş sahnesi","Portre","Manzara","Cansız nesne resmi"]'::jsonb, 3, 'sanat'),
('"Portre" neyin resmidir?', '["Kişinin","Manzaranın","Nesnenin","Olayın"]'::jsonb, 0, 'sanat'),
('"Manzara" resminde konu nedir?', '["İnsan yüzü","Doğa görünümü","Meyve tabağı","Mimari plan"]'::jsonb, 1, 'sanat'),
('"Otoportre" ne demektir?', '["Grup resmi","Aile portresi","Sanatçının kendi portresi","Manzara"]'::jsonb, 2, 'sanat'),
('Sanatta "triptik" nedir?', '["Dört panel","Tek panel","İki panel","Üç panelli eser"]'::jsonb, 3, 'sanat'),
('Resimde "şase" nedir?', '["Tuvalin gerildiği çerçeve","Boya kutusu","Fırça sapı","Sergi standı"]'::jsonb, 0, 'sanat'),
('Tuval üzerine astar sürmenin amacı nedir?', '["Rengi değiştirmek","Boyanın tutunmasını sağlamak","Ağırlık eklemek","Koku vermek"]'::jsonb, 1, 'sanat'),
('Palet ne işe yarar?', '["Çerçeve yapmak","Tuval germek","Boyaları karıştırmak","Fırça temizlemek"]'::jsonb, 2, 'sanat'),
('Vernik neden sürülür?', '["Ölçmek","Rengi silmek","Ağırlaştırmak","Yüzeyi korumak ve parlaklık vermek"]'::jsonb, 3, 'sanat'),
('Sanat tarihinde "avangart" ne demektir?', '["Öncü ve yenilikçi","Geleneksel","Ticari","Amatör"]'::jsonb, 0, 'sanat'),

-- ===================== SİNEMA (100) =====================
('Sinemada "yönetmen" ne yapar?', '["Bilet satar","Filmin sanatsal yönetimini üstlenir","Işık taşır","Kostüm diker"]'::jsonb, 1, 'sinema'),
('Senarist ne üretir?', '["Dekor","Müzik","Senaryo","Afiş"]'::jsonb, 2, 'sinema'),
('Görüntü yönetmeninin sorumluluğu nedir?', '["Dağıtım","Oyunculuk","Kurgu","Kamera ve ışık"]'::jsonb, 3, 'sinema'),
('Kurgucu (montajcı) ne yapar?', '["Çekimleri birleştirip düzenler","Senaryo yazar","Set kurar","Oyuncu seçer"]'::jsonb, 0, 'sinema'),
('Yapımcının temel görevi nedir?', '["Kamera kullanmak","Filmin finansman ve organizasyonu","Rol oynamak","Kurgu yapmak"]'::jsonb, 1, 'sinema'),
('Sinemada "plan" ne demektir?', '["Afiş","Senaryo bölümü","Kesintisiz çekilen görüntü parçası","Fragman"]'::jsonb, 2, 'sinema'),
('"Sahne" ne anlama gelir?', '["Jenerik","Tek kare","Film müziği","Aynı mekân ve zamandaki planlar bütünü"]'::jsonb, 3, 'sinema'),
('"Sekans" nedir?', '["Anlamlı bir bütün oluşturan sahneler dizisi","Tek plan","Ses efekti","Poster"]'::jsonb, 0, 'sinema'),
('Genel plan ne gösterir?', '["Yalnız gözü","Geniş çevreyi ve konumu","Yalnız eli","Yalnız sesi"]'::jsonb, 1, 'sinema'),
('Yakın plan neyi vurgular?', '["Kalabalık","Mekân genişliği","Yüz ifadesi ve ayrıntı","Manzara"]'::jsonb, 2, 'sinema'),
('Omuz üstü çekim genellikle neyi gösterir?', '["Gökyüzünü","Manzarayı","Kalabalığı","Diyalog kuran iki kişiyi"]'::jsonb, 3, 'sinema'),
('"Travelling" çekimi nedir?', '["Kameranın hareket ederek çekmesi","Sabit çekim","Zoom","Kesme"]'::jsonb, 0, 'sinema'),
('"Pan" hareketi nedir?', '["Dikey kaydırma","Kameranın yatay dönüşü","İleri gitme","Odak değişimi"]'::jsonb, 1, 'sinema'),
('"Tilt" hareketi nedir?', '["Zoom","Yatay dönüş","Kameranın dikey dönüşü","Kesme"]'::jsonb, 2, 'sinema'),
('Steadicam ne sağlar?', '["Işık","Sabit tripod","Ses kaydı","Titreşimsiz hareketli çekim"]'::jsonb, 3, 'sinema'),
('Sinemada "kesme" (cut) ne demektir?', '["İki plan arasında ani geçiş","Yavaş geçiş","Karartma","Donma"]'::jsonb, 0, 'sinema'),
('"Zincirleme" (dissolve) geçiş nasıldır?', '["Ani kesme","Bir görüntü diğerine erir","Kararma","Donma"]'::jsonb, 1, 'sinema'),
('"Fade out" ne anlama gelir?', '["Hızlanma","Ani kesme","Görüntünün karararak kaybolması","Yavaşlama"]'::jsonb, 2, 'sinema'),
('"Flashback" ne demektir?', '["Hızlı çekim","Geleceğe sıçrama","Yavaş çekim","Geçmişe dönüş"]'::jsonb, 3, 'sinema'),
('"Flashforward" ne anlatır?', '["İleriye sıçrama","Geçmişe dönüş","Donma","Kesme"]'::jsonb, 0, 'sinema'),
('Sinemada "montaj" neyi belirler?', '["Bilet fiyatını","Anlatının ritmini ve akışını","Afişi","Vizyon tarihini"]'::jsonb, 1, 'sinema'),
('"Kurgu" olmadan tek planda çekilen filme ne denir?', '["Kısa film","Belgesel","Tek plan (uzun plan) filmi","Animasyon"]'::jsonb, 2, 'sinema'),
('Sinemada "mizansen" ne demektir?', '["Dağıtım planı","Ses miksajı","Afiş tasarımı","Sahne içindeki her şeyin düzenlenmesi"]'::jsonb, 3, 'sinema'),
('Filmde "jenerik" ne içerir?', '["Emeği geçenlerin listesi","Fragman","Eleştiri","Bilet"]'::jsonb, 0, 'sinema'),
('Fragman ne işe yarar?', '["Filmi bitirmek","Filmi tanıtmak","Kurgu yapmak","Senaryo yazmak"]'::jsonb, 1, 'sinema'),
('Film müziği (score) ne sağlar?', '["Kurgu hızı","Görüntü netliği","Duygusal atmosfer","Işık"]'::jsonb, 2, 'sinema'),
('Sinemada "ses miksajı" nedir?', '["Afiş","Görüntü rengi","Kamera açısı","Ses katmanlarının dengelenmesi"]'::jsonb, 3, 'sinema'),
('"Dublaj" ne demektir?', '["Sesin sonradan kaydedilip eklenmesi","Altyazı","Kurgu","Işıklandırma"]'::jsonb, 0, 'sinema'),
('Altyazının işlevi nedir?', '["Ses seviyesini artırmak","Konuşmaları yazıyla aktarmak","Görüntüyü büyütmek","Renk vermek"]'::jsonb, 1, 'sinema'),
('Sinemada "kadraj" ne anlama gelir?', '["Süre","Ses düzeyi","Görüntünün çerçevelenmesi","Bütçe"]'::jsonb, 2, 'sinema'),
('"Alan derinliği" sinemada neyi etkiler?', '["Bilet fiyatını","Ses tonunu","Film süresini","Netlik alanının genişliğini"]'::jsonb, 3, 'sinema'),
('Yeşil perde (green screen) ne için kullanılır?', '["Arka planı sonradan değiştirmek","Ses kaydı","Işık ölçümü","Kostüm"]'::jsonb, 0, 'sinema'),
('CGI ne anlama gelir?', '["Kamera markası","Bilgisayarla üretilen görüntü","Ses formatı","Bilet sistemi"]'::jsonb, 1, 'sinema'),
('"Motion capture" nedir?', '["Işık kaydı","Ses kaydı","Oyuncunun hareketlerinin dijital kaydı","Renk kaydı"]'::jsonb, 2, 'sinema'),
('Sinemada "storyboard" ne işe yarar?', '["Afiş satmak","Bilet basmak","Ses kesmek","Çekimleri önceden çizmek"]'::jsonb, 3, 'sinema'),
('"Casting" ne demektir?', '["Oyuncu seçimi","Set kurulumu","Kurgu","Dağıtım"]'::jsonb, 0, 'sinema'),
('Figüran ne yapar?', '["Başrol oynar","Arka planda yer alır","Yönetir","Kurgular"]'::jsonb, 1, 'sinema'),
('Dublör ne yapar?', '["Işık tutar","Ses verir","Tehlikeli sahneleri oynar","Yazar"]'::jsonb, 2, 'sinema'),
('"Post prodüksiyon" hangi aşamadır?', '["Dağıtım öncesi bilet","Çekim öncesi","Çekim sırası","Çekim sonrası işler"]'::jsonb, 3, 'sinema'),
('"Pre prodüksiyon" hangi aşamadır?', '["Çekim öncesi hazırlık","Çekim sonrası","Vizyon","Festival"]'::jsonb, 0, 'sinema'),
('Belgesel filmin temel amacı nedir?', '["Kurgu yaratmak","Gerçekliği aktarmak","Reklam yapmak","Animasyon üretmek"]'::jsonb, 1, 'sinema'),
('Kısa filmin ayırt edici özelliği nedir?', '["Sessiz olması","Renkli olması","Kısa süresi","Belgesel olması"]'::jsonb, 2, 'sinema'),
('Animasyon filmde görüntü nasıl üretilir?', '["Fotoğrafla yalnızca","Doğrudan kamerayla","Ses kaydıyla","Kare kare oluşturularak"]'::jsonb, 3, 'sinema'),
('Sinemada "tür" (janr) ne demektir?', '["Filmin kategorisi","Kamera açısı","Ses formatı","Süre"]'::jsonb, 0, 'sinema'),
('Korku türünün amacı nedir?', '["Güldürmek","Gerilim ve korku yaratmak","Bilgi vermek","Dans ettirmek"]'::jsonb, 1, 'sinema'),
('Komedi türünün amacı nedir?', '["Ağlatmak","Korkutmak","Güldürmek","Belgelemek"]'::jsonb, 2, 'sinema'),
('Bilim kurgu türü neye dayanır?', '["Spor","Tarihî belge","Günlük hayat","Bilimsel varsayımlar ve gelecek"]'::jsonb, 3, 'sinema'),
('Western türünün klasik mekânı neresidir?', '["Amerikan Batısı","Antik Roma","Uzay","Okyanus"]'::jsonb, 0, 'sinema'),
('Film noir''in görsel özelliği nedir?', '["Parlak renkler","Karanlık ve gölgeli atmosfer","Animasyon","Belgesel çekim"]'::jsonb, 1, 'sinema'),
('Gerilim (thriller) türünde öne çıkan öğe nedir?', '["Dans","Kahkaha","Merak ve tempo","Belgesellik"]'::jsonb, 2, 'sinema'),
('Sinemanın icadıyla anılan kardeşler kimlerdir?', '["Wachowski Kardeşler","Warner Kardeşler","Coen Kardeşler","Lumiere Kardeşler"]'::jsonb, 3, 'sinema'),
('İlk halka açık film gösterimleri hangi yüzyılın sonunda yapılmıştır?', '["19. yüzyıl","17. yüzyıl","20. yüzyıl ortası","18. yüzyıl"]'::jsonb, 0, 'sinema'),
('Sessiz sinema döneminde anlatım neye dayanırdı?', '["Diyalog sesi","Görüntü ve ara yazılar","Dublaj","Altyazı"]'::jsonb, 1, 'sinema'),
('Charlie Chaplin hangi dönemin ikonudur?', '["Dijital çağ","3D sinema","Sessiz sinema","Sesli belgesel"]'::jsonb, 2, 'sinema'),
('Chaplin''in ünlü karakteri hangisidir?', '["Tarzan","Sherlock","Zorro","Şarlo"]'::jsonb, 3, 'sinema'),
('Buster Keaton hangi türde ünlüdür?', '["Sessiz komedi","Korku","Belgesel","Müzikal"]'::jsonb, 0, 'sinema'),
('Sesli sinemaya geçiş hangi yenilikle olmuştur?', '["Renkli film","Senkron ses kaydı","Geniş perde","3D"]'::jsonb, 1, 'sinema'),
('Alfred Hitchcock hangi türle özdeşleşmiştir?', '["Western","Müzikal","Gerilim","Belgesel"]'::jsonb, 2, 'sinema'),
('Hitchcock''un "Sapık" filmi hangi türdedir?', '["Belgesel","Komedi","Müzikal","Gerilim/korku"]'::jsonb, 3, 'sinema'),
('"Vatandaş Kane" filminin yönetmeni kimdir?', '["Orson Welles","John Ford","Howard Hawks","Billy Wilder"]'::jsonb, 0, 'sinema'),
('İtalyan Yeni Gerçekçiliği neyi öne çıkarır?', '["Stüdyo görkemi","Sokakta çekim ve gerçek yaşam","Fantastik kurgu","Animasyon"]'::jsonb, 1, 'sinema'),
('"Bisiklet Hırsızları" hangi akıma örnektir?', '["Alman Dışavurumculuğu","Fransız Yeni Dalgası","İtalyan Yeni Gerçekçiliği","Dogma 95"]'::jsonb, 2, 'sinema'),
('Fransız Yeni Dalgası hangi ülkede doğmuştur?', '["Danimarka","İtalya","Almanya","Fransa"]'::jsonb, 3, 'sinema'),
('Jean-Luc Godard hangi akımla anılır?', '["Fransız Yeni Dalgası","İtalyan Yeni Gerçekçiliği","Dogma 95","Yeni Hollywood"]'::jsonb, 0, 'sinema'),
('Alman Dışavurumcu sinemasının görsel özelliği nedir?', '["Doğal ışık","Çarpık dekor ve sert gölgeler","Belgesel çekim","Renk patlaması"]'::jsonb, 1, 'sinema'),
('"Dr. Caligari''nin Muayenehanesi" hangi akıma aittir?', '["Yeni Dalga","Yeni Gerçekçilik","Alman Dışavurumculuğu","Dogma 95"]'::jsonb, 2, 'sinema'),
('Akira Kurosawa hangi ülkenin yönetmenidir?', '["Hindistan","Çin","Kore","Japonya"]'::jsonb, 3, 'sinema'),
('Federico Fellini hangi ülkenin yönetmenidir?', '["İtalya","Fransa","İspanya","Yunanistan"]'::jsonb, 0, 'sinema'),
('Ingmar Bergman hangi ülkenin yönetmenidir?', '["Norveç","İsveç","Danimarka","Finlandiya"]'::jsonb, 1, 'sinema'),
('Andrey Tarkovski hangi ülkenin yönetmenidir?', '["Macaristan","Polonya","Rusya (SSCB)","Çekya"]'::jsonb, 2, 'sinema'),
('Stanley Kubrick''in uzay temalı ünlü filmi hangisidir?', '["Interstellar","Yıldız Savaşları","Arrival","2001: Bir Uzay Destanı"]'::jsonb, 3, 'sinema'),
('Martin Scorsese hangi ülkenin yönetmenidir?', '["ABD","İtalya","İngiltere","Kanada"]'::jsonb, 0, 'sinema'),
('Steven Spielberg''in bilim kurgu klasiklerinden biri hangisidir?', '["Matrix","E.T.","Alien","Blade Runner"]'::jsonb, 1, 'sinema'),
('"Jurassic Park" hangi türdedir?', '["Müzikal","Belgesel","Bilim kurgu/macera","Western"]'::jsonb, 2, 'sinema'),
('"Yıldız Savaşları" serisinin yaratıcısı kimdir?', '["Ridley Scott","Steven Spielberg","James Cameron","George Lucas"]'::jsonb, 3, 'sinema'),
('"Titanik" ve "Avatar" filmlerinin yönetmeni kimdir?', '["James Cameron","Ridley Scott","Peter Jackson","Christopher Nolan"]'::jsonb, 0, 'sinema'),
('"Alien" ve "Blade Runner" filmlerinin yönetmeni kimdir?', '["James Cameron","Ridley Scott","George Lucas","David Fincher"]'::jsonb, 1, 'sinema'),
('Christopher Nolan''ın rüya temalı filmi hangisidir?', '["Arrival","Gravity","Inception","Looper"]'::jsonb, 2, 'sinema'),
('Quentin Tarantino''nun anlatı özelliği nedir?', '["Animasyon","Belgesel çekim","Sessiz sinema","Doğrusal olmayan kurgu"]'::jsonb, 3, 'sinema'),
('Pixar hangi alanda öncüdür?', '["Bilgisayar animasyonu","Sessiz film","Belgesel","Western"]'::jsonb, 0, 'sinema'),
('"Oyuncak Hikâyesi" hangi açıdan öncüdür?', '["İlk sesli film","İlk tam bilgisayar animasyonu uzun metraj","İlk renkli film","İlk 3D film"]'::jsonb, 1, 'sinema'),
('Studio Ghibli hangi ülkenin animasyon stüdyosudur?', '["Çin","Kore","Japonya","ABD"]'::jsonb, 2, 'sinema'),
('Hayao Miyazaki hangi alanda ünlüdür?', '["Müzikal","Belgesel","Western","Animasyon yönetmenliği"]'::jsonb, 3, 'sinema'),
('Cannes''da verilen büyük ödül hangisidir?', '["Altın Palmiye","Altın Ayı","Altın Aslan","Oscar"]'::jsonb, 0, 'sinema'),
('Oscar ödüllerini veren kurum hangisidir?', '["Cannes","Akademi","UNESCO","FIFA"]'::jsonb, 1, 'sinema'),
('Antalya Altın Portakal hangi ülkenin festivalidir?', '["İtalya","Yunanistan","Türkiye","Mısır"]'::jsonb, 2, 'sinema'),
('Türk sinemasında Yeşilçam ne anlama gelir?', '["Bir ödül","Bir festival","Bir salon zinciri","Klasik dönem Türk sineması"]'::jsonb, 3, 'sinema'),
('Nuri Bilge Ceylan hangi alanda tanınır?', '["Yönetmenlik","Bestecilik","Oyunculuk yalnızca","Kurgu yalnızca"]'::jsonb, 0, 'sinema'),
('Yılmaz Güney hangi alanda tanınır?', '["Yalnız besteci","Yönetmen ve oyuncu","Yalnız yapımcı","Yalnız kurgucu"]'::jsonb, 1, 'sinema'),
('Sinemada "gişe" ne demektir?', '["Set alanı","Kurgu odası","Filmin bilet hasılatı","Ses kabini"]'::jsonb, 2, 'sinema'),
('Bir filmin "vizyona girmesi" ne demektir?', '["Yazılması","Çekime başlaması","Kurgulanması","Sinemalarda gösterime başlaması"]'::jsonb, 3, 'sinema'),
('"Remake" ne anlama gelir?', '["Bir filmin yeniden çevrimi","Devam filmi","Ön hikâye","Belgesel"]'::jsonb, 0, 'sinema'),
('"Prequel" ne demektir?', '["Devamı","Öncesini anlatan film","Yeniden çevrim","Kısa film"]'::jsonb, 1, 'sinema'),
('"Sequel" ne demektir?', '["Yeniden çevrim","Ön hikâye","Devam filmi","Fragman"]'::jsonb, 2, 'sinema'),
('Sinemada "kült film" ne anlama gelir?', '["Belgesel","En çok hasılat yapan","İlk film","Zamanla sadık hayran kitlesi kazanan film"]'::jsonb, 3, 'sinema'),

-- ===== EK BLOK =====
('Futbolda taç atışı nasıl kullanılır?', '["İki elle baş üstünden","Ayakla vurarak","Dizle","Tek elle"]'::jsonb, 0, 'spor'),
('Futbolda kaleci topu elinde en fazla ne kadar tutabilir (kural gereği sınırlıdır)?', '["Süresiz","Sınırlı bir süre","Bir devre","Yalnız bir saniye"]'::jsonb, 1, 'spor'),
('Futbolda uzatma dakikaları neden eklenir?', '["Skor eşitliği için","Seyirci isteğiyle","Kaybedilen süreyi telafi için","Reklam için"]'::jsonb, 2, 'spor'),
('Futbolda penaltı atışlarında kaleci nerede durmalıdır?', '["Orta sahada","Direk dışında","Ceza sahası dışında","Kale çizgisi üzerinde"]'::jsonb, 3, 'spor'),
('Futbolda "geri pas kuralı" neyi yasaklar?', '["Kalecinin ayakla gelen geri pası elle almasını","Kaleye şut atmayı","Korner kullanmayı","Taç atmayı"]'::jsonb, 0, 'spor'),
('Futbol topunun standart numarası yetişkinlerde kaçtır?', '["3","5","4","7"]'::jsonb, 1, 'spor'),
('Futbolda "asist" ne demektir?', '["Kurtarış","Şut","Gole giden son pas","Faul"]'::jsonb, 2, 'spor'),
('Futbolda kalecinin kurtarışına ne denir?', '["Ofsayt","Asist","Çalım","Kurtarış (save)"]'::jsonb, 3, 'spor'),
('Futbolda maç kaç hakemle yönetilir (saha içinde ana hakem sayısı)?', '["Bir","İki","Üç","Dört"]'::jsonb, 0, 'spor'),
('Futbolda kaleye atılan ve içeri giren toplara ne denir?', '["Korner","Gol","Faul","Taç"]'::jsonb, 1, 'spor'),
('Basketbolda maç FIBA kurallarına göre kaç periyottan oluşur?', '["3","2","4","5"]'::jsonb, 2, 'spor'),
('Basketbolda bir periyot FIBA kurallarına göre kaç dakikadır?', '["8","12","15","10"]'::jsonb, 3, 'spor'),
('Basketbolda "adım hatası" ne demektir?', '["Top sürmeden fazla adım atmak","Faul yapmak","Çift sektirme","Zaman aşımı"]'::jsonb, 0, 'spor'),
('Basketbolda "çift sektirme" ne anlama gelir?', '["Şut atmak","Top sürmeyi bırakıp tekrar başlamak","Pas vermek","Blok yapmak"]'::jsonb, 1, 'spor'),
('Basketbolda hücumun kendi sahasından çıkma süresi kaç saniyedir?', '["10","5","8","3"]'::jsonb, 2, 'spor'),
('Basketbolda pota altında bekleme kuralı kaç saniyedir?', '["10","5","8","3"]'::jsonb, 3, 'spor'),
('Voleybolda topun sahaya değmesiyle ne olur?', '["Rakip sayı alır veya sayı belirlenir","Set biter","Oyun durur","Servis tekrarlanır"]'::jsonb, 0, 'spor'),
('Voleybolda "manşet" nedir?', '["Smaç","Alt paslaşma tekniği","Servis","Blok"]'::jsonb, 1, 'spor'),
('Voleybolda "parmak pas" hangi bölgeyle yapılır?', '["Dirsekle","Bilekle","Parmak uçlarıyla","Omuzla"]'::jsonb, 2, 'spor'),
('Yüzmede start nasıl verilir?', '["Antrenör düdüğüyle","Seyirci sesiyle","Rastgele","Hakem işaretiyle"]'::jsonb, 3, 'spor'),
('Yüzmede kulvar çizgilerinin işlevi nedir?', '["Dalga etkisini azaltmak","Süs","Derinlik ölçmek","Isıtmak"]'::jsonb, 0, 'spor'),
('Serbest stil yüzmede yaygın kullanılan teknik hangisidir?', '["Kurbağalama","Krol","Kelebek","Sırtüstü"]'::jsonb, 1, 'spor'),
('Sırtüstü yüzmede sporcu nasıl konumlanır?', '["Yan","Yüzüstü","Sırt üstü","Dik"]'::jsonb, 2, 'spor'),
('Atletizmde çıkış takozları hangi yarışlarda kullanılır?', '["Uzun mesafe","Maraton","Yürüyüş","Sürat koşuları"]'::jsonb, 3, 'spor'),
('Atletizmde hatalı çıkışa ne denir?', '["Falstart","Diskalifiye zorunlu","Yeniden kura","Ceza turu"]'::jsonb, 0, 'spor'),
('Uzun atlamada sporcu nereye düşer?', '["Mindere","Kum havuzuna","Çime","Suya"]'::jsonb, 1, 'spor'),
('Yüksek atlamada sporcu neyin üzerinden atlar?', '["İp","Engel","Çıta","Duvar"]'::jsonb, 2, 'spor'),
('Disk atmada sporcu hangi alandan atış yapar?', '["Kale önünden","Düz koşu yolundan","Kum havuzundan","Daire içinden"]'::jsonb, 3, 'spor'),
('Çekiç atma hangi tür branştır?', '["Atma","Atlama","Koşu","Yürüyüş"]'::jsonb, 0, 'spor'),
('Boksta sporcuların ellerine ne takılır?', '["Kramp","Eldiven","Bileklik metal","Zincir"]'::jsonb, 1, 'spor'),
('Boksta maçı yöneten kişi kimdir?', '["Antrenör","Kaptan","Ring hakemi","Sekreter"]'::jsonb, 2, 'spor'),
('Güreşte sporcuların üzerinde yarıştığı zemin nedir?', '["Parke","Kum","Buz","Minder"]'::jsonb, 3, 'spor'),
('Güreşte "tuş" ne demektir?', '["Rakibin iki omzunu mindere değdirmek","Puan almak","Çıkış yapmak","Ceza almak"]'::jsonb, 0, 'spor'),
('Taekwondoda puanlar çoğunlukla neyle alınır?', '["Tutuşla","Tekme ve yumruk teknikleriyle","Fırlatmayla","Süreyle"]'::jsonb, 1, 'spor'),
('Eskrimde puan nasıl alınır?', '["Süreyi doldurarak","Rakibi devirerek","Rakibe geçerli bölgeden dokunarak","Sıçrayarak"]'::jsonb, 2, 'spor'),
('Okçulukta yay ile ok arasında gerilen parçaya ne denir?', '["Temren","Sap","Tüy","Kiriş"]'::jsonb, 3, 'spor'),
('Halterde sporcunun kaldırdığı ağırlığa ne denir?', '["Kaldırış","Vuruş","Atış","Sıçrayış"]'::jsonb, 0, 'spor'),
('Bisiklette kask kullanmanın amacı nedir?', '["Hız artırmak","Baş yaralanmasını önlemek","Süs","Ağırlık"]'::jsonb, 1, 'spor'),

('Resimde "kontrast" ne demektir?', '["Simetri","Benzerlik","Karşıtlık","Ritim"]'::jsonb, 2, 'sanat'),
('Sanatta "simetri" neyi ifade eder?', '["Doku","Dağınıklık","Renk uyumu","Eksene göre denklik"]'::jsonb, 3, 'sanat'),
('Kompozisyonda "denge" ne sağlar?', '["Görsel ağırlığın dağılımını","Renk sayısını","Boyut artışını","Işık şiddetini"]'::jsonb, 0, 'sanat'),
('Sanatta "ritim" nasıl oluşur?', '["Tek öğeyle","Öğelerin düzenli tekrarıyla","Renksizlikle","Boşlukla yalnızca"]'::jsonb, 1, 'sanat'),
('Sanatta "doku" ne anlama gelir?', '["Boyut","Renk tonu","Yüzeyin dokunsal ve görsel niteliği","Çerçeve"]'::jsonb, 2, 'sanat'),
('Resimde "negatif alan" nedir?', '["Kontur","Nesnenin kendisi","Gölge","Nesne dışındaki boşluk"]'::jsonb, 3, 'sanat'),
('Renk doygunluğu neyi ifade eder?', '["Rengin canlılık derecesini","Rengin sıcaklığını","Boyut","Doku"]'::jsonb, 0, 'sanat'),
('Akromatik renkler hangileridir?', '["Kırmızı, sarı, mavi","Siyah, beyaz, gri","Yeşil, mor","Turuncu, pembe"]'::jsonb, 1, 'sanat'),
('Ara renk nasıl elde edilir?', '["Beyaz ekleyerek","Tek renkle","İki ana rengin karışımıyla","Siyah ekleyerek"]'::jsonb, 2, 'sanat'),
('Bir renge beyaz eklenirse ne oluşur?', '["Ana renk","Koyu ton","Tamamlayıcı renk","Açık ton"]'::jsonb, 3, 'sanat'),
('Bir renge siyah eklenirse ne oluşur?', '["Koyu ton","Açık ton","Ara renk","Nötr"]'::jsonb, 0, 'sanat'),
('Sanatta "monokrom" ne demektir?', '["Çok renk","Tek renk tonlarıyla çalışma","Renksizlik zorunlu","Baskı tekniği"]'::jsonb, 1, 'sanat'),
('Sanat tarihinde "ikon" ne anlama gelir?', '["Heykel","Fotoğraf","Dinî tasvir resmi","Afiş"]'::jsonb, 2, 'sanat'),
('Bizans sanatında altın zemin neyi simgeler?', '["Toprak","Zenginlik yalnızca","Gökyüzü","Kutsal ışık ve sonsuzluk"]'::jsonb, 3, 'sanat'),
('Mozaikte altın tesseralar hangi dönemde yaygındır?', '["Bizans","Rönesans","Barok","Modern"]'::jsonb, 0, 'sanat'),
('Orta Çağ el yazmalarındaki resimlere ne denir?', '["Fresk","Minyatür","Mozaik","Gravür"]'::jsonb, 1, 'sanat'),
('Rönesans''ta "hümanizm" sanata nasıl yansımıştır?', '["Reklamla","Soyutlamayla","İnsan ve doğaya artan ilgiyle","Endüstriyle"]'::jsonb, 2, 'sanat'),
('Botticelli hangi dönemin ressamıdır?', '["Empresyonizm","Barok","Rokoko","Rönesans"]'::jsonb, 3, 'sanat'),
('Barok heykelin öncü ismi kimdir?', '["Bernini","Michelangelo","Donatello","Rodin"]'::jsonb, 0, 'sanat'),
('Auguste Rodin hangi alanda ünlüdür?', '["Resim","Heykel","Mimarlık","Fotoğraf"]'::jsonb, 1, 'sanat'),
('Constantin Brancusi hangi anlayışla çalışmıştır?', '["Fotogerçekçilik","Barok ayrıntı","Yalın ve soyutlanmış formlar","Kolaj"]'::jsonb, 2, 'sanat'),
('Sanatta "kinetik" ne anlama gelir?', '["Sesli","Sabit","İki boyutlu","Hareket içeren"]'::jsonb, 3, 'sanat'),
('Op art neye dayanır?', '["Optik yanılsama","Reklam imgeleri","Belgesel fotoğraf","Doğa manzarası"]'::jsonb, 0, 'sanat'),
('Fotogerçekçilik neyi hedefler?', '["Soyutlama","Fotoğraf gibi ayrıntılı resim","Kolaj","Lekesel anlatım"]'::jsonb, 1, 'sanat'),
('Arte Povera hangi malzemeleri öne çıkarır?', '["Mermer","Altın","Sıradan ve gündelik malzemeler","Bronz"]'::jsonb, 2, 'sanat'),
('Sanatta "seri üretim" eleştirisi hangi akımda belirgindir?', '["Romanesk","Rönesans","Gotik","Pop art"]'::jsonb, 3, 'sanat'),
('Sanat yapıtında "orijinal" ile "reprodüksiyon" farkı nedir?', '["Reprodüksiyon çoğaltmadır","Aynı şeydir","Orijinal kopyadır","Fark boyuttur"]'::jsonb, 0, 'sanat'),
('Türk resminde ilk kuşak ressamlara ne ad verilir?', '["Saray ressamları","Asker ressamlar","Halk ressamları","Soyutçular"]'::jsonb, 1, 'sanat'),
('Osman Hamdi Bey hangi alanda öne çıkmıştır?', '["Mimarlık","Bestecilik","Ressamlık ve müzecilik","Şairlik"]'::jsonb, 2, 'sanat'),

('Sinemada "senaryo taslağı" neyi içerir?', '["Ses dosyasını","Bilet listesini","Set malzemesini","Hikâyenin yazılı planını"]'::jsonb, 3, 'sinema'),
('Bir filmde "başrol" kimdir?', '["Hikâyenin merkezindeki oyuncu","Yönetmen","Yapımcı","Figüran"]'::jsonb, 0, 'sinema'),
('"Yardımcı rol" ne demektir?', '["Yönetmen yardımcısı","Başrolü destekleyen karakter","Kurgucu","Dublör"]'::jsonb, 1, 'sinema'),
('Sinemada "sesli anlatıcı" (voice-over) nedir?', '["Şarkı","Diyalog","Görüntü dışından duyulan anlatım","Efekt"]'::jsonb, 2, 'sinema'),
('Filmde "efekt sesi" ne sağlar?', '["Altyazıyı","Diyaloğu","Müziği","Ortam ve olay seslerini"]'::jsonb, 3, 'sinema')

on conflict (soru) do nothing;

-- ===================== KARIŞTIRMA =====================
-- Doğru cevap hep aynı şıkta olmasın: SADECE bu partide eklenen soruların
-- şıkları karıştırılır. `created_at >= transaction_timestamp()` koşulu
-- ZORUNLUDUR; onsuz tüm havuzun şıkları karışır ve o an oynanan maçlarda
-- şık indeksleri kayar.
with karisik as (
  select q.id,
         jsonb_agg(s.value order by s.rnd) as yeni_secenekler,
         (array_position(array_agg(s.idx order by s.rnd), q.dogru_cevap::int) - 1)::smallint as yeni_dogru
  from public.questions q
  cross join lateral (
    select value, (ordinality - 1)::int as idx, random() as rnd
    from jsonb_array_elements(q.secenekler) with ordinality
  ) s
  where q.created_at >= transaction_timestamp()
  group by q.id, q.dogru_cevap
)
update public.questions q
   set secenekler = k.yeni_secenekler,
       dogru_cevap = k.yeni_dogru
  from karisik k
 where q.id = k.id;
